- api.planx.uk/gis/digitalLand.js
- api.planx.uk/gis/local_authorities/metadata/doncaster.js
https://docs.google.com/spreadsheets/d/1W72w2oEii7OeAUBkP8ya9ipMxD3m-PNmmZPiusKAOfA/edit#gid=0
Example address that picks up article4.doncaster.hmo passport variable: 121 Thorne Rd, Doncaster DN2 5BQ
> feat: GIS API returns granular Article 4 values for Doncaster

- api.planx.uk/server.js
see thread https://opensystemslab.slack.com/archives/C0405SQDP8B/p1663263727756039
we are logging pay notifications regardless of payment status, and we pushed a manual submission for a failed payment.
https://docs.payments.service.gov.uk/api_reference/#payment-status-meanings
> fix: add status to pay notifications

- .github/workflows/pull-request-main.yml
Fixes issue where only Storybook build was getting passed to Vultr, as a result of [the recent parallelization of CI jobs ](https://github.com/theopensystemslab/planx-new/pull/1154)
I've tried a few (now squashed) commits on this branch to make sure the cache is behaving as expected 👍
> fix(ci): Use unique keys for React and Storybook build cache

- api.planx.uk/saveAndReturn/sendEmail.js
- api.planx.uk/saveAndReturn/sendEmail.test.js
- api.planx.uk/saveAndReturn/utils.js
- hasura.planx.uk/metadata/tables.yaml
- hasura.planx.uk/migrations/1664529923804_alter_table_public_lowcal_sessions_add_column_has_user_saved/down.sql
- hasura.planx.uk/migrations/1664529923804_alter_table_public_lowcal_sessions_add_column_has_user_saved/up.sql
Sets up email "Reminder" and "Expiry" event when a user explicitly hits the "Save and return to this application later" button. Previously this was done automatically once a session was started.
Event triggers used to be hit with an insert to `lowcal_sessions`, it will now be an update on `lowcal_sessions.has_user_saved`.
- Start a new session on flow, e.g. XXXX
- Once you have entered email x2, a `lowcal_session` record will be inserted
- Event will **not** be set up in Hasura (Events > One-off Scheduled Events > Pending Events)
- Back on the flow, hit "Save and return to this application later" 
- A reminder and expiry event has now been set up in Hasura, with the timestamp matching when you hit "Save and return..." ✅
> feat: Setup Save & Return email notifications on user prompt, not automatically

- api.planx.uk/send/bops.js
- api.planx.uk/send/bops.test.js
- api.planx.uk/send/uniform.js
Since fixing the "don't show first node in the graph" issue when resuming between Pay & Send last week, it seems that the Send component has become more prone to automatically rerendering/reloading/etc. We hit this issue twice with manaul submissions and yesterday with a live submission. There have also been successful single-submisssions in between though.
While we're fully investigating and diagnosing that, this should help add a layer of protection to avoid duplicate successful submissions (and by extension notifications in the Slack channel) per sessionId & destination. Because the Send component creates Hasura Events, and then those events run with some level of parallelization, I'm not certain this will catch every case - but it seems to work as intended in testing.
This PR won't …
> fix: prevent duplicate submissions per sessionId and destination

- .github/workflows/weekly-staging-db-sync.yml
- hasura.planx.uk/seeds/1595528762802_teams_and_users.sql
- scripts/seed-database/package.json
- scripts/seed-database/pnpm-lock.yaml
- scripts/seed-database/seed-db.sh
- scripts/seed-database/upsert-production-flows.js
- scripts/start-containers-for-tests.sh
Continuation of #913 and #1123:
- Pulls published_flows from production (the last 2 published flows per flow)
- The fetching of flows is now spread across multiple requests as to avoid Hasura running out of memory
- Requests run in parallel but are throttled
```
$ docker compose down --volumes --remove-orphans
$ docker compose up --build
$ # Wait for the seeding script to finish
$ # check that your local database now containes published flows from production
```
> feat: sync production data to staging weekly

- .github/workflows/pizza-teardown-manual.yml
- Allows us to teardown pizzas by manually triggering the GitHub Actions teardown workflow
- I can only test it by merging it (and seeing if the button shows up on the Actions tab of this repo) so I might need a couple of PRs to get this right
Here's a picture of a workflow_dispatch action and its input fields:
(of course, our fields will be different. the image above is for illustration purposes only)
> ci(pizza): teardown pizzas manually

- editor.planx.uk/src/@planx/components/Send/bops/__tests__/makePayload.test.ts
- editor.planx.uk/src/@planx/components/Send/bops/index.ts
Addresses the following error - https://opensystemslab.slack.com/archives/C4B0CKQ3U/p1665145845295839
The affected user here had an additional breadcrumb which was subsequently removed from the flow, leading to the following error.
We could / should catch this at the reconciliation stage but a frontend guard will always be required as sometimes reconciliation is skipped (e.g. returning from pay).
> bug: Send payload should build despite additional breadcrumbs

- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
- editor.planx.uk/src/@planx/components/Send/uniform/xml.test.ts
- editor.planx.uk/src/@planx/components/Send/uniform/xml.ts
- Uniform submission failed where an end user had entered a "&" character in their project description
- This resulted in invalid XML being sent to Uniform, which the connector could not parse
- Very quick and dirty - just using `_.escape()` on text fields which are part of the XML string template
- I think this is another indication we might want to take another look at the work started by @jessicamcinchak here to implement an alternative method of constructing the Uniform XML - https://github.com/theopensystemslab/planx-new/pull/939#discussion_r891010320
- I've added a card to the backlog to discuss prioritising this - https://trello.com/c/6PD2SuLw/2144-implement-uniformpayload-interface-to-improve-xml-construction
> fix: Escape XML special characters

- .github/workflows/weekly-staging-db-sync.yml
- scripts/seed-database/upsert-production-flows.js
Fixes this error:
```
node:internal/process/esm_loader:97
internalBinding('errors').triggerUncaughtException(
^
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/runner/work/planx-new/planx-new/scripts/seed-database/node_modules/lodash/groupBy' imported from /home/runner/work/planx-new/planx-new/scripts/seed-database/upsert-production-flows.js
Did you mean to import lodash@4.17.21/node_modules/lodash/groupBy.js?
at new NodeError (node:internal/errors:387:5)
at finalizeResolution (node:internal/modules/esm/resolve:429:11)
at moduleResolve (node:internal/modules/esm/resolve:1006:10)
at defaultResolve (node:internal/modules/esm/resolve:1214:11)
at nextResolve (node:internal/modules/esm/loader:165:28)
at ESMLoader.resolve (node:internal/modules/esm/loader:844:30)
at …
```
> fix: weekly sync of prod data into staging

- api.planx.uk/package.json
- api.planx.uk/tsconfig.json
`ts-node-dev` does not check eagerly for type files,
therefore we need to add the flag `--files`.
See: https://github.com/TypeStrong/ts-node#missing-types
> fix: `ts-node-dev` not finding types

- editor.planx.uk/src/@planx/components/Send/uniform/xml.ts
After testing with Kev, I've identified `common:OperationsDescription` as the problem node which was duplicating descriptions for Proposed applications. 
The descriptions where never duplicated for Existing LDC apps (see second screenshot).
> fix: Remove duplicate "Proposal" value in Uniform

- editor.planx.uk/src/routes/unpublished.tsx
Fixes - https://trello.com/c/YUdmMlW3/2153-footer-links-dont-work-on-the-initial-enter-email-page-of-apply-for-services
The previous fix for this (https://github.com/theopensystemslab/planx-new/pull/1045) only addressed the issues in /preview, but missed out /unpublished
To test - 
- I can click on "Privacy" and "Contact Us" links in the footer of the following `/unpublished` Pizza link - https://1203.planx.pizza/buckinghamshire/apply-for-a-lawful-development-certificate/unpublished
> fix(save & return): Display pages on /unpublished route

- editor.planx.uk/src/@planx/components/Send/uniform/xml.ts
Noticed this whilst working on the `UniformPayload` type. Currently `getAddressFromSiteAddress()` returns the following fragment with commas after each `apd:IntAddressLine` node.
It's perfectly valid XML (surprisingly!) and Uniform reads it, but just tidying up here!
```xml
<common:ExternalAddress>
<common:InternationalAddress>
<apd:IntAddressLine>DRF CONSULTING ENGINEERS</apd:IntAddressLine>,
<apd:IntAddressLine>ANNEX BUILDING</apd:IntAddressLine>,
<apd:IntAddressLine>DISTRICT COUNCIL OFFICES</apd:IntAddressLine>,
<apd:IntAddressLine>QUEEN VICTORIA ROAD</apd:IntAddressLine>,
<apd:IntAddressLine>HIGH WYCOMBE</apd:IntAddressLine>
<apd:Country></apd:Country>
<apd:InternationalPostCode>HP11 1BB</apd:InternationalPostCode>
</common:InternationalAddress>
</common:ExternalAddress>
```
Tested on …
> fix: Return string as addressLines, not array

- hasura.planx.uk/migrations/1665744811194_delete_lowcal_events_on_submit_or_soft_delete/down.sql
- hasura.planx.uk/migrations/1665744811194_delete_lowcal_events_on_submit_or_soft_delete/up.sql
Issue raised here - https://opensystemslab.slack.com/archives/C4B0CKQ3U/p1665739302290809
Scheduled events are deleted via trigger when a hard delete takes place, but actually we want to delete them when either a submission or a soft delete takes place. This follows a recent change in the following PR - 
There's no user impact, as these API calls fail anyway (see Airbrake error above) but it's best to align everything here.
I'm getting increasingly keen to tidy things up in a more robust way...!  🗑️  https://trello.com/c/FlGxMbps/2078-data-retention-create-single-scheduled-task-to-purge-application-data-at-set-time-interval
To test - 
- Create a lowcal_session record (via Hasura or frontend)
- Query Hasura - there should be no scheduled events set up yet 
- Set `has_user_saved` = true …
> fix: Drop scheduled events on update of submitted_at or deleted_at

- api.planx.uk/send/uniform.js
- hasura.planx.uk/migrations/1665755400143_alter_table_public_uniform_applications_add_column_payload/down.sql
- hasura.planx.uk/migrations/1665755400143_alter_table_public_uniform_applications_add_column_payload/up.sql
- Adds a `payload` column on the `uniform_application` audit table
- This will be helpful for debugging as we're now doing a better job of cleaning up the scheduled event tables (#1206)
- An application submitted to Uniform will have the `payload` column populated
> feat: Capture payload on Uniform application audit table

- .github/workflows/sync-staging-db.yml
Fixes this error
```
error: PULUMI_ACCESS_TOKEN must be set for login during non-interactive CLI sessions
```
in the [Weekly staging database sync](https://github.com/theopensystemslab/planx-new/actions/workflows/sync-staging-db.yml) action:
> fix(ci): add missing env var

- editor.planx.uk/src/@planx/components/shared/Preview/MoreInfo.tsx
- editor.planx.uk/src/@planx/components/shared/Preview/QuestionHeader.tsx
- editor.planx.uk/src/theme.ts
- editor.planx.uk/src/ui/icons/MoreInfo.tsx
- Changes the help icon style - larger, uses team primary colour, and has a thicker outline
- Increases `MoreInfo` drawer width from 400px to 600px
- Fixes a style issue when both `:hover` and `:focus-visible` pseudo classes where applied to the button
- Updates the styles in touched components from JSS to Emotion (part of the MUI v5 upgrade - docs here https://mui.com/material-ui/migration/migrating-from-jss/
||Before|After|
|---|---|---|
|**Standard**|<img width="774" alt="image" src="https://user-images.githubusercontent.com/20502206/196893656-514b987a-a09d-4f32-892f-d37a437f000a.png">|<img width="801" alt="image" src="https://user-images.githubusercontent.com/20502206/196894675-274104c6-bfec-44b2-b0a5-221174ec44f9.png">|
|**Focus**|<img width="811" alt="image" …
> feat: Improvements to help button

- .github/workflows/pull-request-main.yml
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> refact(ci): set-output is being deprecated

- api.planx.uk/auth/index.ts
- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- api.planx.uk/send/bops.test.ts
- api.planx.uk/server.ts
- Sending to BOPS and Uniform via the API does not need to be publicly accessible
- We're already sending the `HASURA_PLANX_API_KEY` secret as a header from the Hasura send event to our API, so it makes sense to leverage this and to restrict our API
- You can send an application to both BOPS & Uniform on the Pizza. This can be verified via the audit tables (`unifrom_applications` and `bops_applications`) as well as via the event invocation log in the Hasura console.
- Update auth code to TS!
```mermaid
sequenceDiagram
participant P as PlanX Public Interface
participant A as API
participant H as Hasura
participant BU as BOPS / Uniform
P->>A: User submits application (public)
A->>H: Create send events (private)
H->>A: Call /send endpoint (private)
A->>BU: Send payload (private)
```
> fix: Use auth for sending applications to BOPS & Uniform

- hasura.planx.uk/metadata/tables.yaml
- hasura.planx.uk/tests/lowcal_sessions.test.js
Fixes the following Airbrake error - https://opensystemslab.slack.com/archives/C4B0CKQ3U/p1666791610814459
This allows the public user to access the `has_user_saved` column which was added to the `ValidateSingleSessionRequest` query in #1236 
Please note that users can only select rows they have permissions for - see `filter` in `tables.yaml` immediately below the code change here for details.
> fix: Allow public user to select has_user_saved column

- scripts/seed-database/upsert-production-flows.js
Solves the current problem in the sync'ing code in that flows don't show up in order on [staging](https://editor.planx.dev/buckinghamshire).
> feat(sync): keep timestamps so that flows appear in the right order

- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
- editor.planx.uk/src/@planx/graph/index.ts
- editor.planx.uk/src/pages/FlowEditor/lib/__tests__/clones.test.ts
- editor.planx.uk/src/pages/FlowEditor/lib/__tests__/mocks/flowWithClones.json
- editor.planx.uk/src/pages/FlowEditor/lib/__tests__/mocks/flowWithReverseClones.json
- editor.planx.uk/src/pages/FlowEditor/lib/__tests__/preview.test.ts
- editor.planx.uk/src/pages/FlowEditor/lib/store/preview.ts
Test flow on staging where this bug can be recreated - https://editor.planx.dev/testing/clone-order-example ❌ 
Pizza where this is fixed - https://1164.planx.pizza/testing/clone-order-example ✅ 
Cloned nodes are not asked in the correct order within the flow
The depth first sort algorithm used (`dfs()`) current creates a unique set of node ids. This means that clones will appear only once in this set. When `sortIdsDepthFirst()` is called, this results in the returned array for `upcomingCardIds()` "hoisting" cloned nodes to their first graph wide index position.
- Use an array in the `dfs()` algroithim, which means that clones will be listed in all graph positions
- When calling `sortIdsDepthFirst()`, only sort nodes within the context of their locality within the graph to ensure clones …
> fix: Clones should be asked in correct order

- editor.planx.uk/src/@planx/components/Pay/Public/Pay.tsx
Allows a legitimately failed payment to be retried.
- When a user returns to PlanX after payment we get their GovUkPayment details from their lowcal_sessions record. This was created before they redirected away to GovPay.
- On return, we reconcile this in the function `refetchPayment()`
- Based on the returned state (e.g. "failed", "success") we decide on how to proceed
- However! In the handler `resumeExistingPayment()` we check the legacy version of GovUkPayment from state, which has not been amended after the `refetchPayment()` call.
- This PR fixes this, and ensures that the updated payment details are stored and referenced consistently.
**To test -** 
- Try to pay on dummy flow https://1259.planx.pizza/buckinghamshire/daf-pay-test/preview?analytics=false using card number …
> fix: Update state on refetchPayment

- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
- editor.planx.uk/src/@planx/components/Review/Public.test.tsx
- editor.planx.uk/src/@planx/graph/index.ts
- editor.planx.uk/src/pages/FlowEditor/lib/__tests__/clones.test.ts
- editor.planx.uk/src/pages/FlowEditor/lib/__tests__/preview.test.ts
- editor.planx.uk/src/pages/FlowEditor/lib/store/preview.ts
- Reverts logical changes made in https://github.com/theopensystemslab/planx-new/pull/1164
- Removes redundant `act()` and `waitForExpect()` calls which were throwing "not wrapped in act(...)" errors in test (see https://github.com/theopensystemslab/planx-new/pull/1141 for context)
Pizza passed along to George and Jenna for testing.
> fix: Revert #1164 (Clones re-ordering)

- infrastructure/application/Pulumi.production.yaml
BOPS was failing to download files with the prior production key which had single quote, double quote and back tick characters in it :see_no_evil: 
Hopefully this is a simple step to resolve it! 
If successfully deployed, we need to determine if we need to resubmit session `17a6fa12-6300-4e17-97fb-a055efb48e5a`. I'm guessing we also failed to add the user-uploaded files to the Uniform zip.
To regenerate the key I ran: `pulumi config set --secret file-api-key SECRETTOKEN --stack production`
To retrieve the new value run: `pulumi config get file-api-key --stack production`
> fix: rotate production `file-api-key` to be alphanumeric

- hasura.planx.uk/metadata/tables.yaml
Previously, we'd retry 3 times after 10s, now we'll just retry 1 time after 30 sec on a failure to Send to BOPS or Uniform. 
As we discussed yesterday, the retries here aren't actually usually succeeding, but more so serve as a flag in the #planx-notifications channel that something went wrong. 1 retry should still give us that little notification nudge, while reducing noise and recognizing our ultimate action is more likely to be manual intervention to resubmit.
> fix: adjust Hasura event retries for Send

- .env.example
- api.planx.uk/.env.test.example
minor clarifications!
yesterday we discussed updating the Docker `FILE_API_KEY` value to match staging, which would then enable us to successfully send & test files to BOPS from a pizza environment. If we still agree that's a good way forward, I will additionally update S3 `pizza-secrets` value to do that as a manual step of this PR !
> docs: update .env.example files with FILE_API_KEY

- api.planx.uk/server.ts
- Enhances the GovUK Pay notifications in the `#planx-notifications` channel by appending the message (if available)
- Docs: https://docs.payments.service.gov.uk/api_reference/#errors-caused-by-payment-statuses
> feat: Add message to GovUK Pay notifications

- api.planx.uk/hasura/metadata/index.test.ts
- api.planx.uk/jest.config.ts
- api.planx.uk/webhooks/hardDeleteSessions.test.ts
- api.planx.uk/webhooks/lowcalSessionEvents.test.ts
- api.planx.uk/webhooks/sendNotification.test.ts
- api.planx.uk/webhooks/sendNotifications.ts
- Brings test coverage for the API `/webhook` and `hasura-metadata` modules up to 100%
- Bumps API global functions coverage threshold to 60%
- Delivers on this promise from last week 😅 https://github.com/theopensystemslab/planx-new/pull/1252#discussion_r1016424337
> test: Increase test coverage for API /webhooks & /hasura-metadata dirs

- editor.planx.uk/src/@planx/components/DrawBoundary/Public/Upload.tsx
- editor.planx.uk/src/@planx/components/FileUpload/Public.tsx
- Reports back a correct `aria-valuenow` to screen readers when a file is uploaded
- Previously this was off by a factor of 100... 👀 
- Drops redundant `aria-valuemin` and `aria-valuemax` - these are the default values ([docs](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/progressbar_role))
Note - refactoring the duplicated upload code would be a great win when looking at multiple file upload.
https://user-images.githubusercontent.com/20502206/203310811-e3b666a0-0e39-402a-b8bf-a0672c18b6f8.mov
> fix: Use correct value for aria-valuenow on upload progress bars

- editor.planx.uk/src/@planx/components/PlanningConstraints/Public.tsx
- editor.planx.uk/src/ui/FileDownload.tsx
Quick fix - this is currently logging out an error when displayed, and when Editor tests are running.
Visually this still looks as expected -
> fix: border-style kebab case warning

- api.planx.uk/s3/getFile.ts
- api.planx.uk/server.ts
- Publicly uploaded files are not accessible currently, and give a CORS error
- This is because files are now being served via the API
- This may not work still on custom domains - we can change to "cross-origin" if required but this feels worth a shot...!
- I'm pretty certain that these headers are set via Helmet in Express, but I'm a little unclear on Pulumi / AWS setup here. I see this as a bit of a temporary measure which is worth trying until we nail down the exact fix / implementation. Ideally we'd still limit access to certain domains if at all possible.
> fix: Allow public uploads to be accessed via API

- editor.planx.uk/src/ui/RichTextInput.tsx
Fix a bug where if the user pastes a URL into the rich text editor URL field, the initially populated `https://` gets doubled up.
[Per Slack discussion](https://opensystemslab.slack.com/archives/C5Q59R3HB/p1668710715681179).
> Fix paste url bug

- api.planx.uk/s3/getFile.ts
Please see https://github.com/theopensystemslab/planx-new/pull/1289 for context
As suspected, in order to work on custom domains this value needs to be set to `cross-site`.
https://planningservices.buckinghamshire.gov.uk/temporary-pay-test
> fix: Set public image CORP to "cross-site"

- docker-compose.yml
Allows for live-reload on development environments.
Doesn't affect staging/production as these are deployed using pulumi (not docker compose).
Might make pizzas slightly less performant but overall shouldn't affect it that much.
> chore(api): use pnpm dev on local environment

- .github/workflows/pull-request.yml
- Adds a GitHub Action that runs Lighthouse on two flows (production and canary)
- Takes the opportunity to add a markdown heading to the Pizza sticky comment
> feat(ci): lighthouse

- editor.planx.uk/src/@planx/components/DrawBoundary/Editor.tsx
- editor.planx.uk/src/@planx/components/DrawBoundary/Public/index.tsx
Three minor changes:
- "boundary" &rarr; "outline" in hardcoded sentence under map
- add comma separator for site areas in the thousands of square metres
- add internal passport variable for hectares conversion (editor-configured area passport variable currently referenced in Calculate etc remains unchanged and still defaults to metres square)
> fix: tweak DrawBoundary language and add passport variable for hectares conversion

- editor.planx.uk/src/@planx/components/DrawBoundary/Public/index.tsx
Follow up to implement the changes made in #1225 
Feedback from UR - 
> Tested with 6 people in R.45. I don't think there are lots of feedback on the enlargement of the map. The users didn't really know what it used to be like before the changes and they are still struggling a bit when the map doesn't show the whole of their property and they have to zoom out to see the whole of their site and then they are slightly nervous when the snap points disappear. But map enlarged map appears to be clear to users and doesn't seem to have an issue with the enlarged view.
> feat: Increase DrawBoundary map size

- editor.planx.uk/src/@planx/components/DrawBoundary/Public/index.tsx
- editor.planx.uk/src/@planx/components/FindProperty/Public/index.tsx
- editor.planx.uk/src/@planx/components/PlanningConstraints/Public.tsx
- editor.planx.uk/src/@planx/components/Result/Public/index.tsx
- editor.planx.uk/src/@planx/components/shared/FeedbackInput.tsx
- editor.planx.uk/src/theme.ts
- editor.planx.uk/src/ui/CollapsibleInput.stories.tsx
- editor.planx.uk/src/ui/CollapsibleInput.tsx
- editor.planx.uk/src/ui/ExternalPlanningSiteDialog.tsx
- editor.planx.uk/src/ui/FileDownload.tsx
- Styles secondary buttons used throughout the service as links
- Follows on from the work done in #1294 
- Converts a few components to the MUI v5 style engine 💅 
https://user-images.githubusercontent.com/20502206/204912557-c54cf16e-aa0a-4df0-bcd6-6a86714dd391.mov
I feel like there's a good chance I may have missed some of these - if you spot other instances of secondary buttons, let me know and I'll be happy to address.
> feat: Style secondary buttons as links

- editor.planx.uk/src/@planx/components/DrawBoundary/Public/index.tsx
In conclusion of Lam's user-testing feedback: 
> Turn red dot into a crosshair: Tested with 6 people in R.45. All users understood the cross-hair icon as a drawing tool. Don’t seem to mind the over icon also overlapping on it. (Lam: But we should get rid of it when we can)
> feat: switch to crosshair as drawing cursor

- editor.planx.uk/src/@planx/components/DrawBoundary/Public/index.tsx
This is a fix for styling issue I missed when resolving merge conflicts between increasing map size and converting buttons to links.
|Before|After|
|---|---|
|<img width="784" alt="image" src="https://user-images.githubusercontent.com/20502206/205274540-900f7e73-425a-4404-ade2-22e68ab824d3.png">|<img width="1031" alt="image" src="https://user-images.githubusercontent.com/20502206/205274609-d2b43844-83ac-4a1a-9763-3f5faf865ccb.png">|
> fix: Adjust space on 'Upload location plan'

- editor.planx.uk/src/@planx/components/DrawBoundary/Public/index.tsx
User-research wasn't particularly conclusive here, so we made a decision to go this route as it's most distinct from current option: 
> What should we change draw outline icon from :leftwards_arrow_with_hook: to ?
Tested in R.45 with 6 users.
Reset icon: 3/6 users prefer this icon, but a couple of them expect it to only delete one stroke at a time. Also, a user thinks it looks like the refresh button refreshes the whole page
Trash icon: 2/6 prefer this. Users Understood the ‘trash icon’ as ‘Delete’/ ‘Restart’. It feels clear what the button does but a couple of users don’t like it as it feels ‘too serious’/' too strong’
Rubber icon: Only 1 user perfer this and understood this as a rubber. It is not clear what the symbol means to most users. (edited)
> feat: DrawBoundary map uses trash bin icon stead of arrow

- editor.planx.uk/src/@planx/components/Content/Public.tsx
- editor.planx.uk/src/components/Footer.tsx
- Adds back the missing `capitalize` class from footer links
- Ensures sufficient contrast on links in `Content` components
- Updates Footer to the MUI v5 style engine
> fix: Footer & Content style fixes

- api.planx.uk/.eslintrc
- api.planx.uk/gis/index.test.ts
- api.planx.uk/hasura/metadata/index.test.ts
- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- api.planx.uk/saveAndReturn/validateSession.test.ts
- api.planx.uk/server.test.js
- api.planx.uk/tests/serverErrorHandler.test.js
- api.planx.uk/webhooks/hardDeleteSessions.test.ts
- api.planx.uk/webhooks/lowcalSessionEvents.test.ts
- api.planx.uk/webhooks/sendNotification.test.ts
- editor.planx.uk/.eslintrc
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
- editor.planx.uk/src/@planx/components/Calculate/model.test.ts
- editor.planx.uk/src/@planx/components/DateInput/Public.test.tsx
- editor.planx.uk/src/@planx/components/DateInput/model.ts
- editor.planx.uk/src/@planx/components/InternalPortal/Editor.test.tsx
- editor.planx.uk/src/@planx/components/Question/Public.test.tsx
- editor.planx.uk/src/@planx/components/Result/Public.test.tsx
- editor.planx.uk/src/@planx/components/Send/Public.test.tsx
- editor.planx.uk/src/@planx/components/Send/bops/__tests__/fileDescriptions.test.ts
- editor.planx.uk/src/@planx/components/Send/bops/__tests__/files.test.ts
- editor.planx.uk/src/@planx/graph/__tests__/add.test.ts
- editor.planx.uk/src/@planx/graph/__tests__/clone.test.ts
- editor.planx.uk/src/@planx/graph/__tests__/move.test.ts
- editor.planx.uk/src/@planx/graph/__tests__/remove.test.ts
- editor.planx.uk/src/@planx/graph/__tests__/update.test.ts
- editor.planx.uk/src/pages/FlowEditor/lib/__tests__/preview.test.ts
- editor.planx.uk/src/pages/FlowEditor/lib/__tests__/useNotValues.test.ts
- Sets up [eslint-plugin-jest](https://github.com/jest-community/eslint-plugin-jest) on both the API & Editor projects
- Resolves all warnings and errors, apart from [`jest/no-disabled-tests`](https://github.com/jest-community/eslint-plugin-jest/blob/v27.1.6/docs/rules/no-disabled-tests.md) which is only a warning, and serves us well in the absence of being able to call `jest.fails()` with the version of jest installed by create-react-app v5
I've checked in `test.only()` way too many times 😅 
I noticed on @gunar's [Playwright PR](https://github.com/theopensystemslab/planx-new/pull/1295#discussion_r1035735003) that the config allowed him to block `test.only()` calls, which we can now also do. Plus other bonus linting rules of course - a few decent things caught in this PR I think! 
I'll …
> chore: Setup eslint-plugin-jest on API & Editor

- editor.planx.uk/src/@planx/components/Confirmation/Public.tsx
- editor.planx.uk/src/@planx/components/Notice/Public.tsx
- editor.planx.uk/src/@planx/components/shared/Buttons/ButtonBase.tsx
- editor.planx.uk/src/@planx/components/shared/Preview/QuestionHeader.tsx
- editor.planx.uk/src/components/PhaseBanner.tsx
- editor.planx.uk/src/ui/ColorPicker.tsx
- editor.planx.uk/src/ui/ExpandableList.tsx
Very minor style tidy up I noticed when working on #1301 
Docs: https://mui.com/material-ui/customization/spacing/#multiple-arity
> fix: Simplify MUI spacing notation

- api.planx.uk/auth/index.ts
- api.planx.uk/server.ts
Check for API key on `/file/private` should use auth helper function `isEqual()` instead of a simple equality check.
> fix: Use isEqual() auth helper for useFilePermission()

- editor.planx.uk/src/@planx/components/DrawBoundary/Public/index.tsx
Here's a fix for some of the issues encountered with using `vw` units for increasing the map size. 
Using `vw` caused issues when browsers zoomed in and out, and did not produce a consistent right hand margin.
https://user-images.githubusercontent.com/20502206/206158604-2ccaf0b7-b9fd-4df7-b325-1571958d8c9e.mov
> fix: Different approach on map size increase

- editor.planx.uk/src/routes/utils.ts
Removes a reference to an old pizza link.
> chore: remove old pizza link

- .github/workflows/pull-request.yml
- doc/how-to/how-to-add-a-secret.md
- scripts/README.md
- scripts/pull-secrets.sh
- scripts/push-secrets.sh
- Documents how to add a secret to the PlanX application
- Adds two helper scripts to assist with this
- Calls these scripts as part of the CI process
If running `push-secrets.sh` locally you'll need to have an IAM user on AWS with appropriate permissions, and credentials stored at `~/.aws`. The `ci-user` does not have permissions to push to S3.
If we're averse to using the AWS CLI locally we can use a docker image to run these, something like...
```sh
docker run --rm -it -v ~/.aws:/root/.aws -v $(pwd):/aws public.ecr.aws/aws-cli/aws-cli --version; \
aws s3 cp s3://pizza-secrets/root.env ./../.env; \
aws s3 cp s3://pizza-secrets/api.env.test ./../api.planx.uk/.env; \
aws s3 cp s3://pizza-secrets/editor.env ./../editor.planx.uk/.env; \
aws s3 cp s3://pizza-secrets/hasura.env.test …
```
> doc: How to add a secret

- editor.planx.uk/src/@planx/components/shared/Preview/QuestionHeader.tsx
- editor.planx.uk/src/ui/RichTextInput.tsx
Fixes https://trello.com/c/73L0mP1Q/2224-how-is-it-defined-header-should-not-be-visible-in-draw-boundary-component-when-there-is-no-text.
@DafyddLlyr the checks in `QuestionHeader.tsx` won't be necessary after a while, just making sure things will work as expected without needing to do a sweeping `"<p></p>" -> ""`migration.
> Handle empty rich text editor content

- .github/workflows/pull-request.yml
- scripts/pull-secrets.sh
Fixes a bug introduced here, leading to API test suite failing due to missing file - https://github.com/theopensystemslab/planx-new/pull/1322/
> fix: Set correct API .env filename

- api.planx.uk/s3/utils.ts
- docker-compose.yml
Reverts change made in https://github.com/theopensystemslab/planx-new/pull/1271
This change meant that Pizzas were calling minio to handle file uploads, which isn't running as a service on Pizzas.
This is a quick and pragmatic revert / fix forward, I think more generally it might be more meaningful to have more fine grained values for `NODE_ENV` such as `"production" | "staging" | "pizza" | "test" | "local"`
We could also just override this in `docker-compose.pizza.yaml` if having it locally makes a significant difference 👌
> fix(wip): Fix upload in Docker environments

- api.planx.uk/editor/copyFlow.test.ts
- api.planx.uk/editor/copyFlow.ts
- api.planx.uk/helpers.ts
- api.planx.uk/server.ts
- api.planx.uk/types.ts
- editor.planx.uk/src/pages/FlowEditor/lib/store/editor.ts
- editor.planx.uk/src/pages/Team.tsx
- hasura.planx.uk/migrations/1671095403563_alter_table_public_flows_add_column_copied_from/down.sql
- hasura.planx.uk/migrations/1671095403563_alter_table_public_flows_add_column_copied_from/up.sql
lets editors make a unique copy of a flow within the same team
borrows logic from https://github.com/theopensystemslab/planx-team-onboarding/blob/main/client.js
future scope: 
- "move" flow to a new team
- for now, a dev can manually hit the endpoint without `insert` param and manually copy/paste response `data` for one-off copy requests _betweeen_ teams or use onboarding script to copy canonical 3 services to a new team :slightly_smiling_face: 
- "copy to flow" action from "internal portal" node menu
- connect planx-team-onboarding scripts to use this endpoint
> feat: add "copy" to editor-facing flow actions menu

- editor.planx.uk/src/pages/FlowEditor/lib/analyticsProvider.tsx
should hopefully address the lingering analytics-related Airbrake errors still coming through since yesterday's deployment: 
- https://john-opensystemslab-io.airbrake.io/projects/329753/groups/3432131055656736004
- https://john-opensystemslab-io.airbrake.io/projects/329753/groups/3432158337079285043 
- https://john-opensystemslab-io.airbrake.io/projects/329753/groups/3432136561972581678 etc
builds on this database migration merged as part of #1295 & deployed to prod yesterday:
> fix: update graphql type to "bigint" on analytics_log.analytics_id mutation

- README.md
Branch protection rules were recently adjusted, but I realized that I had incorrectly assumed yesterday what that meant for how we should deploy now - so writing down the process as I understand it after getting everything back in alignment today. 
Edits welcome!
> docs: add deployment steps to README

- api.planx.uk/admin/feedback/downloadFeedbackCSV.test.ts
- api.planx.uk/admin/feedback/downloadFeedbackCSV.ts
- api.planx.uk/server.ts
- editor.planx.uk/src/@planx/components/FindProperty/Public/index.tsx
- editor.planx.uk/src/@planx/components/PlanningConstraints/Public.tsx
- editor.planx.uk/src/@planx/components/Result/Public/index.tsx
- editor.planx.uk/src/components/Footer.tsx
- editor.planx.uk/src/components/PhaseBanner.tsx
- editor.planx.uk/src/lib/feedback.ts
- Fixes how existing metadata is sent to the FeedbackFish API when user submits information via the "Report an inaccuracy" buttons
- Send additional ("standard") metadata to allow George and Alastair more context when understanding feedback (e.g. UPRN, proposal.propertyType). This gets sent via the widget and our custom forms.
- Adds a basic `/admin/feedback` endpoint that allows logged in Editor to download a CSV of feedback
This ticket has morphed from looking at alternatives to FeedbackFish, to improving the current integration with a view to replacing it with a custom version in the medium term. Tickets for the follow on task of designing and building this have been added to Trello.
I certainly see the current implementation of the "download feedback CSV" endpoint as a temporary …
> feat: Enhance FeedbackFish metadata

- editor.planx.uk/src/airbrake.ts
Error logs should be quieter (and not error on setup!)
Note: `DEBUG=true` is now needed to see full logs
> chore: fix over-enthusiastic error logger

- editor.planx.uk/src/components/Footer.tsx
- editor.planx.uk/src/components/PhaseBanner.tsx
Currently the `metadata` passed into the FeedbackFish widget is only calculated on initial render of the `Footer` and `PhaseBanner` components. We want it to be "live" with the applicant's current state, not just the initial state on load.
Call `getFeedbackMetadata()` when the widget is opened (using the `window`'s `message` event).
There's a bit of a rearranging of the `Footer` component here to split things up a little bit.
- Navigate a few questions into a flow and submit feedback via the `Footer` or `PhaseBanner`
- The network tab should show the full "live" metadata being sent (e.g. breadcrumbs)
> fix: Send current metadata via FeedbackFish widget, not initial metadata

- .github/workflows/pull-request.yml
- .github/workflows/push-main.yml
- .github/workflows/push-production.yml
- api.planx.uk/proxy/ordnanceSurvey.ts
- editor.planx.uk/.env.example
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
- editor.planx.uk/src/@planx/components/DrawBoundary/DrawBoundary.stories.tsx
- editor.planx.uk/src/@planx/components/DrawBoundary/Public/index.tsx
- editor.planx.uk/src/@planx/components/FindProperty/Public/index.tsx
- editor.planx.uk/src/@planx/components/shared/Preview/SummaryList.tsx
- It points `MyMap` and `AddressAutocomplete` at the new `/proxy/ordnance-survey` endpoint added in #1334 
- Removes the `REACT_APP_ORDNANCE_SURVEY_KEY` from the application
- This PR (and changes to the GitHub actions) might break the map and address components on open PRs. A rebase to `main` should fix this though.
- Once merged I'll also remove ` {{ secrets.ORDNANCE_SURVEY_KEY }}` from the GitHub environment
- As another PR, I'll tidy up the React app `.env` file - these aren't secrets so we can manage to make this a bit simpler going forward
> feat: Point MyMap and AddressAutocomplete at proxy endpoint

- .github/workflows/pull-request.yml
- .gitignore
- editor.planx.uk/.env
- editor.planx.uk/.gitignore
- scripts/pull-secrets.sh
- scripts/push-secrets.sh
- Simplify secret management by committing our Editor `.env` file
- These are all publicly exposed, and are not secrets
- This work follows on from implementing a proxy for OS API calls #1334
> chore: Commit Editor environmental variables

- editor.planx.uk/src/@planx/components/DrawBoundary/Public/index.tsx
was testing FOIYNPP services and noticed that the area calculation was hidden when the file upload option was toggled off, but I think this is probably unintentional and we want to always show the area calculation - it was still being written to the passport in the background! 
now we'll render this when `props.hideFileUpload` is true:
> fix: always show DrawBoundary area

- api.planx.uk/send/email.ts
- api.planx.uk/send/uniform.js
Adds "boundary.geojson" & "map.html" files to the application file packet sent by email if the user draws their site boundary. If they uploaded a location plan, their uploaded file will be available same as any other user-uploaded files.
I'm purposefully not sending the CSV data as well to the HTML DocumentViewer right now, as send to email services will likely have simpler content and officers just want an easy way to screenshot the map for starters! I'll open a separate PR in the other repo to conditionally display the "Data" column so the boundary-only content looks more intentional
**To test:**
- Pick a team to test and configure `teams.settings.sendToEmail` to your email (via this pizza's Hasura Console)
- Create a simple test service with FindProperty > DrawBoundary > FileUpload > …
> feat: add geojson and html map-viewer to files sent by email

- editor.planx.uk/src/pages/FlowEditor/lib/__tests__/filters.test.ts
- editor.planx.uk/src/pages/FlowEditor/lib/__tests__/mocks/flowWithAutoAnsweredFilterPaths.json
see conversation here: https://opensystemslab.slack.com/archives/C5Q59R3HB/p1671546721333969
based on flow here: https://editor.planx.uk/testing/flag-order-test-with-autoanswer 
first test is a happy path and expected behavior, second fails on production so is still skipped with a clear TODO at the line that we'd expect to pass when we fix filters.
> tests: add more filter component scenarios for flag paths that have auto-answerable questions

- api.planx.uk/send/email.ts
- editor.planx.uk/src/@planx/components/Send/Public.tsx
I expect Emily's going to be doing some testing on "Send to email" this week, so two quick tidy-ups: 
- Mark the associated lowcal_session as submitted on success to avoid any confusing expiry reminder emails later
- Populate the Planx flow name in the email template
How to test:
- Add `"sendToEmail":"<your email>"` to `team.settings` on this pizza (pick any un-assigned team for testing)
- Edit a flow within that team: make sure it has a Send component with "Email to planning office" selected and the content is published
- Submit a test application 
- Check that: you have received an email; the template shows the name of your flow without hyphens; and your lowcal_session has a `submitted_at` timestamp in Hasura
> fix: populate flow name in "Submission" email template and mark associated session as submitted

- editor.planx.uk/src/lib/featureFlags.ts
- editor.planx.uk/src/theme.ts
This PR sets up an alternate theme which can be toggled using the `ALT_THEME` feature flag. This will allow @ianjon3s to work on theming in relative isolation.
> feat: Setup alt theme behind feature flag

- api.planx.uk/Dockerfile
Undoes change made here - https://github.com/theopensystemslab/planx-new/pull/1323/files#diff-9fee14c6790003e5ec78ba098a0e86794e0aeaac6a5ca302dc10ad9ae9d2aae8
Currently, API endpoint which end in `next()` seem to be throwing an instant 500 since the most recent deploy.
This seems to be the only significant change in the recent deploy (#1375
> fix: Reinstante port 4000 on API

- api.planx.uk/send/email.ts
- api.planx.uk/send/uniform.js
- api.planx.uk/send/uniform.test.ts
It appears that the document review is the source of issues affecting zip generation for send to email / send to Uniform.
Tested successfully here on a failing "Send to email" link - https://github.com/theopensystemslab/planx-new/pull/1379/commits/fc580eaf31a1b9c4360a0f1bbd16e0d1131c9c14
Just commenting out for now in order to get change to production to `main` and then `production` in order to get failed Uniform submission to Lambeth.
> fix: Comment out document review

- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- api.planx.uk/send/email.ts
- api.planx.uk/send/uniform.js
- api.planx.uk/send/uniform.test.ts
This undoes the temporary changes made in #1383 and bumps the document review library to v1.1.2 which should resolve the issues previously described.
> chore: Reinstate document review

- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
- editor.planx.uk/src/@planx/components/DrawBoundary/Public/index.tsx
context https://github.com/theopensystemslab/map/pull/255
no changes to our passport data, this just reflects the new event data structure and continues to store `property.boundary.site` geojson in EPSG:3857
> chore: upgrade to @opensystemslab/map v0.7.0 and update geojson change handler

- api.planx.uk/send/email.ts
- editor.planx.uk/src/@planx/components/Send/bops/__tests__/applicationType.test.ts
- editor.planx.uk/src/@planx/components/Send/bops/__tests__/fileDescriptions.test.ts
- editor.planx.uk/src/@planx/components/Send/bops/__tests__/files.test.ts
- editor.planx.uk/src/@planx/components/Send/bops/__tests__/flags.test.ts
- editor.planx.uk/src/@planx/components/Send/bops/__tests__/makePayload.test.ts
- editor.planx.uk/src/@planx/components/Send/bops/__tests__/userRole.test.ts
- editor.planx.uk/src/@planx/components/Send/bops/index.ts
- editor.planx.uk/src/@planx/components/Send/model.ts
Replaces hardcoded instances of `application_type = "lawfulness_certificate"` with flow name when calling this method to generate CSV's for non-LDC services. Additionally adds BOPS unit tests to confirm we set `application_type` correctly in different scenarios. 
Still essentially replacing a hardcoded instance with a different version of hardcoding/relying on a flow name, and will need to be adjusted if we send different types of applications to BOPS in the future, but makes the CSV more usable for other services (eg Prior approvals) in the shortterm.
To test:
- Make a simple flow with some questions and either a Confirmation page or Send component (so S&R is enabled)
- Open `/preview` and go through flow, click "Save and return later" or reach Confirmation page and click "Download your …
> fix: make "application_type" dynamic in `getBOPSParams` for non-LDC services 

- api.planx.uk/Dockerfile
- sharedb.planx.uk/Dockerfile
Originally spotted by @builditben here - https://github.com/theopensystemslab/planx-new/pull/1323/files#diff-9fee14c6790003e5ec78ba098a0e86794e0aeaac6a5ca302dc10ad9ae9d2aae8
Reinstated in #1380 as a poor attempt at troubleshooting API issues...!
Everything works fine locally without this, and there's not other references to port 4000 in the codebase.
> chore: Remove exposure of port 4000 from Dockerfiles

- api.planx.uk/webhooks/sanitiseApplicationData/mocks/queries.ts
- api.planx.uk/webhooks/sanitiseApplicationData/operations.test.ts
- api.planx.uk/webhooks/sanitiseApplicationData/operations.ts
**Problem**
Since merging https://github.com/theopensystemslab/planx-new/pull/1325 the `sanitiseReconciliationRequests` operation has been failing. This can be seen in the Hasura logs on `.dev` and Slack errors in the `#planx-notifications-internal` channel.
**Cause**
This is caused by refactoring `sanitiseReconciliationRequests` to delete instead of sanitising, without properly updating how the request was being destructured.
**Solution**
Update queries and variables to better reflect what's happening here - `sanitiseReconciliationRequests` consistently becomes `deleteReconciliationRequests`, and queries are updated accordingly.
> fix: Correctly rename queries for ReconciliationRequests

- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
v1.1.2 did not include the `/dist` folder so was not a valid release
> chore: Bump doc review to v1.1.3

- api.planx.uk/send/email.test.ts
- api.planx.uk/send/email.ts
- hasura.planx.uk/migrations/1674571117161_alter_table_public_teams_add_column_submission_email/down.sql
- hasura.planx.uk/migrations/1674571117161_alter_table_public_teams_add_column_submission_email/up.sql
- scripts/seed-database/upsert-production-flows.js
Better solution to quick bug fix last week #1390 &larr; full context in this PR
When merged to production, I'll manually migrate the handful of values in `teams` table to populate `submission_email` and remove `settings.sendToEmail` so that prior approval/send to email testing is uninterrupted.
> fix: add new column `teams.submission_email` so we can safely sync `teams.settings` across environments

- editor.planx.uk/src/@planx/components/AddressInput/model.ts
- editor.planx.uk/src/@planx/components/ContactInput/model.ts
- editor.planx.uk/src/@planx/components/TextInput/model.ts
Alice flagged `ContactInput` directly, quickly updated other similar offenders that I found too to match
See "Error messages" section of content guide here: https://www.notion.so/30313a55fc5b4499846e32e88b1cf76a#f4b90732e686447d9c36ab137908876f
> fix: adjust error messages to align with content guide

- api.planx.uk/gis/index.test.ts
- api.planx.uk/jest.config.ts
the braintree GIS server is down, and these tests do not have mocked responses (originally introduced in #1251 i think?)
simply skipping for now to un-block CI, but will revisit in another PR to clean up / add mocks / update to use a meaningful team
context https://opensystemslab.slack.com/archives/C4B0CKQ3U/p1675049856729589
> ci: skip braintree gis tests

- .github/workflows/pull-request.yml
- .github/workflows/push-main.yml
- .github/workflows/push-production.yml
- api.planx.uk/airbrake.ts
- api.planx.uk/helpers.ts
- api.planx.uk/s3/utils.ts
- api.planx.uk/server.ts
- docker-compose.pizza.yml
- editor.planx.uk/.env
- editor.planx.uk/.env.test
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
- editor.planx.uk/src/airbrake.ts
- editor.planx.uk/src/lib/featureFlags.ts
- editor.planx.uk/src/setupTests.ts
- editor.planx.uk/src/utils.ts
- infrastructure/application/index.ts
- Allows us to have a more granular understanding of the current environment. This has come up recently in the context of error logging and data retention Slack notifications.
- Sets `NODE_ENV` on the API, and `REACT_APP_ENV` on the Editor, to be one of `"test" | "development" | "pizza" | "staging" | "production"`
- `create-react-app` doesn't allow us to overwrite `NODE_ENV` in the Editor. Docs:  https://create-react-app.dev/docs/adding-custom-environment-variables/ 
- Adds a helper function `isLiveEnv()` which is equivalent to the current `process.env.NODE_ENV === "production"` condition.
> refactor: Add granularity to NODE_ENV and REACT_APP_ENV

- api.planx.uk/helpers.test.ts
- api.planx.uk/helpers.ts
- api.planx.uk/webhooks/sanitiseApplicationData/index.ts
Branches from #1412 which should be merged first.
Resolves issue of data sanitation Slack messages logging out to `#planx-notifications-internal` without the proper context.
> feat: Display env details in Slack notifications

- api.planx.uk/admin/session/oneAppXML.test.ts
- api.planx.uk/admin/session/oneAppXML.ts
- api.planx.uk/server.ts
Wish I'd done this sooner...!
This takes away the pain and time of getting a Uniform submission XML from Hasura, formatting it, and checking it out.
We could add an explicit validation check here, but the browser will generally show this if there's an issue. If it's something we hit often we can add it in to get errors which are more nicely formatted. Theoretically, as we're using a library to build the XML this shouldn't really be an issue.
Example url (must be logged in) - https://api.1424.planx.pizza/admin/session/dummy_submission_ref_123/xml
> feat: Session XML endpoint

- editor.planx.uk/src/@planx/components/ExternalPortal/Editor.tsx
- editor.planx.uk/src/@planx/components/ui.tsx
- editor.planx.uk/src/pages/FlowEditor/components/PreviewBrowser.tsx
two quick improvements from this thread: https://opensystemslab.slack.com/archives/C5Q59R3HB/p1675688673788069
1. Add alert on error when calling `diffFlow` to check for changes to publish. this now matches the error handling for `publishFlow`, which wasn't actually being reached if the first diff-ing for changes step failed
2. Improve editor UI for "external portals" to give more context to what's actually being edited
before:
> fix: give editors feedback on publishing errors

- .gitignore
After the latest update, when I'm running a dev container in VSCode a temporary json file with env secrets is now stored. 
I'll look at the setup to see why this is happening or if it's required, but this seems a sensible precaution for now.
Tactfully cropped screenshot showing file -
> chore: Update `.gitignore` for VSCode devcontainers tmp files

- editor.planx.uk/src/@planx/components/Send/uniform/UniformPayload/model.ts
- Ensures that `getAddressForPerson()` always returns an `ExternalAddress`
- Due to a content bug (now fixed), it was previously possible to submit an application without an applicant address when submitted by an agent
- This requires a site address in the passport. We'll need to revisit this assumption when an applicant has a site without an address.
This type of issue raises a whole load of questions for me about how we validate and understand passports, and how we handle this. The approach implemented here is still prone to content bugs (for example, if we don't ask for the agents address it will provide the site address).
A number of recent Uniform submissions have failed, all of which did not have an applicant address. The following message from Idox suggests that this is the cause …
> fix: Update getAddressForPerson() - address is required

- editor.planx.uk/src/@planx/components/shared/Buttons/DescriptionButton.tsx
> fix: glitch in description button

- editor.planx.uk/src/pages/FlowEditor/lib/store/preview.ts
while testing property component changes on prod, I noticed that I couldn't proceed past a checklist. dev is OK - so this likely stems from a content bug somewhere? i can reproduce locally with content synced from production ~3 days ago. 
try: https://editor.planx.uk/southwark/find-out-if-you-need-planning-permission/preview?analytics=false
production console shows this on clicking "continue" & doens't proceed:
local console shows:
this small type adjustment allows me to successfully click the "continue" button now, but there's likely still a corrupted node somewhere in a content graph that needs to be fixed too outside of code as well.
> fix: can't proceed past checklists on production

- editor.planx.uk/src/@planx/components/Send/uniform/UniformPayload/types.d.ts
Please see discussion here - https://opensystemslab.slack.com/archives/C5Q59R3HB/p1676042939048459
I feel like it's becoming more apparent that having a `UniformPayload` type is helpful for development and a big step forward from where we were, but it's failing to catch issues such as this one. It wasn't really a part of the previous task.
I'm going to take a look at ways we could implement a schema here, derived from the existing type, which should allow us to pre-validate and catch issues _before_ submission wherever possible
> chore: Add more detail to ConsentRegimes

- editor.planx.uk/src/@planx/components/Send/uniform/UniformPayload/model.ts
Not yet spotted where this regression has come from. I've confirmed the following - 
- OS API returns value to 2 decimal places (docs: https://osdatahub.os.uk/docs/places/technicalSpecification)
- OneApp requires integer (see XML below)
```xml
<xsd:complexType name="CoordinateStructure">
<xsd:annotation>
<xsd:documentation>Coordinate Point based on UK National Grid</xsd:documentation>
</xsd:annotation>
<xsd:sequence>
<xsd:element name="X">
<xsd:annotation>
<xsd:documentation>Easting Field</xsd:documentation>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:unsignedLong">
<xsd:minInclusive value="0" />
<xsd:maxInclusive value="9999999" />
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Y">
<xsd:annotation>
<xsd:documentation>Northing …
```
> fix: Pass integer coords to Uniform

- api.planx.uk/admin/session/oneAppXML.test.ts
- api.planx.uk/admin/session/oneAppXML.ts
Adding an `order_by` here means we just display the most recently submitted payload, which is really the intention.
Multiple records will be returned when an application has been re-submitted.
> fix: Fetch only most recent submission

- doc/how-to/how-to-resubmit-an-application.md
Thanks for adding this doc yesterday! 
I think there's perhaps a case to split it into two sections/scenarios though (often partners are using same language for both/either scenario, yet technical steps required are different): 
1.  We're re-submitting because there was a previous attempt that failed. This is most common, and makes good case for re-submission API
2.  We're re-submitting beause a partner notified us of a payment without a submission. This is increasingly rare, but can still occassionally happen and anyone should know how to investigate/proceed. These are very uncommon edge cases that will probably never justify scripting or wrapping in the re-submissions API
Second section comes from this pinned Slack message in #planx, which is hard to find and collectively update: …
> doc: re-submission steps for orphan payment scenario

- doc/how-to/how-to-resubmit-an-application.md
apologies that #1452 merged before Ben's comments / feedback - this PR addresses them:
> nit: are 3 and 4 the wrong way round?
good eye, 3 and 4 were indeed out of order, now updated :heavy_check_mark: 
> What prevents re-submission for the status (step 5)? - could we append a "resubmission" column, duplicate the entry and skip this status check for anything marked as a re-submission? That way we'd keep the original in place if any other mistake is made.
In the past, we've had instances where a user would refresh the page on Send, causing the component to re-render and another set of Hasura scheduled events to be created. To avoid un-intentional duplicated submissions, each Uniform ([here](https://github.com/theopensystemslab/planx-new/blob/main/api.planx.uk/send/uniform.js#L40-L51)) and …
> fix: update order of steps in re-submission doc

- editor.planx.uk/src/@planx/components/Confirmation/Public.test.tsx
- editor.planx.uk/src/@planx/components/Confirmation/Public.tsx
- editor.planx.uk/src/@planx/components/Send/Public.tsx
- editor.planx.uk/src/@planx/components/Send/bops/__tests__/applicationType.test.ts
- editor.planx.uk/src/@planx/components/Send/bops/__tests__/fileDescriptions.test.ts
- editor.planx.uk/src/@planx/components/Send/bops/__tests__/files.test.ts
- editor.planx.uk/src/@planx/components/Send/bops/__tests__/flags.test.ts
- editor.planx.uk/src/@planx/components/Send/bops/__tests__/makePayload.test.ts
- editor.planx.uk/src/@planx/components/Send/bops/__tests__/userRole.test.ts
- editor.planx.uk/src/@planx/components/Send/bops/index.ts
- editor.planx.uk/src/@planx/components/shared/hooks.ts
- editor.planx.uk/src/components/Header.test.tsx
- editor.planx.uk/src/components/Header.tsx
- editor.planx.uk/src/pages/FlowEditor/lib/store/shared.ts
- editor.planx.uk/src/pages/Preview/StatusPage.tsx
- editor.planx.uk/src/routes/preview.tsx
- editor.planx.uk/src/routes/unpublished.tsx
- editor.planx.uk/src/routes/utils.ts
Quick refactor based on [comments here](https://github.com/theopensystemslab/planx-new/pull/1436) which means we can more readily get the `flowName` and `flowSlug` without having to call a hook.
> feat: Write flowName to store

- .github/workflows/pull-request.yml
The current Lighthouse tests we have feel a bit useless. There's nothing to compare the results to.
This change makes it so that the sticky comment shows the difference between the lighthouse results from the PR's branch vs `main` (staging). The idea is that it'll allow us to identify PRs that are increase (or decreasing) performance.
> ci: show a diff of lighthouse perf

- editor.planx.uk/src/pages/FlowEditor/lib/store/index.ts
Should've been checked in alongside https://github.com/theopensystemslab/planx-new/pull/1470
One warning still remains, see comment here - https://github.com/theopensystemslab/planx-new/pull/1470#issuecomment-1436838944
> chore: Remove Zustand default import

- editor.planx.uk/src/pages/FlowEditor/lib/__tests__/overrideAnswer.test.ts
- editor.planx.uk/src/pages/FlowEditor/lib/store/preview.ts
I was recently using property override and noticed some strange behavior that was inconsistent with original feature intention. 
:bulb: The order of breadcrumbs is _not_ guaranteed to match the order nodes are asked in the graph, and therefore using `find()` to set "overrideNodeId" could behave unexpectedly :bulb: 
Test flows:
- Prod: https://editor.planx.uk/testing/change-property-test (use to re-create buggy behavior)
- Pizza: https://1473.planx.pizza/testing/change-property-test (use to test this fix)
Steps to reproduce: 
- Search UB9 4AP &rarr; 6, WILLOW CRESCENT EAST, NEW DENHAM
- OS says this address is a Semi-detached house aka `"residential.dwelling.house.semiDetached"`
- Clicking "change" _should_ completely clear the "property.type" variable from the breadcrumb of the …
> fix: sort breadcrumbs when overriding answer and improve test

- api.planx.uk/@types/planx-document-templates.d.ts
- editor.planx.uk/types.d.ts
Recent PRs & local docker "up"s have been failing on the Build React App step (see #1482, #1483 etc)
Based on the timing and error, I think this was likely introduced on this merge - https://github.com/theopensystemslab/planx-document-templates/pull/11 ? I'm not entirely sure if intentional or not (I definitely missed during code review!), so this might be best addressed as a two-part/two-repo fix, but this should clear up our planx-new CI in the meantime :checkered_flag:
> fix: add type declaration for planx-document-templates for successful CI

- .github/workflows/pull-request.yml
Undoes change made here - https://github.com/theopensystemslab/planx-new/pull/1480/files#diff-b71166ed0f585913318ed46933ff9b12901e211de3ac88c40de03f0a944c0ae0L206-L215
Currently, Pizzas are pointing to localhost:XXXX indicating that these values have not been correctly overwritten for the Pizza environment as part of the CI (I think!).
> fix: Add env vars back to React build in CI

- editor.planx.uk/src/pages/FlowEditor/lib/store/shared.ts
- editor.planx.uk/src/routes/flow.tsx
- Adds an additional validation step in the Editor to ensure that users cannot navigate to an invalid route
See PlanX Slack here - https://opensystemslab.slack.com/archives/C4B0CKQ3U/p1677159875899169
To recreate - 
- Delete a node
- Hit back in the browser so your URL is now `…nodes/<DELTED_NODE_ID>/edit`
- Invalid URL - Error! ❌ 
The above steps cannot be recreate on the Pizza, invalid routes will just redirect to the main flow.
> fix: Handle missing node id in Editor route

- api.planx.uk/editor/publish.test.ts
- api.planx.uk/editor/publish.ts
- editor.planx.uk/src/@planx/graph/__tests__/add.test.ts
- editor.planx.uk/src/@planx/graph/__tests__/clone.test.ts
- editor.planx.uk/src/@planx/graph/__tests__/move.test.ts
- editor.planx.uk/src/@planx/graph/index.ts
- editor.planx.uk/src/pages/FlowEditor/components/PreviewBrowser.tsx
Rules for working with Sections in the Editor:
Other changes here:
To test: 
- Spend some in test flows on this pizza adding and dragging and cloning sections! (to clone = right click existing node, then click on "open circle" on another branch to attempt to place)
- Confirm that you are seeing error messages when appropriate
- Keep your console open and confirm that there is _not_ an operation logged when errors are thrown
> feat: add checks in the editor for adding, moving, and cloning section nodes

- editor.planx.uk/src/@planx/components/PropertyInformation/Public.tsx
- editor.planx.uk/src/@planx/components/shared/Preview/SummaryList.tsx
The following warning is thrown in console when navigating to the FindProperty and SummaryList components in local dev - 
Change from `:nth-child` selector to `:nth-of-type` selector.
Display after this change is still consistent -
> fix: `:nth-child` CSS warning thrown by Emotion

- editor.planx.uk/src/@planx/components/Section/Public.tsx
- editor.planx.uk/src/pages/FlowEditor/lib/store/navigation.ts
First draft at the public "overview page" display of a "Section" node per Figma (linked in Trello)
Changes here (demo flow https://1491.planx.pizza/doncaster/test-service-with-sections):
- When the `NAVIGATION_UI` feature flag is toggled on, a Section node has a public-facing card in the graph (if the feature flag is off, it is hidden)
- The overview list correctly displays all Setions found in this flow
- The status tag updates correctly as you go forward and answer questions in a section
Future scope:
- Confirm & add tests for status tag behavior (eg back, "change" from Review, etc) & clean up tag styles (colours, etc) ([Trello ticket](https://trello.com/c/yNUyIP2I/2307-08-completed-not-started-ready-to-start-tags-for-sections-on-overview))
- If status = "Completed", then style section …
> feat: sections overview page with dynamic status tags

- api.planx.uk/gis/digitalLand.js
- api.planx.uk/gis/local_authorities/metadata/newcastle.js
To test:
- https://1504.planx.pizza/newcastle/find-out-if-you-need-planning-permission/preview
- TILLEY'S, 105, WESTGATE ROAD, NE1 4AG
- Picks up `article4.newcastle.brandyVaults` (prod currently knows it's an `article4`, but not _which_)
https://api.1504.planx.pizza/gis/newcastle?geom=POLYGON+%28%28-1.620696634054177+54.9705222120086%2C+-1.6207368671894007+54.97043060677049%2C+-1.620527654886239+54.97039981504693%2C+-1.620503515005105+54.970494499521635%2C+-1.620696634054177+54.9705222120086%29%29
> feat: return granular Article 4 data in Newcastle GIS searches

- editor.planx.uk/src/@planx/components/shared/Preview/SummaryList.tsx
- editor.planx.uk/src/pages/FlowEditor/lib/store/navigation.ts
This is a quick refactor to move the section chunking logic to the store for reuse.
The plan was to add tests and modify the export data structure so that we have access to these chunks in the document template data structure, but I'll handle that as a follow on PR so that this can get shared / reviewed sooner.
Please see PlanX Slack discussion here for context - https://opensystemslab.slack.com/archives/C01E3AC0C03/p1678185974650719
> refactor: Move section chunking to store

- editor.planx.uk/src/pages/Preview/Node.tsx
Originally thought we should just make this configurable in the Editor, but that's annoyingly tricky currently because "Application type" is one row within a table of data points generated by `props.details`.
So, instead, trying this which I think still satisfies the original problem! 
**"Application type" will reflect the `flowName` with a few rules applied:**
- If the flowName is phrased as "apply-for-", we'll display the application type as "Application for..." (this service name pattern is agreed upon by content team according to govuk standards, so unlikely to change I think!)
- If there's a "work status" in the passport (eg "existing" or "proposed"), it'll be tacked onto the end of the flow name
On production, on an LDC Confirmation page, now: "Application for a Certificate of …
> feat: Confirmation page "application type" reflects service name

- editor.planx.uk/src/@planx/components/Section/Public.tsx
Instead of linking back to the section card, we should navigate back to the first question of that section.
https://user-images.githubusercontent.com/20502206/224757599-082e15cf-1861-4a31-b8ac-54b8b0ea078a.mov
> fix: Link to first question from section page

- editor.planx.uk/src/components/Header.tsx
- editor.planx.uk/src/pages/FlowEditor/lib/store/navigation.ts
Currently, the section banner does not display the correct data when reaching a section card. It should treat the section card as the first card of the _next_ section. 
As we rely on breadcrumbs to calculate the current section and update this on `record()`, it's always backwards looking. By using `currentCard()` we can always display the correct section title and index.
TODO: Link to example on Pizza
The section banner displays the correct information...
- On the initial section card
- On subsequent sections when navigating forwards
- On previous sections when navigating via the "Back" button
- On previous sections when navigating via the links on the section page
> fix: Treat section card as first of next section

- infrastructure/application/Pulumi.production.yaml
- infrastructure/application/Pulumi.sandbox.yaml
- infrastructure/application/Pulumi.staging.yaml
What I did:
- Generated 3 new secrets as 32-character alphanumeric strings using 1pass generator
- Ran `pulumi config set --secret hasura-admin-secret $NEW_VALUE --stack $ENV` x3 for `production`, `staging` & `sandbox`
What happens next:
- Once deployed, we should all be prompted to login fresh to the Hasura web console and any "remembered" passwords/connections will be invalid
- You can access the new secrets by running `pulumi config get hasura-admin-secret --stack $ENV`
Future todo:
- Rotate the docker `HASURA_ADMIN_SECRET`. I didn't include this here since it will effect all open pull requests, and pizzas are isolated envs without user data anyways so far fewer concerns about maintaining access to application data
> chore: rotate `hasura-admin-secret` across all AWS environments

- infrastructure/application/index.ts
Commented out until we receive updated certificates, this will allow production deploys to succeed.
> chore: Disable Medway CDN

- hasura.planx.uk/config.yaml
- hasura.planx.uk/seeds/1595528762802_teams_and_users.sql
A few little issues hit with getting Ian up and running on PlanX.
- Some Mac versions use port 7000 for Airdrop, but this needs to be updated in multiple places in the `.env` to work correctly. Alternatively, Airdrop can be disabled.
- Ian wasn't listed on prod and staging dbs, likely overwritten by the new data sync
> fix: Update user pk, use port env var

- editor.planx.uk/src/components/Header.tsx
Quick fix using `useAnalyticsTracking()` to get current node in a more stable way - this is still calling `getCurrentCard()` behind the scenes. As it's using React's `useContext()` it's probably a bit wiser about rendering.
Ideally, we'd be able to track the current node in the store instead of having to call `currentCard()` which iterates over the flow. I'll take a look at this tomorrow 👍
> fix: Fetch current node without recursive loop

- infrastructure/data/index.ts
this was causing `pulumi up` to fail and pick up a larger diff (db password _and_ `engineVersion`). 
now this reflects the version that our staging & production AWS RDS databases are actually running on. 
we suspect the sandbox environment _only_ was installed at v14.6. we may need to manually adjust this when rotating creds there.
> fix: sync postgres version in Pulumi

- editor.planx.uk/src/routes/utils.ts
Medway have now confirmed that their CNAME record has been setup.
`team.domain` has also been populated on the production db.
> feat: Add custom Medway domain

- api.planx.uk/pnpm-lock.yaml
- e2e/package.json
- e2e/playwright.config.ts
- e2e/src/context.ts
- e2e/src/pay.spec.ts
- editor.planx.uk/src/@planx/components/Pay/Public/Pay.tsx
- editor.planx.uk/src/lib/lowcalStorage.ts
- editor.planx.uk/src/types.ts
- hasura.planx.uk/.env.test.example
- hasura.planx.uk/metadata/tables.yaml
- hasura.planx.uk/tests/lowcal_sessions.test.js
- hasura.planx.uk/tests/utils.js
Save a lowcal session before redirecting to GovPay.
This PR introduces a change which adds a lowcal session entry on pay interactions.
I considered only updating the lowcal session on new payments or only on success but decided to update on every request to resolve the payment response from the proxy. This means that the lowcal session is always up to date with the latest payment information (including status). GovPay will only allow one payment at a time so keeping track of the latest payment requested will always result in tracking any payments that actually succeed.
To test this in detail, you would need to set up some additional logging to validate the payment_id tracks correctly. The audit table is also a helpful tool for testing here. Have a look at the E2E test scenarios which …
> feat: Save session on payment responses

- editor.planx.uk/src/components/Header.tsx
From @ianjon3s - 
> the navigation pages should not have the navigation banner present as they are intermediate states that mark milestone positions in the journey (they also give a more detailed breakdown of navigation status in the table). Scroll position isn't a concern here as we are jumping out of the user-flow of repetitive question patterns to signify the milestone has been reached.
> chore: Remove section navbar from section components

- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- api.planx.uk/saveAndReturn/validateSession.test.ts
- api.planx.uk/saveAndReturn/validateSession.ts
- api.planx.uk/tests/mocks/saveAndReturnMocks.ts
This adds handling for section reconciliation. My understanding of how this should behave is described in the automated tests - please review those tests and also let me know if there are any additional behaviors that need testing here. 
This depends on a change to planx-core here: https://github.com/theopensystemslab/planx-core/pull/2
> feat: Handle sections in flow reconciliations

- docker-compose.yml
- infrastructure/application/index.ts
The main motivation here is in order to access better dashboard duplication features to make onboarding Medway and Canterbury a smoother process.
Release notes: https://www.metabase.com/releases/Metabase-0.45
Once done, I'll also update our docs to reflect any changes in the process.
> chore: Update Metabase to v0.45.3

- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
this bumps up our commit reference to pick up the styled overview.html & addition of section headers if the flow is using sections.
testing: `application.html` is currently part of the packet of documents in "send to email", so add your email in `teams.submission_email` and make/publish a test flow
> chore: link up new overview.html changes in planx

- api.planx.uk/s3/utils.test.ts
- api.planx.uk/s3/utils.ts
- docker-compose.yml
- package.json
I'm currently getting the following error when running the app locally and trying to upload files - 
`{"error":"Inaccessible host: '127.0.0.1' at port '9000'. This service may not be available in the 'eu-west-2' region."}`
Is anybody else having this issue?
- Always run Minio on local dev
- Use docker networking address
> fix: Re-enable Minio locally

- api.planx.uk/pnpm-lock.yaml
- api.planx.uk/send/uniform.ts
- api.planx.uk/types.ts
Been meaning to get round to this one for a while!
A few small refactors that should help with testing also, will look at bumping up test coverage in another PR.
I can successfully send dummy submissions locally and via the Pizza, but would appreciate another dev please testing this if possible.
> chore: Convert `send/uniform` to TypeScript

- infrastructure/application/Pulumi.staging.yaml
we expect that changing dbUser password has cascaded here and invalidated it, so it needs to be re-created at the same time. 
https://github.com/theopensystemslab/planx-new/actions/runs/4510429671/jobs/7941489234
> infra: rotate metabase role pg password on staging

- api.planx.uk/send/email.ts
- editor.planx.uk/src/@planx/components/DrawBoundary/Public/Public.test.tsx
- editor.planx.uk/src/@planx/components/DrawBoundary/Public/index.tsx
- editor.planx.uk/src/@planx/components/Review/Public.test.tsx
- editor.planx.uk/src/@planx/components/Send/bops/index.ts
I hit this issue when looking at attach files for sendToEmail. Because the passport variable assigned in DrawBoundary is not the same as normal file upload we need some additional code to get the file based on the passport variable as opposed to relying on the structure of the object.
Before we jump into multiple file upload I'd be interested in wider refactor of some of this shared upload logic, but this feels like a decent light touch for now.
**What this fixes**
- Manually having to find `DrawBoundary` files when parsing the passport
- This file isn't being currently handled in `planx-core` when generating a OneApp payload, or when we delete files by parsing the passport
> fix: Handle file uploads in standard format

- api.planx.uk/send/uniform.test.ts
- api.planx.uk/send/uniform.ts
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
- editor.planx.uk/src/@planx/components/DrawBoundary/Public/Public.test.tsx
- editor.planx.uk/src/@planx/components/DrawBoundary/Public/index.tsx
- editor.planx.uk/src/@planx/components/DrawBoundary/model.ts
- editor.planx.uk/src/@planx/components/Review/Public.test.tsx
- editor.planx.uk/src/@planx/components/Send/bops/index.ts
- editor.planx.uk/src/@planx/components/Send/uniform/index.ts
- editor.planx.uk/src/@planx/components/shared/Preview/SummaryList.tsx
- Generates list of files on the backend, no longer needs a list sent via `getUniformParams()`
- Simplifies duplicated keys set by `DrawBoundary`
- See comment here - https://github.com/theopensystemslab/planx-new/pull/1568#pullrequestreview-1356945031
- `cachedFile` removed
- `uploadedFile` removed
- `proposal.drawing.locationPlan` kept in format which more closely matches other file upload data objects.
There's certainly more scope for unit testing or E2E testing here, but I'd be a bit more keen to pick that up once we move more Submission logic to the backend. If you feel it's more appropriate to increase coverage at this stage to describe the current Editor behaviour I'm happy to pick that up.
**To test**
- Upload file via `DrawBoundary`
- If I navigate "Back" to this component file …
> refactor: Simplify Editor file upload logic

- hasura.planx.uk/metadata/tables.yaml
- hasura.planx.uk/migrations/1679922513351_alter_table_public_lowcal_sessions_add_column_read_only/down.sql
- hasura.planx.uk/migrations/1679922513351_alter_table_public_lowcal_sessions_add_column_read_only/up.sql
- hasura.planx.uk/tests/lowcal_sessions.test.js
This PR adds a `locked_at` column to the lowcal_sessions table.
Before a 'payment request" is created, the associated lowcal session should be locked and future updates should not be allowed.
> feat: Lock lowcal sessions

- api.planx.uk/gis/helpers.js
- api.planx.uk/gis/index.js
- api.planx.uk/gis/local_authorities/metadata/braintree.js
- api.planx.uk/gis/local_authorities/metadata/scotland.js
- api.planx.uk/gis/local_authorities/scotland.js
Hookup initial GIS layers so team `/scotland` can successfully query planning constraints from dedicated data sources
What I did here: 
- Scotland shared a list of layers and source links, I prioritzed ones already hosted as un-authenticated ESRI Rest services
- Copied Braintree's GIS setup, subbed in Scotland metadata (a lot of GIS files always feel ripe to want to refactor, but avoiding that and aiming for a quick proof of concept here re-using as many prior ESRI helper methods as possible)
Testing:
- https://1578.planx.pizza/scotland/search/preview
- Try address: Cairngorms National Park Authority Planning Office, 14 The Square, Grantown-on-Spey PH26 3HG
- Planning constraints will generate approximately this PlanX API [request](https://api.1578.planx.pizza/gis/scotland?x=303325&y=82797 …
> feat: hook up GIS layers for Scotland

- scripts/pullrequest/update.sh
the TPX pizza was created 2 months ago when we were still using `docker-compose`, so when I rebased and tried to push GIS changes today it errored because now we're using `docker compose`.
i want to avoid destroying & re-creating the whole vultr instance because they've been editing content in at least ~10 flows.
how i expect this to work: 
- reverts pull request update script to use `docker-compose` like here: https://github.com/theopensystemslab/planx-new/pull/1333/files#diff-e82530b26a3296f5accde8f5cb20952d0b84ab13d94eb03f32b8477be20926bc
- docker-compose.yml still matches main and has `["seed"]` profile, so update _should not_ re-seed the database
anything i might be missing here? 
i tried running this locally and got this error, but I'm hoping that already in use port might just be a …
> build: revert to old update script using docker-compose for tpx demo env

- editor.planx.uk/src/@planx/components/Send/bops/__tests__/works.test.ts
- editor.planx.uk/src/@planx/components/Send/bops/index.ts
- editor.planx.uk/src/@planx/components/Send/model.ts
Please see discussions on ODP Slack here - https://opendigitalplanning.slack.com/archives/C0182MVK4AW/p1680010700510649
I've not added the `immune` key as I think what we're doing in `result` should be enough and duplicating it doesn't make a whole load of sense to me but happy to get feedback from BoPS and we can take it from there.
> feat: Add works dates to BOPS payload

- api.planx.uk/saveAndReturn/resumeApplication.ts
- api.planx.uk/saveAndReturn/utils.ts
- editor.planx.uk/src/lib/feedback.ts
Something that came up on the dev call the other day - `address.title` should always be set, `address.single_line_address` may not be set.
As `address.single_line_address` includes postcode, I've used this as the first option.
Going forward it will be nice to roll this logic up in the `Passport()` class in `planx-core` 👍
> fix: Use `address.title` as fallback

- infrastructure/application/Pulumi.staging.yaml
- infrastructure/application/index.ts
- infrastructure/data/Pulumi.staging.yaml
Continues from https://opensystemslab.slack.com/archives/C01E3AC0C03/p1679661932799729
We expect our prior failures were due to actual metabase "database" resources not being picked up in the diff nor updated, even though the stored secrets were rotated. By updating `postgres.Provider("metabaseNew")`, we expect the "provider" to now update and read in the updated root URL.
How we'll merge this: 
- Let CI complete
- Manually deploy data layer
- Merge to automatically deploy application layer
- Test staging on success, or rollback on failure
> build: rotate postgres secrets and update metabase provider

- infrastructure/application/index.ts
if we run `pulumi up --stack staging **--refresh**` in the data layer, we think the original rotation will work without having to update all of metabase
> build: don't change metabase provider yet

- infrastructure/application/index.ts
Reverts theopensystemslab/planx-new#1586
Same failure, see https://github.com/theopensystemslab/planx-new/actions/runs/4596631751
> Revert "build: don't change metabase provider yet"

- infrastructure/application/index.ts
Reverts theopensystemslab/planx-new#1587
We want the original provider for #1588
> Revert "Revert "build: don't change metabase provider yet""

- editor.planx.uk/src/lib/graphql.ts
Hit an issue earlier when rotating db connection details - Hasura returns as `200 OK` if the db connection string is invalid, alongside an error message.
> fix: Show toast on GraphQL error

- editor.planx.uk/src/pages/FlowEditor/lib/__tests__/navigation.test.ts
- editor.planx.uk/src/pages/FlowEditor/lib/store/navigation.ts
testing out a quick new thought I had around how we can correct section statues on reconciliation without needing to calculate whole paths using the breadcrumbs.
because we have distinct statuses and only allow continuous forward travel (eg no jumping ahead to non-consecutive sections), I think we can simply check:
- does more than one section currently have the status "READY TO CONTINUE"?
- if yes, keep that status for the most recently seen section node only (the one latest in order), but update each prior to be "COMPLETED" (because of forward travel rule, it _must_ have all been seen, and if it hasn't because of a content change it will have been already tagged as "NEW INFORMATION NEEDED")
i'm not sure this would hold up as neatly if we introduced all of the original "middle statuses" …
> fix: on reconciliation, previously "completed" sections should still be tagged as "completed" not "ready to continue"

- .github/workflows/toggle-maintenance-page.yml
- scripts/toggle-maintenance-page.sh
GitHub action which toggles the default root object in CloudFront in order to swap in the `error.html` maintenance page and `index.html` page as we're organising planned downtime.
Script tested locally and works using my (staging) AWS credentials, action not tested yet but keen to give it a go once merged against staging.
> feat: Toggle maintenance page GitHub action

- api.planx.uk/errors/ServerError.ts
- api.planx.uk/errors/index.ts
- api.planx.uk/inviteToPay/index.ts
- api.planx.uk/inviteToPay/inviteToPay.test.ts
- api.planx.uk/inviteToPay/inviteToPay.ts
- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- api.planx.uk/server.ts
- api.planx.uk/tests/mocks/inviteToPayData.ts
- api.planx.uk/tests/mocks/inviteToPayMocks.ts
Adds a simple endpoint to initiate a payment request for invite to pay.
Once called, the session will be locked and a payment request will be created.
The caller is responsible for setting which `sessionPreviewKeys` are used to store a `sessionPreviewData` object. The API (via planx-core) looks up those values from a locked session to ensure the stored preview data is available and an accurate reflection of what has been stored on the session.
Change depends on: https://github.com/theopensystemslab/planx-core/pull/7
Notes:
* The endpoint is public and anyone can lock a session that meets the invite to pay criteria.
* A session that has been locked already is currently showing as "session not found". Locked sessions cannot use this feature.
* Currently this doesn't validate breadcrumbs …
> feat: Initial Invite to pay API

- .github/workflows/toggle-maintenance-page.yml
Checked on https://rhysd.github.io/actionlint/ and linter for actions now installed locally 🤞
> fix: GitHub action syntax (again...)

- .github/workflows/push-production.yml
- infrastructure/application/Pulumi.production.yaml
- infrastructure/data/Pulumi.production.yaml
after some trial & error we successfully rotated credentials on staging ([thread here](https://opensystemslab.slack.com/archives/C01E3AC0C03/p1679661932799729)); this PR repeats the process for production. 
**DO NOT MERGE** until scheduled maintenance window is decided ([thread here](https://opensystemslab.slack.com/archives/C5Q59R3HB/p1680531568429899)).
to deploy: 
- first, manually deploy the data layer change by running `pulumi up --stack production` from this branch in the `infrastructure/data` subdirectory
- then, merge this PR to automatically deploy the application layer
- confirm that all services are back up, including custom subdomains
future steps:
- display either error toast or downtime page, but not a blank white screen #1590
- determine why `refresh: true` was added to our …
> infra: rotate postgres root user and metabase roles on production

- api.planx.uk/session/files.test.ts
- api.planx.uk/session/files.ts
- api.planx.uk/session/mocks/passports.ts
- api.planx.uk/webhooks/sanitiseApplicationData/operations.test.ts
The logic and associated tests for `Passport().getFiles()` was originally taken from https://github.com/theopensystemslab/planx-new/pull/1444 and moved to `planx-core` in this PR - https://github.com/theopensystemslab/planx-core/pull/3
This just tidies things up by pointing at the functionality in `planx-core` as opposed to keeping a duplicate of it.
> chore: Tidy up duplicated `getFiles()` logic

- api.planx.uk/send/uniform.ts
Regression introduced here when switching from `fetch` to `axios` - https://github.com/theopensystemslab/planx-new/pull/1551
Axios has a default `maxBodyLength` of 10MB which is increased to 1GB in this PR.
Tested locally - 
- On `main`, zip file greater than 10MB fails to send to Uniform with `Failed to send to Uniform. Error [ERR_FR_MAX_BODY_LENGTH_EXCEEDED]: Request body larger than maxBodyLength limit` error
- On `dp/axios-maxBodyLength` the same payload succeeds and is sent to the Uniform staging environment
> fix: Increase Axios limit to 1GB for Uniform submissions

- hasura.planx.uk/metadata/tables.yaml
- hasura.planx.uk/migrations/1681301564609_add_payment_amount_and_applicant_name/down.sql
- hasura.planx.uk/migrations/1681301564609_add_payment_amount_and_applicant_name/up.sql
- hasura.planx.uk/tests/payment_requests.test.js
This adds `applicant_name` and `payment_amount` to the payment request table.
`applicant_name` is the provided name of the person/company submitting the application on behalf of the nominee.
`payment_amount` is the total application fee payable by the nominated payee.
> feat: Add columns to payment request table

- infrastructure/application/index.ts
should fix issues described here #1617 
refactoring how we handle these (not secret) variables queued up in a separate trello ticket here https://trello.com/c/b1HtcRgM/2371-improve-api-handling-for-configuring-and-sending-govuk-notify-emails
> fix: add Notify templates for pay to Pulumi

- api.planx.uk/inviteToPay/index.ts
- api.planx.uk/inviteToPay/paymentRequest.ts
- api.planx.uk/pay/index.ts
- api.planx.uk/pay/pay.ts
- api.planx.uk/pay/proxy.ts
- api.planx.uk/server.ts
- api.planx.uk/types.ts
This PR adds two API endpoints for managing the invite-to-pay payments. It also includes a refactor of the pay proxy to allow those functions to be reused for invite-to-pay.
Testing is a bit of a pain to set up:
* create a lowcal session
* create a payment request with that lowcal session
* post to the API endpoint https://api.1612.planx.pizza/payment-request/:paymentRequestId/pay?returnURL=https://example.com
* complete the payment by manually navigating to the response's `next_url`
* get the API endpoint https://api.1612.planx.pizza/payment-request/:paymentRequestId/payment/:paymentId using the payment id from the completed payment
Existing pay endpoints should be covered by the end-to-end tests. Do shout if you think that assumption doesn't hold.
> feat: Payment request pay APIs

- editor.planx.uk/src/@planx/components/Pay/Public/Pay.tsx
- editor.planx.uk/src/pages/Pay/MakePayment.tsx
- editor.planx.uk/src/pages/Pay/types.d.ts
This PR introduces a GovPay integration to the MakePayment component for the payee standalone journey.
This depends on #1612 which exposes the APIs this component calls.
The focus for this PR is the make payment functionality - display content and styling can be handled in a follow-up PR (I'd hoped to get to this in this PR but better to merge early so this isn't a blocker).
> feat: Payee make payment functionality

- api.planx.uk/inviteToPay/inviteToPay.test.ts
- api.planx.uk/inviteToPay/inviteToPay.ts
- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- api.planx.uk/saveAndReturn/validateSession.ts
- api.planx.uk/tests/mocks/inviteToPayData.ts
- api.planx.uk/tests/mocks/inviteToPayMocks.ts
Validates that the session flow includes a pay component and that the passport contains a valid payment amount. The payment request will fail to create if a payment amount cannot be found.
Depends on https://github.com/theopensystemslab/planx-core/pull/13
To test, send an API request to set the session as invite to pay with something like this:
```
curl -X POST -H "Content-Type: application/json" -H "Accept: application/json" --data '{ "payeeEmail": "...", "payeeName": "...", "sessionPreviewKeys": [["_address", "title"]] }' https://api.1597.planx.pizza/invite-to-pay/$SESSION_ID
```
> feat: Validate Pay amount for invite-to-pay

- editor.planx.uk/src/@planx/components/Send/bops/__tests__/works.test.ts
- editor.planx.uk/src/@planx/components/Send/bops/index.ts
Follows on from https://github.com/theopensystemslab/planx-new/pull/1581
> fix: Use correct passport variable for BoPS payload `start_date`

- .github/workflows/action-failure.yml
- .github/workflows/pull-request.yml
This introduces a new action which should run when an action fails. 
For now, I'm running on `pull_request` but I think this will actually just be unnecessary noise - we want it just to run on failed staging and prod deploys.
Next steps...
- Merge this to `main` so we can run it
- Open a PR with a failing test to force failure, and triggering of this action
- If this action is triggered, update workflow to run on staging and prod deploys
> feat(ci): Action failure notification

- .github/workflows/pull-request.yml
Action failed due to the following error - `[ERROR] Secret `SLACK_WEBHOOK` is missing. Please add it to this action for proper execution.`
https://github.com/theopensystemslab/planx-new/actions/runs/4699099376/jobs/8332639317
> fix: Inherit secrets in failure notification workflow

- .github/workflows/push-production.yml
- infrastructure/application/Pulumi.production.yaml
- infrastructure/data/Pulumi.production.yaml
Reverts theopensystemslab/planx-new#1634
We were able to successfully deploy the data layer and see the new database URL reflected back, but our existing db connection never went down as expected and the application layer failed to deploy with error (same result with & without `--refresh` flag and IAM user region set): https://github.com/theopensystemslab/planx-new/actions/runs/4728804304/jobs/8390982698
To research next: 
- How to reconcile Pulumi stack changes with actual AWS resources
> Revert "infra: rotate postgres & metabase passwords on aws production" [skip pizza]

- .github/workflows/push-production.yml
Followup to #1638 and this error: https://github.com/theopensystemslab/planx-new/actions/runs/4729176854
> infra: don't refresh on pulumi up on production

- api.planx.uk/helpers.ts
- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- api.planx.uk/server.ts
Follows on from https://github.com/theopensystemslab/planx-new/pull/1185
Neither `passport` not `cookie-session` have yet had an update that addresses this compatibility issue.
This solution was sourced [here](https://github.com/jaredhanson/passport/issues/904#issuecomment-1307558283) and is worth testing on staging as it will allow us to resolve this long running issue if it works.
> chore: Update passport to v0.6.0

- scripts/seed-database/container.sql
followup to #1633 
`pnpm docker:seed` was throwing this error because `domain` was only removed from the `container.sh` script, not `container.sql`  - I admittedly am not sure why both are still needed, seems like something we should look into simplifying - but this fixes local dev environment in short term!
> fix: make sure `teams` seed scripts references same columns

- infrastructure/data/index.ts
ref https://www.pulumi.com/registry/packages/aws/api-docs/rds/instance/
testing questions: 
- should we try rotating the password on staging _again_ to test this? a bit confusing still as only our prod deploy has failed to take effect.
> infra: try passing `applyImmediately` flag to Pulumi for data layer changes

- editor.planx.uk/src/@planx/components/Pay/Public/Confirm.tsx
- editor.planx.uk/src/@planx/components/Pay/Public/Pay.test.tsx
**note: this is not behind the feature flag & will disable the feedback option immediately** 
Alastair & George confirmed that this is both rarely filled out/collected in the learning log and not a particularly relevant roadmap topic, therefore we can remove it.
https://trello.com/c/45whNb0u/2385-99-outstanding-itp-tasks
> chore: remove "other ways to pay" suggestion drawer from Pay component

- editor.planx.uk/src/@planx/components/Pay/Editor.tsx
- editor.planx.uk/src/@planx/components/Pay/Public/Confirm.tsx
- editor.planx.uk/src/@planx/components/Pay/model.ts
A small tweak that came up in conversation with Ian yesterday ! Additionally better aligns other default text to the newest Figma. I expect this is still one of few default content iterations, but will give me a slightly more realistic heirarchy of headers to expect for #1646
> fix: update Pay content copy, add secondary page title to Editor fields

- editor.planx.uk/src/@planx/components/Pay/Editor.tsx
- editor.planx.uk/src/@planx/components/Pay/Public/InviteToPayForm.tsx
- editor.planx.uk/src/@planx/components/Pay/model.ts
better aligns Editior defaults to Figma!
> fix: subheader descriptions shouldn't be required on invite to pay form

- hasura.planx.uk/metadata/tables.yaml
This issue has caught me out on a number of previous occasions... 🤦 
`paid_at` and `govpay_payment_id` columns were added to the `payment_requests` table, but the permissions for the public role was not updated at the same time.
This means that certain pages/routes fail if you're logged out as the public role does not have access to these columns. Both are required to handle payment completion, and to display meaningful data to the user. 
Test links - 
- Nominee confirmation page - https://1670.planx.pizza/buckinghamshire/invite-to-pay-test/pay?paymentRequestId=1a4d21f2-439b-4e3a-a3fa-255f78754ded 
- Applicant confirmation page - https://1670.planx.pizza/buckinghamshire/invite-to-pay-test/pay/invite?paymentRequestId=1a4d21f2-439b-4e3a-a3fa-255f78754ded
If the `INVITE_TO_PAY` feature flag …
> fix: Allow public access (with headers) to new `payment_requests` columns

- editor.planx.uk/src/@planx/components/Pay/Public/InviteToPayForm.tsx
- editor.planx.uk/src/@planx/components/Pay/Public/Pay.test.tsx
Removes browser validation, in favour of validation via Formik
> fix: Standard error handling on `InviteToPayForm`

- api.planx.uk/inviteToPay/sendPaymentEmail.test.ts
- api.planx.uk/notify/routeSendEmailRequest.test.ts
No logical changes here, just a grouping of tests into `describe()` blocks with the template name to allow for simpler debugging when a template is causing an issue.
> test: Add template names to tests for easier debugging

- api.planx.uk/webhooks/sanitiseApplicationData/mocks/queries.ts
- api.planx.uk/webhooks/sanitiseApplicationData/operations.test.ts
- api.planx.uk/webhooks/sanitiseApplicationData/operations.ts
- Ensures that `payment_request` record are deleted after out retention period (currently 6 months)
- Due to the foreign key relationship with `lowcal_sessions` they will get deleted when an associated session is dropped (currently deleted after 1 year, sanitised after 6 months)
- I think an E2E test of the sanitation process (inc. file deletion with minion) would be more robust than the API tests and mocks here - very much a nice to have!
- I've created a `payment_request` record on staging and bumped back it's `created_at` date which should get deleted overnight once this PR is merged - id 
3e9229e8-23ef-40c4-a9e5-0d340da1214e
> chore: Delete payment requests older than retention period

- hasura.planx.uk/migrations/1683197635599_delete_payment_request_events_on_paid/down.sql
- hasura.planx.uk/migrations/1683197635599_delete_payment_request_events_on_paid/up.sql
This trigger and stored procedure cleans up hasura events when `paid_at` is updated to a non-null value.
Testing via direct db manipulation:
1. create a lowcal session
2. create a payment requests for that session
3. Note the creation of pending events at https://hasura.1679.planx.pizza/console/events/one-off-scheduled-events/pending
4. set the `paid_at` field in the payment request to `now()`
5. Note the removal of pending events for that payment request at https://hasura.1679.planx.pizza/console/events/one-off-scheduled-events/pending
> feat: Clean-up ITP emails on changes to `paid_at`

- .github/workflows/pull-request.yml
- e2e/src/flows/sections-flow.ts
- e2e/src/helpers.ts
- e2e/src/save-and-return.spec.ts
- e2e/src/sections.spec.ts
- editor.planx.uk/src/@planx/components/Section/Public.test.tsx
- editor.planx.uk/src/@planx/components/Section/Public.tsx
- editor.planx.uk/src/@planx/components/Section/model.test.ts
- editor.planx.uk/src/@planx/components/Section/model.ts
- editor.planx.uk/src/@planx/components/Send/bops/index.ts
- editor.planx.uk/src/pages/FlowEditor/lib/__tests__/navigation.test.ts
- editor.planx.uk/src/pages/FlowEditor/lib/store/navigation.ts
- editor.planx.uk/src/pages/Preview/ReconciliationPage.tsx
- editor.planx.uk/src/types.ts
This PR changes and adds some new section states: 
Change:
:heavy_minus_sign:  `NotStarted: "CANNOT CONTINUE YET"`
:heavy_plus_sign:  `NotStarted: "CANNOT START YET"`
Change:
:heavy_minus_sign:  `InProgress: "READY TO CONTINUE"`
:heavy_plus_sign:   `ReadyToContinue: "READY TO CONTINUE"`
Additions:
:heavy_plus_sign: `Started: "CANNOT CONTINUE YET"`
:heavy_plus_sign:  `ReadyToStart: "READY TO START"`
These may not be the final text for each sections but the focus of this PR is the functionality for each of these scenarios.
This ticket took a stab at styling the new statuses but any suggestions welcome (or that could be part of the clickable tags PR).
The PR adds some end-to-end tests and updates some unit tests for a `computeSectionStatuses` function. If you spot any scenarios not covered, …
> feat: add all section statuses

- api.planx.uk/pay/pay.ts
- api.planx.uk/server.test.js
- editor.planx.uk/src/pages/Pay/MakePayment.tsx
This PR allows `next_url` links to be passed back to the client when fetching a previous payment. This means that previous payments can be resumed if they are still in an active state.
This changes the Pay proxy but cancelled/abandoned payments in the normal pay journey should continue to work as before.
> fix: Handle abandoned payments

- editor.planx.uk/src/@planx/components/PlanningConstraints/Public.tsx
TPX folks reported the classified roads check was particularly slow on their services which they've been actively demo'ing - https://opensystemslab.slack.com/archives/C5Q59R3HB/p1683742850624589
theoretically the OS data has the same availability in Scotland, but USRNs may work a bit different? 
for now, disabling the extra roads query for any team that is not fetching Digital Land data (eg Scotland and Braintree) so that only their custom planning constraints are shown.  
https://1689.planx.pizza/scotland/check-what-permissions-your-building-project-is-likely-to-need/preview
> fix: disable checking classified roads in scottish services

- editor.planx.uk/src/@planx/components/Section/Public.test.tsx
- editor.planx.uk/src/@planx/components/Section/Public.tsx
- editor.planx.uk/src/@planx/components/shared/Buttons/Tag.tsx
- editor.planx.uk/src/pages/Preview/ReconciliationPage.tsx
This is a response to user research where people sometimes attempt to click the tag instead of the continue button.
Rather than making the tag a full-fledged button (i.e. with accessibility features) my approach here is to retain the emphasis on the "Continue" button as the primary navigation but to also allow the tag to be clickable. I think this adds the least confusion and complexity while allowing user expectations to be met. The tag has a hover state when clickable but otherwise doesn't advertise itself as a button.
**Testing**:
This flow contains sections and a send component: https://1686.planx.pizza/testing/new-sections-test/preview?analytics=false
The "NEEDS UPDATED", "READY TO CONTINUE" and "READY TO START" tags should link to the same location as the "Continue" button. The …
> feat: Make next section tag clickable

- e2e/src/sections.spec.ts
- editor.planx.uk/src/@planx/components/Section/Public.test.tsx
- editor.planx.uk/src/@planx/components/Section/Public.tsx
- editor.planx.uk/src/@planx/components/Send/bops/__tests__/sectionName.test.ts
- editor.planx.uk/src/components/Header.test.tsx
- editor.planx.uk/src/lib/featureFlags.ts
- editor.planx.uk/src/pages/FlowEditor/lib/__tests__/navigation.test.ts
- editor.planx.uk/src/pages/FlowEditor/lib/store/navigation.ts
Removes the `NAVIGATION_UI` feature flag enabling sections for all users.
Here's a flow to test with:
https://1609.planx.pizza/testing/sections-nav-test
https://1609.planx.pizza/testing/sections-nav-test/preview?analytics=false
> chore: Remove `NAVIGATION_UI` feature flag

- api.planx.uk/editor/publish.test.ts
- api.planx.uk/editor/publish.ts
- api.planx.uk/server.ts
- editor.planx.uk/src/pages/FlowEditor/components/PreviewBrowser.tsx
- editor.planx.uk/src/pages/FlowEditor/lib/store/editor.ts
**Validation rules introduced:**
If Invite to Pay is enabled, check that:
- There is at least one Send component
- There is at least one FindProperty (this component type sets `_address` by default)
- There is at least one Checklist that sets the passport variable `proposal.projectType` (we could be more flexible about component type here, but I think Checklist actually makes sense because a) it matches all existing content patterns and b) we expect to parse a _list_ of one or many project types answers)
This validation checks for the _existance_ of these components, but doesn't actually do any path calculations to ensure that all paths that reach the Pay node also are guaranteed to pass through the prior required nodes. That would be an interesting challenge to solve next! 
**Other …
> feat: validate flow content on publish if Invite to Pay is enabled

- api.planx.uk/inviteToPay/sendPaymentEmail.test.ts
- api.planx.uk/inviteToPay/sendPaymentEmail.ts
- api.planx.uk/notify/routeSendEmailRequest.test.ts
- api.planx.uk/saveAndReturn/resumeApplication.test.ts
- api.planx.uk/saveAndReturn/resumeApplication.ts
- api.planx.uk/saveAndReturn/utils.ts
- api.planx.uk/tests/mocks/inviteToPayMocks.ts
- api.planx.uk/tests/mocks/saveAndReturnMocks.ts
- e2e/package.json
- e2e/pnpm-lock.yaml
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
- editor.planx.uk/src/pages/Pay/MakePayment.tsx
- Picks up formatted project types from `planx-core` for Invite to pay, and Save and Return emails
- Updates tests and mocks
> feat: Get formatted project types from `planx-core`

- api.planx.uk/send/email.test.ts
- api.planx.uk/send/email.ts
- api.planx.uk/webhooks/sanitiseApplicationData/mocks/queries.ts
- api.planx.uk/webhooks/sanitiseApplicationData/operations.test.ts
- api.planx.uk/webhooks/sanitiseApplicationData/operations.ts
- api.planx.uk/webhooks/sendNotifications.ts
- hasura.planx.uk/metadata/tables.yaml
- hasura.planx.uk/migrations/1683874331828_create_table_public_email_applications/down.sql
- hasura.planx.uk/migrations/1683874331828_create_table_public_email_applications/up.sql
- hasura.planx.uk/tests/email_applications.test.js
Sets up Slack notifications for "Send to email" production services (will mostly capture activity from Buck's "Report a breach" service!)
**Changes:** 
- Adds `email_applications` audit table, the Slack notification is then configured to trigger on `insert` to this table same as our other send notifications
- Adds introspection tests for `email_applications` (no public access)
- Adds sanitasion operations for `email_applications`
> feat: create an audit table for email submissions and send a slack notification

- editor.planx.uk/src/pages/Preview/Questions.tsx
Every question transition should trigger the scroll position being reset to the top of the page.
> feat: Add scroll to top behaviour

- editor.planx.uk/.storybook/preview-head.html
- editor.planx.uk/src/app.css
The current app imports the following font weights for Inter:
400 regular
600 semi-bold
800 extra-bold
This means that any bold text is being rendered at 800 weight, despite being referred to at bold or 700 weight in the CSS.
PR to correct the imports to be 400, 600, 700.
> FIX: font import weights

- editor.planx.uk/src/@planx/components/Confirmation/Public.tsx
| ![image](https://github.com/theopensystemslab/planx-new/assets/20502206/cf90a1b6-ee5f-4011-bc15-0ebed9fc1481) | ![image](https://github.com/theopensystemslab/planx-new/assets/20502206/158f88f3-4959-476f-9822-3736a134843e) |
Follow up for issue that was introduced in the following PR where the outline was added as a style to the banner - https://github.com/theopensystemslab/planx-new/pull/1669
> fix: Remove duplicated outline on success icon

- api.planx.uk/saveAndReturn/validateSession.test.ts
- api.planx.uk/saveAndReturn/validateSession.ts
- editor.planx.uk/src/@planx/components/Section/Public.tsx
- editor.planx.uk/src/pages/Preview/Questions.tsx
- editor.planx.uk/src/pages/Preview/ReconciliationPage.tsx
- editor.planx.uk/src/pages/Preview/ResumePage.tsx
This change allows sections to behave as expected during reconciliation.
The ResumePage component is no longer competing with the Question component to update state after reconciliation. 
I attempted to solve some of the strange behavior we had noticed around state updating in unexpected ways but it looks like some weird behaviours are rooted in how `upcomingCards` and/or `computePassport` work. 
Here's my current theory about outstanding issues with reconciliation:
It seems that the preemptive auto-answering in `upcomingCards` can create new breadcrumb entries for auto-answerable cards. Reconciliation removes altered breadcrumbs but it doesn't remove breadcrumbs with matching "automations". When `upcomingCards` runs again (and it is called many times) it reconstructs and re-adds the …
> fix: Fix resume state on reconciliation

- editor.planx.uk/src/lib/pay.ts
- editor.planx.uk/src/pages/ErrorPage.tsx
- editor.planx.uk/src/routes/pay.tsx
Adds a custom error page if we're unable to display a payment request. I've gone for a single, generic message as opposed to one for each possible failure method - opinions welcome here!
The copy is just a placeholder, a ticket for content has been generated on the green Trello here - https://trello.com/c/2jSoPczy/1236-write-copy-for-invite-to-pay-error-pages
Please toggle `INVITE_TO_PAY` feature flag to test this.
**Test URLs** (E2E tests of this feature are on another branch incoming shortly)
- Valid payment request link - https://1706.planx.pizza/buckinghamshire/apply-for-a-lawful-development-certificate/pay?paymentRequestId=11c95bc2-b99c-4d81-8b02-7e35a883a3fd
- Missing `paymentRequestId` param - https://1706.planx.pizza/buckinghamshire/apply-for-a-lawful-development-certificate/pay?wr …
> feat: Better error handling for ITP

- e2e/package.json
- e2e/src/context.ts
- e2e/src/create-flow.spec.ts
- e2e/src/login.spec.ts
- e2e/src/pay.spec.ts
- e2e/src/save-and-return.spec.ts
- e2e/src/sections.spec.ts
* Shares context defaults
- adds a new planx testing logo
- uses smoke testing email address (as recommended [here](https://docs.notifications.service.gov.uk/rest-api.html#smoke-testing))
- reduces duplication
* Adds the "@integration" test annotation for test calling 3rd party services
* Adds commands for `test:ours` and `test:integrations` to run annotation sensitive tests
Whether we run every e2e test on every PR change or only a subset is still up for discussion but this PR provides a methodology for setting-up selective test runs.
> chore: Tidy up e2e test context and add test annotations

- api.planx.uk/gis/classifiedRoads.ts
- api.planx.uk/gis/digitalLand.js
- api.planx.uk/gis/local_authorities/metadata/base.js
Fetches metadata using the `Get dataset` endpoint from [planning.data.gov.uk](https://www.planning.data.gov.uk/docs) and appends it to our overall planning constraints response. This enables re-styling the component to be grouped by category and show additional information when expanded.
Splitting off the planning constraints API changes into their own PR for a couple of reasons:
- Appending `metadata`  & `category` properties to the `/gis` endpoint is only additive, it doesn't break the current public display of the component
- Once merged & rebased, this will simplify the original branch (PR #1296) to only include frontend file changes so it's easier for @ianjon3s to come in and share design work of the new accordions
- With this new API structure in place in the background, we can …
> feat: add GIS metadata from planning.data.gov.uk to constraints API

- editor.planx.uk/src/@planx/components/shared/Preview/Card.tsx
something that came up in Sections & Navigation feedback is slow navigation between cards, especially when going "back" to a previous section. this has also been a known issue with rendering the long "Project type" Checklist and when using the "change" link from Review ([ticket](https://trello.com/c/zoYs9u8U/2204-text-input-takes-1s-to-respond-to-keyboard-input)).
i think adding these props very mildly helps, but i honestly didn't come up with a great way to measure this and am definitley still experiencing some lag in my own test runs through LDCs. i think most of our lag is likely still in `handleSubmit` method on "continue", rather than the transition/rendering of the Card itself, which we can turn more attention to in a near-future logic sprint. …
> fix: add transition group props to Card fade

- api.planx.uk/saveAndReturn/validateSession.ts
- api.planx.uk/types.ts
- e2e/src/context.ts
- e2e/src/flows/invite-to-pay-flow.ts
- e2e/src/invite-to-pay/agent.spec.ts
- editor.planx.uk/src/pages/Preview/ResumePage.tsx
- Returns an error from the API when trying to validate a session which is locked
- Returns the associated `payment_request` record for a session
- Displays a warning page, with payment link, for the applicant / agent
- Card created on Green Trello to cross check copy - https://trello.com/b/AfZjkFq0/planx-services-delivery
> fix: Add "locked application" warning, fix E2E tests

- docker-compose.yml
- scripts/seed-database/write/flows.sql
two fixes for bugs I encountered on #1721:
- `flows` & `operations` need aligned versions (flows are copied with their original version from prod, but operations are inserted fresh at v1, so flows needs to be manually updated) or else sharedb will error and flows will fail to load in the editor
- docker images (aka pizzas) should `"include_published_flows"` (previously only staging sync was using this flag) 
- still not sure i understand a scenario where we'd ever _not_ want this behavior on sync, is it more clear to handle `published_flows` same as other tables rather than uniquely?
- i think there was a tricky reason we needed the last _two_ published_flows (save & return reconciliation maybe?) as originally written by gunar, rather than the last _one_ as updated recently - this is one …
> fix: tweak data sync to fix sharedb errors

- api.planx.uk/editor/publish.test.ts
- api.planx.uk/editor/publish.ts
- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
Invite to Pay validation is timing-out and/or running out of memory and a patch for simple validation is currently in place (https://github.com/theopensystemslab/planx-core/pull/36)
This PR applies a different workaround which limits flow that use the ITP feature to only define one Pay node in that flow (corresponding planx-core update here: https://github.com/theopensystemslab/planx-core/pull/38).
Like the Send node restriction, this limit is temporary until we can efficiently traverse the flow graph to find the next node of the matching type.
> Fix: Limit ITP to one Pay node

- editor.planx.uk/src/@planx/components/DrawBoundary/Public/Upload.tsx
- editor.planx.uk/src/@planx/components/DrawBoundary/Public/index.tsx
- editor.planx.uk/src/@planx/components/FileUpload/Public.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Settings/DesignSettings.tsx
- editor.planx.uk/src/ui/Dropzone.tsx
- editor.planx.uk/src/ui/ImgInput.tsx
- editor.planx.uk/src/ui/PublicFileUploadButton.tsx
- editor.planx.uk/src/ui/UploadedFileCard.tsx
A first stab at rationalising some of the duplicated file upload code.
I've focused here on just the `Dropzone` and `FileUploadCard` UI components - there's a lot of duplicated logic left controlling uploads and slots. I'm going to branch off this PR and give that a go as well as I don't think it's too far off - working on a new branch means I can timebox it a bit easier and reviewing should be simpler also.
> feat: Shared file upload UI components

- editor.planx.uk/src/@planx/components/shared/Preview/Card.tsx
- editor.planx.uk/src/@planx/components/shared/Preview/QuestionHeader.tsx
- editor.planx.uk/src/@planx/components/shared/Preview/SaveResumeButton.tsx
- editor.planx.uk/src/components/AnalyticsDisabledBanner.tsx
- editor.planx.uk/src/components/Footer.tsx
- editor.planx.uk/src/components/Header.tsx
- editor.planx.uk/src/components/PhaseBanner.tsx
- editor.planx.uk/src/pages/Preview/Questions.tsx
- editor.planx.uk/src/pages/layout/PublicLayout.tsx
- editor.planx.uk/src/theme.ts
- editor.planx.uk/src/ui/Input.tsx
- editor.planx.uk/src/ui/icons/MoreInfo.tsx
PR is forked from / dependent on font sizes update - https://github.com/theopensystemslab/planx-new/pull/1616 (now merged)
- General tidy up of padding/gutters at smaller breakpoints
- Adding more control over header columns to prevent logo shrinking as viewport width is decreased
- Tidy up of analytics off banner layout
- Tidy up of phase banner layout
- Exporting of line-height and letter-spacing variable from theme.ts for use in components
Visual preview (before/after) of 390px width viewport:
> update: mobile UI tidy up

- editor.planx.uk/src/pages/FlowEditor/components/PreviewBrowser.tsx
I think this is a regression introduced in https://github.com/theopensystemslab/planx-new/pull/1648 that I missed on review
| ![image](https://github.com/theopensystemslab/planx-new/assets/20502206/236bba07-a83f-4a7d-8f23-374c3a410af6) | ![image](https://github.com/theopensystemslab/planx-new/assets/20502206/e28446a6-2202-49c8-8268-a48d0aad7b58) |
> fix: Add padding to `PreviewBrowser`

- editor.planx.uk/src/@planx/components/Pay/Public/Confirm.tsx
Been meaning to get around to the bottom of this one for a while!
> fix: `validateDOMNesting()` warning on Pay component

- editor.planx.uk/src/@planx/components/MultipleFileUpload/Public.tsx
- editor.planx.uk/src/@planx/components/shared/Preview/QuestionHeader.tsx
Conditionally renders the more information icon & sidebar for both the overall component and individual files which have help text defined in the editor.
> feat: show global and per-file help text in MultipleFileUpload component

- api.planx.uk/send/bops.ts
- api.planx.uk/send/email.ts
- api.planx.uk/send/uniform.ts
- api.planx.uk/server.ts
- infrastructure/application/index.ts
An attempt at an immediate fix for recent submission timeouts. This value is set to 60s by default, bumping it to 120s may give us a bit of breathing space to get to the root of the problem.
It's likely that fetching and processing the entire flow on the API is taking longer than it did on the frontend where we already had the flow upfront.
> chore: Bump up API timeout

- editor.planx.uk/src/@planx/components/MultipleFileUpload/Public.tsx
Two changes here for some foundational functionality we can keep building on:
1. Adds a basic error wrapper around the file dropzone if you try to continue before uploading anything - and introduces a basic yup validation schema we can add "real" rules to next
2. Retains previously uploaded files when navigating fowards / back (& on "change" from Review page in future)
> feat: adds basic validation and back/change behavior to MultipleFileUpload

- editor.planx.uk/src/@planx/components/MultipleFileUpload/Editor.tsx
- editor.planx.uk/src/@planx/components/MultipleFileUpload/Public.tsx
- editor.planx.uk/src/@planx/components/MultipleFileUpload/model.test.ts
- editor.planx.uk/src/@planx/components/MultipleFileUpload/model.ts
- Build a `FileList` object based on the current passport and the `FileType` rules built by the Editor
- This structure can (hopefully) do the job of driving the logic for the public facing component
- Not totally sold on a few names here - `FileList` feels pretty vague and generic - thoughts welcome!
> feat: Create `FileList` from passport and parsed `FileType` rules

- editor.planx.uk/src/ui/InputRow.tsx
Visual regression introduced here - https://github.com/theopensystemslab/planx-new/pull/1616/files#diff-13dc74286f2a3643ed730d3b71dbc8ec7fb23a019be0f6c68976c38d9fcc1a6a
I've checked the very few places where `InputRow` is used in the public interface and I can't see a negative effect of dropping this.
> fix(style): `InputRow` length

- editor.planx.uk/src/@planx/components/MultipleFileUpload/Modal.tsx
- editor.planx.uk/src/@planx/components/MultipleFileUpload/Public.tsx
- editor.planx.uk/src/@planx/components/shared/PrivateFileUpload/UploadedFileCard.tsx
- editor.planx.uk/src/theme.ts
Has been feeling good to have small, incremental PRs for MultipleFileUpload to avoid big rebases as we work in parallel, so opening this "starter Dialog" for review now 
What it does so far:
- Opens on clicking "Change" from any uploaded file card, closes on clicking action dialog buttons or outside dialog
- Renders each uploaded file in the dialog
- Very basic initial styling to match Figma like square corners and top border
What it still needs to do: 
- Also open when a file is dropped in the dropzone
- What about on file deletion or validation errors? Quickly realised this was trickier than hooking into existing `useEffect` hook that listens for changes to `slots`, so just started with straightforward option to open on "Change" for now
- Render a dropdown with grouped checklists of …
> feat: add a modal for tagging files in MultipleFileUpload

- editor.planx.uk/src/pages/Preview/ReconciliationPage.tsx
- As of https://github.com/theopensystemslab/planx-new/pull/1701 we no longer return the passport data as part of the response. This is done as the values were already set in state when `resumeSession() is called, and setting twice was leading to conflicts.
- The `SummaryListsBySections` component was relying on the `passport` returned by this response
- Read `passport` from state, not the response
- @builditben (as a follow on PR) to tidy up types of `ReconciliationResponse` on frontend and backend
> fix: Use passport from state for `SummaryListsBySections`

- editor.planx.uk/src/@planx/components/MultipleFileUpload/Editor.tsx
Something I missed in the previous review - I was using `lowerCase()` as a way of splitting the `Condition` enum between words with a space
Docs: https://lodash.com/docs/4.17.15#lowerCase
| <img width="544" alt="image" src="https://github.com/theopensystemslab/planx-new/assets/20502206/72933c12-58c0-41e8-9fed-9b227f1e9579"> | <img width="562" alt="image" src="https://github.com/theopensystemslab/planx-new/assets/20502206/f161207c-40f7-4e57-bbf0-58b224ca3ff1"> |
> fix: Correctly format conditions

- editor.planx.uk/src/@planx/components/Result/Public/ResultReason.tsx
Fixes https://opensystemslab.slack.com/archives/C01E3AC0C03/p1686565382480159
Quickly updated to use `paper` color for all "Reasons". In the future, the band color should match the flag color if the question has an associated flag, or fallback to `paper` if it doesn't have an associated flag? Currently, the `ResultReason` doesn't have access to the flag info; it'll need to join to flow data on `id` in order to set the color.
> fix: Result reasons shouldn't have hardcoded green band

- editor.planx.uk/src/@planx/components/MultipleFileUpload/Public.test.tsx
- editor.planx.uk/src/@planx/components/MultipleFileUpload/Public.tsx
- editor.planx.uk/src/@planx/components/shared/PrivateFileUpload/Dropzone.tsx
Adds the following behaviour to the `MultipleFileUpload` public component - 
- `FileTaggingModal` does not open on component mount
- `FileTaggingModal` opens when a single file is uploaded
- `FileTaggingModal` opens when multiple files are uploaded
- `FileTaggingModal` is not opened when files are deleted
Also a quick a11y fix, and some basic tests for the above cases.
> feat: Automatically open tagging modal when file is uploaded

- e2e/tests/ui-driven/src/invite-to-pay/agent.spec.ts
- e2e/tests/ui-driven/src/invite-to-pay/helpers.ts
- editor.planx.uk/src/@planx/components/Pay/Public/InviteToPayForm.tsx
- editor.planx.uk/src/components/Header.tsx
- editor.planx.uk/src/pages/Pay/InviteToPay.tsx
**Changes made following feedback** (Link: https://trello.com/c/2n0EJ3wA/1635-invite-to-pay-epic) -
- Removed text saying we’ll contact in 24hrs
- Guarded against double payments (https://github.com/theopensystemslab/planx-new/pull/1773)
- Changes warning text about “Continue” button
- Show "Restart application" button on `/pay` pages
- Requested services delivery / content team look at question of copy on the payment confirmation page https://trello.com/c/31xGMIcV/1268-write-copy-for-payment-confirmation-page-invite-to-pay-journeys
**Next steps...**
- Once merged (and https://github.com/theopensystemslab/planx-new/pull/1721 rebased) I'll request POs test again, in particular the double payment issues
- If all ok, we can merge the above PR 🎉 
- There are a few very minor green trello …
> fix: ITP PO feedback

- editor.planx.uk/src/pages/Preview/StatusPage.tsx
> feat: Styled `StatusPage`

- editor.planx.uk/src/@planx/components/MultipleFileUpload/Public.tsx
- editor.planx.uk/src/@planx/components/MultipleFileUpload/mocks.ts
- editor.planx.uk/src/@planx/components/MultipleFileUpload/model.test.ts
- editor.planx.uk/src/@planx/components/MultipleFileUpload/model.ts
- editor.planx.uk/src/@planx/components/MultipleFileUpload/schema.ts
- Changes the `UserFile` type to support have `FileUploadSlot[]` instead of just a single `FileUploadSlot`
- This matches our current file upload data structure, and should work with submissions as-is 🤞
> fix: Support multiple slots per `userFile`

- editor.planx.uk/src/@planx/components/Notice/Public.tsx
PR updates notice component to match Figma designs.
Update prevents a visual conflict between help text icon in upper right of title.
Before (above) and updated (below):
> UPDATE: styling for notice component

- editor.planx.uk/src/pages/FlowEditor/components/Settings/index.tsx
PR add min-height so that editor settings panel spans full height of page.
Before:
After:
> FIX: editor settings panel min-height

- editor.planx.uk/src/@planx/components/DateInput/Public.tsx
> feat: Styled `DateInput`

- editor.planx.uk/src/@planx/components/Calculate/Editor.tsx
> feat: Styled `Calculate`

- editor.planx.uk/src/@planx/components/shared/Preview/SummaryList.tsx
Currently just simply matching file upload style, we can change in future if required.
> feat: Show MFU on `SummaryList`

- editor.planx.uk/src/@planx/components/shared/Preview/Card.tsx
- editor.planx.uk/src/@planx/components/shared/Preview/SaveResumeButton.tsx
PR fixes a visual regression that was causing elements to not inherit the `margin-top` added with a wildcard selector.
The regression appears to have been caused by the move to `styled` as a method, which has changed the specificity of styles in the CSS output. Any elements that bring default styling (in this case `margin: 0` for `<button>` and `<p>`) are overriding the selector used on the container with these styles.
To fix this I have created the margin as a global property that can be applied to elements (`<button>`, `<p>` etc) that carry their own default styling.
> FIX: content flow margins

- editor.planx.uk/src/@planx/components/MultipleFileUpload/Public.tsx
- editor.planx.uk/src/@planx/components/MultipleFileUpload/model.test.ts
- editor.planx.uk/src/@planx/components/MultipleFileUpload/model.ts
- editor.planx.uk/src/@planx/components/MultipleFileUpload/schema.test.ts
- editor.planx.uk/src/@planx/components/MultipleFileUpload/schema.ts
- Allows an applicant to navigate "back" to an MFU component and retain their state
- This was a regression I missed when changing from a single `userFile.slot` to `userFiles.slots` in https://github.com/theopensystemslab/planx-new/pull/1784
- Fixes a few schema validation issues to enforce the following - 
- All user uploaded files must be tagged
- All required fileTypes must have associates slots (also fixed here - https://github.com/theopensystemslab/planx-new/pull/1801#discussion_r1233842550)
> fix: MFU "Back" behaviour

- editor.planx.uk/src/@planx/graph/__tests__/clone.test.ts
- editor.planx.uk/src/@planx/graph/index.ts
will throw during live editing, _not_ on publish - therefore won't flag any pre-existing cloned external portals - but is a proactive guard against the bug raised by George & Alastair here: https://opensystemslab.slack.com/archives/C5Q59R3HB/p1687273389151209
> fix: throw an error if attempting to clone external portals

- editor.planx.uk/src/@planx/components/FileUploadAndLabel/Modal.tsx
- editor.planx.uk/src/@planx/components/shared/PrivateFileUpload/Dropzone.tsx
- editor.planx.uk/src/@planx/components/shared/PrivateFileUpload/UploadedFileCard.tsx
PR addresses a few styling snags for Upload and Label.
- Removes min-height from multi-select wrapper and adds to child clickable div with padding, this addresses an issue where the clickable area was shorter in height than the parent select input. To target this I've had to use the direct child selector (& > div) as the element is injected into the DOM with JavaScript.
- Adds global yellow focus style to multi-select.
- Adds `pointer-events: none` to chips within the multi-select component so they don't block interaction.
- Removes the empty link in the dropzone as this was flagged as an accessibility violation, converted to a span with 'faux' link styling. Interaction is maintained as parent dropzone represents a button.
- Small type update for file size label to `body2`.
> UPDATE: file upload styles

- api.planx.uk/gis/digitalLand.ts
- api.planx.uk/gis/helpers.js
- api.planx.uk/gis/local_authorities/braintree.js
- api.planx.uk/gis/local_authorities/scotland.js
Found this while debugging some multiple file upload logic: `computePassport()` was overriding this and already handling the granularity logic (eg auto-answer "Is it on designated land?" if any one of the `designated.X` constraints is set) on the frontend. 
No reason to explicitly return this via the API anymore - which will then also let us enforce a stricter type since this variable uniquely only had a `value` property. Will make type changes in a followup PR.
> fix: remove single `designated` variable from GIS API response

- editor.planx.uk/src/@planx/components/Question/Public/Question.tsx
- editor.planx.uk/src/theme.ts
PR updates radio styling to prevent mis-alignment at different zoom levels.
- Adjust dot to be an even number in diameter (20px), matching even size of border (40px).
- Use top and left position of 50% to force top-left of dot to centre of element, then translate -50% in both axis to ensure dot sits at centre, rather than rely on pixel spacing to align.
The combination of the above should ensure the dot is central at all zoom levels.
Before (at 75% zoom):
After (at 75% zoom):
> FIX: radio alignment on zoom

- editor.planx.uk/src/components/Header.tsx
- editor.planx.uk/src/components/TestEnvironmentBanner.tsx
- editor.planx.uk/src/routes/flow.tsx
New councils are onboarding to the Editor and we want to avoid hiccups around creating content on staging https://opensystemslab.slack.com/archives/C5Q59R3HB/p1687518232056569
This banner will display on the following pages:
> feat: add a warning banner to non-production environments

- editor.planx.uk/src/@planx/components/Pay/Public/InviteToPayForm.tsx
ITP routing is not working on custom domains. When I invite somebody else to pay, the request is successful, but I'm not routed to the correct confirmation page.
Custom domains do not have the `/preview` suffix on routes - this fix accounts for this by changing the route used based on `isPreviewOnlyDomain`.
> fix: Different ITP routing for custom domains

- editor.planx.uk/src/@planx/components/Pay/Public/InviteToPayForm.tsx
- editor.planx.uk/src/@planx/components/Pay/Public/Pay.test.tsx
Tested by adding `localhost` to the list of preview only domains, and setting it as domain for Bucks locally as well - getting the expected results now for both domain types.
> fix(itp): Handle routing for custom domains

- .github/workflows/pull-request.yml
Proposal for a change to our Github Action CI steps on pull requests:
- Remove Lighthouse; personally wasn't finding much value in this step and don't understand how to parse anything meaningful from the diff, and it occassionally fails
- Wait for 30s before starting healthcheck; this step often fails on first run but succeeds on retry later, this might help!
> ci: remove lighthouse and do healthcheck on delayed start on pull requests

- .github/workflows/pull-request.yml
- scripts/pullrequest/create.sh
This addresses recent CI failures on a number of PRs. See error message thrown by GitHub actions below - 
```
out: Fetched 44.8 MB in 9s (5,227 kB/s)
err: E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/c/cups/libcups2_2.4.1op1-1ubuntu4.2_amd64.deb  404  Not Found [IP: 91.189.91.38 80]
err: E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
err: ./scripts/pull-secrets.sh: line 5: aws: command not found
err: ./scripts/pull-secrets.sh: line 6: aws: command not found
err: ./scripts/pull-secrets.sh: line 7: aws: command not found
out: Complete: Secrets from S3 copied to local machine
err: cat: .env: No such file or directory
```
This PR ran without issue, and did not need to be rebuilt etc to succeed.
> fix(ci): Run `apt-get update` before all other commands

- scripts/pullrequest/create.sh
https://github.com/theopensystemslab/planx-new/pull/1864/files#diff-5ea9e337803948274b694e82fe6c895196b548a3299642155678ebb149f2fe15L21
Now hitting the following CI issues, possibly resolved by adding back this second `apt-get` removed in #1864 
Errors seen on rebase PR here - https://github.com/theopensystemslab/planx-new/actions/runs/5398583470/jobs/9805904969
```
out: Preparing to unpack .../apt-transport-https_2.4.9_all.deb ...
out: Unpacking apt-transport-https (2.4.9) ...
out: Setting up apt-transport-https (2.4.9) ...
out: Running kernel seems to be up-to-date.
out: No services need to be restarted.
out: No containers need to be restarted.
out: No user sessions are running outdated binaries.
out: No VM guests are running outdated hypervisor (qemu) binaries on this host.
out: …
```
> fix: Add back second `apt-get update`

- editor.planx.uk/src/@planx/components/shared/Buttons/Tag.tsx
Fix of a typo from https://github.com/theopensystemslab/planx-new/pull/1837 which was throwing an error in the console.
> fix: Don't pass `tagType` prop to DOM

- .github/dependabot.yml
Really unsure of the syntax here but worth a try...!
At some point we probably do want to migrate to the v3 version, but it's fine to park it for now 
Docs: https://hasura.io/docs/latest/migrations-metadata-seeds/legacy-configs/upgrade-v3/
> chore: Ignore Hasura `cli-migrations-v3` versions

- editor.planx.uk/src/@planx/components/Question/Public.test.tsx
- editor.planx.uk/src/@planx/components/Question/Public/Question.tsx
This fixes a visual regression when taking the following actions - 
- Answer a question
- Go back
- Attempt to change answer
This journey results in the correct, new, answer being selected but there's no visual feedback for the user (the radio button remains unchecked).
This was something missed as part of #1844 - `previousResponseId` is static and calculated on initial of the component, whilst `formik.values.selected.id` is dynamic and updates as users interact with the radio group.
> fix: Handle radio group state

- .github/dependabot.yml
Reverts theopensystemslab/planx-new#1877
This is leading to other PRs failing - reverting for now to take a closer look.
> Revert "chore: Ignore Hasura `cli-migrations-v3` versions"

- infrastructure/application/services/hasura.ts
Currently, these are just retained for 1 day and not 30 like all other services which can make resolving issues a little tricky!
> chore: Keep Hasura CloudWatch logs for 30 days

- editor.planx.uk/src/@planx/components/Result/Public/ResultReason.tsx
- editor.planx.uk/src/@planx/components/shared/Preview/MoreInfo.tsx
- editor.planx.uk/src/ui/Input.tsx
- editor.planx.uk/src/ui/SelectInput.tsx
Fixes https://trello.com/c/Edty1cU8/2502-text-in-text-input-showing-outside-of-box
It appears that under certain conditions (possibly when the parent is not a styled component?) the syntax for applying classes cannot have a space. `$ .classname` is invalid but `$.classname` is.
> fix: Incorrect MUI classes syntax

- editor.planx.uk/src/@planx/components/shared/Preview/MoreInfo.tsx
Over the weekend I noticed the width on the help drawer dialog had stopped applying, and tracked it down to a regression introduced in https://github.com/theopensystemslab/planx-new/pull/1890
This PR reverts that and adds a `max-width` to simplify and prevent overlap at smaller viewports.
> fix: paper drawer width

- editor.planx.uk/src/pages/FlowEditor/components/Settings/ServiceFlags.tsx
> feat: Styled `ServiceFlags`

- editor.planx.uk/src/pages/FlowEditor/components/Settings/TeamSettings.tsx
> feat: Styled `TeamSettings`

- editor.planx.uk/src/ui/Banner.tsx
Fix of a visual regression introduced here - https://github.com/theopensystemslab/planx-new/pull/1862
I've been a bit sloppy and missed a few of these sorry whilst making the update to using `styled()` - I'm sorry about that and thanks @ianjon3s for tidying up behind me!
When using the `sx` prop, MUI should (and generally does) use the theme value for spacing, see example here directly from [MUI docs ](https://mui.com/system/getting-started/the-sx-prop/#spacing) - 
```jsx
<Box sx={{ margin: 2 }} />
// equivalent to margin: theme => theme.spacing(2)
```
The setup here of an `Icon` being passed in as a prop seems to be affecting this default behaviour. I've not found any open issues describing this on the MUI GitHub but will update if I can find an example.
> fix: Banner icon sizing

- editor.planx.uk/src/@planx/components/TaskList/Public.tsx
- editor.planx.uk/src/ui/NumberedList.tsx
PR updates Task List to better match Figma designs. Also makes it more readable on smaller screens and prevents the task number blocking interaction on the container button.
Before:
After:
> UPDATE: styling for task list

- editor.planx.uk/src/@planx/components/Pay/Public/Confirm.tsx
- editor.planx.uk/src/theme.ts
PR fixes the background on the payment banner so that link text is not invisible, also tidies up font sizes.
Misalignment of text is covered in the wider container update PR https://github.com/theopensystemslab/planx-new/pull/1775
Before and after below:
> fix: payment banner background

- editor.planx.uk/src/@planx/components/NextSteps/Editor.tsx
- editor.planx.uk/src/@planx/components/NextSteps/Public.tsx
- editor.planx.uk/src/@planx/components/NextSteps/model.ts
- editor.planx.uk/src/@planx/components/Send/bops/index.ts
- editor.planx.uk/src/@planx/components/shared/Preview/SummaryList.tsx
- editor.planx.uk/src/@planx/components/types.ts
- editor.planx.uk/src/@planx/components/ui.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Flow/components/Node.tsx
- editor.planx.uk/src/pages/FlowEditor/components/forms/FormModal.tsx
- editor.planx.uk/src/pages/FlowEditor/components/forms/index.ts
- editor.planx.uk/src/pages/FlowEditor/data/types.ts
- editor.planx.uk/src/pages/Preview/Node.tsx
PR adds the boilerplate setup for the Next Steps component, based on the work of Jess https://github.com/theopensystemslab/planx-new/pull/1448/files
Bits I'm not sure about:
- Classification of component, I've added under "Question" for now
- Numbering system used in editor.planx.uk/src/@planx/components/types.ts, I've added to the end of the list with sequential number
Pizza preview here:
https://1909.planx.pizza/testing/next-steps-test/preview?analytics=false
> feat: Boilerplate next steps component

- api.planx.uk/inviteToPay/paymentRequest.ts
- api.planx.uk/package.json
- api.planx.uk/pay/pay.ts
- api.planx.uk/pnpm-lock.yaml
- api.planx.uk/send/helpers.ts
- api.planx.uk/types.ts
- e2e/tests/api-driven/package.json
- e2e/tests/api-driven/pnpm-lock.yaml
- e2e/tests/ui-driven/package.json
- e2e/tests/ui-driven/pnpm-lock.yaml
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
- editor.planx.uk/src/@planx/components/Pay/Public/Confirm.tsx
- editor.planx.uk/src/@planx/components/Pay/Public/InviteToPayForm.tsx
- editor.planx.uk/src/@planx/components/Pay/Public/Pay.test.tsx
- editor.planx.uk/src/@planx/components/Pay/Public/Pay.tsx
- editor.planx.uk/src/@planx/components/Pay/model.ts
- editor.planx.uk/src/@planx/components/Send/bops/index.ts
- editor.planx.uk/src/pages/FlowEditor/lib/store/preview.ts
- editor.planx.uk/src/pages/Pay/MakePayment.tsx
- editor.planx.uk/src/pages/Preview/Node.tsx
- editor.planx.uk/src/types.ts
- hasura.planx.uk/metadata/tables.yaml
- hasura.planx.uk/migrations/1688457221159_alter_table_public_payment_status_add_column_payment_amount/down.sql
- hasura.planx.uk/migrations/1688457221159_alter_table_public_payment_status_add_column_payment_amount/up.sql
- Imports types from planx-core (relies on https://github.com/theopensystemslab/planx-core/pull/52)
- Adds new `payment_status.amount` column
- Adds relationship between `lowcal_sessions` and `payment_status` tables
---
Adding the relationship here allows us to query like this - 
We could also make this a computed field on `lowcal_sessions` which may be simpler, but also less discoverable.
I think we'll just need to update this query once so this feels like the right approach but happy to re-evaluate if we end up repeating it.
> chore: Add `payment_status.amount` column 

- editor.planx.uk/src/@planx/components/Confirmation/Public.tsx
- editor.planx.uk/src/@planx/components/FileUploadAndLabel/Public.tsx
- editor.planx.uk/src/@planx/components/Notice/Public.tsx
- editor.planx.uk/src/@planx/components/Pay/Public/Confirm.tsx
- editor.planx.uk/src/@planx/components/Pay/Public/InviteToPayForm.tsx
- editor.planx.uk/src/@planx/components/PlanningConstraints/List.tsx
- editor.planx.uk/src/@planx/components/PlanningConstraints/Public.tsx
- editor.planx.uk/src/@planx/components/PropertyInformation/Public.tsx
- editor.planx.uk/src/@planx/components/Result/Editor.tsx
- editor.planx.uk/src/@planx/components/Result/Public/index.tsx
- editor.planx.uk/src/@planx/components/Section/Public.tsx
- editor.planx.uk/src/@planx/components/shared/Preview/MoreInfoSection.tsx
- editor.planx.uk/src/@planx/components/shared/Preview/QuestionHeader.tsx
- editor.planx.uk/src/@planx/components/shared/Preview/SummaryList.tsx
- editor.planx.uk/src/components/ErrorFallback.tsx
- editor.planx.uk/src/components/Header.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Settings/DataManagerSettings.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Settings/DesignSettings.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Settings/ServiceFlags.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Settings/ServiceSettings.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Settings/TeamSettings.tsx
- editor.planx.uk/src/pages/GlobalSettings.tsx
- editor.planx.uk/src/pages/Pay/InviteToPay.tsx
- editor.planx.uk/src/pages/Preview/ReconciliationPage.tsx
- editor.planx.uk/src/pages/Team.tsx
- editor.planx.uk/src/pages/Teams.tsx
- editor.planx.uk/src/theme.ts
- editor.planx.uk/src/ui/ExpandableList.tsx
- editor.planx.uk/src/ui/NumberedList.tsx
- editor.planx.uk/src/ui/Palette.stories.tsx
PR updates heading tags to be sequential throughout the app.
Currently the theme and component files contain no `<h2>`, meaning that styles go straight from `<h1>` to `<h3>`.
PR bumps all styles from h3–6 up to h2–5, specifying or removing `component="x"` wherever necessary to maintain sequential headings in the DOM.
> chore: Update font sizes to linear numbers

- hasura.planx.uk/tests/package.json
- hasura.planx.uk/tests/pnpm-lock.yaml
Replaces https://github.com/theopensystemslab/planx-new/pull/1927
`pnpm update`, `pnpm audit --fix`, `pnpm i` on the Hasura tests directory.
> chore: Update Hasura tests dependencies (minor and patch)

- sharedb.planx.uk/package.json
- sharedb.planx.uk/pnpm-lock.yaml
Replaces https://github.com/theopensystemslab/planx-new/pull/1919
`pnpm update` followed by `pnpm audit --fix && pnpm i` in ShareDB project
> chore: Update ShareDB dependencies (minor and patch)

- e2e/package.json
- e2e/pnpm-lock.yaml
- e2e/tests/api-driven/package.json
- e2e/tests/api-driven/pnpm-lock.yaml
- e2e/tests/ui-driven/package.json
- e2e/tests/ui-driven/pnpm-lock.yaml
Closes https://github.com/theopensystemslab/planx-new/pull/1921
`pnpm update` and `pnpm audit --fix && pnpm i` in E2E projects.
> chore: Update E2E dependencies (minor and patch)

- editor.planx.uk/src/@planx/components/FileUploadAndLabel/Modal.tsx
- editor.planx.uk/src/@planx/components/FileUploadAndLabel/Public.test.tsx
- editor.planx.uk/src/@planx/components/FileUploadAndLabel/Public.tsx
https://github.com/theopensystemslab/planx-new/assets/20502206/23b7d2d1-4164-43e7-b40f-e15bab3d1d20
- Add additional validating of `FileList` on "Done"
- Still allow users to exit modal with errors (click away or `Esc`) for a11y - validation will catch any issues on "Continue"
- As with the current component, validation of for the entire state and not "per file" so the warning is at a global level
- `ErrorWrapper` is moved to a more prominent location on the main component
> feat: Basic validation in 'Upload and label' modal

- .github/dependabot.yml
- IaC code has numerous dependencies major versions behind
- Updating and testing these is difficult as it can only be done on staging / production
- Testing here will be slow and could hold up CI pipelines whilst we work issues out
- Close open dependabot infra PRs
- Document and use Sandbox environment (https://trello.com/c/H3mGuTjL/2497-document-and-turn-off-aws-sandbox-environment)
- Update dependencies as it's own task, test on Sandbox (https://trello.com/c/U2Lmt4oK/2280-upgrade-infrastructure-dependencies)
- Once looking good, merge to staging
- Turn dependabot back on
> chore: Temporarily turn off dependabot for IaC

- editor.planx.uk/src/@planx/components/Checklist/Public.tsx
- editor.planx.uk/src/@planx/components/Confirmation/Public.tsx
- editor.planx.uk/src/@planx/components/FileUploadAndLabel/Public.tsx
- editor.planx.uk/src/@planx/components/Pay/Public/Confirm.tsx
- editor.planx.uk/src/@planx/components/PropertyInformation/Public.tsx
- editor.planx.uk/src/@planx/components/Question/Public/Question.tsx
- editor.planx.uk/src/@planx/components/Result/Public/ResultSummary.tsx
- editor.planx.uk/src/@planx/components/shared/Preview/Card.tsx
- editor.planx.uk/src/@planx/components/shared/Preview/MapContainer.tsx
- editor.planx.uk/src/@planx/components/shared/Preview/QuestionHeader.tsx
- editor.planx.uk/src/components/AnalyticsDisabledBanner.tsx
- editor.planx.uk/src/components/Footer.tsx
- editor.planx.uk/src/components/Header.tsx
- editor.planx.uk/src/components/PhaseBanner.tsx
- editor.planx.uk/src/components/TestEnvironmentBanner.tsx
- editor.planx.uk/src/pages/FlowEditor/components/PreviewBrowser.tsx
- editor.planx.uk/src/pages/Pay/InviteToPay.tsx
- editor.planx.uk/src/pages/Pay/MakePayment.tsx
- editor.planx.uk/src/pages/Preview/Questions.tsx
- editor.planx.uk/src/theme.ts
- editor.planx.uk/src/themeOverrides.d.ts
- editor.planx.uk/src/ui/Banner.tsx
- editor.planx.uk/src/ui/FormWrapper.tsx
PR aims to simplify and unify the container system.
- Adds two new media queries, `contentWrap` for page-level containers and `formWrap` to use as a max-width for form content.
- Adds MUI `<Container>` to all page level items to unify padding and max-widths.
- Sets global padding for `<Container>` at theme level.
- Removes `getHeaderPadding` property as this is inherited from containers.
- Uses wildcard selector (`& > *`) to apply max-width to form items in `Card.ts`, and targeted styles to set the following to full-width: Upload and label, maps, radio and checkbox with description and/or images.
- Adds targeted max-widths to invite-to-pay hardcoded content.
> feat: Page container / layout restructure

- editor.planx.uk/src/@planx/components/AddressInput/AddressInput.stories.tsx
Follow up from conversation here - https://github.com/theopensystemslab/planx-new/pull/1910#discussion_r1254053772
I did a bit of reading up on Storybook v7 and TypeScript integration and this pattern looks like it works. We end up inheriting the expected props without everything being optional or having `| undefined` appended to its types. Docs / blog post here - https://storybook.js.org/blog/improved-type-safety-in-storybook-7/
Might be worth pulling this branch down @jessicamcinchak and just double checking that this works as expected.
If so I'm happy to go through and update v7 stories, or it can be picked up on your branch - whatever works 🙂
> chore: TS annotations for Storybook v7

- editor.planx.uk/src/@planx/graph/__tests__/update.test.ts
- editor.planx.uk/src/@planx/graph/index.ts
New PR cherry-picked from https://github.com/theopensystemslab/planx-new/pull/1952 to avoid rebase headaches! 🍒 
- Fixes a bug in `_update()` where updates in an array in `node.data` is not handled correctly
- This bug results in arrays incorrectly getting a `remove` patch / operation when another property of the node is updated. See video below for demonstration of this on the `TaskList` component - 
https://github.com/theopensystemslab/planx-new/assets/20502206/05a1841a-14f0-4925-ad48-3ffc5fb9040c
Helpful model to have in mind here - I wasn't super familiar with this aspect of the codebase.
```mermaid
sequenceDiagram
participant Editor
participant Immer
participant convert as convertPatchesToOps()
participant ShareDB Client
participant ShareDB Service
participant Postgres …
```
> fix: Handle arrays when updating node data

- editor.planx.uk/src/pages/FlowEditor/lib/__tests__/preview.test.ts
- editor.planx.uk/src/pages/FlowEditor/lib/store/shared.ts
- editor.planx.uk/src/pages/Preview/StatusPage.tsx
- editor.planx.uk/src/utils.ts
Bug spotted here with notes on how to re-create: https://opensystemslab.slack.com/archives/C4B0CKQ3U/p1689144968660159
Changes:
- `resetPreview` store method clears `saveToEmail` in addition to `sessionId`
- `resetPreview` store method should remove the `sessionId` search param from the URL if it exists
Testing:
- it works on both save & return sessions when `saveToEmail` & `sessionId` search param are defined and with local storage when they're not
> fix: Notice "Back to start" should reset `saveToEmail` and `sessionId`

- editor.planx.uk/src/ui/ReactMarkdownOrHtml.tsx
PR fixes a regression where markdown was been rendered as source code in the planning constraints component.
Not an ideal solution but could work as a patch for now.
> fix: HTML or markdown detection

- editor.planx.uk/src/components/AnalyticsDisabledBanner.stories.tsx
- editor.planx.uk/src/components/DelayedLoadingIndicator.stories.tsx
- editor.planx.uk/src/components/ErrorFallback.stories.tsx
- editor.planx.uk/src/components/Footer.stories.tsx
- editor.planx.uk/src/components/Header.stories.tsx
- editor.planx.uk/src/components/TestEnvironmentBanner.stories.tsx
- editor.planx.uk/src/ui/Banner.stories.tsx
- editor.planx.uk/src/ui/Checkbox.stories.tsx
- editor.planx.uk/src/ui/ChecklistItem.stories.tsx
- editor.planx.uk/src/ui/CollapsibleInput.stories.tsx
- editor.planx.uk/src/ui/ColorPicker.stories.tsx
- editor.planx.uk/src/ui/DateInput.stories.tsx
- editor.planx.uk/src/ui/DescriptionList.stories.tsx
- editor.planx.uk/src/ui/ExpandableList.stories.tsx
- editor.planx.uk/src/ui/ExternalPlanningSiteDialog.stories.tsx
- editor.planx.uk/src/ui/FileDownload.stories.tsx
- editor.planx.uk/src/ui/ImgInput.stories.tsx
- editor.planx.uk/src/ui/Input.stories.tsx
- editor.planx.uk/src/ui/InputField.stories.tsx
- editor.planx.uk/src/ui/OptionButton.stories.tsx
- editor.planx.uk/src/ui/Palette.stories.tsx
- editor.planx.uk/src/ui/Radio.stories.tsx
- editor.planx.uk/src/ui/RichTextInput.stories.tsx
- editor.planx.uk/src/ui/SelectInput.stories.tsx
- editor.planx.uk/src/ui/VisibilityToggle.stories.tsx
Filling in a lot of gaps here, but haven't really sweated what's best categorised as a "Molecule", an "Atom" or otherwise yet - I figure we can revisit that more comprehensively later once we have better component coverage.
My general approach here is:
- Update type annotations & naming in existing stories
- Add new stories for un-documented components
- "Form elements" typically just get a "Basic" story, maybe an additional "With Error" story if applicable
> chore: update Storybook components [Design System / Atoms and Molecules]

- README.md
- editor.planx.uk/README.md
"Production" Storybook is deploying from Netlify again on every commit to `main`. This PR adds Storybook links to our READMEs. 
See:
- https://app.netlify.com/sites/planx-storybook/overview
- https://storybook.planx.uk/
One-time changes I made to Netlify site configuration include: 
- Set build environment variables `NODE_VERSION`, `PNPM_VERSION`, `CI=false` to match planx-new settings
- Update build command from `npm run storybook-build` to `pnpm storybook-build`
- Update build directory from `./storybook-static` to `./build/storybook` 
- Setup Slack notifications to `#planx-notifications-internal` on failed deploys
> fix: update READMEs with production Storybook links

- e2e/tests/api-driven/src/invite-to-pay/helpers.ts
- e2e/tests/ui-driven/src/context.ts
- e2e/tests/ui-driven/src/helpers.ts
- e2e/tests/ui-driven/src/invite-to-pay/helpers.ts
- e2e/tests/ui-driven/src/invite-to-pay/mocks.ts
Told Mel earlier in the week I'd sort this...! 
An outstanding E2E test was sending emails to `testAgent@opensystemslab.io` which was then being forwarded to `enquiries@opensystemslab.io`.
> fix: Stop sending E2E emails to enquiries inbox

- editor.planx.uk/src/@planx/components/NextSteps/Editor.tsx
- editor.planx.uk/src/@planx/components/NextSteps/NextSteps.stories.tsx
- editor.planx.uk/src/@planx/components/NextSteps/Public.test.tsx
- editor.planx.uk/src/@planx/components/NextSteps/Public.tsx
- editor.planx.uk/src/@planx/components/NextSteps/model.ts
- editor.planx.uk/src/ui/NextStepsList.tsx
- pnpm-lock.yaml
PR adds a new component named Next Steps.
I've constructed this using examples from other components. 
Bits I'm not sure on so far:
- The component does not have a continue button and I've tried to set this up accordingly, using the Confirmation component as an example.
- ~~The URL field is currently a text field, I'm expecting this should have a `type="url"` property added with validation, but wasn't sure how to bring this in.~~ update: added `type="url"`
- Model.ts has the commented text `/* remove once migrated */`, which was copied over from another file, does this need addressing? https://github.com/theopensystemslab/planx-new/pull/1957/files#diff-99e03f9ab40b152de3dbfa281c5ae664df487266dee9594485d388d0b4ae221cR18
Working example: …
> feat: Next steps component build

- editor.planx.uk/src/@planx/components/Result/Public/index.tsx
- editor.planx.uk/src/@planx/components/shared/Preview/WarningContainer.tsx
PR updates the disclaimer shown after a flow result to be inline with the notice styling.
I've also removed the "read more/less" toggle from this as it appears to be redundant, happy to reinstate if there is a valid use-case for this being here.
Previews of before (left) & after (right):
> feat: update disclaimer styling

- editor.planx.uk/src/@planx/components/FileUploadAndLabel/Modal.tsx
- editor.planx.uk/src/@planx/components/FileUploadAndLabel/Public.test.tsx
This came out of PO testing feedback: 
Previously:
- Upload one file, the tagging modal opens, select 1 or many "Required files" checkboxes
- Click “Done” in modal and throws error “All required files must be tagged”. 
- Clicking away from Modal still closes it successfully, but as a user I don't understand this is an option
- Clicking "Done" throws error that confuses me because I want to close it and upload my second file. I have to select incorrect checkboxes to proceed through "Done"
This wasn't noticeable if you drag many files into dropzone at same time and tag all at same time, or if you upload a single file that satisfies all requirements in one go. But if you're uploading one-by-one and focused on navigating with buttons, it's confusing! 
Now:
- Only validate on "Continue", …
> fix: don't validate that all required files are tagged yet when clicking modal "Done" 

- api.planx.uk/Dockerfile
- hasura.planx.uk/Dockerfile
- hasura.planx.uk/proxy/Caddyfile
- hasura.planx.uk/proxy/Dockerfile
- infrastructure/application/index.ts
- infrastructure/application/package.json
- infrastructure/application/services/hasura.ts
- sharedb.planx.uk/Dockerfile
- Remove HTTP -> HTTPS forwarding on AWS, and turn on CloudFlare proxying. See [docs here](https://developers.cloudflare.com/ssl/troubleshooting/too-many-redirects/#flexible-encryption-mode).
> If your domain’s encryption mode is set to [Flexible](https://developers.cloudflare.com/ssl/origin-configuration/ssl-modes/flexible/), Cloudflare sends unencrypted requests to your origin server over HTTP.
>
> Redirect loops will occur if your origin server automatically redirects all HTTP requests to HTTPS.
>
> To solve this issue, either **remove HTTPS redirects from your origin server** or update your SSL/TLS Encryption Mode to be [Full](https://developers.cloudflare.com/ssl/origin-configuration/ssl-modes/full/) or higher (requires an SSL certificate configured at your origin server).
- Fix …
> feat(ci): CloudFlare proxy for Hasura console

- api.planx.uk/admin/session/summary.test.ts
- api.planx.uk/admin/session/summary.ts
- api.planx.uk/server.ts
Was thinking about this yesterday when troubleshooting the recent LDC apps with George. This offers a quicker alternative than going directly into the Hasura console to check the `lowcal_sessions` table and is a link we could share with any Editor admin going forward rather than exporting/passing along CSVs or JSON files.
We can keep buildng on the format of this return response. 
Admin endpoints will be behind Cloudflare's Zero Trust soon for restricted access by email and WARP client connection.
> feat: general `admin/session/:sessionId/summary` endpoint for debugging

- editor.planx.uk/src/@planx/components/Checklist/Public.tsx
- editor.planx.uk/src/@planx/components/Content/Public.tsx
- editor.planx.uk/src/@planx/components/DrawBoundary/Public/index.tsx
- editor.planx.uk/src/@planx/components/FileUploadAndLabel/Modal.tsx
- editor.planx.uk/src/@planx/components/FileUploadAndLabel/Public.tsx
- editor.planx.uk/src/@planx/components/FindProperty/Public/Autocomplete.tsx
- editor.planx.uk/src/@planx/components/FindProperty/Public/index.tsx
- editor.planx.uk/src/@planx/components/Question/Public/Question.tsx
- editor.planx.uk/src/@planx/components/Result/Public/ResultReason.tsx
- editor.planx.uk/src/@planx/components/Result/Public/index.tsx
- editor.planx.uk/src/@planx/components/Section/Public.tsx
- editor.planx.uk/src/@planx/components/shared/Preview/MapContainer.tsx
- editor.planx.uk/src/@planx/components/shared/PrivateFileUpload/Dropzone.tsx
- editor.planx.uk/src/components/AnalyticsDisabledBanner.tsx
- editor.planx.uk/src/components/TestEnvironmentBanner.tsx
- editor.planx.uk/src/pages/Preview/ReconciliationPage.tsx
- editor.planx.uk/src/theme.ts
- editor.planx.uk/src/ui/FullWidthWrapper.tsx
- editor.planx.uk/src/ui/ReactMarkdownOrHtml.tsx
PR updates and fixes a number of mobile specific styles, following extensive mobile QA.
- Updates default "factor" for responsive font resizing
- Adds small button size
- Adds missing `<Typography>` where needed
- Adjusts margins and padding of numerous components to unify layout
- Changes hierarchy of `<MapContainer>` and `<MapFooter>` to prevent overlap on smaller screens
- Adds a `nowrap` span to red line size indicator to keep units (m²) on same line as number
Size comparison before (left) & after (right)
> feat: mobile styles update

- editor.planx.uk/src/ui/ReactMarkdownOrHtml.tsx
PR fixes heading text sizing. Small headers shown below:
> fix: heading styling in rich text

- editor.planx.uk/src/@planx/components/shared/PrivateFileUpload/Dropzone.tsx
Accessibility fix: missing input label on dropzone component.
PR adds an `aria-labelledby` tag to the input, referencing the input button text.
> fix: missing input label on dropzone

- .github/dependabot.yml
The intention here was to drop these intervals once this was setup - hopefully this will make things less noisy. If not we'll keep tweaking these as we go forwards.
Security updates from dependabot will ignore these intervals.
I've not yet seen any updates come through for `/api.planx.uk` or `/editor.planx.uk` so lets see if this gets picked up sometime soon.
> chore: Change dependabot settings

- scripts/pull-secrets.sh
Currently causing CI to fail. I did re-run all jobs on https://github.com/theopensystemslab/planx-new/pull/2005 after making this change and all jobs passed - GitHub actions must have been using a cache from a previous run.
This works locally for me, and if this PR succeeds it also works on CI.
> fix: Fix `pull-secrets.sh`

- .github/workflows/pull-request.yml
- scripts/pull-secrets.sh
The reasons I've been hitting issues here is because the `$CI` env var is set to `true` on GitHub actions, but not on Vultr which we ssh onto and then re-run the `pull-secrets.sh` script.
> fix: Fix `pull-secrets.sh` (again)

- hasura.planx.uk/metadata/tables.yaml
- hasura.planx.uk/migrations/1690531868914_add_session_payment_computed_field/down.sql
- hasura.planx.uk/migrations/1690531868914_add_session_payment_computed_field/up.sql
- hasura.planx.uk/tests/sessions.test.js
Sessions should fetch a `payment_id` from a successful payment in the payment status table (discussed here: [doc/architecture/decisions/0006-remove-govukpayment-from-session-data.md](https://github.com/theopensystemslab/planx-new/blob/main/doc/architecture/decisions/0006-remove-govukpayment-from-session-data.md)).
This PR adds a computed field for the `sessions` table to fetch the id of the latest successful payment.
I believe this should work for invite-to-pay journeys too since the payment_status audit table is updated using the original lowcal_session id (an identical ID will be used for entries in the sessions table).
> feat: Add payment_id computed field on sessions

- api.planx.uk/gis/digitalLand.ts
- api.planx.uk/gis/helpers.js
- api.planx.uk/gis/local_authorities/braintree.js
- api.planx.uk/gis/local_authorities/scotland.js
manually reverts #1821 
for testing by August & George, see this thread: https://opensystemslab.slack.com/archives/C5Q59R3HB/p1690462520855369
this was only working for sites that have at least one true constraint, not if all constraint values are part of `_nots` - which seems to break our passport granularity checks
> fix: revert omission of `designated` variable in GIS response

- editor.planx.uk/src/@planx/components/shared/Radio/BasicRadio.tsx
- editor.planx.uk/src/@planx/components/shared/Radio/ImageRadio.tsx
- editor.planx.uk/src/theme.ts
PR fixes an issue with vertical spacing in radio buttons. Padding is applied to the radio button icon rather than the element itself, meaning if text labels are taller than the button icon there is no space between the text.
Small spacing adjustment also made to `ImageRadio` to compensate (no adjustment needed for `DescriptionRadio`).
Example before (left) and after (right):
> fix: radio label spacing

- editor.planx.uk/src/@planx/components/shared/Preview/MoreInfo.tsx
- editor.planx.uk/src/@planx/components/shared/Preview/MoreInfoSection.tsx
- editor.planx.uk/src/theme.ts
PR improves the usability of the 'more info' drawer.
Updates:
- Change position of close button to `fixed` so that it remains in place on scroll. This is especially needed for larger amounts of content on smaller screens, where there isn't the option to 'click outside' to close, and after reading content the user must scroll back to the top of the dialog to close.
- Increase contrast of close button.
- Bring `<Container>` into the dialog for more consistent and responsive gutters.
- Reduce heading font sizes so they form more readable content.
- Update `font-weight` of `<h3>`, this was missed when the numbers were incremented to make of use of the previously unused `<h2>` size.
Example to come once a pizza link is generated.
> feat: improve usability of more info drawer

- editor.planx.uk/src/@planx/components/Content/Public.test.tsx
- editor.planx.uk/src/@planx/components/Content/Public.tsx
- editor.planx.uk/src/@planx/components/Notice/Public.tsx
PR fixes a regression where the text of the notice component is outputting as the primary theme colour instead of a black/white contrast to the background.
Before:
After:
> fix: notice component text colour

- editor.planx.uk/src/@planx/components/Pay/Public/Confirm.tsx
- editor.planx.uk/src/pages/Preview/ReconciliationPage.tsx
- editor.planx.uk/src/pages/Preview/ResumePage.tsx
- editor.planx.uk/src/pages/Preview/StatusPage.tsx
- editor.planx.uk/src/theme.ts
Watching Jess reveal the 'hard-to-reach' pages in this mornings demo, I realised that there were several pages that had missed out on the style update.
PR updates banner background colour, type sizes and spacing to tidy up the resume pages.
**Before:**
https://storybook.planx.uk/?path=/docs/design-system-pages-resume--docs
**After:**
https://storybook.2058.planx.pizza/?path=/docs/design-system-pages-resume--docs
> feat: tidy up resume pages

- editor.planx.uk/src/@planx/components/shared/FeedbackInput.tsx
- editor.planx.uk/src/ui/CollapsibleInput.stories.tsx
- editor.planx.uk/src/ui/CollapsibleInput.tsx
Accessibility fix: missing input label on collapsable feedback input.
PR adds an `aria-label` to the input, referencing the input button text.
> fix: missing input label on feedback

- infrastructure/application/index.ts
- infrastructure/application/services/hasura.ts
- infrastructure/application/utils/addListenerRule.ts
The following URLs are no longer exposed and should redirect to `plan.in` domains which is proxied via CloudFlare - 
- http://sharedb-f3c94f4-2023684948.eu-west-2.elb.amazonaws.com →→→ https://sharedb.planx.in
- http://hasura-79e5fd6-2123067927.eu-west-2.elb.amazonaws.com →→→ https://hasura.planx.in
- http://metabase-ca18194-269509255.eu-west-2.elb.amazonaws.com →→→ https://metabase.planx.in
- http://api-b0a0d39-1647464175.eu-west-2.elb.amazonaws.com →→→ https://api.planx.in
You can confirm the redirect by...
- checking the network activity for a 301 or 426 status
- checking the new URL in the browser
- checking the response headers (set in CloudFlare) for the `{ Daf-Test: "hello world" }` header as further proof we're proxying via CF! (I'll remove this once the PR is merged)
> feat(iac): Redirect ELB traffic to CloudFlare DNS

- editor.planx.uk/src/@planx/components/Section/Public.tsx
- editor.planx.uk/src/@planx/components/Section/Section.stories.tsx
I spent some time trying to resolve this using Zustand stores without much luck within the Storybook components. I think in order to get this to work we'd need to use a Provider approach, similar to what's outlined here - 
This would be a big refactor and I'm unsure of the real benefit for the effort involved.
I've gone for just a stateless wrapper component to simplify the visual testing of the "Section" component.
> feat: Basic `Section` stories

- api.planx.uk/pay/pay.ts
A few API errors have come through without meaningful context, hopefully this helps. Example - https://planx.airbrake.io/projects/329753/groups/3596064650871018548
> chore: Enrich GovPay API error messages

- api.planx.uk/admin/session/html.test.ts
- api.planx.uk/hasura/metadata/index.ts
See Axios docs - https://github.com/axios/axios#handling-errors
We can get a more useful error object with `.toJSON()` - trying this as a first pass as we're currently getting an unhelpful `500 internal server error`
> chore(api): Improve error logging for Hasura Metadata API

- api.planx.uk/hasura/schema/index.ts
Complements https://github.com/theopensystemslab/planx-new/pull/2069
The schema API is also failing with 403 errors when running the `deleteHasuraEventLogs` and `deleteHasuraScheduledEventsForSubmittedSessions` operations - hopefully this will give us a bit more insight.
> chore: Improve Schema API logging

- infrastructure/certificates/package.json
- infrastructure/certificates/pnpm-lock.yaml
https://github.com/theopensystemslab/planx-new/security/dependabot/31 remained open following https://github.com/theopensystemslab/planx-new/pull/1235
When running `pnpm why protobufjs` in the `/infrastructure/certificates` layer we were still getting results for affected versions - the autogenerated version syntax from `pnpm audit --fix` didn't appear to be working as expected.
I've manually changed it to just override all versions, instead of using the autogenerated `@>=6.10.0 <7.2.4` syntax.
> chore: Override protobufjs

- api.planx.uk/hasura/metadata/index.ts
- api.planx.uk/hasura/schema/index.ts
It's likely there's a better medium-term way of achieving this (`axiosError.cause.message` or `axiosError.response.data`) but right now I'd just like to see the entire object to try and work out what's going on.
> chore: Stringify Axios errors

- infrastructure/application/Pulumi.production.yaml
- infrastructure/application/Pulumi.sandbox.yaml
- infrastructure/application/Pulumi.staging.yaml
An offboarding step :white_check_mark: Hasura console access is restricted via zero trust now, but rotation ensures a dev couldn't connect to a GraphQL client directly.
> chore: rotate `hasura-admin-secret` across all Pulumi/AWS environments

- infrastructure/data/Pulumi.staging.yaml
will need to be manually deployed as its part of the data layer. follow-up PRs for production & sandbox after confirming this works.
> chore: rotate `db-password` for Pulumi staging

- infrastructure/data/Pulumi.staging.yaml
Reverts theopensystemslab/planx-new#2089
CLI output when running `pulumi --up --stack staging --refresh` in `/infrastructure/data`
```
Previewing update (staging)
Updating (staging)
View in Browser (Ctrl+O): https://app.pulumi.com/planx/data/staging/updates/24
Type                             Name                      Status           Info
pulumi:pulumi:Stack              data-staging                               
~   ├─ pulumi:pulumi:StackReference  planx/networking/staging  refresh (1s)     
├─ aws:s3:Bucket                 user-data                                  [diff: ~corsRules,serverSideEncryptionConfiguration]
└─ aws:rds:Instance              app                                        [diff: ~password]
Outputs:
apiBucketId: **REDACTED**
dbRootUrl  : **REDACTED**
Resources:
3 …
```
> Revert "chore: rotate `db-password` for Pulumi staging"

- editor.planx.uk/src/pages/Preview/Questions.tsx
Partial roll back of https://github.com/theopensystemslab/planx-new/pull/2035/files
The following error has been recurring heavily since the above PR was deployed https://planx.airbrake.io/projects/329753/groups/3600981422569003052
I suspect this change is the most likely culprit - I've reverted the `useEffect()` dependency arrays to what they were originally. If this doesn't succeed I'll revert the entire PR next.
> fix: Recurring call depth React error on Airbrake

- editor.planx.uk/src/@planx/components/FileUploadAndLabel/model.ts
- editor.planx.uk/src/@planx/graph/__tests__/update.test.ts
- editor.planx.uk/src/@planx/graph/index.ts
So this was an interesting / crazy one...
Before this fix - 
- When I modified a `FileType` it would persist if I had just added it
- Subsequent changes to the same `FileType` do not persist, but appear to do so as the local flow is updated
This actually matched behaviour George has described a few times (and maybe Emily?) and we've put it down to ShareDB I think.
- The local flow was updating _immediately_ as soon as I modified my `FileType` in the modal, no need to "Confirm"
- When saving and exiting the modal, the ShareDB side of things should start to persist flow changes to the db (see https://github.com/theopensystemslab/planx-new/pull/1958 for context)
- However, as the local flow as _already_ up to date, there was no difference between old and existing data and no `ops` were …
> fix: Resolve non-persistent state in `FileUploadAndLabel`

- editor.planx.uk/src/@planx/components/FileUploadAndLabel/Editor.tsx
Came up [on Slack today](https://opensystemslab.slack.com/archives/C5Q59R3HB/p1692103209278829) that we'd missed wiring up this button - nice quick one!
> fix: Wire up `FileType.moreInformation.definitionImg` button

- e2e/tests/ui-driven/pnpm-lock.yaml
- e2e/tests/ui-driven/src/context.ts
Spent a bit of time trying to get to the bottom of this one and this was the best solution I could find!
The value for `TEST_EMAIL` was being passed as `undefined` when `contextDefaults` was imported elsewhere - some combination of importing / cloning / using `as const` wasn't working together in the Playwright environment.
Tests pass locally, will point the regression test suite as this branch before opening for a review.
Update: Regression test action has succeeded on this branch - https://github.com/theopensystemslab/planx-new/actions/runs/5923944785 ✅
> fix: Don't pass `TEST_EMAIL` by reference

- api.planx.uk/.husky/pre-commit
- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- api.planx.uk/send/email.ts
- api.planx.uk/send/exportZip.ts
- api.planx.uk/send/uniform.ts
- e2e/.husky/pre-commit
- e2e/package.json
- e2e/pnpm-lock.yaml
- Add pre-commit hooks (using husky and lint-staged) to the API and E2E projects
I did consider configuring this at the root level of the project, [which lint-staged supports](https://github.com/okonet/lint-staged#how-to-use-lint-staged-in-a-multi-package-monorepo), but for now I'm happy steering away from any mono-repo tooling unnecessarily.
> chore: Setup husky and lint-staged for API and E2E projects

- api.planx.uk/server.ts
- hasura.planx.uk/metadata/tables.yaml
- hasura.planx.uk/migrations/1692347940126_drop_table_public_team_members/down.sql
- hasura.planx.uk/migrations/1692347940126_drop_table_public_team_members/up.sql
- hasura.planx.uk/migrations/1692350571424_create_table_public_user_teams/down.sql
- hasura.planx.uk/migrations/1692350571424_create_table_public_user_teams/up.sql
- hasura.planx.uk/migrations/1692362284817_alter_table_public_users_drop_column_is_admin/down.sql
- hasura.planx.uk/migrations/1692362284817_alter_table_public_users_drop_column_is_admin/up.sql
- hasura.planx.uk/seeds/1595528762802_teams_and_users.sql
- hasura.planx.uk/tests/teams.test.js
- scripts/seed-database/write/users.sql
- Drop the currently redundant `team_members` table
- Drop the currently redundant `users.is_admin` column
- Add a new `user_teams` (not totally sold on the name?) table which can be used to track the relationship between users and teams
> feat: Drop `team_members`, replace with `user_teams`

- api.planx.uk/editor/findReplace.ts
- api.planx.uk/server.ts
Relies on #2090 
Adds Swagger docs for find and replace endpoint. Hitting a few DX pain points with YAML in JSDocs annotation (spacing, no linting/types, text legibility etc). I'm going to take a look sometime next week at splitting out docs into their own YAML / JSON files that can just be referred to in modules before we go too far down the path with the `@swagger` notation 👍
> docs: Find and Replace Swagger docs

- .github/workflows/push-production.yml
- .github/workflows/regression-tests.yml
This should fix this morning's regression test failure.
I've now double checked and the `.gitconfig` is being setup on each GitHub action before a `pnpm install` for any project which uses `planx-core`.
Bit on an awkward workaround, which we could mitigate in future by...
- Reusable workflows
- Publish `planx-core` to NPM
> chore: Setup `.gitconfig` on outstanding actions

- hasura.planx.uk/metadata/tables.yaml
- hasura.planx.uk/migrations/1692010483148_add_team_boundary/down.sql
- hasura.planx.uk/migrations/1692010483148_add_team_boundary/up.sql
- Adds `team.boundary` column
- Adds `team.boundary_bbox` column, which is a computed field derived from `team.boundary`
As we want to move away from JSONB for team settings where possible, it made sense to make a start on this. By storing the boundary directly, we gain a few benefits - 
- Less reliance on planning.data.gov.uk in terms of live services (a small, but non-zero, benefit)
- The ability to just fetch the geometry we care about (e.g. a simplified envelope of the boundary)
- Significant reduction in request size to get the boundary (Doncasters full GeoJSON is 89KB, bbox is 404B. As an extreme example Cornwall's full boundary on planning.data is 1.2MB 🤯 )
- Generally, I'd prefer to store a `geometry` type for easier interactions with PostGIS. The `boundary_bbox` function is doing …
> feat: Add `team.boundary` and `team.boundary_bbox` columns

- editor.planx.uk/src/@planx/components/FileUploadAndLabel/Modal.tsx
PR introduces a header/title to the file upload & label modal, to prompt the user to label files.
The select/dropdowns are frequently being missed in user testing. In addition to the header, the chevron icon has been enlarged and the colour of it has been updated to the primary brand colour.
Relates to card:
https://trello.com/c/2vbA1u8O/2583-make-what-is-this-file-more-prominent
Previews (left = before, right = after):
> feat: Add header to file upload modal

- api.planx.uk/gis/classifiedRoads.ts
- editor.planx.uk/src/@planx/components/PlanningConstraints/mocks/classifiedRoadsNegativeResponseMock.ts
- editor.planx.uk/src/@planx/components/PlanningConstraints/mocks/classifiedRoadsResponseMock.ts
Classified roads come from OS rather than Planning Data, so we maintain our own hardcoded metadata fields for consistency. This adds `text` that August wrote in response to user feedback identified here https://trello.com/c/3Q9x5JkL/1338-from-ur-constraints-page-extra-information
I've also moved the distinct road name & classification level into a bullet point for consistency with other constraints.
**After:**
**Before:**
> fix: adjust metadata text for classified roads

- api.planx.uk/Dockerfile
Yesterday I did a `docker system prune -a` (the first since #2128) and subsequent builds have failed on the API due to Husky being missing as it's not a dev dependency.
This resolves the issue for me locally.
Details on the `--development` flag from [pnpm docs](https://pnpm.io/cli/install#--dev--d) - 
> Only devDependencies are installed and dependencies are removed insofar they were already installed, regardless of the NODE_ENV.
It looks like this flag is actually removing dependencies as opposed to just installing devDependencies. Possibly something that was missed on a pnpm upgrade?
> fix(api): Missing Husky dependency causing `pnpm dev` to fail 

- scripts/seed-database/container.sh
I had assumed that `cat` would always generate a file, but it doesn't appear to do so when nested in a subdirectory 👀
> fix(ci): Create `sync.sql` in advance

- scripts/seed-database/container.sh
Apologies for the churn here....
Tested and works as expected locally. Pizza not skipped so we can see check the db.
> fix: Correct `cat` syntax (again...)

- hasura.planx.uk/migrations/1693519114802_insert_into_public_user_roles/down.sql
- hasura.planx.uk/migrations/1693519114802_insert_into_public_user_roles/up.sql
This will need to get merged to prod in order to assign user roles, and before #2182
> chore: Change `user_role` enum from teamAdmin -> teamEditor

- api.planx.uk/modules/auth/service.ts
A logged in user with the `platformAdmin` role is unable to access the same tables as the `public` role.
This comment explains in detail what the issue is - https://github.com/theopensystemslab/planx-new/pull/2182/commits/64a2d1141fc6da53a8206aa6bf1cf131f79d81d2#r1312254263
There's a commit queued on another PR which addresses this - https://github.com/theopensystemslab/planx-new/pull/2182/commits/64a2d1141fc6da53a8206aa6bf1cf131f79d81d2
I hadn't appreciated that this would be an issue yet but I'll queue up another discrete fix first which just addresses this issue. In the meantime, reverting to `admin` should work without any issues and leaves us in status-quo god mode.
> fix: Temporarily revert to admin role whilst setting up Public GraphQL client

- scripts/seed-database/container.sh
- scripts/seed-database/write/main.sql
- scripts/seed-database/write/team_members.sql
- scripts/seed-database/write/users.sql
This will be required for users to have permissions on Pizzas, and to keep staging up to date.
The `github_actions` user was granted the following - 
```sql
GRANT SELECT ON TABLE team_members TO github_actions;
```
The role isn't in code anywhere to the best of my knowledge which isn't ideal.
Also fixed the sync script (missing `is_platform_admin` column)
> feat: Sync `team_members`, fix sync script

- package.json
Lost a fair bit of time to this one...! 
Part of a wider issue already discussed with inconsistent Docker scripts which I'd like to get back to and sort.
Currently, running `pnpm add-data` does not pick up `docker-compose.local.yml` which is responsible for changing the target to "development". This means `pnpm add-data` currently runs a static version of the API from the `/dist` folder - no live reload of changes as you're working.
This change means that now running `pnpm add-data` will result in a the API refreshing and picking up changes as you work.
On a similar note - this issue is related https://github.com/docker/compose/issues/7262
- Running `pnpm start` picks up the "development" target on the first instance
- Re-running `pnpm start` does not pick up the "development" target as …
> fix: Run development API following `pnpm add-data` script

- scripts/seed-database/container.sh
Based on [Github Actions error message](https://github.com/theopensystemslab/planx-new/actions/runs/6067468978/job/16459159443), it seems like flows is failing to get truncated. 
I think this is because the `>` operator only _replaces_ when using cat (so we're only running main sql write commands), whereas we want `>>` to append.
This works for me locally, but going to merge directly to staging to see if it clears up the sync job which hasn't been totally predictable based on local/pizza testing.
> fix: `cat` should use `>>` to append SQL commands for nightly staging sync

- package.json
- scripts/seed-database/container.sh
- scripts/seed-database/write/truncate_team_members.sql
Quick fix to most recent failure https://github.com/theopensystemslab/planx-new/actions/runs/6078545275/job/16489856129 
```sh
psql:write/team_members.sql:8: ERROR:  duplicate key value violates unique constraint "team_members_pkey"
DETAIL:  Key (id)=(ada5cbae-a4a2-4ab1-[98](https://github.com/theopensystemslab/planx-new/actions/runs/6078545275/job/16489856129#step:9:99)17-989689bf59b9) already exists.
CONTEXT:  COPY team_members, line 1
```
A quick truncation before copy does the trick but is a bit of a hack solution.
Going forward, I think we actually need to consider if `team_members.id` should be a sequenced integer, rather than random `uuid` - then adding a command like `SELECT setval('teams_members_id_seq', max(id)) FROM teams_members;` to end of insert rather than having to …
> fix: truncate `team_members` on staging sync

- editor.planx.uk/src/@planx/components/FileUploadAndLabel/Modal.tsx
- editor.planx.uk/src/@planx/components/FileUploadAndLabel/Public.test.tsx
- editor.planx.uk/src/@planx/components/FileUploadAndLabel/schema.test.ts
- editor.planx.uk/src/@planx/components/FileUploadAndLabel/schema.ts
Branched from / relies on #2209 
Based on Trello feedback [here](https://trello.com/c/IryaS9Yo/2582-investigate-if-we-can-make-users-label-file-before-returning-to-main-upload-and-label-component)
Disables closing the modal via clicking outside. Helpful docs [here](https://mui.com/api/dialog/) & [here](https://stackoverflow.com/questions/57329278/how-to-handle-outside-click-on-dialog-modal).
A number of our Public tests rely on checking modal visibility using ESC still.
I think the second suggestion for a Cancel button & deleting the actual uploaded file _slots_ from the modal will be quite tricky and require a big reshuffling of state - I'd vote that gets picked up separately & shouldn't hold up merging these incremental improvements!
> fix: only allow the `FileUploadAndLabel` modal to be closed using buttons

- editor.planx.uk/src/pages/FlowEditor/components/Settings/DataManagerSettings.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Settings/DesignSettings.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Settings/ServiceFlags.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Settings/ServiceSettings.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Settings/TeamSettings.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Settings/index.tsx
- editor.planx.uk/src/pages/Team.tsx
- editor.planx.uk/src/ui/FeaturePlaceholder.tsx
PR addresses: https://trello.com/c/Bw9veG77/2558-remove-unused-settings-pages-in-planx
- Introduces a new UI element `FeaturePlaceholder`
- Uses this in place of admin settings that are currently non-functioning
- Removes Flows/Archive/Trash buttons from "My services" list
> chore: Remove unused admin settings

- editor.planx.uk/src/@planx/components/FileUploadAndLabel/Modal.tsx
- editor.planx.uk/src/@planx/components/FileUploadAndLabel/Public.tsx
- editor.planx.uk/src/@planx/components/FindProperty/Public/Autocomplete.tsx
- editor.planx.uk/src/@planx/components/PlanningConstraints/List.tsx
- editor.planx.uk/src/@planx/components/PropertyInformation/Public.tsx
- editor.planx.uk/src/@planx/components/Result/Public/ResultReason.tsx
- editor.planx.uk/src/@planx/components/Section/Public.tsx
- editor.planx.uk/src/@planx/components/shared/Buttons/ImageButton.tsx
- editor.planx.uk/src/@planx/components/shared/Preview/SummaryList.tsx
- editor.planx.uk/src/@planx/components/shared/Preview/WarningContainer.tsx
- editor.planx.uk/src/@planx/components/shared/PrivateFileUpload/UploadedFileCard.tsx
- editor.planx.uk/src/@planx/components/shared/Radio/DescriptionRadio.tsx
- editor.planx.uk/src/@planx/components/shared/Radio/ImageRadio.tsx
- editor.planx.uk/src/theme.ts
- editor.planx.uk/src/themeOverrides.d.ts
- editor.planx.uk/src/ui/ExpandableList.tsx
- editor.planx.uk/src/ui/NextStepsList.tsx
- editor.planx.uk/src/ui/NumberedList.tsx
@jessicamcinchak I've added this as a separate branch as it involves a lot of file changes.
The default secondary colour was being reused as a border style as MUI doesn't include specific entries for borders. I've added a custom border palette, which frees up the secondary colour to be used as intended.
I've also added the cancel button and styled with the secondary colour.
> feat: set up border palette, add secondary button

- editor.planx.uk/src/@planx/components/FileUploadAndLabel/Modal.tsx
- editor.planx.uk/src/@planx/components/FileUploadAndLabel/Public.test.tsx
- editor.planx.uk/src/@planx/components/FileUploadAndLabel/Public.tsx
- editor.planx.uk/src/@planx/components/FileUploadAndLabel/schema.test.ts
- editor.planx.uk/src/@planx/components/FileUploadAndLabel/schema.ts
- editor.planx.uk/src/@planx/components/FindProperty/Public/Autocomplete.tsx
- editor.planx.uk/src/@planx/components/PlanningConstraints/List.tsx
- editor.planx.uk/src/@planx/components/PropertyInformation/Public.tsx
- editor.planx.uk/src/@planx/components/Result/Public/ResultReason.tsx
- editor.planx.uk/src/@planx/components/Section/Public.tsx
- editor.planx.uk/src/@planx/components/shared/Buttons/ImageButton.tsx
- editor.planx.uk/src/@planx/components/shared/Preview/SummaryList.tsx
- editor.planx.uk/src/@planx/components/shared/Preview/WarningContainer.tsx
- editor.planx.uk/src/@planx/components/shared/PrivateFileUpload/UploadedFileCard.tsx
- editor.planx.uk/src/@planx/components/shared/Radio/DescriptionRadio.tsx
- editor.planx.uk/src/@planx/components/shared/Radio/ImageRadio.tsx
- editor.planx.uk/src/theme.ts
- editor.planx.uk/src/themeOverrides.d.ts
- editor.planx.uk/src/ui/ExpandableList.tsx
- editor.planx.uk/src/ui/NextStepsList.tsx
- editor.planx.uk/src/ui/NumberedList.tsx
Splits up the validation checks for "each file should be tagged" & "all required files must be tagged" so that we can call _only_ the first check from the Modal when clicking "Done". This hopefully makes for any easier to understand user journey than this original feedback that we went back on forth on: https://github.com/theopensystemslab/planx-new/pull/1994
Other changes:
- Disables outside clicks to close the modal, ESC key still okay
- Changes all user-facing instances of "tag" to "label" in hardcoded error messages, etc
Behavior before: 
- Modal opens, you can click "Done" to close without tagging any files, no error
- Modal opens, you can click away to close without tagging any files, no error
- Modal opens, you can press ESC to close without tagging any files, no error
- You only …
> fix: `FileUploadAndLabel` modal should error if each file is not tagged, but not validate that all required files are uploaded yet

- api.planx.uk/send/bops.ts
- api.planx.uk/send/email.ts
- api.planx.uk/send/uniform.ts
More submission errors are popping up lately as folks are testing usually because their selected Send destination isn't configured or enabled in the environment they're testing in - eg https://opensystemslab.slack.com/archives/C4B0CKQ3U/p1695054852938379
Airbrake doesn't capture the service URL in these cases (because the error is thrown via Hasura events?), so adding the local authority param direct to the message will make it a bit quicker to id bugs on live versus testing/staging-only integrations.
> fix: include local authority name on submission errors

- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
- editor.planx.uk/src/@planx/components/Send/bops/index.ts
Please see https://github.com/theopensystemslab/planx-new/security/code-scanning/7
The same PR will shortly follow on `planx-core`
> fix: Incomplete multi-character sanitation

- hasura.planx.uk/metadata/tables.yaml
- hasura.planx.uk/tests/team_members.test.js
- hasura.planx.uk/tests/users.test.js
Permissions issue I hit when working on https://github.com/theopensystemslab/planx-new/pull/2224
- platformAdmins have full access to `team_members` table
- teamEditors can read their own record from the `team_members` table
- teamEditors can read their own record from the `users` table
> feat: Grant permissions on `team_members` table

- api.planx.uk/admin/feedback/downloadFeedbackCSV.ts
- api.planx.uk/admin/session/bops.ts
- api.planx.uk/admin/session/csv.ts
- api.planx.uk/admin/session/html.ts
- api.planx.uk/admin/session/oneAppXML.ts
- api.planx.uk/admin/session/summary.ts
- api.planx.uk/admin/session/zip.ts
- api.planx.uk/client/index.ts
- api.planx.uk/editor/copyFlow.ts
- api.planx.uk/editor/publish.ts
- api.planx.uk/inviteToPay/sendConfirmationEmail.ts
- api.planx.uk/inviteToPay/sendPaymentEmail.ts
- api.planx.uk/modules/auth/middleware.ts
- api.planx.uk/modules/auth/service.ts
- api.planx.uk/modules/misc/controller.ts
- api.planx.uk/modules/misc/docs.yaml
- api.planx.uk/modules/misc/routes.test.ts
- api.planx.uk/modules/misc/routes.ts
- api.planx.uk/modules/team/controller.ts
- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- api.planx.uk/saveAndReturn/resumeApplication.ts
- api.planx.uk/saveAndReturn/utils.ts
- api.planx.uk/server.test.js
- api.planx.uk/server.ts
- api.planx.uk/tests/mockJWT.ts
- e2e/tests/api-driven/pnpm-lock.yaml
- e2e/tests/ui-driven/pnpm-lock.yaml
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
- Creates a context object to store the user which will persist throughout the callstack of a request/response cycle
- Uses the Node `AsyncLocalStoreage` API to acheive this ([docs](https://nodejs.org/docs/latest-v18.x/api/async_context.html))
We need to keep user details, specifically the JWT and user ID, for a number of operations that happen in the API. The specific issue we're hoping to address in the short term here is ensuring that any requests made the the API are scoped to the permission level of the user who made the request.
We always have `req.user` as the `express-jwt` middleware sets this up for us. If we wanted to access this value in a service, or a child function of that service, we'd need to "prop drill" the request or user object all the way through. This approach can …
> feat: Setup `AsyncLocalStoreage` context for Express.User throughout the callstack

- editor.planx.uk/src/components/Header.tsx
- editor.planx.uk/src/pages/FlowEditor/lib/store/editor.ts
- editor.planx.uk/src/pages/FlowEditor/lib/store/user.ts
- I added a "Templates" team to production & staging, this change ensures any user will have `teamEditor` access to "Templates" by default when they're added independent of records in the `team_members` table (if this feels too liberal, very happy to re-think how we should do this!)
- `moveFlow` Editor store method now checks if the given user has permission to move the flow into the requested team. If they don't, it'll display and error and return early. The copy/move menu is only visible in teams you can edit already, so I don't think we need to do anything similar with other store methods besides `moveFlow` yet.
**Testing:** 
- (If you're a platformAdmin, toggle this off first in https://hasura.2239.planx.pizza/console/login)
- I see an "edit" icon next to `Templates` even though I do …
> feat: all users can edit "Templates" team and `moveFlows` to teams they're allowed to edit

- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- e2e/README.md
- e2e/tests/api-driven/README.md
- e2e/tests/api-driven/package.json
- e2e/tests/api-driven/pnpm-lock.yaml
- e2e/tests/api-driven/src/client.ts
- e2e/tests/api-driven/src/globalHelpers.ts
- e2e/tests/api-driven/src/helpers.ts
- e2e/tests/api-driven/src/invite-to-pay/helpers.ts
- e2e/tests/api-driven/src/invite-to-pay/steps.ts
- e2e/tests/api-driven/src/invite-to-pay/submissions.feature
- e2e/tests/api-driven/src/jwt.ts
- e2e/tests/api-driven/src/permissions/helpers.ts
- e2e/tests/api-driven/src/permissions/queries/flows.ts
- e2e/tests/api-driven/src/permissions/queries/index.ts
- e2e/tests/api-driven/src/permissions/steps.ts
- e2e/tests/api-driven/src/permissions/teamAdmin.feature
- e2e/tests/ui-driven/package.json
- e2e/tests/ui-driven/pnpm-lock.yaml
- e2e/tests/ui-driven/src/context.ts
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
- Setup test harness for user permissions, with one example test in each category
- More details in README!
> test: Setup E2E tests for user roles

- editor.planx.uk/src/index.tsx
- editor.planx.uk/src/pages/FlowEditor/lib/store/user.ts
- editor.planx.uk/src/routes/authenticated.tsx
- Init user store via router context
- This means that we can refresh at any point / any page and the store will re-init
> fix: Init user store across all routes

- editor.planx.uk/src/@planx/components/FileUploadAndLabel/Modal.tsx
- Adds a 'done' button to the header of the select dropdown list.
- Header is sticky so will be visible at all times for longer lists that overflow the viewport
PR satisfies: https://trello.com/c/XCE7KiSR/2645-add-okay-or-done-button-to-labels-component-for-upload-drawings-section
Demo:
https://2225.planx.pizza/planx/test-upload-label-select/preview
There are two upload and label components in the demo flow, the first with a short file list and the second with a longer list (to demonstrate the effectiveness of the list header). You will need to upload and label a file to reach the second component.
> feat: Improve upload + label select usability

- e2e/tests/ui-driven/src/helpers.ts
- editor.planx.uk/src/@planx/components/Section/Editor.tsx
- editor.planx.uk/src/@planx/components/Section/Public.test.tsx
- editor.planx.uk/src/@planx/components/Section/Public.tsx
- editor.planx.uk/src/@planx/components/Section/Section.stories.tsx
- editor.planx.uk/src/@planx/components/Section/model.test.ts
- editor.planx.uk/src/@planx/components/Section/model.ts
- editor.planx.uk/src/types.ts
- PR adds the option to add a rich-text description to sections
- `<dl>` structure is maintained, I've checked and nesting a `<div>` inside a `<dl>` is valid HTML [source](https://html.spec.whatwg.org/multipage/grouping-content.html#the-dl-element)
- Tests and storybook updated accordingly
Related to Trello card:
https://trello.com/c/SGy6v0Sm/2587-investigate-section-descriptions
Example:
https://2240.planx.pizza/lambeth/apply-for-prior-approval/preview
> feat: Add section descriptions

- hasura.planx.uk/metadata/tables.yaml
- hasura.planx.uk/tests/flows.test.js
Raised by August [here on OSL Slack](https://opensystemslab.slack.com/archives/C5Q59R3HB/p1695634674247739?thread_ts=1695633553.425559&cid=C5Q59R3HB)
> feat: Allow `platformAdmin` role to delete flows

- api.planx.uk/docs/index.ts
- api.planx.uk/modules/team/controller.test.ts
- api.planx.uk/modules/team/controller.ts
- api.planx.uk/modules/team/docs.yaml
- api.planx.uk/modules/team/routes.ts
- api.planx.uk/modules/team/service.test.ts
- api.planx.uk/modules/team/service.ts
- api.planx.uk/modules/user/controller.ts
- api.planx.uk/modules/user/docs.yaml
- api.planx.uk/modules/user/index.test.ts
- api.planx.uk/modules/user/routes.ts
- api.planx.uk/server.ts
- hasura.planx.uk/metadata/tables.yaml
- hasura.planx.uk/tests/users.test.js
- Adds a new create user endpoint to be used by Platform Admins
- Updates team endpoints to use user emails and team slugs
- Updates tests, standardises error handling in new modules
- Fixes a few missing permissions for the `platformAdmin` role
Depends on https://github.com/theopensystemslab/planx-core/pull/137
> feat: Create user endpoint, manage team members by email and teamSlugs

- editor.planx.uk/src/components/Header.test.tsx
- editor.planx.uk/src/components/Header.tsx
- editor.planx.uk/src/pages/FlowEditor/lib/store/settings.ts
- editor.planx.uk/src/pages/FlowEditor/lib/store/team.ts
- editor.planx.uk/src/pages/Team.tsx
- editor.planx.uk/src/routes/team.tsx
- editor.planx.uk/src/routes/views/team.tsx
- editor.planx.uk/src/types.ts
- Resolves an issue described by August [here on OSL Slack](https://opensystemslab.slack.com/archives/C5Q59R3HB/p1695652749495649?thread_ts=1695633553.425559&cid=C5Q59R3HB)
- Ensures that the team store is not just loaded and populated on initial run through, but works on page refresh
- Tidies up the `Header` component to use the teamStore as opposed to the route data
- The logic inside a `mount()` function on a route only gets called for a specific route
- Using `withView()` matches all child routes, e.g. `/team/settings`
> fix: Persist `TeamStore`

- editor.planx.uk/src/pages/FlowEditor/lib/store/team.ts
- editor.planx.uk/src/pages/FlowEditor/lib/store/user.ts
- editor.planx.uk/src/routes/views/team.tsx
Fixes bug currently live on staging which causes `/preview` and `/unpublished` routes to fail. E2E tests to follow which will cover this!
> fix: Use `get()` instead of `this` in Zustand stores

- api.planx.uk/modules/user/controller.ts
- api.planx.uk/modules/user/docs.yaml
- api.planx.uk/modules/user/index.test.ts
- api.planx.uk/modules/user/routes.ts
- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- hasura.planx.uk/metadata/tables.yaml
- hasura.planx.uk/tests/users.test.js
- Allow `platformAdmins` to update user emails (for soft delete)
- Add delete user endpoint to API docs
> feat(api): Remove user endpoint

- api.planx.uk/helpers.test.ts
- api.planx.uk/helpers.ts
- editor.planx.uk/src/lib/dataMergedHotfix.ts
- editor.planx.uk/src/pages/FlowEditor/lib/__tests__/externalPortals.test.ts
- editor.planx.uk/src/pages/FlowEditor/lib/__tests__/mocks/multipleExternalPortals.json
- editor.planx.uk/src/pages/FlowEditor/lib/__tests__/mocks/singleExternalPortal.json
- Fixes bug described here - https://trello.com/c/23Wi60zZ/2551-blank-screen-shows-when-passing-through-external-portal
- Adds tests
- Small restructure/renaming refactor of `dataMerged()`
It appears to have been there since `dataMerged()` was written as far as I can tell which is a little surprising - I don't have total confidence in this but it's my best guess.
We could do this, but there's not real need to - if more flow management / logic goes there then sure, but for now we can continue to live with the duplication here I think.
- Simplified example - https://2217.planx.pizza/testing/external-portal-fixed-test/preview?analytics=false
- Compex example (real flow described in ticket) - https://2217.planx.pizza/buckinghamshire/apply-for-building-regulations-applications/preview?analytics …
> fix: Handle multiple external portals as siblings

- e2e/tests/api-driven/src/permissions/helpers.ts
Regression tests failed over the weekend - https://github.com/theopensystemslab/planx-new/actions/runs/6376551702
This was due to sloppy find/replace by me in this commit to replace `@opensystemslab.io` emails with `@example.com` addresses - https://github.com/theopensystemslab/planx-new/pull/2230/commits/1833a1356eb7687ba231799fc7c30b8df053d733
✅ Regression tests pass against this branch - https://github.com/theopensystemslab/planx-new/actions/runs/6379097869
> fix(e2e): Fix incorrect dummy emails in api-driven tests

- hasura.planx.uk/seeds/1595528762802_teams_and_users.sql
These are no longer needed now that we have data sync commands. There's no existing references to this file that I could find - the `hasura seed apply` command that was in the README is already gone.
> chore: Remove Hasura seeds

- api.planx.uk/modules/webhooks/service/lowcalSessionEvents/schema.ts
- api.planx.uk/modules/webhooks/service/paymentRequestEvents/schema.ts
- api.planx.uk/shared/middleware/validate.ts
Hit this issue when troubleshooting E2E test (this doesn't fix them yet! 😅)
The change introduced in https://github.com/theopensystemslab/planx-new/pull/2252 validates that incomming requests are valid (e.g. dates), and then hands over the request type to the `ValidatedRequestHandler` type.
What I missed is that we're never passing along the parsed request to the next middleware layer (but it does pass the type as mentioned above).
This means we end up with strings being passed into functions that expect `Date` objects. When running E2E tests a number of API requests fail as a result.
> fix: Correctly parse and transform strings to date in `/webhook` APIs

- editor.planx.uk/src/@planx/components/Pay/Editor.tsx
- editor.planx.uk/src/@planx/components/Pay/Public/Confirm.tsx
- editor.planx.uk/src/@planx/components/Pay/Public/Pay.stories.tsx
- editor.planx.uk/src/@planx/components/Pay/Public/Pay.test.tsx
- editor.planx.uk/src/@planx/components/Pay/Public/Pay.tsx
- editor.planx.uk/src/@planx/components/Pay/model.ts
**Changes:**
- Adds Editor option to "Hide the pay buttons and show fee for information only" (off by default)
- Renders [like this in the public interface](https://storybook.2284.planx.pizza/?path=/story/planx-components-pay--for-information-only)
- Updates how `NaN` / `undefined` fees are handled
- Current behavior: if the data field referenced by the Pay component (`props.fn`) is undefined when Pay is reached, then automatically skip the Pay component. This led to real applications being successfully submitted without paying because of a content error a few weeks ago.
- New behavior: if `props.fn` is undefined when Pay is reached, display an error and do not let the applicant continue. An airbrake error including the `sessionId` is also thrown/should be picked up in Slack. …
> feat: add option to use "Pay without pay" and show error in cases of undefined fee

- api.planx.uk/server.test.js
- api.planx.uk/server.ts
- api.planx.uk/tests/serverErrorHandler.test.js
- Drops `/hasura`
- E2E tests cover functionality, and `/me` can be used to the same effect to check API -> Hasura networking)
- Drops `/error` and `/throw-error`
> chore: Drop redundant API endpoints

- api.planx.uk/modules/analytics/controller.ts
- api.planx.uk/modules/analytics/docs.yaml
- api.planx.uk/modules/analytics/index.test.ts
- api.planx.uk/modules/analytics/routes.ts
- api.planx.uk/modules/analytics/service.ts
- api.planx.uk/server.ts
- Converts analytics REST API endpoints to modular structure proposed for API
- Adds test coverage and Swagger docs
I needed a break from E2E tests and it seemed worthwhile getting this quickly tidied up before @Mike-Heneghan may want to expand on this.
> feat: Modularise and document analytics endpoints

- editor.planx.uk/src/pages/Preview/StatusPage.tsx
Spotted this one today!
| ![image](https://github.com/theopensystemslab/planx-new/assets/20502206/0be9aaf5-6b99-407c-a78d-39d5da0a724d) | ![image](https://github.com/theopensystemslab/planx-new/assets/20502206/a36c3839-4a6f-44a0-b39b-21090a991a06) |
> fix: Left align 'Start new application' link

- hasura.planx.uk/metadata/tables.yaml
- hasura.planx.uk/tests/analytics.test.js
- hasura.planx.uk/tests/blpu_codes.test.js
- hasura.planx.uk/tests/bops_applications.test.js
- hasura.planx.uk/tests/email_applications.test.js
- hasura.planx.uk/tests/flow_document_templates.test.js
- hasura.planx.uk/tests/flows.test.js
- hasura.planx.uk/tests/global_settings.test.js
- hasura.planx.uk/tests/lowcal_sessions.test.js
- hasura.planx.uk/tests/payment_requests.test.js
- hasura.planx.uk/tests/payment_status.test.js
- hasura.planx.uk/tests/planning_constraints_requests.test.js
- hasura.planx.uk/tests/reconciliation_requests.test.js
- hasura.planx.uk/tests/sessions.test.js
- hasura.planx.uk/tests/team_members.test.js
- hasura.planx.uk/tests/teams.test.js
- hasura.planx.uk/tests/uniform_applications.test.js
- hasura.planx.uk/tests/users.test.js
- hasura.planx.uk/tests/utils.js
- Adds a new `api` role in Hasura
- Adds introspection test coverage for user role
I'm working towards https://trello.com/c/qSCoDRAO/2650-implement-editor-permissions-throughout-the-api which has two main aims - 
- When a request to the API is initiated by a user, use their permission level throughout the call stack
- When a request to the API is initiated by an internal service (e.g. Hasura), use appropriate permissions (not admin token with full "God mode")
The first step has been pretty well started in previous PRs. Adding an `api` role will allow us to scope service → API requests appropriately when a service has authenticated to the API (e.g. through the `useHasuraAuth()` middleware).
The permission set outlined here is based on queries currently made by the two admin GraphQL clients …
> feat: Create new `api` role in Hasura

- e2e/tests/api-driven/src/hasuraTriggers/hasuraTriggers.feature
- e2e/tests/api-driven/src/hasuraTriggers/helpers.ts
- e2e/tests/api-driven/src/hasuraTriggers/steps.ts
- editor.planx.uk/src/components/Header.tsx
- editor.planx.uk/src/pages/FlowEditor/lib/__tests__/user.test.ts
- editor.planx.uk/src/pages/FlowEditor/lib/store/user.ts
- hasura.planx.uk/migrations/1696884217237_grant_new_user_template_team_access/down.sql
- hasura.planx.uk/migrations/1696884217237_grant_new_user_template_team_access/up.sql
- Using a trigger, automatically adds new users to the "Templates" team
- Removes the responsibility for handling this end from the frontend
- Adds E2E test coverage of this new behaviour
- Adds basic tests for `canUserEditTeam()` logic in `UserStore`
> feat: Automatically grant users access to the "Templates" team

- api.planx.uk/gis/digitalLand.ts
- api.planx.uk/gis/local_authorities/metadata/base.ts
- editor.planx.uk/src/@planx/components/PlanningConstraints/List.tsx
Changes:
- Adds values `flood`, `flood.zone.1`, `flood.zone.2` and `flood.zone.3` to the planning constraints check (only adds granular entries if `flood` is true, consistent with Article 4 granular variables)
I hit two quirks with Planning Data that I've raised with Matt L, and expect to be updated soon on their side. When it is, the dropdown will populate as expected, no extra code changes required (so no need to block initial merge I think!):
- Planning data hasn't populated the "text" for `flood-risk-zone` metadata (which is used to render the contextual paragraphs in the dropdown)
- Planning data hasn't populated the "name" for `flood-risk-zone` entities (which is used to render the bullet-pointed list in the dropdown)
Address in a flood zone for testing: 47, COBOURG ROAD, SOUTHWARK, …
> feat: query & display Flood Risk Zones in PlanningConstraints

- api.planx.uk/hasura/index.ts
- api.planx.uk/inviteToPay/sendPaymentEmail.test.ts
- api.planx.uk/notify/notify.ts
- api.planx.uk/notify/routeSendEmailRequest.test.ts
- api.planx.uk/saveAndReturn/utils.ts
- api.planx.uk/tests/mocks/saveAndReturnMocks.ts
- api.planx.uk/types.ts
- Replaces `publicGraphQLClient` in favour of `$public`
- No functionality change, just a tidy up and simplification
- Small permission change with `getClientForTemplate()` now conditionally using the `api` role instead of the `admin` role
> feat: Drop `publicGraphQLClient` in favour of `$public` client

- api.planx.uk/admin/session/html.test.ts
- api.planx.uk/client/index.ts
- api.planx.uk/hasura/index.ts
- api.planx.uk/inviteToPay/createPaymentSendEvents.ts
- api.planx.uk/inviteToPay/inviteToPay.ts
- api.planx.uk/inviteToPay/sendConfirmationEmail.ts
- api.planx.uk/inviteToPay/sendPaymentEmail.test.ts
- api.planx.uk/modules/auth/service.ts
- api.planx.uk/modules/webhooks/service/sanitiseApplicationData/operations.test.ts
- api.planx.uk/modules/webhooks/service/sendNotification/index.test.ts
- api.planx.uk/modules/webhooks/service/sendNotification/index.ts
- api.planx.uk/notify/notify.ts
- api.planx.uk/notify/routeSendEmailRequest.test.ts
- api.planx.uk/pay/pay.ts
- api.planx.uk/saveAndReturn/utils.ts
- api.planx.uk/send/bops.ts
- api.planx.uk/send/exportZip.test.ts
- api.planx.uk/send/exportZip.ts
- api.planx.uk/send/uniform.ts
- api.planx.uk/session/files.test.ts
- api.planx.uk/session/files.ts
- api.planx.uk/tests/mocks/saveAndReturnMocks.ts
- api.planx.uk/types.ts
- Replace the "god mode" `$admin` client with the `$api` client (see comment on naming conventions) which is scoped to the  "api" role
- All the functions updated here are behind the `useHasuraAuth()` auth middleware - these functions are all triggered by Hasura
Yep, this is tricky. Introspection tests cover the permissions the `$api` client has here. Some of the functionality is covered by E2E tests (send, invite to pay) - some is not (submit, export).
I think the best solution here in the medium term is to probably work to improve our E2E test coverage for high-priority functionality.
> feat: Use `$api` client for requests from Hasura → API

- api.planx.uk/docs/index.ts
- api.planx.uk/modules/webhooks/docs.yaml
Restores `hasuraAuth` option to submission and webhook endpoints
> fix: Add security header for `/webhooks` API routes

- api.planx.uk/admin/session/bops.ts
- api.planx.uk/admin/session/oneAppXML.test.ts
- api.planx.uk/admin/session/oneAppXML.ts
- hasura.planx.uk/metadata/tables.yaml
**Changes:**
- `/admin/xml` should query any `lowcal_sessions`, rather than rely on `uniform_applications` audit record
- `/admin/bops` was already adjusted for this, make sure Swagger reflects that
- admin endpoints should use `$api` client, rather than granting session select access to `platformAdmin` 
- (i've only made this change for xml & bops so far as we need these for immediate LDC debugging, will come back to adjust all admin endpoints in a follow-up PR once we confirm this is working as expected)
Test endpoints (this is a partial session, so OneApp shows errors as expected!):
- https://api.2309.planx.pizza/admin/session/cae52bd7-a4e5-4bfd-b25f-98913bb9d61f/bops
- https://api.2309.planx.pizza/admin/session/cae52bd7-a4e5-4bfd-b25f-98913bb9d61f/xml
> fix: adjust BOPS & XML admin endpoints for debugging

- infrastructure/application/index.ts
Currently, the API is hitting 100% CPU on prod when handling submissions.
Even when submissions succeed, it causes the API to restart which means that subsequent calls to the API (e.g. to proxy image requests, or trigger Slack notifications) then fail.
Doubling the memory also bumps the CPU size ([Fargate docs](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/fargate-tasks-services.html#fargate-tasks-size)) 
If we can get this to prod and test (via `/admin` endpoints) I'd hope we can notice a difference on Fargate task.
I'd like to take a look at (and profile) what I suspect the culprit is here (`computeBOPSParams()`) and see if there are any code changes we can make that don't purely rely on just upping memory / CPU. This should buy us some time though!
> chore: Bump API memory (and CPU)

- scripts/seed-database/write/users.sql
The [nightly database sync](https://github.com/theopensystemslab/planx-new/actions/runs/6540664008) failed yesterday with the following error - 
```sh
psql:write/team_members.sql:8: ERROR:  duplicate key value violates unique constraint "team_members_user_id_team_id_key"
DETAIL:  Key (user_id, team_id)=(117, 29) already exists.
CONTEXT:  COPY team_members, line 174
Database sync failed!
```
I think what's happening here is a race condition between the trigger inserting record in `team_members` and the script inserting them. This could explain the flakiness we've seen on recent Pizzas with the sync sometimes working and sometimes failing.
I'd tested this locally a few times (including adding a new user to check the trigger is still active) and it seems to work as expected without a hitch.
> fix: Disable `grant_new_user_template_team_access` trigger on DB sync

- api.planx.uk/admin/session/bops.test.ts
- api.planx.uk/admin/session/bops.ts
- api.planx.uk/admin/session/csv.test.ts
- api.planx.uk/admin/session/csv.ts
- api.planx.uk/admin/session/html.ts
- api.planx.uk/admin/session/oneAppXML.test.ts
- api.planx.uk/admin/session/oneAppXML.ts
- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- api.planx.uk/send/bops.ts
- api.planx.uk/send/email.test.ts
- api.planx.uk/send/exportZip.test.ts
- api.planx.uk/send/exportZip.ts
- api.planx.uk/send/uniform.ts
- e2e/tests/api-driven/package.json
- e2e/tests/api-driven/pnpm-lock.yaml
- e2e/tests/ui-driven/package.json
- e2e/tests/ui-driven/pnpm-lock.yaml
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
- Updates `planx-core` to pick up the changes implemented in https://github.com/theopensystemslab/planx-core/pull/162
- This avoids repeated calls to the expensive `computeBOPSParams()` function. Local testing indicates that this approximately halves the time it takes to hit the `/admin` endpoints being updated here.
> feat: Explicitly handle redaction

- editor.planx.uk/src/@planx/components/shared/Preview/SummaryList.tsx
PR builds on @DafyddLlyr's moving of the 'change' button in the review component with the following:
- Update on heading sizes and spacing to improve visual hierarchy
- Moving of logic to remove grid column when 'change' button is hidden, allowing for full width for table content
Before (left) and after (right):
> feat: Update review section styling

- api.planx.uk/admin/session/csv.ts
- api.planx.uk/admin/session/html.ts
Quick follow up from https://github.com/theopensystemslab/planx-new/pull/2309
> chore: Convert remaining `/admin` endpoints to `$api` client

- .env.example
- README.md
- editor.planx.uk/.env
We got the repo up & running on an external fork today in less than an hour :tada: :fork_and_knife: 
Updating our docs with a couple gotchas we spotted along the way.
> chore: update local development instructions in README

- editor.planx.uk/src/@planx/components/NextSteps/Public.tsx
- editor.planx.uk/src/pages/FlowEditor/lib/analyticsProvider.tsx
- editor.planx.uk/src/pages/Preview/StatusPage.tsx
- editor.planx.uk/src/ui/InputLabel.tsx
- editor.planx.uk/src/ui/NextStepsList.tsx
A good play around with this shows it's not actually doing anything currently so can be safely removed.
> fix: Drop redundant (and error-throwing) `:first-child` selector

- api.planx.uk/server.ts
There may be a few of these incoming - keeping them small and easy should it make it more readable and manageable. There's not much test coverage for some of these steps (and I'm not sure how valuable they would be?) so hopefully small PRs would mean they're a little more easily testable as we go along.
> chore: Convert `/download-schema` endpoint to `$public` client

- api.planx.uk/inviteToPay/createPaymentSendEvents.ts
- api.planx.uk/inviteToPay/inviteToPay.ts
- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- e2e/tests/api-driven/package.json
- e2e/tests/api-driven/pnpm-lock.yaml
- e2e/tests/api-driven/src/permissions/helpers.ts
- e2e/tests/api-driven/src/permissions/steps.ts
- e2e/tests/ui-driven/package.json
- e2e/tests/ui-driven/pnpm-lock.yaml
- e2e/tests/ui-driven/src/context.ts
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
- editor.planx.uk/src/@planx/components/NextSteps/Public.tsx
- editor.planx.uk/src/pages/FlowEditor/lib/analyticsProvider.tsx
- editor.planx.uk/src/pages/Preview/StatusPage.tsx
- editor.planx.uk/src/ui/NextStepsList.tsx
This picks up the (long delayed!) changes made in [this PR ](https://github.com/theopensystemslab/planx-core/pull/79) which notably tidies up and namespaces more functionality (e.g. `$admin.createFlow()` → `$admin.flow.create()`).
There's also a few small type tidy picked up in E2E tests.
This PR relies on https://github.com/theopensystemslab/planx-core/pull/164 and should unblock https://github.com/theopensystemslab/planx-new/pull/2322
> chore: Update `planx-core`

- editor.planx.uk/src/pages/FlowEditor/lib/analyticsProvider.tsx
- hasura.planx.uk/metadata/tables.yaml
- hasura.planx.uk/migrations/1697540635734_alter_table_public_analytics_logs_add_column_next_log_created_at/down.sql
- hasura.planx.uk/migrations/1697540635734_alter_table_public_analytics_logs_add_column_next_log_created_at/up.sql
- Catch when a component is transitioned and a new `analytics_log` record is created. 
- Store the `created_at` of this against `newLogCreatedAt`
- Use the `lastAnalyticsLog` to mutate the last log with the new `newLogCreatedAt`stored against the new `next_log_created_at` column.
- We want to be able to track how long users spend on each card
- When querying we can compare the difference between `created_at` and `next_log_created_at` to have a number for how long was take on the card in the context of a user in a session.
- Allow null to show that user's don't always proceed in the flow and might `"resume"` later kicking off a new session. 
- Shares the same format as existing data
- Based on the system time which avoid conversion issues
- I believe it will be easy to interrogate the data …
> feat: add next_log_created_at to analytics_log to allow time tracking per card

- api.planx.uk/send/uniform.ts
- e2e/tests/api-driven/src/invite-to-pay/mocks/server-mocks.yaml
Currently testing submissions on staging and hitting issues with Uniform. The current message is getting logged which is not particularly insightful - 
`message: 'Failed to send to Uniform (chiltern): AxiosError: Request failed with status code 500'`
The issue I'm hitting is that their token endpoint is not returning `organisation-name` and `organisation-id` either Chiltern or Aylesbury Vale, which is required for the next step of the submission process.
Update: I've manually tested their production API and both `organisation-name` and `organisation-id` are returned so I'm confident we're good to put this additional error handling in place.
> chore: Improve Uniform error logging

- scripts/seed-database/write/flows.sql
- scripts/seed-database/write/published_flows.sql
- scripts/seed-database/write/team_members.sql
- scripts/seed-database/write/teams.sql
- scripts/seed-database/write/users.sql
See context on OSL Slack - https://opensystemslab.slack.com/archives/C01E3AC0C03/p1696942132535689
Currently, we don't overwrite DB records on conflict - we skip them. This can lead to inconsistencies (as on the above thread), could potentially lead to permissions diverging between staging and prod, and also causes this new issue raised here where the prod boundary has not been copied across to staging - https://trello.com/c/hreL5mn4/2665-site-doesnt-have-address-showing-london-map-extract-on-bucks-service
> chore: Overwrite records on data-sync conflict

- editor.planx.uk/src/@planx/components/FileUploadAndLabel/model.test.ts
- editor.planx.uk/src/@planx/components/FileUploadAndLabel/model.ts
- When constructing a `FileList` for display to the user, we want this to only contain unique files (by name)
- We're experiencing a bug where a file is missing from the `FileList`
- There are two `FileType`s with the same name
- Only one of their conditions is met
- Neither appear in the final list ❌ 
- Described in detail with example flow [here on OSL Slack](https://opensystemslab.slack.com/archives/C01E3AC0C03/p1697646369616819)
- The unique list of file names we maintain does not check if the file has been added or not to the `FileList`
- Check if a file is added by the `populateFileList()` function
- Only count it as a unique file if added to our `FileList`
Broken flow on prod - https://editor.planx.uk/testing/upload-and-label-recommended-test ❌ 
Fixed flow on pizza - …
> fix: Handle unique file list correctly

- scripts/seed-database/write/flows.sql
- scripts/seed-database/write/published_flows.sql
- scripts/seed-database/write/team_members.sql
- scripts/seed-database/write/teams.sql
- scripts/seed-database/write/users.sql
Fix for clumsy SQL in [previous PR](https://github.com/theopensystemslab/planx-new/pull/2332) which is causing the sync script to fail.
Tested multiple times locally and getting the expected results.
> fix: SQL `DO UPDATE` syntax for data sync script

- api.planx.uk/send/uniform.ts
- e2e/tests/ui-driven/package.json
- e2e/tests/ui-driven/playwright.config.ts
- e2e/tests/ui-driven/pnpm-lock.yaml
- e2e/tests/ui-driven/src/create-flow.spec.ts
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
- editor.planx.uk/src/@planx/components/Pay/Public/InviteToPayForm.tsx
- editor.planx.uk/src/components/DelayedLoadingIndicator.tsx
- editor.planx.uk/src/pages/Pay/MakePayment.tsx
- editor.planx.uk/src/routes/pay.tsx
- editor.planx.uk/src/routes/team.tsx
E2E "Invite to Pay" tests have been failing for a while (and flaky prior to that). Here's a description and video of the bug which was leading to these failures -
- Visit any "Invite to Pay" URL (e.g. `/:team/:flow/pay` or `/:team/:flow/invite`)
- Page loads as expected ✅ 
- Refresh page
- Endless "Loading..." spinner, error thrown in console ❌ 
- Refresh again - issue persists
- Hard refresh - back to normal page load
Sometime you can hit the error immediately without first encountering the successful page load.
This bug was getting hit in Invite to Pay E2E tests where multiple tabs were being opened and refreshed to check the status of payment requests.
https://github.com/theopensystemslab/planx-new/assets/20502206/b193773e-6510-4936-bfc8-d4bfe2aa4e06
```
Uncaught (in promise) …
```
> fix: Failing regression E2E tests

- api.planx.uk/admin/session/html.ts
- api.planx.uk/inviteToPay/createPaymentSendEvents.ts
- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- e2e/tests/api-driven/package.json
- e2e/tests/api-driven/pnpm-lock.yaml
- e2e/tests/ui-driven/package.json
- e2e/tests/ui-driven/pnpm-lock.yaml
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
- editor.planx.uk/src/@planx/components/Result/Editor.tsx
- editor.planx.uk/src/pages/FlowEditor/lib/store/preview.ts
- Updates `planx-core` to latest (`main`)
- Adds a few type guards to match changes made in https://github.com/theopensystemslab/planx-core/pull/78
> chore: Bump `planx-core`, update types

- editor.planx.uk/src/components/Header.tsx
- editor.planx.uk/src/routes/views/authenticated.tsx
- Fixes `initUserStore() is not a function` error which Airbrake has been catching intermittently since the `UserStore` was introduced
The bug can be triggered by navigating from the `/preview` or `/unpublished` ("standalone") routes back into the Editor via the breadcrumb link in the header. Breadcrumbs only appear if a team does not have a logo, so this bug is probably only being triggered by those working on the Templates or Testing teams.
This is happening because the "standalone" pages of the application do not build a full Zustand store, only selected "slices" which does not contain the user store. See code below - 
https://github.com/theopensystemslab/planx-new/blob/caf3fb9d5b2ed398b372042ab5b5216842a862bc/editor.planx.uk/src/pages/FlowEditor/lib/store/index.ts#L65-L93
This is …
> fix: `initUserStore() is not a function` bug

- editor.planx.uk/src/pages/FlowEditor/components/Flow/components/Portal.tsx
Addresses a small visual issue [flagged here on OSL Slack](https://opensystemslab.slack.com/archives/C5Q59R3HB/p1698246962206489?thread_ts=1698246212.639239&cid=C5Q59R3HB) where External Portals do not update as expected
https://github.com/theopensystemslab/planx-new/assets/20502206/cdd71588-288f-4538-a774-61a7fd4730f3
https://github.com/theopensystemslab/planx-new/assets/20502206/13e36e6a-199b-443d-a423-424fc10e1637
> fix: Change external portal cache strategy

- editor.planx.uk/src/@planx/components/FindProperty/Public/Map.tsx
- editor.planx.uk/src/@planx/components/shared/Preview/MapContainer.tsx
Quick fix for an outstanding issue I noticed when recently discussing this component.
The `MapContainer` currently does not encapsulate the `<MapFooter>` correctly as the `MyMap` element within it is styled to have `height: "100%"`. This means that any elements beneath it (such as the "Name the site" input) are not spaced correctly.
| | Before | After |
|   **Spacing**   | <img width="1034" alt="image" src="https://github.com/theopensystemslab/planx-new/assets/20502206/b2406ec8-24bf-43bd-8c99-160ffee281f5"> | <img width="1039" alt="image" src="https://github.com/theopensystemslab/planx-new/assets/20502206/a425a540-58fe-45b2-858b-8ead6f4445d3"> |
|   **Map Container**   | <img width="942" alt="image" src="https://github.com/theopensystemslab/planx-new/assets/205 …
> fix: Increase spacing above "Name the site" input

- infrastructure/application/index.ts
See https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#task_size
This should double the API vCPU from 0.5 → 1, which should help with Uniform submission issues.
> chore: Bump API task CPU

- editor.planx.uk/src/@planx/components/Content/Public.tsx
Fixes React error seen when in dev mode on the "Content" component.
> fix: React errors on content component

- api.planx.uk/editor/publish.test.ts
- api.planx.uk/editor/publish.ts
- api.planx.uk/gis/classifiedRoads.ts
- api.planx.uk/gis/local_authorities/metadata/braintree.js
- api.planx.uk/hasura/metadata/index.ts
- api.planx.uk/hasura/schema/index.ts
- api.planx.uk/helpers.test.ts
- api.planx.uk/helpers.ts
- api.planx.uk/inviteToPay/sendPaymentEmail.test.ts
- api.planx.uk/modules/webhooks/service/sanitiseApplicationData/index.ts
- api.planx.uk/modules/webhooks/service/sanitiseApplicationData/operations.ts
- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- api.planx.uk/saveAndReturn/utils.ts
- api.planx.uk/types.ts
- Address some eslint warnings in API tests
- Imports and uses types from `planx-core`
I've been staring at the message below a fair amount these past few days trying to sort E2E tests, so this is just a quick pass at addressing a few of these issues.
The eventual aim would be to remove the Passport / Flow etc types from the API and just use the ones from `planx-core`. This isn't a small change though so I'll just try chipping away at them here and there as a maintenance task 👍
> chore: Fix Run API test type warnings

- editor.planx.uk/src/@planx/components/FileUploadAndLabel/Public.tsx
- Update the `FileUploadAndLabel` component to order the slots with the most recently uploaded at the top.
- This includes the main page and the labelling modal.
- As per: https://trello.com/c/YDoIk2tG/2663-upload-and-label-new-files-to-appear-at-top-of-modal
- In user testing it was found that users were not seeing their most recently uploaded files as they were not being clearly displayed as they were rendered at the bottom of the list.
- This caused issues for labelling and frustration for users. 
- As per @jessicamcinchak's comment reversed the slot order in the `useEffect`
- Changing the order doesn't break the logic for uploading and labelling.
The files uploaded and their labels as seen by the user:
Subsequent update to the data with the labels assigned as expected:
> feat: first pass reordering uploaded files to show most recent first

- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
- editor.planx.uk/src/pages/FlowEditor/lib/analyticsProvider.tsx
- hasura.planx.uk/metadata/tables.yaml
- hasura.planx.uk/migrations/1698350858952_alter_table_public_analytics_logs_add_column_user_agent/down.sql
- hasura.planx.uk/migrations/1698350858952_alter_table_public_analytics_logs_add_column_user_agent/up.sql
- Appends user agent details to analytics, using the [Bowser library](https://github.com/lancedikson/bowser)
- Appends referrer details to analytics
> feat: Capture user agent and referrer analytics

- editor.planx.uk/src/@planx/components/FileUploadAndLabel/Modal.tsx
- editor.planx.uk/src/@planx/components/FileUploadAndLabel/model.ts
- Remove the `resetAllSlots` logic from `updateFileListWithTags`.
- Remove initial definition of `updatedFileList` from `updateFileListWithTags`.
- Refactor from `merge(fileList)` to `cloneDeep(fileList)`
- A bug was encountered where if a file had one tag which was then removed it would erroneously trigger the `resetAllSlots` which would wipe the tags applied to all files.
- As a tag can either be added or removed one at a time it was unclear what the use case for the reset was so it was removed to resolve the bug. 
- During debugging some opportunities for refactoring were found this included:
- Moving from single argument `merge` to `cloneDeep` as `merge` was not a deep clone leading us to mutate state directly.
- Removing the initial definition of `updatedFileList` from the …
> fix: remove reset logic which cleared all slots

- editor.planx.uk/src/@planx/components/Notice/Public.tsx
- editor.planx.uk/src/@planx/components/shared/Preview/SaveResumeButton.tsx
- editor.planx.uk/src/components/Header.tsx
- editor.planx.uk/src/pages/FlowEditor/lib/analyticsProvider.tsx
- When a user decided to click the "Save" application link update the analytics_log for the node with a flow_direction of "save"
- This should allow us to analyse which nodes are most saved on etc.
- This function is very similar to `trackResetFlow()`
- It might be worth adding a function which takes in a `flow_direction` and updates the `last_analytics_log` with that direction. 
```Typescript
async function trackFlowDirectionChange (flowDirection: AnalyticsLogDirection) {
if (shouldTrackAnalytics && lastAnalyticsLogId) {
await publicClient.mutate({
mutation: gql`
mutation UpdateFlowDirection($id: bigint!, $flow_direction: String) {
update_analytics_logs_by_pk(
pk_columns: { id: $id }
_set: { flow_direction: $flow_direction }
) {
id
}
}
`,
variables: {
id: lastAnalyticsLogId, …
```
> feat: track a user hitting the "Save" application link

- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- e2e/tests/api-driven/package.json
- e2e/tests/api-driven/pnpm-lock.yaml
- e2e/tests/ui-driven/package.json
- e2e/tests/ui-driven/pnpm-lock.yaml
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
so the admin endpoint for the digital planning schema is based to v0.1.2 !
> chore: bump `planx-core`

- e2e/tests/api-driven/src/globalHelpers.ts
- e2e/tests/api-driven/src/invite-to-pay/helpers.ts
- e2e/tests/ui-driven/src/context.ts
- e2e/tests/ui-driven/src/create-flow/create-flow.spec.ts
- e2e/tests/ui-driven/src/create-flow/helpers.ts
- e2e/tests/ui-driven/src/globalHelpers.ts
- e2e/tests/ui-driven/src/invite-to-pay/agent.spec.ts
- e2e/tests/ui-driven/src/invite-to-pay/helpers.ts
- e2e/tests/ui-driven/src/invite-to-pay/mocks.ts
- e2e/tests/ui-driven/src/invite-to-pay/nominee.spec.ts
- e2e/tests/ui-driven/src/login.spec.ts
- e2e/tests/ui-driven/src/pay.spec.ts
- e2e/tests/ui-driven/src/save-and-return.spec.ts
- e2e/tests/ui-driven/src/sections.spec.ts
- Reduces / removes flakiness of `user data persists on page refresh @regression` E2E Playwright test
- I've re-run this multiple times on CI (7-10 times?) without a failure so I've got a good degree of confidence it's better than the current implementation
- This is achieved by wrapping actions in a `Promise.all()`
- https://github.com/microsoft/playwright/issues/5470
- https://www.workwithloop.com/blog/our-1-solution-to-playwright-flakiness-waitforresponse-waitforrequest-promises
> fix: Improve flakey E2E tests

- api.planx.uk/modules/analytics/controller.ts
- api.planx.uk/modules/team/controller.ts
- api.planx.uk/modules/user/controller.ts
- api.planx.uk/modules/webhooks/controller.ts
- api.planx.uk/modules/webhooks/docs.yaml
- api.planx.uk/modules/webhooks/service/lowcalSessionEvents/index.test.ts
- api.planx.uk/modules/webhooks/service/lowcalSessionEvents/schema.ts
- api.planx.uk/shared/middleware/validate.ts
A "reminder" email failed this morning - the reason for this was that the required "email" field was missing from the event sent to Hasura.
This field was missed when [typing the schema for this endpoint](https://github.com/theopensystemslab/planx-new/pull/2252). This happened as the `routeSendEmailRequest()` function is not yet typed - meaning the variable was missed.
- Add "email" to schema
- Add test cases
- Also, don't overwrite `req` with `parsedReq` - this change means that non-updated endpoints shouldn't fail as the original `req` object is not touched. I'm now writing to `res.locals` ([docs](https://expressjs.com/en/api.html#res.locals)) which is a nice solution to the issue I was talking about in a previous dev call. We can now coerce types as part of validation in the …
> fix: Don't overwrite `req` with `parsedReq`

- editor.planx.uk/src/@planx/components/PlanningConstraints/Public.tsx
A4s not published yet, so no associated API changes here yet. From https://opensystemslab.slack.com/archives/C5Q59R3HB/p1699018486114879
For postcode: EN5 5UU
> chore: enable Barnet to query Planning Constraints

- api.planx.uk/inviteToPay/paymentRequest.ts
Regression tests are failing as an invalid body is being sent to GovPay to create a payment. The following error is returned from the GovPay sandbox API - 
```json
{
"field": "amount",
"code": "P0102",
"description": "Invalid attribute value: amount. Must be a valid numeric format"
}
```
The bug was introduced [here](https://github.com/theopensystemslab/planx-new/blob/6e7b88f48d279b14a47021ad4cfbb21a171bf1ab/api.planx.uk/inviteToPay/paymentRequest.ts#L71) in this PR - https://github.com/theopensystemslab/planx-new/pull/2356.
`req.params` must be a string, so the amount was cast to as string but never back to a number.
This is only on staging currently so will not be affecting customers.
I did locally run E2E regression tests on this branch but must not have rebuilt the API after these …
> fix: Correctly parse `amount` as number

- editor.planx.uk/src/@planx/components/Result/Public/ResultReason.tsx
- editor.planx.uk/src/@planx/components/shared/Preview/SummaryList.tsx
- editor.planx.uk/src/pages/FlowEditor/lib/analyticsProvider.tsx
- editor.planx.uk/src/pages/Preview/Questions.tsx
- Users can initiate moving backwards through the flow by node id via the `back` or `change` button.
- Track users initiating this and store the initiator i.e `back` or `change` and store target node metadata i.e. `title` and `type`.
- Currently we can't clearly infer when a user initiated moving backwards through a flow via the `back` or `change` button.
- Added some basic data of the target node being navigated back to gain insight on which question are challenging and which are often changed
https://github.com/theopensystemslab/planx-new/assets/36415632/4d32450a-6bc3-46f5-a2ab-bde0398c85fb
> feat: track a user navigating backwards through flow by node id

- api.planx.uk/helpers.ts
- api.planx.uk/modules/auth/middleware.ts
- API errors thrown when hitting certain routes called via the frontend (e.g. `/diff`)
- Errors suggest an issue with validation - `Could not verify JWT`
- Likely caused by recent change to permissions (https://github.com/theopensystemslab/planx-new/pull/2356 & https://github.com/theopensystemslab/planx-new/pull/2375)
- The middlewares `useRoleAuth` and `useLoginAuth` were only getting JWT's from `req.cookies`
- However, auth headers were being used by the frontend to pass along the JWT to the API
- Update middlewares to get this data from the auth headers
- API docs were reading `req.cookies` despite the additional Swagger authorisation
- E2E tests are adding a cookie to all requests using the helper method `createAuthenticatedSession()`
> fix: `Could not verify JWT` bug

- api.planx.uk/editor/publish.test.ts
- api.planx.uk/helpers.ts
- api.planx.uk/saveAndReturn/validateSession.ts
Over eager error handling excluded a use case where `mostRecent` should be falsy (on first publish)
> fix: Handle bug on first publish

- editor.planx.uk/src/@planx/components/PlanningConstraints/Public.tsx
- hasura.planx.uk/metadata/tables.yaml
- hasura.planx.uk/tests/planning_constraints_requests.test.js
August flagged this morning that on `/unpublished` routes, PlanningConstraints are failing to render correctly & throwing the following console error:
```json
{
"extensions": {
"path": "$.selectionSet.insert_planning_constraints_requests_one",
"code": "validation-failed"
},
"message": "field "insert_planning_constraints_requests_one" not found in type: 'mutation_root'"
}
```
Before: https://editor.planx.uk/barnet/find-out-if-you-need-planning-permission/unpublished
After: https://2392.planx.pizza/barnet/find-out-if-you-need-planning-permission/unpublished
**Changes**:
- Update `planning_constraints_requests` table to grant the `api` role select permissions, consistent with other audit tables, as this is necessary for the `insert_` mutation to return the new record's `id`
- Adjust frontend …
> fix: update audit table API permissions so unpublished routes can render PlanningConstraints

- editor.planx.uk/src/@planx/components/PlanningConstraints/Public.tsx
A4s not yet available https://www.planning.data.gov.uk/entity/?dataset=article-4-direction-area&geometry_curie=statistical-geography%3AE08000025&entry_date_day=&entry_date_month=&entry_date_year=
> chore: enable Birmingham to query planning constraints

- scripts/seed-database/write/flows.sql
A manual trigger of the data sync script failed here: https://github.com/theopensystemslab/planx-new/actions/runs/6849674665/job/18622337310#step:9:99
This is a bit of a tedious process:
- First we `select * from flows` in `scripts/seed_database/container.sh`
- Then, consequently, the specific list of columns in `scripts/seed_database/write/flows.sql` need to match `*`, even for columns like `analytics_link` where we don't want to sync the actual value across envs
I tested locally by running `pnpm test-sync` in the project root
> fix: account for new column `flows.analytics_link` in data sync script

- editor.planx.uk/src/@planx/components/Send/Public.tsx
- editor.planx.uk/src/components/FeatureFlagBanner.tsx
- editor.planx.uk/src/components/Header.tsx
- scripts/seed-database/write/flows.sql
Addresses this error: https://opensystemslab.slack.com/archives/C01E3AC0C03/p1699868054247069
Testing:
- With no feature flags toggled, a published flow will create "Send" events as expected. There is no warning banner.
- With the `DISABLE_SAVE_AND_RETURN` feature flag toggled, you can still proceed through Send to the Confirmation page, but no events have been created in Hasura. The warning banner is also visible.
> fix: show warning and skip Send event creation if `DISABLE_SAVE_AND_RETURN` feature flag is enabled

- editor.planx.uk/src/@planx/components/FileUploadAndLabel/Public.tsx
- editor.planx.uk/src/@planx/components/FileUploadAndLabel/model.ts
- Update the `removeFile` function to set the updated file list to state.
- This was written when the state was being updated directly and was therefore broken when the fileList was deep cloned.
Bug:
https://github.com/theopensystemslab/planx-new/assets/36415632/1d8f28c8-accb-458e-94c8-361ff1b1f9d7
Post fix:
https://github.com/theopensystemslab/planx-new/assets/36415632/a5535588-7c6b-41b4-b3c9-8db7188068fc
> fix: bug with file requirements not changing on delete of file

- hasura.planx.uk/metadata/tables.yaml
Reported here https://opendigitalplanning.slack.com/archives/C0241GWFG4B/p1699976778720039
Testing:
- As a platform admin you can "move" a flow to any team
- As a team editor you can "move" a flow to any team you have edit access to
> fix: `platformAdmin` and `teamEditor` roles need to be able to update `flows.team_id` for "move" functionality

- api.planx.uk/modules/misc/controller.ts
- api.planx.uk/modules/misc/docs.yaml
- api.planx.uk/modules/misc/routes.ts
- api.planx.uk/server.ts
- Document the `/download-application` endpoint
- Adds request validation
> feat: Document `/download-application` endpoint

- api.planx.uk/saveAndReturn/resumeApplication.test.ts
- api.planx.uk/saveAndReturn/resumeApplication.ts
This is a follow up to this comment - https://github.com/theopensystemslab/planx-new/pull/2356#discussion_r1381640332
Clearly I either didn't commit my change or I overwrote it on a merge somehow sorry.
We're currently pointing to the wrong table so "resume" requests will fail.
> fix: Point to `lowcal_sessions` table

- api.planx.uk/modules/file/file.test.ts
- api.planx.uk/modules/file/routes.ts
- api.planx.uk/server.ts
Reported here on ODP Slack - https://opendigitalplanning.slack.com/archives/C0241GWFG4B/p1700064607120349
Uploading files is not working from applicant facing flows.
The route guard `useTeamEditorAuth()` was incorrectly applied to the "public" and not the "private" - anybody can upload to private, only Editors can upload to public 🙃 
Maybe another sign that some E2E file upload tests may be a good idea to consider soon?
> fix: Apply auth to public upload, not private

- hasura.planx.uk/metadata/tables.yaml
- hasura.planx.uk/migrations/1700072112794_create_view_submission_services_summary/down.sql
- hasura.planx.uk/migrations/1700072112794_create_view_submission_services_summary/up.sql
As discussed in Slack and over dev call! Currently "select" permissions on this view are restricted to the "admin" role, which I think is all Metabase will need?
> feat: create a `submission_services_summary` database view for analytics

- editor.planx.uk/src/@planx/components/PlanningConstraints/Public.tsx
A4s not published yet, so frontend change only & no API metadata changes yet https://www.planning.data.gov.uk/entity/?dataset=article-4-direction-area&geometry_curie=statistical-geography%3AE07000240&entry_date_day=&entry_date_month=&entry_date_year=
> feat: enabled St Albans to query planning constraints

- api.planx.uk/modules/saveAndReturn/service/utils.ts
Trying to get a bit more insight into this error - https://planx.airbrake.io/projects/329753/groups/3673249731619951928?tab=overview
Payload and validation seem fine, can't locate the Hasura query log which indicates it never ran and it's maybe an import error somewhere with the client?
I'd like to get this across to prod, re-trigger action, then work on a fix...!
> chore: Improve email trigger error logging

- hasura.planx.uk/metadata/tables.yaml
- hasura.planx.uk/migrations/1700221802780_alter_table_public_teams_add_column_reference_code/down.sql
- hasura.planx.uk/migrations/1700221802780_alter_table_public_teams_add_column_reference_code/up.sql
Followup from https://github.com/theopensystemslab/digital-planning-data-schemas/pull/71
Once merged to production, I'll populate for all existing council-teams based on https://files.planning.data.gov.uk/dataset/local-authority.json?limit=400
> feat: add `teams.reference_code` to store Planning Data organisation

- scripts/seed-database/write/teams.sql
`teams.reference_code` is populated on production now, but this new column needs to be manually added to sync script and available across envs to generate the ODP schema payload successfully !
> fix: include `teams.reference_code` in data sync

- api.planx.uk/modules/saveAndReturn/service/utils.ts
- api.planx.uk/modules/sendEmail/index.test.ts
- api.planx.uk/modules/sendEmail/types.ts
- Follow on and fix for https://github.com/theopensystemslab/planx-new/pull/2436 
- Don't trigger reminder emails if a session is already submitted. We have a guard on these emails to not send, but it's actually simpler if we just don't create events unnecessarily in the first place
> fix: Change `undefined` to `null` in `confirmationEmailSchema`

- docker-compose.yml
- infrastructure/application/index.ts
Seemed worthwhile to pick this up whilst we're making changes and we've not updated in 8 months or so.
v0.47 should also allow us to turn on JSONB support on a per-table basis which would be a great UI win.
⚠️ I'm always slightly nervous about updating Metabase - let's just double check that rolling this up to staging works as expected and we don't lose any data there before promoting to prod ⚠️
> chore: Update Metabase to v0.47.8

- editor.planx.uk/src/@planx/components/shared/Preview/SummaryList.tsx
Resolves https://planx.airbrake.io/projects/329753/groups/3674911676429344553?tab=overview and https://planx.airbrake.io/projects/329753/groups/3672018983332190585?tab=notice-detail
The session caught by the most recent exception had nodeIds in the breadcrumbs which are no longer in the flow which caused this issue. The session does have records in `reconciliation_requests` which show changes between answered questions and the newly published flow - hence the additional breadcrumbs.
I'm going to take a closer look at `removeAlteredAndAffectedBreadcrumb()` to try and work out why this breadcrumb wasn't dropped which is the ultimate cause of this issue.
> fix: `SummaryList` bug

- editor.planx.uk/src/@planx/components/FileUploadAndLabel/Modal.tsx
- Update the modal component so that for each instance of the `SelectMultiple` component the `previousTags` are previous state or the `initialTags` on first render
-  Updates are checked but an update isn't applied as the previousTags = intialTags
- When the modal is rendered when there are two files it renders two `SelectMultiple` components and they were incorrectly updating the `fileList` as the `previousTags` variable was `undefined`
- Therefore the uploaded file was effectively being removed from the slots. 
Bug
https://github.com/theopensystemslab/planx-new/assets/36415632/4cc83831-dd36-4a14-b834-d02b920f5e92
Fix
https://github.com/theopensystemslab/planx-new/assets/36415632/f9fe4618-29d1-4eed-b9c5-06bc81dda470
> fix: repeated label removed from file on change click bug

- editor.planx.uk/src/@planx/components/PlanningConstraints/Public.tsx
- editor.planx.uk/src/types.ts
As more councils are coming onboard, this change will let us skip [PRs for Trello tickets like this one](https://trello.com/c/JVlAfSp5/2701-hook-up-planning-data-constraints-for-st-albans) and instead just add the property `"hasPlanningData": true` to `teams.settings` in the prod Hasura console for this council. No changes to permissions or the staging data sync are necessary for this to work as expected.
We will **still** open PRs to add API GIS metadata when a council's granular Article 4 variables become available.
Also updated council onboarding step in README here: https://github.com/theopensystemslab/planx-team-onboarding/tree/main#after-running-this-script
Future scope: expose this property via the Team Settings page in the Editor or via admin endpoint in the short term (probably …
> feat: add `hasPlanningData` property to `teams.settings`

- editor.planx.uk/src/pages/FlowEditor/components/PreviewBrowser.tsx
https://github.com/mui/material-ui/issues/8416
> fix: MUI tooltip warning on analytics button

- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
- editor.planx.uk/src/routes/utils.ts
- `NotFound` errors on routes in staging (not replicable yet on local dev)
- See OSL Slack for context - https://opensystemslab.slack.com/archives/C01E3AC0C03/p1700476380638669
- I'm not totally confident that this is the cause but as the query isn't firing it makes sense to try this
- At minimum we rationalise how we do caching / memoization, drop our bundle size, and rule a variable out of the equation.
> chore: Drop p-memoize in favour of Apollo caching

- api.planx.uk/modules/send/docs.yaml
`sessionId` is already a param in the path here - it's not required to be repeated again in the query.
> docs: Remove repeated `sessionId` param

- api.planx.uk/modules/admin/routes.ts
- api.planx.uk/modules/analytics/routes.ts
- api.planx.uk/modules/file/routes.ts
- api.planx.uk/modules/flows/routes.ts
- api.planx.uk/modules/team/routes.ts
- api.planx.uk/modules/user/routes.ts
- api.planx.uk/modules/webhooks/routes.ts
- api.planx.uk/server.ts
- Moves full route path to `router.ts` files and out of `server.ts`
- This means that the full route lives in one place instead of being split over two files
> chore: Tidy up routes

- editor.planx.uk/src/@planx/components/Calculate/Editor.tsx
Quick & simple for now - I'd love to take a pass at all components sometime in the future :art:
> fix: link math.js documentation in Calculate node modal

- api.planx.uk/modules/send/utils/exportZip.test.ts
- api.planx.uk/modules/send/utils/exportZip.ts
Reverts theopensystemslab/planx-new#2380 - building this pizza again to see if it introduced issue described here (**update: it did**): https://opendigitalplanning.slack.com/archives/C0241GWFG4B/p1700561792278499
Fixes issue where user-uploaded files appear not to be included in zip reported in #help-issues. On production, I can still see a `/tmp` folder &rarr; `{sessionId}_{s3FolderId}` folder &rarr; user uploaded files, but it sounds like for MS users the `/tmp` folder is being hidden altogether ! 
This one was a small tidy up without major performance impacts, so just going to revert & deploy fix for now & will add a Trello ticket to pick back up and solve properly :ok_hand:
> Revert "chore: Stream S3 files directly to zip"

- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
- editor.planx.uk/src/pages/FlowEditor/components/PreviewBrowser.tsx
- editor.planx.uk/src/pages/FlowEditor/floweditor.scss
The app currently uses a mixture of the React Feather and MUI Icons libraries to serve icons.
Instances of React Feather replaced with MUI Icons and dependency removed.
Edit: also updates sizing and margins to increase visual and target size.
Before:
After:
> chore: remove react-feather icon library

- editor.planx.uk/src/pages/FlowEditor/components/PreviewBrowser.tsx
Simple one — the debug console toggles in the editor browser preview with no difference in style from the browser background, meaning there is no visual boundary between the two.
PR adds a subtle border and background to create the delineation.
Before:
After:
> feat: Simple styling for editor console

- editor.planx.uk/src/theme.ts
- editor.planx.uk/src/ui/RichTextImage.tsx
The theme.ts file currently uses a mixture of variables, palette variables and hardcoded colours, this PR simplifies it so that the palette variables are used throughout.
> chore: Unify colour refs in theme

- editor.planx.uk/src/@planx/components/FileUploadAndLabel/Public.tsx
- editor.planx.uk/src/@planx/components/Notice/Public.tsx
- editor.planx.uk/src/@planx/components/shared/Preview/Card.tsx
- editor.planx.uk/src/@planx/components/shared/Preview/QuestionHeader.tsx
- editor.planx.uk/src/theme.ts
User-testing feedback and analytics have told us that we need to rethink the position and style of the help text button.
**Summary of changes**
- Reposition button from right-side of viewport to within the content flow (maintaining sticky positioning)
- Update and use the 'outline' button variant
- Add dedicated width, height (min 44px in each dimension as WCAG AAA guidance), font size and drop shadow
**Live example**
https://2435.planx.pizza/lambeth/help-button-test/preview
**Visual example**
> feat: Reposition and style help text button

- sharedb.planx.uk/package.json
- sharedb.planx.uk/pnpm-lock.yaml
- sharedb.planx.uk/server.js
- Uses [DOMPurify](https://github.com/cure53/DOMPurify) to sanitise input on "commit" to ShareDB
- Look at blocking flow updates via GraphQL API
- Try to work out a reliable testing methodology (in another PR). It looks like Playwright has a WebSocket class that should allow the intercept of an outgoing frame to attempt to inject unsafe content (Docs: https://playwright.dev/docs/api/class-websocket)
https://github.com/theopensystemslab/planx-new/assets/20502206/6fa17f8e-f53f-42b6-94c2-314518a640da
> feat: Sanitise operations on commit to ShareDB

- editor.planx.uk/src/@planx/components/shared/Preview/QuestionHeader.tsx
The updated help text introduced a bug where the help text button container overlaps certain elements. This is caused by an absolute-positioned div that runs along the right-hand-side of the column.
By removing pointer-events from the column and reintroducing it on the button, no content is blocked.
Current example (bug present):
https://editor.planx.dev/testing/test-upload-and-label/preview?analytics=false
Fixed example:
https://2486.planx.pizza/testing/test-upload-and-label/preview?analytics=false
> fix: help text pointer overlap

- editor.planx.uk/src/components/Header.tsx
Fixes bug reported here: https://opendigitalplanning.slack.com/archives/C0241GWFG4B/p1701170825043769
Underlying permissions were correct, but edit-able teams were showing a view-only icon at the flow level. 
Steps to re-create issue:
- Login into editor as a non-platformAdmin
- At the teams-level, you see the correct icons
- Pick a team you can edit, you see the correct icons for the list of services
- At the graph view of an individual flow, you see the incorrect icon but have the correct permissions
> fix: get team from store, not route data, to display permissions icons in Editor

- editor.planx.uk/src/pages/FlowEditor/lib/__tests__/canGoBack.test.ts
- editor.planx.uk/src/pages/FlowEditor/lib/store/preview.ts
- editor.planx.uk/src/pages/Preview/Questions.tsx
- Hides the back bar when we reach a confirmation component
This is a small visual thing which has bugged me since we introduced the save and return status pages which have the banner starting at the top of the page, making this look a little inconsistent.
**Why not just hide the entire backbar on a single condition?**
This would mean that the layout would jump in instances where the back button should be hidden (e.g. first card).
| <img width="1439" alt="image" src="https://github.com/theopensystemslab/planx-new/assets/20502206/c6b37890-d8c7-4077-80ad-4009becd41af"> | <img width="1438" alt="image" src="https://github.com/theopensystemslab/planx-new/assets/20502206/e0fd5048-84eb-4e03-927a-6d34eaff343d"> |
> fix: Remove empty back bar from confirmation component

- e2e/tests/ui-driven/src/globalHelpers.ts
- editor.planx.uk/src/@planx/components/Pay/Public/Pay.tsx
- Fixes regression tests which are failing as they expect to find `sessionId` via the URL (context: )
- Instead, we can access this from our [`window.api`](https://github.com/theopensystemslab/planx-new/blob/cf1e311111541c4c41d649d0deebc972a089330d/editor.planx.uk/src/pages/FlowEditor/lib/store/index.ts#L106) methods, and Playwright's [`page.evalutate()`](https://playwright.dev/docs/evaluating) API
- Prior discussion on this here - https://github.com/theopensystemslab/planx-new/pull/1485#discussion_r1117488853
E2E regression test suite passing locally and on CI ✅ https://github.com/theopensystemslab/planx-new/actions/runs/7023467552
> test(e2e): Access `sessionId` via store, not URL

- api.planx.uk/modules/file/docs.yaml
Noticed this when looking into https://opensystemslab.slack.com/archives/C01E3AC0C03/p1701187355822639
Follow on from https://github.com/theopensystemslab/planx-new/pull/2427
> fix(docs): Auth on public, not private

- api.planx.uk/lib/notify/index.ts
- api.planx.uk/modules/admin/session/bops.test.ts
- api.planx.uk/modules/admin/session/digitalPlanningData.test.ts
- api.planx.uk/modules/admin/session/oneAppXML.test.ts
- api.planx.uk/modules/admin/session/summary.test.ts
- api.planx.uk/modules/admin/session/zip.test.ts
- api.planx.uk/modules/pay/service/inviteToPay/sendPaymentEmail.test.ts
- api.planx.uk/modules/pay/service/inviteToPay/sendPaymentEmail.ts
- api.planx.uk/modules/saveAndReturn/service/utils.test.ts
- api.planx.uk/modules/saveAndReturn/service/utils.ts
- api.planx.uk/modules/sendEmail/index.test.ts
- api.planx.uk/tests/mocks/saveAndReturnMocks.ts
Follow on from https://github.com/theopensystemslab/planx-new/pull/2466 - please see this PR for details.
> test: Cover error handling cases in API tests (2/2)

- api.planx.uk/client/index.test.ts
- api.planx.uk/helpers.test.ts
- api.planx.uk/lib/hasura/metadata/index.test.ts
- api.planx.uk/lib/hasura/metadata/index.ts
- api.planx.uk/lib/hasura/schema/index.test.ts
- api.planx.uk/lib/notify/index.test.ts
- api.planx.uk/lib/notify/index.ts
- api.planx.uk/modules/admin/session/bops.test.ts
- api.planx.uk/modules/admin/session/digitalPlanningData.test.ts
- api.planx.uk/modules/admin/session/oneAppXML.test.ts
- api.planx.uk/modules/admin/session/summary.test.ts
- api.planx.uk/modules/admin/session/zip.test.ts
- api.planx.uk/modules/flows/copyFlow/copyFlow.test.ts
- api.planx.uk/modules/flows/copyFlowAsPortal/service.ts
- api.planx.uk/modules/flows/findReplace/findReplace.test.ts
- api.planx.uk/modules/flows/findReplace/service.ts
- api.planx.uk/modules/flows/moveFlow/moveFlow.test.ts
- api.planx.uk/modules/flows/publish/publish.test.ts
- api.planx.uk/modules/pay/service/inviteToPay/sendPaymentEmail.test.ts
- api.planx.uk/modules/pay/service/inviteToPay/sendPaymentEmail.ts
- api.planx.uk/modules/saveAndReturn/service/utils.test.ts
- api.planx.uk/modules/saveAndReturn/service/utils.ts
- api.planx.uk/modules/saveAndReturn/service/validateSession.test.ts
- api.planx.uk/modules/send/email/index.test.ts
- api.planx.uk/modules/send/email/index.ts
- api.planx.uk/modules/sendEmail/index.test.ts
- api.planx.uk/modules/webhooks/service/sanitiseApplicationData/operations.test.ts
- api.planx.uk/tests/mocks/saveAndReturnMocks.ts
- Tidies up a few uncovered branches with test cases following refactors for documentation and stronger enforcing of types
- Most test cases just cover exception handling, but there's a few others thrown in
- I see it as a helpful step before trying to take on https://trello.com/c/TfmJiwID/2686-fix-airbrake-error-logging-on-api
- PR was growing in size so I'll pick up the rest next week - happy for this to be merged upon review
| - | Before | After |
| Statements | 79.32% | 80.41% | 
| Branches | 50.69% | 55.68% | 
| Functions | 67.88% | 67.88% | 
| Lines | 78.79% | 79.66% |
> test: Cover error handling cases in API tests (1/2)

- editor.planx.uk/src/@planx/components/FindProperty/Public/Autocomplete.tsx
Per feedback from Birmingham about not picking up a classified road as expected - has been tested by council and working as expected now :heavy_check_mark: https://opensystemslab.slack.com/archives/C5Q59R3HB/p1701099275002579
Notes: 
- Original UPRN padding comes from here, but it was a faulty assumption that USRN should be same: https://github.com/theopensystemslab/planx-new/pull/694
- ODP schema only defines a `maxLength` for USRN & UPRN, so this will still validate fine!
> fix: remove zero padding for USRNs

- editor.planx.uk/src/api/upload.ts
- Add auth header to the public file upload
- The public upload requires at least `teamEditor` permissions for uploading files
Bug:
https://github.com/theopensystemslab/planx-new/assets/36415632/6224bd31-2b53-4906-b77e-b00841461268
Fix:
https://github.com/theopensystemslab/planx-new/assets/36415632/d704e7d5-4934-4077-b976-810e0594ecd0
> fix: add auth header to public image upload

- editor.planx.uk/src/@planx/components/Calculate/Editor.tsx
- editor.planx.uk/src/@planx/components/Checklist/Editor.tsx
- editor.planx.uk/src/@planx/components/Confirmation/Editor.tsx
- editor.planx.uk/src/@planx/components/DrawBoundary/Editor.tsx
- editor.planx.uk/src/@planx/components/FileUploadAndLabel/Editor.tsx
- editor.planx.uk/src/@planx/components/InternalPortal/Editor.tsx
- editor.planx.uk/src/@planx/components/PlanningConstraints/Editor.tsx
- editor.planx.uk/src/@planx/components/Question/Editor.tsx
- editor.planx.uk/src/lib/featureFlags.ts
- editor.planx.uk/src/pages/FlowEditor/components/Settings/DesignSettings.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Settings/ServiceSettings.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Settings/index.tsx
- editor.planx.uk/src/pages/FlowEditor/components/forms/FormModal.tsx
- editor.planx.uk/src/ui/ColorPicker.tsx
- editor.planx.uk/src/ui/EditorRow.tsx
- editor.planx.uk/src/ui/ImgInput.tsx
- editor.planx.uk/src/ui/Input.tsx
- editor.planx.uk/src/ui/InputCaption.tsx
- editor.planx.uk/src/ui/InputDescription.tsx
- editor.planx.uk/src/ui/InputField.tsx
- editor.planx.uk/src/ui/InputGroup.tsx
- editor.planx.uk/src/ui/InputLegend.tsx
- editor.planx.uk/src/ui/InputRow.tsx
- editor.planx.uk/src/ui/InputRowLabel.tsx
- editor.planx.uk/src/ui/ModalSection.tsx
- editor.planx.uk/src/ui/ModalSectionContent.tsx
- editor.planx.uk/src/ui/ModalSubtitle.tsx
- editor.planx.uk/src/ui/OptionButton.tsx
- editor.planx.uk/src/ui/PublicFileUploadButton.tsx
- editor.planx.uk/src/ui/RichTextInput.css
Two main areas of work addressed:
UI has been added for the following (UI only, no working functionality at present).
1. Theme colour with colour picker
2. Logo with file upload
3. Favicon with file upload
Note: I've added example links to guides for each of these elements. I'll make sure these are in place on our PlanX Notion before the work goes live.
As part of this I have created the `EditorRow` UI component with optional background variant, to be used for each row of settings. 
As guided by @jessicamcinchak this sits behind the feature flag `window.featureFlags.toggle("SHOW_TEAM_SETTINGS")`
Preview:
https://2491.planx.pizza/buckinghamshire/find-out-if-you-need-planning-permission/settings/design
Interwoven with and as an extension of the above, I've given the editor UI a going over …
> feat: Editor styles and layout update

- editor.planx.uk/.storybook/preview-head.html
- editor.planx.uk/public/index.html
The header files for PlanX contain obsolete references to Source Sans Pro, served from Google Fonts.
Removing these should save on potential unnecessary files being loaded in a user session.
> chore: Remove obsolete Source Sans Pro ref from header

- hasura.planx.uk/metadata/tables.yaml
- hasura.planx.uk/migrations/1701282718987_create_table_public_team_integrations/down.sql
- hasura.planx.uk/migrations/1701282718987_create_table_public_team_integrations/up.sql
- hasura.planx.uk/tests/team_integrations.test.js
- scripts/seed-database/container.sh
- scripts/seed-database/write/main.sql
- scripts/seed-database/write/team_integrations.sql
- Adds a new `team_integrations` table
- Sets up sync script for this table
As we need to add environment details for Medway it seems sensible to start tidying this up and dropping the numerous env vars we have holding these details.
In future we could also store encrypted API keys here.
Doing this means we don't need to manage an additional data sync from staging to Pizza environments (which currently has production data, but staging secrets). By only copying across the relevant column for the environment, we can avoid managing an additional data sync process. The slight compromise here is that if we allow the setting of these values in the Editor, we'll just need to ensure we just access the environment-appropriate column.
- Merge to `production`
- Populate table with values currently …
> feat: Add `team_integrations` table

- editor.planx.uk/src/pages/FlowEditor/lib/__tests__/flags.test.ts
- editor.planx.uk/src/pages/FlowEditor/lib/__tests__/ordering.test.ts
- editor.planx.uk/src/pages/FlowEditor/lib/__tests__/preview/canGoBack.test.ts
- editor.planx.uk/src/pages/FlowEditor/lib/__tests__/preview/changeAnswer.ts
- editor.planx.uk/src/pages/FlowEditor/lib/__tests__/preview/getResultData.test.ts
- editor.planx.uk/src/pages/FlowEditor/lib/__tests__/preview/hasPaid.test.ts
- editor.planx.uk/src/pages/FlowEditor/lib/__tests__/preview/overrideAnswer.test.ts
- editor.planx.uk/src/pages/FlowEditor/lib/__tests__/preview/previousCard.test.ts
- editor.planx.uk/src/pages/FlowEditor/lib/__tests__/preview/record.test.ts
- editor.planx.uk/src/pages/FlowEditor/lib/__tests__/preview/removeNodesDependentOnPassport.test.ts
- editor.planx.uk/src/pages/FlowEditor/lib/__tests__/preview/removeOrphansFromBreadcrumbs.test.ts
- editor.planx.uk/src/pages/FlowEditor/lib/__tests__/preview/resetPreview.test.ts
- editor.planx.uk/src/pages/FlowEditor/lib/__tests__/preview/upcomingCardIds.test.ts
Replaces #2299 
Changes:
- Splits up `preview.test.ts` by method name for more isolated testing (this isn't perfect because so many store methods call each other, but definitely an improvement in readability I think!)
- Takes a first pass through mock flow data and tidies up types (import from `TYPES`), replaces node ids with human readable ones, etc. Definitely more that could be consolidated here, but there's enough initial changes here for now
There's a few new & existing `.skip` and `.todo` annotated tests throughout which detail future expected behavior for autoAnswers, filters, getResult and more.
> chore: tidy logic tests

- hasura.planx.uk/metadata/tables.yaml
- hasura.planx.uk/tests/payment_status.test.js
hit this minor permissions issue while trying to use the `/summary` admin endpoint ! 
eg https://api.editor.planx.uk/admin/session/978e8024-e7ba-471d-8656-088c76b8cd56/summary
> fix: api client should be able to select * from `payment_status`

- editor.planx.uk/src/theme.ts
- editor.planx.uk/src/ui/Input.tsx
- editor.planx.uk/src/ui/RichTextInput.tsx
The recent changes applied to the editor introduced a small visual bug on the public-facing UI where a rich text input shifts 1px in each direction when focused. The PR introduces a default input focus style to the theme and extends it to be applied only to bordered inputs.
Live example (enter text and focus/unfocus to see layout shift):
https://editor.planx.uk/testing/rich-text-test/preview?analytics=false
Fixed example:
https://2531.planx.pizza/testing/rich-text-test/preview?analytics=false
> fix: Input focus styles for editor and public UI

- api.planx.uk/modules/gis/service/digitalLand.ts
- api.planx.uk/modules/gis/service/local_authorities/metadata/base.ts
Just spotted this when testing - it looks like category for article 4s are not being returned by API so the UI is defaulting to `undefined`.
I don’t think there have really been any recent changes here that could have caused this - there might be another solution (or cause!) I'm missing here so this might be a naive fix...!
Waiting on Pizza to test changes 🚀 
Original request URL (undefined): 
https://api.2529.planx.pizza/gis/southwark?geom=POLYGON+%28%28-0.0807095109084621+51.50357969225416%2C+-0.08026678402163087+51.50357732850256%2C+-0.0803878763290122+51.50339599741571%2C+-0.0807095109084621+51.50357969225416%29%29&analytics=false
> fix: Assign missing A4 category

- editor.planx.uk/src/@planx/components/Pay/Public/Confirm.tsx
- editor.planx.uk/src/theme.ts
Another quick fix I've been meaning to get round to since a while - 
| <img width="580" alt="image" src="https://github.com/theopensystemslab/planx-new/assets/20502206/71bc0ed7-3c56-4e7c-bba9-15fdf6a3ce72"> |<img width="614" alt="image" src="https://github.com/theopensystemslab/planx-new/assets/20502206/865cb3a1-8765-4ef5-acca-753a03d7fe7d"> | 
This also now more closely aligns to GDS style in that the underline / box shadow is retained on hover - https://design-system.service.gov.uk/components/button/
> fix(style): ITP button underline

- api.planx.uk/modules/admin/docs.yaml
Quick fix for an issue I noticed the other day when discussing the FeedbackFish API.
Currently the URL stored in 1Password works, but this is inaccessible via Swagger as the cookie is encoded when entered into the API docs.
Docs: https://swagger.io/docs/specification/describing-parameters/ (see "Reserved Characters in Query Parameters")
> fix(api): Allow reserved characters for FeedbackFish endpoints

- editor.planx.uk/src/pages/Preview/ResumePage.tsx
- editor.planx.uk/src/pages/Preview/SaveAndReturn.test.tsx
- editor.planx.uk/src/pages/Preview/SaveAndReturn.tsx
- editor.planx.uk/src/utils.ts
Reverts theopensystemslab/planx-new#2485
From Jumpsec - 
> Regarding the issue with a session value being contained within GET parameters, I believe this should be fine and I have removed it from the findings (due to an email address being required for further authorisation).
Reverting this restores the `allowResumeOnBrowserRefresh()` functionality which I didn't really have a decent / simple fix in mind for 👍 
Related change https://github.com/theopensystemslab/planx-new/pull/2494 is good to stay in place as this is still a valid alternate method of grabbing the `sessionId` value.
> Revert "fix: remove sessionId from URLs"

- api.planx.uk/modules/auth/service.test.ts
- api.planx.uk/modules/auth/service.ts
- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- e2e/tests/api-driven/package.json
- e2e/tests/api-driven/pnpm-lock.yaml
- e2e/tests/ui-driven/package.json
- e2e/tests/ui-driven/pnpm-lock.yaml
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
- hasura.planx.uk/migrations/1701434967109_alter_table_public_users_add_column_is_staging_only/down.sql
- hasura.planx.uk/migrations/1701434967109_alter_table_public_users_add_column_is_staging_only/up.sql
- scripts/seed-database/write/users.sql
- Adds an additional check on login, to ensure users can access production environment
As we sync the users table across environments, this means all users can access production. Generally this is what we want as "real" users live on production and this allows them to access test and staging environments - all good.
The catch is that occasionally we have a set of users who we do not wish to grant access to production - for example the user accounts associated with the recent pen test, or certain sets of users with "demo" access (until we have these roles set up). This is not a common occurrence or user type, but it feels like a sensible restriction to put in place restrictions here as a bit of a guard rail.
> feat: Restrict certain users from production environments

- api.planx.uk/modules/flows/findReplace/controller.ts
- editor.planx.uk/src/ui/ReactMarkdownOrHtml.tsx
- sharedb.planx.uk/server.js
Reason DOMPurify strips this - https://developer.chrome.com/docs/lighthouse/best-practices/external-anchors-use-rel-noopener/
> When you link to a page on another site using the target="_blank" attribute, you can expose your site to performance and security issues:
>
> The other page may run on the same process as your page. If the other page is running a lot of JavaScript, your page's performance may suffer.
>
> The other page can access your window object with the window.opener property. This may allow the other page to redirect your page to a malicious URL.
> Adding `rel="noopener"` or `rel="noreferrer"` to your `target="_blank"` links avoids these issues.
Discussion / solution found here: https://github.com/cure53/DOMPurify/issues/317
> fix: Allow `target="_blank"` in anchors

- api.planx.uk/modules/flows/findReplace/findReplace.test.ts
- Adds test coverage for changes made in this PR - https://github.com/theopensystemslab/planx-new/pull/2536
- Very much imperfect - we'd need E2E tests for all scenarios to be covered, but my main aim here is to write a test that fails if DOMPurify is replaced / removed to the config updated in a breaking way
> test: Cover HTML anchor target attribute stipping

- api.planx.uk/modules/gis/service/digitalLand.ts
- api.planx.uk/modules/gis/service/local_authorities/metadata/birmingham.ts
Pending one outstanding question https://opensystemslab.slack.com/archives/C5Q59R3HB/p1701441593601269 &larr; let's address this in a followup PR since it's been a slow response from the council!
> chore: add granular A4 GIS variables for Birmingham

- api.planx.uk/modules/pay/index.test.ts
- api.planx.uk/modules/pay/middleware.ts
- editor.planx.uk/src/@planx/components/Pay/model.ts
Short & simple as this is a bit of an exploratory task still at this point - we'll see if any councils notice & can extend the `metadata` type as necesary based on any future requests !
> feat: add basic metadata to GOV.UK Pay requests

- editor.planx.uk/src/ui/Input.tsx
- editor.planx.uk/src/ui/RichTextInput.tsx
URLs entered into the editor rich-text input do not currently wrap and therefore longer URLs will expand the container beyond the layout. Adding a `word-wrap` property to inserted URLs fixes this.
**Current example:**
https://editor.planx.uk/barnet/article4/nodes/_root/nodes/CnIGlaoSRM/edit
**Fixed example:**
https://2552.planx.pizza/barnet/article4/nodes/_root/nodes/CnIGlaoSRM/edit
> fix: Long URL wrapping in editor

- editor.planx.uk/src/@planx/components/Checklist/Editor.tsx
- editor.planx.uk/src/@planx/components/Question/Editor.tsx
- editor.planx.uk/src/ui/Input.tsx
- editor.planx.uk/src/ui/ModalSectionContent.tsx
The current editor layout becomes unusable at smaller screen sizes due to columns and indentation. This PR introduces small changes to make it somewhat more usable. Also removes a rogue 25px hardcoded size for inputs that was only showing up at smaller breakpoints.
**Before (left) & after (right):**
> fix: Editor layout for small screens

- editor.planx.uk/src/ui/SelectInput.tsx
Reported by August — The click area of the MUI Select component used in the editor is smaller than the input container, meaning that there are clickable areas (including the chevron/arrow) that focus the input but do not toggle the select. Small changes to element and parent padding ensure that the clickable area fills the container.
**Visual example (pink is clickable area that toggles select):**
**Current example:**
https://editor.planx.uk/barking-and-dagenham/find-out-if-you-need-planning-permission/nodes/_root/nodes/XqMey8xqx4/edit
**Fixed example:**
https://2555.planx.pizza/barking-and-dagenham/find-out-if-you-need-planning-permission/nodes/_root/nodes/XqMey8xqx4/edit
> fix: Touch area for MUI Select

- infrastructure/application/Pulumi.production.yaml
The most recent prod deploy failed with the following message - 
```
Diagnostics:
pulumi:pulumi:Stack (application-production):
error: Missing required configuration variable 'application:file-api-key-nexus'
please set a value using the command `pulumi config set --secret application:file-api-key-nexus <value>`
```
The value was intentionally not set for production, however it is included in the Pulumi build and I'm uncertain if left blank how this would be handled (looking at tests now).
Rather than add temporary code to check the environment as part of `useFilePermission()` I think it's simpler for now to set and generate the key, but just keep secret.
> chore: Setup prod Nexus key

- api.planx.uk/modules/auth/middleware.test.ts
- api.planx.uk/modules/auth/middleware.ts
Follow on from https://github.com/theopensystemslab/planx-new/pull/2557 as I was unsure how the API would handle an undefined API key.
Turns out it handles it just fine and an error is thrown 👍 
It will still match on `"" === ""` which isn't wrong but is very likely not going to be a valid check in the context we use `isEqual()` - I've added a guard for this. If you think this is redundant please let me know....!
This function already has coverage from a number other test suites (e.g. `api.planx.uk/modules/file/file.test.ts` and `api.planx.uk/modules/send/bops/bops.test.ts`) but a few unit tests just explaining how it handles these edge cases is a bit more reassuring I think!
> test: Add basic tests describing `isEqual()` function

- hasura.planx.uk/migrations/1702312905340_alter_view_analytics_summary_add_analytics_session_length_data/down.sql
- hasura.planx.uk/migrations/1702312905340_alter_view_analytics_summary_add_analytics_session_length_data/up.sql
- Found that it wasn't possible to replicate the ["Average time spent"](https://metabase.editor.planx.uk/question/15-average-time-spent?flow_id=0e9d79ec-9cf3-497d-a1a1-8e70469bb52d) card without analytics session ended at
- Added this to the view to make it accessible in the "Question" GUI.
- For council users to use the GUI and edit their dashboard it's necessary for their questions to be written against the "Analytics Summary" or "Submission Services Summary" views with the GUI.
> feature: add analytics session ended_at to view

- api.planx.uk/modules/auth/middleware.test.ts
- api.planx.uk/modules/auth/middleware.ts
- api.planx.uk/modules/pay/index.test.ts
- api.planx.uk/modules/pay/middleware.ts
- editor.planx.uk/src/@planx/components/Checklist/Editor.tsx
- editor.planx.uk/src/@planx/components/Pay/model.ts
- editor.planx.uk/src/@planx/components/Question/Editor.tsx
- editor.planx.uk/src/ui/Input.tsx
- editor.planx.uk/src/ui/ModalSectionContent.tsx
- editor.planx.uk/src/ui/RichTextInput.tsx
- editor.planx.uk/src/ui/SelectInput.tsx
- hasura.planx.uk/migrations/1702312905340_alter_view_analytics_summary_add_analytics_session_length_data/down.sql
- hasura.planx.uk/migrations/1702312905340_alter_view_analytics_summary_add_analytics_session_length_data/up.sql
- infrastructure/application/Pulumi.production.yaml
To replaced failed run https://github.com/theopensystemslab/planx-new/actions/runs/7182808055 (fixed by https://github.com/theopensystemslab/planx-new/commit/d885b24d3983e79b9902e0a3ad34bd513fc82c44)
> Production deploy

- hasura.planx.uk/Dockerfile
- hasura.planx.uk/metadata/functions.yaml
- hasura.planx.uk/metadata/tables.yaml
- Update Hasura from v2.8.4 → v.2.36.0
- Automated updates `tables.yaml` and `function.yaml`
- I added/removed a permission (so no changes) which triggered an update to alphabetise these files
- Without this step the next PR that touches the file gets very noisy
- This also removed 5 instances of `backend_only: false` which is redundant as this is the default value
- It's been a while! Last update was July 2022.
- There are a few features I'd love to pick up - inherited roles could be helpful (and we've previously discussed this), and I'm looking to implement [Postgres input validation](https://hasura.io/docs/latest/schema/postgres/input-validations/) to tackle recent sanitation questions
- Testing locally seems fine ✅ 
- Testing on Pizza 🚀 
- Regression tests on branch ✅
> chore: Update Hasura to v2.36.0

- api.planx.uk/modules/pay/middleware.ts
Fixes failed regression tests on `main` this morning: https://github.com/theopensystemslab/planx-new/actions/runs/7191369572
Now passing on this branch: https://github.com/theopensystemslab/planx-new/actions/runs/7193346466
Gov Pay was throwing this error: 
```
code: "P0102"
description: "Invalid attribute value: metadata. Values must be no greater than 100 characters long"
field: "metadata"
```
This was only effecting invite-to-pay cases, _not_ "regular" payments initiated on the frontend - as these always have direct access to the `flowSlug` in state and do not rely on parsing the `returnUrl`.
Metadata is now correctly captured:
> fix: correctly parse flow slug for invite-to-pay cases for GOV Pay metadata

- editor.planx.uk/src/@planx/components/shared/Preview/SummaryList.tsx
Fixing a small style regression that crept in here https://github.com/theopensystemslab/planx-new/pull/2481
Test: 
- Review page for flow without sections https://2565.planx.pizza/testing/review-without-sections/preview
- Review page with sections https://2565.planx.pizza/testing/review-with-sections/preview
> fix: correctly display inline change links for services without sections

- infrastructure/application/index.ts
Please see https://docs.google.com/document/d/1jGUW7319B64Zr07qNDoUF4m-u2EuuM1_5yohEvwh33Q/edit for more context (internal OSL doc).
This PR sets the `X-Content-Type-Options` header to `nosniff` for out CloudFront CDN (our React app hosted on S3).
Pulumi docs - https://www.pulumi.com/registry/packages/aws/api-docs/cloudfront/responseheaderspolicy/#responseheaderspolicysecurityheadersconfig
AWS CloudFront Docs - https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/example-function-add-security-headers.html
We actually can't test this until we get to staging (the first AWS / Pulumi environment).
> fix: Set `X-Content-Type-Options` headers on CloudFront

- api.planx.uk/modules/auth/controller.ts
Set `httpOnly` attribute on JWT cookie to be true on all non-dev and non-Pizza environments
Flagged in Jumpsec report 2023, page 9.
Good question! I suspect that that the auth logic pre-dates Pizzas and so this environment isn't correctly accounted for - take a look at `handleSuccess()` in `api.planx.uk/modules/auth/controller.ts`.
I'm going to try to resolve this in other PR later today 👍 
This needs to be on staging for us to test it (see above).
> fix: Set `httpOnly` attribute on JWT cookie

- api.planx.uk/modules/send/uniform/uniform.ts
- e2e/tests/api-driven/src/invite-to-pay/mocks/server-mocks.yaml
We had a failed Southwark submission this morning and found out that there was a new release of the Submissions API Tuesday that changes the response shape of our authentication endpoint. 
This change addresses that update, and we'll figure out a process for more pro-active communication and documentation with Idox going forward.
Regression tests failing against this branch but passing locally, going to pick up fix outside of this PR: https://github.com/theopensystemslab/planx-new/actions/runs/7222293774
> fix: decode organisation details from `access_token` for Uniform authentication

- api.planx.uk/modules/auth/controller.ts
Reverts theopensystemslab/planx-new#2570
So this breaks login on staging...! (but does fix the issue - see screenshot)
Taking another look here, let's roll this back whilst I get to the bottom of it.
> Revert "fix: Set `httpOnly` attribute on JWT cookie"

- editor.planx.uk/src/pages/FlowEditor/lib/analyticsProvider.tsx
- hasura.planx.uk/metadata/functions.yaml
- hasura.planx.uk/metadata/tables.yaml
- hasura.planx.uk/migrations/1702897470388_alter_table_public_analytics_logs_add_column_node_id/down.sql
- hasura.planx.uk/migrations/1702897470388_alter_table_public_analytics_logs_add_column_node_id/up.sql
- hasura.planx.uk/migrations/1702899813258_update_view_analytics_summary_node_id/down.sql
- hasura.planx.uk/migrations/1702899813258_update_view_analytics_summary_node_id/up.sql
Changes:
- Alters table `analytics_logs` to add new column `node_id`, populates value on record creation
- Updates view `analytics_summary` to add new column `node_id`
> feat: add & populate column `analytics_logs.node_id`

- editor.planx.uk/src/pages/FlowEditor/lib/analyticsProvider.tsx
- Refactor for readability
- Refactor to make some of the analytics functions more abstract
- When creating an analytics session check the `currentCard` rather than relying on the `node`
- Refactoring to improve readability to lay ground work for changing the analytics logging strategy.
- Making the functions more abstract works towards decoupling the logic from the `node` which is checked on instantiation but can become out of sync. 
- Currently, when creating an analytics session we log the data of the root node.
- This is somewhat misleading and doesn't provide a great deal of context on the users journey. 
- Update to instead log the `currentCard` i.e. the node being shown to the user on resume, init etc.
What would currently be logged for a FOIYNPP on creating a new analytics …
> fix: log the viewed node rather than root node when creating new analytics session

- e2e/tests/ui-driven/.eslintrc
- e2e/tests/ui-driven/package.json
- e2e/tests/ui-driven/playwright.config.ts
- e2e/tests/ui-driven/pnpm-lock.yaml
- e2e/tests/ui-driven/src/globalHelpers.ts
- e2e/tests/ui-driven/src/login.spec.ts
- e2e/tests/ui-driven/src/save-and-return.spec.ts
A quick attempt to rule this out as a blocker on #2575 without creating additional noise 👌 
Regression tests passing on branch ✅
> chore(e2e): Update dependencies for Playwright tests

- editor.planx.uk/src/airbrake.ts
- editor.planx.uk/src/routes/utils.ts
Queuing this up now, but it needs to merge after #2582 & #2583. 
This covers step 10 in the how-to, and is the final code change.
> infra: add frontend values for Barnet's subdomain

- api.planx.uk/modules/send/bops/bops.ts
- e2e/tests/api-driven/src/invite-to-pay/helpers.ts
- Fixes failing regression test due to bug introduced in https://github.com/theopensystemslab/planx-new/pull/2581
- Relying on `NODE_ENV` over `APP_ENVIRONMENT`
Failing regression test now passing locally on this branch - 
🚀 Regression tests running against this branch here - https://github.com/theopensystemslab/planx-new/actions/runs/7275585116
> fix: Syntax issue in `SetupTeamIntegrationE2E` mutation

- editor.planx.uk/src/@planx/components/FileUploadAndLabel/Public.tsx
- editor.planx.uk/src/@planx/components/shared/Preview/QuestionHeader.tsx
The upload + label component sits in a full-width wrapper, when the file list is shown without the upload dropzone it inherits the full-width.
This PR introduces `formWidth` max-width wrappers to both the question header and file list.
**Preview (current):**
https://editor.planx.dev/testing/upload-label-file-list/preview?analytics=false
**Preview (fixed):**
https://2588.planx.pizza/testing/upload-label-file-list/preview?analytics=false
> fix: Form wrapper for upload + label

- doc/how-to/how-to-setup-planning-constraints.md
So anyone can hopefully pick up this new request ! https://trello.com/c/igzaovVx/2735-hook-up-barnets-article-4s
> docs: add how-to for enabling planning constraints and setting up granular A4 response

- api.planx.uk/server.ts
- Excludes AWS healthcheck logs
- Excludes local docker healthcheck logs
Been meaning to take a look at this small one for a while! 95%+ of the AWS logs are noise, just the healthchecker calling the API which makes troubleshooting locally or on the AWS console a more painful and slow experience.
> chore: Ignore AWS healthcheck from API logs

- editor.planx.uk/src/@planx/components/shared/Preview/Card.tsx
- editor.planx.uk/src/pages/FlowEditor/lib/analyticsProvider.tsx
- Update the approach to gathering analytics
- Differentiate between `auto` answered questions and those the user explicitly sees in approach but also in logs.
- Capture `auto` question when breadcrumbs change
- Capture logs for nodes users see when rendered by the `Card` component 
- Ensure that when a user interacts with a visible component the meta info is recorded against the visible node
- Previously when navigating between nodes if there were auto answered questions they may be logged but subsequently many duplicates of the visible node were added to the log. 
- This could result in logging info being inaccurate and not being representative of  the way the user navigates through a flow
- Now explicitly logging all auto answered questions but also differentiating them from those the …
> fix: rationalise analytics logs to remove duplication and inconsistencies

- api.planx.uk/modules/auth/controller.ts
- api.planx.uk/server.ts
- e2e/tests/ui-driven/src/create-flow/helpers.ts
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
- editor.planx.uk/src/index.tsx
- editor.planx.uk/src/pages/FlowEditor/lib/store/user.ts
- editor.planx.uk/src/routes/views/authenticated.tsx
- Adds the `httpOnly` flag to our auth cookie
- Corresponding changes to not descructure and read the cookie in the frontend
- Some refactoring of auth methods to make things a bit easier to follow
I'll move this diagram to a page in Notion as well, but this is a helpful diagram for making sense of the changes here - 
```mermaid
sequenceDiagram
participant Frontend as PlanX Editor
participant API as PlanX API
participant GoogleOAuth as Google OAuth
participant Hasura
Frontend ->> API: Initiate Login
activate API
API ->> GoogleOAuth: Proxy OAuth request
activate GoogleOAuth
GoogleOAuth ->> API: Redirect to callback URL
deactivate GoogleOAuth
API ->> API: Generate JWT
alt Staging/Production
API ->> Frontend: Return JWT in cookie
else Local Dev/Pizzas
API ->> Frontend: Return JWT in search …
```
> feat: Set `httpOnly` flag in cookie

- hasura.planx.uk/metadata/tables.yaml
Restore access for `platformAdmin` and `teamEditor` roles to `flow.data` column.
This is now redundant following https://github.com/theopensystemslab/planx-new/pull/2551 - we're handling sanitation via input validation so we don't need to restrict access here.
Introduced in https://github.com/theopensystemslab/planx-new/pull/2488 as an inital attempt at handling sanitation.
> chore: Restore permissions for `flow.data` column

- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- e2e/tests/api-driven/package.json
- e2e/tests/api-driven/pnpm-lock.yaml
- e2e/tests/ui-driven/package.json
- e2e/tests/ui-driven/pnpm-lock.yaml
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
- editor.planx.uk/src/components/Header.test.tsx
- editor.planx.uk/src/components/Header.tsx
- editor.planx.uk/src/routes/views/published.tsx
- editor.planx.uk/src/routes/views/standalone.tsx
- editor.planx.uk/src/routes/views/unpublished.tsx
- editor.planx.uk/src/types.ts
- hasura.planx.uk/metadata/tables.yaml
- hasura.planx.uk/migrations/1703240593405_squashed/down.sql
- hasura.planx.uk/migrations/1703240593405_squashed/up.sql
- hasura.planx.uk/tests/team_themes.test.js
- scripts/seed-database/write/teams.sql
- Moves `team.theme` JSONB to a new `team_themes` table
- Migrates data from column to table
- Updates frontend queries and types
Relies on https://github.com/theopensystemslab/planx-core/pull/242
> feat: Add `team_themes` table

- .github/workflows/push-main.yml
- .github/workflows/push-production.yml
Reverts theopensystemslab/planx-new#2621
This one is only triggered on deploys to `main` & `production`, so PR CI success isn't particularly meaningful. `pulumi up` step has failed twice - once before #2620 was merged & successfully deployed, and once after. https://github.com/theopensystemslab/planx-new/actions/runs/7383295642
> Revert "chore(deps): bump actions/download-artifact from 3 to 4"

- .github/workflows/push-main.yml
- .github/workflows/push-production.yml
Reverts theopensystemslab/planx-new#2623
Getting a little sidetracked by action failures here - but I think they're do to cache issues rather than v4 actually being faulty! This "revert revert" gets us back up v4.
> Revert "Revert "chore(deps): bump actions/download-artifact from 3 to 4""

- editor.planx.uk/src/components/Header.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Settings/index.tsx
- editor.planx.uk/src/routes/flow.tsx
- editor.planx.uk/src/routes/flowSettings.tsx
- editor.planx.uk/src/routes/team.tsx
- editor.planx.uk/src/routes/teamSettings.tsx
- editor.planx.uk/src/routes/utils.ts
- Makes the `Settings` component more generic, so it can be reused in different contexts
- Splits current tabs up across "Team Settings" and "Flow Settings"
- Just a UI change, nothing is wired up
https://github.com/theopensystemslab/planx-new/assets/20502206/3d4f6376-bc75-4115-82b3-adc7065518b1
> feat: Team settings page and routes

- editor.planx.uk/src/@planx/components/FileUploadAndLabel/Public.tsx
- editor.planx.uk/src/@planx/components/shared/Preview/QuestionHeader.tsx
- editor.planx.uk/src/theme.ts
- editor.planx.uk/src/themeOverrides.d.ts
After further user-testing, we are still seeing a reduction in clicks on the help text button. This PR simplifies the button setup by bringing it inline with the content, similar to how the GOV.UK system uses their Details component.
A new button variant `help` has been created to style help associated buttons.
Example:
https://2543.planx.pizza/lambeth/help-text-test/preview
> refactor: Simplify help text button

- api.planx.uk/helpers.ts
- api.planx.uk/modules/webhooks/service/validateInput/utils.test.ts
- api.planx.uk/modules/webhooks/service/validateInput/utils.ts
Originally picked up here - https://opensystemslab.slack.com/archives/C01E3AC0C03/p1703175603781519 (OSL Slack)
A permission error is thrown when attempting to copy some flows from the "Templates" team, despite the users in question having the requisite permission level.
The logged error is misleading, it's actually an [input validation](https://github.com/theopensystemslab/planx-new/pull/2551) error that's being thrown - the try/catch block just didn't account for this.
What's happening here is that the simple `length === length` check for DOMPurify is not accounting for HTML entities (see screenshot below).
There isn't a simple alternative way of checking that DOMPurify has modified content unfortunately. We can't check string equality directly as the order of HTML attributes in …
> fix: Unescape HTML entities for alternate DOMPurify check

- scripts/seed-database/container.sh
- scripts/seed-database/write/main.sql
- scripts/seed-database/write/team_themes.sql
- scripts/seed-database/write/teams.sql
- Syncs new `team_themes` table from production to staging and local dev environments
- Tested locally with `pnpm test-sync` script ✅ 
- Permissions manually granted on production database with `GRANT SELECT on team_themes TO github_actions;` - my understanding is that this isn't tracked anywhere currently and is just a manual process.
> chore: Update sync script for `team_themes` table

- scripts/seed-database/write/team_themes.sql
Quick fix-forward for https://github.com/theopensystemslab/planx-new/pull/2633!
Currently hitting [the following issue on CI](https://github.com/theopensystemslab/planx-new/commit/c9b7810ceab63f21ac1c9be6e54147ea1d93b6e4/checks) which I didn't hit locally - 
```bash
psql:write/team_themes.sql:37: ERROR:  duplicate key value violates unique constraint "team_themes_team_id_key"
DETAIL:  Key (team_id)=(15) already exists.
Database sync failed!
```
> fix: Handle duplicate `team_id` on re-sync

- api.planx.uk/modules/auth/controller.ts
- api.planx.uk/modules/user/controller.ts
- api.planx.uk/modules/user/docs.yaml
- api.planx.uk/server.ts
- e2e/tests/ui-driven/src/create-flow/helpers.ts
- e2e/tests/ui-driven/src/globalHelpers.ts
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
- editor.planx.uk/src/@planx/components/FileUploadAndLabel/Editor.test.tsx
- editor.planx.uk/src/api/upload.ts
- editor.planx.uk/src/client/index.ts
- editor.planx.uk/src/index.tsx
- editor.planx.uk/src/lib/graphql.ts
- editor.planx.uk/src/pages/FlowEditor/lib/store/editor.ts
- editor.planx.uk/src/pages/FlowEditor/lib/store/user.ts
- editor.planx.uk/src/routes/index.tsx
- editor.planx.uk/src/routes/views/authenticated.tsx
Merges PRs https://github.com/theopensystemslab/planx-new/pull/2591 and https://github.com/theopensystemslab/planx-new/pull/2595 which were previously reverted. These two PRs have had their commits cherry picked and have been previously reviewed.
Code from [`ecb270a`](https://github.com/theopensystemslab/planx-new/pull/2634/commits/ecb270a3e65990c098ea4aea043a7105a029133d) is new to this branch.
- Sets `httpOnly` flag in cookie (see https://github.com/theopensystemslab/planx-new/pull/2591)
- Adds additional `auth` cookie to detect presence of unreadable `httpOnly` cookie (see https://github.com/theopensystemslab/planx-new/pull/2595)
- Pass JWT from `user/me` endpoint and retains in `UserStore` - this is required to pass `JWT` to `planx-core` as well as to pass into auth headers.
- I can …
> feat: Set `httpOnly` flag in cookie, use cookie for auth

- api.planx.uk/modules/auth/controller.ts
Currently getting an issue setting the auth cookie on staging - please see screenshots below.
Login cannot be tested on the Pizza as this is pointing to the staging API for auth.
> fix: Add `secure` flag to auth cookie

- api.planx.uk/modules/auth/controller.ts
- editor.planx.uk/src/lib/graphql.ts
- editor.planx.uk/src/pages/FlowEditor/lib/store/user.ts
- editor.planx.uk/src/routes/authenticated.tsx
**Take 1**
~~This seems like the simplest solution here - to use the cookie for requests via Apollo directly, instead of trying to read it (which isn't possible as it's now `httpOnly`!)~~
~~My original idea was to wait for the JWT to be returned before making the failing query, but it's actually a bit more complex as the client is already instantiated by this point.~~
**Take 2**
So it turns out Hasura won't accept either a cookie or an auth header - is has to be one or the other. This would mean a number of changes to how we handle tests, and authenticate via scripts, or the API etc, so seems a non-starter. For reference - this setting can be controlled via the [`header`](https://hasura.io/docs/latest/auth/authentication/jwt/#header) JWT configuration option.
I've gone back to my initial …
> fix: Setup `authMiddleware` for Apollo

- editor.planx.uk/src/@planx/components/PropertyInformation/Public.tsx
- editor.planx.uk/src/@planx/components/Result/Public/ResultReason.tsx
- editor.planx.uk/src/@planx/components/Section/Public.tsx
- editor.planx.uk/src/@planx/components/shared/Preview/SummaryList.tsx
- editor.planx.uk/src/pages/FlowEditor/lib/analyticsProvider.tsx
- editor.planx.uk/src/pages/Preview/Questions.tsx
- More comprehensively track instances where a user makes a `change` 
- This is associated with `changeAnswer` being called
- On `overrideAnswer` track "change" click but leave the target node metadata as `{}`
- Track the the id of the target node
- Refactor to use the existing `extractNodeTitle` function to more comprehensively extract the title. 
- The metrics team have requested "change" clicks are tracked
- In the instance of `overrideAnswer` the logic is unlike `changeAnswer` and the basic requirement is tracking the "change" click not the target node. 
- When tracking target node data add the id as it can be helpful rather than relying on just the node title and type
- Also, in testing noticed that the node title was often undefined due to the limited way it was being extracted. …
> feat: track in analytics_logs instances where `changeAnswer` is called

- api.planx.uk/modules/send/bops/bops.ts
- api.planx.uk/modules/send/createSendEvents/controller.ts
Per dev call update that v2 API is available on BOPS production.
Satisfying PR will be the next one when we can retire this parallel approach and only submit via v2 :slightly_smiling_face:
> feat: create parallel BOPS send events for v1 & v2 on all environments

- editor.planx.uk/src/components/Header.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Settings/index.tsx
- editor.planx.uk/src/routes/flowSettings.tsx
- editor.planx.uk/src/routes/teamSettings.tsx
- editor.planx.uk/src/routes/utils.ts
Noticed this when working on another branch - not sure if it's an issue with Husky, but I suspect it's just from bumping eslint versions without running `pnpm lint:fix`. I'll check this out next time there's a version bump.
> chore: `pnpm lint:fix` in `editor.planx.uk`

- api.planx.uk/modules/pay/service/inviteToPay/createPaymentSendEvents.test.ts
- api.planx.uk/modules/send/bops/bops.test.ts
- api.planx.uk/modules/send/email/index.test.ts
- api.planx.uk/modules/send/uniform/uniform.test.ts
- api.planx.uk/modules/webhooks/service/analyzeSessions/index.test.ts
- api.planx.uk/modules/webhooks/service/lowcalSessionEvents/index.test.ts
- api.planx.uk/modules/webhooks/service/paymentRequestEvents/index.test.ts
- api.planx.uk/modules/webhooks/service/sanitiseApplicationData/index.test.ts
- api.planx.uk/modules/webhooks/service/sendNotification/index.test.ts
- api.planx.uk/modules/webhooks/service/validateInput/validateInput.test.ts
- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- e2e/tests/api-driven/package.json
- e2e/tests/api-driven/pnpm-lock.yaml
- e2e/tests/ui-driven/package.json
- e2e/tests/ui-driven/pnpm-lock.yaml
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
- hasura.planx.uk/package.json
- hasura.planx.uk/pnpm-lock.yaml
One PR to combine dependabot attempts - 
- https://github.com/theopensystemslab/planx-new/pull/2648
- https://github.com/theopensystemslab/planx-new/pull/2649
- https://github.com/theopensystemslab/planx-new/pull/2650
- https://github.com/theopensystemslab/planx-new/pull/2651
- https://github.com/theopensystemslab/planx-new/pull/2652
Where possible, I've just updated the package using `follow-directs`, in other places I've needed to `pnpm audit --fix`.
> chore: Update `follow-redirects` across project to resolve `CVE-2023-26159`

- editor.planx.uk/src/pages/FlowEditor/lib/analyticsProvider.tsx
- hasura.planx.uk/migrations/1704887727847_sql_migration_update_analytics_logs_metadata_to_use_text_node_type/down.sql
- hasura.planx.uk/migrations/1704887727847_sql_migration_update_analytics_logs_metadata_to_use_text_node_type/up.sql
- Update the way `back` and `change` events are tracked to store the node type as text rather than an integer for all new tracking events
- Add a migration to update historical records
- It can be difficult to understand the node type by their integer alone, using the text makes it more human readable
- I tried running the migrations via the Hasura console locally ensuring that the data updated in the correct way for both `up` and `down`
- Then ensured this worked using `hasura` cli to apply `up`/`down` migrations
> fix: for backwards tracking events update analytics_logs.metadata to use the text component type rather than integer for new and historical records

- editor.planx.uk/src/pages/FlowEditor/lib/analyticsProvider.tsx
- hasura.planx.uk/metadata/tables.yaml
- hasura.planx.uk/migrations/1704731606083_squashed/down.sql
- hasura.planx.uk/migrations/1704731606083_squashed/up.sql
- Track the `node_fn` in `analytics_log` table to tie together nodes and the passport variables they relate to
- Track `allow_list_answers` in `analytics` when a user directly answers a question
- Adding `node_fn` makes it easier to reason about how nodes can affect the passport. 
- Metrics requested the `allow_list_answers`
- This supersedes https://github.com/theopensystemslab/planx-new/pull/2487
> feat: track allow list answers

- editor.planx.uk/src/pages/FlowEditor/components/Settings/DesignSettings.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Settings/index.tsx
- editor.planx.uk/src/ui/editor/EditorRow.tsx
Builds UI for editor team design settings, currently hidden behind a feature flag.
Example:
https://2643.planx.pizza/barnet/settings/design
Feature flag to toggle design settings:
`window.featureFlags.toggle("SHOW_TEAM_SETTINGS")`
> wip: UI setup for team design settings

- editor.planx.uk/src/pages/FlowEditor/lib/analyticsProvider.tsx
- Fixes small logical bug introduced in https://github.com/theopensystemslab/planx-new/pull/2597
- `skipUpdateIfNotTracking()` does not correctly return from parent function
- I encountered an issue with this when the `ErrorWrapper` component was trying to write a log to the DB from within the Editor. You can test this by triggering an error state a "Send" node - https://editor.planx.dev/buckinghamshire/request-a-building-control-site-inspection/nodes/_root/nodes/9VzYz3damo/edit
> fix: Exit parent function on `shouldSkipTracking()`

- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- e2e/tests/api-driven/package.json
- e2e/tests/api-driven/pnpm-lock.yaml
- e2e/tests/ui-driven/package.json
- e2e/tests/ui-driven/pnpm-lock.yaml
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
- editor.planx.uk/src/components/Header.test.tsx
- editor.planx.uk/src/components/Header.tsx
- editor.planx.uk/src/pages/FlowEditor/lib/store/team.ts
- editor.planx.uk/src/pages/FlowEditor/lib/store/user.ts
- editor.planx.uk/src/pages/Teams.tsx
- editor.planx.uk/src/pages/layout/PublicLayout.tsx
- editor.planx.uk/src/routes/views/published.tsx
- editor.planx.uk/src/routes/views/standalone.tsx
- editor.planx.uk/src/routes/views/unpublished.tsx
- editor.planx.uk/src/theme.ts
- editor.planx.uk/src/themeOverrides.d.ts
- editor.planx.uk/src/types.ts
- editor.planx.uk/src/ui/public/ExternalPlanningSiteDialog.tsx
- editor.planx.uk/src/ui/shared/ReactMarkdownOrHtml.tsx
- hasura.planx.uk/metadata/tables.yaml
- hasura.planx.uk/migrations/1704892559414_alter_table_public_team_themes_add_column_link_colour/down.sql
- hasura.planx.uk/migrations/1704892559414_alter_table_public_team_themes_add_column_link_colour/up.sql
- scripts/seed-database/write/team_themes.sql
- Update `team_themes` table to include `action_colour` and `link_colour` columns, and drops `secondary_colour` column
- Pulls these new values into the MUI theme
- Imports `Team` and associated types from `planx-core`
- Depends upon https://github.com/theopensystemslab/planx-core/pull/259
- No style changes are made
- `link_colour` value in the database is set to the current default
- `color="prompt"` is not used anywhere yet so this value is not pulled in and used
- @ianjon3s is planning to pick up these changes (thank you!)
If you wish to do so, you can test this locally by updating colours for a team in Hasura and then see them get picked up in `/preview` and `/unpublished` routes. You'll need to set `color="prompt"` on a component (e.g. button) to see the `action_colour` feeding …
> feat: Access team secondary colour via MUI theme

- editor.planx.uk/src/@planx/components/Send/Editor.tsx
- editor.planx.uk/src/@planx/components/Send/model.ts
We've had a number of BOPS submission failures recently for services that shouldn't be attempting to send to BOPS in the first place because they're unsupported application types.
This makes two simple changes to the Send component: 
- Switches default "destination" from BOPS to email for all newly created Send components in the Editor
- Adds a simple window alert on selection of BOPS or Uniform if the flow slug isn't an obviously supported application type. This is just meant to be a quick deterent for now, and we'll revisit and think about more robust on-publish validation later this phase via [this Trello ticket](https://trello.com/c/LGIoRgym/2641-validate-that-flow-meets-schema-requirements-on-publish)
> fix: use email as default destination for new Send components and add warnings when selecting BOPS or Uniform

- scripts/seed-database/write/team_themes.sql
Tested locally with `pnpm test-sync` ✅
> chore: Sync new `team_themes` columns from production

- api.planx.uk/modules/webhooks/service/analyzeSessions/operations.ts
- editor.planx.uk/src/pages/FlowEditor/lib/analyticsProvider.tsx
Was wanting this while further reviewing title boundary feedback, feels useful to have in addition to `proposal.projectType` !
> feat: add `property.type` to analytics allow list answers

- editor.planx.uk/src/airbrake.ts
- editor.planx.uk/src/routes/utils.ts
- Sets up domain for Tewkesbury in frontend (Step 10 of https://github.com/theopensystemslab/planx-new/blob/main/doc/how-to/how-to-setup-custom-subdomains.md)
- Depends on Tewkesbury IT creating CNAME record. Will merge once I get confirmation from them.
> chore(editor): Setup Tewkesbury domain

- editor.planx.uk/src/@planx/components/Content/Public.tsx
- editor.planx.uk/src/@planx/components/FileUploadAndLabel/Modal.tsx
- editor.planx.uk/src/@planx/components/FileUploadAndLabel/Public.tsx
- editor.planx.uk/src/@planx/components/Notice/Public.tsx
- editor.planx.uk/src/@planx/components/shared/Preview/Card.tsx
- editor.planx.uk/src/@planx/components/shared/PrivateFileUpload/Dropzone.tsx
- editor.planx.uk/src/theme.ts
- editor.planx.uk/src/ui/public/NextStepsList.tsx
Applies new theme colours created in https://github.com/theopensystemslab/planx-new/pull/2646 across the components and UI of the app.
Notes:
- The content component is correctly selecting the appropriate colours for contrast link text (default: link colour, plus black or white depending on contrast), however I was not able to get this to function in the notice component due to overriding specificity set in the theme. This is also a current issue on the live services. For simplicity I've set the link text to inherit paragraph text colour in this component, and will revisit this in a future PR.
- As we are now using both dark and light button background colours, I've adjusted the tonal offset to 0.1, ensuring that darkening a light background colour on hover does not reduce it's contrast …
> feat: Apply theme colours across app

- e2e/tests/ui-driven/src/globalHelpers.ts
- editor.planx.uk/src/@planx/components/shared/Preview/MoreInfo.tsx
- editor.planx.uk/src/components/Feedback.tsx
- editor.planx.uk/src/components/FeedbackPhaseBanner.tsx
- editor.planx.uk/src/components/MoreInfoFeedback.tsx
- editor.planx.uk/src/components/PhaseBanner.tsx
- editor.planx.uk/src/lib/featureFlags.ts
- editor.planx.uk/src/pages/Preview/Questions.tsx
- editor.planx.uk/src/pages/layout/PublicLayout.tsx
- editor.planx.uk/src/theme.ts
- editor.planx.uk/src/ui/public/FeedbackDisclaimer.tsx
- editor.planx.uk/src/ui/public/FeedbackOption.tsx
- New UI components built by Ian as per [designs](https://www.figma.com/file/bnUUrsVRG6qPwDkTmVKACI/PlanX-Design?type=design&node-id=12766-9275&mode=design) and [prototype](https://www.figma.com/proto/bnUUrsVRG6qPwDkTmVKACI/PlanX-Design?page-id=12766%3A9275&type=design&node-id=13794-32506&viewport=-1569%2C471%2C0.7&t=hHNmEtfB7iz7Lk6T-1&scaling=min-zoom&starting-point-node-id=13794%3A32506&mode=design)
- Reorganisation of the components to allow them to be hidden behind a feature flag
- Useful to split up the PR for comprehensibility
- Demo service: https://2632.planx.pizza/testing/feedback-ui/preview
- Check that the UI defaults to current designs (barring background difference on Help Text)
- Toggle the feature flag: `window.featureFlags.toggle("SHOW_INTERNAL_FEEDBACK")`
- View the new …
> feat: UI setup for feedback component hidden behind feature flag

- api.planx.uk/modules/ordnanceSurvey/controller.ts
- api.planx.uk/modules/ordnanceSurvey/ordnanceSurvey.test.ts
- api.planx.uk/server.ts
- Fix OS proxy endpoints to allow correct list of origins defined in `MAP_ALLOWLIST`
- Pull this function out of the proxy, and place it into a middleware layer
**To test**
> fix: Handle CORS for OS proxy endpoints

- editor.planx.uk/public/index.html
- editor.planx.uk/src/pages/FlowEditor/components/Settings/DesignSettings/FaviconForm.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Settings/DesignSettings/index.tsx
- editor.planx.uk/src/pages/FlowEditor/lib/store/team.ts
- editor.planx.uk/src/ui/editor/ImgInput.tsx
- editor.planx.uk/src/ui/shared/PublicFileUploadButton.tsx
- Wires up Team Settings > Design Setting > Favicon
- Updates favicon in `/preview` and `/unpublished` routes if one is set in DB for team
**To test** 
- Standard "X" favicon still appears in Editor and for "unset" teams
- If I upload a favicon for a team and save, it displays in `/preview` and `/unpublished` routes 
- File type restrictions work
Demo: https://2680.planx.pizza/barking-and-dagenham/backup-dec23-article4-barkinganddagenham-manual-constraints/preview?analytics=false
> feat: Wire up favicon form

- editor.planx.uk/src/pages/FlowEditor/components/Settings/DesignSettings/ButtonForm.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Settings/DesignSettings/FaviconForm.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Settings/DesignSettings/TextLinkForm.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Settings/DesignSettings/ThemeAndLogoForm.tsx
- editor.planx.uk/src/ui/editor/ImgInput.tsx
- Small refactor mentioned here - https://github.com/theopensystemslab/planx-new/pull/2680#discussion_r1458791228
- Use `ImgInput` component instead of `PublicFileUploadButton`
- This allows us to remove images and view them, and is a little more consistent with how we handle images elsewhere in the Editor
- Restricts logo to SVG or PNG
> feat: Use `ImgInput` for logo upload

- editor.planx.uk/src/@planx/components/Content/Public.tsx
- editor.planx.uk/src/pages/FlowEditor/floweditor.scss
- editor.planx.uk/src/ui/editor/RichTextInput.tsx
- editor.planx.uk/src/ui/shared/InputRow.tsx
- editor.planx.uk/src/ui/shared/InputRowLabel.tsx
- Fixes noisy React warning (in dev-mode console, and tests) warning about use of `:first-child` selector
- Replaces with `:nth-child(1)` selector
> fix(css): Change `first-child` to `nth-child(1)`

- editor.planx.uk/src/ui/editor/RichTextInput.tsx
Please see https://opensystemslab.slack.com/archives/C04DZ1NBUMR/p1705661907092319 for context (OSL Slack)
This PR fixes the location of the rich text popover. A look through tiptap and tippy.js docs pointed at this solution which feels a little hacky but does the job!
https://github.com/theopensystemslab/planx-new/assets/20502206/6423b674-3619-4083-a6a0-c5683f1420f3
> feat: Freeze rich text popover

- editor.planx.uk/src/pages/FlowEditor/components/Settings/DesignSettings/ButtonForm.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Settings/DesignSettings/FaviconForm.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Settings/DesignSettings/TextLinkForm.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Settings/DesignSettings/ThemeAndLogoForm.tsx
Updates link provided in the design settings page to the correct guidance page on Notion.
https://opensystemslab.notion.site/10-Customise-the-appearance-of-your-services-3811fe9707534f6cbc0921fc44a2b193
This page has been updated to list instructions for button colour, text link colour and favicons. I shall be making a short guidance video to embed into this page.
> chore: Update link to council design guide [skip pizza]

- editor.planx.uk/pnpm-lock.yaml
- Deletes lockfile and node_modules, then reinstalled packages
- This recreates the lockfile with the pnpm overrides correctly installed
- https://github.com/theopensystemslab/planx-new/security/dependabot/59 reopened overnight
- Changes made in https://github.com/theopensystemslab/planx-new/pull/2653 reverted in Editor. Checked other projects which are all still fine, it's just the Editor which was affected.
- No quite sure how this regression was introduced but I've noticed a few times that `pnpm overrides` are a little flakey - node_modules and lockfile have to be dropped for an install of overrides to be successful
> chore: Recreate lockfile to install pnpm overrides (resolves `CVE-2023-26159`)

- editor.planx.uk/src/components/Header.tsx
- editor.planx.uk/src/routes/authenticated.tsx
- editor.planx.uk/src/routes/flowSettings.tsx
- editor.planx.uk/src/routes/teamSettings.tsx
- hasura.planx.uk/metadata/tables.yaml
- Visually hides "Team Settings" menu for users who do not have the `teamEditor` or `platformAdmin` roles
- Also handle "Global Settings" and "Flow Settings" displaying in the incorrect context
- Adds route guard for `<team>/settings`
- Also added a guard for `<team>/<flow>/settings` and `/global-setting` as these were previously missed
- Correctly sets up Hasura permissions for the `teamEditor` role
If we decide we want / need a `teamAdmin` role we can add one in future but this seems fine to me for the moment
**TeamEditor**
**Not TeamEditor**
> feat: Only show "Team Settings" menu for users with `teamEditor` role

- editor.planx.uk/src/components/Feedback.tsx
- editor.planx.uk/src/components/FeedbackPhaseBanner.tsx
- editor.planx.uk/src/components/MoreInfoFeedback.tsx
- editor.planx.uk/src/ui/public/FeedbackOption.tsx
- Based on [Figma prototype](https://www.figma.com/proto/bnUUrsVRG6qPwDkTmVKACI/PlanX-Design?page-id=12766%3A9275&type=design&node-id=13794-32506&viewport=-1569%2C471%2C0.7&t=hHNmEtfB7iz7Lk6T-1&scaling=min-zoom&starting-point-node-id=13794%3A32506) conditionally render the new UI components
- Add dummy form submission methods and basic inout validation
- Sets up the paths for users to provide feedback
- Discrete chunk of work which can be tested / reviewed 
- Testing link: https://2678.planx.pizza/testing/feedback-ui/unpublished
- As default no change to feedback banner
- As default no chance to the more info UI
- Toggle the feature `window.featureFlags.toggle("SHOW_INTERNAL_FEEDBACK")`
- Test the feedback banner behaviour works as per [Figma Prototype …
> feat: logic for conditionally rendering feedback UI

- api.planx.uk/modules/admin/session/html.ts
- api.planx.uk/modules/send/utils/exportZip.ts
- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- e2e/tests/api-driven/package.json
- e2e/tests/api-driven/pnpm-lock.yaml
- e2e/tests/ui-driven/package.json
- e2e/tests/ui-driven/pnpm-lock.yaml
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
- editor.planx.uk/src/@planx/components/FindProperty/Public/Map.tsx
- editor.planx.uk/src/@planx/components/shared/Preview/SummaryList.tsx
See https://github.com/theopensystemslab/planx-core/pull/269
Not a blocker to merging public-facing aspects of title boundaries to production, but we do want to make sure any maps displayed on document templates in submission zips have proper attribution sooner than later.
To test:
- This small test flow sends to email devops@ https://2696.planx.pizza/testing/document-templates-test/preview - check the inbox for a recent existing submission or send your own
- In this example, each document should have correct attribution & clearly communiate that the user "Accepted the title boundary" - for visual maps this means a source line below the map & double OS licenses, and for .geojson this means a custom key `properties.planx_user_action`
> chore: account for title boundaries in document templates

- editor.planx.uk/src/@planx/components/Checklist/Editor.tsx
- editor.planx.uk/src/@planx/components/Question/Editor.tsx
Previously August reported inconsistencies with how we require input for user-added fields in components.
The current behaviour for questions and checklists is that if an option is added and left blank it is deleted when the component is saved. The PR introduces required fields on user-added options for questions and checklists.
This brings it in line with the following components, which all require input on user-added fields:
- Next steps
- Upload + label
- Task list
- Confirmation (next steps)
> feat: Add required fields for question and checklist options

- api.planx.uk/modules/send/utils/exportZip.test.ts
- api.planx.uk/modules/send/utils/exportZip.ts
- api.planx.uk/tests/mocks/saveAndReturnMocks.ts
- Fixes bug with GeoJSON generation reported here - https://opendigitalplanning.slack.com/archives/C0241GWFG4B/p1706259470167559 (ODP Slack)
- Handles the `properties` of GeoJSON object being `null`
- Ensure unit tests pick up this logical branch by adding `drawBoundary.action` to mock data
> fix: Safely assign geojson properties

- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- e2e/tests/api-driven/package.json
- e2e/tests/api-driven/pnpm-lock.yaml
- e2e/tests/ui-driven/package.json
- e2e/tests/ui-driven/pnpm-lock.yaml
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
Resolves
- https://github.com/theopensystemslab/planx-new/security/dependabot/61
- https://github.com/theopensystemslab/planx-new/security/dependabot/62
- https://github.com/theopensystemslab/planx-new/security/dependabot/63
- https://github.com/theopensystemslab/planx-new/security/dependabot/64
> chore: Bump `planx-core` (fixes CVE-2020-8203)

- infrastructure/application/utils/generateTeamSecrets.ts
Assign the gov pay uk secret in every instance other than `goPayUkStagingOnly && env === "production"`
> fix: logical error with assigning gov pay secret

- editor.planx.uk/src/components/Header.tsx
Logical bug in the conditions to hide / show the menu settings introduced here - https://github.com/theopensystemslab/planx-new/pull/2693/files
Identified by @augustlindemer here - https://opensystemslab.slack.com/archives/C5Q59R3HB/p1706632533938589 (OSL Slack)
> fix: Conditions for settings visibility

- editor.planx.uk/src/ui/public/FeedbackOption.tsx
Flagged by @Mike-Heneghan here - https://github.com/theopensystemslab/planx-new/pull/2701
Should have spotted this one when working on https://github.com/theopensystemslab/planx-new/pull/2695
This error is being raised as the prop `Icon` is being passed to a MUI button. Docs: https://mui.com/system/styled/#api
> fix: Unrecognised 'Icon' prop passed to MUI button

- e2e/tests/api-driven/src/invite-to-pay/helpers.ts
- hasura.planx.uk/metadata/tables.yaml
Fixes failing regression tests from this morning - https://github.com/theopensystemslab/planx-new/actions/runs/7752056090
✅  Regression tests are passing on this branch - https://github.com/theopensystemslab/planx-new/actions/runs/7754684418
> fix(e2e): Update `setupMockBopsSubmissionUrl()`

- api.planx.uk/modules/gis/service/digitalLand.ts
- api.planx.uk/modules/gis/service/local_authorities/metadata/barkingAndDagenham.ts
Testing 
- From within B&G team on pizza, search an address in the Becontree estate area
- Proceed through constraints, confirm that if you've picked up a positive A4 intersection the granular A4 variables are set as expected (granular A4 variables will NOT be in passport if parent A4 intersection is false)
> feat: hook up granular Article 4 GIS variables for Barking & Dagenham

- editor.planx.uk/src/components/Feedback/MoreInfoFeedback.tsx
- editor.planx.uk/src/components/Feedback/index.tsx
Main Feedback:
- Add ref and useEffect to scroll down when it changes and isn't the "banner" or "thanks"
MoreInfo Feedback:
- Add ref and useEffect to scroll down when it changes is "input"
- When the currentFeedbackView changes the component can render partially off screen
- This might have a negative impact on accessibility / usability?
Before:
https://github.com/theopensystemslab/planx-new/assets/36415632/9ec4c454-b8c1-41e7-8bdd-adf20ae0e4bd
After:
https://github.com/theopensystemslab/planx-new/assets/36415632/bb9df931-e6c5-411f-9e38-eb9bd26cdbed
> feat: scroll to feedback view on view change

- infrastructure/application/Pulumi.production.yaml
- infrastructure/application/Pulumi.staging.yaml
I updated the key in the `.env` and tested on the Pizza, but never made the corresponding update on Pulumi for staging and prod envs (AWS).
> fix: Update Pulumi encryption keys

- api.planx.uk/modules/send/bops/bops.ts
- Contextualises errors thrown from BOPS send API endpoints by expanding `try/catch` blocks
- Context: https://opensystemslab.slack.com/archives/C4B0CKQ3U/p1706887476740319 (OSL Slack)
> chore: Improve send to BOPS error messages

- api.planx.uk/modules/send/docs.yaml
Quick docs issue I spotted whilst trying to submit something via the API.
> docs(api): Fix session param for `/create-send-events`

- editor.planx.uk/src/@planx/components/FileUploadAndLabel/Modal.tsx
- editor.planx.uk/src/@planx/components/FileUploadAndLabel/Public.tsx
- editor.planx.uk/src/@planx/components/shared/PrivateFileUpload/UploadedFileCard.tsx
- Adds option to remove file when modal is open
- Addresses feedback from recent UR
There's certainly scope here in these components to refactor and simplify some of the logic - there's a fair amount of prop drilling / shared state. 
As we're likely going to have to make changes here following the a11y audit I'm intentionally swerving this for now and we can always come back to pick this up!
> feat: Add remove file option to modal

- api.planx.uk/modules/gis/service/digitalLand.ts
From https://opensystemslab.slack.com/archives/C5Q59R3HB/p1706874436756669
**Testing**
Before (only sets `article4`): https://api.editor.planx.dev/gis/barking-and-dagenham?geom=POLYGON+%28%280.13405814766883314+51.55540648395743%2C+0.13406082987784804+51.555344779619105%2C+0.13432636857032218+51.555348948833796%2C+0.13436526060103812+51.55534144424706%2C+0.13438671827315724+51.555358121104746%2C+0.1341748237609809+51.55547152357477%2C+0.13407692313193736+51.55540648395743%2C+0.13405814766883314+51.55540648395743%29%29&analytics=false
After (correctly sets granular variables): https://api.2760.planx.pizza/gis/barking-and-dagenham?geom=POLYGON+%28%280.13405814766883314+51.55540648395743%2C+0.13406082987784804+51.555344779619105%2C+0.13432636857032218+51.555348948833796%2C+0.13436526060103812 …
> fix: correctly set granular Article 4 GIS keys for `barking-and-dagenham`

- hasura.planx.uk/metadata/tables.yaml
- hasura.planx.uk/migrations/1707234695689_create_view_feedback_summary/down.sql
- hasura.planx.uk/migrations/1707234695689_create_view_feedback_summary/up.sql
- Adds a new db view called `feedback_summary` which displays the `feedback` data enriched with data pulled out from the `user_data` column and enriched with data extracted from the associated `published_flow`
- To provide a more human readable summary of the `feedback` table enriched with `published_flow` data and with the pertinent `user_data` extracted.
- On the [pizza](https://2762.planx.pizza/) leave feedback on services: 
- Review the [feedback_summary](https://hasura.2762.planx.pizza/console/data/default/schema/public/views/feedback_summary/browse) and check the data extracted: 
- Where possible I've tried to give fallback `keys` for accessing things like the `node_title` but there might be more opportunities to account for situations where the node data is formatted differently
- …
> feat: add feedback_summary db view

- editor.planx.uk/src/components/Feedback/FeedbackPhaseBanner.tsx
Small one — something I missed when setting up the UI for our feedback component:
Makes the `feedback` link a button, so that it is included in the tabindex.
> feat: Feedback link as button

- editor.planx.uk/src/@planx/components/DrawBoundary/Public/Public.test.tsx
- editor.planx.uk/src/@planx/components/DrawBoundary/model.ts
- editor.planx.uk/src/@planx/components/Review/Public/mocks/fileUpload.tsx
- editor.planx.uk/src/@planx/components/Send/bops/__tests__/files.test.ts
This one isn't exposed as editor props, so it'll be live across services as soon as it's merged ! We'll coordinate merge with other file key changes.
Related to https://github.com/theopensystemslab/planx-core/pull/289 & https://github.com/theopensystemslab/planx-data-migrations/pull/7
BOPS logic is repeated in the editor's `Send` component still for frontend CSV generation - I'll take a look at properly refactoring using the planx-core public client today so we don't have to repeat the same find-and-replace across the v1 tagging functions.
> chore: update DrawBoundary upload key from `proposal.drawing.locationPlan` to `locationPlan`

- editor.planx.uk/src/@planx/components/FileUpload/Editor.tsx
- editor.planx.uk/src/@planx/components/FileUpload/FileUpload.stories.tsx
- editor.planx.uk/src/@planx/components/FileUpload/Public.test.tsx
- editor.planx.uk/src/@planx/components/FileUpload/Public.tsx
- editor.planx.uk/src/@planx/components/FileUploadAndLabel/Public.test.tsx
- editor.planx.uk/src/@planx/components/FileUploadAndLabel/model.ts
- editor.planx.uk/src/@planx/components/shared/utils.ts
- editor.planx.uk/src/pages/FlowEditor/lib/store/preview.ts
Prior art - https://github.com/theopensystemslab/planx-new/pull/2755
- Adds a new passport variable - `_requestedFile`
- Keeps this updated each time we pass through an Upload or UploadAndLabel component
To do 
- More test coverage
- Capture files uploaded via DrawBoundary
> feat: Add `_requestedFiles` key to Passport

- editor.planx.uk/src/@planx/components/Review/Public/mocks/fileUpload.tsx
- editor.planx.uk/src/@planx/components/shared/Preview/SummaryList.tsx
- Handles additional info in breadcrumbs for `FileUploadAndLabel` components added in #2763 when rendering `SummaryList` component
- Updates tests
> fix: Handle additional breadcrumb info in `SummaryList` component

- editor.planx.uk/src/@planx/components/DrawBoundary/Public/Public.test.tsx
- editor.planx.uk/src/@planx/components/DrawBoundary/Public/index.tsx
- editor.planx.uk/src/@planx/components/FileUploadAndLabel/Public.test.tsx
- Follow up to https://github.com/theopensystemslab/planx-new/pull/2763 which only handled `FileUpload` and `FileUploadAndLabel`
- Adds uploaded files to `_requestedFiles` in Passport
> feat: Capture `_requestedFiles` from `DrawBoundary` component

- api.planx.uk/helpers.test.ts
- api.planx.uk/helpers.ts
- api.planx.uk/modules/webhooks/service/sanitiseApplicationData/mocks/queries.ts
- api.planx.uk/modules/webhooks/service/sanitiseApplicationData/operations.test.ts
- api.planx.uk/modules/webhooks/service/sanitiseApplicationData/operations.ts
- hasura.planx.uk/metadata/tables.yaml
- hasura.planx.uk/tests/feedback.test.js
- Delete `feedback` records which were created before the retention policy date
- Rename `development` -> `local` for Slack warnings
- `feedback` can contain personally identifiable information so needs to be sanitised or deleted
- Records older than 28 days are likely to have little value and wou;d already have been downloaded and processed
- The `development` name is easy to conflate with `staging` i.e. our `.dev` environment
- Renaming to `Local` explicits shows there's been a failure running sanitisation based on local environment
Rename
- Added `feedback` records and manually changed the dates in the hasura console
- When cron job triggered the expected records were deleted successfully
> chore: remove feedback records which are beyond retention policy

- editor.planx.uk/src/@planx/components/DrawBoundary/Public/Public.test.tsx
- editor.planx.uk/src/@planx/components/DrawBoundary/Public/index.tsx
- editor.planx.uk/src/@planx/components/FileUpload/Public.tsx
- editor.planx.uk/src/@planx/components/FileUploadAndLabel/model.ts
- editor.planx.uk/src/pages/FlowEditor/lib/store/preview.ts
- Moves fetching, and returning default values, to a single shared store function
- Previous attempt in https://github.com/theopensystemslab/planx-new/commit/f74f9da68edbce7406260051b8eb297fb21722ae led mysteriously failing tests - see comment on code explaining how this is now fixed
> feat: Move `requestedFiles()` to store

- editor.planx.uk/src/@planx/components/Review/Public/Public.test.tsx
- editor.planx.uk/src/@planx/components/shared/Preview/SummaryList.tsx
- editor.planx.uk/src/components/ConfirmationDialog.tsx
- Moves "change" button back to per-question, not per-section
- Adds a MUI dialog to warn user of changes - please [see here](https://trello.com/c/Xap6HPg2/2654-on-the-result-page-move-change-button-to-be-by-the-section-rather-than-by-the-question-set-up-a-pop-up-warning-for-users-who-cli#comment-65c37821daecef2b370963a9) for context
- Basic test coverage for confirm modal behaviour
https://github.com/theopensystemslab/planx-new/assets/20502206/3aa288b0-3167-4152-90e6-864f854da6e5
> feat: Reposition change button, add dialog on change

- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- doc/how-to/how-to-setup-planning-constraints.md
- e2e/tests/api-driven/package.json
- e2e/tests/api-driven/pnpm-lock.yaml
- e2e/tests/ui-driven/package.json
- e2e/tests/ui-driven/pnpm-lock.yaml
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
- editor.planx.uk/src/@planx/components/PlanningConstraints/Public.tsx
- editor.planx.uk/src/components/Header.test.tsx
- editor.planx.uk/src/components/Header.tsx
- editor.planx.uk/src/pages/FlowEditor/lib/store/team.ts
- editor.planx.uk/src/routes/views/published.tsx
- editor.planx.uk/src/routes/views/standalone.tsx
- editor.planx.uk/src/routes/views/unpublished.tsx
- hasura.planx.uk/metadata/tables.yaml
- hasura.planx.uk/migrations/1707730766728_alter_table_public_team_integrations_add_column_has_planning_data/down.sql
- hasura.planx.uk/migrations/1707730766728_alter_table_public_team_integrations_add_column_has_planning_data/up.sql
- hasura.planx.uk/tests/team_integrations.test.js
- Creates new publicly queryable `team_integrations.has_planning_data` column
- Populates column with data from from `teams.settings-->"hasPlanningData"`
- Updates frontend to read from new location
- Note: `teams.settings-->"hasPlanningData"` value not removed / tidied up, we can maybe address this when we just stop the `team_settings` column?
On the Pizza, the following query can be made to get a list of all teams which have `has_planing_data` set to `true` - 
```sql
SELECT slug FROM teams
JOIN team_integrations
ON teams.id = team_integrations.team_id
WHERE has_planning_data
ORDER BY slug ASC;
```
This gives the following list which matches the previous value of the hardcoded [`digitalLandOrganisations`](https://github.com/theopensystemslab/planx-new/blame/a7065013d0a002c3a78e62577533ac9 …
> chore: Move `hasPlanningData` value to `team_integrations` table

- hasura.planx.uk/metadata/tables.yaml
- hasura.planx.uk/migrations/1707838555655_alter_table_public_team_integrations_add_column_staging_govpay_secret/down.sql
- hasura.planx.uk/migrations/1707838555655_alter_table_public_team_integrations_add_column_staging_govpay_secret/up.sql
- Follow on from https://github.com/theopensystemslab/planx-new/pull/2499 and https://github.com/theopensystemslab/planx-core/pull/212
- Adds columns for GovPay secrets to `team_integrations` table
- Does not read or use these secrets yet, this will be a follow on PR as the sequencing is a little tricky. Purposefully breaking this down into small atomic steps will hopefully make things a bit simpler.
- Populate columns with encrypted secrets (will be done once columns added to production)
- Update sync scripts to read new columns - https://github.com/theopensystemslab/planx-new/pull/2787
- Read and decrypt secrets using `planx-core`. PR here - https://github.com/theopensystemslab/planx-core/pull/303
- Remove env vars
- Work out how to inject secrets into e2e tests
> feat: Add GovPay columns to `team_integrations` table

- scripts/seed-database/container.sh
- scripts/seed-database/write/team_integrations.sql
~~Relies on #2786 - please see this PR for context. Should be merged to `main` once the above PR is merged to `production`, and secrets populated.~~
Tested locally multiple times with `pnpm test-sync` ✅ 
Encrypted values added to prod db ✅
> chore: Sync govpay secrets

- api.planx.uk/server.ts
Context https://opensystemslab.slack.com/archives/C4B0CKQ3U/p1707753609576929
Before:
After:
Forgot that Airbrake won't log on pizzas, let's merge to staging & see !
> fix: format Airbrake API errors for more readable Slack

- api.planx.uk/modules/auth/middleware.ts
- api.planx.uk/modules/file/routes.ts
Works on pizza and locally for me ✅ Will be sure to test on Staging and Prod also
- Example file - https://api.2793.planx.pizza/file/private/ktay5vj1/PXL_20230511_093922923.jpg
- Private file is inaccessible without key
- Private file is accessible with key
- Private file is then still inaccessible on subsequent requests
> fix: Add no-cache headers to file route

- api.planx.uk/server.ts
Reverts theopensystemslab/planx-new#2781
Looks like this is actually a bit worse, so reverting! This should have been a "Failed to send to BOPS" error equivalent to the original PR "before" screenshot:
> Revert "fix: format Airbrake API errors for more readable Slack"

- editor.planx.uk/src/@planx/components/PropertyInformation/Editor.tsx
> fix: Typo in `PropertyInformation` component [skip pizza]

- e2e/tests/ui-driven/src/create-flow/create-flow.spec.ts
- editor.planx.uk/src/lib/dataMergedHotfix.ts
- editor.planx.uk/src/pages/FlowEditor/components/PreviewBrowser.tsx
- editor.planx.uk/src/pages/FlowEditor/lib/store/editor.ts
- editor.planx.uk/src/routes/flow.tsx
- editor.planx.uk/src/routes/utils.ts
- editor.planx.uk/src/routes/views/published.tsx
- hasura.planx.uk/metadata/tables.yaml
Quick proof of concept to follow up on discussion point from yesterday about publishing flows. No strong feelings about when / how this proceeds - it might make sense to bundle a bunch of related "publish" changes together such as https://github.com/theopensystemslab/planx-new/pull/2783?
- Disable "preview" icon in Editor if flow is unpublished
- Throws a `NotFound` error on `/preview` routes for unpublished flows (no fallback to `dataMerged()` / "unpublished" version of the flow)
- If we go ahead with this it's probably worth improving this - not found for public, a meaningful message for logged in Editors maybe?
- A few type tidy ups 🧹
> feat: Disable `/preview` for unpublished flows

- api.planx.uk/modules/send/utils/helpers.ts
- api.planx.uk/modules/webhooks/service/validateInput/utils.ts
- Improves types on `reportError()` to better match what Airbrake expects ([docs](https://github.com/airbrake/airbrake-js/tree/master/packages/browser#notice-annotations))
- Quick fix as this error did contain the expected context  - https://opensystemslab.slack.com/archives/C4B0CKQ3U/p1707928622915259 (OSL Slack)
- A proper review of Airbrake logging should be picked up here with this ticket https://trello.com/c/TfmJiwID/2686-fix-airbrake-error-logging-on-api
> fix(types): Add better types to Airbrake logging

- editor.planx.uk/src/pages/layout/PublicLayout.tsx
I missed the significance of this change at review stage - apologies for that one @Mike-Heneghan 
Next steps (we can highlight at standup) would be to update privacy policy pages to drop FeedbackFish reference.
> fix: Restore flow privacy pages

- editor.planx.uk/src/pages/FlowEditor/lib/analyticsProvider.tsx
- hasura.planx.uk/migrations/1708016067772_alter_view_analytics_summary_unfold_metadata/down.sql
- hasura.planx.uk/migrations/1708016067772_alter_view_analytics_summary_unfold_metadata/up.sql
- Unwraps `user_agent` column into `platform`, `os`, and `browser`
- Unwraps metadata column into `change_metadata`, `back_metadata`, `help_metadata` and `selected_urls`
I'll cross check with @zz-hh-aa before we move this to production that this won't be a breaking change
> chore: Unwrap JSONB columns in `analytics_summary` view

- api.planx.uk/modules/send/utils/exportZip.test.ts
- api.planx.uk/modules/send/utils/exportZip.ts
- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- api.planx.uk/tests/mocks/saveAndReturnMocks.ts
- e2e/tests/api-driven/package.json
- e2e/tests/api-driven/pnpm-lock.yaml
- e2e/tests/ui-driven/package.json
- e2e/tests/ui-driven/pnpm-lock.yaml
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
Adds the ODP Schema JSON to the zip file for supported application types so that councils can build reports.
**Testing notes**
I've set up all flows under Lambeth on this pizza to email to `devops@opensystemslab.io`
1. You can submit an LDC successfully and the zip includes `application.json`: https://2804.planx.pizza/lambeth/apply-for-a-lawful-development-certificate/preview
- Double check the [Hasura events](https://hasura.2804.planx.pizza/console/events/one-off-scheduled-events/processed) to confirm that each send to email, BOPS, and Uniform submissions succeed
2. You can submit a discretionary service successfully (send to email only) and the zip does NOT include `application.json`: https://2804.planx.pizza/lambeth/send-to-email-test/preview
Related …
> feat: include the ODP schema as "application.json" in submission zips for supported application types

- editor.planx.uk/src/components/Feedback/FeedbackPhaseBanner.test.tsx
- Add tests for the FeedbackPhaseBanner component functionality and accessibility
- Improving test coverage
> test: FeedbackPhaseBanner component functionality and accessibility

- api.planx.uk/modules/gis/service/helpers.js
- api.planx.uk/modules/gis/service/local_authorities/metadata/base.ts
- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- e2e/tests/api-driven/package.json
- e2e/tests/api-driven/pnpm-lock.yaml
- e2e/tests/ui-driven/package.json
- e2e/tests/ui-driven/pnpm-lock.yaml
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
- `designated.SPA` &rarr; `nature.SPA`
- `designated.greenBelt` &rarr; `greenBelt` 
Based on feedback from Tewkesbury & thread here https://opensystemslab.slack.com/archives/C5Q59R3HB/p1709036570888579
Requires schema change before merging to production: https://github.com/theopensystemslab/digital-planning-data-schemas/pull/125 & https://github.com/theopensystemslab/planx-core/pull/316
> fix: rename SPA & Green Belt planning designations using ODP Schema v0.4.0

- editor.planx.uk/src/components/Feedback/FeedbackForm.stories.tsx
- The FeedbackForm assumes there's either multiple labelled inputs or one unlabelled input
- Demo these views as well as form submit
- Useful for testing accessibility and demoing functionality
> story: add FeedbackForm to storybook

- editor.planx.uk/src/components/Feedback/MoreInfoFeedback.stories.tsx
- editor.planx.uk/src/components/Feedback/index.stories.tsx
- Adds basic Storybook stories for remaining components
- Rather than explicitly defining the different states this requires users to click through component journeys
- Increasing coverage of components in the storybook component library
> story: add basic stories for feedback components

- api.planx.uk/helpers.ts
- api.planx.uk/tests/mocks/flattenPortals.ts
- editor.planx.uk/src/pages/FlowEditor/components/PreviewBrowser.tsx
Initially point to `main` to build fresh pizza for comparative testing, but will rebase this to point at `jess/fetch-published-portals-on-publish` before merging.
Context:
- The same portal can be referenced many times, but its' nodes only appear in the flattened flow data structure once 
- The same portal can be reference many times _at different levels_ 
- For example, tthere's a parent flow that references two nested flows A & B. Flow B also references flow A. 
- B can be published when A is at v1
- The parent flow can be published when A is at v2 and B is at v1 (which snapshot A v1). 
- In these cases, A v1 was captured in the flattened parent flow data, rather than forcing B to also consume the _latest_ published version of A (v2) which is a direct child of the parent flow …
> fix: if same portal is nested many times at different levels, ensure latest version is always flattened and not old snapshot

- api.planx.uk/pnpm-lock.yaml
- e2e/tests/api-driven/pnpm-lock.yaml
- e2e/tests/ui-driven/pnpm-lock.yaml
- editor.planx.uk/pnpm-lock.yaml
- scripts/encrypt/package.json
- scripts/encrypt/pnpm-lock.yaml
Addresses a number of related dependabot security issues, e.g. https://github.com/theopensystemslab/planx-new/security/dependabot/71
Regenerates lockfiles to bump `es5-ext` to 0.10.64
`pnpm audit` or `pnpm why ex5-ext` on projects now show there's no issues. Dependabot issues should also closed when this is merged.
> chore: Fix `CVE-2024-27088`

- editor.planx.uk/src/@planx/components/FindProperty/Editor.tsx
- editor.planx.uk/src/@planx/components/FindProperty/Public/index.tsx
- editor.planx.uk/src/@planx/components/FindProperty/model.ts
Per Doncaster feedback, see Trello ticket
New components only, not migrating existing content in this case
> chore: update default copy for FindProperty plot a new address 

- .env.example
- api.planx.uk/modules/saveAndReturn/service/resumeApplication.test.ts
- api.planx.uk/modules/saveAndReturn/service/utils.test.ts
- api.planx.uk/modules/saveAndReturn/service/utils.ts
- api.planx.uk/tests/mocks/digitalPlanningDataMocks.ts
- e2e/tests/ui-driven/src/create-flow/create-flow.spec.ts
- e2e/tests/ui-driven/src/globalHelpers.ts
- e2e/tests/ui-driven/src/invite-to-pay/agent.spec.ts
- e2e/tests/ui-driven/src/invite-to-pay/helpers.ts
- e2e/tests/ui-driven/src/pay.spec.ts
- e2e/tests/ui-driven/src/save-and-return.spec.ts
- e2e/tests/ui-driven/src/sections.spec.ts
- editor.planx.uk/src/components/Header.test.tsx
- editor.planx.uk/src/lib/graphql.ts
- editor.planx.uk/src/pages/FlowEditor/components/PreviewBrowser.tsx
- editor.planx.uk/src/pages/FlowEditor/index.tsx
- editor.planx.uk/src/pages/FlowEditor/lib/store/index.ts
- editor.planx.uk/src/pages/Pay/InviteToPay.tsx
- editor.planx.uk/src/routes/index.tsx
- editor.planx.uk/src/routes/pay.tsx
- editor.planx.uk/src/routes/utils.ts
Last big functional update for #2783 ! 
Will rebase this branch once pizza builds against main. Opening as separate PR for easier review - this touches a lot of files.
**Testing:** 
- CI tests and nightly regression tests passing against this branch :white_check_mark: 
- https://github.com/theopensystemslab/planx-new/actions/runs/8121796912
- Editor :globe_with_meridians: icon directly opens `/published` now (still disabled if flow is unpublished)
- Saving a session & inviting to pay generate magic links which have `/published` in the URL; you can resume successfully using those magic links
- After redirecting away to Gov Pay for any payment, you can redirect back to `/published` successfully
- `/preview` redirects to `/published` and **keeps query search params** like analytics, …
> feat: update and redirect `/preview` to `/published`

- editor.planx.uk/src/@planx/components/FileUploadAndLabel/Public.tsx
- editor.planx.uk/src/@planx/components/shared/Preview/QuestionHeader.tsx
- Addresses issue `DAC_Non-Text_Content_02` in the Accessibility Report (page 15)
- Removes the `alt` text in favour of `aria-describedby`
- Example of this on MDN docs here - https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/img_role#description
- The conditional logic around `howMeasured` ensures that the image is only displayed if there is an associated description, so it's already not possible to have an image without text.
> fix(a11y): Replace generic `alt` text with `aria-describedby`

- editor.planx.uk/src/components/Header.test.tsx
- editor.planx.uk/src/components/Header.tsx
Small change to make the user avatar more visible and useful — increases contrast and adds the second user initial to the avatar.
Before:
After:
> feat: Contrast and both initials for user avatar

- editor.planx.uk/src/@planx/components/Pay/Editor.tsx
- Addresses issue `DAC_Link_Purpose_Out_of_Context_01` in Accessibility Report (page 63)
- Updates default description for Pay component (content taken from template - this is consistent across services)
- Updated content of flow where this issue was flagged - https://editor.planx.uk/lambeth/accessibility-test
- Not yet published, will check on OSL Slack before proceeding
- Manually checked current submission services for out-of-date content, no issues found (will cross-check on OSL Slack)
> fix(a11y): Update default description in Pay component

- editor.planx.uk/src/@planx/components/shared/Preview/SummaryList.tsx
**Issue**
We have two component types - FindProperty & DrawBoundary - displayed on the review page where we can't rely on the node title or text to be a sensible row title in the descriptive list.
Previously, the row would display a static title but the visibly hidden change link still pointed at the node title - making it impossible to connect the change link to the correct row content.
Now, the change link consistently reflects the row titles. 
All nodes in "real" services should have titles (would be nice to enforce Editor validation consistently across component types here in future), so I'm also removing other static fallback titles for clarity as these would similarly fail a11y testing.
**Testing**
https://2868.planx.pizza/testing/review/unpublished
> fix(a11y): change links reference descriptive list titles whether dynamic or static

- editor.planx.uk/src/@planx/components/DateInput/Public.test.tsx
- editor.planx.uk/src/@planx/components/DateInput/model.test.ts
- editor.planx.uk/src/@planx/components/DateInput/model.ts
- Addresses issue `DAC_Vague_Error_Message_Usability_01` in Accessibility Report (page 73)
- Adds granular error messages for missing day, month, or year values
- Adds granular error messages for invalid day, month, or year values
- Adds tests for the above errors
- Splits existing DateInput tests into `Public.test.ts` (react-testing-library) and `model.test.ts` (jest)
https://github.com/theopensystemslab/planx-new/assets/20502206/e146bd53-59b2-4777-a60d-ac8be69ec68e
> chore(a11y): Improve granularity of `DateInput` errors

- editor.planx.uk/src/app.css
- editor.planx.uk/src/pages/FlowEditor/floweditor.scss
- editor.planx.uk/src/ui/shared/Input.tsx
- editor.planx.uk/src/ui/shared/InputRow.tsx
Requested by August and a general usability win:
The current formatting for data inputs differs from default inputs with only a slight background tint, meaning that data is often added to the component description in error.
This PR introduces a monospace font (CSS embed from Google Fonts), and a slightly different input style.
Before:
After:
Still to do (if possible):
> feat: Styling for editor data inputs

- hasura.planx.uk/metadata/tables.yaml
- hasura.planx.uk/migrations/1710258204814_alter_view_submission_services_summary_expand_application_data/down.sql
- hasura.planx.uk/migrations/1710258204814_alter_view_submission_services_summary_expand_application_data/up.sql
- Spun out of draft PR: https://github.com/theopensystemslab/planx-new/pull/2867
- Add `submission_services_summary` tracking
- Expand the application data exposed in the view 
- Adding columns: 
- `payment_request`
- `payment_status`
- `bops_applications`
- `uniform_applications`
- `email_applications`
- Each summarising related records as an array of objects with pertinent data
- As per: https://github.com/theopensystemslab/planx-new/pull/2867#discussion_r1516249772
- The `submission_services_summary` can be expanded to expose the requested data and isn't PII
- Council officers need to be able to connect the various ids, payments and submissions related to applications
> feat: expand the application data exposed on submission_services_summary

- doc/how-to/how-to-grant-metabase-permissions.md
- hasura.planx.uk/migrations/1709565833346_run_sql_migration/down.sql
- hasura.planx.uk/migrations/1709565833346_run_sql_migration/up.sql
- infrastructure/application/index.ts
- Sets up the `metabase_read_only` database role
- Ensures that Metabase can only read a small subset of tables and views, and has no write permissions
- Please see included doc file for more context and detail
I've gone ahead and set up the user and permissions outlined here on staging Metabase so that we can test a little (I'll revoke the changes before merging this PR).
It works as expected - for example, I can read `sessions_summary`, but running SQL to select from `lowcal_sessions` gives a permissions error.
> feat: Setup `metabase_read_only` role

- editor.planx.uk/src/pages/FlowEditor/lib/analyticsProvider.tsx
Follow up from https://github.com/theopensystemslab/planx-new/pull/2835 following comments from @Mike-Heneghan 
- Captures data from breadcrumbs (e.g. `drawBoundary.action`)
- Captures answers from breadcrumbs (e.g. `proposal.projectType`)
- Both values for `allow_list_answers` column will be in the format `[ {nodeFn} : answers ]`
- This matches `allow_list_answers` for session summary table
- This is required if any components could set multiple allow list values
- This is required where the `fn` field of the component won't match the variable used in the allow list (e.g. `drawBoundary.userAction` which is set automatically by the component)
- This might cause some issues with existing captures allow list answers - open to ideas and comments!
I'd love to get some tests written for …
> fix: Get allowlist answers from both breadcrumb data and answers

- api.planx.uk/modules/admin/session/html.test.ts
- editor.planx.uk/src/@planx/components/Confirmation/Public.tsx
- editor.planx.uk/src/@planx/components/PropertyInformation/Public.tsx
- editor.planx.uk/src/@planx/components/shared/Preview/SummaryList.tsx
The accessibility report identified an instance of an unstructured table (everything in <td>) on the Confirmation page of a service (p.46). The report suggested that we use <th> to add semantic structure to the table, however we can also achieve this using a Description List (`<dl>`), as we have done elsewhere.
Looking further into this I found three different uses of the same layout/pattern:
1. A Description List (`<dl>`) used for the Review page, as a styled component (SummaryList.tsx)
2. Another Description List with replicated styling from the above used for the Property Information page
3. An unstructured table with styling used for the Confirmation page (identified in the report)
Exporting the styling from the SummaryList component allows us to use this across each page as a …
> refactor: Unify summary list tables

- editor.planx.uk/src/pages/FlowEditor/components/Settings/DataManagerSettings.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Settings/ServiceFlags.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Settings/Submissions/index.tsx
- editor.planx.uk/src/routes/flowSettings.tsx
- Add a new placeholder component for a "Feature in development"
- Conditionally render this component as a flow settings tab based on the `SUBMISSION_VIEW` feature flag. 
- Adding development behind a feature flat allows the work to be shipped incrementally without being visible to user
- Setups the structure for adding a table for visualising application data
Tab rendered with feature flag enabled:
> feat: add tab for submissions view to flowSettings

- hasura.planx.uk/migrations/1710431558909_alter_view_public_submission_services_summary_reinstate_allow_list_answers/down.sql
- hasura.planx.uk/migrations/1710431558909_alter_view_public_submission_services_summary_reinstate_allow_list_answers/up.sql
- Reinstated `allow_list_answers`
- Add `GRANT SELECT` permission to `submission_services_summary` as per https://github.com/theopensystemslab/planx-new/blob/main/doc/how-to/how-to-grant-metabase-permissions.md#views
- Accidentally removed the `allow_list_answers` from the view by basing updates on an old version of the view
> fix: reinstate allow_list_answers on submission_services_summary view

- api.planx.uk/modules/pay/service/utils.test.ts
- api.planx.uk/modules/pay/service/utils.ts
- Mutes notifications on Slack triggered by test payments
- Requires as Gloucester use Stripe in GovPay
- Stripe does not have a specific test `payment_provider` code (Docs: https://docs.payments.service.gov.uk/testing_govuk_pay/#testing-recurring-payments-on-a-test-account)
- Context: https://opensystemslab.slack.com/archives/C0405SQDP8B/p1710433238647279 (OSL Slack)
> fix: Mute Stripe test notifications

- editor.planx.uk/package.json
- editor.planx.uk/src/@planx/components/Checklist/Editor.tsx
- editor.planx.uk/src/@planx/components/Pay/Editor.test.tsx
- editor.planx.uk/src/@planx/components/Pay/Editor.tsx
- editor.planx.uk/src/@planx/components/Pay/model.test.ts
- editor.planx.uk/src/@planx/components/Pay/model.ts
- editor.planx.uk/src/lib/featureFlags.ts
- editor.planx.uk/src/ui/editor/ListManager.tsx
- editor.planx.uk/src/ui/shared/Input.tsx
- Adds new GOV.UK Pay Metadata section in Pay component
- Adds form validation rules to match GOV.UK Pay requirements
Apologies - PR is much bigger than I'd like! A good chunk of it should just be tests though.
I'll pick up the API half of this in another PR 👍
> feat(editor): Dynamic GOV.UK Pay Metadata in `Pay` component

- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
Encountered this issue when working on #2878 - it happens when the Editor modal displays a form input field with a pre-populated HTML `anchor` element (such as the `Pay` component).
This is caused by this open issue in [tiptap](https://github.com/ueberdosis/tiptap) https://github.com/ueberdosis/tiptap/issues/2876
Reverting here is fine for now as we already sanitise user-submitted HTML on save 👍
> fix: Tiptap "Unknown CSS selector action any" error

- editor.planx.uk/src/@planx/components/shared/Preview/SummaryList.tsx
- editor.planx.uk/src/components/ConfirmationDialog.tsx
Updates text of confirmation dialog, as identified in UR.
Also updates styling of the confirmation dialog:
> refactor: Update confirmation dialog text and styling

- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
Something small I noticed when working on tests for #2878  - this package isn't required, and can cause issues if it resolves to a different version.
> If you use one of the [framework wrappers](https://testing-library.com/docs/dom-testing-library/install#wrappers), it is important that @testing-library/dom is resolved to the same installation required by the framework wrapper of your choice.
>
> Usually this means that if you use one of the framework wrappers, you should not add @testing-library/dom to your project dependencies. 
Source: https://testing-library.com/docs/user-event/install/
> chore: Drop redundant `@testing-library/dom` dependency

- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- e2e/tests/api-driven/package.json
- e2e/tests/api-driven/pnpm-lock.yaml
- e2e/tests/ui-driven/package.json
- e2e/tests/ui-driven/pnpm-lock.yaml
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
- hasura.planx.uk/package.json
- hasura.planx.uk/pnpm-lock.yaml
- Resolves a number of dependabot security issues
- Bumps libraries using `follow-redirects` where it's already patched (e.g. Axios), otherwise falls back to a pnpm override
> fix: CVE-2024-28849

- .github/workflows/pull-request.yml
- .github/workflows/regression-tests.yml
Please see https://opensystemslab.slack.com/archives/C01E3AC0C03/p1711359461634859 for context.
Looks like there's a few issues with the latest releases - https://www.npmjs.com/package/hasura-cli?activeTab=versions
Suggesting this as a temp fix for now, and I'll check in on it next few days. If it lasts any longer I'll open an issue in the `hasura-cli` repo.
> fix(temp): Pin `hasura-cli` version

- editor.planx.uk/src/pages/FlowEditor/components/Settings/Submissions/SubmissionView.stories.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Settings/Submissions/SubmissionsView.test.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Settings/Submissions/SubmissionsView.tsx
- Follow on from: https://github.com/theopensystemslab/planx-new/pull/2898
- Add the `SubmissionsTable` to the `SubmissionsView` to render it when there's submission data
- Add basic stories for component sates
- Add basic tests
- Incremental step towards feature
> feat: add SubmissionsTable to SubmissionsView

- editor.planx.uk/src/pages/FlowEditor/components/Settings/Submissions/index.stories.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Settings/Submissions/index.test.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Settings/Submissions/mocks.ts
- Add basic tests dependent on potential query results
- Add basic storybook stories based on query results
- Improve test coverage
- Add to component library on. storybook
> test: add test coverage for `index.tsx` as well as stories

- api.planx.uk/modules/pay/middleware.ts
- editor.planx.uk/src/@planx/components/Pay/Public/Pay.tsx
- Fixes an issue where existing, non-updated, Pay nodes were not handling default values correctly
- Alternatively, this could have been handled by a data migration but this seems a lighter-weight and quicker solution
> fix: Set up defaults for non-updated Pay components

- api.planx.uk/modules/send/bops/bops.test.ts
- api.planx.uk/modules/send/bops/bops.ts
Allows us to use Planning API for staging, and BOPS for production
See thread https://opensystemslab.slack.com/archives/C4B0CKQ3U/p1710431607298759
To test: update BOPS staging `team_integrations` values on this pizza to Planning API endpoint and test a submission. Will need to coordinate merge & deploy with prod db updates & syncs
> fix: store full BOPS endpoint in `team_integrations`, don't concat in API

- e2e/tests/api-driven/src/invite-to-pay/mocks/server-mocks.yaml
✅ Regression tests passing locally
✅ Regression tests passing on CI here - https://github.com/theopensystemslab/planx-new/actions/runs/8449763473
> fix: Update BOPS URL in E2E test

- api.planx.uk/modules/webhooks/service/analyzeSessions/operations.ts
- hasura.planx.uk/migrations/1711469716227_alter_view_public_submission_services_summary_split_allow_list_answers_into_columns/down.sql
- hasura.planx.uk/migrations/1711469716227_alter_view_public_submission_services_summary_split_allow_list_answers_into_columns/up.sql
- Split the `submission_services_summary` `allow_list_answers` into separate columns
- Allow Metabase seems to be unfolding some of the `ALLOW_LIST` answers it's not covering everything
- Splitting the `allow_list_answers` means we don't have to rely on the flakey unfolding
> feat: split submission_services_summary allow_list_answers into their own columns in view

- editor.planx.uk/src/pages/FlowEditor/lib/analyticsProvider.tsx
- hasura.planx.uk/migrations/1711457331702_alter_view_public_analytics_summary_split_allow_list_answers_into_columns/down.sql
- hasura.planx.uk/migrations/1711457331702_alter_view_public_analytics_summary_split_allow_list_answers_into_columns/up.sql
- Add separate columns for each of the possible `ALLOW_LIST` variables
- Add the `created_at` for the `analytics_log` rather than just the `created_at` for the `analytics` session
- It was found that the `allow_list_answers` with the new data structure was difficult to work with on Metabase
- Noticed that the `allow_list_answer` data structure is inconsistent i.e. `{key: value}` rather than `{key: [value]}` <img width="362" alt="Screenshot 2024-03-26 at 12 59 07" src="https://github.com/theopensystemslab/planx-new/assets/36415632/5b74421e-8264-40f1-ad2e-0c7e983aa16f">
- Noticed that the `null` values are no longer being filtered out: https://github.com/theopensystemslab/planx-new/blob/612fa877f30818b4d22c98df3e3b44158bdfa095/editor.planx.uk/src/pages/FlowEditor/lib/analyticsProvider.tsx#L4 …
> feat: split allow_list_answers column in analytics_summary view

- editor.planx.uk/src/theme.ts
- Use [darken colour tool](https://mdigi.tools/darken-color/#bdbdbd) to find a shade of #BDBDBD which meet 1.99 contrast ratio 
- 5% darker achieves a ratio of 2.07 - see https://color.a11y.com/ContrastPair/?bgcolor=ffffff&fgcolor=000042
- It looks like jest-axe and jsdom can't automatically contrast ratio, so we can't automatically test for this - https://github.com/dequelabs/axe-core/issues/4021
- The MUI palette has a default contrast threshold of 3:1, but it looks like this just applies to text ([docs](https://mui.com/material-ui/customization/palette/#contrast-threshold))
> fix(a11y): Darken disabled colour in MUI theme

- hasura.planx.uk/migrations/1711637066987_alter_table_public_analytics_logs_default_allow_list_answers_to_null/down.sql
- hasura.planx.uk/migrations/1711637066987_alter_table_public_analytics_logs_default_allow_list_answers_to_null/up.sql
- Default `analytics_logs` `allow_list_answers` to `null`
- Update existing empty arrays to `null`
- In Metabase the empty areas were found to be challenging to filter out
- Initially intended to allow do this for `metadata` and `input_errors` as per the ticket although due to the mutation using `_append` and the nature of those tracking events it wasn't practical to do.
> chore: default analytics_logs allow_list_answers to null

- editor.planx.uk/src/@planx/components/Result/Public/ResultReason.tsx
- Restructure DOM so the order of elements is correct (move change button to come "after" accordion)
- Use `useRef()` and `useLayoutEffect()` hooks to maintain consistent style - change button remains in same location
https://github.com/theopensystemslab/planx-new/assets/20502206/0e18e26a-9bbd-4b1e-a2e7-e481bf74c740
🧪 Test flow: https://2941.planx.pizza/testing/result-tab-index-order/amber
There were a few lines controlling the logic around `expanded` and `onChange` which are redundant - the MUI accordion has this as the default behaviour anyway, so I've removed this.
> fix(a11y): `ResultReason` tabindex order

- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- e2e/tests/api-driven/package.json
- e2e/tests/api-driven/pnpm-lock.yaml
- e2e/tests/ui-driven/package.json
- e2e/tests/ui-driven/pnpm-lock.yaml
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
- editor.planx.uk/src/@planx/components/DrawBoundary/Public/index.tsx
- editor.planx.uk/src/@planx/components/FindProperty/Public/Map.tsx
- editor.planx.uk/src/@planx/components/PropertyInformation/Public.tsx
- editor.planx.uk/src/@planx/components/shared/Preview/SummaryList.tsx
**From page 61:**
> Content is lost when resizing the webpage to a smaller viewing dimension. This instance can 
be found with the site boundary section of the definition list. The map feature has been 
resized however the tooltip provided is covering the user from identifying the boundary of 
the location. This issue affects low vision users who are likely to require a smaller window to 
progress through the journey as content is affected. 
Additionally, due to the change links being covered on the side of the window, part of the 
focus highlight is obscured. 
**Changes:**
- Openlayers map attributions are collapsed on screens less than 500px
- Review page `SummaryList` 3-column layout is collapsed to single column on screens less than 500px ("small" MUI breakpoint), consistent with …
> fix(a11y): collapse map attributions and wrap SummaryList columns on small screens

- editor.planx.uk/src/components/Header.tsx
- Adds a visually hidden description to the "Restart application" button
I'd dispute this is really totally necessary as our current markdown matches [the suggestion on MDN perfectly](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label) (`<button>` with `aria-label` wrapping an `<svg>` with `aria-hidden=true`), and clicking the button opens a dialog with more details. However, it's an easy fix to just add an additional description element here.
> fix(a11y): Add visually hidden context to "Restart Application" button

- editor.planx.uk/src/components/Feedback/FeedbackForm.stories.tsx
- editor.planx.uk/src/components/Feedback/FeedbackForm.test.tsx
- editor.planx.uk/src/components/Feedback/FeedbackForm.tsx
- editor.planx.uk/src/components/Feedback/MoreInfoFeedback.tsx
- editor.planx.uk/src/components/Feedback/index.tsx
- Address accessibility report issue "Label and Accessible Name" (page 43)
- Adds a label to each input used in the feedback from instead of conditionally relying on the title for this
This approach is very much up for discussion, I've hopefully explained my thought process below.
> A text area was found to have an accessible name that does not match the one that is provided visually. This can be found across the service; however, this instance relates to the text area below the ‘please help us to improve the service by sharing feedback’. The visual label has not been programmatically associated with the related text area, and so the information presented visually is not relayed to screen reader users navigating out of context.
```jsx
<textarea 
aria-describedby="comment-title" …
```
> fix(a11y): Add labels to all feedback form inputs

- editor.planx.uk/src/@planx/components/PlanningConstraints/List.tsx
- editor.planx.uk/src/@planx/components/Result/Public/ResultReason.tsx
- editor.planx.uk/src/theme.ts
- Replaces the combination of `Button` and `Collapse` components with an `Accordion` component
- Moves some Accordion theming to the MUI theme so that there's more consistency with our other accordions (currently just `ResultReason`)
- No intentional visual changes
- Apart from one! 
- The colour for the Caret and hover is now fixed and not based on primary colour - I wasn't sure if this was intentional in the first place, or a hangover from using a `Button`.
- If you could take a look at this one please @ianjon3s and confirm that would be much appreciated! 🙌 
| | Before | After |
| **Screenshot** | <img width="721" alt="image" src="https://github.com/theopensystemslab/planx-new/assets/20502206/fce37f6c-00a7-487e-949d-3dfe81b317a2">|<img width="703" …
> fix(a11y): Replace `Collapse` and `Button` with `Accordion` components in `PlanningConstraints`

- editor.planx.uk/.eslintrc
- editor.planx.uk/src/pages/FlowEditor/lib/analyticsProvider.tsx
- editor.planx.uk/src/pages/FlowEditor/lib/store/preview.ts
- editor.planx.uk/src/pages/Preview/Node.tsx
- editor.planx.uk/src/routes/utils.ts
Fixes https://eslint.org/docs/latest/rules/no-case-declarations by just wrapping the cases in `{}` as suggested.
Also removes a few unused imports 🗑️
> chore: Fix eslint rule "no-case-declarations"

- editor.planx.uk/src/@planx/components/DateInput/Public.test.tsx
- editor.planx.uk/src/@planx/components/TextInput/Public.test.tsx
- editor.planx.uk/src/ui/shared/ErrorWrapper.tsx
- Adds an optional `role` property to the `ErrorWrapper` component, defaulting to `"alert"`
- (I believe) `ErrorWrapper` is only currently used for input feedback errors, but I've allowed "status" to be a valid role prop if there are exceptions in future
- Recommended several times throughout accessibility report (pages [40](https://trello.com/c/4rqZjL5Q/2813-error-identification-for-uploadlabel-a) & [53](https://trello.com/c/THkjn5rm/2818-status-messages-aa))
- MDN docs show that "alert" is correct for form feedback - https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/alert_role
> The alert role is used to communicate an important and usually time-sensitive message to the user. When this role is added to an element, the browser will send out an accessible alert event …
> fix(a11y): Use `role="alert"` as default value for `ErrorWrapper`

- editor.planx.uk/src/pages/FlowEditor/lib/analyticsProvider.tsx
- hasura.planx.uk/metadata/tables.yaml
- hasura.planx.uk/migrations/1711643574155_update_analytics_logs_allow_list_answers_array_to_object/down.sql
- hasura.planx.uk/migrations/1711643574155_update_analytics_logs_allow_list_answers_array_to_object/up.sql
- hasura.planx.uk/migrations/1711645589762_alter_table_public_analytics_logs_drop_column_node_fn/down.sql
- hasura.planx.uk/migrations/1711645589762_alter_table_public_analytics_logs_drop_column_node_fn/up.sql
- Store `allow_list_answers` as an object
- Update `getAnswers` to filter out `null` `answerValues` to avoid storing `null` values: https://metabase.editor.planx.uk/question/353-null-allow-list-values
- Update historical records to move form array of object to an object:
- The SQL for handling an array greater than 1 was very challenging
- Realised that although it's theoretically possible to have `allow_list_answers` > 1 none of our ALLOW_LIST actually gets set by the same node: https://metabase.editor.planx.uk/question/354-number-of-analytics-logs-with-allow-list-answers-greater-than-1
- This allows us to use the more naive approach here:  5d2cec68f179e635b5b194d6817b579616270eaf
- Update `analytics_summary` to handle the change in data structure of `allow_list_answers`
- Remove …
> refactor: store analytics_logs allow_list_answers from arrays of objects to object

- editor.planx.uk/src/pages/FlowEditor/components/Settings/DataManagerSettings.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Settings/DesignSettings/index.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Settings/ServiceFlags.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Settings/ServiceSettings.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Settings/Submissions/SubmissionsTable.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Settings/Submissions/index.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Settings/TeamSettings.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Settings/index.tsx
Adds a basic level of styling to the submissions log table:
- Page containers adjusted to allow full width or 'form' width containers.
- Table given max-height to allow for sticky headers — this is a quirk with HTML tables in that they cannot have sticky headers and horizontal overflow scroll without an explicit height or max-height being set.
- Other settings pages updated to use same `<EditorRow>` component for consistency.
There is no data in the pizza environment but the table can be previewed on Storybook (thanks for @Mike-Heneghan for putting together the stories for this!):
https://storybook.2975.planx.pizza/?path=/docs/design-system-molecules-submissions--docs
Note: Storybook does squash up the columns somewhat, it'll be a lot more readable in the editor.
(currently behind a …
> feat: Styling for submissions table

- editor.planx.uk/src/lib/featureFlags.ts
- editor.planx.uk/src/pages/FlowEditor/components/Settings/index.tsx
- editor.planx.uk/src/routes/flowSettings.tsx
- Drop feature flag to create Pizza for UAT
- Some type tidy ups
In this instance we’re better off removing the feature flag and encouraging PO testing on production as - 
- there’s real submission data there to test against
- it’s a pretty unobtrusive feature - if it needs changes we can easily do this without effecting anything else
> chore: Drop `SUBMISSION_VIEW` feature flag

- editor.planx.uk/src/airbrake.ts
- editor.planx.uk/src/routes/utils.ts
Currently awaiting a response from Gateshead's IT team to confirm they've set up a CNAME record. This PR can sit as a draft until I get that confirmation.
Remaining tasks (steps 10, 11, 12 from [docs](https://github.com/theopensystemslab/planx-new/blob/main/doc/how-to/how-to-setup-custom-subdomains.md))
> chore: Finalise Gateshead subdomain

- e2e/tests/ui-driven/src/create-flow/create-flow.spec.ts
- editor.planx.uk/src/@planx/components/shared/Preview/MoreInfo.tsx
- editor.planx.uk/src/pages/Preview/Questions.tsx
- editor.planx.uk/src/pages/Preview/ResumePage.tsx
- editor.planx.uk/src/pages/Preview/SaveAndReturn.tsx
- editor.planx.uk/src/pages/layout/PublicLayout.tsx
- Move back component out of `#main` element (report page 91 - [Trello ticket](https://trello.com/c/C0e3PdIu/2835-back-button-positioning-usability))
- Ensure we only use a single `#main` element (report page 82 - [Trello ticket](https://trello.com/c/ksGgKnK7/2830-multiple-main-roles-usability?search_id=23e5b034-13a3-424f-9c07-fd0dbf48fbb6))
- Use `<main>` element instead of `<div role="main">` - not in report just something I spotted. From MDN docs - 
> Prefer using the `<main>` element over declaring role="main", unless there are [legacy browser support concerns](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/main#browser_compatibility).
> feat: Move back button out of main component, ensure single main component only

- editor.planx.uk/src/@planx/components/Checklist/Public.tsx
- editor.planx.uk/src/@planx/components/Question/Public/Question.tsx
- editor.planx.uk/src/components/Feedback/MoreInfoFeedback.tsx
- Adds `<fieldset>` and `<legend>` elements for input groupings
- Applies to Checklist and Question components, and Yes/No feedback buttons in help text feedback.
Identified in the accessibility report pages 21–26:
`Checkboxes relating to one another have not been grouped programmatically.`
`Ensure that the legend is the first element instantiated within the fieldset to make sure that
no sporadic results occur for users of screen reading assistive technologies.`
`Buttons relating to a question have not been grouped within a fieldset.`
https://2976.planx.pizza/testing/input-grouping/published
> fix(a11y): Input grouping, fieldset and legend

- editor.planx.uk/src/@planx/components/DrawBoundary/Public/index.tsx
Now determines the basemap clip buffer based on the area of the site, meaning we don't unnecessarily expose more vector tiles to regular householder applicants.
Ticket only has one example address (5 Pancras Square, N1C 4AG) which is now fully in view if viewing the default title boundary:
> fix: allow larger basemap buffer for large sites

- editor.planx.uk/src/pages/FlowEditor/lib/analyticsMutations.ts
- editor.planx.uk/src/pages/FlowEditor/lib/analyticsProvider.tsx
- Move the `mutations` in the `analyticsProvider.tsx` into their own file
- The `analyticsProvider` file is complex
- Separating concerns reduces the lines and should hopefully make reading the files easier
> refactor: move analytics mutations into their own file

- editor.planx.uk/src/pages/Preview/ResumePage.tsx
- editor.planx.uk/src/pages/Preview/SavePage.tsx
- Removes "Close tab" option 
- Replaces with a message ("You may now close this tab") and makes "Start a new application" the primary action
- Reported as a bug, does not work in Firefox and Edge
- It turns out `window.close()` is not allowed by these browsers - https://caniuse.com/mdn-api_window_close
> chore: Remove close tab option

- editor.planx.uk/src/@planx/components/FileUploadAndLabel/Public.tsx
- editor.planx.uk/src/@planx/components/Notice/Public.tsx
- editor.planx.uk/src/@planx/components/PropertyInformation/Public.tsx
- editor.planx.uk/src/@planx/components/Result/Public/ResultReason.tsx
- editor.planx.uk/src/@planx/components/Section/Public.tsx
- editor.planx.uk/src/@planx/components/shared/Preview/QuestionHeader.tsx
- editor.planx.uk/src/@planx/components/shared/Preview/SaveResumeButton.tsx
- editor.planx.uk/src/@planx/components/shared/Preview/SummaryList.tsx
- editor.planx.uk/src/components/Header.tsx
- editor.planx.uk/src/pages/FlowEditor/lib/analyticsProvider.tsx
- editor.planx.uk/src/pages/Preview/Questions.tsx
- editor.planx.uk/src/ui/public/NextStepsList.tsx
- editor.planx.uk/src/ui/shared/ErrorWrapper.tsx
- As per: https://github.com/theopensystemslab/planx-new/pull/2597#discussion_r1448669108
- Consolidating individual tracking event functions into a single function with a case statement
- Step towards clearer organisation and documentation of analyticsProvider
- Should hopefully be a clearer pattern for adding tracking of new events
> refactor: create trackEvent function and apply updates in relevant files

- editor.planx.uk/src/theme.ts
- editor.planx.uk/src/themeOverrides.d.ts
- editor.planx.uk/src/ui/editor/RichTextInput.tsx
- editor.planx.uk/src/ui/shared/Input.tsx
- Addresses colour contrast issues highlighted by accessibility testing (pages 48–50).
- Introduces a new 'dark' success colour that adequately contrast with 'light' success.
- Introduces a dedicated colour for placeholder text that uses a solid opacity, rather than relying on a opacity reduction of a current colour (easier to test, not as dependent on background). This has also been applied to inputs and textareas in the editor.
To pass at AA level the contrast ratio of small text should be at least 4.5 : 1.
Three groups of contrast issues were highlighted in the report:
READY TO START:
**Tested colours:**
Background: #e5f1eb
Text: #409444
Contrast Ratio: **3.27 : 1**
**Updated colours:**
Background: #e5f1eb
Text: #265A26 (new success dark colour)
Contrast Ratio: **7.04 : 1**
This also …
> fix(a11y): Colour contrast issues

- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
Resolves control button focus color contrast & tab-order issues
> chore: bump @opensystemslab/map to v0.8.1 for a11y fixes

- editor.planx.uk/src/components/Feedback/MoreInfoFeedback.tsx
- editor.planx.uk/src/pages/FlowEditor/lib/analytics/provider.tsx
- editor.planx.uk/src/pages/FlowEditor/lib/analytics/types.ts
- hasura.planx.uk/migrations/1712323679734_alter_view_public_analytics_summary_unfold_metadata_help_text_useful/down.sql
- hasura.planx.uk/migrations/1712323679734_alter_view_public_analytics_summary_unfold_metadata_help_text_useful/up.sql
- Track when a user provides feedback on the helpfulness of help text
- Update the `analytics_summary` to expose this new metadata in it's own column
- Although we record feedback on help text it's necessary for user to explicitly leave a comment and it's not accessible in the `analytics_logs`
- Tracking "yes" / "no" clicks via analytics give us a higher level view of whether users are finding help text useful with a lower barrier
> feat: track feedback on help text usefulness

- editor.planx.uk/src/pages/Preview/ResumePage.tsx
- editor.planx.uk/src/pages/Preview/SaveAndReturn.tsx
- editor.planx.uk/src/pages/layout/SaveAndReturnLayout.tsx
- editor.planx.uk/src/routes/views/standalone.tsx
- Moves the `main` element as high up the component tree as we can, to ensure all views are wrapped
- We've had to recently move this "down" so as to not wrap the "back" button for accessibility reasons, hence the need to repeat this a few places
✅  Regression tests passing against this branch here - https://github.com/theopensystemslab/planx-new/actions/runs/8595892001
> fix: Hoist `main` element higher up DOM tree

- editor.planx.uk/src/@planx/components/PlanningConstraints/Editor.tsx
- editor.planx.uk/src/@planx/components/PlanningConstraints/Public.tsx
- editor.planx.uk/src/@planx/components/PlanningConstraints/model.ts
Per request from Doncaster, followup from #2891 
**Now:**
> fix: update PlanningConstraints disclaimer to suppot rich text formatting

- editor.planx.uk/src/@planx/components/Result/Public/ResultReason.tsx
- editor.planx.uk/src/components/Header.tsx
- editor.planx.uk/src/theme.ts
- editor.planx.uk/src/ui/editor/SelectInput.tsx
Small tidy up / refactor I hit when working on https://github.com/theopensystemslab/planx-new/pull/2993
MUI offers classnames as an import so we can avoid hardcoding these 👍
> chore: Tidy up hardcoded MUI classnames

- editor.planx.uk/src/@planx/components/Send/Editor.tsx
- editor.planx.uk/src/@planx/components/Send/Public.tsx
- editor.planx.uk/src/@planx/components/Send/model.ts
Editor-side changes for the Barnet prototype described in linked Trello ticket. API changes to follow in a separate PR
> feat: add AWS S3 bucket as "Send" destination for staging envs only

- e2e/tests/ui-driven/src/globalHelpers.ts
- e2e/tests/ui-driven/src/pay.spec.ts
Most recent regression test are failing - https://github.com/theopensystemslab/planx-new/actions/runs/8642231150 ❌ 
Tests passing on this branch - https://github.com/theopensystemslab/planx-new/actions/runs/8643303652 ✅ 
It looks like this is due to GovPay changing their payment journeys - card details need to be re-entered.
> chore(e2e): Update e2e tests to match GovPay journey

- infrastructure/application/Pulumi.production.yaml
- infrastructure/application/Pulumi.staging.yaml
Hasura console access is restricted via Zero Trust, but rotation ensures an offboarded dev couldn't connect to a GraphQL client directly.
Additionally pushes new value to AWS `pizza-secrets` - so please make sure to sync down for local dev!
> chore: rotate Hasura admin secret on AWS & Docker envs

- api.planx.uk/lib/hasura/metadata/index.ts
- api.planx.uk/modules/file/service/uploadFile.ts
- api.planx.uk/modules/send/createSendEvents/controller.ts
- api.planx.uk/modules/send/createSendEvents/types.ts
- api.planx.uk/modules/send/routes.ts
- api.planx.uk/modules/send/s3/index.test.ts
- api.planx.uk/modules/send/s3/index.ts
- editor.planx.uk/src/@planx/components/Send/Editor.tsx
- editor.planx.uk/src/@planx/components/Send/Public.tsx
- editor.planx.uk/src/@planx/components/Send/model.ts
These are the backend changes following on from #2999:
- Adds API endpoint `/upload-submisison/:localAuthority` within Send module to generate digital planning payload JSON & upload as a private file to a specified/static S3 folder within our main user data bucket
- Hooks up Hasura send events for this destination
**Testing:**
- Go to a supported submission service flow in Barnet's editor workspace (eg Prior Approval) 
- Update Send component to select S3 option and publish
- Open `/published` link and fill out application (note that Pay is not enabled for Barnet and will show error, but you can "Continue" through without paying for this test and still generate a valid payload)
- After reaching Confirmation page, check Hasura events for successful audit log 
- The success message will …
> feat: add send events and API endpoint for uploading submissions to S3

- editor.planx.uk/src/@planx/components/Content/Public.test.tsx
- editor.planx.uk/src/@planx/components/Content/Public.tsx
Bug report via August. You can define help text in the editor for Content nodes, but it was never displayed on the frontend - presumably because this component doesn't use the `QuestionHeader />` . 
This now displays the "More information" link below the rich text content block if defined like this:
> fix: show help text if defined for Content components

- editor.planx.uk/src/@planx/components/Confirmation/Public.tsx
Quick one — the contact text on the confirmation page is currently set in council primary colour.
PR updates to use the default text colour.
**Current:**
**Updated:**
> fix: Confirmation contact set in primary colour

- editor.planx.uk/src/@planx/components/shared/PrivateFileUpload/PrivateFileUpload.tsx
- Reorders the `Dropzone` component to be above the list of `UploadedFileCard` components
- Recommended as a usability improvement in accessibility report - issue "Organisation of Content", page 80
- Matches file upload and label
> chore(a11y): Re-order dropzone to be above file cards

- e2e/tests/ui-driven/src/pay.spec.ts
✔️  Regression tests passing on this branch here - https://github.com/theopensystemslab/planx-new/actions/runs/8686048354
This PR is a follow on from https://github.com/theopensystemslab/planx-new/pull/3009 from last week. 
GovPay have now reverted the change we were fixing in the previous PR - possibly this was caused by a bug on their end?
Traces from failing regression tests show that these fields are now already pre-populated when navigating back to them.
> fix(e2e): Revert change to GovPay journey

- editor.planx.uk/src/@planx/components/shared/Preview/SummaryList.tsx
- editor.planx.uk/src/components/Header.tsx
- editor.planx.uk/src/pages/FlowEditor/lib/store/settings.ts
- editor.planx.uk/src/pages/PlatformAdminPanel.tsx
- editor.planx.uk/src/routes/authenticated.tsx
- editor.planx.uk/src/types.ts
- hasura.planx.uk/metadata/tables.yaml
- hasura.planx.uk/migrations/1713084872473_create_view_teams_summary/down.sql
- hasura.planx.uk/migrations/1713084872473_create_view_teams_summary/up.sql
**Why / current challenges / user stories:** 
- As more & more councils are onboarding or preparing to go live with services, we have a fair amount of back & forth in Slack about what's done versus still outstanding when it comes to their integrations. As a Planx product owner, I want to be able to check these details myself in one place and not rely on a dev to sign into the Hasura console/database to check ad-hoc. 
- For help-issues related to send to email, devs currently have to sign into the Hasura console/database to check if a submission email is configured. As anyone on the Planx team, I want to be able to see _if_ a submission email is configured for a certain environment, and which email it is so I can respond to the council person to help them troubleshoot.
**What I'm …
> feat: basic platform admin panel for checking onboarding status & available integrations

- scripts/encrypt/decrypt.ts
- scripts/encrypt/encrypt.ts
- scripts/encrypt/package.json
Seems sensible to have this in place! I've just been toggling `encypt()` with `decrypt()` when needed but it's a bit of a faff.
The order of the arguments has also been changed as this is easier for writing or reading multiple values (the key stays constant, and only the secret needs to change).
> chore: Add `decrypt()` util to scripts

- api.planx.uk/modules/admin/session/digitalPlanningData.test.ts
- api.planx.uk/modules/admin/session/digitalPlanningData.ts
- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- e2e/tests/api-driven/package.json
- e2e/tests/api-driven/pnpm-lock.yaml
- e2e/tests/ui-driven/package.json
- e2e/tests/ui-driven/pnpm-lock.yaml
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
Relies on https://github.com/theopensystemslab/planx-core/pull/353
**Testing:**
- I copied Freya's failed staging payload to this pizza
- This admin endpoint displays validation errors as before https://api.3021.planx.pizza/admin/session/22d8d2ee-df1f-4696-9713-fc366561ee98/digital-planning-application
- Adding the `skipValidation` query param now displays the invalid data payload https://api.3021.planx.pizza/admin/session/22d8d2ee-df1f-4696-9713-fc366561ee98/digital-planning-application?skipValidation=true
> feat: add option to skipValidation when using `/digital-planning-application` admin endpoint

- editor.planx.uk/src/pages/FlowEditor/components/Settings/index.tsx
https://github.com/theopensystemslab/planx-new/assets/20502206/bcd53e78-fadc-4608-8f15-50fd9c44e0fb
> fix: Add zIndex value to settings to cover badge

- editor.planx.uk/src/pages/FlowEditor/index.tsx
Quick / dirty fix to a very odd regression currently live on staging and production. Replicable in Chrome, Firefox and Edge.
See screenshot below of current staging and production Editor. The flow is pushing the preview web browser off-screen. 
There's a commit somewhere in https://github.com/theopensystemslab/planx-new/pull/3023 which introduced this and we missed. Will take a closer look through tomorrow to try and resolve this properly, but in the meantime this at least seems to resolve things.
> fix: Editor layout overflow bug

- infrastructure/data/Pulumi.staging.yaml
`pulumi preview --stack staging` gives the following correct output here - https://app.pulumi.com/planx/data/staging/previews/72838b03-854f-47d4-9272-9810fe91e3e0
Next steps -
> chore: Rotate Postgres staging password

- infrastructure/application/Pulumi.production.yaml
- infrastructure/data/Pulumi.production.yaml
> chore: Rotate `db-password` and `metabasePgPassword` (production)

- editor.planx.uk/src/@planx/components/FileUploadAndLabel/SelectMultiple.tsx
- editor.planx.uk/src/@planx/components/shared/PrivateFileUpload/UploadedFileCard.tsx
- editor.planx.uk/src/theme.ts
Adjusts styling of the autocomplete on upload + label to match previous iteration.
> feat: Styling for autocomplete on upload

- editor.planx.uk/src/pages/FlowEditor/floweditor.scss
Quick one: prevent the editor sidebar/preview pane from shrinking if no content is present.
**Before:**
**After:**
> fix: Prevent editor sidebar from shrinking

- api.planx.uk/modules/pay/middleware.ts
- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- api.planx.uk/tests/mocks/inviteToPayMocks.ts
- e2e/tests/api-driven/package.json
- e2e/tests/api-driven/pnpm-lock.yaml
- e2e/tests/ui-driven/package.json
- e2e/tests/ui-driven/pnpm-lock.yaml
- e2e/tests/ui-driven/src/mocks/flows/invite-to-pay-flow.ts
- e2e/tests/ui-driven/src/mocks/flows/pay-flow.json
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
- editor.planx.uk/src/@planx/components/Pay/Editor.test.tsx
- editor.planx.uk/src/@planx/components/Pay/Editor.tsx
- editor.planx.uk/src/@planx/components/Pay/Public/Pay.tsx
- editor.planx.uk/src/@planx/components/Pay/model.test.ts
- editor.planx.uk/src/@planx/components/Pay/model.ts
- Addresses this comment - https://github.com/theopensystemslab/planx-new/pull/3015#discussion_r1568374826
- The value for `paidViaInviteToPay` now appears as a dynamic one
- It is not related to the `isInviteToPay` prop in the `Pay` component
- Updates validation rules of dynamic data variables
> fix: Break link between `isInviteToPay` Pay component prop and `paidViaInviteToPay` metadata value

- hasura.planx.uk/metadata/tables.yaml
- hasura.planx.uk/migrations/1713793168052_alter_table_public_team_integrations_add_column_staging_file_api_key/down.sql
- hasura.planx.uk/migrations/1713793168052_alter_table_public_team_integrations_add_column_staging_file_api_key/up.sql
**Changes:** 
- Adds `*_file_api_key` variables per environment (will retire existing env var `FILE_API_KEY_BARNET` in a future PR)
- Adds `power_automate_webhook_url` 
- Currently assuming that councils are going to have a _single_ environment for this
- Still exploring authorisation options with Kev, so only storing/handling URL to begin with
**Follow-ups / future PRs:**
> feat: add Microsoft variables to `team_integrations`

- editor.planx.uk/src/pages/FlowEditor/components/PreviewBrowser.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Settings/index.tsx
- editor.planx.uk/src/pages/FlowEditor/floweditor.scss
- Adds tabbed menu to the browser preview in the editor sidebar to allow for switching between browser preview and history views
- Updates React states for tab functionality
> feat: Tab styling for editor browser preview / history

- editor.planx.uk/src/airbrake.ts
- editor.planx.uk/src/routes/utils.ts
Step #10 of how-to plus an alphabetic re-ordering (sorry for extra noise).
I have _not_ updated `teams.domain` on Hasura yet.
> chore: add Gloucester subdomain to editor envs

- editor.planx.uk/src/@planx/components/Checklist/Editor.tsx
- editor.planx.uk/src/@planx/components/Question/Editor.tsx
Fixes input widths for multi-input rows in the editor modal.
> fix: Input widths for multi input rows

- editor.planx.uk/src/pages/FlowEditor/components/PreviewBrowser.tsx
Realised this is going to merge to prod sooner than usual because of custom subdomain work (see #3049) - and this looks just a bit more polished ! 
(Also realising we should all get our linters aligned :slightly_smiling_face:)
> fix: quick adjustment to "History" tab to display "Coming soon"

- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
This PR will hopefully be redundant shortly as [an updated version of supertest in being worked on currently](https://github.com/ladjs/supertest/issues/833) 🤞 
If there's no updates by the time this gets to review we can go ahead with a temporary pnpm override to bypass this issue.
> chore: CVE-2022-29622

- hasura.planx.uk/metadata/tables.yaml
- hasura.planx.uk/migrations/1713964927926_alter_table_public_team_integrations_add_column_power_automate_api_key/down.sql
- hasura.planx.uk/migrations/1713964927926_alter_table_public_team_integrations_add_column_power_automate_api_key/up.sql
- scripts/seed-database/container.sh
- scripts/seed-database/write/team_integrations.sql
Based on most recent testing with Kev - this allows us to make an authorised request to the Power Automate Webhook
Plan is:
- Merge this to `main` and do prod deploy
- Update value on prod db
- Run data sync script to pull down to staging/local
- Rebase #3047 & bump planx-core commit to reflect https://github.com/theopensystemslab/planx-core/pull/359
> chore: add `team_integrations.power_automate_api_key` column

- editor.planx.uk/src/pages/FlowEditor/components/PreviewBrowser.tsx
- editor.planx.uk/src/pages/FlowEditor/index.tsx
This remains behind the "UNDO" feature flag until full functionality in place, but getting this onto `main` sooner than later should make it easier for Ian to continue working in parallel on styling while I hook up API functionality to icon button. 
**Changes:**
- Populates side panel with formatted change history of last 15 edits
- If using the "UNDO" feature flag, sets default tab to `History` rather than `PreviewBrowser` - otherwise our known rendering bug makes checking/watching consecutive edits very annoying
Run `window.featureFlags.toggle("UNDO")` for tesitng please !
> feat: display formatted edit history of a flow

- editor.planx.uk/src/components/Header.tsx
- editor.planx.uk/src/pages/ErrorPage.tsx
- editor.planx.uk/src/pages/Team.tsx
- editor.planx.uk/src/pages/Teams.tsx
- editor.planx.uk/src/theme.ts
- editor.planx.uk/src/themeOverrides.d.ts
- Replaces multiple cases of a dark background being repeated used as hex value in the app
- Introduces a `palette.background.dark` variable so that this can be brought into the theme
> chore: Dark background colour as variable

- editor.planx.uk/src/@planx/components/ui.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Flow/components/Checklist.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Flow/components/Option.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Flow/components/Portal.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Flow/components/Question.tsx
- editor.planx.uk/src/pages/FlowEditor/floweditor.scss
Visual changes to the logic graph, summarised as:
- Increased contrast to nodes, branches and add-node links
- Standardised padding across hangers and branches to increase visibility of structure
- Updated styling of portal nodes to show clear demarcation between node link (enter portal) and menu link (configure portal)
- Only questions and checklists without answers present in sticky-note styling
- Section nodes have dashed border to add subtle visual organisation to graph
- Assigned flag colours no longer apply to full background of an option - reduces contrast issue (made more acute by small size)
- GOV.UK focus style on nodes and add-node links
- Clearer green outline to mark traversed nodes
Before:
After:
> feat: Update logic graph styling

- api.planx.uk/modules/send/uniform/uniform.ts
Please see [this thread](https://opensystemslab.slack.com/archives/C5Q59R3HB/p1714060081409409) for context (OSL Slack)
> chore: Additional logging for Uniform attachArchieve endpoint

- editor.planx.uk/src/@planx/components/Send/Public.tsx
- editor.planx.uk/src/components/Header.test.tsx
- editor.planx.uk/src/lib/graphql.ts
- editor.planx.uk/src/pages/FlowEditor/components/PreviewBrowser.tsx
- editor.planx.uk/src/routes/index.tsx
- editor.planx.uk/src/routes/views/preview.tsx
- Removes temporary redirects from `/preview` to `/published` - see confirmation thread from councils that this should be updated throughout all local sites now https://opensystemslab.slack.com/archives/C5Q59R3HB/p1713872123361579
- Temporary `/amber` route is renamed to `/preview` as originally intended (note that I am _not_ redirecting `/amber` &rarr; `/preview`; since this route is only navigable to from within editor, it shouldn't really be saved/advertised anywhere!)
> chore: finalise in-editor publishing routes

- editor.planx.uk/src/pages/FlowEditor/floweditor.scss
Adds subtle 'data' styling to the Set Component, inheriting font family (monospace) and background from editor data input.
Before:
After:
**Example:**
https://3066.planx.pizza/testing/set-value-append-replace
> feat: Styling for set component in graph

- editor.planx.uk/src/@planx/components/FileUploadAndLabel/SelectMultiple.tsx
- Stops drop down list "resetting" to the top when an option is selected via keyboard
Please see https://github.com/theopensystemslab/planx-new/pull/2993#discussion_r1559815505
Originally I had to nest `ListboxComponent ` this within `SelectMultiple` in order to access functions related to the state of the popper. 
What I _think_ is happening is that selecting an item with they keyboard was causing a re-render of the popper and effectively resetting the view to the top of the list.
I've actually removed these here as currently clicking "Done" counts as a clickaway as it's outside of the scope of the popper (`ref` and `props` are applied to the `role="listbox"` child element within `ListboxComponent`). This actually in effect matches the current behaviour -
- there's no custom action being …
> fix: Autocomplete reset/re-render on keyboard events

- editor.planx.uk/src/@planx/components/shared/PrivateFileUpload/UploadedFileCard.tsx
Fixes issue where long filenames are causing layout overflow on smaller screens.
**Before:**
**After:**
> fix: Long string wrapping in filenames

- editor.planx.uk/src/@planx/components/Checklist/Public.tsx
- editor.planx.uk/src/@planx/components/DateInput/Public.tsx
- editor.planx.uk/src/theme.ts
I think this is the route of the problem causing the recent layout quirks we've been encountering.
Regression originally introduced here - https://github.com/theopensystemslab/planx-new/pull/2976
It turns out `<fieldset>` elements have [`min-inline-size: min-content`](https://developer.mozilla.org/en-US/docs/Web/CSS/min-inline-size) applied by default ([MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/fieldset#styling_with_css)). This means that child content was overflowing and affecting layouts in a number of ways.
**Broken layout on staging**
https://editor.planx.dev/opensystemslab/listed-building-consent-files
https://github.com/theopensystemslab/planx-new/assets/20502206/d49727a9-3c9c-443e-ab41-83729c015f40
**Fixed layout on pizza** …
> fix: `<fieldset>` element overflows

- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
- editor.planx.uk/src/pages/FlowEditor/index.tsx
Builds on #3056 - up for discussion & testing ! 
Rather than only being able to undo the most recent operation, now I can undo any of the operations shown - but I need to understand that it will also reverse each more recent change above it (we can't cherry pick out of this list because graph structure may have changed).
> feat: undo the last N operations to a flow

- .github/workflows/pull-request.yml
- .github/workflows/push-main.yml
- .github/workflows/push-production.yml
Resolves this issue currently raised under GitHub actions, possibly addresses recent caching issues we believe we've been facing.
> chore: Bump `actions/cache` to v4 (Node 20)

- editor.planx.uk/src/@planx/components/FileUploadAndLabel/Modal.tsx
- editor.planx.uk/src/@planx/components/FileUploadAndLabel/SelectMultiple.tsx
- editor.planx.uk/src/theme.ts
Removes margins around modal windows on smaller screens, allowing the full screen area for interactions.
> fix: Max out modal on smaller screens -- no margin

- editor.planx.uk/src/components/TestEnvironmentBanner.tsx
- editor.planx.uk/src/pages/FlowEditor/lib/store/editor.ts
Regression introduced here - https://github.com/theopensystemslab/planx-new/pull/3028
Variable hardcoded to `true` for testing and never spotted sorry 🤦‍♂️ 
Original conditional logic now restored, see here for reference - https://github.com/theopensystemslab/planx-new/pull/3028/files#diff-9bc006127599ede1eeba7b86caa661cc41ccd88a25bbccb5fbce32f9aad0ba49L22
> fix: Conditionally set test env header

- editor.planx.uk/src/components/Header.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Team/TeamMembers.tsx
- editor.planx.uk/src/routes/team.tsx
- editor.planx.uk/src/routes/teamMembers.tsx
- Makes new page `/:team/members`
- Sets up query to get team members, and to group by role
- No styling, no feature flags!
- Ready for handover to @ianjon3s!
Would be good to have a handover here to talk about how routes, queries, and components are lining up here 👍 
- "Inactive" users have an email address of `null` - should they be grouped by this, or are they fine within their previous roles?
- We can add sorting to the query if we want to, that should then carry over into the `groupBy()`
> feat: Setup query and placeholder components for "Team members" page

- editor.planx.uk/src/pages/FlowEditor/components/EditHistory.tsx
- Updates layout of undo history to make best use of available space
- Prevents layout overflow caused by long strings (urls)
- Adds MUI Tooltip to give immediate feedback on restore button
- Changes history list bullet style to square to create a subtle difference from the timeline bullet
> feat: Layout for undo history

- .github/workflows/pizza-teardown.yml
[v2](https://github.com/theopensystemslab/vultr-action/pull/2) of vultr-action is stricter about requiring all inputs, leading to a [failed teardown](https://github.com/theopensystemslab/planx-new/actions/runs/9003898131/job/24735601568) of the pizza for #2963 - this PR should resolve this by supplying a full set of inputs in the teardown workflow.
> fix: add required inputs to pizza teardown workflow

- editor.planx.uk/src/@planx/components/DrawBoundary/Public/Public.test.tsx
- editor.planx.uk/src/@planx/components/DrawBoundary/Public/index.tsx
**Previously:**
- We disabled the "Upload a location plan instead" and "Draw the boundary on a map instead" links to switch pages if the data on the respective page was fulfilled - meaning the user had to erase the boundary or remove their upload to switch pages back
**Now:**
- The links to switch pages are always enabled regardless of data
- Data is retained when switching pages
- `handleSubmit()` only submits the data from the page which the use "Continues" onwards from - ensuring the application payload has GeoJSON _or_ an uploaded location plan, never both
**Note:**
- Enabling the link & updating the corresponding `visuallyHidden` text should fix the A-level issue described on page 17 (enabling by default also resolves a AA contrast issue)
- The overall "Continue" button on this …
> fix(a11y): DrawBoundary link to switch between map and upload should always be enabled

- .github/workflows/pizza-teardown.yml
- .github/workflows/pull-request.yml
- scripts/pullrequest/create.sh
As per title - use Alpine OS instead of Ubuntu 22.04 as the base OS for our Vultr pizzas. This seems to provide some substantial time savings, according to some tests I ran (see below). In particular, the work of updating the server, ensuring docker and aws-cli are installed, and actually doing the `docker compose` command to build the container stack, all of which are encapsulated in the `Create commands` step, is reduced from an average of 10:42 to 8:05, a saving of `157s`!
I didn't compare the `Update commands` step across the different operating systems, but there may also be gains there (I think unlikely that there would be losses).
Note that Vultr now provides an OS for the new Ubuntu LTS release (24.04, Noble Numbat). This is only just released as of this PR. Once it's more mature …
> feat: build pizzas on alpine

- editor.planx.uk/src/components/Feedback/FeedbackPhaseBanner.tsx
Fixes issue highlighted by DAC report p.88 (DAC_Buttons_Styled_As_Links_Usability_01) in that the feedback link is a button with the appearance of a link.
To fix this I've added a hash link (href="#") and used `preventDefault` to remove link functionality. This works similar to how GOV.UK use it here: https://design-system.service.gov.uk/components/phase-banner/
Also, the layout has been tidied up for smaller screens.
> fix(a11y): Feedback link as <a> element

- e2e/tests/ui-driven/src/create-flow/create-flow.spec.ts
- e2e/tests/ui-driven/src/globalHelpers.ts
- editor.planx.uk/src/@planx/components/Notice/Public.tsx
Quick one - updates title of the notice component to be a `<h1>` element, as recommend in DAC audit p.67.
> fix(a11y): Update notice component title to h1

- editor.planx.uk/src/@planx/components/DrawBoundary/Public/Public.test.tsx
- editor.planx.uk/src/@planx/components/DrawBoundary/Public/index.tsx
- editor.planx.uk/src/@planx/components/FileUpload/Public.test.tsx
- editor.planx.uk/src/@planx/components/FileUpload/Public.tsx
We currently have three components that don't enable the "Continue" button by default which is flagged as a bad pattern in the "usability" feedback section of our Accessbility report: 
1. FindProperty (two pages - select & map)
2. DrawBoundary (two pages - map & upload)
3. FileUpload
These changes address enabling the continue button for all "upload" instances. I'll continue to address the map & select instances in a followup PR (see #3022).
**Testing:**
- DrawBoundary 
- When you switch to the upload page the "continue" button should always be enabled now
- If you click it before uploading, you should see an error wrapper around the upload preventing you from proceeding
- If you upload a file, you can proceed successfully
- FileUpload
-  "Continue" should be enabled by defualt
- If you …
> fix(a11y): always enable continue button on FileUpload and DrawBoundary upload page

- api.planx.uk/modules/webhooks/service/analyzeSessions/operations.ts
- editor.planx.uk/src/@planx/components/FindProperty/Public/Public.test.tsx
- editor.planx.uk/src/@planx/components/FindProperty/Public/index.tsx
- editor.planx.uk/src/@planx/components/FindProperty/model.ts
- editor.planx.uk/src/pages/FlowEditor/lib/analytics/provider.tsx
- hasura.planx.uk/migrations/1715340505747_add_find_property_action_analytics_views/down.sql
- hasura.planx.uk/migrations/1715340505747_add_find_property_action_analytics_views/up.sql
- Adds column `find_property_action` to both `analytics_summary` & `submission_services_summary` views
- Will be populated with one of two values: "Selected an existing address" or "Proposed a new address" 
- Will help us understand how users are proceeding through the service and evidence roadmap requests related to improving search capability & map interactions around proposing new addresses
> chore: set & track `findProperty.action` in analytics allow lists

- editor.planx.uk/src/@planx/components/DrawBoundary/Public/Public.test.tsx
- editor.planx.uk/src/@planx/components/DrawBoundary/Public/index.tsx
- editor.planx.uk/src/@planx/components/FileUpload/Public.test.tsx
- editor.planx.uk/src/@planx/components/FileUpload/Public.tsx
> fix(a11y): always enabled continue button on DrawBoundary map page

- editor.planx.uk/src/theme.ts
- Ignores the `forced-colors` media query on `img` elements to ensure we always have high enough contrast on our images
We've been unable to recreate the issue `DAC_Inverted_Colours_Usability_01` (page 89) from the accessability report. We asked for further feedback and got the following response - 
Response from DAC -
> _I tested the inverted colours by using the windows settings and applying the ‘night sky’ preset. I was able to replicate the issue on Journey 1 step 14, however I could not replicate the issue again on Journey 1 step 34. It is frequent that <img> elements do not contrast appropriately when these settings are applied, however if these images are implemented as <svg> elements, then the CSS property ‘forced-color-adjust: auto;’ can be applied. This CSS property is used to …
> fix(a11y): Add support for Windows high contrast mode

- hasura.planx.uk/metadata/tables.yaml
- hasura.planx.uk/migrations/1715689232003_create view submission services log /down.sql
- hasura.planx.uk/migrations/1715689232003_create view submission services log /up.sql
Creates a new view of submission & pay events - now exposing successful _and failed_ events - more similar to what we log in `#planx-notifications`.  
Here's a snippet of what this looks like running against an environment with submissions:
Next steps:
- Query via frontend and update visual display in submissions log tab
- Remove any views or outdated data structures associated with current implementation
> feat: create `submission_services_log` view

- editor.planx.uk/src/routes/index.tsx
See thread https://opensystemslab.slack.com/archives/C01E3AC0C03/p1715761863470209
A better option than fully reverting #3069 !
> fix: temporary redirect for Bucks building control service

- hasura.planx.uk/migrations/1715784133713_run_sql_migration/down.sql
- hasura.planx.uk/migrations/1715784133713_run_sql_migration/up.sql
Having `team_slug` means we can match on variables in existing dashboards without an additional join in Metabase.
> chore: Replace `team.name` for `team.slug` in `feedback_summary` view

- editor.planx.uk/src/@planx/components/Question/Public.test.tsx
- editor.planx.uk/src/@planx/components/Question/Public/Question.tsx
- Enables the "Continue" button by default on all `Question` components
- Adds an error message if no option is selected
- Copy taken from error message of text input
Test flow here with all variants of the question component - https://3149.planx.pizza/testing/question-error-test
> feat(a11y): Remove disabled button from `Question` component

- editor.planx.uk/src/pages/FlowEditor/components/Settings/Submissions/EventsLog.tsx
Builds on the submissions log work:
https://github.com/theopensystemslab/planx-new/pull/3153
- Move border to collapsable element to prevent double border
- Prevent overflow by setting explicit column widths and wrapping code
- Use separate icons for success/error, so that it not communicated by colour only
- Wrap cell inner contents in a div with `flex` to allow cells to expand vertically
**Preview:**
https://3155.planx.pizza/testing/test-submissions/settings/submissions
> feat: Submissions log styles update

- editor.planx.uk/src/lib/feedback.ts
- hasura.planx.uk/metadata/tables.yaml
- hasura.planx.uk/migrations/1715867685564_alter_table_public_feedback_add_column_node_data/down.sql
- hasura.planx.uk/migrations/1715867685564_alter_table_public_feedback_add_column_node_data/up.sql
- hasura.planx.uk/migrations/1715868696352_run_sql_migration/down.sql
- hasura.planx.uk/migrations/1715868696352_run_sql_migration/up.sql
- Adds new `node_data` column to `feedback` table
- Writes to the `node_data` column when feedback is logged
- Rebuilds `feedback_summary` view to read from this column
The current `feedback_summary` view in pretty slow running, likely due to the filtered join per-row to the `published_flows` table. This solution stores the node data directly alongside the feedback, thus mitigating this issue (hopefully!).
Local testing is good - significantly faster to query the view now.
Once the following changes are live on production, I'm proposing to run the following SQL to populate the new column. I'm opting to do this manually instead of as a Hasura migration as it will be slightly easier to manage and monitor, and it's pretty low-risk (we're just populating a new column).
```sql
UPDATE feedback …
```
> feat: Capture `node_data` directly alongside feeback

- editor.planx.uk/src/@planx/components/Result/Public/ResultReason.tsx
Address issue where result summaries that do not have expandable content (help text) are still given expand functionality and associated aria labels.
To prevent this the accordion component is only used if there is associated content to expand.
Current:
https://editor.planx.dev/testing/result/published
Updated:
https://3150.planx.pizza/testing/result/published?analytics=false
> a11y: Result accordions non-expanding option

- editor.planx.uk/src/pages/FlowEditor/components/EditHistory.tsx
"Undo" is live on prod this morning which is exciting because all flows are loading with an _existing_ edit history (whereas pizzas and staging do _not_ sync edit history). 
When the earliest timeline point is not "Created flow", it's not always obvious why the timeline ends. This adds a quick contextual note in cases where edit history for this service is longer than the 15 operations we show!
> feat: add quick note to contextualise length of edit history

- editor.planx.uk/src/@planx/components/FindProperty/Public/index.tsx
- editor.planx.uk/src/components/DelayedLoadingIndicator.tsx
To both build on the work in progress here: https://github.com/theopensystemslab/planx-new/pull/3022,
and also as an improvement to the current setup — updates the progress indicator to be inline with the continue button.
**Changes:**
- Progress indicator given a wrapper that is omnipresent (absolute positioning on desktop), eliminates layout shift on both desktop and small screens
- `inline` prop added to `DelayedLoadingIndicator`, making it easier to use either as a full screen takeover or as part of page content
- Text updated to "Fetching address data" to be more descriptive to users
**Preview:**
**Test:**
https://3136.planx.pizza/testing/address-lookup/published
> feat: Inline loading indicator for address lookup

- editor.planx.uk/src/components/Feedback/MoreInfoFeedback.tsx
- editor.planx.uk/src/components/Feedback/index.tsx
- editor.planx.uk/src/pages/FlowEditor/components/EditorMenu.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Flow/FeedbackPage.tsx
- editor.planx.uk/src/routes/feedback.tsx
- editor.planx.uk/src/routes/flow.tsx
- hasura.planx.uk/metadata/tables.yaml
- hasura.planx.uk/migrations/1715929881942_run_sql_migration/down.sql
- hasura.planx.uk/migrations/1715929881942_run_sql_migration/up.sql
- Sets up permissions to allow logged in users to access data from `feedback_summary` view
- Sets up routing and placeholder component to display this in the Editor, following the pattern established in https://github.com/theopensystemslab/planx-new/pull/3109
- Display data in table
- Get more detailed info to a user - either CSV download per-row, or established accordion pattern maybe? I've included a function to fetch this data and we can have a think about this one.
My intention here is to display a small subset of the data - are these minimal columns the most relevant ones?
> feat: Setup routing, queries, and permissions for `/:flow/feeback`

- editor.planx.uk/src/@planx/components/FileUploadAndLabel/Public.test.tsx
- editor.planx.uk/src/@planx/components/FileUploadAndLabel/Public.tsx
- editor.planx.uk/src/@planx/components/FileUploadAndLabel/SelectMultiple.tsx
- editor.planx.uk/src/@planx/components/shared/PrivateFileUpload/UploadedFileCard.tsx
- editor.planx.uk/src/theme.ts
- editor.planx.uk/src/ui/shared/Checkbox.tsx
- Replaces the MUI Select component with a MUI Autocomplete component within the `FileUploadAndLabel` modal
- This is done in order to resolve the accessibility report issue "Customised Combobox" (Page 35)
After spending a good while amending the markup of the `Select` I realised it wasn't possible to meet the requirements laid out the in report. These are the two fundamental barriers I hit -
- MUI was hardcoding `role="option"` on the children of the Select - we require `role="group"`
- A single `ul` element is forced as the first child element
Using the Autocomplete allows us access to grouping, which allows us to inject some custom HTML elements in the order and location we require. I've been aiming to match the following example of a grouped listbox shared in the report - …
> feat: Replace `Select` with `Autocomplete` in `FileUploadAndLabel` component

- scripts/seed-database/container.sh
- scripts/seed-database/write/feedback.sql
- scripts/seed-database/write/main.sql
Not really advocating for this to be merged, but I wanted some sort of history here and it may prove to be helpful for others.
I added a `feedback.sql` so I could get a copy of production data locally.
Commenting out an item in the list seemed a nicer pattern than a flag per table or some other optional inputs to the script. A bit quick and dirty but worked well for me.
> chore: Feedback sync script (example)

- editor.planx.uk/src/theme.ts
Removes a visual regression introduced by placing popper shadow property at theme level.
Preview of issue:
> fix: Remove popper shadow placed at theme level

- editor.planx.uk/src/pages/FlowEditor/components/Team/TeamMembers.tsx
Spotted while testing here https://editor.planx.dev/newcastle/members
> fix: only show active users in "Team editors" 

- api.planx.uk/modules/gis/routes.ts
- api.planx.uk/modules/gis/service/article4Schema.ts
- api.planx.uk/modules/gis/service/digitalLand.ts
- editor.planx.uk/src/pages/PlatformAdminPanel.tsx
Currently the Editor's admin panel will display a static "?" for Article 4 status because A4s are a tricky three-part onboarding process: spreadsheet, flow content, and GIS API.  
This introduces a quick API endpoint we can use to correctly set "Configured" or "Not configured" for a more meaningful reflection of the status of the final step of the onboarding process (GIS API).
> fix: check if council has A4 schema set via GIS API and display in admin panel

- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- e2e/tests/api-driven/package.json
- e2e/tests/api-driven/pnpm-lock.yaml
- e2e/tests/ui-driven/package.json
- e2e/tests/ui-driven/pnpm-lock.yaml
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
Reverts theopensystemslab/planx-new#3180 (I'll fix-forward in #planx-core next) 
Regression tests passing against this branch :white_check_mark: which fixes our failure last night: https://github.com/theopensystemslab/planx-new/actions/runs/9186773259
**Context:**
A Planx tester didn't wait for constraints to load (x3 apps for a demo) and submitted to BOPS. The payloads were valid with empty constraints, and we got a successful response from BOPS, but the apps didn't display in BOPS. Likely because they have an internal dependency on expected constraints? I was tagged in the help-issue request instead of the BOPS team, and should have been initially clear which side of the fence this bug was on. 
I thought this simple payload mapping change would be fine & allow me to resubmit the apps …
> Revert "chore: bump planx-core"

- editor.planx.uk/src/routes/flow.tsx
- editor.planx.uk/src/routes/flowSettings.tsx
This is a small fix / refactor I noticed when working on https://github.com/theopensystemslab/planx-new/pull/3183. It was introduced in https://github.com/theopensystemslab/planx-new/pull/3028. 
This work in also included in the WIP PR #3183 - once this PR is merged I'll rebase that one to pick up the changes. I've pulled it out into its own PR to make it easier to test & review. 
The new pages (e.g. `/:flow/service`) aren't correctly fetching team settings - this was only being done in `/:flow/settings/:tab`).
A shared function, `getFlowSettings()`, to handle this across routes in a consistent manner.
To test this works as expected, you should be able to view and edit settings for a flow via both routes. You'll need the `EDITOR_NAVIGATION` feature flag to do this …
> fix: Fetch flow settings in new views

- editor.planx.uk/src/@planx/components/SetValue/Editor.tsx
- editor.planx.uk/src/@planx/components/SetValue/model.ts
- editor.planx.uk/src/@planx/components/SetValue/utils.test.ts
- editor.planx.uk/src/@planx/components/SetValue/utils.ts
- editor.planx.uk/src/pages/FlowEditor/components/Flow/components/Node.tsx
- editor.planx.uk/src/pages/FlowEditor/lib/__tests__/preview/record.test.ts
- editor.planx.uk/src/pages/FlowEditor/lib/__tests__/setValue.test.ts
- editor.planx.uk/src/pages/FlowEditor/lib/store/preview.ts
- Changes SetValue component from having a single operation, to having an option to append, replace, removeOne or removeAll
Basic test flow here - https://2914.planx.pizza/testing/set-value-playground
This (hopefully!) illustrates that the behaviour matches the desired outcomes discussion at our recent "Logic Camp" - full details here - https://miro.com/app/board/uXjVN9K07PQ=/?moveToWidget=3458764588027715730&cot=14
I feel like there's a decent level of unit testing here, as well as more psuedo-integration level tests calling store functions to mock a user's journey.
What I'm really interested in testing feedback on would be - 
- Unexpected, or breaking, changes in existing flows - possibly related to edge cases with current SetValue
- Is there something missing in how multiple SetValue …
> feat: Append, replace, removeOne, & removeAll operations for `SetValue`

- e2e/tests/api-driven/src/flowStatusHistory/flowStatusHistory.feature
- e2e/tests/api-driven/src/flowStatusHistory/helpers.ts
- e2e/tests/api-driven/src/flowStatusHistory/steps.ts
- hasura.planx.uk/metadata/tables.yaml
- hasura.planx.uk/migrations/1715954131936_create_table_public_flow_status_enum/down.sql
- hasura.planx.uk/migrations/1715954131936_create_table_public_flow_status_enum/up.sql
- hasura.planx.uk/tests/flow_status_history.test.js
- Adds `flows.status` column, which can be one of "online" or "offline"
- Adds `flow_status_history` audit table which could be used to check the status of a flow at a given point in time, and could be used to filter analytics if we wished to do so
- Populates table to indicate that all flows are currently "online"
- Adds trigger `tack_flow_status_history()` which has the following behaviour -
- Called on `UPDATE` to `flow.status` or `INSERT` to `flows`
- Closes "open" `flow_status_history` record, and opens new one with toggled status
- Hasura introspection tests for table permissions
- Gherkin integration tests for trigger behaviour 
- Simple toggle in Editor to control status
- Restrict public access to flow based on status
- Slack message on toggle (?)
Regression tests passing here - …
> feat(backend): Toggle flow online or offline

- .github/workflows/pizza-teardown.yml
- .github/workflows/pull-request.yml
- scripts/pullrequest/create.sh
Reverts theopensystemslab/planx-new#3117
Replaces #3193  - forgot we need to swap more than just OS here, but package manager and install steps too! 
Plan would be to revert again in a few days once Apine has a fix
> Revert "feat: build pizzas on alpine"

- scripts/seed-database/write/flows.sql
This PR adds the `flows.status` column to our sync script which was added in #3170 
Tested locally with `pnpm test-sync` command ✅
> fix: Add new `flow.status` column to sync script

- api.planx.uk/modules/pay/controller.ts
- api.planx.uk/modules/pay/helpers.ts
- api.planx.uk/modules/send/s3/index.ts
- api.planx.uk/modules/send/utils/exportZip.test.ts
- api.planx.uk/modules/send/utils/exportZip.ts
- api.planx.uk/modules/send/utils/helpers.ts
- api.planx.uk/modules/webhooks/service/validateInput/utils.ts
**Changes:**
- Generates & includes a Digital Planning Application JSON for _every_ "Send to email" or "Upload to S3" submission, skipping validation if not a supported application type
- For example, this should be sufficient for Barnet to begin testing "Report a Planning Breach" with Power Automate
- Does not change anything about current BOPS or Uniform payloads
- BOPS currently rejects invalid payloads, they may accept discretionary services in future
- Uniform zip can't contain JSON files at all currently
- Moved pay helpers out of send module into pay!
**Open questions:** 
- What's a "generic" or "discretionary" payload to begin with? I've decided it's simply the ODP Schema shape, but without any validation for a couple of reasons:
- We have existing methods to generate this
- …
> feat: generate JSON payloads for discretionary services

- api.planx.uk/modules/gis/service/digitalLand.ts
Quick adjustment to start returning the WKT `geometry` & `point` fields from the raw Planning Data "entity" response in our own formatted response for any intersecting entities. 
We used to filter these out for simplicity, but now we want to start prototyping displaying maps of intersecting constraints on the frontend so we need the geometry! (We already have a WKT library in the editor to handle the GeoJSON conversion).
> fix: GIS API should return geometry

- editor.planx.uk/src/@planx/components/PlanningConstraints/List.tsx
- editor.planx.uk/src/@planx/components/PlanningConstraints/Public.tsx
- editor.planx.uk/src/@planx/components/shared/Preview/SimpleExpand.tsx
Style updates to planning constraints, based on the recommendations from Barnet:
https://trello.com/c/EBcEUyLk/2896-discuss-these-2-changes-to-the-constraints-components-from-the-barnet-team
- Add colour tint to accordion header to re-enforce grouping
- Tidy up spacing of 'no constraints' copy
**Preview:**
Before (left) vs after (right)
**Test:**
https://3179.planx.pizza/testing/constraints/preview
> feat: Update constraints page styles

- editor.planx.uk/src/@planx/components/PropertyInformation/Public.tsx
Spotted while grabbing screenshots & updating service spec pages for geo features. 
`PropertyInformation` component was using a redundant local definition rather than importing the shared `MapContainer` styled component. This was also leading to an oversized map on the PropertyInformation page, now it's a smaller reference map as expected.
> fix: ensure all maps are referencing same container

- .github/workflows/pull-request.yml
- .github/workflows/regression-tests.yml
It's currently tricky to parse the logs from the React tests in the GitHub UI as they're massive! Over 50mb of logs on each run means a lot of endless scrolling and frustration.
Almost all the warnings are either - 
- `console.alert()` and `console.error()` messages such as Zustand deprecation warnings, CSS warnings (`:nth-child` alert)
- `console.log()` called by tests or components
- `not wrapped in act(...)` warning (see https://kentcdodds.com/blog/fix-the-not-wrapped-in-act-warning)
This should not affect test runs, or failure messages, it just stops the console working during test runs (docs: https://jestjs.io/docs/cli#--silent)
> chore: Run React tests with `--silent` flag

- editor.planx.uk/src/@planx/components/List/Public/Context.tsx
- editor.planx.uk/src/@planx/components/List/Public/index.test.tsx
- editor.planx.uk/src/@planx/components/List/Public/index.tsx
- editor.planx.uk/src/@planx/components/List/model.ts
- Follows on from https://github.com/theopensystemslab/planx-new/pull/3197
- Sets up `ListContext` to wrap components and share state and logic
- List items can be added, edited and removed
- Tests to describe this behaviour
https://github.com/theopensystemslab/planx-new/assets/20502206/5cf251de-6cff-458c-9651-22eabe40a1d9
- No form state / form validation - any values typed into inputs is not persisted
- Logic to stop new items being added when there's still an active/incomplete item
- UI polish, e.g. scroll to new item, scrol on delete or edit
I feel like one of the main pain points with the `FileUploadAndLabel` component was having a group of interdependent components which relied on a shared state in the "root" component. This wasn't a problem initially, but as things grew it got …
> feat: Basic CRUD for `userData` structure, setup `ListContext`

- editor.planx.uk/src/theme.ts
Colour are derived from current colours, darkened to hit 3:1 ratio.
> fix(a11y): Non-text contrast (3:1)

- hasura.planx.uk/migrations/1715954131936_create_table_public_flow_status_enum/up.sql
Please see https://github.com/theopensystemslab/planx-new/pull/3183#discussion_r1617191040 for context.
Despite reading as being correct (to me!) I didn't get the expected results on staging after merging to `main`. All `flow.status` columns were set to `"offline"` despite the command `UPDATE "public"."flows" SET status = 'online';` in the migration script.
I'm guessing this may be an issue a race condition, or some sort of issue with how Hasura handles transactions as part of migrations?
I manually fixed this on staging but as there's an associated trigger and audit table, it was a bit of a hassle. This change in this PR won't get run on staging but the updated migration will get run when it hits production.
> fix: Flow status migration script

- editor.planx.uk/src/@planx/components/DateInput/DateInput.stories.tsx
- editor.planx.uk/src/@planx/components/DateInput/Editor.test.tsx
- editor.planx.uk/src/@planx/components/DateInput/Editor.tsx
- editor.planx.uk/src/@planx/components/DateInput/Public.test.tsx
- editor.planx.uk/src/@planx/components/shared/testHelpers.ts
- editor.planx.uk/src/ui/shared/DateInput.tsx
This is the only public facing placeholder in PlanX - all others are in the Editor. To meet the requirements set out in the report, we'd need to increase font size to 18pt which is a fair bit bigger than the current size.
Removing placeholder text also meets the [GDS recommendation](https://design-system.service.gov.uk/components/text-input/), as well as the pattern currently used in [their Date Input components](https://design-system.service.gov.uk/components/date-input/) - 
> ### Avoid placeholder text
> Do not use placeholder text in place of a label, or for hints or examples, as:
>
> - it vanishes when the user starts typing, which can cause problems for users with memory conditions or when reviewing answers
> - not all screen readers read it out
> - its browser default styles often …
> fix(a11y): Remove placeholders in `DateInput`

- e2e/tests/api-driven/src/flowStatusHistory/steps.ts
- hasura.planx.uk/migrations/1715954131936_create_table_public_flow_status_enum/up.sql
Apologies - just spotted this issue now when testing. This must have been missed when changing the model to offline by default here - https://github.com/theopensystemslab/planx-new/pull/3170/commits/81d7c7be64566b770ca5abb98b1b429e00a01a6f
I've actually just updated the _existing_ migration file here, with proposal to be to update the trigger directly on staging and production as a more immediate fix.
✅ Regression tests passing here - https://github.com/theopensystemslab/planx-new/actions/runs/9289391705
> fix: Incorrect status in `flow_status_history`

- editor.planx.uk/src/components/Header.tsx
Adds a "restart" text label to the restart button in the page header.
Highlighted as a usability suggestion in the DAC audit.
**Example:**
https://3211.planx.pizza/camden/apply-for-prior-approval/published
> feat: Add restart text label to restart button

- editor.planx.uk/src/routes/index.tsx
Reverts theopensystemslab/planx-new#3147
Jack has confirmed Bucks IT have updated all links to Planx services on their council site now, so we should be able to safely revert this.
> Revert "fix: temporary redirect for Bucks building control service"

- editor.planx.uk/src/@planx/components/DateInput/Editor.test.tsx
- editor.planx.uk/src/@planx/components/NumberInput/Editor.tsx
> fix: spell "metres" not "meters" in NumberInput modal
