- .github/workflows/sync-staging-db.yml
fixes `no Pulumi.yaml project file found` error
> fix(ci): add missing working directory

- README.md
Some notes on things that tripped me up.
> Chore: Add a troubleshooting section to README

- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
- editor.planx.uk/src/@planx/components/DrawBoundary/Public/index.tsx
- editor.planx.uk/src/@planx/components/DrawBoundary/Public/map.css
- editor.planx.uk/src/@planx/components/FindProperty/Public/index.tsx
- editor.planx.uk/src/@planx/components/FindProperty/Public/map.css
Branched from https://github.com/theopensystemslab/planx-new/pull/1223 to try another style suggested by @Alastairparvin at Show & Tell
> feat: Increase map size in DrawBoundary (alt)

- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
Reverts theopensystemslab/planx-new#1185
Confirmed this still throws the same error & breaks login on Staging https://opensystemslab.slack.com/archives/C4B0CKQ3U/p1666709259742689
> Revert "build: upgrade passport >= 0.6.0"

- api.planx.uk/saveAndReturn/sendEmail.test.ts
- api.planx.uk/saveAndReturn/utils.ts
- api.planx.uk/tests/mocks/saveAndReturnMocks.js
- Please see a proper explanation co-located on the offending code!
- There was no user impact here - duplicate events were not getting created 👌 
- Adds test cases to capture intended behaviour
- Tidies up old JSDocs
> fix: Correctly handle lowcal_session.has_user_saved

- editor.planx.uk/src/@planx/components/DrawBoundary/Public/Upload.tsx
- editor.planx.uk/src/@planx/components/FileUpload/Public.tsx
https://john-opensystemslab-io.airbrake.io/projects/329753/groups/3393061708783262295
> fix: file type is possibly undefined on draw boundary upload

- scripts/seed-database/upsert-production-flows.js
The existing sync code had a bug in the scenario where staging and
production environments have the same team ids and team slugs
(which are unique contraints) but where each environment would have these
ids and slugs be in different pairings.
Here instead of upsert we're doing a delete-then-insert mechanism.
> fix(sync): delete before insert

- api.planx.uk/helpers.ts
- scripts/seed-database/upsert-production-flows.js
Fixes two issues [reported on Slack](https://opensystemslab.slack.com/messages/C01E3AC0C03/p1667301408714349?thread_ts=1667300494.749479&cid=C01E3AC0C03). 
Note to self: Re-run the sync script after merging this to fix staging.
> fix(staging): infinite loading spinner and publish button

- editor.planx.uk/src/@planx/components/DrawBoundary/Public/index.tsx
https://1254.planx.pizza/testing/maps-test/preview?analytics=false
> feat: DrawBoundary map continues to show address point

- api.planx.uk/editor/copyPortalAsFlow.test.ts
- api.planx.uk/editor/copyPortalAsFlow.ts
- api.planx.uk/editor/findReplace.test.ts
- api.planx.uk/editor/findReplace.ts
- api.planx.uk/editor/publish.test.ts
- api.planx.uk/editor/publish.ts
- api.planx.uk/helpers.ts
- api.planx.uk/package.json
- api.planx.uk/saveAndReturn/validateSession.ts
- api.planx.uk/server.test.js
- Convert `api.planx.uk/editor` from JavaScript to TypeScript
- A few additional tidy ups to helper functions
> chore: Convert api/editor to TS

- infrastructure/application/Pulumi.production.yaml
Reverts theopensystemslab/planx-new#1262
> Revert "fix: rotate production `file-api-key` to be alphanumeric"

- editor.planx.uk/src/api/upload.ts
- Currently, test users use the name "test test" on Production to send applications to the BOPS Staging environment
- Applications sent via this method are failing, as they cannot access images uploaded via the PlanX Production API
- If a user is using "test test", upload via the Staging API
- Likewise, correctly format the URL added to their passport
- This would be made redundant by https://github.com/theopensystemslab/planx-new/pull/1275
- For this to work, a user has to enter their name before uploading files. This is fine for LDC flows, but may not always hold true.
- Needs to be tested on prod to know it works 😬 
A HTTP interceptor would be a nice refactor here to clean things up a little if our general pattern is "a test application should use the staging API". Example Axios docs - …
> fix: Files uploaded by test users should be handled by staging

- .github/workflows/sync-staging-db.yml
- scripts/seed-database/package.json
- scripts/seed-database/pnpm-lock.yaml
- scripts/seed-database/upsert-production-flows.js
- Adds an option to the script that allows one to specify the maximum concurrency
- This should solve our weekly sync problem
> feat(sync): add limit cli options

- editor.planx.uk/src/routes/utils.ts
Fixes bug reported here:
https://opensystemslab.slack.com/archives/C5Q59R3HB/p1670506544605919?thread_ts=1670500507.687649&cid=C5Q59R3HB
> fix(public): add missing doncaster domain config

- editor.planx.uk/src/ui/RichTextInput.stories.tsx
- editor.planx.uk/src/ui/RichTextInput.test.ts
- editor.planx.uk/src/ui/RichTextInput.tsx
Initially part of #1192, plucked off of it to reduce scope.
> Inject passport variables into rich text editor output

- .github/workflows/pull-request.yml
- .gitignore
- docker-compose.yml
- e2e/.gitignore
- e2e/package.json
- e2e/playwright.config.ts
- e2e/playwright/assets/payFlowPublishedFlow.json
- e2e/playwright/pay.spec.ts
- e2e/playwright/utils.ts
- e2e/pnpm-lock.yaml
- e2e/run-playwright-tests.sh
- e2e/wait-for-it.sh
- editor.planx.uk/src/@planx/components/DrawBoundary/Public/Upload.tsx
- editor.planx.uk/src/ui/FileUpload.tsx
- hasura.planx.uk/migrations/1669979245259_alter_table_public_analytics_logs_alter_column_analytics_id/down.sql
- hasura.planx.uk/migrations/1669979245259_alter_table_public_analytics_logs_alter_column_analytics_id/up.sql
- adds End-to-End tests for the Pay component using Playwright
- the test running on the `preview` URL be redirected to the online yet sandbox `GOV.UK` API
> test(e2e): add pay component test using playwright

- .github/workflows/cron-deploy-to-production.yml
Should fix the error below
https://github.com/theopensystemslab/planx-new/actions/runs/3759553898/jobs/6389256274
> fix(ci): add missing namespace

- editor.planx.uk/src/@planx/components/Pay/Public/Confirm.tsx
> fix: Wire up alternate payments form

- .github/workflows/end-to-end-tests.yml
was previously triggering duplicate runs! context and outcome of quick vote here https://opensystemslab.slack.com/archives/C01E3AC0C03/p1674053666637189
> chore: reduce e2e github action to run on "review_requested" only

- api.planx.uk/send/email.ts
was previously only displaying the map on the HTML in the email packet, this additionally populates the "Data" column of the template.
together with #1379, ensures that folks who are testing Prior Approval will have an email packet that matches our demo from earlier this week. 
to test: 
- edit pizza db `teams.settings.sendToEmail` to add yourself
- make a simple flow with Draw, FileUpload, "Send to planning office" 
- go through flow: confirm you receive email, can download files, and zip packet contains expected files
> fix: replace map.html with application.html in zip sent by email

- api.planx.uk/send/email.test.ts
- api.planx.uk/send/email.ts
- hasura.planx.uk/migrations/1674571117161_alter_table_public_teams_add_column_submission_email/down.sql
- hasura.planx.uk/migrations/1674571117161_alter_table_public_teams_add_column_submission_email/up.sql
- scripts/seed-database/upsert-production-flows.js
reminder #1400 will require a quick content update once live, I'll plan to take care of it!
> Production deploy

- editor.planx.uk/src/@planx/components/AddressInput/model.ts
- editor.planx.uk/src/@planx/components/ContactInput/model.ts
- editor.planx.uk/src/@planx/components/FindProperty/Public/index.tsx
- editor.planx.uk/src/@planx/components/PropertyInformation/Public.tsx
- editor.planx.uk/src/@planx/components/TextInput/model.ts
- editor.planx.uk/src/pages/FlowEditor/lib/store/preview.ts
adds logic to original branch, as the change link work exposed important context for how to approach the actual component split in the first place
> add change link logic

- doc/architecture/decisions/0005-data-retention-policy.md
Follow up from #1325 - will share with @Alastairparvin also 👍
> doc: Data retention policy proposal

- hasura.planx.uk/metadata/cron_triggers.yaml
🍒 Cherry pick of 0870c512966b7d77310b3f35a17535879854e4a0
I'll tackle setting `NODE_ENV` as it's own task.
> chore: Drop data sanitation retries

- api.planx.uk/helpers.test.ts
- api.planx.uk/s3/controller.ts
- api.planx.uk/s3/s3.test.ts
- api.planx.uk/s3/utils.test.ts
- api.planx.uk/s3/utils.ts
Something I picked up in the background whilst watching the show & tell this morning.
The commits might make the changes in `api.planx.uk/s3/s3.test.ts` more easy to understand.
> test: Increase API test coverage

- .github/workflows/end-to-end-tests.yml
Trying to resolve changes made on https://github.com/theopensystemslab/planx-new/pull/1419
> fix(ci): Tweak E2E coverage syntax

- api.planx.uk/editor/findReplace.ts
- api.planx.uk/editor/moveFlow.ts
- api.planx.uk/editor/publish.ts
- api.planx.uk/gis/digitalLand.js
- api.planx.uk/helpers.ts
- api.planx.uk/saveAndReturn/resumeApplication.ts
- api.planx.uk/saveAndReturn/utils.ts
- api.planx.uk/saveAndReturn/validateSession.ts
- api.planx.uk/send/bops.js
- api.planx.uk/send/email.ts
- api.planx.uk/send/uniform.js
- api.planx.uk/server.ts
A few tidy ups which were flagged by the following comment - https://github.com/theopensystemslab/planx-new/pull/1424#discussion_r1095754112
> chore: Standardise API imports, gql tags

- doc/how-to/how-to-resubmit-an-application.md
Hopefully this will be short lived and replaced by a re-submission API to make this a simple / quick / repeatable process.
> doc: Re-submission guide

- api.planx.uk/.eslintrc
- api.planx.uk/helpers.ts
- api.planx.uk/send/bops.test.ts
- api.planx.uk/send/bops.ts
**What does this PR do?**
- Convert `bops.js` -> `bops.ts`
- Use `fixRequestBody()` instead of custom function (https://github.com/theopensystemslab/planx-new/pull/1434#discussion_r1100022772)
- Bump test coverage for this file to 100%
**To do**
> chore: Convert `api.planx.uk/send/bops.js` to TypeScript

- api.planx.uk/gis/local_authorities/metadata/base.js
> feat: add Locally Listed Buildings when querying planning constraints

- editor.planx.uk/src/components/Header.tsx
Missed whilst implementing https://github.com/theopensystemslab/planx-new/pull/1472
> fix: Console warning for header ref

- infrastructure/application/README.md
Trying to keep this simple, and link to other places instead of writing down all the details, as to avoid duplicate information spread across the stack. That being said, feedback is welcome.
> docs(infra): create application/README.md

- api.planx.uk/@types/planx-document-templates.d.ts
- editor.planx.uk/types.d.ts
Gunar said this during the dev call! 
Are there other updates we can/should make to the infra READMEs? Please feel free to push more commits directly to this branch!
> docs: update infrastructure README

- .github/workflows/sync-staging-db.yml
- Fixes this error: https://github.com/theopensystemslab/planx-new/actions/runs/4263660933/jobs/7420686816
- Proof that it works: https://github.com/theopensystemslab/planx-new/actions/runs/4263869878/jobs/7421162534
> fix: staging  database sync

- scripts/seed-database/container.sh
Flagged as an issue here - https://trello.com/c/KeCs6vcw/2279-always-send-a-confirmation-email-to-the-user-when-the-application-has-been-submitted
> fix: Sync `teams.notify_personalisation` column to ensure emails work on Staging

- scripts/seed-database/container.sql
> fix: Add `teams.notify_personalisation` column to COPY

- editor.planx.uk/src/@planx/components/Pay/Public/Confirm.tsx
> feat: Add warning text to Pay component

- hasura.planx.uk/seeds/1595528762802_teams_and_users.sql
- Removes prior or inactive team members: Gunar, John, & Sarah
- Updates all seed emails to OSL emails (need to update this directly on prod/staging still for Ian to login successfully)
> chore: update seed users

- api.planx.uk/saveAndReturn/sendEmail.test.ts
- api.planx.uk/saveAndReturn/utils.ts
- api.planx.uk/tests/mocks/saveAndReturnMocks.js
Adds an explicit lookup for user session data
> fix: email query fix

- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
- editor.planx.uk/src/@planx/components/FindProperty/Public/Autocomplete.tsx
fixes address display for postcode ME7 1NH: https://1550.planx.pizza/medway/find-out-if-you-need-planning-permission/preview
relies on https://github.com/theopensystemslab/map/pull/275
> fix: display full addresses in autocomplete dropdown

- README.md
- docker-compose.yml
- package.json
- scripts/pullrequest/create.sh
**Current behavior**
- Postgres database re-seeded on each commit to an open PR
**Desired behavior**
- Postgres database only seeded when PR is opened
> fix: Stable Pizza databases

- editor.planx.uk/public/error.html
- infrastructure/application/index.ts
Adds a simple error page and updates the cloudflare config to use this page.
---
> feat: Add an error page

- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- api.planx.uk/send/createSendEvents.ts
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
Tidying up a bit of leftover logic that was missed when moving OneApp generation to `planx-core`
> fix: Uniform submission issue

- api.planx.uk/s3/uploadFile.ts
- docker-compose.local.yml
- package.json
Hit this issue when trying to deal with turning question buttons to radios, file upload was failing. Would appreciate if somebody could also test this out locally 👌
> fix: Minio S3 pathname

- .github/workflows/push-production.yml
- infrastructure/application/Pulumi.production.yaml
- infrastructure/data/Pulumi.production.yaml
Reverts theopensystemslab/planx-new#1591
Manually deploying the data layer failed on an unexpected permissions error. Reverting this PR as none of these values have been deployed successfully to the production layer.
> Revert "infra: rotate postgres root user and metabase roles on production"

- api.planx.uk/send/email.test.ts
- api.planx.uk/send/email.ts
- api.planx.uk/send/helpers.test.ts
- api.planx.uk/send/helpers.ts
- api.planx.uk/send/uniform.test.ts
- api.planx.uk/send/uniform.ts
- Add template files to sendToEmail zip files
- Runs skipped sendToEmail tests
I've ended up with a bit of a dependency chain here because of a few things I've picked up along the way and tried to resolve atomically. Before merging this we'll need to merge...
> feat: Send template files to email

- api.planx.uk/helpers.ts
- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- api.planx.uk/server.ts
Reverts theopensystemslab/planx-new#1630
> Revert "chore: Update passport to v0.6.0"

- api.planx.uk/inviteToPay/sendPaymentEmail.test.ts
- api.planx.uk/inviteToPay/sendPaymentEmail.ts
- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- api.planx.uk/saveAndReturn/utils.ts
- api.planx.uk/tests/mocks/inviteToPayData.ts
- api.planx.uk/tests/mocks/inviteToPayMocks.ts
- api.planx.uk/types.ts
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
- editor.planx.uk/src/@planx/components/Pay/Public/InviteToPayForm.tsx
- editor.planx.uk/src/pages/Pay/MakePayment.tsx
- scripts/seed-database/container.sh
| Agent Email | Nominee Email |
| ![image](https://user-images.githubusercontent.com/20502206/232530073-b60316fc-a74f-42e5-8259-d34b51d2b852.png) | ![image](https://user-images.githubusercontent.com/20502206/232529745-3f1fdc42-2d31-47f8-b51c-f1de874fd22c.png) |
Relies on - 
- https://github.com/theopensystemslab/planx-core/pull/16
- https://github.com/theopensystemslab/planx-core/pull/17
> feat: Populate ITP email templates

- .github/workflows/pull-request.yml
This should have been included in https://github.com/theopensystemslab/planx-new/pull/1625
> chore(ci): Remove failure notification from pull request action

- editor.planx.uk/src/pages/Pay/InviteToPay.tsx
- editor.planx.uk/src/pages/Pay/MakePayment.tsx
- editor.planx.uk/src/theme.ts
- editor.planx.uk/src/ui/Banner.tsx
- editor.planx.uk/src/ui/DescriptionList.tsx
**Link:** https://1669.planx.pizza/buckinghamshire/invite-to-pay-test/pay/invite?paymentRequestId=ba1b0073-1b0d-4082-9d75-08c1ca882943
**Link:** https://1669.planx.pizza/buckinghamshire/invite-to-pay-test/pay?paymentRequestId=ba1b0073-1b0d-4082-9d75-08c1ca882943
> fix: ITP styling and layout

- e2e/src/pay.spec.ts
- editor.planx.uk/src/@planx/components/Pay/Public/Confirm.tsx
- editor.planx.uk/src/@planx/components/Pay/Public/InviteToPayForm.tsx
- editor.planx.uk/src/@planx/components/Pay/Public/Pay.test.tsx
- editor.planx.uk/src/@planx/components/Pay/Public/Pay.tsx
> fix: style Pay page toggles as secondary buttons

- api.planx.uk/.eslintrc
- api.planx.uk/inviteToPay/inviteToPay.ts
- api.planx.uk/inviteToPay/sendPaymentEmail.ts
- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- api.planx.uk/saveAndReturn/resumeApplication.ts
- api.planx.uk/saveAndReturn/utils.ts
- api.planx.uk/saveAndReturn/validateSession.ts
- api.planx.uk/tests/mocks/inviteToPayData.ts
- api.planx.uk/tsconfig.json
- e2e/package.json
- e2e/pnpm-lock.yaml
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
- editor.planx.uk/src/@planx/components/Pay/Public/InviteToPayForm.tsx
- editor.planx.uk/src/@planx/components/Send/bops/__tests__/applicationType.test.ts
- editor.planx.uk/src/pages/Pay/InviteToPay.tsx
- editor.planx.uk/src/pages/Pay/MakePayment.tsx
- editor.planx.uk/src/routes/pay.tsx
Updates planx-core and imports to work with [@theopensystemslab/planx-core#15](https://github.com/theopensystemslab/planx-core/pull/15)
> chore: update planx-core

- .github/workflows/pull-request.yml
- e2e/.eslintrc
- e2e/README.md
- e2e/package.json
- e2e/pnpm-lock.yaml
- e2e/src/context.ts
- e2e/src/create-flow.spec.ts
- e2e/src/flows/sections-flow.ts
- e2e/src/helpers.ts
- e2e/src/login.spec.ts
- e2e/src/pay.spec.ts
- e2e/src/save-and-return.spec.ts
- e2e/src/sections.spec.ts
- e2e/tsconfig.json
Updates to planx-core required some updates to e2e tests which was also an opportunity for a tidy-up of the typechecking which was failing. I've added code checks to the CI workflow and fixed broken typing issues. I also did a small refactor to share code while adding some tests for sections.
In the process, I found some tests that were not set-up correctly and should actually be failing. I've skipped them out in this PR so I can fix them in the next (to avoid too big a change).
> chore: update e2e tests and add initial tests for sections

- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- e2e/package.json
- e2e/pnpm-lock.yaml
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
Version bump to pick up https://github.com/theopensystemslab/planx-core/pull/27
> chore: Bump planx-core version

- api.planx.uk/inviteToPay/inviteToPay.ts
Make error cause more discoverable.
> chore: make error causes more visible in invite-to-pay

- editor.planx.uk/src/@planx/components/Pay/Public/Confirm.tsx
- editor.planx.uk/src/@planx/components/Pay/Public/InviteToPayForm.tsx
- editor.planx.uk/src/@planx/components/Pay/Public/Pay.test.tsx
> feat: Add `SaveResumeButton` to pay component

- editor.planx.uk/src/@planx/components/Section/Public.tsx
should fix failed React build on staging deploy https://github.com/theopensystemslab/planx-new/actions/runs/4948901909
> fix: remove useEffect in Section now that feature flag is removed

- api.planx.uk/saveAndReturn/utils.ts
> fix: Handle empty project types

- editor.planx.uk/src/@planx/components/FileUpload/Public.tsx
- editor.planx.uk/src/@planx/components/FindProperty/Public/Autocomplete.tsx
- editor.planx.uk/src/@planx/components/Notice/Public.tsx
- editor.planx.uk/src/@planx/components/Result/Public/ResultReason.tsx
- editor.planx.uk/src/@planx/components/shared/Buttons/ImageButton.tsx
- editor.planx.uk/src/@planx/components/shared/PermissionSelect.tsx
- editor.planx.uk/src/@planx/components/shared/Preview/MoreInfoSection.tsx
- editor.planx.uk/src/@planx/components/shared/Preview/QuestionHeader.tsx
- editor.planx.uk/src/@planx/components/shared/Preview/SaveResumeButton.tsx
- editor.planx.uk/src/@planx/components/shared/Preview/SummaryList.tsx
- editor.planx.uk/src/components/Footer.tsx
- editor.planx.uk/src/components/Header.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Settings/index.tsx
- editor.planx.uk/src/pages/FlowEditor/components/forms/FormModal.tsx
- editor.planx.uk/src/pages/Preview/Questions.tsx
- editor.planx.uk/src/pages/Team.tsx
- editor.planx.uk/src/pages/Teams.tsx
- editor.planx.uk/src/theme.ts
- editor.planx.uk/src/ui/DateInput.tsx
- editor.planx.uk/src/ui/ErrorWrapper.tsx
- editor.planx.uk/src/ui/Input.tsx
- editor.planx.uk/src/ui/InputRow.tsx
- editor.planx.uk/src/ui/ListManager.tsx
- editor.planx.uk/src/ui/NumberedList.tsx
- editor.planx.uk/src/ui/SelectInput.tsx
Font size update across theme file (alt theme used).
Font weight update across component files.
> update: all font sizes

- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
https://github.com/theopensystemslab/planx-document-templates/pull/18
> chore: bump planx-document-templates commit to include static maps

- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- api.planx.uk/tests/mocks/inviteToPayData.ts
Points at this change - https://github.com/theopensystemslab/planx-core/pull/36
Test to see if payment validation step on complex flow is leading to timeouts / memory issues.
> chore: Bump planx-core to test validation skip

- editor.planx.uk/src/components/Header.tsx
Fix for visual regression introduced in #1740
> fix: Header link style

- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- e2e/package.json
- e2e/pnpm-lock.yaml
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
Hadn't appreciated I'd missed this step - this should now pull the `section_name` change in as well as a few other commits.
> chore: Bump `planx-core`

- editor.planx.uk/src/@planx/components/MultipleFileUpload/Public.tsx
- editor.planx.uk/src/@planx/components/shared/PrivateFileUpload/Dropzone.tsx
- editor.planx.uk/src/@planx/components/shared/PrivateFileUpload/PrivateFileUpload.tsx
- editor.planx.uk/src/@planx/components/shared/PrivateFileUpload/UploadedFileCard.tsx
> feat: Style `UploadedFileCard` and `Dropzone`

- editor.planx.uk/src/@planx/components/Result/Public/ResultReason.tsx
- editor.planx.uk/src/@planx/components/shared/Preview/SimpleExpand.tsx
- editor.planx.uk/src/theme.ts
- editor.planx.uk/src/ui/ExpandableList.tsx
- editor.planx.uk/src/ui/icons/Caret.tsx
PR is forked from / dependent on **update: mobile UI tidy up** - https://github.com/theopensystemslab/planx-new/pull/1648
Updates styling for generic accordion and results accordion.
> update: accordion and result styling

- infrastructure/application/index.ts
An attempt at smoothing out the submission process in the short / medium term.
> chore: Increase API Fargate memory

- editor.planx.uk/src/@planx/components/FindProperty/Editor.tsx
- editor.planx.uk/src/@planx/components/FindProperty/Public/Map.tsx
- editor.planx.uk/src/@planx/components/FindProperty/Public/Public.test.tsx
- editor.planx.uk/src/@planx/components/FindProperty/Public/index.tsx
- editor.planx.uk/src/@planx/components/FindProperty/model.ts
> feat: Make new property label editable

- editor.planx.uk/src/ui/ListManager.tsx
> feat: Styled `ListManager`

- editor.planx.uk/src/@planx/components/MultipleFileUpload/Modal.tsx
- editor.planx.uk/src/@planx/components/MultipleFileUpload/Public.tsx
- editor.planx.uk/src/@planx/components/shared/PrivateFileUpload/Dropzone.tsx
- editor.planx.uk/src/ui/icons/MoreInfo.tsx
A first pass of styling for multiple file upload.
Example screenshots to follow (left: current, right: updated)
> UPDATE: first pass of multiple file styling

- editor.planx.uk/src/pages/Preview/ReconciliationPage.tsx
> feat: Styled `ReconciliationPage`

- editor.planx.uk/src/pages/FlowEditor/components/forms/FormModal.tsx
> feat: Styled `FormModal`

- editor.planx.uk/src/pages/FlowEditor/index.tsx
> feat: Styled `FlowEditor`

- editor.planx.uk/src/pages/Teams.tsx
> feat: Styled `Teams`

- editor.planx.uk/src/@planx/components/shared/Preview/Card.tsx
> feat: Styled `Card`

- editor.planx.uk/src/@planx/components/shared/Buttons/ButtonBase.tsx
- editor.planx.uk/src/ui/Checkbox.tsx
- editor.planx.uk/src/ui/ChecklistItem.tsx
> feat: Styled `ButtonBase`

- editor.planx.uk/src/pages/FlowEditor/components/PreviewBrowser.tsx
> feat: Styled `PreviewBrowser`

- editor.planx.uk/src/@planx/components/Confirmation/Public.tsx
> feat: Styled `Confirmation`

- editor.planx.uk/src/components/DelayedLoadingIndicator.tsx
> feat: Styled `DelayedLoadingIndicator`

- editor.planx.uk/src/@planx/components/Result/Public/ResultReason.tsx
> feat: Styled `ResultReason`

- editor.planx.uk/src/pages/Preview/ContentPage.tsx
> feat: Styled `ContentPage`

- editor.planx.uk/src/ui/InputRowLabel.tsx
> feat: Styled `InputRowLabel`

- editor.planx.uk/src/@planx/components/FileUploadAndLabel/Public.tsx
- editor.planx.uk/src/pages/FlowEditor/lib/analyticsProvider.tsx
- Add analytics metadata each time the help text on a fileType is clicked
> feat: Granular MFU analytics

- editor.planx.uk/src/@planx/components/Pay/Public/InviteToPayForm.tsx
- editor.planx.uk/src/pages/Pay/InviteToPay.tsx
> feat: Add 'Start new application' option on ITP page

- editor.planx.uk/src/@planx/components/PlanningConstraints/Public.tsx
- editor.planx.uk/src/@planx/components/Result/Public/index.tsx
- editor.planx.uk/src/@planx/components/shared/Preview/SimpleExpand.tsx
- editor.planx.uk/src/ui/icons/Caret.tsx
Bonus - tackling an outstanding a11y issue with this component.
> feat: Styled `SimpleExpand` & `Caret`

- editor.planx.uk/src/@planx/components/Result/Public/ResultReason.tsx
- editor.planx.uk/src/@planx/components/Result/Public/ResultSummary.tsx
- editor.planx.uk/src/@planx/components/shared/FeedbackInput.tsx
- editor.planx.uk/src/@planx/components/shared/Preview/Card.tsx
> UPDATE: result reason styling

- .github/dependabot.yml
> feat: Setup dependabot

- editor.planx.uk/src/pages/Login.tsx
- editor.planx.uk/src/theme.ts
PR adds a styled login screen.
Also updates default theme colour to #0010A4
> feat: Login screen style update

- editor.planx.uk/src/ui/ExpandableList.tsx
> feat: Styled `ExpandableList`

- hasura.planx.uk/package.json
- hasura.planx.uk/pnpm-lock.yaml
Closes https://github.com/theopensystemslab/planx-new/pull/1920
> chore: Update Hasura CLI

- editor.planx.uk/src/pages/ErrorPage.stories.tsx
- editor.planx.uk/src/pages/Login.stories.tsx
- editor.planx.uk/src/pages/Pay/InviteToPay.stories.tsx
- editor.planx.uk/src/pages/Preview/ResumePage.stories.tsx
- editor.planx.uk/src/pages/Preview/ResumePage.tsx
- editor.planx.uk/src/pages/Preview/SaveAndReturn.stories.tsx
- editor.planx.uk/src/pages/Preview/SavePage.stories.tsx
- editor.planx.uk/src/pages/Preview/SavePage.tsx
We haven't captured "pages" at all in previous iterations of Storybook - but feels like a useful area to try to get some coverage. "Pages" will cover custom page layouts/templates associated with Save & Return, Resume, Reconciliation, Invite to Pay and other journeys.
> chore: update Storybook [Design System / Pages]

- editor.planx.uk/src/ui/ChecklistItem.tsx
| Pizza | Staging |
| ![image](https://github.com/theopensystemslab/planx-new/assets/20502206/6e95dbbb-9447-4312-85d5-1a9917fe0377) | ![image](https://github.com/theopensystemslab/planx-new/assets/20502206/3ff6e4cf-1348-4a14-a9c0-013d79a61750) |
| [Storybook](https://storybook.2008.planx.pizza/?path=/docs/design-system-atoms-form-elements-checklistitem--docs) | [Storybook](https://storybook.planx.dev/?path=/docs/design-system-atoms-form-elements-checklistitem--docs&globals=backgrounds.grid:!false) |
> feat: Styled `ChecklistItem`

- editor.planx.uk/src/ui/InputField.tsx
| Pizza | Staging |
|![image](https://github.com/theopensystemslab/planx-new/assets/20502206/2e2cd0ce-a54d-4ec3-b76f-7ec3889ce29c)|![image](https://github.com/theopensystemslab/planx-new/assets/20502206/e4501eac-03aa-438d-9348-56d5b270a799)|
| [Storybook](https://storybook.2012.planx.pizza/?path=/docs/design-system-atoms-form-elements-inputfield--docs) | [Storybook](https://storybook.planx.dev/?path=/docs/design-system-atoms-form-elements-inputfield--docs) |
> feat: Styled `InputField`

- editor.planx.uk/src/@planx/components/Checklist/Editor.tsx
- editor.planx.uk/src/@planx/components/Question/Editor.tsx
- editor.planx.uk/src/ui/InputGroup.tsx
The majority of the logic of this component is either -  
- Superseded by `ListManager`
- Only used on Settings > Flags (dummy component)
I'd actually vote for removing / dramatically simplifying most of the components used on the Settings tab 🗑️ 
Zero rush to get to this one, but let's talk about it on a dev call!
> feat: Styled `InputGroup`

- editor.planx.uk/src/ui/DateInput.tsx
| Pizza | Staging |
|![image](https://github.com/theopensystemslab/planx-new/assets/20502206/b455c741-f35e-40d2-a067-3dcb8f6e2ea4)|![image](https://github.com/theopensystemslab/planx-new/assets/20502206/4536bf2c-9b3c-4838-9fcd-ae84bd6cb171)|
| ![image](https://github.com/theopensystemslab/planx-new/assets/20502206/4a78df27-f616-4e47-b4f1-18b02ba941ae)| ![image](https://github.com/theopensystemslab/planx-new/assets/20502206/eb603df8-7f43-4ad4-97af-5c64fcc10112) |
| [Storybook](https://storybook.2010.planx.pizza/?path=/docs/planx-components-dateinput--docs) | [Storybook](https://storybook.planx.dev/?path=/docs/planx-components-dateinput--docs) |
> feat: Styled `DateInput`

- infrastructure/application/index.ts
- infrastructure/application/services/hasura.ts
Reverts theopensystemslab/planx-new#2018
> Revert "chore: Revert proxy via CloudFlare [skip pizza]"

- infrastructure/application/index.ts
- infrastructure/application/services/hasura.ts
Hopefully not needed, but getting PR ready for quick revert tomorrow morning if certificates don't resolve overnight.
> chore: Revert proxy via CloudFlare

- infrastructure/application/index.ts
- infrastructure/application/services/hasura.ts
Reverts theopensystemslab/planx-new#2034
Trying again - this time we'll delete any pre-existing Advanced Certificates in Cloudflare before merging/deploying to try to replicate the starting state when we had a quick validation cycle a couple days ago in testing.
> Revert "chore: Revert proxy via CloudFlare"

- e2e/package.json
- e2e/pnpm-lock.yaml
- e2e/tests/api-driven/src/client.ts
- e2e/tests/api-driven/src/invite-to-pay/helpers.ts
- e2e/tests/api-driven/src/invite-to-pay/steps.ts
- e2e/tests/ui-driven/src/context.ts
- e2e/tests/ui-driven/src/create-flow.spec.ts
- e2e/tests/ui-driven/src/helpers.ts
- e2e/tests/ui-driven/src/invite-to-pay/agent.spec.ts
- e2e/tests/ui-driven/src/invite-to-pay/helpers.ts
- e2e/tests/ui-driven/src/invite-to-pay/nominee.spec.ts
- e2e/tests/ui-driven/src/login.spec.ts
- e2e/tests/ui-driven/src/pay.spec.ts
- e2e/tests/ui-driven/src/sections.spec.ts
- e2e/tests/ui-driven/src/utils.ts
Replaces https://github.com/theopensystemslab/planx-new/pull/2025 and runs `pnpm lint:fix` in `/e2e`
> chore(e2e): Bump prettier to v3

- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- e2e/tests/api-driven/package.json
- e2e/tests/api-driven/pnpm-lock.yaml
- e2e/tests/ui-driven/package.json
- e2e/tests/ui-driven/pnpm-lock.yaml
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
Currently facing this issue with CI / dependabot which this may resolve... https://github.com/npm/cli/issues/2610
> chore: Change format of GitHub hosted dependencies

- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- e2e/tests/api-driven/package.json
- e2e/tests/api-driven/pnpm-lock.yaml
- e2e/tests/ui-driven/package.json
- e2e/tests/ui-driven/pnpm-lock.yaml
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
> chore: GitHub dependencies format

- api.planx.uk/.gitconfig
- api.planx.uk/Dockerfile
> chore: Add `.gitconfig` to Docker

- editor.planx.uk/src/@planx/components/Notice/Public.tsx
- editor.planx.uk/src/@planx/components/Question/Public/Question.tsx
- editor.planx.uk/src/theme.ts
Outstanding tidy up from https://github.com/theopensystemslab/planx-new/pull/1963
Quick, manually created, PR to sense check failing CI (React tests) on dependabot created PRs.
> fix: Correct `useTheme()` import

- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- e2e/tests/api-driven/package.json
- e2e/tests/api-driven/pnpm-lock.yaml
- e2e/tests/ui-driven/package.json
- e2e/tests/ui-driven/pnpm-lock.yaml
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
- editor.planx.uk/src/@planx/components/PlanningConstraints/Public.tsx
See https://github.com/theopensystemslab/planx-core/pull/98 for more context
> fix: Handle constraints errors more gracefully

- .github/workflows/push-main.yml
- .github/workflows/regression-tests.yml
Missed these action when updating others - https://github.com/theopensystemslab/planx-new/pull/2112/files
> chore: Setup `.gitconfig` in "Regression Tests" and "Pulumi (Deploy Staging)" actions

- README.md
Can't re-create MUI react build error locally or on original branch, seeing if this inconsequential change branched from `main` succeeds
https://github.com/theopensystemslab/planx-new/actions/runs/5940138267/job/16108302587
> test: staging deploy

- scripts/seed-database/container.sh
> chore(ci): Tidy up `sync.sql` when job is complete

- infrastructure/application/Pulumi.staging.yaml
- infrastructure/data/Pulumi.staging.yaml
Retry of https://github.com/theopensystemslab/planx-new/pull/2089 which didn't rotate metabase in same go
> chore: rotate staging `data:db-password` & `application:metabasePgPassword`

- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- e2e/tests/api-driven/package.json
- e2e/tests/api-driven/pnpm-lock.yaml
- e2e/tests/ui-driven/package.json
- e2e/tests/ui-driven/pnpm-lock.yaml
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
Picks up https://github.com/theopensystemslab/planx-core/pull/121
> chore: bump planx-core to pick up BOPS & CSV export fixes

- api.planx.uk/modules/auth/service.ts
- editor.planx.uk/src/lib/dataMergedHotfix.ts
- editor.planx.uk/src/lib/graphql.ts
- editor.planx.uk/src/lib/lowcalStorage.ts
- editor.planx.uk/src/pages/FlowEditor/lib/analyticsProvider.tsx
- editor.planx.uk/src/pages/FlowEditor/lib/store/editor.ts
- editor.planx.uk/src/pages/Team.tsx
- editor.planx.uk/src/routes/pay.tsx
- editor.planx.uk/src/routes/settings.tsx
- editor.planx.uk/src/routes/utils.ts
- editor.planx.uk/src/routes/views/published.tsx
- editor.planx.uk/src/routes/views/standalone.tsx
- editor.planx.uk/src/routes/views/unpublished.tsx
Please see https://github.com/theopensystemslab/planx-new/pull/2190 and https://github.com/theopensystemslab/planx-new/pull/2182#discussion_r1312254263 for context.
This PR introduces the following change - 
- Explicitly use a `publicClient` - this means that the `public` role will be used for these requests
> feat: Explicitly use `publicClient` in frontend

- editor.planx.uk/src/airbrake.test.ts
- editor.planx.uk/src/airbrake.ts
Please see https://github.com/theopensystemslab/planx-new/security/code-scanning/2
> fix: Incomplete URL substring sanitation

- doc/how-to/how-to-setup-custom-subdomains.md
Follow on action from https://github.com/theopensystemslab/planx-new/pull/2227
> doc: Update subdomain creation steps

- api.planx.uk/modules/team/docs.yaml
> docs: Include details on WARP for API endpoints

- e2e/tests/ui-driven/package.json
- e2e/tests/ui-driven/pnpm-lock.yaml
Fixed in other api-tests here - https://github.com/theopensystemslab/planx-new/pull/2230
> chore(e2e): Resolve CVE-2023-26144 in `/e2e/ui-driven`

- editor.planx.uk/src/@planx/components/FileUploadAndLabel/Modal.tsx
Changes copy in upload + label component as advised by UR / content design (Nomensa).
> feat: Update upload label text [skip pizza]

- api.planx.uk/modules/webhooks/docs.yaml
- api.planx.uk/modules/webhooks/service/sendNotification/index.test.ts
- api.planx.uk/modules/webhooks/service/sendNotification/index.ts
- api.planx.uk/modules/webhooks/service/sendNotification/schema.ts
Fixes type issue introduced in https://github.com/theopensystemslab/planx-new/pull/2251
Thread (OSL Slack): https://opensystemslab.slack.com/archives/C0405SQDP8B/p1696877952620659
> fix: BOPS payload type for Slack messages

- editor.planx.uk/src/@planx/components/Checklist/Public.tsx
- editor.planx.uk/src/@planx/components/NextSteps/Public.tsx
- editor.planx.uk/src/@planx/components/shared/index.ts
- editor.planx.uk/src/pages/FlowEditor/lib/analyticsProvider.tsx
- editor.planx.uk/src/pages/Preview/StatusPage.tsx
- editor.planx.uk/src/ui/NextStepsList.tsx
Been meaning to turn my eyes to this one for a while, most recently flagged here - https://github.com/theopensystemslab/planx-new/pull/2314#issuecomment-1766285974
> fix: Unique key for `FormWrapper` in `ChecklistComponent`

- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- e2e/tests/api-driven/package.json
- e2e/tests/api-driven/pnpm-lock.yaml
- e2e/tests/ui-driven/package.json
- e2e/tests/ui-driven/pnpm-lock.yaml
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
Prior art - https://github.com/theopensystemslab/planx-new/pull/2330
Please see https://github.com/theopensystemslab/planx-core/pull/165 for context!
> fix: Update `planx-core` to fix TypeScript compilation

- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- e2e/tests/api-driven/package.json
- e2e/tests/api-driven/pnpm-lock.yaml
- e2e/tests/ui-driven/package.json
- e2e/tests/ui-driven/pnpm-lock.yaml
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
> chore: bump planx-core

- editor.planx.uk/src/airbrake.ts
- editor.planx.uk/src/routes/utils.ts
Draft until St.Albans are pointing to our CDN
> chore: Add St.Albans subdomain to frontend

- hasura.planx.uk/metadata/tables.yaml
Fix for bug introduced here - https://github.com/theopensystemslab/planx-new/pull/2438/files
Caught by Airbrake here - https://planx.airbrake.io/projects/329753/groups/3675812447178036881
> fix: Grant select permission to `submitted_at`

- hasura.planx.uk/metadata/tables.yaml
- hasura.planx.uk/migrations/1700671079904_create_analytics_summary_view/down.sql
- hasura.planx.uk/migrations/1700671079904_create_analytics_summary_view/up.sql
Trying this again with a fresh migration created off of main now :crossed_fingers: see notes on original PR failure here https://github.com/theopensystemslab/planx-new/pull/2472
> feat: create an `analytics_summary` database view for analytics (take two) 

- hasura.planx.uk/metadata/tables.yaml
I need a sticky note or something on my monitor... keep falling for this one...! 🤦
> fix: Grant api role access to `user.is_staging_only` column

- scripts/seed-database/write/users.sql
Please see https://github.com/theopensystemslab/planx-new/pull/2530 and https://github.com/theopensystemslab/planx-new/pull/2530#discussion_r1415127007 for context.
`pnpm test-sync` ran locally multiple times successfully ✅
> chore: Sync new `users.is_staging_only` column

- editor.planx.uk/src/@planx/components/TextInput/Editor.tsx
- editor.planx.uk/src/@planx/components/TextInput/Public.tsx
- editor.planx.uk/src/@planx/components/TextInput/TextInput.stories.tsx
- editor.planx.uk/src/@planx/components/TextInput/model.ts
- editor.planx.uk/src/ui/Radio.tsx
- Adds a new input type, which allows 500 characters to be inputted
> feat: Add extra long text input (500 characters)

- api.planx.uk/modules/gis/service/local_authorities/metadata/birmingham.ts
Adds outstanding variable from #2524
> chore: add outstanding Birmingham A4

- editor.planx.uk/.eslintrc
Been meaning to fix this for a while, current behaviour ends up being pretty painful when developing!
> chore: Don't error on unused vars in Editor

- e2e/tests/ui-driven/src/create-flow/create-flow.spec.ts
Context - this is blocking progress on https://github.com/theopensystemslab/planx-new/pull/2575
Spent a good chunk of time here, will progress the other fix and come back to revisit this 👌
> chore: Temp skip of two E2E tests

- editor.planx.uk/src/@planx/components/Calculate/Public.tsx
- editor.planx.uk/src/@planx/components/Calculate/logic.test.ts
- editor.planx.uk/src/lib/graphql.ts
A few files which have been missed along the way - possibly due to mismatched eslint versions locally on dev machines?
> chore: Run `pnpm lint:fix` in `editor.planx.uk`

- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- e2e/tests/api-driven/package.json
- e2e/tests/api-driven/pnpm-lock.yaml
- e2e/tests/ui-driven/package.json
- e2e/tests/ui-driven/pnpm-lock.yaml
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
✅ Regression tests passing against branch here - https://github.com/theopensystemslab/planx-new/actions/runs/7396684356
> fix(e2e): Update `planx-core` to resolve failing test

- api.planx.uk/modules/gis/service/digitalLand.ts
- api.planx.uk/modules/gis/service/local_authorities/metadata/barnet.ts
> feat: Hook up granular A4 GIS API variables for Barnet

- e2e/tests/ui-driven/src/create-flow/create-flow.spec.ts
Reverts theopensystemslab/planx-new#2589
✅  Regression tests passing on this branch - https://github.com/theopensystemslab/planx-new/actions/runs/7462358187
> Revert "chore: Temp skip of two E2E tests"

- scripts/seed-database/write/team_themes.sql
Fixes data sync issue on the `team_themes` table
> fix: Sync `team_id` on `team_themes` table

- editor.planx.uk/src/pages/FlowEditor/components/Settings/DesignSettings/ButtonForm.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Settings/DesignSettings/FaviconForm.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Settings/DesignSettings/TextLinkForm.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Settings/DesignSettings/ThemeAndLogoForm.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Settings/DesignSettings/index.tsx
- Refactors shared from logic across `DesignSettings`' child components
- Creates a shared `FormikConfig<TeamTheme>` which is passed into child components
> chore: Refactor repeated form logic in `DesignSettings`

- api.planx.uk/server.ts
Please see https://opensystemslab.slack.com/archives/C4B0CKQ3U/p1705786942766949 for context - this is just additional logging to help troubleshoot this one.
> chore: Additional logging of CORS errors

- editor.planx.uk/src/@planx/components/Send/Editor.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Settings/DesignSettings/ButtonForm.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Settings/DesignSettings/FaviconForm.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Settings/DesignSettings/TextLinkForm.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Settings/DesignSettings/ThemeAndLogoForm.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Settings/DesignSettings/index.tsx
- editor.planx.uk/src/theme.ts
- editor.planx.uk/src/themeOverrides.d.ts
- editor.planx.uk/src/ui/editor/ImgInput.tsx
- editor.planx.uk/src/ui/shared/PublicFileUploadButton.tsx
- Addresses feedback here https://github.com/theopensystemslab/planx-new/pull/2685#issuecomment-1903697762. Updating a form section will only update the `Partial<TeamTheme>` fields related to the specific form section.
- Also - runs `pnpm lint:fix` - a few of these I think have been missed in merge conflicts or through me not running `pnpm i` after minor eslint updates when working on team theme branches.
> fix: Design settings - custom `onSubmit()` functions

- editor.planx.uk/src/lib/featureFlags.ts
> fix: Correct case for `FeatureFlag` type

- scripts/seed-database/container.sh
- scripts/seed-database/write/team_integrations.sql
Final step of the tasks outlined here - https://github.com/theopensystemslab/planx-new/pull/2703
Tested locally with `pnpm test-sync` ✅
> chore: Sync new `staging_bops_secret` column

- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- e2e/tests/api-driven/package.json
- e2e/tests/api-driven/pnpm-lock.yaml
- e2e/tests/api-driven/src/globalHelpers.ts
- e2e/tests/ui-driven/package.json
- e2e/tests/ui-driven/pnpm-lock.yaml
- e2e/tests/ui-driven/src/context.ts
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
Updates to pick up changes in https://github.com/theopensystemslab/planx-core/pull/283
> chore: Update `planx-core`

- editor.planx.uk/src/ui/public/FeedbackOption.tsx
Quick follow on to https://github.com/theopensystemslab/planx-new/pull/2722
> fix: Don't forward `showArrow` prop to MUI button

- editor.planx.uk/src/components/Feedback/MoreInfoFeedback.tsx
- editor.planx.uk/src/components/Feedback/index.tsx
- editor.planx.uk/src/ui/public/FeedbackDisclaimer.tsx
- Replace lorem ipsum thank you copy with a sensible placeholder
- Link to PlanX privacy policy in feedback disclaimer
- More realistic content for PO testing
https://github.com/theopensystemslab/planx-new/assets/36415632/a657f8f4-66f2-453c-8693-4d11a0c87935
> chore: update feedback placeholder content for PO testing

- editor.planx.uk/src/lib/featureFlags.ts
- editor.planx.uk/src/pages/FlowEditor/components/Settings/DesignSettings/index.tsx
Testing notes here - https://docs.google.com/document/d/1aocM_ri3LctK3obQCl53nhYbaELZ3I7rcY5e3eIfpRo/edit?usp=sharing
Ticket currently in "To be tested by POs" - will ask Silvia to draw attention to it, maybe alongside a video from @ianjon3s 👌
> chore: Drop `TEAM_SETTINGS` feature flag

- editor.planx.uk/src/pages/FlowEditor/components/Settings/ServiceSettings.tsx
- Quick follow up task to https://github.com/theopensystemslab/planx-new/pull/2689 to make Flow Settings UI more consistent
- Disables form if not dirty
- Enables "Update" when form dirty
- Opens MUI snackbar / alert on save
https://github.com/theopensystemslab/planx-new/assets/20502206/a982773e-a366-4af8-913c-aa8735d3dce5
> feat: Add snackbar for Flow Settings

- editor.planx.uk/src/pages/Team.tsx
No strong opinions here, just something to try out. A bit fed up of scrolling down so far to make a new service! 😅
> feat: Move add service button to top

- editor.planx.uk/src/components/Header.tsx
Follow on from #2774 - please see https://github.com/theopensystemslab/planx-new/pull/2774#discussion_r1485939159 for context.
> feat: Use MUI dialog for restart session

- scripts/seed-database/container.sh
- scripts/seed-database/write/team_integrations.sql
~~To be tested and merged once https://github.com/theopensystemslab/planx-new/pull/2776 has gone to production~~
Tested locally multiple times with `pnpm test-sync` and getting expected results now that the column has been added to production ✅
> chore: Update sync script for `team_integrations.has_planning_data`

- editor.planx.uk/src/components/Feedback/MoreInfoFeedback.tsx
- editor.planx.uk/src/components/Feedback/index.tsx
- editor.planx.uk/src/ui/public/FeedbackDisclaimer.tsx
As per: https://trello.com/c/xdTl65RD/1533-create-content-for-new-feedback-component
- Update copy in the feedback disclaimer
- Update the "thank you" content
> chore: update feedback copy

- editor.planx.uk/src/components/Feedback/FeedbackForm.test.tsx
- editor.planx.uk/src/components/Feedback/MoreInfoFeedback.test.tsx
- Testing the `FeedbackForm` component functionality and accessibility
- Refactor `MoreInfoFeedback.test.tsx` as per feedback
- Increasing test coverage
> test: add basic tests for the FeedbackForm component

- api.planx.uk/modules/gis/service/digitalLand.ts
- api.planx.uk/modules/gis/service/local_authorities/metadata/gateshead.ts
- api.planx.uk/modules/gis/service/local_authorities/metadata/tewkesbury.ts
See thread https://opensystemslab.slack.com/archives/C5Q59R3HB/p1708370584385399
> chore: return granular A4 variables for Tewkesbury and Gateshead

- editor.planx.uk/src/airbrake.ts
- editor.planx.uk/src/routes/utils.ts
- As per  [step 10 of subdomain setup guide](https://github.com/theopensystemslab/planx-new/blob/main/doc/how-to/how-to-setup-custom-subdomains.md)
> infra: point application to new westberks domain

- api.planx.uk/modules/saveAndReturn/controller.ts
- api.planx.uk/modules/saveAndReturn/routes.ts
- api.planx.uk/modules/saveAndReturn/service/validateSession.ts
- api.planx.uk/modules/saveAndReturn/types.ts
Small issue/tidy up I hit whilst working on another ticket. It's not actually a breaking problem but I'm trying to just rule this out as an issue elsewhere.
Zero functional changes, just moving types to their own file and then importing from there 👍
> chore: Remove circular dependency in `saveAndReturn` module

- editor.planx.uk/src/components/Feedback/index.test.tsx
- Add functionality / accessibility tests for the Feedback component
- Expanding test coverage
> test: add tests for Feedback component

- editor.planx.uk/src/pages/FlowEditor/lib/analyticsProvider.tsx
- Allow list values not set as the explicit `fn` or `val` of a node are not correctly captured
- This is an issue as some nodes set multiple values internally which we want to capture
- Scans breadcrumbs for allow list values instead of node
- This ensures we capture all allow list values - those set by Editors, and those set internally by nodes
Currently this needs to be tested manually - see screenshot above.
I'm not exactly sure the best way of testing this as there's no existing framework. We could set this up for analytics in E2E tests but ideally we'd find a lighter weight way of testing this in the frontend. In order to move this forward I've slightly swerved this issue for now.
> fix: Read allow list values from breadcrumbs not flow

- hasura.planx.uk/migrations/1709208323190_run_sql_migration/down.sql
- hasura.planx.uk/migrations/1709208323190_run_sql_migration/up.sql
- Adds `allow_list_answers` to the `analytics_summary` view
- Adds unfolded result columns to the `analytics_summary` view
> chore: Add `allow_list_answers` column to `analytics_summary`  view

- api.planx.uk/helpers.ts
- editor.planx.uk/src/pages/FlowEditor/components/PreviewBrowser.tsx
Plus a few type / component tidy ups ! 
**Before**
**After**
> chore: map user ids to names on publish change dialog for nested flows

- editor.planx.uk/src/@planx/components/Result/Public/index.tsx
See suggestion from Hannah here - https://trello.com/c/Iu2nNd8v/2549-change-wording-of-titles-on-result-page
> chore: Update copy on result page 

- editor.planx.uk/src/@planx/components/Calculate/Editor.tsx
- editor.planx.uk/src/@planx/components/Calculate/model.ts
- editor.planx.uk/src/pages/FlowEditor/components/Flow/components/Node.tsx
- Adds an optional "title" field to the `Calculate` component
> feat: Add title to calculate component

- infrastructure/application/Pulumi.staging.yaml
> chore: Update Gloucester GovPay token (staging)

- hasura.planx.uk/migrations/1710409167587_alter_view_submission_services_summary_json_keys_to_camel_case/down.sql
- hasura.planx.uk/migrations/1710409167587_alter_view_submission_services_summary_json_keys_to_camel_case/up.sql
- Update the JSON objects in the view to have camel case keys
- Avoid case mismatches with types in the FE
> chore: update view JSON object keys to camel case

- editor.planx.uk/src/@planx/components/PlanningConstraints/Editor.tsx
- editor.planx.uk/src/@planx/components/PlanningConstraints/PlanningConstraints.stories.tsx
- editor.planx.uk/src/@planx/components/PlanningConstraints/Public.test.tsx
- editor.planx.uk/src/@planx/components/PlanningConstraints/Public.tsx
- editor.planx.uk/src/@planx/components/PlanningConstraints/model.ts
> feat: add disclaimer to PlanningConstraints editor modal

- editor.planx.uk/src/pages/FlowEditor/components/Settings/Submissions/SubmissionsTable.stories.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Settings/Submissions/SubmissionsTable.test.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Settings/Submissions/SubmissionsTable.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Settings/Submissions/mocks.ts
- editor.planx.uk/src/pages/FlowEditor/components/Settings/Submissions/submissionData.ts
- Add a table for displaying application data
- Add mock data
- Add a basic story for viewing the table
- Add basic testing
- Incremental step towards the SubmissionView feature
> feat: SubmissionsTable component

- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
Rolling back change to Editor made here - https://github.com/theopensystemslab/planx-new/pull/2908
Pretty unsure if this is the fix, but it's worth merging to `main` to test, then we can at least rule this one out 👍
> fix(wip): Broken address search

- editor.planx.uk/src/@planx/components/Pay/Public/Confirm.tsx
- editor.planx.uk/src/@planx/components/Pay/Public/InviteToPayForm.tsx
| ![image](https://github.com/theopensystemslab/planx-new/assets/20502206/387ecbee-e0f1-4e46-b90c-16166188f02e) | ![image](https://github.com/theopensystemslab/planx-new/assets/20502206/594719f8-628b-43a5-95cd-0d77525f7027) |
> fix: Visual issue with underline on ITP button

- api.planx.uk/modules/pay/middleware.ts
- editor.planx.uk/src/@planx/components/Pay/Public/Pay.tsx
Fixes for this PR I hit when testing - https://github.com/theopensystemslab/planx-new/pull/2922
> fix: Better handling of default values for `GovPayMetadata`

- api.planx.uk/modules/team/controller.test.ts
- api.planx.uk/modules/team/controller.ts
Quick improvement of error message, see here for context - https://opensystemslab.slack.com/archives/C4B0CKQ3U/p1711542500843619 (OSL Slack)
> chore: Improve add member error message

- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- e2e/tests/api-driven/package.json
- e2e/tests/api-driven/pnpm-lock.yaml
- e2e/tests/ui-driven/package.json
- e2e/tests/ui-driven/pnpm-lock.yaml
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
Fixes schema validation issue for prod LDC - see https://github.com/theopensystemslab/planx-core/pull/338
> fix: bump planx-core

- editor.planx.uk/src/@planx/components/shared/PrivateFileUpload/UploadedFileCard.tsx
> fix: Add aria-label to progressbar

- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- e2e/tests/api-driven/package.json
- e2e/tests/api-driven/pnpm-lock.yaml
- e2e/tests/ui-driven/package.json
- e2e/tests/ui-driven/pnpm-lock.yaml
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
Replaces #2936, see testing notes there please
> chore: bump planx-core to ODP schema v0.5.0

- editor.planx.uk/src/pages/Preview/ResumePage.tsx
- editor.planx.uk/src/pages/Preview/SaveAndReturn.tsx
Regression tests failing as they're looking for this ID. Regression introduced in this PR - https://github.com/theopensystemslab/planx-new/pull/2970
> fix: Add `id="main-content"` back to `main` elements

- editor.planx.uk/src/@planx/components/FileUploadAndLabel/Modal.tsx
- editor.planx.uk/src/@planx/components/FileUploadAndLabel/SelectMultiple.tsx
Small refactor I hit whilst looking at this issue - https://trello.com/c/2qftxyhY/2812-customised-combobox-a
- Makes new styled components (`StyledSelect`, `StyledInputLabel`) to separate style from structure a little more
- Moves `SelectMultiple` to its own file
- Seemed worth doing before making further changes to this component
That's it, no functional or visual changes, just splitting up a complex/long file.
> chore: Refactor `SelectMultiple`

- .github/workflows/pull-request.yml
- .github/workflows/push-main.yml
- .github/workflows/push-production.yml
- editor.planx.uk/.env
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
- editor.planx.uk/src/lib/graphql.ts
- editor.planx.uk/src/pages/FlowEditor/index.tsx
- Basic proof of concept for using GraphQL subscriptions for operations
- A bit rough and ready but demonstrates the idea!
- Remove / hide component to merge
- Look into whole page re-rendering when modal opens - this is not unique to this component and already happens
https://github.com/theopensystemslab/planx-new/assets/20502206/bf9f5711-e83d-4957-a3ca-7dec06e391bb
> feat(proof-of-concept): GraphQL subscription for operations

- infrastructure/application/Pulumi.staging.yaml
Also manually updated Metabase passwords for `metabase_user` on Staging and Prod, and logged into Metabase to update connection string, and updated 1Password.
> chore: Update `metabasePgPassword` (staging)

- editor.planx.uk/src/pages/Preview/Questions.tsx
- editor.planx.uk/src/pages/layout/SaveAndReturnLayout.tsx
Follow up to #3029  - noticed a few other pages with the same issue!
> fix: Ensure main components have full-width

- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
> chore: Update supertest, drop temp pnpm override

- api.planx.uk/modules/send/uniform/uniform.ts
✅ Regression tests passing here - https://github.com/theopensystemslab/planx-new/actions/runs/8879808467
> fix: Logging circular structure to JSON

- editor.planx.uk/src/components/Header.tsx
Follow up to https://github.com/theopensystemslab/planx-new/pull/3069, resolves issues outlined here https://opensystemslab.slack.com/archives/C5Q59R3HB/p1714474156311369 (OSL Slack)
> fix: Replace remaining `/amber` references

- editor.planx.uk/src/@planx/components/FileUploadAndLabel/SelectMultiple.tsx
> fix: Remove 'Select all that apply' element from combobox

- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- e2e/tests/api-driven/package.json
- e2e/tests/api-driven/pnpm-lock.yaml
- e2e/tests/ui-driven/package.json
- e2e/tests/ui-driven/pnpm-lock.yaml
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
- editor.planx.uk/src/@planx/components/List/Editor.tsx
- editor.planx.uk/src/@planx/components/List/Public.test.tsx
- editor.planx.uk/src/@planx/components/List/Public.tsx
- editor.planx.uk/src/@planx/components/List/model.ts
- editor.planx.uk/src/@planx/components/shared/Preview/SummaryList.tsx
- editor.planx.uk/src/@planx/components/ui.tsx
- editor.planx.uk/src/lib/featureFlags.ts
- editor.planx.uk/src/pages/FlowEditor/components/Flow/components/Node.tsx
- editor.planx.uk/src/pages/FlowEditor/components/forms/FormModal.tsx
- editor.planx.uk/src/pages/FlowEditor/components/forms/index.ts
- editor.planx.uk/src/pages/FlowEditor/data/types.ts
- editor.planx.uk/src/pages/Preview/Node.tsx
- Adds `LIST_COMPONENT` feature flag
- Adds new `List` component type behind this flag
- No functionality, just boilerplate code
> chore: Setup new "List" component

- docker-compose.local.yml
- editor.planx.uk/.husky/pre-commit
- editor.planx.uk/.husky/pre-push
- Ran in to issues running the docker-api container
- Issue solved with changes to the docker local yml file
- used line from sharedb docker local
> fix: get planx running on windows

- api.planx.uk/modules/gis/service/local_authorities/metadata/base.ts
Last outstanding piece of feedback on attached Trello ticket.
> fix: adjust Article 4 text per Barnet's feedback

- editor.planx.uk/src/pages/FlowEditor/components/Settings/ServiceSettings.tsx
- Resets the form after submission to reset "dirty" status
- Aligns with behaviour in design settings, as seen in snippet below - 
https://github.com/theopensystemslab/planx-new/blob/e4cfb30ca2ce49a488c9f49273b08e7ed674919b/editor.planx.uk/src/pages/FlowEditor/components/Settings/DesignSettings/ThemeAndLogoForm.tsx#L38-L49
https://github.com/theopensystemslab/planx-new/assets/20502206/0f8833ee-a325-4b8b-b959-986ce5d14def
> feat: Improve flow status form UX

- editor.planx.uk/src/components/Header.tsx
- Adds a 'feedback' option to the menu for flows
> feat: Add feedback to menu

- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- e2e/tests/api-driven/package.json
- e2e/tests/api-driven/pnpm-lock.yaml
- e2e/tests/ui-driven/package.json
- e2e/tests/ui-driven/pnpm-lock.yaml
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
Fixes described here: https://github.com/theopensystemslab/planx-core/pull/403
> chore: bump planx-core (again)

- editor.planx.uk/src/pages/Team.tsx
Per feedback here ! https://github.com/theopensystemslab/planx-new/pull/3241#discussion_r1627995945
Merged in a jif because we were pairing & testing a rebase, but this is a much tidier suggestion :slightly_smiling_face:
> fix: use `toSorted()` to copy & sort instead of `slice().sort()`

- doc/how-to/how-to-add-a-list-component-schema.md
Quickly capturing some lessons-learned from onboarding August to creating/editing schemas this past week for future reference!
> docs: how to add List component schemas

- editor.planx.uk/pnpm-lock.yaml
Fixes https://github.com/theopensystemslab/planx-new/security/dependabot/99
> fix(editor): CVE-2024-37890

- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
Fixes https://github.com/theopensystemslab/planx-new/security/dependabot/98
> fix(api): CVE-2024-37890

- editor.planx.uk/src/@planx/components/List/Editor.tsx
- editor.planx.uk/src/@planx/components/List/schemas/Floorspace.ts
Added non-residential floorspace to list component and schema
> feat: Add non-residential floorspace to list component and schema

- e2e/tests/ui-driven/src/create-flow/create-flow.spec.ts
Regression tests passing here - https://github.com/theopensystemslab/planx-new/actions/runs/9642098388 ✅ 
This PR addresses a few failing regression tests, following on from this change - https://github.com/theopensystemslab/planx-new/pull/3303
> test: Update regression tests for new Team page layout

- editor.planx.uk/src/routes/teamSettings.tsx
## What does this PR do?
Commenting out General Settings Editor tab to allow production deploy
> refactor: [skip pizza] commenting out general settings tab

- infrastructure/application/Pulumi.staging.yaml
Follow on from https://github.com/theopensystemslab/planx-new/pull/3288
We're now seeing similar issues in staging, so this is a quick / pragmatic change to keep things up and available.
> chore: Bump Hasura fargate CPU and memory (staging)

- .github/workflows/pizza-teardown.yml
- .github/workflows/pull-request.yml
- scripts/pullrequest/create.sh
Reverts theopensystemslab/planx-new#3194
Looks like the latest release of Alpine has added back aws-cli ! Let's switch back and save a few minutes on pizza builds again :shaved_ice:
> Revert "Revert "feat: build pizzas on alpine""

- scripts/seed-database/write/team_settings.sql
This PR renames ``boundary_json`` references in the Scripts to ``boundary_bbox``
> feat: adding scripts for new ``boundary_bbox`` column in ``team_settings``

- editor.planx.uk/src/lib/graphql.ts
Please see https://opensystemslab.slack.com/archives/C01E3AC0C03/p1720449876847459 (OSL Slack) for context
> chore: Additional logging in `errorLink`

- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
Fixes https://github.com/theopensystemslab/planx-new/security/dependabot/100
> fix: CVE-2024-39008

- e2e/tests/ui-driven/src/create-flow/create-flow.spec.ts
- editor.planx.uk/src/components/Header.tsx
- Remove items from the drop down menu which now belong in the `EditorNavMenu`
> chore: Remove additional options from dropdown menu

- editor.planx.uk/src/pages/PlatformAdminPanel.tsx
- Brings admin panel styling in line with updated editor styling
- Introduces a basic level of responsive layout, allowing info to be viewable on narrower screens
**Preview:**
https://3424.planx.pizza/admin-panel
> feat: Admin panel styling

- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- e2e/tests/api-driven/package.json
- e2e/tests/api-driven/pnpm-lock.yaml
- e2e/tests/api-driven/src/globalHelpers.ts
- e2e/tests/ui-driven/package.json
- e2e/tests/ui-driven/pnpm-lock.yaml
- e2e/tests/ui-driven/src/context.ts
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
- Writes to new `team_settings` table in E2E tests (this will fix failing regression tests)
- Relies on https://github.com/theopensystemslab/planx-new/pull/3422
> test(e2e): Write to new `team_settings` table

- editor.planx.uk/src/lib/featureFlags.ts
- editor.planx.uk/src/pages/FlowEditor/components/Sidebar/Search.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Sidebar/index.tsx
- editor.planx.uk/src/ui/shared/Checkbox.tsx
- editor.planx.uk/src/ui/shared/ChecklistItem.tsx
- Adds a (very rough!) initial UI for the search feature
- It also has basic state, fetching, and debouncing set up
- This is behind the `SEARCH` feature flag
- Merging this means I can integrate with the API on another branch
> feat: Initial search UI (feature flagged)

- editor.planx.uk/src/components/EditorNavMenu.tsx
- Rearrange menu items on root page and teams page
- Please see https://opensystemslab.slack.com/archives/C04DZ1NBUMR/p1721124945443589 for context (OSL Slack)
> chore: Rearrange Editor menu items

- api.planx.uk/pnpm-lock.yaml
This resolves [failing regression tests](https://github.com/theopensystemslab/planx-new/actions/runs/10071355431) locally 👍
> fix(api): Regenerate lockfile

- editor.planx.uk/src/@planx/components/List/Editor.tsx
- editor.planx.uk/src/@planx/components/List/schemas/Materials.ts
- editor.planx.uk/src/@planx/components/List/utils.tsx
- editor.planx.uk/src/@planx/components/MapAndLabel/model.ts
- editor.planx.uk/src/@planx/components/Pay/Editor.test.tsx
- editor.planx.uk/src/@planx/components/PlanningConstraints/List.tsx
- editor.planx.uk/src/@planx/components/Question/Public.test.tsx
- editor.planx.uk/src/@planx/components/Question/Public/Question.tsx
- editor.planx.uk/src/components/Header.tsx
- editor.planx.uk/src/lib/featureFlags.ts
- editor.planx.uk/src/pages/FlowEditor/components/Flow/components/Node.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Settings/GeneralSettings/index.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Settings/shared/SettingsForm.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Sidebar/PublishDialog.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Sidebar/Search.tsx
- editor.planx.uk/src/pages/FlowEditor/lib/store/index.ts
- editor.planx.uk/src/pages/Preview/Node.tsx
- editor.planx.uk/src/pages/Teams.tsx
- editor.planx.uk/src/routes/views/flowEditor.tsx
- editor.planx.uk/src/routes/views/standalone.tsx
- editor.planx.uk/src/theme.ts
- editor.planx.uk/src/themeOverrides.d.ts
- editor.planx.uk/src/ui/editor/ColorPicker.tsx
- Runs `pnpm lint:fix`
- Removes unused variables 
Quick PR to check CI!
> chore: Remove unused variables and imports

- editor.planx.uk/src/pages/FlowEditor/components/Sidebar/Search.tsx
- editor.planx.uk/src/theme.ts
- editor.planx.uk/src/themeOverrides.d.ts
- editor.planx.uk/src/ui/shared/Input.tsx
- Adds a "data" typography variant to the MUI theme
- Please see https://github.com/theopensystemslab/planx-new/pull/3435#discussion_r1696622931 for context
> feat: Add 'data' typography variant

- editor.planx.uk/src/pages/Login.tsx
- Button style for login screen with icon
- Placeholder login button for Microsoft
> feat: Dual login screen

- api.planx.uk/modules/webhooks/docs.yaml
- api.planx.uk/modules/webhooks/service/sendNotification/index.test.ts
- api.planx.uk/modules/webhooks/service/sendNotification/index.ts
- api.planx.uk/modules/webhooks/service/sendNotification/schema.ts
- api.planx.uk/modules/webhooks/service/sendNotification/types.ts
- hasura.planx.uk/metadata/tables.yaml
Reverts theopensystemslab/planx-new#3466
See https://opensystemslab.slack.com/archives/C01E3AC0C03/p1722871590807709
> Revert "feat: setup a Slack notification when flow status is updated"

- editor.planx.uk/src/pages/FlowEditor/floweditor.scss
Resolves layout issues described in https://trello.com/c/pKlx6bg5/2979-diagnose-and-fix-layout-overlap-in-editor-graph
Please compare the following two flows - 
- https://editor.planx.dev/open-digital-planning/validating-and-assessing-applications-with-heritage-impacts
- https://3499.planx.pizza/open-digital-planning/validating-and-assessing-applications-with-heritage-impacts
> fix: Flow layout issues

- editor.planx.uk/public/index.html
Quick one! See thread: https://opensystemslab.slack.com/archives/C5Q59R3HB/p1723469856983559
> chore: update `<meta/>` description per feedback

- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- e2e/tests/api-driven/package.json
- e2e/tests/api-driven/pnpm-lock.yaml
- e2e/tests/ui-driven/package.json
- e2e/tests/ui-driven/pnpm-lock.yaml
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
Resolves - 
- https://github.com/theopensystemslab/planx-new/security/dependabot/102
- https://github.com/theopensystemslab/planx-new/security/dependabot/103
- https://github.com/theopensystemslab/planx-new/security/dependabot/104
- https://github.com/theopensystemslab/planx-new/security/dependabot/105
> fix: CVE-2024-39338

- editor.planx.uk/src/@planx/components/List/Editor.tsx
- editor.planx.uk/src/@planx/components/List/Public/List.stories.tsx
This PR completes the task: https://trello.com/c/4HVZfC7p/2985-add-list-component-to-storybook
The newly created ``List`` component needs to be added to the planx Storybook. 
To help adding schemas to the right component, I have added a ``schemeFinder`` function which finds a certain name of schema in the list created within the Editor file.
```ts
const schemaFinder = (name: SchemaNames) => {
const schemaObj = SCHEMAS.find((schema) => schema.name === name)?.schema;
return schemaObj;
};
```
To capture all of it's features, I have added 3 sections:
Multiple Card component connected to the `Residential units (GLA) - Removed` schema.
```ts
export const Basic: Story = {
args: {
title: "List",
description: "Add information on the removed residential units",
schemaName: "Residential units (GLA) …
```
> feat: List Component Storybook

- editor.planx.uk/src/@planx/components/PlanningConstraints/Public.tsx
Quick followup from #3514 - which refactored this bit of logic
While the condition looked fine on paper, I was getting some goofy UI behavior where instead of the loading indicator, we'd show only gis responses OR only road responses OR the no-info error summary, but then the full collated correct responses would fully load
This clears things up that bug & hopefully makes a marginal readability improvement
> fix: ensure loading indicator is visible when fetching Planning Constraints

- editor.planx.uk/src/@planx/components/FindProperty/Public/Public.test.tsx
Please see https://github.com/theopensystemslab/planx-new/pull/3549 for context
> test: Handle default export in `swr`

- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
- editor.planx.uk/src/@planx/components/DrawBoundary/Public/index.tsx
- editor.planx.uk/src/@planx/components/FindProperty/Public/Map.tsx
- editor.planx.uk/src/@planx/components/MapAndLabel/Public.tsx
- editor.planx.uk/src/@planx/components/shared/Preview/SummaryList.tsx
Let's use `v1.0.0-alpha.0` throughout planx-new to test our work! 
All working as expected so far, will rebase #3501 to this once merged instead of commit-style upgrade :+1:
> chore: use `@opensystemslab/map@next` in editor

- .github/workflows/push-main.yml
- .github/workflows/push-production.yml
Picked this up [for Pizzas here](https://github.com/theopensystemslab/planx-new/pull/3544/commits/ce4d8e69029bded3af46e8e97127e4346636b056), but neglected to check staging and production actions 😅
> fix: Add `VITE_APP_*` env vars to staging and prod CI

- editor.planx.uk/src/@planx/components/List/Public/index.test.tsx
Resolving a timeout which appears to be juuust over the current thresholds - it's intermittently passing and failing.
> test: Bump timeout on long running List component test

- editor.planx.uk/src/@planx/components/MapAndLabel/Public/index.tsx
"Copy from" and "Remove" don't work yet! Just stubbing them out so easier for anyone to come in and "wire up" or update styles next.
> chore: add basic UI components for Map & Label "remove" & "copy"

- editor.planx.uk/src/pages/Preview/Node.tsx
Spotted a few unused variables here whilst working on another PR, just removing these and also removing an `any` 🗑️ 🧹
> fix: Tidy up `Node.tsx`

- editor.planx.uk/src/@planx/components/Checklist/Editor.tsx
- Fixes issue described here https://opensystemslab.slack.com/archives/C01E3AC0C03/p1724940042979079 (OSL Slack)
- Regression introduced here - https://github.com/theopensystemslab/planx-new/pull/3514/files#r1718063305
> fix: Expandable checklists

- editor.planx.uk/src/@planx/components/MapAndLabel/Public/Context.tsx
- editor.planx.uk/src/@planx/components/MapAndLabel/Public/index.tsx
Please see https://github.com/theopensystemslab/planx-new/pull/3589#discussion_r1738012522
> chore: Update MapAndLabel root error messages

- editor.planx.uk/src/@planx/components/MapAndLabel/Public/index.tsx
> feat: Style 'Plot a feature...' text

- editor.planx.uk/src/@planx/components/List/Editor.tsx
- editor.planx.uk/src/@planx/components/List/schemas/GLA/ParkingGLA.ts
- editor.planx.uk/src/@planx/components/List/schemas/Parking.ts
Add parking space list schemas for GLA and non-GLA councils.
> feat: add parking space schemas

- editor.planx.uk/src/@planx/components/List/schemas/Trees.ts
- editor.planx.uk/src/@planx/components/List/schemas/TreesMapFirst.ts
Per feedback here! https://opensystemslab.slack.com/archives/C5Q59R3HB/p1725456319413809?thread_ts=1725376092.471139&cid=C5Q59R3HB
> fix(list-with-map): Update schema language "Tree" >> "Tree type"

- infrastructure/application/Pulumi.production.yaml
- infrastructure/application/Pulumi.staging.yaml
- infrastructure/application/index.ts
Follow up to #3453 
This adds secrets to our AWS staging and production environments. These are already configured for dev and pizza environments.
> chore(iac): Add Microsoft secrets to Pulumi

- docker-compose.yml
- infrastructure/application/utils/generateCORSAllowList.ts
Hopefully the final Pulumi follow on to #3453 🤞
> chore: Update `CORS_ALLOWLIST` on staging and production

- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
Resolves https://github.com/theopensystemslab/planx-new/security/dependabot/111
> chore: CVE-2024-43788

- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
Resolves - 
- https://github.com/theopensystemslab/planx-new/security/dependabot/121 
- https://github.com/theopensystemslab/planx-new/security/dependabot/118
- https://github.com/theopensystemslab/planx-new/security/dependabot/113
- https://github.com/theopensystemslab/planx-new/security/dependabot/116
> chore: CVE-2024-43796

- editor.planx.uk/src/@planx/components/Page/Public.tsx
Creates public interface for the Page component - a very simple implementation for the existing `SchemaFields` 👌
> feat(page): Public interface

- editor.planx.uk/src/@planx/components/Page/Page.stories.tsx
- Sets up Storybook for the Page component
- Pizza link here - https://storybook.3681.planx.pizza/?path=/docs/planx-components-page--docs
> feat(page): Add Storybook file

- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
Resolves - 
- https://github.com/theopensystemslab/planx-new/security/dependabot/124
- https://github.com/theopensystemslab/planx-new/security/dependabot/125
> chore: CVE-2024-45801

- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- e2e/tests/api-driven/package.json
- e2e/tests/api-driven/pnpm-lock.yaml
- e2e/tests/ui-driven/package.json
- e2e/tests/ui-driven/pnpm-lock.yaml
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
Switched the planx-core reference in the package.json.
> fix: team settings fix 

- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- e2e/tests/api-driven/package.json
- e2e/tests/api-driven/pnpm-lock.yaml
- e2e/tests/ui-driven/package.json
- e2e/tests/ui-driven/pnpm-lock.yaml
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
See https://github.com/theopensystemslab/planx-core/pull/515 && https://opensystemslab.slack.com/archives/C01E3AC0C03/p1726672061820229
> fix: bump planx-core and regenerate e2e/tests/ui-driven lockfile

- editor.planx.uk/src/lib/featureFlags.ts
- editor.planx.uk/src/pages/FlowEditor/components/Sidebar/index.tsx
- Removes `SEARCH` feature flag
- Removes redundant `ADD_NEW_EDITOR` feature flag
> chore: Drop search feature flag

- .env.example
- api.planx.uk/.env.test.example
- api.planx.uk/modules/send/bops/bops.ts
- api.planx.uk/server.ts
- docker-compose.yml
- infrastructure/application/Pulumi.production.yaml
- infrastructure/application/Pulumi.staging.yaml
- infrastructure/application/index.ts
Ticket: https://trello.com/c/MNMIyVfR/2975-remove-bopsapitoken
As part of this, I have also ran the `push-secrets` script to remove `BOPS_API_TOKEN` from `api.planx.uk/.env.test`
> chore: remove BOPS_API_TOKEN

- editor.planx.uk/src/lib/featureFlags.ts
- editor.planx.uk/src/pages/FlowEditor/components/Sidebar/Search/SearchHeader.tsx
Quick, pretty short term, feature flag allowing me to develop the "all node data" search across a few PRs.
> chore: Add feature flag to toggle data only searching

- api.planx.uk/lib/notify/index.ts
First attempt to get a better insight into https://planx.airbrake.io/projects/329753/groups/3890967064109750041?tab=overview
> chore: Improve logging on Notify errors

- editor.planx.uk/src/@planx/components/FileUploadAndLabel/Public.test.tsx
- editor.planx.uk/src/@planx/components/FileUploadAndLabel/Public.tsx
- editor.planx.uk/src/@planx/components/Review/Public/Presentational.tsx
- editor.planx.uk/src/@planx/components/Review/Public/Public.test.tsx
- editor.planx.uk/src/components/PrintButton.tsx
Trello ticket: https://trello.com/c/EhZbLJQV/2927-add-export-print-function-for-validation-checklist
> feat: add export/print button to Upload+Label and Review components

- editor.planx.uk/src/pages/FlowEditor/components/Settings/ServiceSettings/FlowStatus/index.tsx
Please see https://opensystemslab.slack.com/archives/C0405SQDP8B/p1728550588196189 (OSL Slack)
This _should_ now correctly mention Silvia when the message is sent - not tested yet, will try it out on prod.
Docs: https://api.slack.com/reference/surfaces/formatting#mentioning-users
> fix: Correct slack mention syntax

- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
Fixes https://github.com/theopensystemslab/planx-new/security/dependabot/136
> chore: CVE-2024-21536

- editor.planx.uk/src/pages/FlowEditor/components/Flow/components/Filter.tsx
Please see https://github.com/theopensystemslab/planx-new/pull/3764#discussion_r1789193286
> fix:  Apply `wasVisited` class to Filter node

- hasura.planx.uk/metadata/tables.yaml
Spent way too long staring at this error not to spot this one 🙃
> fix: Typo in `x-hasura-user-id`

- editor.planx.uk/src/airbrake.ts
- editor.planx.uk/src/routes/utils.ts
Step 10 here - https://github.com/theopensystemslab/planx-new/blob/main/doc/how-to/how-to-setup-custom-subdomains.md
> chore: Finalise Newcastle subdomain setup

- api.planx.uk/modules/auth/controller.ts
- api.planx.uk/modules/auth/middleware.ts
- api.planx.uk/modules/auth/strategy/microsoft-oidc.ts
- api.planx.uk/server.ts
Dupe of #3803 to resolve (undiagnosed) problem with the React build step not using latest workflow changes.
> [api] security hardening for microsoft auth

- api.planx.uk/modules/flows/validate/controller.ts
- api.planx.uk/modules/flows/validate/service/index.ts
Large flows are timing out on "Check for changes to publish" as reported here: https://opensystemslab.slack.com/archives/C01E3AC0C03/p1730715895034839
> fix: bump timeout on `/diff` endpoint

- doc/how-to/how-to-setup-custom-subdomains.md
Quick note to improve workflow and not have to message devs on their days off (sorry @jamdelion!)
> docs: Suggest .key and .csr are saved to 1Password [skip pizza]

- api.planx.uk/modules/send/docs.yaml
- api.planx.uk/modules/send/goss/controller.ts
- api.planx.uk/modules/send/goss/goss.test.ts
- api.planx.uk/modules/send/goss/service.ts
- api.planx.uk/modules/send/routes.ts
- Sets up boilerplate API code and initial tests for the GOSS integration
- No functionality, I'll pick these up shortly!
> feat: Basic boilerplate for GOSS API endpoint

- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- e2e/tests/api-driven/package.json
- e2e/tests/api-driven/pnpm-lock.yaml
- e2e/tests/ui-driven/package.json
- e2e/tests/ui-driven/pnpm-lock.yaml
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
**Captures all recent planx-core changes in one go** (should save on rebases later!):
- ESM migration https://github.com/theopensystemslab/planx-core/pull/601
**Data migration changes:**
- Flag prop https://github.com/theopensystemslab/planx-core/pull/611
- Corresponds to #4098
- Calculate https://github.com/theopensystemslab/planx-core/pull/593 
- Corresponds to #4083
- Draw Boundary https://github.com/theopensystemslab/planx-core/pull/594
- Corresponds to #4085
> migrate: bump planx-core

- editor.planx.uk/src/pages/FlowCard.tsx
- editor.planx.uk/src/pages/Team.tsx
- editor.planx.uk/src/ui/editor/FlowTag.tsx
- Adds `flowTag` setup
- Adds logic for displaying `flowTag` on `flowCard`
> feat: Add tags to flowCard

- editor.planx.uk/pnpm-lock.yaml
Fixes https://github.com/theopensystemslab/planx-new/security/dependabot/168
> fix: CVE-2024-57556

- .github/dependabot.yml
- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- api.planx.uk/vitest.config.ts
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
- hasura.planx.uk/tests/package.json
- hasura.planx.uk/tests/pnpm-lock.yaml
Fixes - 
- https://github.com/theopensystemslab/planx-new/security/dependabot/169
- https://github.com/theopensystemslab/planx-new/security/dependabot/170
- https://github.com/theopensystemslab/planx-new/security/dependabot/171
> chore: CVE-2025-24964

- hasura.planx.uk/migrations/1738757992023_run_sql_migration/down.sql
- hasura.planx.uk/migrations/1738757992023_run_sql_migration/up.sql
Opened on behalf of @christinelangston
A few questions below for @zz-hh-aa 👇
> chore: Clean property type column

- editor.planx.uk/src/components/EditorNavMenu.test.tsx
- editor.planx.uk/src/components/EditorNavMenu.tsx
- editor.planx.uk/src/routes/authenticated.tsx
Reverts theopensystemslab/planx-new#4267
Will merge to `main` once current deploy is tested and merged.
This works! Next step is to pay for a service and correctly configure this.
> Revert "poc: Notion iframes in AWS Cloudfront [skip pizza]"

- e2e/tests/ui-driven/src/invite-to-pay/nominee.spec.ts
This title was removed here - https://github.com/theopensystemslab/planx-new/pull/4067/commits/ec26132c2f80a8f47bc71ddc0bf90f9413989c3b (PR #4067)
> test(e2e): Fix redundant regression test check for fee table title

- editor.planx.uk/src/@planx/components/List/schemas/CIL/ExistingCIL.ts
- editor.planx.uk/src/@planx/components/List/schemas/CIL/MezzanineCIL.ts
- editor.planx.uk/src/@planx/components/List/schemas/CIL/UnoccupiedCIL.ts
Updates CIL schema wording and adds optional date input.
> chore: update cil schemas

- scripts/seed-database/write/flows.sql
Data sync currently failing locally, just a simple new column out of sync !
> fix: add `flows.is_template` to sync scripts

- e2e/tests/api-driven/src/demo-workspace/demoUser.feature
- e2e/tests/api-driven/src/demo-workspace/helper.ts
- e2e/tests/api-driven/src/demo-workspace/steps/background_steps.ts
- e2e/tests/api-driven/src/demo-workspace/steps/verification_steps.ts
Regression tests passing here - https://github.com/theopensystemslab/planx-new/actions/runs/13262726107 ✅ 
This resolves test failures I was hitting here - https://github.com/theopensystemslab/planx-new/pull/4234
> fix(e2e): Fix async and logical issues with demoUser tests

- scripts/seed-database/write/flows.sql
Will be required once https://github.com/theopensystemslab/planx-new/pull/4234 is on production.
> chore: Add `flows.deleted_at` to the sync script

- .github/workflows/sync-staging-db.yml
- docker-compose.seed.yml
- docker-compose.yml
Replaces #4310 - see #4320 for context on version leap restrictions !
> infra: upgrade docker envs to postgres 16

- docker-compose.yml
- infrastructure/application/index.ts
- sharedb.planx.uk/server.js
Reverts theopensystemslab/planx-new#4328
Opening pro-actively incase we need to roll back this change.
> Revert "feat(sharedb): Toggle Postgres SSL for AWS environments"

- editor.planx.uk/src/theme.ts
- Removes the overflow scrollbar in the data grid table footer, identified by @jamdelion https://github.com/theopensystemslab/planx-new/pull/4376#pullrequestreview-2641250157
**Preview:**
https://4380.planx.pizza/admin-panel
> fix: Grid table footer scrollbar

- editor.planx.uk/src/pages/FlowEditor/components/Settings/Submissions/Submissions.tsx
- editor.planx.uk/src/pages/Teams.tsx
- editor.planx.uk/src/ui/shared/SearchBox/SearchBox.tsx
To get the submissions log height fix out there asap!
> Prod deploy

- infrastructure/application/Pulumi.staging.yaml
- infrastructure/data/Pulumi.staging.yaml
> [application] fix db-url config misapplication

- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- doc/how-to/how-to-add-a-new-planning-data-layer.md
- doc/how-to/how-to-setup-planning-constraints-for-a-team.md
- e2e/tests/api-driven/package.json
- e2e/tests/api-driven/pnpm-lock.yaml
- e2e/tests/ui-driven/package.json
- e2e/tests/ui-driven/pnpm-lock.yaml
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
Relies on https://github.com/theopensystemslab/planx-core/pull/663
See how-to doc added here for pizza testing notes!
> feat: add Archeaological Priority Areas & how-to doc for new PD layers

- editor.planx.uk/src/pages/FlowEditor/components/Flow/FeedbackLog/FeedbackLog.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Flow/FeedbackLog/utils.tsx
Removes feedback type icons from feedback log.
> refactor: Remove feedback type icons from log

- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- hasura.planx.uk/tests/package.json
- hasura.planx.uk/tests/pnpm-lock.yaml
Fixes - 
- https://github.com/theopensystemslab/planx-new/security/dependabot/173
- https://github.com/theopensystemslab/planx-new/security/dependabot/174
> chore: CWE-346 (API & Hasura tests)

- infrastructure/performance/pyproject.toml
- infrastructure/performance/uv.lock
Resolves https://github.com/theopensystemslab/planx-new/security/dependabot/179
> chore: CVE-2025-27516

- api.planx.uk/pnpm-lock.yaml
- e2e/pnpm-lock.yaml
- e2e/tests/api-driven/pnpm-lock.yaml
- e2e/tests/ui-driven/pnpm-lock.yaml
- editor.planx.uk/pnpm-lock.yaml
- scripts/encrypt/pnpm-lock.yaml
Fixes - 
- https://github.com/theopensystemslab/planx-new/security/dependabot/183
- https://github.com/theopensystemslab/planx-new/security/dependabot/185
- https://github.com/theopensystemslab/planx-new/security/dependabot/187
- https://github.com/theopensystemslab/planx-new/security/dependabot/189
- https://github.com/theopensystemslab/planx-new/security/dependabot/190
- https://github.com/theopensystemslab/planx-new/security/dependabot/191
> chore: CVE-2025-27789

- api.planx.uk/modules/auth/docs.yaml
> docs(api): Swagger docs for `/auth/validate-jwt` endpoint

- infrastructure/application/Pulumi.production.yaml
- infrastructure/application/Pulumi.staging.yaml
- infrastructure/application/index.ts
- infrastructure/application/services/hasura.ts
- infrastructure/networking/index.ts
- **Revert "fix: Drop containerPort [skip pizza] (#4477)"**
- **Revert "fix: Service registry port config (#4476)"**
- **Revert "fix: Use default routing policy (#4475)"**
- **Revert "fix: Setup internal DNS for Fargate (take 2) (#4474)"**
- **Revert "feat: Setup Fargate internal DNS (#4473)"**
> chore: Revert attempt to configure Fargate internal DNS

- scripts/seed-database/write/team_integrations.sql
`pnpm test-sync` working locally - apologies for missing this one.
I'll re-trigger staging sync once this is merged.
> fix: Team integrations data sync

- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- e2e/tests/api-driven/package.json
- e2e/tests/api-driven/pnpm-lock.yaml
- e2e/tests/ui-driven/package.json
- e2e/tests/ui-driven/pnpm-lock.yaml
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
- editor.planx.uk/src/@planx/components/SetFee/Editor.tsx
- editor.planx.uk/src/@planx/components/SetFee/Public.tsx
- editor.planx.uk/src/@planx/components/SetFee/model.ts
- editor.planx.uk/src/@planx/components/shared/Preview/SummaryList.tsx
- editor.planx.uk/src/@planx/components/shared/icons.tsx
- editor.planx.uk/src/pages/FlowEditor/components/Flow/components/Node.tsx
- editor.planx.uk/src/pages/FlowEditor/components/forms/FormModal.tsx
- editor.planx.uk/src/pages/FlowEditor/components/forms/index.ts
- editor.planx.uk/src/pages/FlowEditor/data/types.ts
- editor.planx.uk/src/pages/Preview/Node.tsx
New component type which will support adding VAT & service charges
> chore: stub out `SetFee` component

- editor.planx.uk/src/@planx/components/PlanningConstraints/List.tsx
> fix: React prop error (`inaccurateConstraints`)

- editor.planx.uk/src/pages/FlowEditor/components/Team/components/UserUpsertModal.tsx
Please see https://opensystemslab.slack.com/archives/C088K9ZL8EA/p1743094307043209 (OSL Slack) for context.
Login requires a lowercase email address.
> chore: Format user model before submit

- api.planx.uk/modules/auth/strategy/google.ts
- Adds a configurable blocklist to the Google auth strategy
- Adds Newcastle's domain to the blocklist
Request by Newcastle IT. Please see thread here (OSL Slack) - https://opensystemslab.slack.com/archives/C01E3AC0C03/p1743414949278419
**To test**
When running locally, add your own domain to the blocklist and attempt to sign in via Google SSO.
```ts
const GOOGLE_AUTH_BLOCKLIST = ["newcastle.gov.uk", "opensystemslab.io"];
```
> feat: Implement blocklist for Google SSO

- doc/how-to/how-to-identify-missing-files.md
Follow up to https://github.com/theopensystemslab/planx-new/pull/4542
> docs: How to identify missing user uploads

- editor.planx.uk/src/pages/FlowEditor/utils.ts
- editor.planx.uk/src/pages/Team/components/FlowCard.tsx
Updates `FlowCard` to display either last edited or last published date, based on the context.
https://github.com/user-attachments/assets/44d54c01-2f89-4372-bc0d-0d7a5d6bba11
> feat: Display published date when sorting

- api.planx.uk/modules/file/controller.ts
- api.planx.uk/modules/file/docs.yaml
- api.planx.uk/modules/file/file.test.ts
- api.planx.uk/modules/file/service/getFile.ts
- api.planx.uk/modules/send/utils/exportZip.ts
- api.planx.uk/vitest.config.ts
Improves error handling - it's possible an S3 file could be deleted by Scanii and we need to account for this
Docs on narrowing these issues down can be found here - #4543
> feat(api): Improved error handling for files deleted by Scanii

- scripts/seed-database/write/users.sql
> chore: Sync new `users.is_analyst` column

- infrastructure/application/Pulumi.production.yaml
- infrastructure/application/Pulumi.staging.yaml
Rotates both the JWT secret and admin secret.
Also pushed a change to AWS envs, so please pull a local copy.
> chore: Rotate Hasura secrets

- infrastructure/application/Pulumi.staging.yaml
- infrastructure/data/Pulumi.staging.yaml
Timing difference between these two operations will result in some temporary downtime on staging.
`pulumi preview` generates the current correct preview locally for the data layer following these changes - https://app.pulumi.com/planx/data/staging/previews/0ca8defc-0f9d-4283-b855-2c81e16ae9a8
> chore: Rotate staging db password

- infrastructure/application/Pulumi.production.yaml
- infrastructure/data/Pulumi.production.yaml
The following preview is generated by Pulumi for the data layer update (production) https://app.pulumi.com/planx/data/production/previews/925c1fc0-c8ff-4ac6-b8a1-df4033194ded
> chore: Rotate prod db password

- api.planx.uk/modules/webhooks/service/analyzeSessions/operations.ts
- editor.planx.uk/src/pages/FlowEditor/lib/analytics/provider.tsx
Forgot to actually add `userAgent` and `referrer` to allow list in #4643..!
> fix: add `referrer` and `userAgent` to allow list

- editor.planx.uk/src/pages/FlowEditor/components/forms/FormModal.tsx
> feat: disable editing nodes in templated flows that are not tagged 'customisation'

- api.planx.uk/modules/flows/copyFlow/controller.ts
- api.planx.uk/modules/flows/createFlow/controller.ts
- api.planx.uk/modules/flows/createFlowFromTemplate/controller.ts
- editor.planx.uk/src/pages/Team/components/FlowCard.tsx
- editor.planx.uk/src/pages/Team/components/RenameDialog.tsx
- Replaces prompt with a form and dialog on the "rename" action
- Improves error handling
- Trims flow names on creation
Issues raised here (OSL Slack) - https://opensystemslab.slack.com/archives/C088K9ZL8EA/p1746617788647349
> feat: Rename flow dialog

- infrastructure/performance/pyproject.toml
- infrastructure/performance/uv.lock
Fixes - 
- https://github.com/theopensystemslab/planx-new/security/dependabot/215
- https://github.com/theopensystemslab/planx-new/security/dependabot/216
- https://github.com/theopensystemslab/planx-new/security/dependabot/217
Docs: https://github.com/corydolphin/flask-cors/releases/tag/6.0.0
> chore: Bump flask-cors

- editor.planx.uk/src/ui/shared/WatermarkBackground.tsx
> fix: Exclude `forceVisibility` prop from the DOM

- editor.planx.uk/src/@planx/components/Page/schema/Monitoring.ts
- editor.planx.uk/src/@planx/components/Page/schema/Utilities.ts
This PR makes minor copy changes to the page schemas for utilities and GLA monitoring questions.
> chore: page schema copy changes

- .github/workflows/pizza-teardown-manual.yml
- .github/workflows/pizza-teardown.yml
- .github/workflows/pull-request.yml
Points at pre-release of vultr-action, full details here - https://github.com/theopensystemslab/vultr-action/pull/4
Once the above PR is merged, I'll update this branch to use a release of v2.2
> chore(ci): Bump vultr-action

- editor.planx.uk/src/ui/editor/RichTextInput/validationHelpers.ts
QA by @DafyddLlyr on: https://github.com/theopensystemslab/planx-new/pull/4749
`Could we start by splitting it into a switch per variant at least?`
This PR uses a switch to define the variants so that they can be validated against / tested separately.
**Preview:**
https://4772.planx.pizza/a-new-team/content-validation
> refactor: Rich text hierarchy validation by variant

- infrastructure/performance/pyproject.toml
- infrastructure/performance/uv.lock
Resolves https://github.com/theopensystemslab/planx-new/security/dependabot/224
> chore: CVE-2024-47081

- editor.planx.uk/src/pages/FlowEditor/lib/analytics/utils.ts
Just updating the allow list of live flows (from platform amin panel) that can have analytics dashboards.
> chore: update analytics service allow list

- .env.example
- .env.staging
- docker-compose.yml
- infrastructure/application/utils/generateCORSAllowList.ts
Allows requests from `localplannning.PR_NUMBER.pizza` to `api.PR_NUMBER.pizza`
Required for https://github.com/theopensystemslab/planx-new/pull/4797
> chore(api): Setup CORS to allow LPS to make requests to PlanX API

- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
Replaces https://github.com/theopensystemslab/planx-new/pull/4867
> chore(api): Bump helmet to v8

- e2e/tests/ui-driven/package.json
- e2e/tests/ui-driven/pnpm-lock.yaml
- e2e/tests/ui-driven/src/create-flow-with-geospatial.spec.ts
- e2e/tests/ui-driven/src/helpers/geospatialChecks.ts
- Updates Playwright
- Fixes flakey geospatial tests (please see comments on code below)
Regression tests passing against branch here - https://github.com/theopensystemslab/planx-new/actions/runs/16025538764 ✅
> fix(e2e): Fix flakey geospatial tests, bump Playwright version

- editor.planx.uk/src/@planx/components/FindProperty/Editor.tsx
- editor.planx.uk/src/@planx/components/FindProperty/model.ts
Continuation of the work started in https://github.com/theopensystemslab/planx-new/pull/4831
> feat: Apply `baseNodeValidationSchema` to FindProperty

- editor.planx.uk/src/@planx/components/InternalPortal/Editor.test.tsx
- editor.planx.uk/src/@planx/components/InternalPortal/Editor.tsx
- editor.planx.uk/src/@planx/components/InternalPortal/model.ts
- editor.planx.uk/src/@planx/components/shared/types.tsx
- editor.planx.uk/src/pages/FlowEditor/components/forms/FormModal.tsx
- editor.planx.uk/src/routes/flow.tsx
> feat: Validation and type improvements for `InternalPortal`

- editor.planx.uk/src/@planx/components/MapAndLabel/Editor.tsx
- editor.planx.uk/src/@planx/components/MapAndLabel/model.ts
> feat: Validation for MapAndLabel

- editor.planx.uk/src/@planx/components/NextSteps/Editor.tsx
- editor.planx.uk/src/@planx/components/NextSteps/model.ts
> feat: Validation for NextSteps

- editor.planx.uk/src/@planx/components/Notice/Editor.tsx
- editor.planx.uk/src/@planx/components/Notice/model.ts
> feat: Validation for Notice

- api.planx.uk/modules/webhooks/service/sendNotification/index.ts
See https://opensystemslab.slack.com/archives/C01E3AC0C03/p1751550607474109
> chore: add more councils to pilot testing Slack notifications

- editor.planx.uk/src/@planx/components/Pay/Editor/Editor.tsx
- editor.planx.uk/src/@planx/components/Pay/Editor/InviteToPaySection.tsx
- editor.planx.uk/src/@planx/components/Pay/model.ts
> feat: Validation for Pay

- editor.planx.uk/src/@planx/components/Question/Editor.tsx
- editor.planx.uk/src/@planx/components/Question/model.ts
- editor.planx.uk/src/@planx/components/ResponsiveChecklist/Editor.tsx
- editor.planx.uk/src/@planx/components/ResponsiveChecklist/model.ts
- editor.planx.uk/src/@planx/components/ResponsiveQuestion/Editor.tsx
- editor.planx.uk/src/@planx/components/ResponsiveQuestion/model.ts
Starting to see the light at the end of the tunnel now! 🙃
> feat: Validation for `Question`, `ResponsiveQuestion` and `ResponsiveChecklist`

- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- e2e/pnpm-lock.yaml
- e2e/tests/api-driven/README.md
- e2e/tests/api-driven/package.json
- e2e/tests/api-driven/pnpm-lock.yaml
- e2e/tests/ui-driven/package.json
- e2e/tests/ui-driven/pnpm-lock.yaml
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
- editor.planx.uk/src/@planx/components/Result/Editor.tsx
- editor.planx.uk/src/@planx/components/Result/model.ts
- editor.planx.uk/src/ui/editor/ModalFooter.tsx
> feat: Validation for Result

- e2e/tests/ui-driven/src/create-flow-with-geospatial.spec.ts
Regression tests passing here - https://github.com/theopensystemslab/planx-new/actions/runs/16191910563 ✅
> test(e2e): Skip flaky geospatial tests

- localplanning.services/src/components/Footer.astro
- localplanning.services/src/components/LpaMasthead.astro
- localplanning.services/src/components/ServiceCard.astro
- localplanning.services/src/content/generic/about.md
- localplanning.services/src/layouts/SearchLayout.astro
- localplanning.services/src/pages/[lpa].astro
- localplanning.services/src/pages/index.astro
- localplanning.services/src/pages/search/index.astro
Updates content across LPS:
- Updated about page
- Update style of service cards now that they sit within an accordion (with background)
- Reorder footer so that supporter logos come first (feels like a natural progression from content)
> feat(lps): Content update

- localplanning.services/src/components/Accordion.astro
- localplanning.services/src/components/Button.astro
- localplanning.services/src/components/ServiceCard.astro
- localplanning.services/src/components/applications/LoginForm.tsx
- localplanning.services/src/components/directory/AccordionSection.astro
- localplanning.services/src/pages/[lpa].astro
- localplanning.services/src/pages/directory.astro
- Optimises size and spacing of accordions and cards so that they can be easily navigated
- Removes auto scroll-to-accordion on LPA page load, as doing so jumps over the information about which LPA is being viewed
https://localplanning.4966.planx.pizza/buckinghamshire/
https://localplanning.4966.planx.pizza/directory/
> style(lps): Refine accordion and card style

- localplanning.services/src/components/ApplicationsBanner.astro
- localplanning.services/src/layouts/SearchLayout.astro
- localplanning.services/src/pages/[lpa].astro
- localplanning.services/src/pages/directory.astro
- localplanning.services/src/pages/index.astro
- Adds applications banner across LPS
https://localplanning.4999.planx.pizza/
> feat(lps): Applications banner

- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
- editor.planx.uk/src/@planx/components/Checklist/Editor/Editor.test.tsx
- editor.planx.uk/src/@planx/components/Checklist/Editor/Editor.tsx
- editor.planx.uk/src/@planx/components/Checklist/Editor/components/ExclusiveOrOptionManager.tsx
- editor.planx.uk/src/@planx/components/Checklist/Editor/components/OptionsEditor.tsx
- editor.planx.uk/src/@planx/components/Question/OptionsEditor.tsx
- editor.planx.uk/src/@planx/components/shared/BaseOptionsEditor.tsx
- editor.planx.uk/src/@planx/components/shared/DataFieldAutocomplete.tsx
Ensures that the current behaviour is covered by tests - does not update or change existing behaviour.
[This ticket](https://trello.com/c/BWS2DpVZ/3315-nested-checklists-a-p29) requires that we have validation in place to manage unique labels within the checklist component. Prior to doing this I want to ensure the current functionality has adequate coverage.
The workflow will go something like this -
- add test coverage for existing functionality (this PR)
- migrate validation checks from the `test` property, into a single validation schema (https://github.com/theopensystemslab/planx-new/pull/4980)
- add additional validation for unique label rules (upcoming)
_Screenshot from coverage report_
> test: Improve coverage for checklist validation (editor)

- editor.planx.uk/src/ui/shared/SelectMultiple.tsx
DAC pg(82)
This PR sets label prop to fix label positin and remove animation.
> fix: autocomplete label position

- infrastructure/application/pnpm-lock.yaml
- infrastructure/certificates/pnpm-lock.yaml
- infrastructure/data/pnpm-lock.yaml
- infrastructure/networking/pnpm-lock.yaml
Fixes - 
- https://github.com/theopensystemslab/planx-new/security/dependabot/263
- https://github.com/theopensystemslab/planx-new/security/dependabot/264
- https://github.com/theopensystemslab/planx-new/security/dependabot/265
- https://github.com/theopensystemslab/planx-new/security/dependabot/266
> chore: CVE-2025-54798

- editor.planx.uk/src/pages/FlowEditor/lib/sharedb.ts
Follow up to https://github.com/theopensystemslab/planx-new/pull/5123, trying to get a bit more information here. Currently not much of any meaning being captured by Airbrake.
> chore: Improve sharedb logging

- api.planx.uk/modules/auth/controller.ts
- editor.planx.uk/src/pages/FlowEditor/lib/sharedb.ts
- sharedb.planx.uk/server.js
Follow up to #5170 - I can see from Cloudwatch logs that we're frequently failing with the error "Invalid JWT. Please log in again" so I'm trying to gain some more insight here.
> chore: Further ShareDB logging

- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
Fixes https://github.com/theopensystemslab/planx-new/security/dependabot/251
> chore: CVE-2025-7783

- editor.planx.uk/src/pages/Team/components/AddFlow/index.tsx
When copying a flow, it's possible that an error is hit by the API and then not handled by the existing modal. The current business logic does throw an error, but as it's in a dialog there's no existing `ErrorWrapper` to catch this.
This was recently raised [in this thread (ODP Slack)](https://opendigitalplanning.slack.com/archives/C0241GWFG4B/p1757325815807699). The issue in this instance was that there was invalid HTML in the source flow and our HTML sanitation process wasn't allowing us to proceed. As no feedback was given to the user this lead to a help issue being rasied.
- Provide feedback to user via `ErrorWrappers`
- Log errors to Airbrake
- Fix underlying HTML within source flow (in this instance it was a legacy `Confirmation` component with [the `<br>` issued described …
> fix: Improve error handling for Add Flow modal

- editor.planx.uk/src/pages/FlowEditor/ReadMePage/tests/helpers.ts
The latest re-run of a failed staging deploy appears to have succeeded ✅ https://github.com/theopensystemslab/planx-new/actions/runs/17578294327/job/49931169274
This PR should serve as a clean run through so we can be sure of this, and I'll work on provisioning LPS infra locally via the Pulumi CLI tool.
> chore(ci): Whitespace change to test CI pipeline to staging

- localplanning.services/src/components/AddressSearch.tsx
- localplanning.services/src/styles/global.css
- Adds remaining styles to LPS address lookup web component
Preview:
https://localplanning.5232.planx.pizza/search/
> style(lps): Address search function

- localplanning.services/src/components/applications/ApplicationCard.tsx
- localplanning.services/src/components/applications/ApplicationsList.tsx
- localplanning.services/src/components/applications/hooks/useFetchApplications.tsx
Already reviewed and approved, was accidentally merged into `dp/lps-query-improvement` instead of `main` though.
This is a new PR with the same cherry-picked changes from https://github.com/theopensystemslab/planx-new/pull/5200 which should solve this! 🍒
> feat: Wire up API changes to new application card UI

- api.planx.uk/modules/gis/docs.yaml
| <img width="398" height="142" alt="image" src="https://github.com/user-attachments/assets/fad34455-3a41-47b0-864e-6e4a8d6874d3" /><img width="324" height="107" alt="image" src="https://github.com/user-attachments/assets/a0785df3-84e5-49de-b9ae-2a2008ac952b" /> | <img width="450" height="197" alt="image" src="https://github.com/user-attachments/assets/f6ab3e60-d4af-4a99-a937-835504438cb8" /> |
> chore(api): Correctly tag new `/lpa` endpoint

- localplanning.services/src/components/applications/ApplicationCard.tsx
Updates application cards on LPS
- Fallback message if no address is present
- Small spacing tweaks
> refactor(lps): Update application cards

- localplanning.services/src/components/CustomCheckbox.tsx
- localplanning.services/src/components/applications/ApplicationCard.tsx
- localplanning.services/src/components/applications/ApplicationFilters.tsx
- localplanning.services/src/components/applications/ApplicationsList.tsx
- localplanning.services/src/components/applications/hooks/useFetchApplications.tsx
- localplanning.services/src/components/applications/hooks/useFilters.tsx
- localplanning.services/src/styles/global.css
Sets up search and category filters for LPS application cards.
https://github.com/user-attachments/assets/e66e4259-066f-4066-bf11-4108dfc832f5
> feat(lps): Application card filters

- editor.planx.uk/src/routes/views/flowEditor.tsx
Quick one - just hit this when working on another branch, pulling it into here a change to keep churn down in another PR.
> chore(editor): Remove unused imports

- e2e/tests/ui-driven/src/helpers/userActions.ts
- editor.planx.uk/src/@planx/components/List/schemas/ResidentialUnits/Existing.ts
- editor.planx.uk/src/@planx/components/List/schemas/ResidentialUnits/ExistingLDCE.ts
- editor.planx.uk/src/@planx/components/List/schemas/ResidentialUnits/GLA/Gained.ts
- editor.planx.uk/src/@planx/components/List/schemas/ResidentialUnits/GLA/Lost.ts
- editor.planx.uk/src/@planx/components/List/schemas/ResidentialUnits/PreviousLDCE.ts
- editor.planx.uk/src/@planx/components/List/schemas/ResidentialUnits/Proposed.ts
Content review of [residential units schema copy by service team](https://trello.com/c/w6UGJOoa/1726-review-language-used-in-residential-units-flow) suggested various changes.
> chore: change residential units schema copy

- localplanning.services/src/content/actions/index.ts
Source (OSL Slack): https://opensystemslab.slack.com/archives/C5Q59R3HB/p1759417714522489?thread_ts=1759326381.859329&cid=C5Q59R3HB
> chore(lps): Update copy for "notify" card

- api.planx.uk/package.json
- api.planx.uk/pnpm-lock.yaml
- e2e/tests/api-driven/package.json
- e2e/tests/api-driven/pnpm-lock.yaml
- e2e/tests/ui-driven/package.json
- e2e/tests/ui-driven/pnpm-lock.yaml
- editor.planx.uk/package.json
- editor.planx.uk/pnpm-lock.yaml
1 issue here caught by regression tests - 
- Missing fallback for payload generation (regression introduced [here](https://github.com/theopensystemslab/planx-core/pull/831))
Regression tests running here - https://github.com/theopensystemslab/planx-new/actions/runs/18224167307 🚀
> fix(e2e): Regression tests

- hasura.planx.uk/migrations/default/1759310676499_create_analytics_exits_view/up.sql
Our production deploys are failing and Hasura is unhealthy due to this particular migration (originally PR #5317) failing to successfully execute on production. We're attempting to edit it directly here.
See thread for full context: https://opensystemslab.slack.com/archives/C04EEBR1E0P/p1759850237284339
If this works on prod, I think we'll want to manually update SQL definitions on staging to match for better performance? This migration will not be picked up there on merge as it's "already run successfully" (because no actual analytics records to slow it down!)
** **Note that this view will NOT actually be found on the pizza because there is a migration on `main` _after_ this edited one to drop it (#5359), so what we're instead looking for is "Healthy metadata" and no other issues in the …
> fix: update migration for `analytics_exits` materialized view creation

- hasura.planx.uk/metadata/databases/default/tables/public_lowcal_sessions.yaml
- hasura.planx.uk/migrations/default/1759926325370_recreate_view_analytics_exit/down.sql
- hasura.planx.uk/migrations/default/1759926325370_recreate_view_analytics_exit/up.sql
See #5364
Reverting #5359 one at a time to ensure no issues running on prod
> fix(1/4): recreate mv `analytics_exits`
