editor.planx.uk/src/@planx/components/List/Editor.tsx, editor.planx.uk/src/@planx/components/List/Public/Fields.tsx, editor.planx.uk/src/@planx/components/List/Public/index.test.tsx, editor.planx.uk/src/@planx/components/List/model.ts, editor.planx.uk/src/@planx/components/List/schemas/ResidentialUnits.ts
- Adds a first pass of a possible "Residential units" schema
- Adds the concept (only enforced via UI) of a unique constraint
This is based on the following description - 
>For every unit we need to know:
> - Change type (proposed / existing)
> - Tenure type (single choice of 5 options)
> - Unit type (single choice of 6 options)
> - Number of bedrooms (number)
> - Optional: total number of identical units of this type (a way for the user to add multiples of identical units/clones without having to report them individually)
Source: https://opensystemslab.slack.com/archives/C04DZ1NBUMR/p1709126029217489 (OSL Slack)
This is very much a rough pass. I think a sensible next step would be to pass this along to the content team on a Pizza to at least have a look at to try and evaluate the next …
=> feat: List component - First iteration of a residential units schema

editor.planx.uk/src/@planx/components/List/Public/Context.tsx, editor.planx.uk/src/@planx/components/List/Public/index.test.tsx, editor.planx.uk/src/@planx/components/List/Public/index.tsx
- Submits validated form values via `handleSubmit()`
- This adds the values to the passport and breadcrumbs
- I don't think that what's in this PR is necessarily the right or final shape of this data, but this just serves to complete the wiring up of this component
- Pre-populate form values on "back" navigation
- Replaces brittle and repetitive test selectors with `data-testid` values (see https://github.com/theopensystemslab/planx-new/pull/3198#discussion_r1617316748)
=> feat: List component - submission and back navigation

editor.planx.uk/src/pages/FlowEditor/components/Flow/FeedbackPage.tsx, editor.planx.uk/src/routes/feedback.tsx
Adds a styled feedback table using the 'feed' style used for the submissions log.
- Data is separated into a summary row and further feedback on expand.
- Comments are truncated to 50 characters within the table, full comment in the expanded content. The first (bottom) example shows this.
- Help text is shown only for helpful/unhelpful help text feedback.
- User context is shown as the first item for "issue" type feedback, which corresponds to "What were you doing?" in the feedback form.
Example:
https://3208.planx.pizza/testing/find-out-if-you-need-planning-permission/feedback
=> feat: Styled feedback table

api.planx.uk/modules/send/email/index.test.ts
Sam reported this in help-issues: https://opendigitalplanning.slack.com/archives/C0241GWFG4B/p1717490595516369
My best guess is that `planners@southwark.gov.uk` might actually be a real email now & got forwarded to `rs@southwark.gov.uk` per her screenshot ?? Not sure why this happened for the first time last Friday, but this should hopefully prevent in future :crossed_fingers:
=> fix: remove "real" council email extensions in tests

editor.planx.uk/src/pages/FlowEditor/components/Sidebar/index.tsx, editor.planx.uk/src/pages/FlowEditor/lib/store/editor.ts, editor.planx.uk/src/pages/FlowEditor/utils.ts, editor.planx.uk/src/pages/Team.tsx
**Changes:**
August mentioned that it's really disorienting that all the flows within a team now show the same "Edited 5 days ago" timestamp - this is because this message was referencing `flows.updated_at` which changed when `flows.status` merged and is updated, whereas we really think about "edits" to a flow coming from the associated `operations`. 
Now updated to display based on `operations`, sharing the same formatting as in-graph view of "Last edited..." too. This means that both the list & graph timestamps will now match (previously they didn't :see_no_evil:), and that the list timestamps now ignore bulk flow migrations or non-data changes like renaming, toggling status, etc. 
See thread: https://opensystemslab.slack.com/archives/C5Q59R3HB/p1717571853477949
**Testing:**
Click into …
=> fix: list of flows should display and be sorted by most recent operations, not `flows.updated_at`

editor.planx.uk/src/@planx/components/Checklist/Public.tsx, editor.planx.uk/src/@planx/components/List/Editor.tsx, editor.planx.uk/src/@planx/components/List/Public/Context.tsx, editor.planx.uk/src/@planx/components/List/Public/Fields.tsx, editor.planx.uk/src/@planx/components/List/Public/index.test.tsx, editor.planx.uk/src/@planx/components/List/Public/index.tsx, editor.planx.uk/src/@planx/components/List/model.ts, editor.planx.uk/src/@planx/components/List/schemas/ResidentialUnits/Existing.ts, editor.planx.uk/src/@planx/components/List/schemas/ResidentialUnits/GLA/New.ts, editor.planx.uk/src/@planx/components/List/schemas/ResidentialUnits/GLA/Rebuilt.ts, editor.planx.uk/src/@planx/components/List/schemas/ResidentialUnits/GLA/Removed.ts, editor.planx.uk/src/@planx/components/List/schemas/ResidentialUnits/GLA/Retained.ts, editor.planx.uk/src/@planx/components/List/schemas/ResidentialUnits/Proposed.ts, editor.planx.uk/src/pages/FlowEditor/components/Flow/components/Node.tsx
Schemas based on this flow: https://editor.planx.uk/opensystemslab/residential-units
See thread here: https://opensystemslab.slack.com/archives/C5Q59R3HB/p1717676834944659?thread_ts=1717416055.509189&cid=C5Q59R3HB
Also adjusts summary totals calculated `onSubmit` to include both count of list items _and_ sum of all units.
Eventually, we'll want to calculate totals by tenure and unit type - but we should consider capturing the `val`, rather than `text` in the passport first.
=> chore: split residential unit List component schemas into six options

editor.planx.uk/src/@planx/components/List/Editor.tsx, editor.planx.uk/src/@planx/components/List/Public/Context.tsx, editor.planx.uk/src/@planx/components/List/Public/index.tsx, editor.planx.uk/src/@planx/components/List/model.ts, editor.planx.uk/src/@planx/components/shared/Preview/SummaryList.tsx
**Changes:**
- Adds basic `List` component representation to existing `SummaryList` Review page 
- Makes "title" & "fn" required in Editor to ensure necessary info is consistently available
- Displays one row _per_ List component
- If that List's schema includes a field that sets `identicalUnits`, then summary is "X units total"
- Else default to how many items/responses were provided, eg "X items total"
- "Change" link takes you back to the List component where you can edit your responses one-by-one
=> feat: basic summary of List component on Review page

editor.planx.uk/src/@planx/components/Pay/Public/Confirm.tsx, editor.planx.uk/src/@planx/components/Pay/Public/Pay.test.tsx, editor.planx.uk/src/pages/FlowEditor/components/Flow/FeedbackPage.tsx, editor.planx.uk/src/pages/FlowEditor/components/Settings/Submissions/EventsLog.tsx, editor.planx.uk/src/ui/shared/ErrorSummary.stories.tsx, editor.planx.uk/src/ui/shared/ErrorSummary.tsx
- Introduces a standardised error summary with three 'styles'; error, warning and info.
- Updates replicated error summaries
- Introduces error summary for feedback log with no entries
- Storybook story with each permutation 
**Preview:**
https://storybook.3259.planx.pizza/?path=/docs/design-system-molecules-errorsummary--docs
=> refactor: Standardise error summary

e2e/tests/ui-driven/src/context.ts, e2e/tests/ui-driven/src/invite-to-pay/agent.spec.ts, e2e/tests/ui-driven/src/invite-to-pay/nominee.spec.ts, e2e/tests/ui-driven/src/pay.spec.ts, e2e/tests/ui-driven/src/save-and-return.spec.ts, e2e/tests/ui-driven/src/sections.spec.ts
These changes work locally for me, hopefully will pass on CI too :crossed_fingers:
=> fix: make flow name required and update all contexts for passing e2e tests

editor.planx.uk/src/@planx/components/List/Editor.tsx, editor.planx.uk/src/@planx/components/List/schemas/GLA/BuildingDetails.ts, editor.planx.uk/src/@planx/components/List/schemas/GLA/CommunalSpace.ts, editor.planx.uk/src/@planx/components/List/schemas/GLA/ExistingAndProposedUses.ts, editor.planx.uk/src/@planx/components/List/schemas/GLA/OpenSpace.ts, editor.planx.uk/src/@planx/components/List/schemas/GLA/ProtectedSpace.ts, editor.planx.uk/src/@planx/components/List/schemas/ResidentialUnits/GLA/Gained.ts, editor.planx.uk/src/@planx/components/List/schemas/ResidentialUnits/GLA/Lost.ts
Includes the following schemas:
- GLA gained & lost structure
- GLA existing and proposed uses 
- GLA building details
- GLA communal spaces
- GLA open spaces
- GLA protected spaces
=> feat: Add new GLA schemas

editor.planx.uk/src/lib/featureFlags.ts, editor.planx.uk/src/pages/FlowEditor/components/forms/FormModal.tsx, editor.planx.uk/src/pages/Preview/Node.tsx
August has written schemas & the UI is mostly working as expected - so let's remove the feature flag on staging & open it up for PO testing! 
It won't be used in any "live" services just yet.
=> chore: drop "LIST_COMPONENT" feature flag

editor.planx.uk/src/pages/FlowEditor/index.tsx
The 'last edited' banner seems redundant now we have full edit history available. Removing it also maximises graph canvas area.
**Example:**
https://3277.planx.pizza/buckinghamshire/upload-completion-of-works-notice
=> refactor: Remove last edited banner from editor

api.planx.uk/modules/pay/service/inviteToPay/createPaymentSendEvents.test.ts, api.planx.uk/modules/pay/service/inviteToPay/sendConfirmationEmail.test.ts, api.planx.uk/modules/pay/service/inviteToPay/sendConfirmationEmail.ts, api.planx.uk/modules/pay/service/inviteToPay/sendPaymentEmail.ts, api.planx.uk/modules/saveAndReturn/service/resumeApplication.test.ts, api.planx.uk/modules/saveAndReturn/service/utils.ts, api.planx.uk/modules/send/email/index.test.ts, api.planx.uk/modules/send/email/index.ts, api.planx.uk/modules/send/email/service.ts, api.planx.uk/package.json, api.planx.uk/pnpm-lock.yaml, api.planx.uk/tests/mocks/inviteToPayData.ts, api.planx.uk/tests/mocks/inviteToPayMocks.ts, api.planx.uk/tests/mocks/saveAndReturnMocks.ts, api.planx.uk/types.ts, e2e/tests/api-driven/package.json, e2e/tests/api-driven/pnpm-lock.yaml, e2e/tests/ui-driven/package.json, e2e/tests/ui-driven/pnpm-lock.yaml, editor.planx.uk/package.json, editor.planx.uk/pnpm-lock.yaml
This PR follows on from other PRs which have added the ``name`` column to the ``flows`` table and created functionality for users to add a flow name to their team's flows. 
The final part of this work is to update email templates so the ``Session Name`` is the user generated ``name`` rather than the augmented ``flowSlug``
=> feat: Updating Email Templates with Flow Name

api.planx.uk/modules/flows/validate/helpers.ts, api.planx.uk/modules/flows/validate/service.ts, api.planx.uk/modules/flows/validate/validate.test.ts, editor.planx.uk/src/pages/FlowEditor/components/Sidebar/PublishDialog.tsx, editor.planx.uk/src/pages/FlowEditor/components/Sidebar/index.tsx, editor.planx.uk/src/pages/FlowEditor/utils.ts
As a first step towards the attached ticket for adding _more_ validation checks on Publish, I'm refactoring a bit how our existing validation checks are organised and displayed.
**Changes:**
- [API] The `/flows/:flowId/diff` endpoint will now always return a list of `validationChecks` when `alteredNodes` is not null (meaning anytime there are changes queued to publish) independent of the status of each validation check
- Previously, the whole endpoint would return an error for the first failed validation check it found
- [Editor] The "Check for changes to publish" dialog now displays each validation check. If any check has "failed", the "Publish" button will be disabled.
- Currently, the same validation checks are run across _all flows_, so some checks may appear as "Not applicable" …
=> feat: display existing validation checks in publish dialog

editor.planx.uk/src/theme.ts
Quick one: reduces height of updated MUI switch to be more in balance with other form elements.
**Before:**
**After:**
=> refactor: Reduce height of MUI switch

infrastructure/application/Pulumi.production.yaml, infrastructure/application/Pulumi.staging.yaml, infrastructure/application/services/hasura.ts
- There's been an increase in downtime for Hasura recently
- A quick look at the service health on AWS suggests this may be due to hitting max CPU, which may lead to timeouts (see screenshots for overview of past two weeks below)
- Double CPU and memory, and monitor going forward
- CPU and memory are inline with task sizes outlined here - https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#task_size
=> chore: Bump Hasura Fargate task CPU and memory (production)

e2e/tests/api-driven/src/permissions/queries/flows.ts, hasura.planx.uk/migrations/1718705200477_alter_table_public_flows_alter_column_name/down.sql, hasura.planx.uk/migrations/1718705200477_alter_table_public_flows_alter_column_name/up.sql, hasura.planx.uk/tests/portals.test.js, hasura.planx.uk/tests/sessions.test.js, sharedb.planx.uk/sharedb-postgresql.js
- Following on from @RODO94's work to add the `flow.name` column, this has now been updated to be a required field in the DB, which matches the associated types and expected behaviour
- Updates a number of tests and functions which required a value for `flow.name`
The reason there's so much "whack-a-mole" with some of these tests is that `flow.name` and `flow.team_id` are now really the compound primary key / unique constraints, not `flow.slug` and `flow.team_id`. A more robust solution may be to make this change in reality in the database, and to correspondingly update mocks to just have a `flow.name` value.
Regression tests passing here - https://github.com/theopensystemslab/planx-new/actions/runs/9565438594 ✅
=> chore: Make `flow.name` column required

editor.planx.uk/package.json, editor.planx.uk/pnpm-lock.yaml
Fixes https://github.com/theopensystemslab/planx-new/security/dependabot/87
`pnpm why ip` shows this was used by Storybook. Following a patch to Storybook they no longer use this package.
=> fix: CVE-2024-29415

editor.planx.uk/src/components/Header.tsx
2 changes to editor header:
Adds an underline to reenforce the "breadcrumbs as vertical navigation" concept
This will eventually be used for the "Account" menu, but I've added the word "Menu" until the new navigation menus are ready.
=> feat: Updated editor header styles

editor.planx.uk/src/pages/FlowEditor/components/Settings/DesignSettings/index.tsx, editor.planx.uk/src/ui/editor/ImgInput.tsx
Quick one, addresses small issues with image upload and design settings layout.
Previously the uploaded image was being stretched which makes it hard to decipher the image if it is not square:
Having the preview left-aligned means you can't preview what is being applied when the colour picker is open, centering helps with this:
=> fix: Image upload stretch and design settings

e2e/tests/ui-driven/src/create-flow/helpers.ts, e2e/tests/ui-driven/src/login.spec.ts, editor.planx.uk/src/pages/Team.tsx, editor.planx.uk/src/pages/Teams.tsx, editor.planx.uk/src/routes/authenticated.tsx, editor.planx.uk/src/ui/editor/Dashboard.tsx
Introduces style and minor structural changes across Teams and Team pages.
- Background changed to light
- Council branding added to teams list
- Teams list separated into separate lists based on permissions, teams which a user has editing permissions to will appear first
- Services styled similar to editor portals
In addition to this a `<Dashboard>` component has been created to standardise layout and spacing across editor pages (applied to only these two pages for now). This also contains layout styles that make it ready to drop in the editor in-page navigation elements.
=> feat: Updated editor teams and team selection pages

editor.planx.uk/src/pages/FlowEditor/components/Settings/GeneralSettings/index.tsx, hasura.planx.uk/metadata/tables.yaml, hasura.planx.uk/migrations/1719307850258_alter_table_public_team_settings_drop_column_has_planning_data/down.sql, hasura.planx.uk/migrations/1719307850258_alter_table_public_team_settings_drop_column_has_planning_data/up.sql
Following #3305, it was found that the ``has_planning_data`` column of the "team_settings" table is redundant and should be removed.
This PR creates the necessary migrations and table permission changes to remove the column
=> chore: Remove ``has_planning_data`` from team_settings table

hasura.planx.uk/metadata/tables.yaml, scripts/seed-database/container.sh, scripts/seed-database/write/main.sql, scripts/seed-database/write/team_settings.sql
## What does this PR do?
This PR follows #3289 and #3314 which have added the new ``team_settings`` table to the database. With the new table, there is a need to create scripts to pull data from the production database when new, local databases are created for containers. 
This PR will enable this pulling of production ``team_settings`` data
In addition, I have added a relationship between the `teams` table and the `team_settings` table to enable a link when creating queries.
=> feat: add scripts for pulling ``team_settings`` data from production

editor.planx.uk/src/@planx/components/Checklist/Public.test.tsx, editor.planx.uk/src/ui/shared/Checkbox.tsx
I hit some strange checkbox behaviour when working on https://github.com/theopensystemslab/planx-new/pull/3304 which sidetracked me somewhat! See video below for demo - 
https://github.com/theopensystemslab/planx-new/assets/20502206/47b90a82-ebf6-477d-9a63-184fb7879cd6
What's happening is - 
- Clicking labels behaves as expected
- Clicking checkbox fires event (`onChange()` function) twice, resulting in nondeterministic updates when combined with async state updates (via Formik)
We can check this out by using a `console.log()` inside our `onChange()` function and seeing that it fires multiple times (event outside the scope of React's strict mode). Another good example of this, which is now fixed in this PR, is that selecting checkboxes in the Editor's send component triggers an alert …
=> fix: Prevent event bubbling on click of checkbox

editor.planx.uk/src/@planx/components/List/Public/Fields.tsx
Quick one: adds a negative margin to `</RadioGroup>` in the List component to negate the extra margin caused by using this inline (radio button rows have margin-bottom to ensure layout spacing).
**Before vs after:**
=> fix: List component radio remove extra margin

editor.planx.uk/src/@planx/components/List/Public/index.test.tsx, editor.planx.uk/src/@planx/components/List/schemas/mocks/GenericUnits.ts
- There was a skipped test introduced in #3263 
- This was failing when un-skipped, as react-testing-library was unable to locate DOM elements to interact with
Variables need be be reinstated when a new list item is added, otherwise they hold onto their old references and are invalid.
=> test: Fix skipped List component test

api.planx.uk/modules/admin/session/digitalPlanningData.ts
Fix for #3325 - we need to just log the full error to get the trace.
=> fix: Log raw error without `JSON.stringify()`

api.planx.uk/modules/admin/session/digitalPlanningData.ts
Another crack at #3325 and #3327 🤞
=> fix: Log error stack explicitly on DPA failures

editor.planx.uk/src/@planx/components/List/Public/Fields.tsx, editor.planx.uk/src/@planx/components/List/Public/index.test.tsx, editor.planx.uk/src/@planx/components/List/model.ts
- Remove the `Field["required"]` property
- Please see discussion here for context - https://opensystemslab.slack.com/archives/C5Q59R3HB/p1719487898561029 (OSL Slack)
=> feat: Remove optional/required distinction in List schema

editor.planx.uk/src/@planx/components/shared/index.test.ts, editor.planx.uk/src/@planx/components/shared/index.ts, editor.planx.uk/src/pages/FlowEditor/components/forms/FormModal.tsx
Raised as an issue here - https://opensystemslab.slack.com/archives/C01E3AC0C03/p1719495568931289 (OSL Slack)
Currently, this works on node update via `sanitize()` within the `_update()` function which handled operations. `sanitise()` is not set up in quite the same way for add node, so I'm handling this at the `parseFormData()` level.
=> fix: Trim all form values on node creation

editor.planx.uk/src/@planx/components/List/Public/Fields.tsx, editor.planx.uk/src/@planx/components/List/Public/index.test.tsx, editor.planx.uk/src/@planx/components/List/model.ts
- Removes the `QuestionField["unique"]` property
- Please see https://github.com/theopensystemslab/planx-new/pull/3222 for further context
- It's not currently used or necessary for existing schemas
- There's likely better ways of handling this (e.g. pre-populating forms, not putting the onus on the user to manage this)
- It's only being enforced via the UI, and not in the schema currently
=> feat: Remove 'unique' property from List schema (`QuestionField`)

editor.planx.uk/src/@planx/components/List/Public/Context.tsx, editor.planx.uk/src/@planx/components/List/Public/Fields.tsx, editor.planx.uk/src/@planx/components/List/Public/index.test.tsx, editor.planx.uk/src/@planx/components/List/schemas/mocks/Zoo.ts
- Complete remaining `test.todo()`s following on from https://github.com/theopensystemslab/planx-new/pull/3217
- These tests check error handling and form validation within the list component
- There's an outstanding validation test for checklists, I'll either pick this up here as a subsequent commit, or on https://github.com/theopensystemslab/planx-new/pull/3304 (dependant on merge order)
=> test: Outstanding List component validation tests

editor.planx.uk/src/@planx/components/SetValue/Editor.tsx, editor.planx.uk/src/@planx/components/SetValue/model.ts, editor.planx.uk/src/@planx/components/SetValue/utils.ts
- Makes `val` an optional field in the SetValue component if the operation is `removeAll`
- Updates types
- Conditionally hides form field
=> fix: Make `val` optional in SetValue component

editor.planx.uk/src/@planx/components/ui.tsx, editor.planx.uk/src/pages/FlowEditor/components/Flow/FeedbackPage.tsx, editor.planx.uk/src/pages/FlowEditor/components/Settings/DataManagerSettings.tsx, editor.planx.uk/src/pages/FlowEditor/components/Settings/DesignSettings/ButtonForm.tsx, editor.planx.uk/src/pages/FlowEditor/components/Settings/DesignSettings/FaviconForm.tsx, editor.planx.uk/src/pages/FlowEditor/components/Settings/DesignSettings/TextLinkForm.tsx, editor.planx.uk/src/pages/FlowEditor/components/Settings/DesignSettings/ThemeAndLogoForm.tsx, editor.planx.uk/src/pages/FlowEditor/components/Settings/DesignSettings/index.tsx, editor.planx.uk/src/pages/FlowEditor/components/Settings/GeneralSettings/BoundaryForm.tsx, editor.planx.uk/src/pages/FlowEditor/components/Settings/GeneralSettings/ContactForm.tsx, editor.planx.uk/src/pages/FlowEditor/components/Settings/GeneralSettings/index.tsx, editor.planx.uk/src/pages/FlowEditor/components/Settings/ServiceFlags.tsx, editor.planx.uk/src/pages/FlowEditor/components/Settings/ServiceSettings.tsx, editor.planx.uk/src/pages/FlowEditor/components/Settings/Submissions/index.tsx, editor.planx.uk/src/pages/FlowEditor/components/Settings/TeamSettings.tsx, editor.planx.uk/src/pages/FlowEditor/components/Settings/shared/SettingsForm.tsx, editor.planx.uk/src/pages/FlowEditor/components/Team/TeamMembers.tsx, editor.planx.uk/src/pages/GlobalSettings.tsx, editor.planx.uk/src/routes/teamSettings.tsx, editor.planx.uk/src/ui/editor/InputLabel.tsx, editor.planx.uk/src/ui/editor/InputLegend.tsx, editor.planx.uk/src/ui/editor/SettingsDescription.tsx, editor.planx.uk/src/ui/editor/SettingsRow.tsx, editor.planx.uk/src/ui/editor/SettingsSection.tsx
Refactors settings pages to use a simplified and unified structure.
- Introduces dedicated `<InputLabel>` for editor
- `<EditorRow>` renamed to `<SettingsSection>` to differentiate from `<ModalSection>` as used in the graph editor
- `<InputDescription>` renamed to `<SettingsDescription>`
- Changes applied to Team settings page: https://3324.planx.pizza/barking-and-dagenham/settings/general
- Changes applied to Design page: https://3324.planx.pizza/barking-and-dagenham/settings/design
- Changes applied to Global settings page: https://3324.planx.pizza/global-settings
**To do before merging**
=> refactor: Editor forms tidy up and unify

.env.example, api.planx.uk/lib/hasura/metadata/index.ts, api.planx.uk/modules/send/createSendEvents/controller.ts, api.planx.uk/modules/send/createSendEvents/types.ts, api.planx.uk/modules/send/idox/nexus.test.ts, api.planx.uk/modules/send/idox/nexus.ts, api.planx.uk/modules/send/routes.ts, api.planx.uk/modules/send/utils/exportZip.ts, editor.planx.uk/src/@planx/components/Send/Editor.tsx, editor.planx.uk/src/@planx/components/Send/Public.tsx, editor.planx.uk/src/@planx/components/Send/model.ts
We'll hopefully be able to test the new Idox Nexus integration on staging soon, and these changes should make it easier to plug in new credentials (see example env var `IDOX_NEXUS_CLIENT`) and get up & running on staging pretty quickly!
**Changes:**
- Adds "Idox Nexus" as a selectable "Send" component destination on staging-only
- Creates send events for Idox Nexus
- Adds API route `/idox/:localAuthority` (we'll still use local authority param for audit tables, but _not_ for fetching team creds)
- This copies existing `uniform` module and updates the client auth, zip folder, and error messages to be unique with hope of fully retiring uniform in near future ! (therefore removing code duplication)
- Adds `onlyDigitalPlanningJSON` argument to `buildSubmissionZip` to generate a zip file which …
=> feat: stub out editor & API endpoint and send events for Idox Nexus

editor.planx.uk/src/@planx/components/Checklist/Public.tsx, editor.planx.uk/src/@planx/components/Checklist/model.ts, editor.planx.uk/src/@planx/components/List/Editor.tsx, editor.planx.uk/src/@planx/components/List/Public/Context.tsx, editor.planx.uk/src/@planx/components/List/Public/Fields.tsx, editor.planx.uk/src/@planx/components/List/Public/index.test.tsx, editor.planx.uk/src/@planx/components/List/Public/index.tsx, editor.planx.uk/src/@planx/components/List/model.ts, editor.planx.uk/src/@planx/components/List/schemas/ResidentialUnits/GLA/Gained.ts, editor.planx.uk/src/@planx/components/List/schemas/ResidentialUnits/GLA/Lost.ts, editor.planx.uk/src/@planx/components/List/schemas/ResidentialUnits/GLA/New.ts, editor.planx.uk/src/@planx/components/List/schemas/ResidentialUnits/GLA/Rebuilt.ts, editor.planx.uk/src/@planx/components/List/schemas/ResidentialUnits/GLA/Removed.ts, editor.planx.uk/src/@planx/components/List/schemas/mocks/Zoo.ts, editor.planx.uk/src/@planx/components/List/utils.test.ts, editor.planx.uk/src/@planx/components/List/utils.ts, editor.planx.uk/src/@planx/components/List/utils.tsx, editor.planx.uk/src/ui/shared/Checkbox.tsx
- Introduces a `ChecklistField` for the List component
- As with our other fields, this requires making the validation schema shared
- Updates existing schemas to use checklists instead of a series of questions
- Updates tests
- Update `flatten()` logic to handle checklist responses
=> feat: `ChecklistFieldInput` for List component

api.planx.uk/pnpm-lock.yaml, e2e/tests/api-driven/pnpm-lock.yaml, e2e/tests/ui-driven/pnpm-lock.yaml, editor.planx.uk/pnpm-lock.yaml, hasura.planx.uk/tests/pnpm-lock.yaml
Take 2 on #3355 
`pnpm i --fix-lockfile` run on each project. Docs: https://pnpm.io/cli/install#--fix-lockfile
=> chore: Fix broken lockfiles

api.planx.uk/package.json, e2e/package.json, e2e/tests/api-driven/package.json, e2e/tests/ui-driven/package.json, editor.planx.uk/package.json, hasura.planx.uk/package.json, infrastructure/application/package.json, infrastructure/certificates/package.json, infrastructure/data/package.json, infrastructure/networking/package.json, scripts/encrypt/package.json, sharedb.planx.uk/package.json
- Dependabot updates are not using the correct pnpm version following the release of pnpm v9, and associated GitHub action updates
- This means that the incorrect lockfile versions are used (v9 instead of v6)
- See example here - https://github.com/theopensystemslab/planx-new/pull/3357 (screenshot below)
- Add `"packageManager"` field to all `package.json` files
- Please see https://github.com/dependabot/dependabot-core/issues/9684
- We could (should?) also take a look at jumping to pnpm v9 sometime soon
=> chore: Add `packageManager` field to all `package.json` files

editor.planx.uk/src/@planx/components/List/utils.tsx
A small thing spotted during demo this morning!
Since many schemas are using a Number input to collect area, we should ensure the `m2` units is consistently displayed on _both_ the active & inactive List when it's defined.
=> chore: show number units on inactive List if defined

editor.planx.uk/src/pages/FlowEditor/components/Settings/GeneralSettings/BoundaryForm.tsx, editor.planx.uk/src/pages/FlowEditor/components/Settings/GeneralSettings/ContactForm.tsx, editor.planx.uk/src/pages/FlowEditor/components/Settings/GeneralSettings/index.tsx, editor.planx.uk/src/pages/FlowEditor/components/Settings/shared/SettingsForm.tsx, editor.planx.uk/src/pages/FlowEditor/lib/store/team.ts, editor.planx.uk/src/routes/teamSettings.tsx
_This is a cleaner branch from the work undertaken on this previous branch: #3319_ 
Continuing work on the ``team_settings`` implementation, this PR pulls in data from the database with a graphQL query and populates the corresponding form inputs.
This PR also uses the update mutation, similar to `team_themes` to update the form fields and database. 
This PR aligns with a planx-core change where the requests and types for a Team were altered to incorporate the new ``team_settings`` table.
[Reference to the planx-core changes](https://github.com/theopensystemslab/planx-core/pull/424)
> Important to note that this PR has not deleted any functions, methods, or types related to previous versions of `notifyPersonalisation` or the original ``settings`` column of _"teams"_ table. Thinking is to …
=> feat: Fetch `team_settings` data for Editor forms and adding Update fn

editor.planx.uk/src/@planx/components/List/Public/Context.tsx, editor.planx.uk/src/@planx/components/List/Public/Fields.tsx, editor.planx.uk/src/@planx/components/List/Public/index.test.tsx, editor.planx.uk/src/@planx/components/List/Public/index.tsx, editor.planx.uk/src/@planx/components/Send/Public.tsx, editor.planx.uk/src/@planx/components/SetValue/Editor.tsx, editor.planx.uk/src/ui/shared/Checkbox.tsx
Possibly due to prettier updates, or Husky not running correctly (maybe due to CLI commits being done in another directory?) a few files have lining issues. This was recently highlighted here - https://github.com/theopensystemslab/planx-new/pull/3367#discussion_r1664170802
I'll aim to take another look at the Husky setup, especially as there's a new major version.
=> chore: Run `pnpm lint:fix` in Editor

editor.planx.uk/src/pages/FlowEditor/components/Settings/DesignSettings/ButtonForm.tsx, editor.planx.uk/src/pages/FlowEditor/components/Settings/DesignSettings/TextLinkForm.tsx, editor.planx.uk/src/pages/FlowEditor/components/Settings/DesignSettings/ThemeAndLogoForm.tsx, editor.planx.uk/src/pages/FlowEditor/components/Settings/GeneralSettings/BoundaryForm.tsx, editor.planx.uk/src/pages/FlowEditor/components/Settings/GeneralSettings/ContactForm.tsx, editor.planx.uk/src/pages/FlowEditor/components/Settings/shared/SettingsForm.tsx, editor.planx.uk/src/ui/editor/ColorPicker.tsx
Following previous work done on `team_settings` form in the Editor: https://github.com/theopensystemslab/planx-new/pull/3366
This PR will introduce the Error Handling while making changes to shared `SettingsForm` to handle error messaging on an input level rather than form level.
The only change to an _Input Component_ will be to the ``<ColourPicker>`` which is used in the ``Theme`` settings forms. The prop ``errorMessage`` has been added to the ``<ColourPicker>`` component to enable this input level error messaging
=> feat: `team_settings` form error validation

hasura.planx.uk/metadata/tables.yaml, hasura.planx.uk/migrations/1720175441656_alter_table_public_team_settings_alter_column_boundary_json/down.sql, hasura.planx.uk/migrations/1720175441656_alter_table_public_team_settings_alter_column_boundary_json/up.sql
This PR will set up work to add a outer boundary json to the database for a local authority using the data in the `boundary_url` column
Following this work, when a user updates the `boundary_url` column, it will trigger a fetch to get the GeoJSON and then pass it through **turf.js** to turn it into a ``boundary_bbox`` JSON. This initial migration will enable easier follow on work.
=> feat: `team_settings` column rename from `boundary_json` to `boundary_bbox`

editor.planx.uk/src/@planx/components/FileUpload/Public.tsx, editor.planx.uk/src/@planx/components/FileUploadAndLabel/Public.tsx, editor.planx.uk/src/@planx/components/FileUploadAndLabel/schema.ts, editor.planx.uk/src/@planx/components/shared/PrivateFileUpload/UploadedFileCard.tsx
- Follow up to https://github.com/theopensystemslab/planx-core/pull/434 - this PR now catches these errors client side and allows the user the opportunity to resolve them
- Displays error if a file upload fails
- Displays error if user tries to proceed with files with a status of `"error"`
- It could be nice to add a "retry" button on failed uploads, but this will be covering a edge case. To our knowledge, a user submitting files which have failed to upload has only happened twice.
=> feat: Add error handling for failed file uploads

hasura.planx.uk/metadata/tables.yaml
Reported via #help-issues, see thread here: https://opensystemslab.slack.com/archives/C01E3AC0C03/p1720455630197209
Reminder difficult to test this on pizzas & staging because data syncs (it correctly says "Created flow" here!) but we'll be able to fully test once on prod (by toggling platformAdmin to false and checking "History" tab)
=> fix: allow teamEditor to select all rows from users table

e2e/tests/api-driven/src/permissions/teamAdmin.feature
Follow up to https://github.com/theopensystemslab/planx-new/pull/3390
🚀 Regression tests running against this branch here - https://github.com/theopensystemslab/planx-new/actions/runs/9853501058
=> test: Remove redundant test following `teamEditor` permission update

editor.planx.uk/src/@planx/components/Send/Editor.tsx
Barnet is ready to go live with Report a Breach using S3 / Power Automate integration solution
=> chore: enable AWS S3 Send destination on production

editor.planx.uk/src/routes/views/draft.tsx, editor.planx.uk/src/routes/views/published.tsx, editor.planx.uk/src/routes/views/standalone.tsx
Quick fix for https://opensystemslab.slack.com/archives/C4B0CKQ3U/p1720531966270509
This PR ensures that the queries for `/draft`, `/preview`, and `/published` request `teamSettings` - this matches the current type, as expected by the store function `setTeam()`.
A more comprehensive fix, which avoid the nested `team.teamSettings` syntax and fixed types is incoming here - https://github.com/theopensystemslab/planx-new/pull/3391
=> fix: Use `teamSettings` instead of `settings` in query

api.planx.uk/modules/send/s3/index.test.ts, api.planx.uk/modules/send/s3/index.ts, hasura.planx.uk/metadata/tables.yaml, hasura.planx.uk/migrations/1720597665798_create_table_s3_applications/down.sql, hasura.planx.uk/migrations/1720597665798_create_table_s3_applications/up.sql, hasura.planx.uk/tests/s3_applications.test.js
Quick final step in helping Barnet go live with S3/Power Automate submissions soon. 
Adds a basic audit table for tracking application data.
=> feat: add an audit table for applications submitted via S3 and Power Automate

.github/workflows/pizza-teardown-manual.yml
- The GitHub action "Pizza Teardown (Manual)" is currently failing with the following errors (see screenshot below)
- Link to recent failed run of this action here - https://github.com/theopensystemslab/planx-new/actions/runs/9873182798 
- Update action to use variables from [vultr-action@v2.0 update](https://github.com/theopensystemslab/vultr-action/releases/tag/v2.0)
=> fix: Update Pizza Teardown (Manual) GitHub action variables

editor.planx.uk/src/@planx/components/ui.tsx
Addresses issue discussed here (OSL Slack) -https://opensystemslab.slack.com/archives/C01E3AC0C03/p1720190594916289
=> fix: Associate label and input in `MoreInformation`

editor.planx.uk/src/@planx/components/PlanningConstraints/List.tsx
- Adds missing `key` prop
- Ensures we use correct semantic HTML hierarchy by not wrapping HTML in paragraph element
=> fix: React warnings on `PlanningConstraints` component

editor.planx.uk/src/@planx/components/Section/Public.tsx, editor.planx.uk/src/@planx/components/shared/Preview/Card.tsx, editor.planx.uk/src/components/Header.tsx, editor.planx.uk/src/lib/feedback.ts, editor.planx.uk/src/pages/FlowEditor/lib/__tests__/clones.test.ts, editor.planx.uk/src/pages/FlowEditor/lib/__tests__/filters.test.ts, editor.planx.uk/src/pages/FlowEditor/lib/__tests__/preview/canGoBack.test.ts, editor.planx.uk/src/pages/FlowEditor/lib/__tests__/preview/overrideAnswer.test.ts, editor.planx.uk/src/pages/FlowEditor/lib/__tests__/preview/previousCard.test.ts, editor.planx.uk/src/pages/FlowEditor/lib/__tests__/preview/removeNodesDependentOnPassport.test.ts, editor.planx.uk/src/pages/FlowEditor/lib/__tests__/preview/upcomingCardIds.test.ts, editor.planx.uk/src/pages/FlowEditor/lib/__tests__/setValue.test.ts, editor.planx.uk/src/pages/FlowEditor/lib/analytics/provider.tsx, editor.planx.uk/src/pages/FlowEditor/lib/store/preview.ts, editor.planx.uk/src/pages/Preview/Questions.tsx, editor.planx.uk/src/pages/Preview/ReconciliationPage.tsx
- Navigating through a sufficiently large flow can crash PlanX
- This generally happens when navigating backwards, and can be triggered consistently when navigating back to or from a section component (though not exclusively)
- Chrome freezer / runs out of memory
- Raised as an issue here (PlanX Slack) - https://opensystemslab.slack.com/archives/C01E3AC0C03/p1720449876847459
- Consistenly recreateable on this flow when reaching the first section marker - https://editor.planx.dev/buckinghamshire/apply-for-planning-permission/published
When running the application in dev mode, the following two errors generally coincide with the above occurrence - 
The stack traces of these errors point to the following lines of code respectively - …
=> fix: Reduce React re-renders when checking `currentCard()`

hasura.planx.uk/metadata/tables.yaml, hasura.planx.uk/migrations/1720635370662_add_s3_applications_to_submissions_summary_view/down.sql, hasura.planx.uk/migrations/1720635370662_add_s3_applications_to_submissions_summary_view/up.sql
Follow up from https://github.com/theopensystemslab/planx-new/pull/3397#discussion_r1672005478
Adds two new columns:
- `sent_to_s3_power_automate` (boolean)
- `s3_applications` (jsonb)
Updated column-select permissions throughout for `platformAdmin` & `teamEditor` roles which had fallen quite out of date with recent column changes (all sanitised data here so no select-all concerns).
=> chore: add columns to `submissions_services_summary` for S3 applications

editor.planx.uk/src/airbrake.ts, editor.planx.uk/src/routes/utils.ts
The CNAME record is set up and stable despite no confirmation back from E&E directly - https://planningservices.epsom-ewell.gov.uk/
**To Do**
=> chore: Finalise Epsom and Ewell subdomain setup

api.planx.uk/modules/pay/service/inviteToPay/sendConfirmationEmail.ts, api.planx.uk/modules/pay/service/inviteToPay/sendPaymentEmail.ts, api.planx.uk/modules/saveAndReturn/service/resumeApplication.test.ts, api.planx.uk/modules/saveAndReturn/service/resumeApplication.ts, api.planx.uk/modules/saveAndReturn/service/utils.test.ts, api.planx.uk/modules/saveAndReturn/service/utils.ts
Quick tidy up - this was missed when adding the `flow.name` column.
=> chore: Remove redundant `convertSlugToName` util

editor.planx.uk/src/components/Header.tsx, editor.planx.uk/src/pages/FlowEditor/components/Sidebar/index.tsx, editor.planx.uk/src/ui/editor/Permission.tsx
- Adds a `Permission` component which abstracts away the need to fetch and check a user in multiple places
- Over time we can build this up to either map to a permission model, or just a series of static properties like the two added here
- Useful to have in place for https://github.com/theopensystemslab/planx-new/pull/3336 where this was a bit of a blocker
=> feat: `Permission` component

editor.planx.uk/src/pages/FlowEditor/lib/store/editor.ts, editor.planx.uk/src/routes/flow.tsx, editor.planx.uk/src/routes/flowSettings.tsx, editor.planx.uk/src/routes/views/flowEditor.tsx
When creating a new flow, the status shows as "online" if accessed via the Editor Menu. If we check the database, this is set to "offline" (and all tests for triggers etc are passing) - it's just a frontend visual bug.
Somewhere in the Editor Menu work a regression has slipped in which changed the way data was fetched. When accessing it via the dropdown menu, there's no issues. When accessing via the Editor Menu, the correct data is not fetched.
This is what's causing E2E tests to fail in https://github.com/theopensystemslab/planx-new/pull/3408 & https://github.com/theopensystemslab/planx-new/pull/3409
- Only fetch flow settings when navigating to flow/settings
- Make this an async request
- Make query names unique (made debugging this more tricky as we had multiple `GetFlow` queries)
=> fix: Correctly populate flow settings and status

editor.planx.uk/src/components/EditorNavMenu.tsx
- Only displays menu items which a user can access
- Please see https://opensystemslab.slack.com/archives/C01E3AC0C03/p1720786056596119 (OSL Slack) for context
Ideally it would be nice to encode this in our routing system once and use it to also limit access, as opposed to keeping it in the menu and having to add wrappers to views. But this feels like a quick and pragmatic option for now 👍
=> feat: Make `EditorNavMenu` items permission based

api.planx.uk/modules/saveAndReturn/service/utils.ts, editor.planx.uk/src/routes/views/draft.tsx, editor.planx.uk/src/routes/views/published.tsx, editor.planx.uk/src/routes/views/standalone.tsx
Fixes for a few errors which popped up post production-deply.
=> fix: Correct destructuring in queries for `teamSettings`

editor.planx.uk/src/lib/graphql.ts
Follow up to #3393 
Currently this is just (predictably!) `[object Object]` which isn't very helpful.
=> chore: Improve network error logging

api.planx.uk/modules/gis/service/digitalLand.ts
Reverts theopensystemslab/planx-new#3195
Geometries, especially for flood zones, are huge - let's ensure we're not unnecessarily saving them in our breadcrumbs. See issue thread from August about Chrome running out of memory: https://opensystemslab.slack.com/archives/C01E3AC0C03/p1720449876847459
=> Revert "fix: GIS API should return geometry"

editor.planx.uk/src/routes/index.tsx
See thread https://opensystemslab.slack.com/archives/C5Q59R3HB/p1721054184936579
Follows same pattern as #3147 so that the advertised `/preview` link redirects to the "offline" `/published` link.
=> fix: temporary redirect for Canterbury FOI service

api.planx.uk/modules/pay/service/inviteToPay/sendConfirmationEmail.test.ts, api.planx.uk/modules/pay/service/inviteToPay/sendConfirmationEmail.ts, api.planx.uk/modules/pay/service/inviteToPay/sendPaymentEmail.test.ts, api.planx.uk/modules/pay/service/inviteToPay/sendPaymentEmail.ts, api.planx.uk/modules/saveAndReturn/service/resumeApplication.test.ts, api.planx.uk/modules/saveAndReturn/service/resumeApplication.ts, api.planx.uk/modules/saveAndReturn/service/utils.ts, api.planx.uk/modules/sendEmail/index.test.ts, api.planx.uk/package.json, api.planx.uk/pnpm-lock.yaml, e2e/tests/api-driven/package.json, e2e/tests/api-driven/pnpm-lock.yaml, e2e/tests/api-driven/src/globalHelpers.ts, e2e/tests/api-driven/src/invite-to-pay/helpers.ts, e2e/tests/ui-driven/package.json, e2e/tests/ui-driven/pnpm-lock.yaml, e2e/tests/ui-driven/src/invite-to-pay/mocks.ts, e2e/tests/ui-driven/src/invite-to-pay/nominee.spec.ts, e2e/tests/ui-driven/src/mocks/flows/invite-to-pay-flow.ts, editor.planx.uk/package.json, editor.planx.uk/pnpm-lock.yaml, editor.planx.uk/src/pages/Pay/MakePayment.tsx
See https://github.com/theopensystemslab/planx-core/pull/445 for context!
Regression tests timing out on this branch - no errors, not sure why yet ! https://github.com/theopensystemslab/planx-new/actions/runs/9911311940 (likely related to team_settings - let's merge to `main` & fix forward!)
Will drop `project_types` table in a followup PR.
=> chore: refactor `formatRawProjectTypes` (take 2)

editor.planx.uk/src/routes/index.tsx
There's a typo here that I didn't spot when copy+pasting from Slack :see_no_evil: 
Page is currently redirecting to "Not found" whereas we want it to go to "Offline" - so no immediate rush to prod deploy (preview is still technically unavailable as intended!), but we want this fixed later today ideally
=> fix: correct Canterbury redirect

editor.planx.uk/src/pages/FlowEditor/components/Settings/GeneralSettings/ContactForm.tsx, editor.planx.uk/src/pages/FlowEditor/components/Settings/GeneralSettings/ReferenceCodeForm.tsx, editor.planx.uk/src/pages/FlowEditor/components/Settings/GeneralSettings/index.tsx
- Adds a field for reference code to the team setting page
- This is a required field for submissions (`metadata.organisation`) and should be exposed via the Editor
=> feat: Add reference code field to team settings

editor.planx.uk/src/@planx/components/PlanningConstraints/List.tsx
A minor first step at working towards "overriding" constraints by providing the user more context about each constraint. 
Replaces #3216
**Changes:**
- For a constraint that does apply, each entity listed will link to it's entity page on Planning Data (much more reliable than "document-url" field previously used as "source" link)
- In the case of roads, which are not sourced from Planning Data and therefore can't link there, show the plain text list item as before
- For a constraint that does apply, if it does NOT have a `name` property on Planning Data (eg flood zones), ensure we have smarter fallback text
- For _any_ constraint, show a filtered, centred link to the Planning Data map
- The `dataset=` query param reflects multiple datasets where applicable (eg WHS)
- In the case of roads, …
=> feat: add Planning Data entity & filtered map view links to constraints

editor.planx.uk/src/routes/index.tsx
Fixes small typo from https://github.com/theopensystemslab/planx-new/pull/3427 which is causing a react-navi warning.
=> fix: react-navi error for Canterbury redirect

api.planx.uk/modules/send/email/index.ts, api.planx.uk/modules/send/s3/index.ts, api.planx.uk/modules/webhooks/docs.yaml, api.planx.uk/modules/webhooks/service/sendNotification/index.test.ts, api.planx.uk/modules/webhooks/service/sendNotification/index.ts, api.planx.uk/modules/webhooks/service/sendNotification/schema.ts, api.planx.uk/modules/webhooks/service/sendNotification/types.ts, hasura.planx.uk/metadata/tables.yaml
**Two key changes here:** 
- Fixes a previous error where the S3 send events were failing because of a circular async/await error (Kev was still getting webhook notification fine, but we were failing to populate our audit table). 
- Adds a Slack notification on new row insert to `s3_applications` audit table following existing pattern so we can keep a basic pulse on production integration activity
Notes on testing:
- The Slack notification is only called on prod, so the "correct" response in the Hasura event triggers tab here is "Skipping because not production" 
- As for the audit table entry, please note that the _all_ of our Planx environments are sending to the same Power Automate webhook URL on Barnet's side (eg Kev does _not_ have a staging versus production distinction in Power …
=> chore: fix audit entries and setup Slack notifications for production S3 + Power Automate submissions

api.planx.uk/modules/send/s3/index.ts
Followup to #3439 - I was too hasty updating this value & the audit entry is failing again: https://github.com/theopensystemslab/planx-new/pull/3439#discussion_r1684145611
I think we might be getting a slightly malformed response from Power Automate - if `res?.request` is included the `response` json we're trying to write to the audit table (it is by default with `res`) I'm getting this error consistently, but as long as it's omitted everything succeeds.
```
"message": "{\"error\":\"Failed to upload submission to S3 (barnet): Converting circular structure to JSON\\n    --> starting at object with constructor 'ClientRequest'\\n    |     property 'socket' -> object with constructor 'TLSSocket'\\n    --- property '_httpMessage' closes the circle\"}"
```
We're capturing the request separately …
=> fix: fix insert to `s3_submisisons.response`

editor.planx.uk/src/pages/Team.tsx
Following work done on Team Name in #3441 to validate duplicate team names, the same logic has been carried into Flow Name. 
Greater detail on the thinking behind the code is given in the previously mentioned PR, #3441.
=> feat: Flow Name Duplicate Validation

editor.planx.uk/src/pages/FlowEditor/lib/store/team.ts, editor.planx.uk/src/pages/Team.tsx, editor.planx.uk/src/pages/Teams.tsx, hasura.planx.uk/metadata/tables.yaml, hasura.planx.uk/tests/team_integrations.test.js, hasura.planx.uk/tests/team_themes.test.js
This PR introduces a new button on the **Teams** page of the **Editor** which allows a PlatformAdmin to add a new Team to the database.
> By adding a new Team to the database, only ``name`` and ``slug`` are user generated, other fields in the **teams**, **team_themes**, **team_settings**, and **team_integrations** tables all rely on default values for the user to add later
Validation has also been added to ensure all team names are unique in the database, with an alert being added to indicate to the user that the team has not been added, as shown below.
Validation has been set up to use the ``slug`` rather than the ``name`` to catch capitalisation similarities.
>Capitalisation similarities would be like _Newcastle-upon-tyne_ being the same as _Newcastle-Upon-Tyne_
=> feat: Add New Team for Platform Admins 

api.planx.uk/package.json, api.planx.uk/pnpm-lock.yaml, e2e/tests/api-driven/package.json, e2e/tests/api-driven/pnpm-lock.yaml, e2e/tests/ui-driven/package.json, e2e/tests/ui-driven/pnpm-lock.yaml, editor.planx.uk/pnpm-lock.yaml
Ran `pnpm update axios` in each project subdirectory
The editor was already on v1.7.2 (update only impacted downstream deps in lock file), but the API & E2E tests were still on v1.6.8. 
This mismatch might be the source of our Github Actions CI bug? :crossed_fingers: Context here: https://opensystemslab.slack.com/archives/C01E3AC0C03/p1721668629921349
=> chore: bump axios to v1.7.2 across projects

editor.planx.uk/src/@planx/components/PlanningConstraints/List.tsx, editor.planx.uk/src/@planx/components/PlanningConstraints/Modal.tsx, editor.planx.uk/src/@planx/components/PlanningConstraints/PlanningConstraints.stories.tsx, editor.planx.uk/src/@planx/components/PlanningConstraints/Public.tsx, editor.planx.uk/src/lib/featureFlags.ts
**Changes:**
- Adds a new feature flag `"OVERRIDE_CONSTRAINTS"` so we can work on followup PRs in parallel
- Adds a link & modal to capture user input about inaccurate constraints (on intersecting constraints _only_):
- The modal has context text, a checklist of entities that we think apply, and a long text input to provide a reason why it's inaccurate
- "Submit" button does validation and updates internal component state with valid input
- "Cancel" button clears input and exits the modal
- Basic styling feedback if you've marked an entity as inaccurate: gray text and "[Not applicable]" tag next to entity, and overall gray text accordion title if _every_ entity within that category has been marked as inaccurate
**Followup PRs:**
- Styling questions for Ian:
- There's a mix of internal & …
=> feat: modal form for reporting inaccurate Planning Constraints

api.planx.uk/package.json, api.planx.uk/pnpm-lock.yaml, e2e/tests/api-driven/package.json, e2e/tests/api-driven/pnpm-lock.yaml, e2e/tests/ui-driven/package.json, e2e/tests/ui-driven/pnpm-lock.yaml, editor.planx.uk/package.json, editor.planx.uk/pnpm-lock.yaml, editor.planx.uk/src/@planx/components/MapAndLabel/Editor.tsx, editor.planx.uk/src/@planx/components/MapAndLabel/Public.tsx, editor.planx.uk/src/@planx/components/MapAndLabel/model.ts, editor.planx.uk/src/@planx/components/shared/Preview/SummaryList.tsx, editor.planx.uk/src/@planx/components/ui.tsx, editor.planx.uk/src/lib/featureFlags.ts, editor.planx.uk/src/pages/FlowEditor/components/Flow/components/Node.tsx, editor.planx.uk/src/pages/FlowEditor/components/forms/FormModal.tsx, editor.planx.uk/src/pages/FlowEditor/components/forms/index.ts, editor.planx.uk/src/pages/FlowEditor/data/types.ts, editor.planx.uk/src/pages/Preview/Node.tsx
This PR creates the framework for a new Editor "@planx" component. 
To create this PR, I have followed the steps laid out here: https://github.com/theopensystemslab/planx-new/blob/main/editor.planx.uk/docs/adding-a-new-component.md
*_Replacing `SetValue` with `MapAndLabel`_
With this PR, there has also been an update to the planx-core ref in the package.json
=> feat: Add new `MapAndLabel` component to @planx components

editor.planx.uk/src/@planx/components/PlanningConstraints/List.tsx, editor.planx.uk/src/theme.ts, editor.planx.uk/src/themeOverrides.d.ts
- Updates constraints accordion to use a secondary button to report non-applicable constraints
- Creates a theme-level chip style named `notApplicableTag`
- Updates styling of non-applicable constraints to use `notApplicableTag`, rendered conditionally for data reported non-applicable constraints and user-reported non-applicable constraints
Example:
https://3450.planx.pizza/lambeth/check-constraints-on-a-property
A good property with multiple constraints:
SW2 1AH
FLAT A, 102, BRIXTON HILL
Feature flag to enable: `window.featureFlags.toggle("OVERRIDE_CONSTRAINTS")`
=> feat: Not applicable constraints styling

editor.planx.uk/src/pages/Team.tsx
This PR builds on previous work completed in #3445 to add duplicate name validation when you add a new flow.
What that previous PR didn't pick up was adding the validation to the renaming process.
In order to allow a comparison between the new name and the current list of names, I had to alter the props being passed to the ``<FlowItem>`` component which contains the ``<StyledSimpleMenu>``. 
The alteration was just to add ``flows`` into the component.
=> feat: Add duplicate name logic to Rename flow onClick

editor.planx.uk/src/components/EditorNavMenu.tsx, editor.planx.uk/src/components/Header.tsx, editor.planx.uk/src/pages/FlowEditor/index.tsx, editor.planx.uk/src/pages/layout/AuthenticatedLayout.tsx, editor.planx.uk/src/theme.ts, editor.planx.uk/src/themeOverrides.d.ts
Ahead of producing more detailed Figma components the editor screens I wanted to update the editor general interface so that it closer matches existing designs.
- The current editor uses the same header parent styles as the public interface, causing it to have a header min-height that is unnecessarily tall. By introducing a dedicated container for each environment we can allow each to have an optimised height
- Slight reduction of breadcrumb type size to allow for longer council and service names on narrower screens (breadcrumbs are close to wrapping on smaller laptop sizes)
- Introduction of new `body3` type style that can be used for the smaller text sizes used in the editor (equates to around 14px, smaller than we'd generally use for the public interface but very …
=> style: Tighten editor interface layout

editor.planx.uk/src/pages/FlowEditor/lib/store/team.ts, hasura.planx.uk/metadata/tables.yaml, hasura.planx.uk/tests/team_integrations.test.js
Fixes bug described here! https://github.com/theopensystemslab/planx-new/pull/3449#discussion_r1690218020
=> fix: query `hasPlanningData` on `initTeamStore()` to see constraints in editor sidebar

editor.planx.uk/src/components/Footer.tsx, editor.planx.uk/src/components/Header.tsx, editor.planx.uk/src/pages/layout/PublicLayout.tsx
Quick one — there has been a lot of talk about users printing from PlanX recently.
If someone does print from the public interface we can save them a lot of printer ink with a few lines of CSS. This PR uses the `@media print` media query to remove the largest blocks of solid colour from the header and footer.
**Before:**
**After:**
=> feat: Reduced colour fill print css

editor.planx.uk/src/@planx/components/MapAndLabel/Editor.tsx, editor.planx.uk/src/@planx/components/MapAndLabel/Public.tsx, editor.planx.uk/src/@planx/components/MapAndLabel/model.ts
This PR looks to extend the new ``MapAndLabel`` component by adding a ``my-map`` component to the Public file and introduce the passing of props from the Editor Modal version to the Public version to control how the map is formatted.
Two props have been tested
- drawColour
- drawType
drawColour is also used to dictate ``drawFillColour`` and ``drawPointColour`` which are built in props for the ``my-map`` component.
Following this PR, I will start to add more data interactivity with what is happening on the graph and how it updates other elements of the component as shown in the ``FindProperty`` component as an example then continue to integrate work being undertaken on the map repo.
=> feat: Add Props to MapAndLabel Component

editor.planx.uk/src/pages/FlowEditor/components/Sidebar/Search.tsx
- Reduces visual weight of external portals within search results
- Uses a `<a>` tag for the links, allowing for opening in new tabs (right/ctrl click as native behaviour)
**Existing (left) vs updated (right):**
=> style: External portals within search results

editor.planx.uk/package.json, editor.planx.uk/pnpm-lock.yaml, editor.planx.uk/src/hooks/useSearch.ts, editor.planx.uk/src/pages/FlowEditor/components/Flow/components/Portal.tsx, editor.planx.uk/src/pages/FlowEditor/components/Sidebar/Search.tsx, editor.planx.uk/src/pages/FlowEditor/lib/store/editor.ts, editor.planx.uk/src/pages/FlowEditor/lib/store/shared.ts
- Handles search in the frontend using [Fuse.js](https://www.fusejs.io/)
- Creates `useSearch()` hook as a facade for this library
- This means we could search elsewhere fairly easily by re-using this hook (e.g. teams, flows)
- We could also more easily swap out the search functionality in future (maybe with our own API or another library) 
- Displays list of external portals to contextualise search results ([see Figma designs here](https://www.figma.com/design/bnUUrsVRG6qPwDkTmVKACI/PlanX-Design?node-id=15558-12317&t=SjQkPvPMMYyjxwVa-4))
- We have all flow data already in the frontend and don't need to fetch this from the db, add parentIds etc (on each debounced search request)
- Most flows aren't actually _that_ big, so handling this in the frontend isn't as intensive a task as I would …
=> feat: Initial frontend search proof of concept with Fuse.js

editor.planx.uk/src/pages/FlowEditor/components/Sidebar/PublishDialog.tsx
**Changes:**
- Adds a tooltip to the "Validation checks" header to generally introduce what a validation check is (tooltip feels like reasonable interaction to introduce _inside of_ a modal?)
- Adds more explicit list styling to the individual checks and a text-based summary above them (very much mimicing GitHub CI here, hopefully helps with clarifying that "warnings" aren't "errors" etc)
Collecting whole team feedback over here: https://opensystemslab.slack.com/archives/C04DZ1NBUMR/p1722334808628339
**Before:**
**After:**
=> fix: update styling of publish dialog validation checks based on feedback

editor.planx.uk/src/components/Header.tsx
Fixes a regression that has removed the vertical padding from the sections navigation bar.
Before:
After:
=> fix: Sections navigation bar padding

editor.planx.uk/src/@planx/components/Content/Editor.tsx, editor.planx.uk/src/@planx/components/MapAndLabel/Editor.tsx, editor.planx.uk/src/@planx/components/Notice/Editor.tsx, editor.planx.uk/src/pages/FlowEditor/components/Settings/DesignSettings/ButtonForm.tsx, editor.planx.uk/src/pages/FlowEditor/components/Settings/DesignSettings/TextLinkForm.tsx, editor.planx.uk/src/pages/FlowEditor/components/Settings/DesignSettings/ThemeAndLogoForm.tsx, editor.planx.uk/src/ui/editor/ColorPicker.tsx, editor.planx.uk/src/ui/editor/ListManager.stories.tsx
This PR updates the ``ColorPicker`` component to conditionally add a `label` if provided it as a prop, and don't add any label if the `label` prop doesn't exist.
The previous behaviour was to add a label stating ``"background colour"`` if no `label` prop was provided. 
To ensure continuous behaviour, I have updated the two components using ``<ColorPicker>`` without the ``label`` prop and I have updated the `MapAndLabel` component to use the ``<ColorPicker>`` without the `label` prop, which was the catalyst for this change.
=> refactor: Make ``label`` conditional on ``<ColorPicker>``

api.planx.uk/modules/webhooks/docs.yaml
- Fixes two issues in `/send-slack-notification` endpoint Swagger docs, annotated below
- Please see https://github.com/theopensystemslab/planx-new/pull/3466#discussion_r1698777844 for context
=> chore: Fix Slack notification API docs

README.md
Based on issues that both me and Dan have had while cloning the repo, I have added a reminder about the pnpm version in the troubleshooting section of the readme. I didn't want to interfere with the succinct nature of the instructions too much!
=> fix: add pnpm version reminder to readme troubleshooting section

editor.planx.uk/public/.well-known/microsoft-identity-association.json
We want to demonstrate to Microsoft/Azure that we own `editor.planx.uk`, for the purpose of verifying it as a 'publisher domain', which will then be displayed to users attempting to sign on via a Microsoft account, for added trust.
NB. This can be reverted once the verification is complete.
=> [editor] serve microsoft-identity file

editor.planx.uk/src/@planx/components/MapAndLabel/Public.tsx
This PR begins to add event listeners and map dispatches to the public component of ``MapAndLabel`` which can then lay the foundations for Work to Trees and drawing shapes on a map and tracking them with List components.
=> feat: Add event listener trackers to Map and Label

e2e/tests/ui-driven/src/pay.spec.ts
- Fixes failing regression test which relied on outdated copy on GovPay confirmation page
- Annotates test to be a little more descriptive
- Regression tests running passing against this branch here - https://github.com/theopensystemslab/planx-new/actions/runs/10252139211 ✅
=> fix(e2e): Fix broken regression tests due to GovPay copy change

api.planx.uk/.env.test.example, api.planx.uk/jest.setup.js, api.planx.uk/modules/file/service/utils.test.ts
When working on #3464, I needed to make sure I could run all of `pnpm [check/test/build/start/dev]` reliably with any changes I was making. To run the latter 2 commands, I was loading the root `.env` into my shell, but this would then break the tests, because I'd carry the `MINIO_PORT` value over from my shell, and pollute the test environment.
To fix that I made the changes in this PR. It ensures that any environment variables already in your shell are overwritten by the values in `api.planx.uk/.env.test` for the purposes of testing.
Also adds demonstrative minio port value to `.env.test.example`, and adjusts test expectation accordingly.
NB. 1 API test will fail until we push up new secrets (i.e. add `MINIO_PORT=1234` to `.env.test`), but we should only do that when about to merge, …
=> [api] improve DX by overriding shell variables when running tests

api.planx.uk/modules/test/controller.ts, api.planx.uk/modules/test/docs.yaml, api.planx.uk/modules/test/routes.test.ts, api.planx.uk/modules/test/routes.ts, api.planx.uk/package.json, api.planx.uk/pnpm-lock.yaml, api.planx.uk/server.ts, api.planx.uk/session.ts
🔧   [Ticket in Trello](https://trello.com/c/BKP8MVAK).
We've wanted to bump the [passport](https://www.passportjs.org/) version in use for auth routes for some time, because `0.6.0` fixes a 'moderate' [security vulnerability](https://nvd.nist.gov/vuln/detail/CVE-2022-25896) (as [flagged by dependabot](https://github.com/theopensystemslab/planx-new/security/dependabot/1) 2 years ago).
But this version throws up a bug related to our use of `cookie-session`, which `passport` does not commit to being compatible with (see [here](https://github.com/LinkedInLearning/node-authentication-2881188/issues/2)) (it only claims to support `express-session`). The issue is that passport used to implement the `req.session.regenerate` and `req.session.save` methods, which are called by `cookie-session`, but …
=> [chore] bump passport to 0.7.0

api.planx.uk/jest.config.ts, api.planx.uk/modules/file/service/utils.test.ts, api.planx.uk/modules/send/utils/exportZip.ts, api.planx.uk/package.json, api.planx.uk/pnpm-lock.yaml, api.planx.uk/tests/loadOrRecordNockRequests.js
Should fix failing e2e regression tests on `main` :crossed_fingers: https://opensystemslab.slack.com/archives/C04EEBR1E0P/p1723443286868999
Regression tests passing against this branch :white_check_mark: https://github.com/theopensystemslab/planx-new/actions/runs/10358321445
**Two part bug:** 
1.  `__dirname is not defined` error was being thrown when trying to generate zip folders for submissions (hence Uniform-related e2e failure) - we can now access this by using `fileURLToPath` as outlined in [this post](https://iamwebwiz.medium.com/how-to-fix-dirname-is-not-defined-in-es-module-scope-34d94a86694d)
2. BUT that solution throws the following error on `pnpm test` : `The 'import.meta' meta-property is only allowed when the '--module' option is 'es2020', 'es2022', 'esnext', 'system', …
=> fix: refactor uses of `__dirname` now that API is using `esnext`

api.planx.uk/modules/webhooks/service/analyzeSessions/operations.ts, editor.planx.uk/src/pages/FlowEditor/lib/analytics/provider.tsx, hasura.planx.uk/migrations/1723551136179_add_used_foiynpp_allow_list_column/down.sql, hasura.planx.uk/migrations/1723551136179_add_used_foiynpp_allow_list_column/up.sql
Context: https://opensystemslab.slack.com/archives/C5Q59R3HB/p1723126009340879
**Testing:** 
- Answer the question in this sample flow & click "Continue" https://3508.planx.pizza/testing/used-foi-analytics-test/published
- Confirm your "allow listed" answer is recorded in the `analytics_summary` view https://hasura.3508.planx.pizza/console/data/default/schema/public/views/analytics_summary/browse (one row _per_ component/card, so answer is only expected to be present on corresponding "Question" type)
=> feat: add analytics tracking to "Did you use FOI service" question in LDCs

api.planx.uk/modules/gis/service/classifiedRoads.ts, api.planx.uk/modules/webhooks/service/analyzeSessions/operations.ts, editor.planx.uk/src/@planx/components/PlanningConstraints/Public.tsx, editor.planx.uk/src/@planx/components/PlanningConstraints/mocks/overrides/constraints.ts, editor.planx.uk/src/@planx/components/PlanningConstraints/utils.test.ts, editor.planx.uk/src/@planx/components/PropertyInformation/Public.tsx, editor.planx.uk/src/lib/featureFlags.ts, editor.planx.uk/src/pages/FlowEditor/lib/__tests__/preview/overrideAnswer.test.ts, editor.planx.uk/src/pages/FlowEditor/lib/analytics/provider.tsx, editor.planx.uk/src/pages/FlowEditor/lib/store/preview.ts, hasura.planx.uk/migrations/1723636285473_add_planning_constraint_overrides_analytics_summary/down.sql, hasura.planx.uk/migrations/1723636285473_add_planning_constraint_overrides_analytics_summary/up.sql
Adds new passport variables that we'll track via our analytics `ALLOW_LIST`:
- `propertyInformation.action` with possible values "Accepted the property type" or "Changed the property type"
- `planningConstraints.action` with possible values "Accepted all planning constraints" or "Reported at least one inaccurate planning constraint"
- `_overrides` which is only defined _if_ the user has changed the property type _or_ reported inaccurate planning constraints and will include the specific details about _what_ was changed/overrode
- This data format can also be what we reference in the submissions payload to share override info with officers & back-office systems
Todo: 
Testing: 
- Change your property type & override a constraint & confirm your passport is setting `_overrides` and the …
=> chore: add analytics tracking to capture `PlanningConstraints` & `PropertyInformation` "overrides"

api.planx.uk/.eslintrc, e2e/.eslintrc, editor.planx.uk/.eslintrc, editor.planx.uk/src/@planx/components/Checklist/Editor.tsx, editor.planx.uk/src/@planx/components/Checklist/Public.tsx, editor.planx.uk/src/@planx/components/Checklist/model.ts, editor.planx.uk/src/@planx/components/PlanningConstraints/Public.test.tsx, editor.planx.uk/src/@planx/components/PlanningConstraints/Public.tsx, editor.planx.uk/src/@planx/components/Result/Public/index.tsx, editor.planx.uk/src/pages/FlowEditor/components/Flow/FeedbackPage.tsx, editor.planx.uk/src/ui/editor/RichTextInput.test.tsx
- Adds "no-nested-ternary" rules to ESLint configs ([docs](https://eslint.org/docs/latest/rules/no-nested-ternary))
- Refactors nested ternaries to satisfy rule
- I saw [this comment](https://github.com/theopensystemslab/planx-new/pull/3483/files#r1715103291) on #3483 and agreed - as we grow as a team we likely want to move more towards codifying these conventions we aim to follow in the codebase
- Hopefully some of the "before" snippets refactored in this PR demonstrate that nested ternaries are actually very hard to follow - understanding some of these took a surprising amount of mental capacity for this time of day 😅
=> chore: Add "no-nested-ternary" ESLint rule to projects

editor.planx.uk/src/@planx/components/List/Public/Fields.tsx
=> fix: Add missing `key` prop to `ChecklistItem`

editor.planx.uk/src/@planx/components/List/Public/index.test.tsx, editor.planx.uk/src/@planx/components/List/utils.tsx
- Displays responses for question inputs in the "inactive card" view
- Adds tests for "inactive card" view"
Not too sure where this regression slipped in - noticed it when working on other small `List` tickets for works to trees.
|![image](https://github.com/user-attachments/assets/68c5cb7b-cddd-42a8-b31f-03a2718e824a)|![image](https://github.com/user-attachments/assets/c6c9ff2a-00a0-48cc-a257-e670d2e625aa)|
=> fix: Display question values in `List` inactive card view

editor.planx.uk/src/@planx/components/Calculate/Editor.tsx
- Fixes a bug I hit when working on search
- Current behaviour - when I update the formula of a calculate field, unused defaults are retained (these were showing up in search results)
- New behaviour - when I update the formula of a calculate field, unused defaults are removed from the component's data
I did spend a bit of time trying to get tests to work here, without much success.
The issues I was hitting was that both `user.type()` and `user.keyboard()` were having issues correctly populating the formula field. I'm not sure if this is a formik, mathjs or a react-testing-library issue (likely a combination!).
=> fix: Remove unused defaults from the `Calculate` component

editor.planx.uk/src/@planx/components/DateInput/Public.tsx, editor.planx.uk/src/@planx/components/DateInput/model.test.ts, editor.planx.uk/src/@planx/components/DateInput/model.ts, editor.planx.uk/src/@planx/components/List/Public/Fields.tsx, editor.planx.uk/src/@planx/components/List/Public/index.test.tsx, editor.planx.uk/src/@planx/components/List/Public/index.tsx, editor.planx.uk/src/@planx/components/List/model.ts, editor.planx.uk/src/@planx/components/List/schemas/mocks/Zoo.ts, editor.planx.uk/src/@planx/components/List/utils.tsx
Allows dates to be added to list component schemas
Required for works to trees feature, useful for other list schemas.
=> feat(works-to-trees): Add `DateInputField` to `List` component

editor.planx.uk/src/@planx/components/Send/Editor.tsx
Related to #3482 
I want to share `.dev` testing links with Idox instead of `.pizza` because of Vultr issues.
Staging content is overwritten nightly, so I need to create my test flows on production - including ability to set this "Send" destination! 
Production won't have Pulumi keys for new Idox changes coming in #3482, so if a council did attempt to use it too soon it would fail fast on our side :ok_hand:
=> chore: expose "Idox Nexus" Send destination on production for testing

api.planx.uk/modules/send/idox/nexus.ts, hasura.planx.uk/migrations/1723816384301_update_submissions_log_view_format_idox_destination/down.sql, hasura.planx.uk/migrations/1723816384301_update_submissions_log_view_format_idox_destination/up.sql
Two quick bugs:
- Fixes XML generation bug related to testing Idox Nexus - see thread https://opensystemslab.slack.com/archives/C01E3AC0C03/p1723729231085529
- Ensures event name is nicely formatted in the editor Submissions Log (currently overflowing)
=> fix: ensure Idox Nexus audit entries don't rely on XML generation and format submission log event name

infrastructure/application/Pulumi.production.yaml
Follow on from #3482 & failing prod deploy
Prod Pulumi expects same keys, even if we only have "real" staging values so far
=> fix: ensure Pulumi production keys match staging for new Idox configs

editor.planx.uk/src/@planx/components/FindProperty/Public/Map.tsx
Fixes issues raised by Tewkesbury & West Berks linked here: https://trello.com/c/TAY09Mpw/2980-diagnose-and-fix-map-center-zoom-issue-when-displaying-team-boundaries
**Quick but key changes here:**
- FindProperty map gets a `FullWidthWrapper` similar to our other interactive maps (eg DrawBoundary) for more real-estate
- Lowered `zoom` from `14` to `10` which seems to better accomodate more spacious rural councils while still working for London boroughs like Lambeth too
- Removed `drawGeojsonDataBuffer` prop - we don't need this for initial render, and when coming "back" after having plotted a new address, the map defaults will still be smartly zoomed into & centered on your existing point
No changes necessary to how we store boundaries or calculate bounding-boxes - that's all correct, was …
=> fix: when proposing a new address, map should display at full width and lower zoom

editor.planx.uk/src/@planx/components/Confirmation/Confirmation.stories.tsx, editor.planx.uk/src/@planx/components/Confirmation/Editor.tsx, editor.planx.uk/src/@planx/components/Confirmation/Public.test.tsx, editor.planx.uk/src/@planx/components/Confirmation/Public.tsx, editor.planx.uk/src/@planx/components/Confirmation/model.ts, editor.planx.uk/src/pages/Preview/Node.tsx
**Changes:**
- Updates banner `description` to be a rich text input instead of plain text
- Refactors `details` to be handled directly in the `Confirmation` component rather than at the `Node` level
- There was an original request to make the "details" property names customisable while keeping the existing values, but after chatting with August we decided against this approach
- We don't let editors change the text of other static pages (eg Application Saved) or Gov Notify email templates, and we ultimately want to ensure all these fields have consistent naming between these various places - so customisation in this one place doesn't feel like the right solution and would likely lead to Confirmation page language that is out of sync/disjointed from other parts of the service
- We did …
=> chore: update Confirmation banner description to use rich text & reword details

editor.planx.uk/src/@planx/components/FileUploadAndLabel/schema.test.ts, editor.planx.uk/src/@planx/components/FileUploadAndLabel/schema.ts
Addresses issues outlined in this ticket - https://trello.com/c/zYOIK4d1/2996-allow-users-to-bypass-upload-and-label-exemptions-not-working-correctly
> Component requires either all files to be optional or files uploaded to be > 0. Recommended files are however not treated as optional, effectively being treated as if required. The allFilesOptional exemption should really be a noFilesRequired exemption, as the only time a users should be blocked from proceeding without uploading anything is when one or more files are required. Related issue: Even when all files are set to optional, with no uploaded files the component still always triggers the “Remove files which failed to upload” error.
This is now fixed (with added tests). The "Remove files which failed to upload” error was over-eager …
=> fix: Correct logic for `slotsSchema` validation

editor.planx.uk/src/@planx/components/shared/Schema/InputFields/index.tsx, editor.planx.uk/src/@planx/components/shared/Schema/model.ts, editor.planx.uk/src/pages/FlowEditor/components/Flow/components/Node.tsx, editor.planx.uk/src/pages/Preview/Node.tsx, editor.planx.uk/src/utils.ts
- Picks up on this comment - https://github.com/theopensystemslab/planx-new/pull/3526#discussion_r1721316603
- Moves existing repeated code to `utils.ts`
- Ensures that if a new `Field` is added, TS will catch places where this needs to be updated
=> feat: Add exhaustive checks in schema field types

editor.planx.uk/src/pages/FlowEditor/lib/store/settings.ts
Small UX improvement I noticed when turning a flow online/offline for testing.
By directly updating the store, Zustand will reactively update our UI so we don't have to reload the component (e.g. via navigation) to see the update.
https://github.com/user-attachments/assets/bf976ac5-50ae-4995-ad24-9f02c0eabba9
=> fix: Update store on flow status change

editor.planx.uk/src/@planx/components/List/Public/index.tsx
The List component's new "map" field requires address data from state to position the map viewport - this means the component needs to come after a "FindProperty". Currently in testing, if you don't remember this, the larger List will load but the map field will show an empty/non-loading map. 
Now just throw a quick "graph error" (same pattern as other postion-dependent geo components like PlanningConstraints)!
Tests for the "map" fields still outstanding / to-be picked up in follow-up PR
=> chore: add error feedback for editors if using List with "map" field without FindProperty first

editor.planx.uk/src/airbrake.test.ts
Please see https://github.com/theopensystemslab/planx-new/pull/3549 for context
=> test: Setup and manage Airbrake mocks and spies in vitest

e2e/tests/ui-driven/install-dependencies.sh, editor.planx.uk/src/@planx/components/MapAndLabel/Public.tsx, editor.planx.uk/src/@planx/components/shared/Schema/InputFields/MapFieldInput.tsx, editor.planx.uk/src/pages/FlowEditor/components/Settings/ServiceSettings.tsx
A few env vars introduced via a rebase which were then missed!
=> chore: Updating remaining `REACT_APP_*` envs to `VITE_APP_*`

editor.planx.uk/src/pages/FlowEditor/components/Sidebar/Search/ExternalPortalList.test.tsx, editor.planx.uk/src/pages/FlowEditor/components/Sidebar/Search/Headline.test.tsx, editor.planx.uk/src/pages/FlowEditor/components/Sidebar/Search/NodeSearchResults.test.tsx, editor.planx.uk/src/pages/FlowEditor/components/Sidebar/Search/index.test.tsx, editor.planx.uk/src/pages/FlowEditor/components/Sidebar/Search/index.tsx, editor.planx.uk/src/pages/FlowEditor/components/Sidebar/Search/mocks/simple.ts
- Follows on from https://github.com/theopensystemslab/planx-new/pull/3563
- Adds basic test suites describing the current search functionality - plenty more to come!
- A few intentional `test.todo()`s here 
**Context**
As search was initially developed in the frontend as a bit of a proof-of-concept, I'm now playing a bit of catch-up just to re-organise and formalise some of this code. It's actually been a few weeks since I've dived back into it properly so this was a nice useful task to describe and test the current functionality.
=> test: Basic tests describing the "search" feature

editor.planx.uk/src/@planx/components/DrawBoundary/Public/Public.test.tsx, editor.planx.uk/src/@planx/components/FileUploadAndLabel/Public.test.tsx, editor.planx.uk/src/@planx/components/Send/Public.test.tsx
- Context - outstanding task from https://github.com/theopensystemslab/planx-new/pull/3549
- Uncomments tests which were skipped in order to migrate to vitest
- Sets up axios mocks for these tests
- All remaining `.skip()` tests left in Editor are intentional
=> test: Setup axios mocks in outstanding frontend tests

editor.planx.uk/src/@planx/components/List/Public/index.tsx, editor.planx.uk/src/@planx/components/List/utils.tsx
Last piece in order to have an end-to-end List option demo ready for tmrw morning - shows a static map when the List item is inactive for any "map" field types. 
Hit a funny quirk here testing with "points" where I realised a limitation in the map repository - our `geojsonData` layer has only ever accounted for polygons before and doesn't currently have a "point" style associated with it ! So will make that update in `@opensytemslab/map` for a future release, and in the meantime we just slightly adjust our rendering rules based on `drawType` here :+1: 
(Also sorry Rory @RODO94 I know we bookmarked this task to your name last week, but trying to keep momentum ahead of demos & UR deadline! will be plenty more followup tasks when you're ready to come back into works to trees !)
=> feat: display static map for inactive List "map" fields

scripts/seed-database/write/team_settings.sql
Previous PR: https://github.com/theopensystemslab/planx-new/pull/3554 - added `submission_email` to the `team_settings` table but it did not make the change in the scripts which add data to the local database instances. 
This PR fixes that and adds the relevant changes to the scripts.
=> fix: add submission_email to team_settings seed script

editor.planx.uk/src/pages/FlowEditor/components/Sidebar/index.tsx, editor.planx.uk/src/pages/Preview/Questions.tsx, editor.planx.uk/src/theme.ts, editor.planx.uk/src/themeOverrides.d.ts
As part of replacing the current icons in the editor sidebar, this change replaces the refresh icon with a button that sits within the editor preview.
Also as this reuses the "link" style button used for the back button, I've created this as a theme button variant of `link`, that can be reused.
Example:
https://3573.planx.pizza/lambeth/apply-for-planning-permission
=> refactor: Move refresh button to browser preview

api.planx.uk/package.json, api.planx.uk/pnpm-lock.yaml, e2e/tests/api-driven/package.json, e2e/tests/api-driven/pnpm-lock.yaml, e2e/tests/ui-driven/package.json, e2e/tests/ui-driven/pnpm-lock.yaml, editor.planx.uk/package.json, editor.planx.uk/pnpm-lock.yaml, editor.planx.uk/src/pages/FlowEditor/components/Settings/GeneralSettings/SubmissionsForm.tsx, editor.planx.uk/src/pages/FlowEditor/components/Settings/GeneralSettings/index.tsx
This PR continues work in line with the Trello Ticket: https://trello.com/c/dVsTQpZZ/2984-allow-editors-to-see-update-their-teams-submission-email-in-team-settings-form
I have set up a **"Submission Information"** form in the **Team Settings** area. This comes with standard Formik wiring up with `ErrorWrapper` following patterns established in the other forms.
=> feat: Submission Form added to General Settings

docker-compose.yml, infrastructure/application/index.ts
Updates Metabase to [v0.50.22](https://github.com/metabase/metabase/releases/tag/v0.50.22), doing exactly as PR #2451 did. 
By the looks of it, no [big Metabase backup](https://www.metabase.com/docs/v0.50/installation-and-operation/backing-up-metabase-application-data) was done last time and data was just checked in staging--so no backup done here either. 
Let me know if anything further is needed!
=> chore: update Metabase to v0.50.22

editor.planx.uk/src/pages/FlowEditor/components/Sidebar/StyledTab.tsx, editor.planx.uk/src/pages/FlowEditor/components/Sidebar/index.tsx
🚧 **Edit sidebar icon replacement pt2** 🚧
Replaces console icon with a dedicated tab for the console. This is given a 'dark' theme with corresponding prop for dark tabs.
I've also moved `StyledTab` to its own file, I was unsure whether this should remain in the current folder, or be moved to the wider UI components folders, as it is only used in this place. Open to suggestions on this one.
Example:
https://3578.planx.pizza/lambeth/apply-for-planning-permission
=> refactor: Move editor console to tab

editor.planx.uk/.storybook/preview.tsx, editor.planx.uk/src/@planx/components/MapAndLabel/Public/Context.tsx, editor.planx.uk/src/@planx/components/MapAndLabel/Public/MapAndLabel.stories.tsx, editor.planx.uk/src/@planx/components/MapAndLabel/Public/index.tsx
- Sets up `MapAndLabel.stories.tsx`
- Splits up store logic from the rest of the component for simpler testing - the same pattern used in multiple other components for import to Storybook
I started looking at [the next item here to pick up](https://trello.com/c/JafdzU94/2855-epic-allow-applicants-to-work-to-trees-to-see-and-add-more-information-about-protected-trees-on-a-map) and was hitting a few issues setting up state before implementing tests. It seemed worthwhile to handle this once now before we start writing tests and then having to refactor them.
Also, having Storybook should prove helpful to avoid the `FindProperty` step beforehand when working on this and testing!
=> feat: Setup Storybook for `MapAndLabel`

api.planx.uk/.eslintrc, api.planx.uk/package.json, api.planx.uk/pnpm-lock.yaml
- Sets up [eslint-plugin-vite](https://github.com/vitest-dev/eslint-plugin-vitest), which replaces eslint-plugin-jest
- Adds rule to allow supertest assertions to be allowed by linting
- Please see #3555 and https://github.com/theopensystemslab/planx-new/pull/3555#discussion_r1730883773 for context
=> test(api): Setup eslint-plugin-vite

editor.planx.uk/package.json, editor.planx.uk/pnpm-lock.yaml, editor.planx.uk/src/@planx/components/List/utils.tsx
Includes a few fixes we talked about earlier!
- Correct `geojsonData` styles for simplified inactive "List" card
- Larger points & text labels
- Ability to set `dataTestId` prop
=> chore: upgrade to `@opensystemslab/map@next` v1.0.0-alpha.1

editor.planx.uk/src/pages/FlowEditor/components/Sidebar/StyledTab.tsx, editor.planx.uk/src/pages/FlowEditor/components/Sidebar/index.tsx
Simplify the sidebar tabs so that they don't require a colour theme prop, and also take up less visual space.
Before:
After:
Preview:
https://3591.planx.pizza/lambeth/apply-for-planning-permission
=> style: Simplify editor sidebar tabs

editor.planx.uk/package.json
Matches previous craco behaviour (clicking an extra link is hard! 😅)
=> chore: Add `--open` flag to vite in dev mode

api.planx.uk/modules/send/downloadApplicationFiles/index.ts, api.planx.uk/modules/send/email/index.test.ts, api.planx.uk/modules/send/email/index.ts, api.planx.uk/modules/send/email/service.ts, e2e/tests/api-driven/src/globalHelpers.ts, e2e/tests/ui-driven/src/context.ts
This PR looks to alter references from `teams.submission_email` to `team_settings.submission_email`.
I have ran through all references to `submission_email`, `sendEmail`, `submissionEmail` and repointed them to the new reference.
=> feat: API changes for handling new `submission_email` location

editor.planx.uk/src/@planx/components/List/Public/index.test.tsx, editor.planx.uk/src/@planx/components/MapAndLabel/Public/Context.tsx, editor.planx.uk/src/@planx/components/MapAndLabel/Public/index.tsx
- Wires up Formik validation on the `MapAndLabel` component
- Validation is triggered when hitting continue
- The minimum number of items is checked
- The maximum number of items is checked
- Errors in tabs are highlighted - certainly not advocating for this to be the final style but I just wanted to get the data flow set up here. 
- Removes some List specific functionality from `MapAndLabelContext`
- Starts using the language of "features" instead of "items" - feels a little clearer and less generic, but super open to feedback here.
- No tests! Interaction with the Map webcomponent is proving tricky - I'll have a PR later today with my various attempts documented, and I'll work on mocking the GeoJSON change event as an alternative. …
=> feat: Basic validation for `MapAndLabel`

editor.planx.uk/src/@planx/components/MapAndLabel/Public/Context.tsx, editor.planx.uk/src/@planx/components/MapAndLabel/Public/index.tsx
Please see https://github.com/theopensystemslab/planx-new/pull/3589#discussion_r1738010699 for context
=> feat(map-and-label): Better tab error styling

editor.planx.uk/src/@planx/components/MapAndLabel/Public/Context.tsx, editor.planx.uk/src/@planx/components/MapAndLabel/Public/CopyFeature.tsx, editor.planx.uk/src/@planx/components/MapAndLabel/Public/index.tsx, editor.planx.uk/src/theme.ts
- Moves the `CopyFeature` select to its own component
- Wires up this behaviour via a method in the provider
https://github.com/user-attachments/assets/1ff9a34b-b369-4d64-b8a0-634724cd14fb
=> feat(map-and-label): Copy feature

editor.planx.uk/src/pages/FlowEditor/components/Team/components/MembersTable.tsx, editor.planx.uk/src/pages/FlowEditor/components/Team/tests/TeamMembers.addNewEditor.noExistingMembers.test.tsx
Fixes case where the 'add' button wasn't visible for teams where there were no team editors already.
| Before                      | After                  |
| ------------------------ | ------------------------ |
| <img src="https://github.com/user-attachments/assets/229e5a9d-005e-4000-b4e5-024836f3301b" width="300"> | <img src="https://github.com/user-attachments/assets/7422e0bb-6629-4104-8be2-08ee9ced4a16" width="300"> |
Trello ticket: https://trello.com/c/piMcGsJa/2973-add-user-in-editor
Fix for comment raised in Slack: https://opensystemslab.slack.com/archives/C5Q59R3HB/p1724945320946359?thread_ts=1724942587.700829&cid=C5Q59R3HB
=> fix: handle no existing team members case when adding a new editor

editor.planx.uk/package.json, editor.planx.uk/pnpm-lock.yaml, editor.planx.uk/src/@planx/components/List/schemas/Trees.ts, editor.planx.uk/src/@planx/components/List/utils.tsx, editor.planx.uk/src/@planx/components/MapAndLabel/Public/Context.tsx, editor.planx.uk/src/@planx/components/MapAndLabel/Public/index.tsx, editor.planx.uk/src/@planx/components/shared/Preview/SummaryList.tsx, editor.planx.uk/src/@planx/components/shared/Schema/InputFields/MapFieldInput.tsx, editor.planx.uk/src/@planx/components/shared/Schema/model.ts
**A few key changes in here!** 
- Bumps `@opensystemslab/map` to v1.0.0-alpha.2
- Fixes shifty labels when modifying features; now when you modify it should keep the same label
- Enables processing a GeoJSON "FeatureCollection" passed into `drawGeojsonData` prop which is required for "back" navigation when `drawMany` is enabled (previously supported single "Feature")
- **[List]** Pre-populates drawing layer on the map when you click "Edit" for an existing item 
- Replaces #3601
- **[List]** Fix bug preventing existing/pre-populated features from being successfully "cleared"
- **[MapAndLabel]** Updates `handleSubmit` to produce GeoJSON data
- **[MapAndLabel]** Pre-populates map drawing layer and tab fields when you come "back" or "change" from the Review page
- **[MapAndLabel]** Adds a …
=> feat: enable "back" & "edit" navigation for List map fields and MapAndLabel using `@opensystemslab/map` v1.0.0-alpha.2

editor.planx.uk/src/@planx/components/List/Public/index.tsx, editor.planx.uk/src/@planx/components/shared/Schema/SchemaFields.tsx
Adds padding to list component inputs so that labels are correctly visually associated with corresponding inputs.
**Before:**
**After:**
=> fix: List component input spacing

editor.planx.uk/src/@planx/components/MapAndLabel/Public/index.tsx, editor.planx.uk/src/@planx/components/shared/Preview/MapContainer.tsx
Adds a basic level of styling to the MUI tabs on Map + Label to bring them in line with PlanX components.
A notable change is moving the error indicator to the left-side of the tab, this prevents conflict with the active tab marker, is consistent with our other usage of error marking, and prevents having to extend the error border to protrude past the overhang.
On that note I spent an unreasonable amount of time trying to figure our why MUI tabs use this overhang, any attempt to rectify it, breaks the scrollbar/flex system.
**Before:**
**After:**
=> style: Map + label tab style update

editor.planx.uk/src/@planx/components/List/Editor.tsx, editor.planx.uk/src/@planx/components/List/Public/index.test.tsx, editor.planx.uk/src/@planx/components/List/Public/index.tsx, editor.planx.uk/src/@planx/components/List/schemas/TreesMapFirst.ts, editor.planx.uk/src/@planx/components/shared/Schema/InputFields/DateFieldInput.tsx
Working through feedback here: https://opensystemslab.slack.com/archives/C5Q59R3HB/p1725376092471139
=> fix: initial works to trees feedback

editor.planx.uk/src/@planx/components/List/Public/index.tsx
Quick one: updates vertical alignment of list component summary table to top, to be consistent with our other use of summary tables (Review page for example).
**Before:**
**After:**
=> style: List component summary vertical alignment

editor.planx.uk/src/@planx/components/List/Public/index.test.tsx, editor.planx.uk/src/@planx/components/shared/Schema/InputFields/ChecklistFieldInput.tsx, editor.planx.uk/src/@planx/components/shared/Schema/InputFields/DateFieldInput.tsx, editor.planx.uk/src/@planx/components/shared/Schema/InputFields/MapFieldInput.tsx, editor.planx.uk/src/@planx/components/shared/Schema/InputFields/NumberFieldInput.tsx, editor.planx.uk/src/@planx/components/shared/Schema/InputFields/RadioFieldInput.tsx, editor.planx.uk/src/@planx/components/shared/Schema/InputFields/SelectInputField.tsx, editor.planx.uk/src/@planx/components/shared/Schema/InputFields/TextFieldInput.tsx, editor.planx.uk/src/@planx/components/shared/Schema/InputFields/shared.tsx, editor.planx.uk/src/@planx/components/shared/Schema/model.ts
Fixes a regression flagged here: https://opensystemslab.slack.com/archives/C01E3AC0C03/p1725446829984269
**Locally edited schema to include descriptions:** 
**And how descriptions display with validation errors:**
=> fix: display schema field descriptions if set

api.planx.uk/modules/webhooks/service/analyzeSessions/operations.ts, editor.planx.uk/src/pages/FlowEditor/lib/analytics/provider.tsx, hasura.planx.uk/migrations/1725521923612_update_analytics_views_rab_exit_reason/down.sql, hasura.planx.uk/migrations/1725521923612_update_analytics_views_rab_exit_reason/up.sql
Comes out of conversation wtih Maya about how to track various reasons users exit the Report a Breach service - this offers them a simple trackable passport variable they can set in various contexts (on branching Questions, as a SetValue, etc).
Will flag this to Ollie once merged to add a simple summary chart to the RAB template on Metabase.
=> chore: add `rab.exitReason` to analytics allow lists and views

editor.planx.uk/src/@planx/components/MapAndLabel/Public/index.tsx
Follows on from #3612 & https://github.com/theopensystemslab/map/pull/493 - we stabilised labels directly on the map features themselves, but not the tabs
Previously: add three points to the map, modify point #2, tabs 2 & 3 swap order
Now: map _and_ tab order are stable when modifying
=> fix(map-and-label): when modifying features on the map, tabs should stay ordered by label not recently changed

editor.planx.uk/src/@planx/components/List/Editor.tsx, editor.planx.uk/src/@planx/components/List/schemas/ResidentialUnits/Existing.ts, editor.planx.uk/src/@planx/components/List/schemas/ResidentialUnits/GLA/Gained.ts, editor.planx.uk/src/@planx/components/List/schemas/ResidentialUnits/GLA/Lost.ts, editor.planx.uk/src/@planx/components/List/schemas/ResidentialUnits/Proposed.ts
Add Lost/Gained list schema to GLA residential units in addition to current New/Retained/Rebuilt/Removed distinction. The current structure attempts to capture both national and GLA requirements in one structure. GLA councils do however not capture the nationally required information in their current form submissions. This is an alternative and simplified mode of capturing the GLA information.
=> feat: add Lost/Gained list schema to GLA residential units

editor.planx.uk/src/@planx/components/shared/Schema/InputFields/DateFieldInput.tsx, editor.planx.uk/src/ui/shared/DateInput.tsx
Addresses accessibility issue in the date input generated by schema, in that a label (`Expected completion date` in this case) was not correctly associated with a form field.
I've introduced the `<fieldset>` with child `<legend>` pattern to create this association.
=> fix(a11y): Fieldset and legend for list/map date input

editor.planx.uk/src/@planx/components/List/Public/index.tsx, editor.planx.uk/src/@planx/components/shared/Schema/InputFields/MapFieldInput.tsx
Ensures maps in the List component span the full width of `contentWrap` (in line with Map + Label).
Not the most elegant solution, but enough to be functional in the testing prototype.
Feature flag:
`window.featureFlags.toggle("TREES")`
Demo:
https://3632.planx.pizza/testing/full-width-map-testing/preview
Preview:
=> feat: Full width map for list component

editor.planx.uk/src/components/Feedback/FeedbackForm.tsx
Following guidance in the [Trello ticket](https://trello.com/c/465qDleU/3023-content-edit-to-feedback-component), I have updated copy in the FeedbackForm component.
=> refactor: alter copy of `<FeedbackForm/>` comp

editor.planx.uk/src/@planx/components/List/Editor.tsx, editor.planx.uk/src/lib/featureFlags.ts, editor.planx.uk/src/pages/FlowEditor/components/forms/FormModal.tsx
This will make it easier for Nomensa to test on staging next week!
Map & Label still appears with a "(Testing only)" caveat when selecting from components list
=> chore: remove `TREES` feature flag

editor.planx.uk/src/@planx/components/List/Public/index.tsx
Updates layout of the inactive list card so that cards with maps are arranged in a horizontal layout on desktop.
Also general style improvements to the list component as a whole (button contrast, table column widths).
**Preview:**
=> style: Layout for inactive list card with map

hasura.planx.uk/metadata/tables.yaml, hasura.planx.uk/migrations/1725873202035_alter_table_public_teams_drop_column_submission_email/down.sql, hasura.planx.uk/migrations/1725873202035_alter_table_public_teams_drop_column_submission_email/up.sql, scripts/seed-database/write/teams.sql
To finish the work on https://trello.com/c/dVsTQpZZ/2984-allow-editors-to-see-update-their-teams-submission-email-in-team-settings-form
I have dropped the redundant column and adjusted the scripts which create the local DBs.
In order to keep the `team_summary` table, I had to adjust the sql code which creates it. From here I also repointed the `homepage` column of this table from `teams` table to `team_settings` table.
`Up` script running order: 
1. Change `team_summary` view using `team_settings.submission_email` column
2. Remove `teams.submission_email` column
`Down` script:
1. Add `teams.submission_email` column
2. Replace `team_summary` view using new column
Regression tests passing
=> refactor: remove `submission_email` column from `teams` table

editor.planx.uk/src/hooks/useSearch.ts, editor.planx.uk/src/pages/FlowEditor/components/Sidebar/Search/NodeSearchResults.tsx, editor.planx.uk/src/pages/FlowEditor/components/Sidebar/Search/SearchResultCard/DataDisplayMap.test.ts, editor.planx.uk/src/pages/FlowEditor/components/Sidebar/Search/SearchResultCard/DataDisplayMap.tsx, editor.planx.uk/src/pages/FlowEditor/components/Sidebar/Search/SearchResultCard/index.tsx, editor.planx.uk/src/pages/FlowEditor/components/Sidebar/Search/mocks/DataDisplayMap.ts, editor.planx.uk/src/pages/FlowEditor/components/Sidebar/Search/mocks/simple.ts
- Ensures that searching via the "data" facet works for all component types
- For each component which has a unique way of handling data variables, we need to ensure we can still access display details for these components. These components and their associated exceptions are encoded in the `DataDisplayMap` data structure
- Removes temporary guard / filter on search result cards which previously hid these exceptional components
https://github.com/user-attachments/assets/db5aa7e9-ace9-4d2e-8fa0-3281b4955d8f
Next up...
- Navigate to nodes on click of card (Prior art - https://github.com/theopensystemslab/planx-new/pull/3460)
- For nodes within portals, visually wrap with a "portal wrapper" as per Figma
=> feat: Data value search

editor.planx.uk/src/@planx/components/List/schemas/Trees.ts, editor.planx.uk/src/@planx/components/MapAndLabel/Public/index.test.tsx, editor.planx.uk/src/@planx/components/MapAndLabel/Public/index.tsx, editor.planx.uk/src/@planx/components/MapAndLabel/test/mocks/GenericValues.ts, editor.planx.uk/src/@planx/components/MapAndLabel/test/mocks/Trees.ts, editor.planx.uk/src/@planx/components/MapAndLabel/test/mocks/geojson.ts, editor.planx.uk/src/@planx/components/MapAndLabel/test/utils.ts
This PR follows work completed in: #3604 
I am writing tests for the **Error and Validation** `describe()` as part of larger work to write tests for all of the `test.todos()`.
My plan is to push up a PR for each `describe()` section so I can deal with feedback as I go and hopefully improve / fix any structure or logic issues.
For error checking at the Tab, I went with checking for the `border-left` styling as I couldn't see anything more specific to work from. From here I checked that this is removed when a new feature is added but is reapplied when you click "Continue" without adding new inputs.
The original `test.todos` there was one for Maximum number as an inverse to the minimum `it()` block I have written, but I didn't think there was a maximum for this component so I removed it.
=> feat[mal]: Map and Label Error and Validation Tests

api.planx.uk/modules/pay/controller.ts, api.planx.uk/modules/pay/helpers.ts, api.planx.uk/modules/pay/index.test.ts
- The GovPay API is being interacted with whilst the account in question (Barnet) is not yet configured - I've reached out to explain this to Barnet
- GovPay is returning the following message - `Account is not fully configured. Please refer to documentation to setup your account or contact support with your error code - https://www.payments.service.gov.uk/support/`
- We're not accounting for GovPay errors of this type (no paymentId created), which causes are logging to fail
- Caught in Airbrake x2 - https://planx.airbrake.io/projects/329753/groups/3888910995787193650/notices/3888910993592626836?tab=overview
- Add a handler for these errors which returns early if there's an issue
- The frontend already handles these errors
The pattern of proxies and nested callbacks within the Pay module …
=> feat: Better handling of GovPay errors

api.planx.uk/modules/flows/moveFlow/service.ts, api.planx.uk/package.json, api.planx.uk/pnpm-lock.yaml, e2e/tests/api-driven/package.json, e2e/tests/api-driven/pnpm-lock.yaml, e2e/tests/ui-driven/package.json, e2e/tests/ui-driven/pnpm-lock.yaml, editor.planx.uk/package.json, editor.planx.uk/pnpm-lock.yaml, editor.planx.uk/src/lib/feedback.ts
Cleaner branch to see all of the fixes for the `moveFlow` API call and the Feedback library fetch.
Used the `$client` instead of `$public `for the moveFlow `getBySlug()` query.
Removed the fetch for `teamId` in the lib/feedback.ts and replaced it with a store value
=> fix: Move Flow and Feedback Lib bug fixes

editor.planx.uk/src/pages/FlowEditor/components/Sidebar/DebugConsole.tsx, editor.planx.uk/src/pages/FlowEditor/components/Sidebar/Publish/PublishDialog.tsx, editor.planx.uk/src/pages/FlowEditor/components/Sidebar/Publish/PublishFlowButton.tsx, editor.planx.uk/src/pages/FlowEditor/components/Sidebar/index.tsx, editor.planx.uk/src/pages/FlowEditor/index.tsx
- Quick refactor / tidy up before taking a look at maintaining the tabs and search value in state as part of search
- Makes `DebugConsole` its own file / component
- Moves `Publish` to it's own folder and components
- Doesn't unnecessarily pass a URL as props (see https://github.com/theopensystemslab/planx-new/pull/3483#discussion_r1705918426)
- Declares URLs in a data structure instead of dynamically creating the URLs across the component (see https://github.com/theopensystemslab/planx-new/pull/3483#discussion_r1705915756)
No "new" code or functionality here
=> refactor: Split up Sidebar child components

editor.planx.uk/src/@planx/components/FindProperty/Public/Autocomplete.tsx, editor.planx.uk/src/@planx/components/FindProperty/Public/Public.test.tsx, editor.planx.uk/src/@planx/components/FindProperty/model.ts
It came up in Idox feedback that we aren't currently supporting address ranges in the ODP Schema. I looked through the OneApp JSON example we have and don't see any instances of it handling ranges either, but nonetheless it's low effort for us to start more carefully checking for these. 
So, this PR adds a few extra fields from the OS Places API "LPI" data source to our internal model which we can later decide how to send along in payloads / the ODP Schema (https://github.com/theopensystemslab/digital-planning-data-schemas/pull/236). 
Only additive changes here! 
- `saoEnd`
- `paoEnd`
- `ward`
- `parish`
Links: 
- OS Docs (ctrl + f "LPI Output"): https://osdatahub.os.uk/docs/places/technicalSpecification
- Example response: https://api.editor.planx.dev/proxy/ordnance-survey/search/places/v …
=> chore: extend `SiteAddress` type to account for ranges

editor.planx.uk/src/@planx/components/Page/Editor.tsx, editor.planx.uk/src/@planx/components/Page/Public.tsx, editor.planx.uk/src/@planx/components/Page/model.ts, editor.planx.uk/src/@planx/components/Page/schema/AdvertConsent.ts
- Sets up Editor modal for Page component
- Copies "Advert Consent" schema from List component - this is being used as a page there
=> feat(page): Editor modal

editor.planx.uk/package.json, editor.planx.uk/pnpm-lock.yaml, editor.planx.uk/src/@planx/components/Page/Editor.tsx, editor.planx.uk/src/@planx/components/Page/Public.test.tsx, editor.planx.uk/src/@planx/components/Page/Public.tsx, editor.planx.uk/src/@planx/components/Page/model.ts, editor.planx.uk/src/@planx/components/Page/schema/AdvertConsent.ts, editor.planx.uk/src/@planx/components/shared/Preview/SummaryList.tsx, editor.planx.uk/src/@planx/components/ui.tsx, editor.planx.uk/src/lib/featureFlags.ts, editor.planx.uk/src/pages/FlowEditor/components/Flow/components/Node.tsx, editor.planx.uk/src/pages/FlowEditor/components/forms/FormModal.tsx, editor.planx.uk/src/pages/FlowEditor/components/forms/index.ts, editor.planx.uk/src/pages/FlowEditor/data/types.ts, editor.planx.uk/src/pages/Preview/Node.tsx
- Sets up `Page` component, as described in [docs](https://github.com/theopensystemslab/planx-new/blob/main/editor.planx.uk/docs/adding-a-new-component.md)
- Adds temporary `"PAGE"` feature flag
- Follow up PRs to handle next steps, [todo list up to date in trello ticket](https://trello.com/c/7MbycSE8/3016-create-a-page-component)
=> feat(page): Initial setup of Page component

editor.planx.uk/src/@planx/components/List/Editor.tsx, editor.planx.uk/src/@planx/components/List/Public/Context.tsx, editor.planx.uk/src/@planx/components/List/Public/index.tsx, editor.planx.uk/src/@planx/components/List/model.ts
- Removes the `isPageComponent` variable from the List component, and the associated UI changes
- Adds validation to the List editor modal - a List schema must allow multiple items
This was always a bit of unintended workaround, and we're now explicitly removing this as a Page component is likely a more suitable option.
This PR won't break any existing flows or behaviours, it will simply stop pseudo-Page components from being generated. Once the feature flag is removed from the Page feature, we can migrate any flows using the AdvertConsent schema to be a Page, and remove this option from the List schema folder.
=> feat: Remove Page workaround UI from List component

editor.planx.uk/src/components/RouteLoadingIndicator.tsx, editor.planx.uk/src/pages/layout/AuthenticatedLayout.tsx
An implementation of a routing loading bar as opposed to the FOUC and `DelayedLoadingIndicator`.
Follows on from #3671 
**Questions** -
- Is 50ms of delay too short? (is it showing too often and flashing and dissapearing?)
- Style 
- should it be slimmer?
- should it be a more subtle colour
- Do we want to consider something similar on the public interface?
=> feat: Route loading progress bar

editor.planx.uk/src/@planx/components/MapAndLabel/Public/index.test.tsx, editor.planx.uk/src/@planx/components/MapAndLabel/test/utils.ts
Running through the Happy Path test to-dos. Tried to do a nice amount of refactoring to keep the testing concise but explicit, so I have some simple functions handling "Clicking Continue" and "Checking for Error Messages are Populated or Empty" since these are repeatable situations without a high amount of meaning or context for the test. 
I would be interested to know if I should be waiting for a `handleSubmit()` to be called to confirm the happy path is successful rather than just checking the absence of error messages.
=> feat: Map and Label Happy Path Tests

editor.planx.uk/src/pages/FlowEditor/components/Sidebar/Publish/PublishFlowButton.tsx, editor.planx.uk/src/pages/FlowEditor/components/Sidebar/index.tsx
- Bug introduced in https://github.com/theopensystemslab/planx-new/pull/3668
- URLs are not being re-generated when the route changes
- This is because by defining `urls` outside of the lifecycle scope of a component, this is never re-generated
- To recreate - 
- Navigate to a flow in the Editor, checkout icon hrefs in Sidebar
- Navigate to another flow
- Icon hrefs have not updated ❌ 
- Calculate within the `Sidebar` component
- Pass URL as prop, instead of importing it
=> fix: Flow URLs should re-compute on re-render of Sidebar

editor.planx.uk/src/pages/FlowEditor/components/Team/TeamMembers.tsx, editor.planx.uk/src/pages/FlowEditor/components/Team/components/MembersTable.tsx, editor.planx.uk/src/pages/FlowEditor/components/Team/tests/TeamMembers.addNewEditor.test.tsx, editor.planx.uk/src/pages/FlowEditor/components/Team/tests/TeamMembers.updateEditor.test.tsx, editor.planx.uk/src/pages/FlowEditor/components/Team/types.ts
Per #planx-design thread: https://opensystemslab.slack.com/archives/C04DZ1NBUMR/p1726564743563709
**Changes:**
- Hide the add/edit buttons in the "Templates" team as membership to this team is specially handled via a DB trigger
- Don't show an edit button for archived members
=> fix: hide add/edit user in Templates team and for archived members

editor.planx.uk/src/pages/FlowEditor/components/Team/components/MembersTable.tsx
| Before                      | After                  |
| ------------------------ | ------------------------ |
| <img src="https://github.com/user-attachments/assets/a81761ff-29f0-46be-9f7b-d1b6353644f5" width="300"> | <img src="https://github.com/user-attachments/assets/f8ca2aae-507e-4ea2-8778-4117302130ec" width="300"> |
=> fix: realign members table cell borders

editor.planx.uk/src/@planx/components/MapAndLabel/Public/index.test.tsx, editor.planx.uk/src/@planx/components/MapAndLabel/test/mocks/GenericValues.ts
This continues work on the tests for the Map and Label component, building up tests for the _Copy from_ feature
=> feat: Map and Label Copy Tests

editor.planx.uk/src/@planx/components/MapAndLabel/Public/index.test.tsx, editor.planx.uk/src/@planx/components/MapAndLabel/test/mocks/geojson.ts
Following previous work on Map and Label testing, I am continuing through and testing the Remove feature.
To test the feature being deleted the map, I am accessing the `drawgeojson` attribute of `<my-map>` seemed a good way to confirm it has been deleted from the map itself. Open to alternative suggestions though.
```ts
const mapTwo = getByTestId("map-and-label-map");
expect(mapTwo).toHaveAttribute(
"drawgeojsondata",
`{"type":"FeatureCollection","features":[]}`
);
```
=> feat: Map and Label Remove Tests

editor.planx.uk/src/@planx/components/PlanningConstraints/Public.test.tsx, editor.planx.uk/src/@planx/components/PlanningConstraints/Public.tsx, editor.planx.uk/src/@planx/components/PlanningConstraints/mocks/simpleFlow.ts, editor.planx.uk/src/@planx/components/shared/Preview/SimpleExpand.tsx, editor.planx.uk/src/components/Error/ErrorFallback.tsx
Sets up very basic coverage of the public interface of the `PlanningConstraints` component.
- Follow up to https://github.com/theopensystemslab/planx-new/pull/3689#discussion_r1764504784
- Upcoming work may focus on the Editor interface, it's worth having a good test setup here which can be expanded alongside this work
=> test: Basic coverage for `PlanningConstraints` public interface

e2e/tests/ui-driven/src/create-flow/create-flow.spec.ts, e2e/tests/ui-driven/src/helpers/userActions.ts
Hopefully should fix the recent failing regression test runs e.g. https://github.com/theopensystemslab/planx-new/actions/runs/10923566442/job/30320494144
I've replaced the assertion in the one test case where I needed it, rather than assuming that it works for all places that the helper is used.
=> fix: remove assertion from e2e helper to fix regression tests

docker-compose.yml, infrastructure/application/index.ts
Updates Metabase to [v0.50.26](https://github.com/metabase/metabase/releases/tag/v0.50.26).
I know we [just updated Metabase](https://github.com/theopensystemslab/planx-new/pull/3579) but there was a minor change in [v0.50.23](https://discourse.metabase.com/t/cant-access-to-api-docs/150971) that should make life working with the API a lot easier.
=> chore: update Metabase to v0.50.26

api.planx.uk/modules/send/s3/index.ts, api.planx.uk/modules/webhooks/service/sendNotification/index.test.ts, api.planx.uk/modules/webhooks/service/sendNotification/index.ts, api.planx.uk/modules/webhooks/service/sendNotification/schema.ts
Barnet is expanding their use of the S3/Power Automate webhook "Send" method to more services, but our logging for this method isn't currently easily filter-able on flow name.
**Two quick changes:** 
- Add `service` (aka flow name) property to the message we send to the webhook
- Access that `service` name again (from the audit table record) for the Slack message so it's more consistent with other notifications like send to email 
- Before: ` New S3 + Power Automate submission 3ec46727-88b4-4f39-bb95-a89ee33f0b52 [barnet] [Exempt]`
- After:  ` New S3 + Power Automate submission "Apply for a Lawful Development Certificate" 3ec46727-88b4-4f39-bb95-a89ee33f0b52 [barnet] [Exempt]`
**Testing:**
I've tested locally & confirmed with Kev. Please do _not_ send an S3 test submission on this pizza …
=> fix: add flow name to S3 Slack notifications & webhook message

editor.planx.uk/src/pages/FlowEditor/components/Sidebar/Search/index.tsx
- Adds a (pretty conservative) 500ms debounce to search, in order to make sure we're not querying too frequently
- Changes the slightly generic `input` → `pattern` to better match the `useSearch()` hook
- Example large flow - https://3703.planx.pizza/opensystemslab/prior-approval-scope-check
https://github.com/user-attachments/assets/7ead3160-bbc8-4e62-bc9e-2b9647e59d4b
- Offload search to a web worker
- Better loading UI whilst search debounce is updating
- [Virtualised list](https://mui.com/material-ui/react-list/#virtualized-list) for search results (maybe)
- Search by hitting enter / button (maybe, if performance still not great)
=> feat(search): Add debounce to search

editor.planx.uk/src/pages/FlowEditor/components/Team/components/MembersTable.tsx, editor.planx.uk/src/pages/FlowEditor/components/Team/tests/TeamMembers.addNewEditor.errors.serverSide.test.tsx, editor.planx.uk/src/pages/FlowEditor/components/Team/tests/TeamMembers.addNewEditor.errors.userAlreadyExists.test.tsx, editor.planx.uk/src/pages/FlowEditor/components/Team/tests/TeamMembers.addNewEditor.noExistingMembers.test.tsx, editor.planx.uk/src/pages/FlowEditor/components/Team/tests/TeamMembers.addNewEditor.test.tsx, editor.planx.uk/src/pages/FlowEditor/components/Team/tests/TeamMembers.updateEditor.test.tsx
It's the second planning meeting in a row where Ian G has asked about / been a bit confused by adding and editing users and I think it's because he can see the add button as a `teamEditor`, but doesn't have permission to actually use it. 
This change hides the "Add a new editor" from non-`platformAdmins` similar to the "Edit" button. Database-level permissions already look correct (eg only `platformAdmin` role has "insert" permission on `team_members` table).
We've thrown this previous error: https://opensystemslab.slack.com/archives/C01E3AC0C03/p1725542317058179
Good reminder to ourselves to trigger our own `platformAdmin` status "off" sometimes when testing/code reviewing pizzas!
=> fix: hide "Add a new editor" button from non-admin users

editor.planx.uk/src/pages/layout/LoadingLayout.tsx, editor.planx.uk/src/routes/index.tsx
Follow up to https://github.com/theopensystemslab/planx-new/pull/3671 which removed this high level wrapper.
This approach inadventrantly removed the `DelayedLoadingIndicator` from public facing page which very much require it.
I've got a few ideas on how we could improve the loading times on the public facing pages (and the `/flatten-data`request  in particular), but these are a separate spike outside of this scope!
| [/draft](https://editor.planx.dev/birmingham/find-out-if-you-need-planning-permission/draft) | 🍕 [/draft](https://3714.planx.pizza/birmingham/find-out-if-you-need-planning-permission/draft) |
| [/preview](https://editor.planx.dev/birmingham/find-out-if-you-need-planning-permission/preview) | 🍕 …
=> fix: Add loading indicator to public pages

editor.planx.uk/src/pages/FlowEditor/components/Sidebar/Search/index.tsx, editor.planx.uk/src/ui/shared/Checkbox.tsx, editor.planx.uk/src/ui/shared/ChecklistItem.tsx
Adds a "compact" option to checkboxes, in line with the GOV.UK style smaller checkboxes:
https://design-system.service.gov.uk/components/checkboxes/#smaller-checkboxes
This will initially be used for toggling data (and other options) in the search function, but will useful throughout other search / filtering options within the PlanX editor.
**Before:**
**After:**
=> feat: Add compact checkbox option

editor.planx.uk/src/pages/FlowEditor/components/Sidebar/Search/index.tsx
- Adds a loading spinner to the search bar whilst the debounce is happening, to provider better user feedback
- Follow up to https://github.com/theopensystemslab/planx-new/pull/3703
No strong feelings about the UI, the logic here to capture `isSearching` could be used to add opacity to the current search results, or anything else to indicate staleness also.
https://github.com/user-attachments/assets/2307e86e-bf77-42d8-9357-fe614cca3e86
=> feat: Add loading spinner to search bar

editor.planx.uk/src/components/Header.tsx
Adds a chip to the service title to flag whether a preview or draft service is being viewed.
- Chip is display depending on path being `draft` or `preview`
- Icon updated based on path
- Header height is not affected (except in cases of earlier text-wrap for longer titles on smaller screens)
**Demo:**
[Draft environment](https://3717.planx.pizza/buckinghamshire/report-a-planning-breach/draft)
[Preview environment](https://3717.planx.pizza/buckinghamshire/report-a-planning-breach/preview)
[Published environment](https://3717.planx.pizza/buckinghamshire/report-a-planning-breach/published?analytics=false) (no change)
**Preview:**
=> feat: Environment dependant header chip styling

editor.planx.uk/src/@planx/components/Question/Public.test.tsx, editor.planx.uk/src/@planx/components/Question/Public/Question.tsx, editor.planx.uk/src/@planx/components/Question/model.ts
- Moves `Question` to its own `model.ts` file
https://github.com/theopensystemslab/planx-new/pull/3716 has slightly descended into a large messy type fixing PR which I was trying to avoid. I'm splitting it up into smaller, more atomic, PRs in order to better highlight and track the actual important changes.
=> chore: Create model file for `Question`

editor.planx.uk/src/routes/team.tsx, editor.planx.uk/src/routes/views/flowEditor.tsx
Sets the `flowId` variable in the store when the `flowEditorView` is loaded.
This fixes a small bug I just hit. To recreate - 
- Navigate to a team > flow > settings
- Turning flow online/offline works fine as we've set the flowId on the main flow page
- Refresh page
- `flowId` not set as we've gone directly to the settings page
- Turning flow online/offline fails as there's no `flowId` set
Still going to look into why the GraphQL error that's thrown in not being caught correctly!
=> fix: Set `flowId` in `flowEditorView`

editor.planx.uk/src/@planx/components/Checklist/Editor.tsx, editor.planx.uk/src/@planx/components/Checklist/model.ts
- Creates a shared `Category` type, which is shared within the `Checklist` component
https://github.com/theopensystemslab/planx-new/pull/3716 has slightly descended into a large messy type fixing PR which I was trying to avoid. I'm splitting it up into smaller, more atomic, PRs in order to better highlight and track the actual important changes.
=> chore: Create shared `Category` type

editor.planx.uk/src/@planx/components/DrawBoundary/Public/index.tsx, editor.planx.uk/src/@planx/components/FileUpload/Public.tsx, editor.planx.uk/src/@planx/components/FileUpload/model.tsx, editor.planx.uk/src/@planx/components/FileUploadAndLabel/Modal.tsx, editor.planx.uk/src/@planx/components/FileUploadAndLabel/Public.tsx, editor.planx.uk/src/@planx/components/FileUploadAndLabel/SelectMultiple.tsx, editor.planx.uk/src/@planx/components/FileUploadAndLabel/mocks.ts, editor.planx.uk/src/@planx/components/FileUploadAndLabel/model.test.ts, editor.planx.uk/src/@planx/components/FileUploadAndLabel/model.ts, editor.planx.uk/src/@planx/components/FileUploadAndLabel/schema.test.ts, editor.planx.uk/src/@planx/components/FileUploadAndLabel/schema.ts, editor.planx.uk/src/@planx/components/shared/PrivateFileUpload/Dropzone.tsx, editor.planx.uk/src/@planx/components/shared/PrivateFileUpload/PrivateFileUpload.tsx, editor.planx.uk/src/@planx/components/shared/PrivateFileUpload/UploadedFileCard.tsx
- Moves `FileUpload` to its own `model.ts` file
https://github.com/theopensystemslab/planx-new/pull/3716 has slightly descended into a large messy type fixing PR which I was trying to avoid. I'm splitting it up into smaller, more atomic, PRs in order to better highlight and track the actual important changes.
=> chore: Create model file for `FileUpload`

editor.planx.uk/src/@planx/components/Question/Public/Question.tsx, editor.planx.uk/src/@planx/components/shared/Radio/BasicRadio.tsx, editor.planx.uk/src/@planx/components/shared/Radio/DescriptionRadio.tsx
An overdue change — simplifies questions/radios so that they are no longer placed in a 3 column-grid with border when a description is present. Follows the GOV.UK pattern: https://design-system.service.gov.uk/components/radios/#radio-items-with-hints
Image radios are still gridded for now (to be explored as a further design challenge as we are not following a GOV.UK content pattern).
**Preview:**
https://3729.planx.pizza/testing/question-layouts/preview
**Before:**
**After:**
=> refactor: Simplify and improve description radio layout

editor.planx.uk/src/routes/team.tsx
- Ensures that the flow slug always displays in the header breadcrumbs when on a settings page
- Regression introduced as part of recent route refactors (sorry!)
=> fix: Flow slug in header breadcrumbs

api.planx.uk/modules/user/controller.ts, api.planx.uk/modules/user/docs.yaml, api.planx.uk/modules/user/index.test.ts, api.planx.uk/modules/user/routes.ts
- Removes "delete user" route
- Removes "create user" route
Now that this functionality is in the Editor (once https://github.com/theopensystemslab/planx-new/pull/3706 is merged), we can remove this from the REST API  🗑️ 🧹
=> chore: Remove deprecated `/user` endpoints

editor.planx.uk/.eslintrc, editor.planx.uk/src/components/TestEnvironmentBanner.tsx, editor.planx.uk/src/pages/FlowEditor/index.tsx, editor.planx.uk/src/pages/layout/AuthenticatedLayout.tsx
Small CSS fix I've been meaning to take a look at for a while.
When the "test environment" banner is visible, it takes the FlowEditor over 100vh which we don't want. This PR fixes that 👍 
https://github.com/user-attachments/assets/2707add5-ce5d-4f88-bde6-2a72b241ff45
https://github.com/user-attachments/assets/5a27456b-9923-40c3-a87e-382296aa1d28
=> fix: Remove additional Editor scroll

editor.planx.uk/.eslintrc, editor.planx.uk/package.json, editor.planx.uk/pnpm-lock.yaml, editor.planx.uk/src/components/Header.test.tsx, editor.planx.uk/src/pages/FlowEditor/components/Settings/ServiceSettings/FlowStatus/PublicLink.test.tsx
- Replaces legacy jest eslint plugins with a vitest specific plugin
- Makes the few requisite updates to meet the new linting rules
- Add `pnpm lint:error` script which just identifies errors, ignoring warnings
I think that https://github.com/theopensystemslab/planx-new/pull/3731 introduced this issue which dropped jest as a peer dependency.
=> chore: Replace jest linting with vitest linting

api.planx.uk/package.json, api.planx.uk/pnpm-lock.yaml, e2e/tests/api-driven/package.json, e2e/tests/api-driven/pnpm-lock.yaml, e2e/tests/ui-driven/package.json, e2e/tests/ui-driven/pnpm-lock.yaml, editor.planx.uk/package.json, editor.planx.uk/pnpm-lock.yaml, editor.planx.uk/src/@planx/components/Result/Editor.tsx, editor.planx.uk/src/@planx/components/Result/Public.test.tsx, editor.planx.uk/src/@planx/components/Result/Public/index.tsx, editor.planx.uk/src/@planx/components/Result/Result.stories.tsx, editor.planx.uk/src/@planx/components/Result/model.ts, editor.planx.uk/src/pages/FlowEditor/lib/store/preview.ts, editor.planx.uk/src/pages/Preview/Node.tsx
- Breaks up the `Result` component -
- Removes logic from `Node.tsx`
- Moves this to a higher-order component within the `Result` component, with the previous behaviour being delegated to a `Presentational` component (for testing & Storybook).
https://github.com/theopensystemslab/planx-new/pull/3716 has slightly descended into a large messy type fixing PR which I was trying to avoid. I'm splitting it up into smaller, more atomic, PRs in order to better highlight and track the actual important changes.
This pattern of using a `Presentational` component is used elsewhere multiple times. This was recently added to the `MapAndLabel` component here - https://github.com/theopensystemslab/planx-new/pull/3585
=> refactor: Add presentational component to `Result`

editor.planx.uk/src/pages/FlowEditor/components/Sidebar/Search/Headline.tsx
Adds a `<wbr/>` element ([docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/wbr)) after a headline character if it's a special character.
The headline element is split into a series of spans (one per character), so applying a regular word break css rule to the parent won't work. By inserting a `<wbr/>` each time we hit a non-alphanumeric character, we allow the browser to break where it sees fit.
|<img width="395" alt="image" src="https://github.com/user-attachments/assets/d6430233-5362-4273-93e5-d37f3042974b">|<img width="369" alt="image" src="https://github.com/user-attachments/assets/0d021873-4634-4e9c-8b17-8196e9944880">|
=> feat(search): Add word break after special characters in search cards

doc/how-to/how-to-setup-aws-sso-credentials.md, e2e/tests/ui-driven/src/create-flow-with-geospatial.spec.ts, e2e/tests/ui-driven/src/create-flow.spec.ts, e2e/tests/ui-driven/src/helpers/addComponent.ts, e2e/tests/ui-driven/src/pages/Editor.ts
- Add to 'editor side' test: filter and internal portal
- Add to 'user side' test: navigate through an internal portal
- Improve AWS SSO doc
- Re-add in the checklist component (seems to have fixed itself 😅 )
=> test[e2e]: add filter and internal portal into create flow test

editor.planx.uk/src/components/Header.tsx, editor.planx.uk/src/pages/FlowEditor/components/Sidebar/index.tsx
Moves toggle for show/hiding the editor sidebar to be placed on the sidebar itself.
Also stores the toggle position in localStorage so that the position is maintained when opening graph nodes or switching screens.
Example:
https://3747.planx.pizza/barking-and-dagenham/retrofit-guide
=> feat: Handle editor sidebar visibility toggle on sidebar

editor.planx.uk/src/@planx/components/FileUpload/Public.tsx, editor.planx.uk/src/@planx/components/FileUpload/model.tsx, editor.planx.uk/src/@planx/components/Pay/Public/Pay.tsx, editor.planx.uk/src/@planx/components/Question/model.ts, editor.planx.uk/src/@planx/components/Result/Public/ResultReason.tsx, editor.planx.uk/src/@planx/components/TaskList/model.ts, editor.planx.uk/src/@planx/components/shared/Preview/SummaryList.tsx, editor.planx.uk/src/@planx/components/shared/Radio/BasicRadio.tsx, editor.planx.uk/src/@planx/components/shared/Radio/ImageRadio.tsx, editor.planx.uk/src/pages/FlowEditor/components/Flow/components/Node.tsx, editor.planx.uk/src/pages/FlowEditor/components/Sidebar/Search/SearchResultCard/DataDisplayMap.tsx, editor.planx.uk/src/pages/FlowEditor/components/Sidebar/Search/SearchResultCard/index.tsx, editor.planx.uk/src/pages/FlowEditor/lib/analytics/utils.ts, editor.planx.uk/src/pages/FlowEditor/lib/store/index.ts, editor.planx.uk/src/pages/FlowEditor/lib/store/preview.ts, editor.planx.uk/src/pages/Preview/Node.tsx
- Adds `NodeTags` to `Store.Node["data"]`
- Final batch of TS updates in order to use NodeTags across all component types (I believe!)
Most of this is type updates, the two actual changes are highlighted below - 
https://github.com/theopensystemslab/planx-new/blob/0a1cbc68da8a5f3867b41756083aecd2dda7bd31/editor.planx.uk/src/pages/FlowEditor/lib/store/index.ts#L39-L41
https://github.com/theopensystemslab/planx-new/blob/0a1cbc68da8a5f3867b41756083aecd2dda7bd31/editor.planx.uk/src/pages/Preview/Node.tsx#L67-L71
- Add form field for tags to each component (hopefully via `EditorProps<T>` or similar)
- Placeholder UI to add tag in-Editor
=> feat: Add tags to Node data (take 2)

editor.planx.uk/src/lib/pay.ts, editor.planx.uk/src/pages/FlowEditor/components/Settings/Submissions/EventsLog.tsx, editor.planx.uk/src/pages/FlowEditor/lib/store/team.ts
Folks using the existing Uniform connector have been having issues accessing application files in their DMS and more often requesting that a zip be sent to them via Slack, etc - this should make application data easier to self-serve from the editor ! See this thread for more context: https://opensystemslab.slack.com/archives/C5Q59R3HB/p1727791569016769
**Changes:**
- Shows a download button in the submissions log (_if_ it's a sucessful submission within last 28 days, you have team editor privileges to this team, a submission email has been set in team settings)
- This button downloads the same zip that folks access if using "Send to email" - it includes standard PlanX documents (application.csv, application.json, overview.html, redactedOverview.html, locationPlan.html, …
=> feat: allow team editors to download a zip of application data from the editor submissions log

editor.planx.uk/src/pages/FlowEditor/components/Settings/Submissions/EventsLog.tsx
Noticed when merged to staging - eg buttons should be hidden here because > 28 days old https://editor.planx.dev/southwark/apply-for-planning-permission/submissions-log (should help minimise prevalence of "cannot find published flow" error on staging, but that's another topic!)
Was my mistake - just a quick swap of comparison dates here so we're correctly calculating the expiry date _from_ the submission event, not now as before.
=> fix: correct submissions log date comparison (hide download if > 28 days old)

editor.planx.uk/src/@planx/components/List/Public/index.tsx
Improves visibility of the "add new" button for the list component. Abstracts away from common button types to create a custom content-skeleton-esque button for this component.
**Preview:**
https://3756.planx.pizza/testing/list-add-button/preview
**Before:**
**After:**
=> style: Improve visibility of list component add button

editor.planx.uk/src/pages/FlowEditor/components/Sidebar/Search/SearchHeader.tsx, editor.planx.uk/src/pages/FlowEditor/components/Sidebar/Search/facets.ts, editor.planx.uk/src/pages/FlowEditor/components/Sidebar/Search/index.tsx
- Enables "data-only" checkbox to be toggled, which controls if the search uses `DATA_FACETS` or `ALL_FACETS`
- Lists out all text node data values, across all component types, as `ALL_FACETS`
- Still behind a feature flag so I'll pick up the tasks below as follow ups
https://github.com/user-attachments/assets/285f87b3-a71c-4bf1-93e1-a2878cb8fe3c
- Tests (?) - some thoughts here https://opensystemslab.slack.com/archives/C01E3AC0C03/p1727949098464409
- Display all matches in search result cards
- Unpack HTML to string
- Truncate long headlines
- Toggle style of search result cards from "data" to something else
=> feat(search): Enable data-only checkbox

editor.planx.uk/src/pages/FlowEditor/components/Settings/Submissions/EventsLog.tsx, editor.planx.uk/src/pages/FlowEditor/components/Settings/Submissions/index.tsx
Two more minor tweaks to recent Submissions Logs changes - should clear up a bit of confusion based on questions that popped up at planning mtg !
=> fix: update Submission Logs description, hide button on Pay events

editor.planx.uk/src/@planx/components/FileUploadAndLabel/Modal.tsx, editor.planx.uk/src/@planx/components/FileUploadAndLabel/SelectMultipleFileTypes.tsx, editor.planx.uk/src/ui/shared/SelectMultiple.tsx
- Make a new `SelectMultiple` component
- Make a `SelectMultipleFileTypes` component
- Just a refactor, no new functionality or changes, and the existing `FileUploadAndLabel` components all have a decent level of test coverage
- Hit this as a requirement for tagging nodes, based on @ianjon3s's work here - 
- It makes more sense to share how we use a multiple select than to repeat a load of code
- As this relies on the prop `multiple` being present, there's no simple way of handling this via a MUI variant
=> refactor: Make `SelectMultiple` component independent of `FileUploadAndLabel`

editor.planx.uk/src/pages/FlowEditor/components/Sidebar/index.tsx, editor.planx.uk/src/pages/FlowEditor/index.tsx, editor.planx.uk/src/pages/FlowEditor/lib/store/editor.ts
This PR is a rethink of two Friday quick fixes - 
- https://github.com/theopensystemslab/planx-new/pull/3765
- https://github.com/theopensystemslab/planx-new/pull/3766
Originally, I was just resolving a React error and then tidying up some unused store variables.
In this approach, I'm using Zustand's persist middleware pattern ([docs](https://zustand.docs.pmnd.rs/integrations/persisting-store-data)) to handle the variable stores in local storage. Here's the benefits to this approach as I see them - 
- Less boilerplate in components that would need local or session storage - we set this up once in a store
- An easy pattern to follow if we needs something like this elsewhere (e.g. the staging banner, session (!) or notifications when we get there)
- Using a store means the variable could …
=> feat: Use zustand middleware to persist to local storage

editor.planx.uk/src/@planx/components/Content/Public.tsx, editor.planx.uk/src/pages/FlowEditor/floweditor.scss, editor.planx.uk/src/ui/editor/RichTextInput.tsx, editor.planx.uk/src/ui/shared/InputRow.tsx, editor.planx.uk/src/ui/shared/InputRowLabel.tsx
Been meaning to get around to this one for a while!
=> chore: Fix React `:nth-child` warnings

editor.planx.uk/src/routes/index.tsx
- This is a belated follow up to https://github.com/theopensystemslab/planx-new/pull/3671 and https://github.com/theopensystemslab/planx-new/pull/3714
- Re-ordered routes so that the loading progress bar is restored, and the public facing pages maintain their loading spinner
- The previous fix (#3714) wrapped `"*": editorRoutes` in the `loadingView` in order to restore the loading spinner to public facing pages, here I'm (finally!) fixing this properly.
- All Editor routes should have a loading progress bar, when navigating between routes. There is still an initial loading spinner on first load.
- All non-Editor routes should have a loading spinner
=> fix: Restore loading bar and `FlowEditor` state on Editor-only routes

editor.planx.uk/src/components/Header.tsx, editor.planx.uk/src/pages/layout/PublicLayout.tsx
Prompted by the work by @jamdelion to add a print button.
I prototyped a few different approaches here (force background colours to remain, council name as pseudo content in place of logo), but have arrived at a solution that beats all others.
A previous print CSS update removed the large areas of solid header/footer background colour on print (particularly the black of the footer which could take up almost a whole page), and placed a small container with background colour behind the logos. As noted by @jessicamcinchak, removing background colours in print options rendered these invisible (white logo was still in place on white background).
Using `filter: invert(1)` on the images ensure they are still visible regardless of print settings for background graphics, and allows us to keep …
=> refactor: Better handling of print CSS styles

editor.planx.uk/src/components/TestEnvironmentBanner.tsx
- Ensures that the content of the test environment banner are vertically aligned correctly
- It's always been off as `alignItems: "center"` was used without `display: "flex"`, it's just more noticeable now following https://github.com/theopensystemslab/planx-new/pull/3734  which made the banner taller
|<img width="970" alt="image" src="https://github.com/user-attachments/assets/c91c8021-fc60-4990-82c4-07cf433aa466">|<img width="972" alt="image" src="https://github.com/user-attachments/assets/4e61c766-888a-4163-940e-cbfb9f7bc9ba">|
=> fix: Center align text env banner vertically

editor.planx.uk/src/pages/FlowEditor/components/FlowEditor/ToggleTagsButton.tsx, editor.planx.uk/src/theme.ts, editor.planx.uk/src/themeOverrides.d.ts
- Update styling of tag toggle to have a bit more visual prominence (less "floating") and mirror other page inputs
- Creation of an "error" tag state which the red error colour should be reserved for, we may not use this initially
- Nonblocking / to update colour mirror that of which currently used in "sticky note" styling for consistency
=> refactor: Toggle button style and tag colours update

editor.planx.uk/package.json, editor.planx.uk/pnpm-lock.yaml, editor.planx.uk/src/@planx/components/FileUploadAndLabel/schema.ts, editor.planx.uk/src/pages/FlowEditor/components/Flow/components/Tag.tsx, editor.planx.uk/src/pages/FlowEditor/components/FlowEditor/ToggleTagsButton.tsx, editor.planx.uk/src/pages/FlowEditor/index.tsx, editor.planx.uk/src/pages/FlowEditor/lib/store/editor.ts, editor.planx.uk/src/theme.ts, editor.planx.uk/src/themeOverrides.d.ts, editor.planx.uk/src/ui/editor/ComponentTagSelect.tsx
- Imports new tags from planx-core (will bump across all projects once https://github.com/theopensystemslab/planx-core/pull/528 merged to `main`)
- Tags are coloured as per https://opensystemslab.slack.com/archives/C04DZ1NBUMR/p1728385666798109 (OSL Slack)
- Adds toggle to view tags, peristed via local storage
<p align="center">
https://github.com/user-attachments/assets/d48e46ef-1cd6-49ae-9d8f-a792b4742dd3
</p>
=> feat: Setup additional node tags

editor.planx.uk/src/pages/FlowEditor/lib/__tests__/getURLForNode.test.ts, editor.planx.uk/src/pages/FlowEditor/lib/store/editor.ts
- Identified here by @jessicamcinchak - https://opensystemslab.slack.com/archives/C5Q59R3HB/p1727767192939239?thread_ts=1726217456.551129&cid=C5Q59R3HB (OSL Slack)
- When constructing the URL for a node, and then exiting, the path was incorrect
- The order of portals in the URL is hierarchical (grandparent → parent → child), but the path generated by `getPathForNode()` is in opposite order (current node → parent → grandparent).
- This means just need to call `reverse()` on the list of internal portals 👌
- Search for "mansard" in the following flow - https://3773.planx.pizza/opensystemslab/permitteddevelopment
- Close modal
- Your URL is now https://3773.planx.dev/opensystemslab/permitteddevelopment,7GeYLgmnm9,cw73eSHjy2
- You should be able to see the "mansard" node
It's a little …
=> fix: Correctly construct URL by re-ordering portals

editor.planx.uk/src/pages/FlowEditor/floweditor.scss
Fixes a number of styling regressions in the graph introduced by the wrapping div used for tags.
Addresses the following:
- Blank question sticky notes not appearing correctly
- Clones not showing correct dashed background
- Focus and visited states not showing correctly for certain nodes
**Preview of fixed graph:**
https://3782.planx.pizza/testing/graph-styling-fixed
=> fix: Editor graph node link styling

api.planx.uk/modules/webhooks/service/analyzeSessions/operations.ts, editor.planx.uk/src/pages/FlowEditor/lib/analytics/provider.tsx, hasura.planx.uk/migrations/1728311277387_update_analytics_views_pre_app/down.sql, hasura.planx.uk/migrations/1728311277387_update_analytics_views_pre_app/up.sql
**Changes:**
- Adds 3x new values to analytics `ALLOW_LISTS` for Pre App services 
- Updates `analytics_summary` & `submission_services_summary` views 
- Notably remembering to also include `GRANT SELECT ON "public"."{view_name}" TO metabase_read_only;` so that Metabase _should_ smoothly sync/pick up new columns :crossed_fingers:
=> feat: add values to analytics allow lists for Pre Apps

api.planx.uk/modules/pay/service/inviteToPay/sendConfirmationEmail.test.ts, api.planx.uk/modules/pay/service/inviteToPay/sendConfirmationEmail.ts, api.planx.uk/types.ts
- GovNotify is throwing the following error - `"Missing personalisation: serviceName, sessionId"` when trying to populate the `confirmation-agent` email template
- Airbrake logs here - https://planx.airbrake.io/projects/329753/groups/3906275109563899218/notices/3908948747260993950?tab=notice-detail
- Fix types and queries to make sure these variables are provided
- Once this is merged to `production`, I'll manually re-trigger these messages so that the agents receive a confirmation that the application has been paid for
=> fix: Missing personalisation details for `confirmation-agent` email template

editor.planx.uk/src/pages/FlowEditor/components/Team/components/MembersTable.tsx, editor.planx.uk/src/pages/FlowEditor/components/Team/tests/TeamMembers.addNewEditor.test.tsx
- Airbrake caught the following error, which is a teamEditor failing to add a new user https://planx.airbrake.io/projects/329753/groups/3909794420521801267
- They aren't able to do this as they must be a platformAdmin for the action to work
- This means that the button must be visible
I've also messaged the user in question to see if we can help them add a user 👍 
- Add the correct permission guard wrapper to the button
- Update the test to use a non-template team to correctly catch this behaviour
=> fix: Add permission guard to "Add a new Editor" button

e2e/tests/ui-driven/src/refresh-page.spec.ts
🚀 Regression tests running here on CI, passing locally - https://github.com/theopensystemslab/planx-new/actions/runs/11257964868
Best guess is that this was introduced by https://github.com/theopensystemslab/planx-new/pull/3772
The selector `page.getByRole("link", { name: context.team.slug })` is matching both the header and the team "card" in the list - I guess prior to the loading bar this was actually a false positive?
=> fix(e2e): Ensure exact match for team slug

editor.planx.uk/src/components/EditorNavMenu.tsx, editor.planx.uk/src/pages/FlowEditor/components/FlowEditor/ToggleTagsButton.tsx, editor.planx.uk/src/pages/FlowEditor/components/Settings/ServiceSettings/FlowStatus/PublicLink.tsx, editor.planx.uk/src/pages/FlowEditor/components/Settings/Submissions/EventsLog.tsx, editor.planx.uk/src/pages/FlowEditor/components/Sidebar/EditHistory.tsx, editor.planx.uk/src/pages/FlowEditor/components/Sidebar/Publish/PublishDialog.tsx, editor.planx.uk/src/pages/FlowEditor/components/Sidebar/index.tsx, editor.planx.uk/src/theme.ts
- Move repeated tooltip styling to the MUI theme
- Standardises all tooltips within the Editor
- Follow up to https://github.com/theopensystemslab/planx-new/pull/3775#discussion_r1791869180
- Note: `LightToolip` is untouched and intentionally styled this way - if we need to use this more, we can set up a variant
| Component | Before | After |
| `EditorNavMenu` | <img width="114" alt="image" src="https://github.com/user-attachments/assets/b5f1adbb-18e3-49a4-a190-64bc6ca4e3b3"> | <img width="113" alt="image" src="https://github.com/user-attachments/assets/c6c7c2ea-95f7-4d89-9cea-31651bc771ba"> |
| `Tags` | <img width="139" alt="image" src="https://github.com/user-attachments/assets/dfe67680-28a7-44b5-bdd8-114deb4d872f"> | <img width="147" alt="image" …
=> chore: Move repeated shared `Tooltip` styles to MUI theme

README.md, package.json
Please see https://opensystemslab.slack.com/archives/C01E3AC0C03/p1728553069239859 (OSL Slack)
Renames `pnpm add-data` to `pnpm sync-data` to avoid the typo `pnpm add data`
=> chore: Rename add-data to sync-data

editor.planx.uk/src/pages/FlowEditor/components/Settings/ServiceSettings/FlowStatus/PublicLink.tsx
Removes tooltip wrapper from the URL copy function, as the tooltip content replicates that of the text link.
Replication:
=> fix: Remove redundant tooltip on URL copy

api.planx.uk/modules/auth/controller.ts, api.planx.uk/modules/auth/docs.yaml, api.planx.uk/modules/auth/routes.ts
Relates to [this Trello ticket](https://trello.com/c/0gYN7cdt) and follows on from #3453.
After some investigation, I came to the conclusion that implementing [front channel logout](https://learn.microsoft.com/en-us/entra/identity-platform/v2-protocols-oidc#single-sign-out) does not make sense in our context.
Before I realised that, and while trying to figure out how best to implement it, I realised that the API's `/logout` route is never hit, so serves no purpose. Therefore I have removed it in this PR.
As per the Open ID Connect spec, a front channel logout is intended to log a user out of any server on which they are authenticated by a provider (e.g. Microsoft), when they log out of said provider centrally (or via another service).
For example, if I log out of my Microsoft account on …
=> [api] remove `/logout` route (do not implement front channel logout)

editor.planx.uk/src/@planx/components/Result/Editor.tsx
- Updates result component flag descriptions to be multiline text inputs
- Adjusts layout to vertical
- Adds input labels in place of input placeholders
- Removes accordion functionality in favour of presenting a form-based interface
**Example empty form:**
https://3796.planx.pizza/testing/result-empty/nodes/_root/nodes/twngigiPHD/edit
**Example populated form:**
https://3796.planx.pizza/buckinghamshire/find-out-if-you-need-planning-permission/nodes/AVaOWQEwBD/nodes/yc1uC0Mwc7/edit
**Previous:**
**Updated:**
=> refactor: Result component multiline inputs

e2e/tests/ui-driven/src/create-flow-with-geospatial.spec.ts, editor.planx.uk/src/@planx/components/Filter/Editor.test.tsx, editor.planx.uk/src/@planx/components/Filter/Editor.tsx, editor.planx.uk/src/@planx/components/Filter/model.ts, editor.planx.uk/src/pages/FlowEditor/components/Flow/components/Node.tsx
**Changes:**
- Filter component supports picking from any available flagset categories & renders it correctly on the graph
- It defaults to the "Planning permission" category so existing components should work without needing an "Update"
- Uses same bare bones `<select />` styling as External Portal and Result modals, let's revisit styles later
- I have NOT touched the `collectedFlags` store method here, which means that all non-"Planning permission" filters won't actually "work" yet - in that they aren't correctly reading collected flags and still exclusively route down the "No flag result" branch
- This will be addressed once rebased into #3764 (trying to make small PRs for review!)
=> feat: Filters support choosing any flagset category

editor.planx.uk/src/pages/FlowEditor/floweditor.scss
- Regression to graph styling which highlights all children of `.wasVisited` class with a green highlight, not just specific ones
- Believed to have been introduced in https://github.com/theopensystemslab/planx-new/pull/3782
- Use the CSS child selector `>` to limit the styling to child `div` and `a` elements only, not all descendants
https://github.com/user-attachments/assets/91128970-9131-40ba-82e2-7cd5719f6fad
=> fix: Visited node CSS

editor.planx.uk/src/@planx/components/NumberInput/Editor.tsx, editor.planx.uk/src/@planx/components/NumberInput/Public.test.tsx, editor.planx.uk/src/@planx/components/NumberInput/model.ts
This PR adds a switch option to the `<NumberInput>` editor modal to only allow whole numbers. 
A `test()` has been added to the validation schema to test that when `onlyWholeNumbers` is true, then `value` can only be an integer.
```ts
.test({
name: "check for a whole number",
message: "Enter a whole number",
test: (value: string | undefined) => {
if (!value) {
return false;
}
if (input.onlyWholeNumbers && !Number.isInteger(Number(value))) {
return false;
}
return true;
},
});
```
=> feat: Whole number option on Number Input

editor.planx.uk/src/@planx/components/MapAndLabel/Public/index.tsx, editor.planx.uk/src/@planx/components/shared/Schema/InputFields/MapFieldInput.tsx
I have altered the props passed to the map component so the reset icon is now a Trash Icon on the List Map input.
```diff
<my-map
id={id}
// TODO
// ariaLabelOlFixedOverlay={`An interactive map for plotting and describing ${schema.type.toLocaleLowerCase()}`}
height={400}
basemap={mapOptions?.basemap}
drawMode
drawGeojsonData={
features &&
JSON.stringify({
type: "FeatureCollection",
features: features,
})
}
drawMany={mapOptions?.drawMany}
drawColor={mapOptions?.drawColor}
drawType={mapOptions?.drawType}
drawPointer="crosshair"
zoom={20}
maxZoom={23}
latitude={Number(passport?.data?._address?.latitude)}
longitude={Number(passport?.data?._address?.longitude)}
++            resetControlImage="trash"
osProxyEndpoint={`${
import.meta.env.VITE_APP_API_URL
}/proxy/ordnance-survey`}
osCopyright={ …
```
=> refactor: change List Map comp to use Trash icon

editor.planx.uk/src/pages/FlowEditor/components/Flow/components/Checklist.tsx, editor.planx.uk/src/pages/FlowEditor/components/Flow/components/DataField.tsx, editor.planx.uk/src/pages/FlowEditor/components/Flow/components/Option.tsx, editor.planx.uk/src/pages/FlowEditor/components/Flow/components/Question.tsx, editor.planx.uk/src/pages/FlowEditor/components/Flow/components/Thumbnail.tsx, editor.planx.uk/src/pages/FlowEditor/components/FlowEditor/ToggleDataFieldsButton.tsx, editor.planx.uk/src/pages/FlowEditor/components/FlowEditor/ToggleImagesButton.tsx, editor.planx.uk/src/pages/FlowEditor/components/FlowEditor/ToggleTagsButton.tsx, editor.planx.uk/src/pages/FlowEditor/floweditor.scss, editor.planx.uk/src/pages/FlowEditor/index.tsx, editor.planx.uk/src/pages/FlowEditor/lib/store/editor.ts
Adds ability to toggle visibility of images & data fields on the graph. Follows on from #3674 (toggle tags) & #2947 (maximalist biennale graph styling).
In cases where all attributes are set & toggled "on", proposed heirarchy of info from top to bottom is:
- Image
- Flag band
- Text / title (sometimes including icon)
- Data field
- Tag 
Does that feel right? Toggle button group is organised in same vertical order.
=> feat: toggle node images and data fields on editor graph

editor.planx.uk/src/pages/FlowEditor/components/FlowEditor/ToggleDataFieldsButton.tsx, editor.planx.uk/src/pages/FlowEditor/components/FlowEditor/ToggleImagesButton.tsx, editor.planx.uk/src/pages/FlowEditor/components/FlowEditor/ToggleTagsButton.tsx, editor.planx.uk/src/pages/FlowEditor/index.tsx
- Updates editor toggle button group to have a fixed position and contain inner buttons to prevent having to set a fixed bottom/left distance value and replicated styling for each button
- Allows further buttons to be added without needing specific styling
- Unifies heights for each button
**Before (left) vs after (right):**
=> refactor: Simplify editor toggle button group

editor.planx.uk/src/pages/FlowEditor/components/Flow/components/Checklist.tsx, editor.planx.uk/src/pages/FlowEditor/components/Flow/components/Thumbnail.tsx
See feedback & example flows in this thread: https://opensystemslab.slack.com/archives/C04DZ1NBUMR/p1729084076459039
**After:**
&&
=> fix: better styles for toggling images on questions

editor.planx.uk/src/pages/FlowEditor/floweditor.scss
Addresses identified styling snags in the graph following introduction of additional content (images, data, tags):
Nodes now expand to match data width:
Standardised icon styles across nodes (also made a bit more prominent):
(Existing snag fix) URLs now wrapping correctly:
=> fix: Editor graph styling snags

editor.planx.uk/src/@planx/components/MapAndLabel/Public/index.tsx, editor.planx.uk/src/@planx/components/PropertyInformation/Public.tsx, editor.planx.uk/src/@planx/components/shared/Schema/InputFields/MapFieldInput.tsx
Coming from user feedback contained in the Trello Ticket: https://trello.com/c/liDbYC96/3094-both-options-show-static-boundary-or-address-point-for-reference-using-geojsondata-prop?filter=member:rorydoak2
We have added the boundary to map components so users can clearly see their property boundary when adding trees. 
Main changes are using the `geoJsonData` prop to populate a readonly boundary using passport data
https://github.com/user-attachments/assets/ad6067a3-24b4-4404-8c0c-13b7bfcddc53
=> feat: add Boundary to Map and Label comp

editor.planx.uk/src/pages/FlowEditor/components/Sidebar/EditHistory.tsx
The combination of black text mixed with accordions and buttons in the history panel can be difficult to parse visually. This PR improves the legibility of the history view by creating visual hierarchy and grouping. Uses a familiar "chat history" style to create a greater boundary between actions.
I've also removed the repeated text "Edited by", open to be challenged on this, but I don't think it's needed.
**Before vs after:**
=> style: Refine history styling for legibility

editor.planx.uk/src/@planx/components/Pay/Public/Pay.tsx
- The Editor interface of the Pay component only ever knows about its own context - `flowName` will always be the flow it's held within
- At runtime, as an applicant hits the public interface of the component, the context can be different - `flowName` is the root ("parent" flow)
- This means that we send the incorrect flow name to GovPay
- Be a bit more smart about setting the defaults at runtime in the Public interface
- Always overwrite with the _current_ flow name, which is always correct
I didn't find a good way to test this (without setting up a new E2E test). Open to ideas!
You can test this manually here - 
- Public interface - https://3826.planx.pizza/buckinghamshire/test-pay-metadata/published?analytics=false
- Editor interface - …
=> fix: Correctly set parent flow name in GovPayMetadata

e2e/tests/ui-driven/package.json, e2e/tests/ui-driven/pnpm-lock.yaml
Fixes https://github.com/theopensystemslab/planx-new/security/dependabot/115 now that [`serve` has been updated](https://github.com/vercel/serve/releases/tag/14.2.4).
=> chore: CVE-2024-45296

editor.planx.uk/src/components/PrintButton.tsx
Trello ticket: https://trello.com/c/4fhbFPFw/3097-can-we-force-a-timestamp-on-the-new-print-button-regardless-of-browsers-settings-for-the-upload-and-label-review-component
I've simply added some `@media print` CSS so that the 'Print this page' button turns into a line of text saying 'Printed at `<timestamp>`.
Open to wording and styling opinions!
=> feat: add 'printed at' timestamp to print view

editor.planx.uk/src/pages/FlowEditor/components/Sidebar/Search/index.test.tsx
Quick update here, realised whilst working on #3783 that there was a `test.todo()` here that I'd missed.
Please note that the underlying functionality in `getURLForNode()` is tested elsewhere - all we really care about here is that it's correctly wired up.
=> test: Outstanding `test.todo()` in Search component

api.planx.uk/modules/send/docs.yaml
- Add Swagger docs for `/upload-submission/:localAuthority` endpoint
- Add Swagger docs for `/idox/:localAuthority` endpoint
Quick fix I noticed when adding docs for a GOSS endpoint.
=> docs: Update send Swagger API docs

doc/how-to/how-to-add-a-team-secret.md
Another doc update based on more Jo-misunderstandings 😅
=> docs: add note about envs to team-secret doc

.github/workflows/sync-staging-db.yml
Please see https://opensystemslab.slack.com/archives/C01EVPXFU7K/p1729769117634399 for context (OSL Slack)
Using the psql flag `VERBOSITY=terse` will prevent error `DETAILS` being caught in CI logs, but would still appear when running locally ([docs](https://www.postgresql.org/docs/current/runtime-config-logging.html#:~:text=TERSE%20excludes%20the%20logging%20of,number%20that%20generated%20the%20error.)).
=> chore: Add `VERBOSITY=terse` flag to db sync script in CI

editor.planx.uk/src/pages/FlowEditor/components/Sidebar/Publish/PublishDialog.tsx
Flagged by August here https://opensystemslab.slack.com/archives/C01E3AC0C03/p1729858933090839
A couple tricky factors at play here:
- When we flatten flows on publish, external portal node types are converted to internal portal node types, which means we can't filter on node type and instead filter on the "name" of the external or internal portal
- In this particular example, the name of the internal portal is `LDCe & LDCp s.191b/s.191a` which includes a `/` and matched our previous string matching logic which assumed every internal portal name including a `/` must be originally an external portal (eg `{team-slug}/{flow-slug}`) 
This isn't a particularly robust for future-proof fix, but should do the trick for now! External portals names will never have spaces because they are slugs.
=> fix: adjust string matching conditions for summarising external portal changes on publish

editor.planx.uk/.eslintrc
Quick fix which resolves about 20 warnings in the codebase. It's a pretty common (and required) pattern to have empty functions in Storybook files (see screenshot below). This change turns off this check.
=> chore: Turn off `no-empty-function` lint rule in Storybook files

editor.planx.uk/src/components/Header.tsx, editor.planx.uk/src/routes/feedback.tsx, editor.planx.uk/src/routes/serviceSettings.tsx, editor.planx.uk/src/routes/submissionsLog.tsx
Fixes https://trello.com/c/AdUlB86T/3076-fix-header-breadcrumb-view-when-viewing-settings-submission-log-and-feedback-screens-for-a-service
At some point when refactoring routes, I've missed adding the flow name to `route.data`.
We could also get this from the store, but that would mean - 
- needing to nullify `flowSlug` when navigating back to `/teams
- if we want additional breadcrumbs (e.g. "/ feedback") in the header, we'd be controlling them via Zustand
In reality, the route is the most reliable and simple source of truth here for breadcrumbs 👍 
https://github.com/user-attachments/assets/f5759fe8-9433-4569-94c6-8ba1d2bcfefd
=> fix: Flow breadcrumb missing in `Header` component

api.planx.uk/package.json, api.planx.uk/pnpm-lock.yaml, e2e/tests/api-driven/package.json, e2e/tests/api-driven/pnpm-lock.yaml, e2e/tests/ui-driven/package.json, e2e/tests/ui-driven/pnpm-lock.yaml, editor.planx.uk/package.json, editor.planx.uk/pnpm-lock.yaml
Updating planx-core refs to start using the demoUser type in editor features for demo workspaces
=> bump: planx-core for demoUser type

editor.planx.uk/package.json, editor.planx.uk/pnpm-lock.yaml, editor.planx.uk/src/@planx/components/shared/Schema/InputFields/MapFieldInput.tsx
Following work on the map repo to add in a prop to handle hiding the labels shown on a point or polygon, I have added this to the list Map Input, linking it to the `drawMany` prop
=> feat: add `hideDrawLabels` to List Map Input

hasura.planx.uk/metadata/tables.yaml, hasura.planx.uk/migrations/1729675271585_insert_into_public_user_roles/down.sql, hasura.planx.uk/migrations/1729675271585_insert_into_public_user_roles/up.sql, hasura.planx.uk/tests/analytics.test.js, hasura.planx.uk/tests/blpu_codes.test.js, hasura.planx.uk/tests/bops_applications.test.js, hasura.planx.uk/tests/email_applications.test.js, hasura.planx.uk/tests/feedback.test.js, hasura.planx.uk/tests/feedback_status.test.js, hasura.planx.uk/tests/feedback_type_enum.test.js, hasura.planx.uk/tests/flow_document_templates.test.js, hasura.planx.uk/tests/flow_status_history.test.js, hasura.planx.uk/tests/flows.test.js, hasura.planx.uk/tests/global_settings.test.js, hasura.planx.uk/tests/lowcal_sessions.test.js, hasura.planx.uk/tests/payment_requests.test.js, hasura.planx.uk/tests/payment_status.test.js, hasura.planx.uk/tests/planning_constraints_requests.test.js, hasura.planx.uk/tests/reconciliation_requests.test.js, hasura.planx.uk/tests/sessions.test.js, hasura.planx.uk/tests/team_integrations.test.js, hasura.planx.uk/tests/team_members.test.js, hasura.planx.uk/tests/team_themes.test.js, hasura.planx.uk/tests/teams.test.js, hasura.planx.uk/tests/uniform_applications.test.js, hasura.planx.uk/tests/users.test.js, hasura.planx.uk/tests/utils.js
For the Demo Workspace, a `demoUser` may only see flows created by them, or flows within the Open Systems Lab, Open Digital Planning, or Templates team. Also, they cannot see team settings or any other setting outwith flow settings for their own flows.
I have treated them as a `teamEditor` within their flows, and restricted data they can see outwith this. 
Introspection testing has been added to help communicate the relevant permissions changes and ensure future maintainability.
=> feat: add demoUser role to Hasura with permissions

editor.planx.uk/src/pages/FlowEditor/index.tsx
Fixes issue raised here - https://opensystemslab.slack.com/archives/C5Q59R3HB/p1730126400538669 (OSL Slack)
The PR ensures that the URL is correctly deconstructed when we're within a portal root. Previously, it was incorrectly deconstructed leading to the fallback `ROOT_NODE_KEY` being relied on in `editor.planx.uk/src/pages/FlowEditor/components/Flow/index.tsx`
=> fix: Persist portal state behind node modal

hasura.planx.uk/metadata/tables.yaml
This follows work on the demo workspace ticket: https://trello.com/c/EfaEQRzK/2441-create-a-demo-workspace
We found that the `creator_id` was not populating when we create a flow in the editor. To fix this, we decided to use Hasura Column Presets to reduce the number of places the change had to be made, and to make it more maintainable in the future.
We do sacrifice readability in the code base, but we found it was a better win for maintainability for a data field most people would expect to be populated by the user creating it. 
[Column Preset Docs](https://hasura.io/docs/2.0/auth/authorization/permissions/column-presets/)
=> feat: Use Hasura column presets to populate `creator_id`

editor.planx.uk/src/pages/FlowEditor/components/Team/components/EditorUpsertModal.tsx, editor.planx.uk/src/pages/FlowEditor/components/Team/components/MembersTable.tsx, editor.planx.uk/src/pages/FlowEditor/components/Team/components/lib/optimisticallyUpdateMembersTable.tsx, editor.planx.uk/src/pages/FlowEditor/components/Team/queries/createAndAddUserToTeam.tsx, editor.planx.uk/src/pages/FlowEditor/components/Team/tests/TeamMembers.addNewEditor.demoTeam.test.tsx, editor.planx.uk/src/pages/FlowEditor/components/Team/tests/TeamMembers.addNewEditor.test.tsx, editor.planx.uk/src/pages/FlowEditor/components/Team/tests/TeamMembers.removeUser.test.tsx, editor.planx.uk/src/pages/FlowEditor/components/Team/tests/TeamMembers.updateEditor.test.tsx, editor.planx.uk/src/pages/FlowEditor/components/Team/types.ts
- If a user is added to the demo team, assigns the `demoUser` role instead of the `teamEditor` role
- Add a user to the "Demo" team
- User appears in table with `demoUser` role applied
- Hasura `team_members` table confirms this
- Enforce via login API that users with the `demoUser` role can only access staging
- Update team members UI to me more role agnostic - some language like "Team Editors" is not quite right (`demoUser` and `teamViewer` users are displayed)
- Hide certain UI elements from `demoUser` role
=> feat: Adding a new user in the demo team automatically assigns the `demoUser` role

editor.planx.uk/src/pages/FlowEditor/components/Team/components/MembersTable.tsx
Please see React warnings below.
This PR fixes the broken table structure in this component.
=> fix: Invalid table warnings

editor.planx.uk/.eslintrc, editor.planx.uk/src/@planx/components/Checklist/Public.tsx, editor.planx.uk/src/@planx/components/Question/Public/Question.tsx, editor.planx.uk/src/pages/FlowEditor/lib/__tests__/automations.blanks.test.ts, editor.planx.uk/src/pages/FlowEditor/lib/__tests__/preview/autoAnswerableFlag.test.ts, editor.planx.uk/src/pages/FlowEditor/lib/store/preview.ts
Follows on from #3764 
Running `pnpm check` in the editor subdirectory now returns 0 errors for me, sorry I missed these on initial merge !
=> fix: eslint errors from auto-answering changes

api.planx.uk/modules/auth/service.test.ts, api.planx.uk/modules/auth/service.ts, api.planx.uk/modules/auth/types.ts
- Adds a guard to control that users with the `demoUser` role cannot access production
- Type tidy ups
Originally, we did consider reusing the `is_staging_only` column for this purpose. However, I think it's clearer and more meaningful to check the role and just follow the same pattern as opposed to repurposing the `is_staging_only` column.
=> feat: Add check for `demoUser` role on login

api.planx.uk/modules/webhooks/service/analyzeSessions/operations.ts, editor.planx.uk/src/pages/FlowEditor/lib/analytics/provider.tsx, hasura.planx.uk/migrations/1730210889444_add application type to analytics/down.sql, hasura.planx.uk/migrations/1730210889444_add application type to analytics/up.sql
I have added `application.type` to the `ALLOW_LIST` in the relevant api and editor repos, and I have added a migration to add a `application_type` to the `analytics_summary` and the `submission_services_summary` 
Ran through Southwarks Apply for Planning Permission service and tested the output, and received `["pp.full.householder"]` in the `analytics_summary` and the same in the `submission_services_summary`
If this is all good, I'll work up a how-to doc for future ref
=> feat: add `application.type' to allow list for Metabase

api.planx.uk/modules/auth/service.ts
Altered the JWT token builder in the api to set the correct role rather than falling back to only `teamEditor`.
Now it will correctly select `platformAdmin | teamEditor | teamViewer | demoUser`
=> feat: add demo user to api hasura roles

editor.planx.uk/src/pages/FlowEditor/components/Team/TeamMembers.tsx, editor.planx.uk/src/pages/FlowEditor/components/Team/components/MembersTable.tsx, editor.planx.uk/src/pages/FlowEditor/components/Team/components/UserUpsertModal.tsx, editor.planx.uk/src/pages/FlowEditor/components/Team/errors/addNewEditorErrors.tsx, editor.planx.uk/src/pages/FlowEditor/components/Team/formSchema.tsx, editor.planx.uk/src/pages/FlowEditor/components/Team/tests/TeamMembers.addNewMember.demoTeam.test.tsx, editor.planx.uk/src/pages/FlowEditor/components/Team/tests/TeamMembers.addNewMember.errors.serverSide.test.tsx, editor.planx.uk/src/pages/FlowEditor/components/Team/tests/TeamMembers.addNewMember.errors.userAlreadyExists.test.tsx, editor.planx.uk/src/pages/FlowEditor/components/Team/tests/TeamMembers.addNewMember.noExistingMembers.test.tsx, editor.planx.uk/src/pages/FlowEditor/components/Team/tests/TeamMembers.addNewMember.test.tsx, editor.planx.uk/src/pages/FlowEditor/components/Team/tests/TeamMembers.removeUser.test.tsx, editor.planx.uk/src/pages/FlowEditor/components/Team/tests/TeamMembers.updateEditor.test.tsx, editor.planx.uk/src/pages/FlowEditor/components/Team/tests/helpers/setupTeamMembersScreen.tsx, editor.planx.uk/src/pages/FlowEditor/components/Team/tests/helpers/userTriesToAddNewMember.tsx
- Update copy on "Team Members" page to be less Editor specific, for example changing the titles from "Team Editors" to "Team Members"
- Updates language used to code to also reflect this
=> chore: Update copy on "Team Members" page to be less Editor specific

editor.planx.uk/src/@planx/components/List/schemas/Trees.ts, editor.planx.uk/src/@planx/components/List/schemas/TreesMapFirst.ts, editor.planx.uk/src/@planx/components/MapAndLabel/schemas/Trees.ts, editor.planx.uk/src/pages/FlowEditor/components/Sidebar/Search/mocks/dataFacetFlow.ts
- Adds a description/hint text to map date inputs `For example, 16 04 2027`, in line with [GOV.UK example](https://design-system.service.gov.uk/components/date-input/).
Identified in user-research, 2/5 householder participants tried to enter months using text (i.e. "Nov").
A first instinct was to add a script to insert an example date [for example] 6 months in the future, so that the suggested date would be relevant(ish) and never "expire". Seems like something that can be solved by setting a date well into the future to save unnecessary functionality. Interested to hear other opinions on this.
**Preview:**
=> feat: Description text for map schema date input

hasura.planx.uk/metadata/tables.yaml, hasura.planx.uk/tests/team_members.test.js
A few issues when testing the `demoUser` role end-to-end - 
- All users must be able to access their own record in the `team_members` table in order to log in
- All users must have read access to the `team_settings` table
=> fix: Grant additional permissions to demoUser role

editor.planx.uk/src/pages/FlowEditor/lib/store/user.ts
Continuing work of the demo workspaces: https://trello.com/c/EfaEQRzK/2441-create-a-demo-workspace
I have expanded the use of the `canUserEdit` store function to return `true` as long as the `role !== "teamViewer"` as the database will populate the `user.teams` array with all teams the user is a team member of. The only role that can be assigned where you wouldn't be able to edit is the `teamViewer` role thus, I went with this for the condition.
In other circumstances, a user may be a `teamEditor` or `demoUser` and in both cases this will be assigned only on the teams they can edit
=> refactor: expand canUserEdit function to include all user roles

api.planx.uk/helpers.ts, api.planx.uk/modules/flows/copyFlow/service.ts
- The `/flows/:flowId/copy` endpoint is broken - throwing a permission error due to a missing field `creator_id`
- All roles which write to this table have write permissions for this column
When we added a column preset for `creator_id` (https://github.com/theopensystemslab/planx-new/pull/3864) it removed the columns from the insert schema for the flows table.
> The respective fields will also be removed from the generated GraphQL schema for that role.
Source: https://hasura.io/docs/2.0/auth/authorization/permissions/column-presets/
- Let Hasura handle this and populate it from the JWT, remove our custom code for fetch the user ID from the JWT
- It's actually a pretty nice solution / pattern imho!
- I've checked for other references to `creator_id` and `creatorId` - this is the only one …
=> fix: Remove manual population of creator ID

api.planx.uk/modules/auth/middleware.ts
A `demoUser` was forbidden from copying a flow due to the API running auth on if the user is a `teamEditor | platformAdmin` I have now added `demoUser` to this list
=> feat: add demoUser to api user auth

.github/workflows/pull-request.yml
Ticket: https://trello.com/c/WdZicC3b
Resolves the problem in exactly the same way as we do for Google - we do the auth whole flow via the staging API (`api.editor.planx.dev`), and are returned to the pizza afterwards (rather than the staging client).
=> route Microsoft auth requests from pizzas to staging API

editor.planx.uk/src/pages/FlowEditor/components/Flow/components/Option.tsx
Flagged here: https://opensystemslab.slack.com/archives/C01E3AC0C03/p1730462810086459
To recreate bug on staging/prod: 
- Add a question and assign flags to an option and another option without flags -> "create" -> color bands display as expected
- Update that node and remove the flags from the option -> "update" -> no color band displays on updated option
- Fix is to explicitly check for `flags.length > 0` so that `flags = []` doesn't evaluate to `FlagBand` option
=> fix: ensure "no flag" band always displays if no flags are present

doc/architecture/decisions/0003-testing-approach.md, doc/architecture/decisions/0008-authentication-with-microsoft.md, doc/how-to/how-to-setup-azure-application.md
Documentation for Microsoft auth in the form of a new ADR and related how-to.
Definitely final PR on this (pending bugs...) 🥳
=> add ADR#0008 re Microsoft auth, and related HOWTO re Azure application

editor.planx.uk/src/@planx/components/Checklist/Editor.tsx, editor.planx.uk/src/@planx/components/Question/Editor.tsx, editor.planx.uk/src/pages/FlowEditor/lib/store/preview.ts
Fixes edge case flagged here: https://opensystemslab.slack.com/archives/C5Q59R3HB/p1730455691984869
**Two changes:**
- `autoAnswerableOptions` condition is corrected so that _existing_ nodes will behave as expected (put to user)
- Formik validation added to editor modal for Questions & Checklists so that future nodes aren't allowed to do this at all 
**Testing:**
- Production https://editor.planx.uk/testing/self-automation
- Pizza https://3903.planx.pizza/testing/self-automation
=> fix: ensure questions that set a data field with no option data values are not automated

editor.planx.uk/src/pages/FlowEditor/components/Team/components/MembersTable.tsx
This now matches the button shown if there are members - the same guard and check wraps both instances of this button now.
=> fix: Add guard around add member button

hasura.planx.uk/metadata/tables.yaml, hasura.planx.uk/migrations/1730742914548_create_index_bops_applications_session_id/down.sql, hasura.planx.uk/migrations/1730742914548_create_index_bops_applications_session_id/up.sql
Follows on from publishing debugging today: https://opensystemslab.slack.com/archives/C01E3AC0C03/p1730715895034839
**Approached this from two directions:**
1. Which indexes are we missing? Where is postgres is doing more sequence scans than index scans?
- This blog has a useful sample query: https://erikrw.hashnode.dev/how-to-identify-missing-indexes-in-postgresql
- From these results, I then cross-checked with how we commonly query those tables (eg `where` params)
- ![Screenshot from 2024-11-04 19-05-38](https://github.com/user-attachments/assets/a1366460-d325-4ece-9a49-d3aa6e06418c)
2. Which existing indexes are unused? Can any be removed?
- Ran `select * from pg_stat_user_indexes where schemaname = 'public' order by idx_scan asc;` for this one
- We do have multiple cases of existing …
=> fix: add missing postgres indexes 

hasura.planx.uk/tests/team_settings.test.js
While doing the `demoUser` work, we found that we were missing introspection tests for `team_settings`.
I have mocked these off the `team_themes` introspection tests since the permissions are mirrored
=> feat: add `team_settings` introspection tests

editor.planx.uk/src/components/EditorNavMenu.tsx, editor.planx.uk/src/pages/FlowEditor/lib/store/user.ts
Ensure `demoUser` role cannot view Team settings, team members, or team design pages.
Feedback from Show & Tell - users cannot use pages anyway, no benefit to showing them.
=> fix: Hide `/:teams` `EditorNavMenu` from `demoUser` role

editor.planx.uk/src/@planx/components/Checklist/Editor.tsx, editor.planx.uk/src/@planx/components/Question/Editor.tsx, editor.planx.uk/src/pages/FlowEditor/lib/store/preview.ts
Reverts theopensystemslab/planx-new#3903
See thread here https://opensystemslab.slack.com/archives/C01E3AC0C03/p1730884655361309
This is failing to automation `property.localAuthorityDistrict` & `property.region` questions because these data fields are not stored under `fn` in FindProperty.
=> Revert "fix: ensure questions that set a data field with no option data values are not automated"

api.planx.uk/package.json, api.planx.uk/pnpm-lock.yaml, e2e/tests/api-driven/package.json, e2e/tests/api-driven/pnpm-lock.yaml, e2e/tests/ui-driven/package.json, e2e/tests/ui-driven/pnpm-lock.yaml, editor.planx.uk/package.json, editor.planx.uk/pnpm-lock.yaml
Please see for full details - https://github.com/theopensystemslab/planx-core/pull/553
Example flows where this can be tested -
- https://editor.planx.uk/testing/exit-portal-test
- https://3914.planx.pizza/testing/exit-portal-test
Expected behaviour - search result cards correctly match the internal portal they are in.
=> fix: Correctly track portal IDs when indexing nodes

api.planx.uk/package.json, api.planx.uk/pnpm-lock.yaml, e2e/tests/api-driven/package.json, e2e/tests/api-driven/pnpm-lock.yaml, e2e/tests/ui-driven/package.json, e2e/tests/ui-driven/pnpm-lock.yaml, editor.planx.uk/package.json, editor.planx.uk/pnpm-lock.yaml
See https://github.com/theopensystemslab/planx-core/pull/556 for context
**Testing notes:**
This flow has a sticky note question, put-to-user question, and auto-answered question https://3918.planx.pizza/testing/docs-test/published?analytics=false
Here's how each should be handled by the following components / documents:
- Result: put-to-user _and_ auto-answered questions may be included under "Reasons" depending on flags, only put-to-user questions should have a "change" link
- Review: only put-to-user questions are included, all have "change" link
- Submission docs:
- overview.html: put-to-user _and_ auto-answered questions are included, with "auto-answered" annotation
- application.csv: put-to-user _and_ auto-answered questions are included, with "auto" metadata
- application.json …
=> fix: filter questions without responses out of generated docs

editor.planx.uk/src/pages/FlowEditor/components/Flow/FeedbackLog/FeedbackLog.tsx, editor.planx.uk/src/pages/FlowEditor/components/Flow/FeedbackLog/components/CollapsibleRow.tsx, editor.planx.uk/src/pages/FlowEditor/components/Flow/FeedbackLog/queries/getFeedbackById.ts, editor.planx.uk/src/pages/FlowEditor/components/Flow/FeedbackLog/styled.ts, editor.planx.uk/src/routes/feedback.tsx
- Split out FeedbackPage file into its own folder
- Added subfolders for queries, styled and components.
- Renamed to `FeedbackLog`.
=> refactor: tidy up feedback log component

api.planx.uk/package.json, api.planx.uk/pnpm-lock.yaml, e2e/tests/api-driven/package.json, e2e/tests/api-driven/pnpm-lock.yaml, e2e/tests/ui-driven/package.json, e2e/tests/ui-driven/pnpm-lock.yaml, editor.planx.uk/package.json, editor.planx.uk/pnpm-lock.yaml, editor.planx.uk/src/@planx/components/FindProperty/Public/Autocomplete.tsx, editor.planx.uk/src/@planx/components/FindProperty/model.ts
- Updates `planx-core` (see https://github.com/theopensystemslab/planx-core/pull/557)
- Update type for `_address` stored in passport to match schema - this should have a value of `string | undefined` and we're currently passing along `""`
- This is both correct from a type POV and falsy (in JS), but I think the intention here is not to populate the field so `undefined` seems correct here to me
| ![image](https://github.com/user-attachments/assets/c71fd0d4-193e-4135-8b3c-c4641f402a14) | ![image](https://github.com/user-attachments/assets/44ca50dc-34bc-4705-8709-e3f7be415e8a) |
=> chore: Bump `planx-core`, update `_address` type in passport

editor.planx.uk/src/pages/FlowEditor/components/Flow/FeedbackLog/components/CollapsibleRow.tsx
Small issue I spotted when reviewing #3920
=> fix: Typo on FeedbackPage icon title

editor.planx.uk/src/@planx/components/shared/Radio/BasicRadio.tsx, editor.planx.uk/src/pages/FlowEditor/components/Settings/ServiceSettings/FlowStatus/index.tsx, editor.planx.uk/src/theme.ts
Quick one: fixes alignment of `FormControlLabel` when used inline in a form.
Margin is added to `BasicRadio` to maintain alignment within that component.
**Before:**
**After:**
=> fix: FormControlLabel spacing

editor.planx.uk/src/pages/FlowEditor/components/Settings/ServiceSettings/FooterLinksAndLegalDisclaimer.tsx
The current description of the Legal Disclaimer section in the service settings is incorrect. Legal Disclaimers are part of and displayed on the Result component, which 1. can sit in non-submission services, 2. can be absent from submission services, and 3. can (as in the current use case of LDCs) sit nowhere near the submission.
=> fix: correct legal disclaimer description in service settings

editor.planx.uk/src/@planx/components/Feedback/Public/Public.tsx, editor.planx.uk/src/@planx/components/Feedback/components/FaceBox.tsx, editor.planx.uk/src/@planx/components/Feedback/components/defaultContent.tsx, editor.planx.uk/src/@planx/components/Feedback/styled.ts, editor.planx.uk/src/@planx/components/shared/Disclaimer.tsx
Small styling refinements to @jamdelion's work on the feedback component:
- Updates rating buttons to be responsive to width
- Updates selected rating button to be consistent with styling of selected radio grid (blue border)
- Small type and spacing refinements
**Before:**
**After:**
=> style: Feedback component style refinement 

editor.planx.uk/src/@planx/components/Checklist/Editor.tsx, editor.planx.uk/src/@planx/components/Question/Editor.tsx, editor.planx.uk/src/pages/FlowEditor/lib/store/preview.ts
Follows on from #3903 (which was reverted via theopensystemslab/planx-new#3915)
See thread here https://opensystemslab.slack.com/archives/C01E3AC0C03/p1730884655361309
Original solution was failing to automate `property.localAuthorityDistrict` & `property.region` questions because these data fields are not stored under `fn` in FindProperty.
=> fix (take 2): ensure questions that set a data field with no option data values are not automated

editor.planx.uk/src/pages/FlowEditor/lib/store/preview.ts
It appears that when we're loading flows, we're sometimes attempting to run `autoAnswerableOptions` before the whole flow has loaded (eg on `_root` node rather than true current card??) leading to errors like the one screenshot below & reported by Ian Grace in #help-issues here: https://opensystemslab.slack.com/archives/C5Q59R3HB/p1731336388546549
This tries destructuring the single `node` first before immediately assuming it has `{ type, data, edges }` too, similar with passport to account for cases where it's empty (eg no `data` yet)
=> fix: safer destructuring in `autoAnswerableOptions` to prevent error on initial editor load

editor.planx.uk/.eslintrc, editor.planx.uk/src/@planx/components/Calculate/Editor.tsx, editor.planx.uk/src/@planx/components/Checklist/Editor.tsx, editor.planx.uk/src/@planx/components/DrawBoundary/Editor.tsx, editor.planx.uk/src/@planx/components/Feedback/Editor/Editor.tsx, editor.planx.uk/src/@planx/components/FileUploadAndLabel/Editor.tsx, editor.planx.uk/src/@planx/components/FindProperty/Editor.tsx, editor.planx.uk/src/@planx/components/Notice/Editor.tsx, editor.planx.uk/src/@planx/components/NumberInput/Editor.tsx, editor.planx.uk/src/@planx/components/Pay/Editor.tsx, editor.planx.uk/src/@planx/components/PropertyInformation/Editor.tsx, editor.planx.uk/src/@planx/components/Question/Editor.tsx, editor.planx.uk/src/pages/FlowEditor/components/Settings/ServiceSettings/FlowStatus/index.tsx, editor.planx.uk/src/pages/FlowEditor/components/Settings/ServiceSettings/FooterLinksAndLegalDisclaimer.tsx, editor.planx.uk/src/ui/shared/Switch.tsx
- Makes a single `Switch` component, with label, to be used across PlanX
- This stops repetition, and should help with drift in other components in future
- Ensures just switch and label is clickable, not entire row
- Adds `.eslint` rule to enforce that the shared component should be imported
=> feat: Use shared `Switch` component instead of MUISwitch directly

editor.planx.uk/src/pages/FlowEditor/components/Settings/ServiceSettings/FlowStatus/index.tsx, editor.planx.uk/src/pages/FlowEditor/components/Settings/ServiceSettings/FooterLinksAndLegalDisclaimer.tsx, editor.planx.uk/src/ui/shared/Switch.tsx
Please see https://opensystemslab.slack.com/archives/C01E3AC0C03/p1731334276253779?thread_ts=1731076346.004359&cid=C01E3AC0C03 for context (OSL Slack)
This PR ensures that only the content of the label is clickable, not the entire block of the span. As there's a wrapping label we need to control pointer events to allow certain elements to be clickable (or not).
https://github.com/user-attachments/assets/69a8b6d4-b4c1-4740-9b1d-988269ba34a0
=> fix: Only content of Switch label is clickable

editor.planx.uk/src/@planx/components/Checklist/Editor.tsx, editor.planx.uk/src/@planx/components/NextSteps/Editor.tsx, editor.planx.uk/src/@planx/components/Question/Editor.tsx, editor.planx.uk/src/@planx/components/Result/Editor.tsx, editor.planx.uk/src/pages/FlowEditor/components/Flow/components/Option.tsx, editor.planx.uk/src/ui/shared/Input/Input.tsx
I have added the `multiline` prop to certain text inputs to allow multiline text in things like Options in Checkboxes.
Adjustment had to me made with the `textarea` component as it used a `height: auto` rather than a `height: 100%` the change hasn't broken any styling I could find, so hope its okay!
Tested by August here: https://opensystemslab.slack.com/archives/C04DZ1NBUMR/p1730291082584539
=> feat: Add multiline to text inputs

api.planx.uk/modules/webhooks/service/sendNotification/index.ts
Quick solution to request from Silvia here https://opensystemslab.slack.com/archives/C5Q59R3HB/p1731492906193889
If a submisison fits the criteria of ODP Pilot Testing, we want to visually differentiate it's notification in the #planx-notifications channel on Slack with a `:large_orange_square:` emoji prefix
=> chore: add formatting to Slack notifications if meets pilot testing criteria

editor.planx.uk/src/@planx/components/Feedback/Editor/FeedbackEditor.stories.tsx, editor.planx.uk/src/components/Feedback/types.ts, editor.planx.uk/src/pages/FlowEditor/components/Flow/FeedbackLog/FeedbackLog.tsx, editor.planx.uk/src/pages/FlowEditor/components/Flow/FeedbackLog/components/CollapsibleRow.tsx, editor.planx.uk/src/routes/feedback.tsx, hasura.planx.uk/metadata/tables.yaml, hasura.planx.uk/migrations/1731495319577_run_sql_migration/down.sql, hasura.planx.uk/migrations/1731495319577_run_sql_migration/up.sql
- Added column in feedback log for feedback score
- Added 'feedback from component' as a feedback type that can be displayed in the log
- This involved updating the `feedback_summary` table to copy across the `feedbackScore` from the `feedback` table.
=> feat: Display feedback score in feedback log

editor.planx.uk/src/@planx/components/Notice/Public.tsx
This PR ensures that the Notice component has a defined aria-label for its _More information_ button and displays this button below its content block (if defined).
It replaces the use of CardHeader in the Notice component with a custom More information layout using a static aria-label (copying the approach used for the Content component).
=> fix: customise and move location of Notice component More Information button

editor.planx.uk/src/@planx/components/shared/FlagsSelect.tsx, editor.planx.uk/src/ui/editor/ListManager/ListManager.tsx, editor.planx.uk/src/ui/shared/SelectMultiple.tsx
Alternate implementation of https://github.com/theopensystemslab/planx-new/pull/3927
Visually the same, but relies on more simplified and strict type checking in the component to allow either `label` or `placeholder` to be passed as props.
https://github.com/user-attachments/assets/5a36014a-a5f4-402a-9e25-d41d4c93fced
=> feat: Allow `SelectMultiple` to have either a `label` or `placeholder` prop

scripts/seed-database/write/flows.sql
`pnpm run up` on a fresh database is currently failing with the following error message (because we `select * from flows` but are missing recently added column defs)
=> fix: sync all columns in `flows` table

editor.planx.uk/src/pages/FlowEditor/components/Flow/components/EndPoint.tsx
- Ensures flow is always centered, after load
- Alternate implementation of https://github.com/theopensystemslab/planx-new/pull/3854/files#r1816927924
- This does not change or remove the current session storage of x and y values, looking at this separately 
Following https://github.com/theopensystemslab/planx-new/pull/3854 there was some valuable feedback on how this _should_ behave which I'll pick up in follow up PRs.
=> fix: Always center flows on load

api.planx.uk/modules/saveAndReturn/service/utils.ts
- When an application is submitted to multiple locations, the `email_user_submission_confirmation` event trigger is called multiple times, resulting in multiple emails being sent to applicants from PlanX.
- This is recreatable locally, and can be observed as a pattern via GovNotify or the Hasura event log - we can see grouped events and emails for the same PlanX session
- Adds a check within the query, so that the trigger is only called once
=> fix: Only trigger `email_user_submission_confirmation` event once per session

api.planx.uk/package.json, api.planx.uk/pnpm-lock.yaml, e2e/tests/api-driven/package.json, e2e/tests/api-driven/pnpm-lock.yaml, e2e/tests/ui-driven/package.json, e2e/tests/ui-driven/pnpm-lock.yaml, editor.planx.uk/package.json, editor.planx.uk/pnpm-lock.yaml, editor.planx.uk/src/pages/FlowEditor/components/Settings/ServiceSettings/FlowDescription/FlowDescription.tsx, editor.planx.uk/src/pages/FlowEditor/components/Settings/ServiceSettings/FlowStatus/index.tsx, editor.planx.uk/src/pages/FlowEditor/components/Settings/ServiceSettings/FooterLinksAndLegalDisclaimer.tsx, editor.planx.uk/src/pages/FlowEditor/components/Settings/ServiceSettings/index.tsx, editor.planx.uk/src/pages/FlowEditor/lib/store/settings.ts, editor.planx.uk/src/pages/FlowEditor/utils.ts, editor.planx.uk/src/routes/serviceSettings.tsx
This PR introduces a new section in the **Service Settings** page of the Editor. This houses the flow `description` which was added to the `flows` table in a previous PR: https://github.com/theopensystemslab/planx-new/pull/3945
I have created relevant mutations and updated current queries to update, create, and select `description` in `planx-core` in this PR: https://github.com/theopensystemslab/planx-core/pull/564
This new section has been added to the bottom of the **Service Settings** page as not to disrupt the UI too much, although it may be worth reviewing how these things are structured, but I imagined this is most aligned with the "Rethinking the Editor" work rather than this wee PR. 
I've called the setting section "Service Information" in case we want to put anything else in …
=> feat: add a flow description settings section

editor.planx.uk/src/airbrake.ts, editor.planx.uk/src/routes/utils.ts
The council has confirmed that the CNAME record for https://planningservices.lbbd.gov.uk/ has been created.
As per https://github.com/theopensystemslab/planx-new/blob/main/doc/how-to/how-to-setup-custom-subdomains.md :
=> chore: finalise Barking and Dagenham subdomain setup

api.planx.uk/modules/webhooks/service/analyzeSessions/operations.ts, editor.planx.uk/src/@planx/components/Feedback/Public/Public.tsx, editor.planx.uk/src/@planx/components/Feedback/Public/tests/Public.submit.test.tsx, editor.planx.uk/src/pages/FlowEditor/lib/analytics/provider.tsx, hasura.planx.uk/migrations/1731498724636_run_sql_migration/down.sql, hasura.planx.uk/migrations/1731498724636_run_sql_migration/up.sql
- Add `_feedback` to allow_lists
- Update `submission_services_summary` and `analytics_summary` views to include `feedback_score`.
- fix: access previously submitted answers when the user presses back
Verified that feedback_score is an `int` and displaying in `analytics_summary` ✅ 
🎟️ Trello ticket: https://trello.com/c/jEOLoubW/3034-can-we-introduce-in-house-end-of-service-feedback
=> feat: feedback analytics and previously submitted answers

editor.planx.uk/src/@planx/components/PlanningConstraints/Presentational.tsx, editor.planx.uk/src/@planx/components/PlanningConstraints/Public.test.tsx, editor.planx.uk/src/@planx/components/shared/Disclaimer.tsx
As discussed in [this slack thread](https://opensystemslab.slack.com/archives/C01E3AC0C03/p1732029167504329), the disclaimer component got slightly broken in [my refactor ](https://github.com/theopensystemslab/planx-new/pull/3900). Namely, I extracted out the `Disclaimer` component from `Planning Constraints` but accidentally removed the fallback string. 🤦 
This has been re-added as an optional prop `defaultText` in the shared `Disclaimer` component.
=> fix: add default disclaimer text to shared component

editor.planx.uk/src/@planx/components/Pay/Editor.tsx, editor.planx.uk/src/@planx/components/Pay/Public/InviteToPayForm.tsx, editor.planx.uk/src/@planx/components/Pay/Public/Pay.test.tsx, editor.planx.uk/src/@planx/components/Pay/Public/Pay.tsx, editor.planx.uk/src/@planx/components/PlanningConstraints/Public.test.tsx, editor.planx.uk/src/@planx/components/PlanningConstraints/Public.tsx, editor.planx.uk/src/@planx/components/Send/Public.test.tsx, editor.planx.uk/src/@planx/components/Send/Public.tsx
Adding some failure screens with Send Components and Planning Constraints to gracefully catch errors and inform the `demoUsers` of certain restrictions in the Public interface, rather than the Editor one. Found this better as it would still show our range of components (things like Planning Constraints) while removing a potentially confusing experience for users.
For demoUsers, they may still see these components normally when in other teams, like ODP, but they just can't see them when they are within the Demo team.
This is because for the Public interface of the components, we don't have access to a User object which would help us manage it specifically for a `demoUser` role which sits within the `teams` section of a `user` object, as it is applied to the `team_members` table.
Feedback …
=> feat: demo team integrations to fail gracefully

doc/how-to/how-to-setup-custom-subdomains.md, editor.planx.uk/src/lib/featureFlags.ts, editor.planx.uk/src/pages/FlowEditor/components/Flow/FeedbackLog/components/CollapsibleRow.tsx, editor.planx.uk/src/pages/FlowEditor/components/forms/FormModal.tsx
- Remove `FEEDBACK_COMPONENT` feature flag
- Add note to custom subdomains doc about UptimeRobot access.
- From feedback on pizza: change name of column in Feedback log to `User satisfaction` 🍕 
- Fix the ratings not showing by replacing the enum with a regular object `EmojiRating` 🐛
=> chore: remove feature flag for feedback component

doc/how-to/how-to-add-a-send-destination.md
This is something I've been keeping track of whilst adding the GOSS integration, finally typed up my rough notes.
There's a lot of stuff here! Certainly a lot of room for improvement and simplification I think in this process, and it's what's inspired the questions raised in https://github.com/theopensystemslab/planx-new/pull/3961
Ideally, we'd end up distilling this down to - 
- Custom validation in Editor (who can submit where - maybe driven by `team_integrations` table though?)
- Custom authentication logic with integration
- Custom payload generation for integration
- Custom response handling with integration
I think the rest can largely be made generic and standard between send destinations.
As I keep working on GOSS using the existing setup, I'll dip in and out of the doc to update …
=> docs: How to add a send destination

editor.planx.uk/src/@planx/components/ExternalPortal/Editor.test.tsx, editor.planx.uk/src/@planx/components/ExternalPortal/Editor.tsx, editor.planx.uk/src/@planx/components/InternalPortal/Editor.test.tsx, editor.planx.uk/src/@planx/components/InternalPortal/Editor.tsx, editor.planx.uk/src/pages/FlowEditor/components/Flow/components/Portal.tsx, editor.planx.uk/src/ui/editor/ModalSectionContent.tsx
Following previous templates groundwork, this PR adds the ability to add tags to portals
=> feat: add tags to portals

doc/architecture/decisions/0009-single-application-audit-table.md
Something to talk about at the next dev call - thought sooner would be most welcome though. 
Ideally, I'd like to forgo creating and migrating a `goss_applications` table unnecessarily - it would be nice to start working on this soon if there's no real issues and we agree it's worth doing this right now.
=> adr: Single `applications` table

editor.planx.uk/src/@planx/components/Checklist/Editor.tsx, editor.planx.uk/src/pages/FlowEditor/components/Flow/components/Tag.tsx, editor.planx.uk/src/ui/editor/ComponentTagSelect.test.tsx, editor.planx.uk/src/ui/editor/ComponentTagSelect.tsx
This PR adds a role access constraint to the `Placeholder` tag so only `PlatformAdmins` can edit it, but everyone can see it. 
To do this, I have restricted the `renderOption` function so it only shows `Placeholder` tag in the MultiSelect for `PlatformAdmin` users. I have also added the constraint to the `renderTags` function, so it removes the `onDelete` from the `Chip` component when a user is not a `PlatformAdmin`
With the changes to `TAG_DISPLAY_VALUES` we can now use `Role` types to add further permission layers in future if required. To ensure this happens, new logic would need to be introduced to the `canEdit()` in `ComponentTagSelect()`
=> feat: remove `onDelete` for Placeholder tag for non Platform admiins

editor.planx.uk/src/pages/FlowEditor/components/Flow/components/EndPoint.tsx
I had something to this effect in place on a previous PR, but seem to have lost it in a merge/rebase somewhere.
Currently (on staging), the start node scrolls to the center top on each load - it should only happen on initial load.
**Staging - incorrect behaviour**
_Scroll position reset on each route change_
https://github.com/user-attachments/assets/6b348956-f378-4b98-9187-dc92d47ac33a
**This PR - correct behaviour**
_Scroll position retained_
https://github.com/user-attachments/assets/cf789540-187f-469b-a3b1-1ceb121b3e56
=> fix: Only scroll to start node on initial load of flow

editor.planx.uk/public/robots.txt, editor.planx.uk/src/routes/draft.tsx, editor.planx.uk/src/routes/preview.tsx
- Excludes `/draft` and `/preview` routes from search-engine indexing
- These routes should be accessible (e.g. for internal council testing) but not discoverable by members of the public - they will likely have a bad experience on these routes! (not able to submit, incomplete content, testing content etc)
- Other routes either require authentication, or should be publicly accessible
I accidentally entered `https://editor.planx.uk/buckinghamshire/notification-of-commencement/` into a Google search instead of the URL bar and landed [here](https://www.google.com/search?q=https%3A%2F%2Feditor.planx.uk%2Fbuckinghamshire%2Fnotification-of-commencement%2F&sca_esv=dfd2af4a0faad991&rlz=1C5CHFA_enGB981GB982&ei=Pl0-Z5WXIp2N9u8PvruosQs&ved=0ahUKEwiVrq_S9euJAxWdhv0HHb4dKrYQ4dUDCA8&uact=5&oq=https%3A%2 …
=> chore: Remove `/draft` and `/preview` routes from indexing

editor.planx.uk/src/@planx/components/Pay/Editor/Editor.tsx, editor.planx.uk/src/@planx/components/Pay/Public/Confirm.tsx, editor.planx.uk/src/@planx/components/Pay/Public/InviteToPayForm.tsx, editor.planx.uk/src/@planx/components/Pay/Public/Pay.tsx, editor.planx.uk/src/@planx/components/Pay/model.ts
Follow up to https://github.com/theopensystemslab/planx-new/pull/3987#discussion_r1850331418
This PR moves the default values to their own function in `model.ts`.
=> chore: Move Pay default values to model

doc/how-to/how-to-add-a-secret.md
Prompted by https://github.com/theopensystemslab/planx-new/pull/3992 and a discussion earlier today. It's not the easiest setup to explain or understand, hopefully diagrams help a little.
=> docs: Add mermaid diagrams explaining `.env` file setup

hasura.planx.uk/metadata/tables.yaml, hasura.planx.uk/migrations/1732184010002_applicant_research_opt_in_view/down.sql, hasura.planx.uk/migrations/1732184010002_applicant_research_opt_in_view/up.sql
This PR should make generating these reports much easier - just hit the export button in Hasura prod!
=> chore: Save applicant research opt in query as view

e2e/tests/ui-driven/package.json, e2e/tests/ui-driven/pnpm-lock.yaml
Couldn't get Playwright working on my local env so after some debugging, I have bumped the Playwright version and everything is now working.
Couldn't find anything going wrong in the code or anything of note in the release notes
=> chore: playwright bump to 1.49.0

editor.planx.uk/src/components/EditorNavMenu.test.tsx, editor.planx.uk/src/components/EditorNavMenu.tsx, editor.planx.uk/src/pages/FlowEditor/lib/store/user.ts
Please see https://opensystemslab.slack.com/archives/C01E3AC0C03/p1732200694468619 (OSL Slack)
=> fix: Restore `EditorNavMenu` for platformAdmins

editor.planx.uk/src/@planx/components/Send/Public.test.tsx
This test has been failing on a number of CI runs, and then usually passes on a retry.
I'm not able to recreate this locally, so I'm adding in a retry to see if this mitigates the issue.
Once this is up and running, I'll retry the react tests a bunch of time on CI to check that a single retry actually seems to resolve this.
Update: Ran this multiple times, no issues so far 🤞
=> test: Add retry to flaky react unit test

editor.planx.uk/src/@planx/components/PlanningConstraints/Public.test.tsx
Spotted a rogue jest mock - this has now been handled correctly in vitest.
=> chore: Replace jest mock with vitest mock

editor.planx.uk/src/pages/FlowEditor/components/Flow/components/Portal.tsx
Please see https://opensystemslab.slack.com/archives/C01E3AC0C03/p1732286143726329 (OSL Slack)
Fixed small visual regressions introduced in https://github.com/theopensystemslab/planx-new/pull/3975, and adds back missing `ref`s.
=> fix: External Portal node graph styling

editor.planx.uk/src/@planx/components/Pay/Editor/Editor.tsx, editor.planx.uk/src/@planx/components/Pay/Editor/FeeBreakdownSection.tsx, editor.planx.uk/src/@planx/components/Pay/Editor/InviteToPaySection.tsx, editor.planx.uk/src/@planx/components/Pay/Public/Confirm.tsx, editor.planx.uk/src/@planx/components/Pay/Public/FeeBreakdown.test.tsx, editor.planx.uk/src/@planx/components/Pay/Public/FeeBreakdown.tsx, editor.planx.uk/src/@planx/components/Pay/Public/Pay.stories.tsx, editor.planx.uk/src/@planx/components/Pay/Public/Pay.test.tsx, editor.planx.uk/src/@planx/components/Pay/Public/Pay.tsx, editor.planx.uk/src/@planx/components/Pay/model.ts, editor.planx.uk/src/lib/featureFlags.ts
- Adds a `FEE_BREAKDOWN` feature flag
- Allows fee breakdown to be toggled in the Editor
- Displays a very basic fee breakdown table in the Public "Pay" component
- This is _just_ UI initially - there's no data here at all, these are just dummy values and not read from the passport
- I've got a few ideas of how this could work, but having a UI first will help hang a few discussions around this - planning to have some ideas to talk through and maybe demo at dev calls this week
- Storybook link here - https://storybook.4006.planx.pizza/?path=/story/planx-components-pay--with-fee-breakdown
=> feat: Initial fee breakdown public UI

doc/how-to/how-to-add-fields-to-search.md, editor.planx.uk/docs/adding-a-new-component.md
=> docs: How to add fields to search

api.planx.uk/modules/flows/validate/helpers.ts, api.planx.uk/modules/flows/validate/validate.test.ts
Invite to pay validation is only checking for the presence of a checklist, not a checklist with `proposal.projectType` set.
This means than an invalid flow can be configured, for which payment requests cannot be sent. I hit this when working on a follow up to https://github.com/theopensystemslab/planx-new/pull/4010, see demo below.
**`main` - incorrect behaviour**
https://github.com/user-attachments/assets/7b5e8914-6b76-495e-ac27-641222699103
The logic within `hasComponentType()` does not actually update the `nodeIds` array - it just maps and filters without reference to the source. As a result the `fn` check never actually happens, allowing any `Checklist` to pass the test.
**Pizza - correct behaviour**
Flow: https://4014.planx.pizza/testing/test-itp-validation …
=> fix: Ensure `hasComponentType` checks `fn` value

editor.planx.uk/src/pages/FlowEditor/components/Flow/components/Question.tsx, editor.planx.uk/src/pages/FlowEditor/floweditor.scss
Updates structure of graph nodes so that is the `isClone` class always targets all children within a single `div` element.
| <img width="789" alt="image" src="https://github.com/user-attachments/assets/e6c0b925-4655-46c3-99e8-cc9cdfe5e414"> | <img width="781" alt="image" src="https://github.com/user-attachments/assets/f202ca95-139f-4068-b92d-bf1fb38ccbcb"> | 
| Border not applied to sibling data tag, 3px gap | Border applied to single parent div, 3px gap is correctly offsetting hanger above |
=> fix: Clone styling for Questions with data variables or tags

editor.planx.uk/src/pages/FlowEditor/components/Flow/components/Checklist.tsx, editor.planx.uk/src/pages/FlowEditor/components/Flow/components/Question.tsx, editor.planx.uk/src/pages/FlowEditor/components/FlowEditor/ToggleHelpTextButton.tsx, editor.planx.uk/src/pages/FlowEditor/index.tsx, editor.planx.uk/src/pages/FlowEditor/lib/store/editor.ts, editor.planx.uk/src/ui/editor/InternalNotes.tsx, editor.planx.uk/src/ui/editor/MoreInformation/MoreInformation.tsx
Adds a simple toggle & icon to indicate if a node has help text defined without having to open its' modal
=> feat: visually indicate if a node has help text in the graph

editor.planx.uk/src/pages/FlowEditor/components/Flow/components/Checklist.tsx, editor.planx.uk/src/pages/FlowEditor/components/Flow/components/Question.tsx
Quick fix following on from #4021 
This account for nodes which don't have the "More information" fields - currently hitting this here on staging https://editor.planx.dev/templates/apply-for-a-rights-of-way-order
=> fix: Handle nodes without more info fields

hasura.planx.uk/migrations/1733134891363_add_application_type_to_feedback_summary/down.sql, hasura.planx.uk/migrations/1733134891363_add_application_type_to_feedback_summary/up.sql
Adds a new Hasura migration to add `application.type` to `feedback_summary` view.
We tested it in a flow with find property, application type etc. and everything worked.
=> feat: adding application.type to feedback_summary hasura migration

editor.planx.uk/src/@planx/components/Confirmation/Public.test.tsx, editor.planx.uk/src/@planx/components/Confirmation/Public.tsx, editor.planx.uk/src/@planx/components/shared/Preview/Card.test.tsx, editor.planx.uk/src/@planx/components/shared/Preview/Card.tsx, editor.planx.uk/src/pages/FlowEditor/lib/store/preview.ts, editor.planx.uk/src/pages/Preview/Node.tsx
Per request here: https://opensystemslab.slack.com/archives/C01E3AC0C03/p1733157241528129
**Changes:**
- The Confirmation component now determines if it is the final node in the flow
- If it is the final node, it will not display a "Continue" button
- If it is _not_ the final node, it **will** display a "Continue" button and leave a basic breadcrumb
- In either scenario, the Confirmation component still _never_ displays a "back" button - which I think is correct/intended behavior as we would not allow someone to change answers post-Confirmation
- Hides the "Save and return..." link beneath "Continue" if there's a Send component present in our breadcrumbs
**Todo:** 
- :white_check_mark: Add some tests (honestly a little unsettling that this hasn't broken any :sweat_smile:)
**Testing …
=> feat: conditionally show/hide "Continue" button on Confirmation using `isFinalCard`

editor.planx.uk/src/pages/FlowEditor/lib/store/preview.ts
Flagged by Airbrake here: https://opensystemslab.slack.com/archives/C4B0CKQ3U/p1733161837391839
=> fix: `TypeError: Cannot read properties of undefined (reading 'data')` in `autoAnswerableFlag`

editor.planx.uk/src/@planx/components/NextSteps/Editor.tsx
Found that when you deleted a step from the NextSteps component, it wouldn't set `description` or `url` to "", but not set it at all. This meant previous values with the same index would persist until it is submitted then when it is reloaded, data would return to the formik saved values. 
Looked into trying to alter the data model, but got a bit caught up in the components and functions with the way they are passed down and back up. Open to suggestions on a more robust change, but this seemed to work.
=> fix: when next step is deleted, props.value doesn't update

editor.planx.uk/src/pages/FlowEditor/components/Sidebar/Publish/PublishFlowButton.tsx
I've noticed that loading flows in the editor feels particularly sluggish lately and leads to more errors in the Preview side panel than usual (and therefore Airbrake too) - eg `Error: id "eMxQAgygE6" not found`, `TypeError: Cannot read properties of undefined (reading 'data')` and so on.
This PR proposes removing the "badge" on the publish button which displays how many altered nodes are currently un-published. This badge requires calling `validateAndDiff` on initial flow load which is fairly expensive and regularly timesout (therefore badge fails to display at all).
Feels like it's an easy win to remove this feature for now (doubt it'll be noticed or missed), _only_ call `validateAndDiff` when the "Check for cahnges to publish" modal is actually opened and _not_ on first flow load as …
=> fix: remove `alteredNodes` badge on publish button and `validateAndDiff` request on first flow load

editor.planx.uk/src/pages/FlowEditor/floweditor.scss
Fixes issue raised here (OSL Slack) - https://opensystemslab.slack.com/archives/C04DZ1NBUMR/p1733216868074849
Regression introduced here when an additional wrapping `Box` (HTML `div`) was added to the graph node - https://github.com/theopensystemslab/planx-new/pull/4017
=> fix: Reapply SetValue graph CSS

editor.planx.uk/src/@planx/components/Pay/Editor/Editor.tsx, editor.planx.uk/src/@planx/components/Pay/Editor/FeeBreakdownSection.tsx, editor.planx.uk/src/@planx/components/Pay/Public/FeeBreakdown/FeeBreakdown.tsx, editor.planx.uk/src/@planx/components/Pay/Public/FeeBreakdown/types.ts, editor.planx.uk/src/@planx/components/Pay/Public/FeeBreakdown/useFeeBreakdown.test.ts, editor.planx.uk/src/@planx/components/Pay/Public/FeeBreakdown/useFeeBreakdown.tsx, editor.planx.uk/src/@planx/components/Pay/Public/FeeBreakdown/utils.test.ts, editor.planx.uk/src/@planx/components/Pay/Public/FeeBreakdown/utils.ts
- Parses user's Passport for discrete list of reductions and exemptions 
- Displays these as a list to the user (currently just using raw passport vars, will map these to schema `@descriptions` fields)
- Prior art #4022 
- This initial approach allowed any reduction or exemption to be captures, this current PR is stricter when it comes to these values
=> feat(fee-breakdown): Parse and display discrete list of reductions and exemptions

editor.planx.uk/src/@planx/components/Checklist/Editor/Editor.tsx
Flagged here https://opensystemslab.slack.com/archives/C01E3AC0C03/p1733408598813289
We don't currently have an `Editor.test.tsx` file for Checklists but happy to revisit that as a follow-up PR so we don't miss this again ! Probably nice to merge now though to minimise rebases for Jo :slightly_smiling_face:
=> fix: account for expandable checklists in editor modal passport value validation

api.planx.uk/modules/file/service/uploadFile.ts
Thread with lots of context here: https://opensystemslab.slack.com/archives/C01E3AC0C03/p1733474436178079
We removed these `||` when recently upgrading to AWS-SDK v3 (#3989), but they're required for our current handling of the application JSON written to S3 for use in the Power Automate integrations (see this old comment https://github.com/theopensystemslab/planx-new/pull/3003/files#r1560594873)
=> fix: ensure empty JSON files aren't written to S3

infrastructure/application/services/hasura.ts
Related to [this ticket](https://trello.com/c/oRzedbmJ).
This PR introduces a 180s grace period for the Hasura service in an attempt to deal with a boot loop during scale up.
During load testing, even with relatively small numbers of users we immediately hit issues with Hasura.
When the service tries to scale up with a 2nd Task to deal with the load, the new task fails to boot to a healthy state (which the load balancer checks for before directing traffic to it), and AWS then has to deprovision them (usually within 2 minutes or so of boot).
The issue seems to be with the `Hasura` container itself, since the `HasuraProxy` container reports the following in the logs for one of these failed task:
```json
{"level":"error","ts":1733444599.5636377,"logger":"http.log.error","msg":"dial tcp …
```
=> extend Hasura service boot grace period from 0 to 180s

api.planx.uk/modules/webhooks/service/sendNotification/index.ts
Quick followup from this thread yesterday: https://opensystemslab.slack.com/archives/C0405SQDP8B/p1733407486961749
Should now add the apparently-very-relied-on :large_orange_diamond: to all BOPS app type alerts coming through #planx-notifications during the pilot testing
=> fix: add missing BOPS app type suffixes to Slack notification pilot criteria

editor.planx.uk/src/ui/editor/RichTextInput/RichTextInput.tsx
Tightens editor link validation from any link text including ''click'' or ''here'' to links set solely over ''click here'' or ''clicking here''. Includes trimming of white space and punctuation.
=> fix: correct editor link validation

api.planx.uk/modules/file/service/uploadFile.ts, api.planx.uk/modules/file/service/utils.ts, api.planx.uk/modules/send/s3/index.ts
- Convert a `DigitalPlanningPayload` to an `Express.Multer.File` for upload
- Addresses issues discussed here - https://opensystemslab.slack.com/archives/C01E3AC0C03/p1733474436178079 (OSL Slack)
Trickier than expected! TypeScript isn't catching the mismatch between `DigitalPlanningPayload` and `Express.Multer.File` even when the type is imported and assigned. I think it's to do with the combination of the type complexity plus the `Awaited<>` utility type which has a depth limit I believe.
Next up is some tests here for the entire module (in another PR), will also check the Pizza to make this is working as expected once it's up.
=> fix: Convert Digital Planning payload to JSON file before upload

api.planx.uk/modules/file/service/uploadFile.ts, api.planx.uk/modules/send/s3/index.test.ts, api.planx.uk/modules/send/s3/index.ts, api.planx.uk/vitest.config.ts
=> test(api): Coverage for send/s3 module

editor.planx.uk/src/@planx/components/Pay/Editor/Editor.test.tsx, editor.planx.uk/src/@planx/components/Pay/Editor/Editor.tsx, editor.planx.uk/src/@planx/components/Pay/Public/Pay.fixture.tsx, editor.planx.uk/src/@planx/components/Pay/Public/Pay.test.tsx, editor.planx.uk/src/@planx/components/Pay/model.ts
Makes the `data.fn` value of the Pay component a hard-coded variable - `application.fee.payable`
This is relied upon when working out the fee breakdown, as well as in the payload mapping. All real services are using this value and this matches the pattern for other variable like addresses where we need a single static passport key.
=> feat(fee-breakdown): Make Pay component data field a static value

api.planx.uk/modules/gis/service/digitalLand.ts, api.planx.uk/modules/gis/service/index.js
Niche edge case spotted by Jenna while testing constraints here (eg _not_ checking general `article4` but still selecting `article4.caz` :cyclone:): https://opendigitalplanning.slack.com/archives/CQWPPHQ2X/p1733911237161229?thread_ts=1733763841.300959&cid=CQWPPHQ2X
Example request before: https://api.editor.planx.dev/gis/doncaster?geom=MULTIPOLYGON+%28%28%28-1.116085+53.526454%2C+-1.115971+53.52638%2C+-1.115557+53.526611%2C+-1.115625+53.526654%2C+-1.115823+53.526545%2C+-1.115871+53.526576%2C+-1.116085+53.526454%29%29%29&vals=article4.caz%2CbrownfieldSite%2Cdesignated.AONB%2Cdesignated.conservationArea%2CgreenBelt%2Cdesignated.nationalPark%2Cdesignated.nationalPark.broads%2Cdesignated.WHS%2Cflood%2Clisted%2Cmonument%2Cnature.ASNW%2Cnature.ramsarSite%2Cnature.SAC%2Cnature.SPA%2Cnature.SSSI%2 …
=> fix: account for un-checked Article 4 values in GIS API

api.planx.uk/modules/pay/service/inviteToPay/createPaymentSendEvents.ts, api.planx.uk/modules/send/createSendEvents/controller.ts
Context here: https://opensystemslab.slack.com/archives/C01E3AC0C03/p1733920337623209
Future refactor candidate, but quick fix for now !
=> fix: ensure Invite to Pay creates submission events for S3/Power Automate

infrastructure/application/index.ts
We recently hit the following error on a recent staging deploy - 
> `error: denied: The repository with name {NAME} in registry with id {ID} already has the maximum allowed number of images which is ‘10000’`
I manually removed the oldest images from ECR > Private registry > Repository > Repository ID via the AWS console (staging).
After I did this, I re-ran our CI process which succeeded ✅ 
This PR configures an ECR Lifecycle Policy (AWS docs: https://docs.aws.amazon.com/AmazonECR/latest/userguide/LifecyclePolicies.html) via Pulumi. This should be applied automatically on the next staging deploy (I'll verify via the console when this has ran).
=> chore(iac): Configure lifecycle policy for AWS ECR

.gitignore, infrastructure/application/services/hasura.ts
Related to [this ticket](https://trello.com/c/oRzedbmJ).
Neither of the interventions in #4051 or #4076 resolved the Hasura boot loop issue on scale up.
This PR takes a different tack, based on a closer reading of the logs for the instances which are failing to boot (all of which follow a similar pattern). Essentially it allows the Hasura server 5 minutes to pull metadata and handle migrations from the RDS-hosted PostgreSQL database.
(includes bits for gitignore to ease my workflow with python)
See also #4081.
After a closer look at the logs ([example](https://eu-west-2.console.aws.amazon.com/cloudwatch/home?region=eu-west-2#logsV2:log-groups/log-group/hasura20230630103945001200000001/log-events/hasura%2Fhasura%2F15010cf0ad98493eb21ed11d2fbd4773)), I realised that the key might be in the …
=> extend timeout for Hasura migrations at boot

infrastructure/data/index.ts
Related to [this ticket](https://trello.com/c/oRzedbmJ).
This PR bumps the RDS PostgreSQL DB instance used on staging to `db.t3.small`, in order to increase the number of connections it can handle by doubling the memory (to 2GB).
Prod is still pinned to `db.t3.medium`, which has twice the memory again (4GB).
We only need to merge this if #4080 doesn't solve the scaling issue - also see that PR for further context and motivation for this change.
Also note that we'll have to manually roll out the upgrade on AWS via Pulumi CLI, since there is no CI setup for the `data` layer as there is for `application` (see the `push-main` workflow).
=> bump staging RDS instance to T3 Small

e2e/tests/ui-driven/src/create-flow-with-geospatial.spec.ts, e2e/tests/ui-driven/src/helpers/geospatialChecks.ts, e2e/tests/ui-driven/src/mocks/geospatialMocks.ts, e2e/tests/ui-driven/src/mocks/osMapsMockData.ts, e2e/tests/ui-driven/src/mocks/osMapsResponse.ts, editor.planx.uk/src/@planx/components/DrawBoundary/Public/index.tsx
For the Draw Boundary testing, I have focused only on:
-  the ability to add via the Editor modal
- path to navigate to the file upload route
- a map is present with correct geoJSON
- a map can be reset and new boundary drawn
I have left testing the file upload to the relevant unit tests or related testing elsewhere in the code base. I thought this was the easiest given we are yet to do the `FileUploadAndLabel` e2e tests. I can come back to add this in after that.
Rather than add in comments, in some parts I have just added custom text to the `expect()`. It made it easier for me to track when running the test and it was acting the same as the comments in the code. 
```js
await expect(drawBoundaryTitle, "We have navigated back to the map component",).toBeVisible();
```
=> feat: E2E coverage for Draw Boundary

editor.planx.uk/src/@planx/components/PropertyInformation/model.ts
Per data migration plan here https://docs.google.com/spreadsheets/d/1Vtxp5BLweDPDooQoNhgOCYjCIBPRYIcOuyArGJRqOkI/edit?gid=1778589811#gid=1778589811
This one can merge anytime & will mean _new_ PropertyInformation components have correct text, then we'll run script separately to update _existing_ components.
=> chore: update default description text for PropertyInformation

api.planx.uk/modules/analytics/metabase/collection/collection.test.ts, api.planx.uk/modules/analytics/metabase/collection/getTeamIdAndMetabaseId.ts, api.planx.uk/modules/analytics/metabase/collection/updateMetabaseId.ts, hasura.planx.uk/metadata/tables.yaml, hasura.planx.uk/migrations/1733738650997_alter_table_public_teams_add_column_metabase_id/down.sql, hasura.planx.uk/migrations/1733738650997_alter_table_public_teams_add_column_metabase_id/up.sql, hasura.planx.uk/tests/teams.test.js
- Migration to add `metabase_id` column to `teams` in PlanX DB
- Update Hasura permissions for `api` to be able to read and update relevant values
- A `getTeamIdAndMetabaseId` function
- An `updateMetabaseId ` function
- Tests for the above
- Daf suggested that a better pattern than querying Metabase every time we want to check if a collection exists would be to store a `metabase_id` in the PlanX DB and check that instead
- This is the PlanX DB portion of big PR #3971
=> feat: analytics module gets and updates PlanX DB

editor.planx.uk/src/pages/FlowEditor/components/Flow/FeedbackLog/components/CollapsibleRow.tsx
Quick one: fixes alignment of the feedback table dropdown, as another header row has been added.
**Before:**
**After:**
=> fix: Feedback table alignment

editor.planx.uk/src/@planx/components/ExternalPortal/Editor.test.tsx, editor.planx.uk/src/@planx/components/ExternalPortal/Editor.tsx, editor.planx.uk/src/@planx/components/InternalPortal/Editor.test.tsx, editor.planx.uk/src/@planx/components/InternalPortal/Editor.tsx
Quick one per https://opensystemslab.slack.com/archives/C07F7215W7P/p1734520406153639
=> chore: `showInternalNotes` in editor modals for portals

hasura.planx.uk/metadata/tables.yaml, hasura.planx.uk/migrations/1734623060683_create_table_public_temp_data_migrations_audit/down.sql, hasura.planx.uk/migrations/1734623060683_create_table_public_temp_data_migrations_audit/up.sql
Following on from data migration chat! This is a basic table structure that will help us both: queue up _which_ flows should be updated by a given data migration script and track which have been `updated` so far.
Exclusively the `platformAdmin` role can access and update this table.
I'm imagining: 
- We'll simply manually populate the table like so:
```psql
INSERT INTO temp_data_migrations_audit (flow_id, team_id)
SELECT id, team_id
FROM flows 
WHERE team_id IN (1,2,3); -- team_ids match councils that have "consented"
```
- Then kick off the migration script which will fetch/transform/update one flow/row at a time `where updated = false` until all records have been updated
- Finally after a successful migration, we can simply `TRUNCATE` the table and re-use the same structure for our next …
=> feat: add audit table for data migration scripts

editor.planx.uk/src/theme.ts
MUI responsive type sizes provides a one-value (`factor: x`) scale for resizing type which aims to provide a global function, but removes the ability to scale or fine-tune by a particular type property.
In PlanX we use h2 sizes for most page/question titles and h1 for headline/banners, MUI was resizing these to be too small comparatively to be effective.
I've tried a number of methods to work with MUI's automatic scale, ideally we'd use an up-to-date method (such as `fontSize: "clamp(2.125rem, 3rem, 5rem)",`, but MUI needs to see a hardcoded value for each property.
This PR introduces manual media queries to increase larger header sizes at the smallest (sub 500px wide) screens. There is also the reluctant use of an `!important` rule as MUI trumps any media queries defined in the theme …
=> fix: Responsive type sizes

editor.planx.uk/src/@planx/components/Confirmation/Confirmation.stories.tsx, editor.planx.uk/src/@planx/components/Confirmation/Editor.tsx, editor.planx.uk/src/pages/Pay/InviteToPay.tsx
Removes references to certificates from default More Information copy of confirmation and invite to pay page.
Updates default Contact Us copy of confirmation page to new feedback nudge and replaces Lambeth email with placeholder copy requesting the addition of contact details.
=> chore: fix confirmation and invite to pay page default copy

infrastructure/application/Pulumi.production.yaml, infrastructure/application/Pulumi.staging.yaml, infrastructure/application/services/hasura.ts
Relates to [this ticket](https://trello.com/c/oRzedbmJ).
This PR follows hot on the heels of #4080 and #4081, neither of which resolved the issue with Hasura (although I think the latter was necessary because the number of connections the AWS RDS database could handle was a limiting factor).
It implements the following:
- health checks for both the `hasura` and `hasuraProxy` containers, with values based on the docker setup
- new env variables to give a long timeout for a new Hasura server to load metadata and run migrations at boot, ensure said migrations run sequentially (not concurrently) to minimise chance of overloading CPU, and show debug level logs to easily diagnose whatever's going on
- according grace periods / timeouts throughout
- doubles CPU only (to 1GiB) for the hasura …
=> [infrastructure] add explicit autoscaling logic to Hasura service

hasura.planx.uk/metadata/tables.yaml, hasura.planx.uk/migrations/1734705022933_alter_table_public_temp_data_migrations_audit_add_column_logs/down.sql, hasura.planx.uk/migrations/1734705022933_alter_table_public_temp_data_migrations_audit_add_column_logs/up.sql
A couple quick database migrations per our discussion !
=> fix: add `logs` column to `temp_data_migrations_audit` table and create relationship from `flow` to `lowcal_sessions`

e2e/tests/api-driven/src/invite-to-pay/helpers.ts
Should fix `ReferenceError: __dirname is not defined` thrown by nightly regression tests here https://github.com/theopensystemslab/planx-new/commit/2984d2a8708a6daaa63b23d5530a5b978a4ff00f/checks
Regression tests passing against this branch here :heavy_check_mark: https://github.com/theopensystemslab/planx-new/actions/runs/12646931097
=> fix: use ESM-compatible `__dirname` reference in e2e/tests/api-driven

editor.planx.uk/src/@planx/components/Result/Public/index.tsx, editor.planx.uk/src/@planx/components/shared/BaseOptionsEditor.tsx, editor.planx.uk/src/@planx/components/shared/index.ts, editor.planx.uk/src/pages/FlowEditor/components/Flow/components/Option.tsx, editor.planx.uk/src/pages/FlowEditor/lib/__tests__/filters.test.ts, editor.planx.uk/src/pages/FlowEditor/lib/__tests__/preview/collectedFlags.test.ts, editor.planx.uk/src/pages/FlowEditor/lib/__tests__/preview/removeNodesDependentOnPassport.test.ts, editor.planx.uk/src/pages/FlowEditor/lib/__tests__/preview/removeOrphansFromBreadcrumbs.test.ts, editor.planx.uk/src/pages/FlowEditor/lib/__tests__/preview/resultData.test.ts, editor.planx.uk/src/pages/FlowEditor/lib/store/preview.ts
Per data migration script here https://docs.google.com/spreadsheets/d/1Vtxp5BLweDPDooQoNhgOCYjCIBPRYIcOuyArGJRqOkI/edit?gid=0#gid=0
Relies on planx-core PR: https://github.com/theopensystemslab/planx-core/pull/611
=> migrate: find+replace Option/Answer `flag` prop to `flags` and ensure always `string[]` type

editor.planx.uk/src/@planx/components/DrawBoundary/Public/index.tsx, editor.planx.uk/src/@planx/components/DrawBoundary/model.ts
Per data migraiton feedback here: https://opensystemslab.slack.com/archives/C01E3AC0C03/p1736347450892489?thread_ts=1736239726.670049&cid=C01E3AC0C03
When navigating "back" to a DrawBoundary it was incorrectly displaying this:
=> fix: ensure area is correctly displayed when navigating back to DrawBoundary

api.planx.uk/package.json, api.planx.uk/pnpm-lock.yaml, e2e/tests/api-driven/package.json, e2e/tests/api-driven/pnpm-lock.yaml, e2e/tests/ui-driven/package.json, e2e/tests/ui-driven/pnpm-lock.yaml
See https://github.com/theopensystemslab/planx-core/pull/614
**Testing notes:**
- I've copied an "old" session from Bucks RAB production into this pizza database to confirm that the overview document maps display correctly
- Login to the pizza editor to generate an auth token then open this admin endpoint in your browser: https://api.4121.planx.pizza/admin/session/12c48901-178d-445d-a550-783a36ba4bc1/html
- Confirm that you have the subtext "The user accepted the title boundary" and a grey code block "boundary" populated
- There's CORS errors in the console related the the OS maps display that are consistent with production that we can fix forward later (this seems to be specific to the admin endpoint and local downloads are fine)
- But the presence of the subtext & "boundary" block are …
=> chore: bump planx-core

editor.planx.uk/package.json, editor.planx.uk/pnpm-lock.yaml
Bumped planx-core in line with the API and E2E here:
https://github.com/theopensystemslab/planx-new/pull/4121
=> chore: bump planx-core in Editor

editor.planx.uk/src/pages/FlowEditor/components/FlowEditor/ToggleDataFieldsButton.tsx, editor.planx.uk/src/pages/FlowEditor/components/FlowEditor/ToggleHelpTextButton.tsx, editor.planx.uk/src/pages/FlowEditor/components/FlowEditor/ToggleImagesButton.tsx, editor.planx.uk/src/pages/FlowEditor/components/FlowEditor/ToggleTagsButton.tsx, editor.planx.uk/src/ui/editor/ToggleIconButton.tsx, editor.planx.uk/src/ui/icons/ToggleOverlay.tsx
- Simplifies toggle button setup so that styles are defined once in a shared component `ToggleIconButton.tsx`
- Adds a custom "strikethrough" icon overlay to remove reliance on active/inactive icon pairings when using toggle buttons
**Test:**
https://4115.planx.pizza/barnet/find-out-if-you-need-planning-permission
**After change (small visual difference):**
=> refactor: Universal toggle button

editor.planx.uk/src/ui/editor/ToggleIconButton.tsx
- Corrects visual order of editor graph toggle buttons
- Adds `aria-pressed` attribute to ensure correct state is visible in the DOM
=> fix: Toggle button visual order

infrastructure/application/index.ts, infrastructure/application/services/hasura.ts
Currently, we're returning an `Output<string>` instead of a `string` type - this should resolve it!
=> fix: Pulumi output syntax

api.planx.uk/modules/send/email/index.ts
See #help-issues thread from Tewkesbury here: https://opendigitalplanning.slack.com/archives/C0241GWFG4B/p1736501911947289
**Here's what's happening:**
- :heavy_check_mark: Our submissions log button downloads as expected
- :heavy_check_mark: The magic link saved in our `email_applications` audit table downloads as expected
- :x: The magic link when clicked directly from the body of a Gov Notify email does _not_ download as expected and instead throws error: `error: "Missing values required to access application files"` (email forwarded to `devops@`)
- It appears Gov Notify has automatically wrapped the link (eg `https://linkprotect.cudasvc.com/url?a={our encoded URL}` which fails to properly decode the second query param in the request
- Eg see `amp;localAuthority` when inspecting the …
=> fix: explicitly use URLSearchParams when constructing send to email magic links

scripts/seed-database/container.sh, scripts/seed-database/write/published_flows.sql
Working locally after additions to `container.sh`.
It took me a while to track why the script was not working, although the error was informative, so I added a comment to the `published_flows.sql` script.
=> feat: add `has_send_component` to seed scripts

editor.planx.uk/src/pages/FlowEditor/lib/store/preview.ts
This should address an error raised by Greg (via email).
I haven't actually worked out the underlying issue here yet (why there's a node without data) but I'm currently looking into this by working through the session's breadcrumbs.
=> fix: Add optional chaining to flag check

editor.planx.uk/src/@planx/components/Pay/Editor/GovPayMetadataSection.tsx, editor.planx.uk/src/@planx/components/Pay/Editor/helpers.ts, editor.planx.uk/src/@planx/components/Pay/model.test.ts, editor.planx.uk/src/@planx/components/Pay/model.ts
- Update `maxItems` to 15 in `GovPayMetadata`
- Update schema validation and associated tests
- Checked routes and `planx-core` to see if anything needs to be updated there - doesn't look like it to me.
- Minor refactor to move some helper functions to a separate file
=> chore: extend pay metadata

editor.planx.uk/src/@planx/graph/__tests__/remove.test.ts, editor.planx.uk/src/@planx/graph/index.ts
Per bug spot by August https://opensystemslab.slack.com/archives/C01E3AC0C03/p1736354419439469
When removing the last/final node in the graph currently, the flow data will be set to `{}` - which then on next render will display a blank screen & fail to load because of type errors:
```
index-vd9rjCRb.js:614 
TypeError: Cannot read properties of undefined (reading 'edges')
at Object.filterFlowByType (index-vd9rjCRb.js:1565:3082)
at Object.initNavigationStore (index-vd9rjCRb.js:1565:2543)
at Object.setFlow (index-vd9rjCRb.js:1610:741)
at n (index-vd9rjCRb.js:1500:92956)
at Object.connectTo (index-vd9rjCRb.js:1500:93024)
at async team-BRe-K93g.js:107:189
```
This change ensures that removing the last node still preserves the original `{ "_root": { edges: [] } }` flow structure to prevent type …
=> fix: never fully remove `_root` node via graph operations

editor.planx.uk/src/@planx/components/Checklist/Editor/Editor.tsx, editor.planx.uk/src/@planx/components/Question/Editor.tsx, editor.planx.uk/src/@planx/components/shared/BaseOptionsEditor.tsx
Per August's feedback here: https://opensystemslab.slack.com/archives/C01E3AC0C03/p1736435506266819
Fixes a small visual regression from introducing the `DataFieldAutocomplete`. The data field validation was still running and preventing invalid nodes from being created, but failing to visually display an error message. Now added back:
=> fix: display `fn` validation errors in Question and Checklist editor modals

infrastructure/application/Pulumi.production.yaml, infrastructure/application/Pulumi.staging.yaml, infrastructure/application/services/hasura.ts
Relevant Trello ticket: https://trello.com/c/oRzedbmJ
After gaining confidence that the Hasura setup currently on staging can handle the load tests published in #4160, this PR is just intended to polish the infrastructure specifics, and round down some of the values which were extreme for the purpose debugging.
See #4051, #4076, #4080 and #4096 for those initial changes.
I'll tag this up with a quick review to explain some of the decisions.
=> [hasura] finalise infrastructure config at sensible values

editor.planx.uk/src/@planx/components/List/Public/index.tsx, editor.planx.uk/src/@planx/components/List/utils.test.ts, editor.planx.uk/src/@planx/components/List/utils.tsx, editor.planx.uk/src/@planx/components/shared/Preview/SummaryList.tsx, editor.planx.uk/src/@planx/components/shared/Schema/InputFields/index.tsx, editor.planx.uk/src/@planx/components/shared/Schema/model.ts
- Correctly defines output values of a schema field, based on it's field type. This is the `ResponseValue<T>` type.
- Please see https://github.com/theopensystemslab/planx-new/pull/4153#discussion_r1919809762 for details on why this is the approach I've gone for
- Updates code that was relying on type casting, or type checking via disparate means, to use a standard set of type guards defined in the model file
- Overdue technical debt from the list/schema work
- A barrier for https://github.com/theopensystemslab/planx-new/pull/4020 which is introducing another field and response value. One this PR is merged I'll rebase the above branch to incorporate this and make the required type changes there.
=> feat(types): Stricter and more accurate Schema response types

infrastructure/application/Pulumi.production.yaml, infrastructure/application/Pulumi.staging.yaml, infrastructure/application/services/hasura.ts
Relevant Trello ticket: https://trello.com/c/oRzedbmJ
Refinements to #4161 after further testing - see that PR / [this doc](https://www.notion.so/opensystemslab/Testing-Hasura-17d35d469ad18024a105f89a97c579c9?pvs=4#a6687e8b6e7e46a5985f3d5d9d33aaf3) for discussion.
=> [hasura] further fine tuning of scaling and health check config

api.planx.uk/modules/flows/publish/publish.test.ts, api.planx.uk/package.json, api.planx.uk/pnpm-lock.yaml, api.planx.uk/tests/mocks/validateAndPublishMocks.ts, e2e/tests/api-driven/package.json, e2e/tests/api-driven/pnpm-lock.yaml, e2e/tests/ui-driven/package.json, e2e/tests/ui-driven/pnpm-lock.yaml, editor.planx.uk/package.json, editor.planx.uk/pnpm-lock.yaml, editor.planx.uk/src/@planx/components/Filter/Editor.test.tsx, editor.planx.uk/src/@planx/components/PlanningConstraints/List.tsx, editor.planx.uk/src/pages/FlowEditor/components/Sidebar/Search/SearchResultCard/allFacets.test.ts, editor.planx.uk/src/pages/FlowEditor/components/Sidebar/Search/mocks/allFacetFlow.ts, editor.planx.uk/src/pages/FlowEditor/lib/__tests__/filters.test.ts, editor.planx.uk/src/pages/FlowEditor/lib/__tests__/getFlowSchema.test.ts, editor.planx.uk/src/pages/FlowEditor/lib/__tests__/preview/collectedFlags.test.ts, editor.planx.uk/src/pages/FlowEditor/lib/__tests__/preview/removeNodesDependentOnPassport.test.ts, editor.planx.uk/src/pages/FlowEditor/lib/__tests__/preview/removeOrphansFromBreadcrumbs.test.ts, editor.planx.uk/src/pages/FlowEditor/lib/__tests__/preview/resultData.test.ts
- Bumps planx-core to latest `main` (includes ODP Schema v0.7.2 plus flag changes)
- Updates mock test data throughout to reflect new flag values
- Fixes forward lingering `article4` spotted here: https://github.com/theopensystemslab/planx-new/pull/4151#pullrequestreview-2562119952
=> chore: bump planx-core (ODP Schema v0.7.2)

editor.planx.uk/src/@planx/components/Checklist/Editor/Options.tsx, editor.planx.uk/src/@planx/components/Checklist/Editor/components/ExclusiveOrOptionManager.tsx, editor.planx.uk/src/@planx/components/Checklist/Editor/components/GroupedOptions.tsx, editor.planx.uk/src/@planx/components/Question/Editor.tsx
This is me trying to unpick and resolve the changes made in [https://github.com/theopensystemslab/planx-new/pulls whi](https://github.com/theopensystemslab/planx-new/pull/4171) which touch and fix a few things, but is failing E2E tests in a way I've not yet identified. I'm hoping that splitting up the fixes will help me narrow this down. Next up is the same issue for the `DataFieldAutocomplete`.
This PR intentionally does not try to address any issues with the `DataFieldAutocomplete`.
When using a the `ListManger` and re-ordering options, the associated tags are not correctly re-ordered and remain in their index position. This only happens on new, unsaved, list items. See demo below on staging - 
https://github.com/user-attachments/assets/4da620de-b0df-441a-8085-693802ed91de
I believe …
=> fix: Option label reordering in `ListManager`

editor.planx.uk/src/@planx/components/shared/DataFieldAutocomplete.tsx
This is me trying to unpick and resolve the changes made in [https://github.com/theopensystemslab/planx-new/pulls whi](https://github.com/theopensystemslab/planx-new/pull/4171) which touch and fix a few things, but is failing E2E tests in a way I've not yet identified. I'm hoping that splitting up the fixes will help me narrow this down.
When using the `DataFieldAutocomplete` field, values are only captured (the `handleChange()` function being called) only happens when I select a value with the mouse or hit enter. If I type and tab (or click) away, the input will display my value but Formik will not update - this leads to a number of issues.
The `autoSelect` prop controls this, so it's just a case of setting this to `true`. 
> **`autoSelect`**
>
> If `true`, the selected option becomes …
=> fix: Use `autoSelect` prop to capture blur events on `DataFieldAutocomplete`

editor.planx.uk/src/@planx/components/AddressInput/Editor.tsx, editor.planx.uk/src/@planx/components/Confirmation/Editor.tsx, editor.planx.uk/src/@planx/components/ContactInput/Editor.tsx, editor.planx.uk/src/@planx/components/DateInput/Editor.test.tsx, editor.planx.uk/src/@planx/components/DateInput/Editor.tsx, editor.planx.uk/src/@planx/components/FindProperty/Editor.tsx, editor.planx.uk/src/@planx/components/InternalPortal/Editor.tsx, editor.planx.uk/src/@planx/components/NextSteps/Editor.tsx, editor.planx.uk/src/@planx/components/Pay/Editor/Editor.test.tsx, editor.planx.uk/src/@planx/components/Pay/Editor/GovPayMetadataSection.tsx, editor.planx.uk/src/@planx/components/Pay/Editor/InviteToPaySection.tsx, editor.planx.uk/src/@planx/components/Result/Editor.tsx, editor.planx.uk/src/@planx/components/TaskList/Editor.tsx, editor.planx.uk/src/@planx/components/TaskList/TaskList.stories.tsx, editor.planx.uk/src/@planx/components/TextInput/Editor.tsx, editor.planx.uk/src/pages/FlowEditor/components/Settings/GeneralSettings/ContactForm.tsx, editor.planx.uk/src/pages/FlowEditor/components/Settings/GeneralSettings/SubmissionsForm.tsx, editor.planx.uk/src/pages/FlowEditor/components/Settings/ServiceSettings/FlowDescription/FlowDescription.tsx, editor.planx.uk/src/pages/FlowEditor/components/Settings/ServiceSettings/FlowStatus/index.tsx, editor.planx.uk/src/pages/FlowEditor/components/Settings/ServiceSettings/FooterLinksAndLegalDisclaimer.tsx, editor.planx.uk/src/pages/FlowEditor/components/forms/FormModal.tsx, editor.planx.uk/src/pages/GlobalSettings.tsx, editor.planx.uk/src/pages/PlatformAdminPanel.tsx, editor.planx.uk/src/routes/authenticated.tsx, editor.planx.uk/src/ui/shared/Switch.tsx
Currently we use a mix of `Sentence case` and `Title Case` across the editor, with broad mix of the two being used for titles, legends and labels. Our style guides for PlanX state that sentence case should be used except for referring to proper nouns. PR adjusts all visible titles, legends and labels to be sentence case.
Labels for switches were programatically capitalised into title case, I've added a prop `capitalize` which can be used where needed (online/offline switch).
=> fix: Consistent text case in the editor

docker-compose.yml, infrastructure/application/index.ts
Follow up to https://github.com/theopensystemslab/planx-new/pull/4179 - there's a new version! (thanks @jamdelion!)
=> chore: Bump Metabase to v0.52.7

editor.planx.uk/src/@planx/components/shared/BaseOptionsEditor.tsx, editor.planx.uk/src/@planx/components/shared/DataFieldAutocomplete.tsx
This is me trying to unpick and resolve the changes made in [https://github.com/theopensystemslab/planx-new/pulls whi](https://github.com/theopensystemslab/planx-new/pull/4171) which touch and fix a few things, but is failing E2E tests in a way I've not yet identified. I'm hoping that splitting up the fixes will help me narrow this down. 
When using a the `ListManger` and re-ordering options, the associated data fields are not correctly re-ordered and remain in their index position. This only happens on new, unsaved, list items.
I believe that this is caused by inputs going from controlled to uncontrolled ([docs](https://react.dev/learn/sharing-state-between-components#controlled-and-uncontrolled-components)), as the following error can be seen in the console on dev mode - 
By setting all …
=> fix: Force `DataFieldAutocomplete` to be controlled

api.planx.uk/modules/auth/service.ts, api.planx.uk/tests/mockJWT.ts, e2e/tests/api-driven/src/jwt.ts, e2e/tests/ui-driven/src/helpers/context.ts, e2e/tests/ui-driven/src/utils.ts
Flagged by Jumpsec pen test - 
> The applications did not securely expire user session tokens, which provides more opportunities for adversaries to compromise valid tokens and gain access to user accounts.
>
> Ensure session tokens expire within 24 hours after creation and that any log out functionality invalidates the current session token.
This adds a 24hr expiry to the token - see docs here https://github.com/auth0/node-jsonwebtoken?tab=readme-ov-file#usage
To test this I think we probably need to do it manually - we could change it to 30 minutes on this PR, merge to staging and test, then reopen with a 24hr timer. Sounds like a lot of hassle potentially - once this is merged to `main` we should be able to see the `exp` property of the token and see if we get logged out tomorrow. Any …
=> feat: Add 24hr expiry to JWT

editor.planx.uk/src/@planx/components/shared/FlagsSelect.tsx, editor.planx.uk/src/pages/FlowEditor/lib/__tests__/preview/collectedFlags.test.ts
Details outlined here - https://opensystemslab.slack.com/archives/C5Q59R3HB/p1737640916451959 (OSL slack)
When rearranging some options, an error is thrown. This is caused by options having no value for the new `flag` property which the autocomplete is expecting. As it's currently defaulting to `undefined` (the return type of `Array.prototype.filter`) this is throwing a controlled/uncontrolled error again.
Default to an empty array instead of `undefined`. 
This will mean that options without flags, will have this set to the truthy value of `[]`. I've not yet found a place where this will be an issue - we would generally iterate over flags for answers which is safe with an empty array, for example here in `collectedFlagsByCategory()` - …
=> fix: Set default value for `FlagsSelect`

editor.planx.uk/src/pages/FlowEditor/lib/analytics/mutations.ts, editor.planx.uk/src/pages/FlowEditor/lib/analytics/provider.tsx, editor.planx.uk/src/pages/FlowEditor/lib/analytics/utils.ts
Replaces #4007; see conversation here https://opensystemslab.slack.com/archives/C5Q59R3HB/p1737538391491109
**Before:**
- `analytics_logs` tracks every node you've traveled through with metadata about whether or not it's been auto-answered
- For nodes that have been put to a user, we also record `allow_list_answers` (eg answers to non-personal white-listed data fields that we can retain forever)
- We aslo only record the `next_log_created_at` timestamp for nodes which have been put to a user, which means these timestamps can be used to understand how long users spend on _visible_ nodes
- For nodes that have been auto-answered, we won't record `allow_list_answers` even if the auto-answered node sets an allow listed data field
- This generally makes sense because the auto-answered node is …
=> fix: ensure auto-answered `SetValue` nodes track allow list answers

api.planx.uk/modules/send/utils/exportZip.ts, api.planx.uk/package.json, api.planx.uk/pnpm-lock.yaml
Fixes https://github.com/theopensystemslab/planx-new/security/code-scanning/41
Although in its current implementation the user input `sessionId` will always be a valid session ID, it seems worthwhile to follow this recommendation out of an abundance of caution. A future implementation of this class may take input from elsewhere (without going through a validation step, or a roundtrip to the db).
=> fix: Sanitise zip filename

.gitignore, infrastructure/performance/README.md, infrastructure/performance/base_workload.py, infrastructure/performance/pyproject.toml, infrastructure/performance/run_locust.sh, infrastructure/performance/test_hasura.py, infrastructure/performance/test_splash.py, infrastructure/performance/utils.py, infrastructure/performance/uv.lock, package.json
Relevant Trello ticket: https://trello.com/c/oRzedbmJ
This PR introduces load testing scripts in `infrastructure/performance`.
We leverage the [Locust](https://locust.io/) package for Python to ensure our load testing suite is easily maintainable, intending that any PlanX dev can run similar tests in future againts local or staging (or pizza test envionments/prod, should we need to).
I'm not yet finished with the load testing work, but I'm just checking in the general setup and scripts for the aspects of the PlanX stack which I've already load tested to satisfaction / assessed a baseline for.
These are:
- The basic CloudFront-served HTML site (`https://editor.planx.dev/`) ✅ 
- The ECS Fargate Hasura service (server + proxy) - which in turns hits the RDS postgres database ✅ 
OSL team can …
=> [infrastructure] add initial Locust load testing scripts

api.planx.uk/.env.test.example, api.planx.uk/Dockerfile, api.planx.uk/client/index.test.ts, api.planx.uk/errors/requestHandlers.ts, api.planx.uk/modules/auth/middleware.ts, api.planx.uk/modules/flows/publish/publish.test.ts, api.planx.uk/modules/flows/validate/validate.test.ts, api.planx.uk/modules/saveAndReturn/service/resumeApplication.test.ts, api.planx.uk/modules/saveAndReturn/service/utils.test.ts, api.planx.uk/modules/saveAndReturn/service/validateSession.test.ts, api.planx.uk/modules/team/service.test.ts, api.planx.uk/modules/user/index.test.ts, api.planx.uk/server.ts, api.planx.uk/tests/mockJWT.ts, e2e/tests/ui-driven/src/utils.ts, editor.planx.uk/src/lib/graphql.ts, editor.planx.uk/src/pages/FlowEditor/lib/store/user.ts
- Follow on to #4191 & #4193
- Handles an expired token in the following ways - 
- API request - redirect to "/logout" using `res.redirect()`
- GraphQL error - catch and parse error, set `window.location.href`
There's a notable exception here with requests made to planx-core. When these requests fail we currently call a `console.error()` (generally), which can't get caught in a meaningful way by an error boundary. When I've been navigating as an Editor it's not really an issue as most pages require an Apollo request or API request, so I may get a component not loading and then a redirect a few moments later. If this feels like a real usability issue we can work our way through these, throw errors, and catch in an `ErrorBoundary`.
If you want to try this out locally, please pull down the …
=> feat: Gracefully handle expired JWTs

api.planx.uk/modules/auth/service.ts, api.planx.uk/modules/auth/strategy/google.ts, api.planx.uk/modules/auth/strategy/microsoft-oidc.ts
Internal requests from the API to Hasura are failing due to expired JWTs. See recent failures in the `#planx-notifications-internal` Slack channel (OSL).
This is happening as the `$api` client is a singleton, generated once, along with its associated JWT. Calls made by users via the API pass along their JWTs, generated at login, along with their associated roles. The internal JWT used by the API to access Haura is used for various cron jobs, admin endpoints, and other utilities.
Some cron processes are passing as their rely on the admin secret and not the JWT.
We haven't hit this (at time of writing) on staging or production as it's not yet been 24hrs since a deploy.
Remove the expiry on internal-only JWTs. This isn't actually required and it's only needed for user instantiated requests. …
=> fix: Drop expiry from internal only JWT

api.planx.uk/modules/sendEmail/controller.ts
Quick issue I spotted - it would be nice to expose this session id for debugging. It's currently possible to get this via Hasura events but it's a bit tricker that way round. 
With this id exposed we can re-trigger emails quickly and simply via the API docs.
=> chore: Improve email failure logging

api.planx.uk/modules/send/email/index.ts, api.planx.uk/modules/send/s3/index.ts
Recent email and s3 submissions errors did not log to Airbrake, and were only caught via failed Hasura events.
Please see https://opensystemslab.slack.com/archives/C01E3AC0C03/p1737837277353679 (OSL Slack) for further context.
By instantiating a `ServerError` (or a plain `Error`), we can catch this in our `ErrorRequestHandler` middleware ([here](https://github.com/theopensystemslab/planx-new/blob/a7eff12ddf2a7baef4b6c309e02e304b7f14d4d5/api.planx.uk/errors/requestHandlers.ts#L24-L53)) and log to Airbrake. This gives us better visibility on any failures.
=> fix: Log email and s3 submission failures to airbrake

hasura.planx.uk/metadata/tables.yaml
Configures missing permissions, please see comments and https://github.com/theopensystemslab/planx-new/pull/4211#discussion_r1929697776 for context.
=> fix: Restrict access by role to `submissions_services_summary`

hasura.planx.uk/metadata/tables.yaml, hasura.planx.uk/migrations/1737881459011_create_view_email_events_log/down.sql, hasura.planx.uk/migrations/1737881459011_create_view_email_events_log/up.sql
A quick followup to https://github.com/theopensystemslab/planx-new/pull/4209
It's a pain to paginate through our Hasura event logs. We already parse out relevant metadata about our submission events to `submissions_services_log` (aka the "Submissions log" in the editor), this does the same for email events now.
No plans to expose this via the editor right now, but hopefully a handy tool for dev debugging in the meantime :+1:
=> chore: create `email_events_log` view to access Hasura Event metadata

scripts/seed-database/container.sh, scripts/seed-database/write/published_flows.sql
Following a migration to add `is_statutory_application_type` to the database, I have updated the necessary scripts.
https://github.com/theopensystemslab/planx-new/pull/4169
I have tested locally with `sync-data` and have it running without error.
=> feat: Add `is_statutory_application_type` to Seed scripts

api.planx.uk/modules/file/file.test.ts, api.planx.uk/modules/file/middleware/useFileUpload.ts, api.planx.uk/modules/file/routes.ts
Described as follows by the pen test - 
> **Description**
> The application does not implement proper content filtering for file upload function allowing an attacker to upload a malicious file on the system.
>
> **Recommendation**
> Implement file content and extension filtering before saving the file on the server.
Currently, we only restrict this via the frontend. Files are sent to Scanii for checking, but are still written to the server first as this rightly points out.
Add restrictions, using the Multer `fileFilter` ([docs](https://github.com/expressjs/multer?tab=readme-ov-file#filefilter)) to stop the upload of files that don't meet the criteria. I've also added a file size restriction to match the frontend here - not a requirement for the pen test but seemed worthwhile to pick up at …
=> fix: Add filetype validation to API

editor.planx.uk/src/@planx/components/Checklist/Public/components/Checklist.tsx, editor.planx.uk/src/@planx/components/Checklist/Public/components/GroupedChecklist.tsx, editor.planx.uk/src/@planx/components/Checklist/model.test.ts, editor.planx.uk/src/@planx/components/Checklist/model.ts, editor.planx.uk/src/@planx/components/DateInput/Public.tsx, editor.planx.uk/src/@planx/components/DateInput/model.test.ts, editor.planx.uk/src/@planx/components/DateInput/model.ts, editor.planx.uk/src/@planx/components/List/Public/index.test.tsx, editor.planx.uk/src/@planx/components/NumberInput/Public.tsx, editor.planx.uk/src/@planx/components/NumberInput/model.test.ts, editor.planx.uk/src/@planx/components/NumberInput/model.ts, editor.planx.uk/src/@planx/components/TextInput/Public.tsx, editor.planx.uk/src/@planx/components/TextInput/model.test.ts, editor.planx.uk/src/@planx/components/TextInput/model.ts, editor.planx.uk/src/@planx/components/shared/Schema/InputFields/DateFieldInput.tsx, editor.planx.uk/src/@planx/components/shared/Schema/InputFields/MapFieldInput.tsx, editor.planx.uk/src/@planx/components/shared/Schema/InputFields/NumberFieldInput.tsx, editor.planx.uk/src/@planx/components/shared/Schema/InputFields/SelectInputField.tsx, editor.planx.uk/src/@planx/components/shared/Schema/InputFields/TextFieldInput.tsx, editor.planx.uk/src/@planx/components/shared/Schema/InputFields/index.tsx, editor.planx.uk/src/@planx/components/shared/Schema/model.test.ts, editor.planx.uk/src/@planx/components/shared/Schema/model.ts, editor.planx.uk/src/ui/shared/DateInput/DateInput.tsx
- Introduced a new `required` property for all schema fields
- Based on this prop, makes the input conditionally optional or required. Required is the default and fallback value if not set.
- Standardises validation schema names to `${field}InputValidationSchema` (see https://github.com/theopensystemslab/planx-new/pull/4020#discussion_r1923853166)
- Test coverage for new functionality
- Pull down branch
- Make schema changes to make fields required or not (Zoo schema has examples of each field type)
- See `" (optional)" title appended to optional fields
- Optional fields get validated correctly
=> feat: Allow optional fields in `List` and `Page` schemas

editor.planx.uk/src/@planx/components/Checklist/Editor/Options.tsx, editor.planx.uk/src/@planx/components/Checklist/Editor/components/ExclusiveOrOptionManager.tsx, editor.planx.uk/src/@planx/components/Checklist/Editor/components/GroupedOptions.tsx, editor.planx.uk/src/@planx/components/Checklist/Public/hooks/useInitialOptions.tsx, editor.planx.uk/src/@planx/components/Question/Editor.tsx, editor.planx.uk/src/@planx/components/shared/utils.ts
The `DataAutocomplete` component is not aware of the current status of the form, just the initial status. As I enter new values across fields, I should be able to reference and select them within my component. Raised here as an issue on OSL Slack - https://opensystemslab.slack.com/archives/C5Q59R3HB/p1737660734834029?thread_ts=1737640916.451959&cid=C5Q59R3HB
Rather than just entering the `formik.initialValues` as the schema, dynamically pass the current `formik.values`. As I enter new values across the current component, I can see this change reflected across all my `DataAutocomplete` components.
Please watch video in Slack thread referenced above for context
- I can open a new node (e.g. question or checklist)
- As I enter data values, each autocomplete maintains a full copy of the …
=> fix: Use current values to populate `DataAutocomplete` options, not just static initial values

infrastructure/performance/pyproject.toml, infrastructure/performance/uv.lock
Replaces https://github.com/theopensystemslab/planx-new/pulls?q=is%3Apr+is%3Aopen+-label%3Ademo
Fixes https://github.com/theopensystemslab/planx-new/security/dependabot/166 & https://github.com/theopensystemslab/planx-new/security/dependabot/167
`uv` is new to me but looks fab - worked a charm 👌 (thanks @freemvmt)
=> chore: Bump jinja

api.planx.uk/modules/file/controller.ts, api.planx.uk/modules/file/file.test.ts, api.planx.uk/modules/file/middleware/useFileUpload.ts
From Phil at Jumpsec - 
> I've looked at the file upload issue again and have noticed that whilst the restrictions have been implemented on the initial filetype uploaded, the "filename" parameter of the upload forms can be used to change the file extension of the file. I've attached a screenshot of this to demonstrate what I mean. I'm still exploring the exploitability of this, but would you be able to implement the same checks on the "filename" parameter file extension value as well to make sure this also matches the allowed list of file types? 
By adding the same validation to our Zod schema, we can share this validation check across the values in the body of the incoming http request, as well as the attached file.
- Upload a file with a valid extension / mime type (e.g. `myImage.png`) …
=> fix: Add file extension check to filename parameter in body

api.planx.uk/modules/analytics/docs.yaml, api.planx.uk/modules/analytics/metabase/collection/collection.test.ts, api.planx.uk/modules/analytics/metabase/collection/controller.ts, api.planx.uk/modules/analytics/metabase/collection/createCollection.ts, api.planx.uk/modules/analytics/metabase/collection/getCollection.ts, api.planx.uk/modules/analytics/metabase/collection/getTeamIdAndMetabaseId.ts, api.planx.uk/modules/analytics/metabase/collection/service.ts, api.planx.uk/modules/analytics/metabase/collection/types.ts, api.planx.uk/modules/analytics/metabase/shared/client.test.ts, api.planx.uk/modules/analytics/metabase/shared/client.ts, api.planx.uk/modules/analytics/metabase/shared/types.ts, api.planx.uk/modules/analytics/routes.ts, api.planx.uk/modules/send/s3/index.test.ts
- Creates `createCollectionIfDoesNotExist` service
- Creates `createCollection` Metabase API call
- Adds necessary types
- Adds necessary tests
- Creates new route for analytics module
- Fixes an import that was missing from the Metabase client (in order to get this working) [Maybe this should have gone in another PR..?]
This is the second PR that breaks up #3971 (follows #4071)
=> feat: Metabase module controller and service

hasura.planx.uk/metadata/tables.yaml, hasura.planx.uk/migrations/1738063575726_add_team_id_submissions_log_view/down.sql, hasura.planx.uk/migrations/1738063575726_add_team_id_submissions_log_view/up.sql
Per audit feedback:
- This is called via editor Apollo client (not via `$api` role so unchanged)
- Queries `submission_services_log` view which previously did not have row-level permissions configured
- Updated query definition to join to flows to access `team_id`, established "relationship" to `teams`, added row-level permissions for both `teamEditor` & `demoUser` roles
- This is called via editor Apollo client (not via `$api` role so unchanged)
- Queries `feedback_summary` view which DID have row-level permissions configured already
- Updated column-level permissions to toggle-all rather than omit recently added column
Following changes are rolled back per PR feedback / comments below:
- `GetUsersForTeam`
- This is called via editor Apollo client (not via `$api` role so unchanged)
- …
=> chore: adjust row and column access permissions in Hasura

api.planx.uk/modules/flows/docs.yaml, api.planx.uk/modules/flows/routes.ts
Only allows authenticated users to access the `/download-schema` route by applying the `useLoginAuth()` middleware.
This was flagged by the pen test. Whilst there's no security issue here - the flow data should be public, there is a performance concern for exposing this endpoint. This isn't a public feature, and a potentially expensive request - it could degrade performance if this was hit over and over.
=> fix: Add login check on `/download-schema` route

editor.planx.uk/src/lib/featureFlags.ts, editor.planx.uk/src/pages/Team.tsx
It's a basic start !
- Adds a `"TEMPLATES"` feature flag
- When toggled on, will show an additional "Start from a template" button to editors, which opens a modal with basic placeholder text, a select picker (to be populated for real in a future PR once we have a way of tagging & querying flows as a "source" template), and two buttons - one to simply close/go back and one to create the template you've selected (to be wired up next)
Goal here is to keep templates PRs small & quick, so that as much feature-flagged, "skeleton" UI can get to `main` as frequently as possible, allowing design refinement to happen in parallel to technical development.
=> feat: add "TEMPLATES" feature flag and skeleton UI

editor.planx.uk/src/pages/FlowEditor/ReadMePage/tests/ReadMePage.test.tsx
Has been repeatedly timing on out CI.
This test runs in about ~4500ms for me locally, so doubled that for CI :crossed_fingers:
=> fix: bump default timeout for readme react test

editor.planx.uk/src/@planx/components/Content/Public.tsx, editor.planx.uk/src/@planx/components/FileUploadAndLabel/Public.tsx, editor.planx.uk/src/@planx/components/Notice/Public.tsx, editor.planx.uk/src/@planx/components/shared/Preview/CardHeader/CardHeader.tsx, editor.planx.uk/src/ui/editor/RichTextInput/RichTextInput.stories.tsx, editor.planx.uk/src/ui/editor/RichTextInput/RichTextInput.test.tsx, editor.planx.uk/src/ui/editor/RichTextInput/RichTextInput.tsx, editor.planx.uk/src/ui/editor/RichTextInput/components/HeadingButtons.tsx, editor.planx.uk/src/ui/editor/RichTextInput/components/MentionList.tsx, editor.planx.uk/src/ui/editor/RichTextInput/components/PopUpError.tsx, editor.planx.uk/src/ui/editor/RichTextInput/components/RichTextInputButtons.tsx, editor.planx.uk/src/ui/editor/RichTextInput/components/suggestion.tsx, editor.planx.uk/src/ui/editor/RichTextInput/styles.ts, editor.planx.uk/src/ui/editor/RichTextInput/tiptapExtensions.ts, editor.planx.uk/src/ui/editor/RichTextInput/types.ts, editor.planx.uk/src/ui/editor/RichTextInput/utils.ts, editor.planx.uk/src/ui/editor/RichTextInput/validationHelpers.ts
🔥 Blazing in to completely split this file up as it was my most hated file to look at (so far...). 
Using the excuse of the next ticket on my radar (https://trello.com/c/Sv8IfEVi/3206-add-validation-to-editor-modals-to-prevent-made-policy-reference-links-from-being-added-to-help-text) to do this now!
**Summary:**
- `RichTextInput.tsx` now mostly just contains the main input component and editor.
- `/components` sub-folder contains all other defined components that were in the main folder, along with newly extracted `RichTextInputButtons` (such as `H1Button`)
- Styled components extracted to `styles.ts`
- Type definitions extracted to `types.ts`
- Most of the helper functions extracted to `utils.ts`
Now much easier to read in my opinion! 🤭
=> refactor: split Rich Text Input file into smaller files

hasura.planx.uk/metadata/tables.yaml
Quick follow up to #4232 
Something I missed here is that I need a relationship established between a parent template flow, and all of its children (flows derived from it).
This is what we'll use to cascade changes from parent → child, and to block template flows which have "children" to be deleted/archived.
=> feat: Set up relationship between a template flow and children derived from it

scripts/seed-database/write/flows.sql
Identified by @RODO94 here - https://github.com/theopensystemslab/planx-new/pull/4235#issuecomment-2627439158
The sync script is currently failing on `main`.
Two new columns were added here but missed from the sync script - https://github.com/theopensystemslab/planx-new/pull/4145/files#diff-e120d8d8f11dfabb1f6e3d57d577b2f9ac0d0c1ef1a4695d4ab9c265d7cd4eb0
This PR updates the sync script to included these new columns.
=> fix: Sync new `flows.summary` and `flows.limitation` columns

scripts/seed-database/write/flows.sql
Seed scripts were failing and showing the error with the input mistake as it was trying to add `<p>...</p>` to the `templated_from` column which expected a `uuid` type. Seems like this is a simple ordering issue of seed script changes happening close together and in fact, `<p>...</p>` should be trying to update the `description` column.
I have switched these round locally, and it is working as expected
Here's the problem `flow_id` : `9d70b18e-be0d-4f21-944c-a129da271ebd`
=> fix: switch order of column select in `seed-database` flows scripts

api.planx.uk/modules/file/controller.ts, api.planx.uk/modules/file/middleware/useFileUpload.ts
Noticed a fair number of file type errors since the last deploy - https://planx.airbrake.io/projects/329753/groups/3994017674295351163?tab=notice-list
Additional logging here should check we're not being overly restrictive on the API, or too open on the frontend.
=> chore: Improve logging for `fileType` errors

infrastructure/application/Pulumi.production.yaml, infrastructure/application/Pulumi.staging.yaml, infrastructure/application/services/hasura.ts, infrastructure/application/utils/failureNotification.ts, infrastructure/application/utils/index.ts
Follow up to https://github.com/theopensystemslab/planx-new/pull/4096
When a deployment fails on AWS, this will trigger a Slack webhook to ping the `#planx-notifications-internal` channel which is where notifications are currently set up for failed CI deployments.
I believe that this only applies to Hasura currently which has circuit breakers and rollbacks in place - other failures should fail a health check and trigger notifications via CI/Pulumi or UptimeRobot. However I've aimed to write the code in an agnostic way so that we could apply it to other services in future if needed to.
Currently there's just a single webhook for both staging and production - if we find we need to / want to differentiate here I can set up one per-environment if required. Once I've been able to test this I …
=> feat: Setup Slack notification for failed Fargate deployment

infrastructure/application/Pulumi.production.yaml, infrastructure/application/Pulumi.staging.yaml
Fix for #4245. Turns out I used the incorrect URL for the variable!
I provided the workflow URL (formatted `https://slack.com/shortcuts/XXX`) when I intended to use the webhook URL (formatted `https://hooks.slack.com/triggers/XXX`).
=> fix: Set correct webhook URL as secret

api.planx.uk/helpers.ts, api.planx.uk/modules/flows/createFlow/controller.ts, api.planx.uk/modules/flows/createFlow/createFlow.test.ts, api.planx.uk/modules/flows/createFlowFromTemplate/controller.ts, api.planx.uk/modules/flows/createFlowFromTemplate/createFlowFromTemplate.test.ts, api.planx.uk/modules/flows/createFlowFromTemplate/service.ts, api.planx.uk/modules/flows/docs.yaml, api.planx.uk/modules/flows/routes.ts, editor.planx.uk/src/pages/FlowEditor/lib/store/editor.ts, hasura.planx.uk/metadata/tables.yaml
**Changes:**
- Removes redundant `createFlow` GraphQL mutations from the frontend store and instead calls a new API route `flows/create` to access existing API-side mutations already used by copy, move, etc.
- Adds another new API route `/flows/create-from-template/:templateId` which creates a new flow in the target team with a populated `templated_from` reference and data matching the source template (nodes _are not_ renamed like on copy)
- This route _cannot_ be called from the frontend until we have a way of identifying & selecting "source templates" from the skeleton modal - but it's possible to call it direct from Swagger docs in the meantime by passing any valid `flowId` as the `templateId`
=> feat[api]: create flows from templates

editor.planx.uk/src/pages/FlowEditor/lib/store/editor.ts, editor.planx.uk/src/pages/Team.tsx
This PR is linked to this Trello ticket: https://trello.com/c/Lsjy4ZgQ/3195-add-descriptive-error-message-for-duplicate-slug-when-copying-a-service-and-moving-it-to-a-new-team
It comes from a situation where a flow was copied and the user tried to move it to another team, but the other team already had a flow with the same name. No useful error was shown to point the user towards how to resolve it. This is what I have added here.
To guide users towards resolving errors themselves, I have added two new pathways / error messages.
1. For duplicate names within a team, I have added a new prompt pre-populated with the first attempted name
This should help users tweak their initial trial to push it through.
2. I have added a conditional alert for the `uniqueness violation` error messages which …
=> feat: additional error messages for duplicate flow name and moving a flow

editor.planx.uk/src/pages/FlowEditor/floweditor.scss
Quick one: fixes clone styling so that visited clones are still given visible border treatment.
Before (left) vs after (right):
**Test:**
https://4251.planx.pizza/testing/clone-styling
=> fix: Visited clone styling

api.planx.uk/package.json, api.planx.uk/pnpm-lock.yaml, api.planx.uk/tests/mocks/inviteToPayData.ts, api.planx.uk/tests/mocks/inviteToPayMocks.ts, e2e/tests/api-driven/package.json, e2e/tests/api-driven/pnpm-lock.yaml, e2e/tests/ui-driven/package.json, e2e/tests/ui-driven/pnpm-lock.yaml, e2e/tests/ui-driven/src/invite-to-pay/mocks.ts, editor.planx.uk/package.json, editor.planx.uk/pnpm-lock.yaml, editor.planx.uk/src/@planx/components/Pay/Public/Confirm.tsx, editor.planx.uk/src/@planx/components/Pay/Public/FeeBreakdown/FeeBreakdown.tsx, editor.planx.uk/src/@planx/components/Pay/Public/InviteToPayForm.tsx, editor.planx.uk/src/@planx/components/Pay/Public/Pay.stories.tsx, editor.planx.uk/src/@planx/components/Pay/Public/Pay.test.tsx, editor.planx.uk/src/@planx/components/Pay/Public/Pay.tsx, editor.planx.uk/src/@planx/components/Pay/Public/utils.ts, editor.planx.uk/src/lib/local.new.ts
- Refactors `Confirm` component to more explicitly handle various states
- Before this PR, the logic for information only, pay, and invite to pay was quite tricky to manage and understand - adding a "zero fee" option into the mix would add to this confusion.
- Renders `Confirm` in instances where fee is £0
- Removes fee breakdown title and description - if we find we need these we can add them back. There's already a clear title and simple description here.
- Pulls in changes made in https://github.com/theopensystemslab/planx-core/pull/637 which also renders any exemptions
There's still scope here for a content pass through which I'm going to address once this feature is technically complete (e.g. the title "pay for your application" is not very meaningful when we know the fee is £0.) …
=> feat: Display `Pay` component when fee is zero

editor.planx.uk/src/components/EditorNavMenu.test.tsx, editor.planx.uk/src/components/EditorNavMenu.tsx, editor.planx.uk/src/routes/authenticated.tsx
Quick proof of concept to test if the method trialled [here](https://github.com/theopensystemslab/planx-new/pull/4154/files) will work on staging and production, using the IFrame protection set up on AWS Cloudfront.
This is just a test, and once deployed to staging I'll immediately open a revert PR.
I _think_ it will work - our iframe embed headers should stop PlanX being embedded, as opposed to us embedding.
=> poc: Notion iframes in AWS Cloudfront [skip pizza]

editor.planx.uk/src/pages/Team.tsx, editor.planx.uk/src/ui/editor/SortControl.tsx
- Adds styling to the "sort flows" selects
- Updates layout with placeholder "Showing X services" title
⛳️ Requires feature flag: `window.featureFlags.toggle("SORT_FLOWS")`
Before change:
After change:
Preview:
https://4258.planx.pizza/doncaster
=> style: Sort flows selects

editor.planx.uk/src/ui/editor/Filter/Filter.tsx
This is a leftover bug from the `Filter` component work where the searchParams were being cleared on mount. 
Found that it was due to us parsing the filters from the URL and submitting, but that `values.filters` in formik would still be undefined, so it would clear the filters and not apply them. I added a simple effect to re-run `handleSubmit` when this is done. This also has the added effect of not requiring us to re-call `handleSubmit` at other interactions, and rely upon it running when `values.filters` changes
=> fix: read url params for search

editor.planx.uk/src/ui/editor/Filter/Filter.tsx, editor.planx.uk/src/ui/editor/Filter/FiltersColumn.tsx
- Adds correct width to filter columns
Before change:
After change:
Preview:
https://4272.planx.pizza/doncaster
=> style: Filter column widths

editor.planx.uk/src/pages/Team.tsx
This PR follows on from the `SearchBox` and `Filter` component PRs. Each component would filter `flows` and up until this point, they would `setFilteredFlows`. The issue we run into now is when a user wants to **Search** and **Filter**.
To get round this and make it clear what does what. Each component will still search/filter `flows` but they will set their own array `searchedFlows || filteredFlows` - this will then be filtered in the `useEffect` and set a new state variable called `matchedFlows`
My thinking is that:
- If you search first
- `searchedFlows` will change
- `filteredFlows` will be equal to `flows`
- `searchedFlows` is filtered based on whether they exist in `filteredFlows`
- The return will be set as `matchedFlows`
- if you filter first
- `filteredFlows` will change
- …
=> feat: wire up search and filter on Team page

editor.planx.uk/src/components/EditorNavMenu.test.tsx, editor.planx.uk/src/components/EditorNavMenu.tsx, editor.planx.uk/src/pages/FlowEditor/components/Flow/FeedbackLog/FeedbackLog.tsx, editor.planx.uk/src/pages/FlowEditor/components/Flow/FeedbackLog/components/CollapsibleRow.tsx, editor.planx.uk/src/routes/feedback.tsx, editor.planx.uk/src/routes/team.tsx, hasura.planx.uk/metadata/tables.yaml, hasura.planx.uk/migrations/1738840144554_add_flow_name_to_feedback_summary/down.sql, hasura.planx.uk/migrations/1738840144554_add_flow_name_to_feedback_summary/up.sql
- Moves the feedback log page a step higher - from service level to team level
- Updates query to fetch service name
- Updates UI to display service name
Please note: this is just aiming to sort out the routing and associated data changes - no visual or functional changes apart from this (e.g. table styling, filters, link to service).
Example - https://4261.planx.pizza/doncaster/feedback
=> feat: Hoist feeback to team level

editor.planx.uk/src/ui/shared/Checkbox/Checkbox.tsx
Small fix for UI issue noticed on the filters PRs that's not yet been addressed.
When a checkbox is focused on the filters, it picks up a grey background - this resolves the issue.
=> fix: Transparent focused checkboxes

api.planx.uk/modules/admin/feedback/feedback.test.ts, api.planx.uk/modules/admin/feedback/feedback.ts, api.planx.uk/modules/admin/routes.ts, hasura.planx.uk/metadata/tables.yaml
See thread https://opensystemslab.slack.com/archives/C01E3AC0C03/p1738856231269679?thread_ts=1738767687.943469&cid=C01E3AC0C03
Testing notes:
- I've added a quick feedback entry via this pizza already (feedback id = 1)
- Login into the editor, then confirm you get a JSON response at [https://api.4277.planx.pizza/admin/feedback/1](https://api.4277.planx.pizza/admin/feedback/1)
- The JSON response notably includes `userBreadcrumbs` & `userPassport` keys ! 
- Note that when accessing `/admin` endpoints on staging or prod you'll additionally need to be connected to WARP
=> feat: simple `/admin/feedback/:feedbackId` endpoint to access associated user data

editor.planx.uk/src/components/EditorNavMenu.test.tsx, editor.planx.uk/src/components/EditorNavMenu.tsx, editor.planx.uk/src/routes/authenticated.tsx, editor.planx.uk/src/ui/editor/NotionEmbed.tsx
Turns out we can do this and save the $2 monthly fee - still need to check ours Cloudfront setup allow this without changes to CSP headers.
=> feat: Embed using native Notion "Share > Embed this page" option

editor.planx.uk/src/pages/Team/StartFromTemplateButton.tsx, editor.planx.uk/src/pages/Team/index.tsx, hasura.planx.uk/metadata/tables.yaml, hasura.planx.uk/migrations/1738946199211_alter_table_public_flows_add_column_is_template/down.sql, hasura.planx.uk/migrations/1738946199211_alter_table_public_flows_add_column_is_template/up.sql
- Create a new `flows.is_template` column
- Readable by all, but can only be set by `platformAdmins`
- Updates `StartFromTemplateButton` component to display actual list of templates, wires up basic formik
- Just logs out a value, doesn't interact with the API
Having this additional column will massively simplify some of the permissions in https://github.com/theopensystemslab/planx-new/pull/4234 which are trying to check the existance of a relationship, instead of a simple value.
=> feat(templates): Add `flows.is_template` column

editor.planx.uk/src/components/EditorNavMenu.test.tsx, editor.planx.uk/src/components/EditorNavMenu.tsx, editor.planx.uk/src/pages/FlowEditor/components/Flow/GetStarted.tsx, editor.planx.uk/src/pages/FlowEditor/components/Flow/index.tsx, editor.planx.uk/src/routes/authenticated.tsx, editor.planx.uk/src/ui/editor/NotionEmbed.tsx
- Adds "Tutorials" and "Onboarding" links to sidebar
- Adds "GetStarted" option to empty flows
- All based on @ianjon3s's work on https://github.com/theopensystemslab/planx-new/pull/4154/files, and the new Notion iframes from #4279 
Tested and working on staging (AWS Cloudfront) ✅ 
I've scheduled a message to Rish [in this thread](https://opendigitalplanning.slack.com/archives/C0241GWFG4B/p1738837581734279) (ODP Slack) for Monday morning asking him to test the staging environment - lets make sure it's just the Notion iframes that are blocked and not the entire site 🤞 
---
Note: Dark mode is displaying as this is my system preferences. We can configure this in Notion and hardcode to "Light" if we wish to do so.
=> feat: Setup remaining Notion iframes

editor.planx.uk/src/pages/Team.tsx
- Removes search, filters and sort when no services are present
Before changes:
After changes:
**Preview:**
https://4273.planx.pizza/a-new-team
=> refactor: Simplify view when no services are present

hasura.planx.uk/migrations/1739222061613_update_view_applicant_research_opt_in/down.sql, hasura.planx.uk/migrations/1739222061613_update_view_applicant_research_opt_in/up.sql
See request here: https://opensystemslab.slack.com/archives/C01E3AC0C03/p1739179324695849
**Key changes:**
- Renames `id` to `planx_application_reference`
- Adds `site_address`
- Adds `user_role`
- Updates `first_name` and `last_name` to reference correct variables based on `user_role`
=> fix: get name based on user role in `applicant_research_opt_in_view`

editor.planx.uk/src/pages/Team/components/ShowingServicesHeader.tsx, editor.planx.uk/src/pages/Team/index.tsx, editor.planx.uk/src/ui/editor/Filter/Filter.tsx, editor.planx.uk/src/ui/shared/SearchBox/SearchBox.tsx
The final major feature for Filters and Search for the Team page is a clear all button, which clears search term and any collected filters resetting the results back to normal.
The feature should allow a user to filter the list, add a search term and in one click, clear both to reset the list. It should also work independently (if the list is only filtered, or if it is only searched).
This meets feature parity with our demo branch: https://github.com/theopensystemslab/planx-new/pull/4120
>[!IMPORTANT] 
> To test the pizza you need to toggle the feature flag "SORT_FLOWS"
=> feat: Clear filters and search button

editor.planx.uk/src/pages/Team/index.tsx
Picks up two previously applied changes that were lost during rebases:
- Changes default sort category for service cards to be "Last updated"
- Fixes padding for grid when no services are present ("get started" card is in place)
=> fix: Default sort order for service cards

editor.planx.uk/src/ui/shared/Checkbox/Checkbox.tsx, editor.planx.uk/src/ui/shared/ChecklistItem/ChecklistItem.tsx
Fixes a global (public & editor) issue where the clickable width of checkboxes extends beyond the text label.
Also addresses vertical alignment so that the first line of text is always aligned with the centre of the checkbox (rather than the whole text block).
Making both of these changes brings us inline with the GOV.UK checkbox style:
https://design-system.service.gov.uk/components/checkboxes/
Preview:
https://4300.planx.pizza/testing/checkboxes-variable-width/published?analytics=false
=> fix: Clickable width and alignment of checkboxes

e2e/tests/api-driven/src/demo-workspace/helper.ts, editor.planx.uk/src/pages/FlowEditor/lib/store/editor.ts, editor.planx.uk/src/pages/Team/index.tsx, hasura.planx.uk/metadata/tables.yaml, hasura.planx.uk/migrations/1738318254560_alter_table_public_flows_add_column_deleted_at/down.sql, hasura.planx.uk/migrations/1738318254560_alter_table_public_flows_add_column_deleted_at/up.sql, hasura.planx.uk/tests/flows.test.js
- Removes "delete" button from the frontend UI - to be replaced by "Archive" [in this ticket](https://trello.com/c/fhoa1wCa/3166-add-ability-to-archive-flows-instead-of-deleting-them?filter=archive)
- Adds `flows.deleted_at` column in order to allow a soft delete pattern
- Removes "delete" permissions from all roles for the `flows` table
- Allows all roles to set the `flows.deleted_at` column (within the parameters of their current permission levels)
- Does not allow any roles to soft delete (set `flows.deleted_at`) for template flows
Some of this is pretty tricky to understand via the `tables.yaml` and took a bit of trial and error to figure out. Some e2e test coverage is needed here to explain this and act as a guard rail for future changes. I'm planning on introducing this in a future …
=> feat: Do not allow template flows to be deleted / archived

editor.planx.uk/src/@planx/components/Pay/Public/FeeBreakdown/FeeBreakdown.tsx
Quick one: introduces `formWrap` max-width to the fee breakdown table to improve readibility.
Before change:
After change:
Preview (Storybook):
https://storybook.4302.planx.pizza/?path=/docs/planx-components-pay-feebreakdown--docs
=> style: Form max-width for fee breakdown table

editor.planx.uk/src/pages/FlowEditor/lib/store/editor.ts, editor.planx.uk/src/pages/Team/components/FlowCard.tsx
Outputs flow summary on the corresponding `flowCard`.
=> feat: Hook up flow summary to card

editor.planx.uk/src/pages/FlowEditor/ReadMePage/ReadMePage.tsx
Updates readme page show/hide external portals from using a `<Switch>` to use `<SimpleExpand>`.
Rationale:
We use the switch component as an in-form input to toggle functionality or settings, this is occasionally tied in with an interface change (for example when using expandable checklists). For interface only (show/hide) functions we use `<SimpleExpand>` or the accordion component.
Something I'm not sure about (cc @jamdelion ) — is the switch/toggle a performance consideration (only fetch portal list on "show"), which I'm overriding with this change, or is it a purely visual thing?
Preview:
https://4303.planx.pizza/barnet/apply-for-prior-approval/about
=> refactor: Readme page external portal switch to expand

editor.planx.uk/src/@planx/components/shared/FlagsSelect.tsx, editor.planx.uk/src/ui/editor/ComponentTagSelect.tsx, editor.planx.uk/src/ui/shared/Autocomplete/components/RenderOptionCheckbox.tsx
- Fixes [a visual regression introduced here](https://github.com/theopensystemslab/planx-new/pull/3998/files#diff-b2b6873296b0da41040b9766358555ab5d2d701a68f23b7348e5465dc7cdb613L28) in #3998
- Allows style overrides to be passed down through the shared `RenderOptionCheckbox`
This solution ensures that the background colour is correct for the filters, flag select, and general checkboxes.
|![Screenshot 2025-02-13 at 16 26 04](https://github.com/user-attachments/assets/0c1e82a5-4adb-4963-915b-3dd63a28f5e5)|![Screenshot 2025-02-13 at 16 25 31](https://github.com/user-attachments/assets/bd44a070-65d8-41c8-b55b-9cf84241b74c)|
|![Screenshot 2025-02-13 at 16 20 23](https://github.com/user-attachments/assets/74118cd6-15b5-4210-a569-8228f5f439d7)|![Screenshot …
=> fix: Checkbox background style

editor.planx.uk/src/ui/editor/SortControl/SortControl.tsx
Found a bug in testing where query params were not updating when you selected a filter because `SortControl` was running at the same time when `matchingRecords` updated, but it would be before the state change of the URL changes. This meant the chosen filter would flicker in the URL and disappear. 
It made more sense to move this particular function inside it's own Effect so it can update when the URL or sort direction was to update
=> fix: query params not updating when filters update

infrastructure/data/index.ts
**Two key changes here [per Trello comments](https://trello.com/c/qda9058V/3186-update-aws-rds-postgresql-engine-version):** 
- Changes staging `backupRetention` from 0 to 1
- Bumps `engineVersion` to 16.1 which is latest major version we're able to upgrade to, once this succeeds we can aim to get to latest minor version of 16.7
AWS restricts major version leaps - see versions available to us by running 
```shell
$ aws rds describe-db-engine-versions --engine postgres  --engine-version 12.17 --query "DBEngineVersions[*].ValidUpgradeTarget[*].{EngineVersion:EngineVersion}" --output text
12.18
12.19
12.20
12.21
12.22
13.13
13.14
13.15
13.16
13.17
13.18
14.10
15.5
16.1
```
This PR bumps our Pulumi data layer which will need to be manually deployed, see Docker equivalent here for local & …
=> infra: upgrade to postgres 16.1 (then 16.7)

editor.planx.uk/src/ui/editor/SortControl/utils.ts
Found that we were defaulting to the oldest updated first as default, decided to switch this so the last updated service is shown at the top
=> fix: switch sort default to "desc"

infrastructure/data/index.ts
Our RDS instance is actually on 12.19, not 12.17 as Pulumi config had, therefore our valid jump is 16.3, not 16.1.
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.PostgreSQL.MajorVersion.html
=> infra: bump postgres to 16.3

api.planx.uk/modules/analytics/metabase/collection/collection.test.ts, api.planx.uk/modules/analytics/metabase/collection/createCollection.ts, api.planx.uk/modules/analytics/metabase/collection/getCollection.ts, api.planx.uk/modules/analytics/metabase/collection/types.ts, api.planx.uk/modules/analytics/metabase/dashboard/copyDashboard.ts, api.planx.uk/modules/analytics/metabase/dashboard/dashboard.test.ts, api.planx.uk/modules/analytics/metabase/dashboard/getDashboard.ts, api.planx.uk/modules/analytics/metabase/dashboard/service.ts, api.planx.uk/modules/analytics/metabase/dashboard/types.ts, api.planx.uk/modules/analytics/metabase/dashboard/updateFilter.ts
Replaces #4260 because my rebase got way too messy!
Requests and responses are handled once at the point of entry / exit. Each function handles any relevant transformations, and Metabase specific types are added too.
Metabase API uses snake_case, PlanX camel. Carries on from https://github.com/theopensystemslab/planx-new/pull/4157#discussion_r1932074730 in https://github.com/theopensystemslab/planx-new/pull/4157 about how best to handle case conversions.
=> feat: handle Metabase API <-> PlanX API camelCase to snake_case conversion (v2)

docker-compose.yml, infrastructure/application/index.ts, sharedb.planx.uk/server.js
- Toggles the `ssl` property on ShareDB
Postgres 16 (on AWS RDS) sets `force_ssl` to `true` by default. This means that ShareDB is unable to connect to the postgres database while `ssl` is disabled.
One method would be to disable `ssl` on staging and production, but this seems unnecessary from both a risk and complexity option (we need to configure a new parameter group).
I spent a good bit of time trying to get `ssl: true` to work in docker environments and got pretty close. We need self-signed certificates to be generated when the postgis docker container spins up and I hit the following issues - 
- Our Alpine linux distro doesn't come with self-signed certificates (if it did, it would be simple config change)
- The distro doesn't have `openssl` installed
- Installing `openssl` and …
=> feat(sharedb): Toggle Postgres SSL for AWS environments

editor.planx.uk/src/routes/flow.tsx
Please see https://opensystemslab.slack.com/archives/C01E3AC0C03/p1739802552794749 for context (OSL Slack).
**What's the problem?**
When https://github.com/theopensystemslab/planx-new/pull/4256 was merged, we didn't consider that nodes may already have the "placeholder" tag applied. Currently, any nodes with this tag will fail to render in the Editor.
**What's the solution?**
The right solution is to migrate any flows which contain the legacy "placeholder" tag to use the new "customisation" tag. I've added a blue trello card for this here - https://trello.com/c/Cvwe9t9N/3241-migrate-placeholder-tags-to-customisation
In the meantime, a quick guard to convert manually will unblock any Editors.
=> fix: Add temporary guard to convert placeholder tags

editor.planx.uk/src/pages/Team/helpers/sortAndFilterOptions.ts, editor.planx.uk/src/ui/editor/SortControl/SortControl.tsx, editor.planx.uk/src/ui/editor/SortControl/utils.ts
This PR responds to feedback here: https://opensystemslab.slack.com/archives/C5Q59R3HB/p1739788849390769
I have added a function to the `orderBy` iteratee section which mutates the original sort array by sorting all null values to the bottom. Currently, for date formats especially, these were being formatted to the 'newest' sort. 
The sort option `last updated` has now been changed to `last edited` as well.
=> feat: sort null to bottom in SortControl component

hasura.planx.uk/metadata/tables.yaml, hasura.planx.uk/migrations/1739878905926_create_table_public_revoked_tokens/down.sql, hasura.planx.uk/migrations/1739878905926_create_table_public_revoked_tokens/up.sql, hasura.planx.uk/tests/revoked_tokens.test.js
- Creates the `revoked_tokens` table
- Introspection tests
Work in progress documentation here - https://www.notion.so/opensystemslab/How-does-authentication-work-19e35d469ad180b2bc17ce5bc29f6477
Technical checklist on Trello - https://trello.com/c/GZIRbSNO/3217-invalidate-jwt-on-logout
=> feat: Add `revoked_tokens` table

editor.planx.uk/src/@planx/components/FileUpload/model.tsx
Make a file upload component and upload an image of at least 1MB in size (perhaps use example from error reported on ODP slack). An error flashes up if you press continue straight away. This PR simply changes the wording of that error message to be more clear.
**More context:**
https://opensystemslab.slack.com/archives/C088K9ZL8EA/p1739879595245729?thread_ts=1739449301.836729&cid=C088K9ZL8EA
https://github.com/user-attachments/assets/bc18a3ab-ce2f-477b-8aad-256d615f07b1
=> fix: file upload error message if upload in progress

editor.planx.uk/src/components/EditorNavMenu/EditorNavMenu.tsx
Quick one: shortens "Submissions log" menu item to "Submissions" to keep text on one line.
**After change:**
=> fix: Shorten submissions log menu item

editor.planx.uk/src/routes/flow.tsx
Ready to merge after production data migration completes; please note this pizza was built _before_ prod migration completed - so will be most accurate to test on staging ! 
Reverts #4335 & #4342
=> chore: revert "placeholder" tags workaround

editor.planx.uk/src/pages/Team/components/FlowCard.tsx, editor.planx.uk/src/pages/Team/helpers/sortAndFilterOptions.ts
Until we get feedback on how to define what a statutory application is, we should remove this from the work.
Current issues with this have been captured in this Slack thread: https://opensystemslab.slack.com/archives/C5Q59R3HB/p1739800315291939?thread_ts=1739788849.390769&cid=C5Q59R3HB
In short, we are incorrectly labelling some flows which are Discretionary services, but within their external portals are still assigning `application.type` to an ODP Schema approved value, which incorrectly triggers the `statutory` tag.
=> feat: remove statutory application type from tags and filters

infrastructure/data/index.ts
- Sets the AWS RDS maintenance window to `"Mon:00:00-Mon:03:00"`
- Bumps the Postgres version to 16.7
Docs: https://www.pulumi.com/registry/packages/aws/api-docs/rds/instance/#maintenancewindow_nodejs
This will also require a manual deploy of the data layers on staging and production, happy to sort this out once approved and merged.
=> chore(iac): Standardise RDS maintenance window, minor PostgreSQL bump

editor.planx.uk/src/lib/featureFlags.ts
Quick one: removes `SORT_FLOWS` from the list of available feature flags.
=> fix: Remove SORT_FLOWS from feature flag list [skip pizza]

editor.planx.uk/src/components/EditorNavMenu/EditorNavMenu.tsx, editor.planx.uk/src/pages/FlowEditor/components/Settings/Submissions/index.tsx, editor.planx.uk/src/pages/FlowEditor/components/Settings/Submissions/types.ts, editor.planx.uk/src/routes/submissionsLog.tsx
Certain flows fail to display submissions, e.g. https://editor.planx.dev/camden/submissions-log?flow=camden-apply-for-a-lawful-development-certificate
Others work fine, e.g. https://editor.planx.dev/tewkesbury/submissions-log?flow=report-a-breach
We're currently passing through the flow slug and trying to generate a flow name from this in order to filter. This isn't possible as `slugify()` is a destructive, one-way, process.
For example -
- `"CAMDEN - Apply for a lawful development certificate"` would become `"camden-apply-for-a-lawful-development-certificate"`
- `"special CharaCTERS1@@£!!"` becomes `"special-characters1"`
There's no way to reconstruct a flow name from a flow slug, so we need to compare two static values in order to filter.
- Filters the `/${teamSlug}/submissions-log` …
=> fix: Filter submission by flowId

api.planx.uk/package.json, api.planx.uk/pnpm-lock.yaml, e2e/tests/api-driven/package.json, e2e/tests/api-driven/pnpm-lock.yaml, e2e/tests/ui-driven/package.json, e2e/tests/ui-driven/pnpm-lock.yaml, e2e/tests/ui-driven/src/invite-to-pay/nominee.spec.ts, editor.planx.uk/package.json, editor.planx.uk/pnpm-lock.yaml, editor.planx.uk/src/@planx/components/Pay/Public/Confirm.tsx, editor.planx.uk/src/@planx/components/Pay/Public/Pay.stories.tsx, editor.planx.uk/src/lib/featureFlags.ts, editor.planx.uk/src/pages/Pay/MakePayment.tsx
This PR removes the `FEE_BREAKDOWN` feature flag.
**Resources**
- Trello ticket - https://trello.com/c/B3XJVH3l/3067-show-a-breakdown-of-planning-fee-service-charge-to-users
- Storybook - https://storybook.4262.planx.pizza/?path=/docs/planx-components-pay-feebreakdown--docs
- Testing notes - https://docs.google.com/document/d/1eIg-BcH0DaNHxYYHMfWrkUsJkjyXKMJJbGWaCkYMw9s/edit?tab=t.0
- Documentation - https://www.notion.so/opensystemslab/How-displaying-the-fee-breakdown-works-19035d469ad180e3bcd2eab977a39a56
=> chore: Drop fee breakdown flag

editor.planx.uk/src/pages/FlowEditor/components/Settings/Submissions/index.tsx
A condition was missed off in the submissions filter that meant no submissions were showing if no `flowId` rather than all.
This probably would have been caught if we had test coverage in this area - I'll try to rectify that in the upcoming 'filterable submissions table' PRs.
=> fix: show submissions for all flows if no flowId

api.planx.uk/modules/analytics/routes.ts, api.planx.uk/shared/middleware/useEnvGuard.ts
- Metbase doesn't exist locally, or on Pizzas
- It's going to get called via Hasura events (see #4334)
- This will lead to a bunch of errors which we could avoid
- Running Metabase on pizzas (bad - more CI time for little gain)
- Running Metabase locally, syncing data (also not great - nice to optionally do it, but making it a requirement isn't ideal)
- Ignoring this, letting it fail (maybe!)
Very open to ideas here - the current implementation will stop Metabase routes from being accessible locally and on Pizzas.
=> feat: Add env guard middleware

editor.planx.uk/src/ui/editor/Filter/tests/Filter.test.tsx, editor.planx.uk/src/ui/editor/Filter/tests/helpers.ts, editor.planx.uk/src/ui/editor/Filter/tests/mocks.ts
This PR adds unit test coverage for the new `Filters` component as defined here: https://trello.com/c/YU56MRW8/3230-add-unit-tests-for-filter-component
Purpose is to ensure the component can receive an array called `records`, filter the records using `filterOptions` and set a new array with `setRecords`.
It does not delve into testing the inputs at their component level, for instance checking that checkboxes can be checked. I focused on ensuring Filters specific logic works as expected. 
With this in mind, a test in the Technical Plan made on the Trello ticket that I have not added related to displaying an array of records, but as I was structuring the tests I found this to sit outside the role of `Filters` and would be something the parent component would be responsible for. `Filters` …
=> feat: unit tests for Filters

editor.planx.uk/src/pages/PlatformAdminPanel/PlatformAdminPanel.tsx, editor.planx.uk/src/ui/editor/FixedHeightDashboardContainer.tsx, editor.planx.uk/src/ui/shared/DataTable/DataTable.tsx
- Ensures data table fills available screen height to prevent dual scrolling and keep footer visible at all times
- Creates a reusable custom container to achieve this, can be used in place of `<Container>` for any admin/dashboard views that need to be restrained to full-screen-height with overflow scroll
- Adjusts height based on presence of test environment banner
**Preview:**
https://4376.planx.pizza/admin-panel
=> fix: Create fixed-height view for data table

editor.planx.uk/src/pages/Team/index.tsx, editor.planx.uk/src/ui/editor/Filter/Filter.tsx
When performing an action on a `FlowCard` like `copyFlow` - `moveFlow` - `archiveFlow` - the flow list was returning `null`. This was due to the `useEffect` we have which finds the intersection of `searchedFlows` and `filteredFlows`. It kept returning `null` when the `fetchFlows()` ran which updated `searchedFlows` but not `filteredFlows`.
More details in this Slack thread: https://opensystemslab.slack.com/archives/C01E3AC0C03/p1740561802501189
This was due to how each component was handling `flows` in it. `searchedFlows` had a useEffect with `records` as a dependency, `flows` is passed down to each component via the prop `records`. 
Still, this shouldn't be returning `null` on the filter method we have to update `matchingFlows`. 
So, what I found was that the current method of using …
=> fix: matchingFlows resolving to null during flow actions

editor.planx.uk/src/pages/PlatformAdminPanel/PlatformAdminPanel.tsx, editor.planx.uk/src/pages/layout/AuthenticatedLayout.tsx, editor.planx.uk/src/theme.ts, editor.planx.uk/src/ui/editor/FixedHeightDashboardContainer.tsx, editor.planx.uk/src/ui/shared/DataTable/DataTable.tsx, editor.planx.uk/src/ui/shared/DataTable/components/cellIcons.tsx
Adds styles to MUI data grid:
- Updates border styles to fit with wider editor styles
- Filter toolbar uses `midGray` background, consistent with flow filters
- Extends our bordered focus styles to focused cells
- Extends our button focus styles to buttons
- Unifies icon sizes across buttons
- Aligns boolean cell content (tick/cross) to top, maintaining horizontal line with service title and other text content
- Bumps size of tick/cross icons to increase visibility
- Unifies selected cell highlight colour
- Adjusts padding of container element to maximise canvas area for table
**Before changes:**
**After changes:**
=> style: MUI data grid

editor.planx.uk/src/pages/Teams.tsx, editor.planx.uk/src/ui/shared/SearchBox/SearchBox.tsx
This PR is for the ticket: https://trello.com/c/XOqpIQic/3013-search-teams
It introduces the `SearchBox` component to the `Teams` table which lists out all of the Team a user can edit and view. The search box only applies to teams a user can **view** not teams that they can **edit**.
To fit with the compact UI of the title, I have added a new prop to `SearchBox` so we can hide the label if it doesn't make contextual sense. To help communicate the use of the text box, I have thus added a `Search` icon from material ui. This also sits in the Service list `Team` page.
=> feat: add `SearchBox` to Teams page

editor.planx.uk/src/pages/FlowEditor/components/Settings/Submissions/Submissions.tsx
Ensures the submissions table is wrapped in the appropriate `<FixedHeightDashboardContainer>` so that it can inherit the correct height.
Preview:
https://4387.planx.pizza/testing/submissions-log
=> fix: Submissions table container for height

infrastructure/data/index.ts
This PR contains a very small change to the `infrastructure/data` layer, which will not be applied on merge, but only via manually running `pulumi up`.
The intention here is to test the restoration of the staging RDS postgres database from a manual snapshot (in this case `after-postgres-update-167`, a snapshot I took on 21st Feb after applying bump to postgres version `16.7` from `16.3` - see #4361). 
To ensure this works, once this PR is merged, I will:
- run `pulumi up` on staging from my console
- ensure `editor.planx.dev` accessible and running as expected
- use Hasura to check whether published flow `5015` from 20th Feb exists (it should)
- check whether published flow `5024` from 26th Feb exists (it should not)
- check that we can then run [nightly prod -> staging db …
=> [infrastructure] add snapshot reference to test restoring RDS db

infrastructure/application/Pulumi.staging.yaml, infrastructure/data/Pulumi.staging.yaml
Testing db restoration as per #4392 results in a new db instance name and hence a changed `dbRootUrl` output from the data layer. We need to rotate `db-url` in the application layer so that it points at the new db.
=> [application] rotate db-url

editor.planx.uk/src/pages/FlowEditor/components/Flow/FeedbackLog/FeedbackLog.tsx, editor.planx.uk/src/pages/FlowEditor/components/Settings/Submissions/components/EventsLog.tsx
- Makes first column "Service" text bold
- Refines column widths based on content to make space optimal (can be refined as we continue to use the logs)
**Feedback log before changes:**
**Feedback log after changes:**
**Submissions log before changes:**
**Submissions log after changes:**
=> style: Refine data table column widths based on content

infrastructure/application/Pulumi.staging.yaml
Intended to repair metabase such that it points at the new db, after #4392 went slightly awry.
To see the change, run `pulumi config get db-host` and `pulumi config get mb-db-connection-uri` on `main` and on this branch. The only diff is the name of the db instance in the AWS RDS db endpoint, which is generally of the form `instance.xxxxxx.region.rds.amazonaws.com`.
Imo, in a later PR, we should fix the code such that `db-url` (which is baked into the sharedb and hasura services) and `mb-db-connection-uri` are just composed of other known values, such that we can rotate `db-host` singularly in order to repair all services in the event of a db name change.
For OSL crew, more discussion available [here](https://www.notion.so/opensystemslab/Testing-db-restore-from-snapshot-1a735d469ad18008831 …
=> [application] rotate metabase db host/url

infrastructure/data/index.ts
Intended to guard against the situation where Pulumi deletes a db while instantiating a new one from a snapshot, and we have no way of recovering the state of the former because no final snapshot is taken before deletion!
(as happened yesterday when I was conducting the db restoration tests as per #4392)
Note that this is just us reverting to the default, which is for `skipFinalSnapshot: false` (not sure why we originally decided to switch it to `true`).
Relatedly, also removes the `snapshotIdentifier` input.
If applied via `pulumi up`, would cause the following change (i.e. does not imply any db replacement/deletion or anything like that):
Docs: https://www.pulumi.com/registry/packages/aws/api-docs/rds/instance/#skipfinalsnapshot_nodejs
=> [data] keep final snapshots in case of db deletion

editor.planx.uk/src/pages/FlowEditor/components/Settings/Submissions/components/EventsLog.tsx
Adds "Download" header to final column of submissions log table.
=> fix: Add download column header to submissions log

editor.planx.uk/src/pages/FlowEditor/components/Flow/index.tsx
This PR enhances the `showGetStarted` check to make sure that the `GetStarted` card is only displayed once at the flow root.
| ![image](https://github.com/user-attachments/assets/01da8c2e-f5df-4131-b19d-7e9b29e61094) | <img width="348" alt="image" src="https://github.com/user-attachments/assets/e8898fdb-7dbe-4765-904d-303ff8c96557" /> |
=> fix: Don't display `GetStarted` card in empty internal portals

editor.planx.uk/src/@planx/components/Pay/Public/FeeBreakdown/FeeBreakdown.tsx, editor.planx.uk/src/@planx/components/Pay/Public/FeeBreakdown/useFeeBreakdown.tsx
Airbrake is logging a fee breakdown error for each ITP session. However, as we already fallback to the `inviteToPayFeeBreakdown` passed into the component, the payee is presented with a valid and correct fee breakdown table.
Please see https://opensystemslab.slack.com/archives/C4B0CKQ3U/p1740579357423249 (OSL Slack) for context.
As hooks cannot be called conditionally, this is currently written to check for the presence of the `inviteToPayFeeBreakdown` after the hook is called (and an Airbrake error has been called).
This PR checks the `inviteToPayFeeBreakdown` as part of the hook, meaning that the Airbrake error will not be triggered for ITP payments.
Please try to resume the following ITP payment (devops email address) - https://4423.planx.pizza/buckinghamshire/apply-for-a-lawful-develop …
=> fix: False positive ITP fee breakdown error

editor.planx.uk/src/pages/FlowEditor/components/Flow/FeedbackLog/FeedbackLog.tsx, editor.planx.uk/src/pages/FlowEditor/components/Settings/Submissions/components/EventsLog.tsx, editor.planx.uk/src/ui/shared/DataTable/utils.tsx
- Adds a helper function to standardise datetime outputs - `dateFormatter()`
- Applies this in feedback and submission tables
=> fix: Display timestamps correctly in 24hr format

editor.planx.uk/src/pages/PlatformAdminPanel/PlatformAdminPanel.tsx
Quick one: makes first column (council name) in admin panel bold, consistent with submission and feedback logs.
=> style: Team name in admin panel bold

editor.planx.uk/src/components/Header/Header.tsx, editor.planx.uk/src/theme.ts, editor.planx.uk/src/themeOverrides.d.ts, editor.planx.uk/src/ui/editor/Filter/FilterStyles.ts, editor.planx.uk/src/ui/editor/FlowTag/styles.ts
Tides up and simplifies colour styles.
- Removes unneeded `midGray` background colour
- Removes unneeded `lightOff` colour for `flowTag`
- Update theme to use styles from palette
- Header uses theme background style
=> chore: Tidy up colour styles

editor.planx.uk/src/ui/editor/FlowTag/styles.ts
Across the PlanX editor we use fully rounded (lozenge/chip) styles for tags, flow/service tags should be consistent with this style.
**After change:**
=> style: Rounded flow tags

editor.planx.uk/src/@planx/components/SetValue/utils.test.ts, editor.planx.uk/src/@planx/components/SetValue/utils.ts, editor.planx.uk/src/pages/FlowEditor/lib/__tests__/setValue.test.ts
See `property.type` bugs reported via Jonny https://opensystemslab.slack.com/archives/C01E3AC0C03/p1741172093172059 & https://opensystemslab.slack.com/archives/C01E3AC0C03/p1741171167791389
**What was happening:**
- SetValue appended a value => passport `{ "property.type": ["residential.house.detached"] }`
- SetValue removed one value (not an applicable value) => passport `{ "property.type": "residential.house.detached" }` 
- !! Changed type from array to string !!
- This type change both breaks future automations _and_ causes single letter, rather than first item, to be displayed in "About the property" summary table
- Question/Checklist could not be auto-answered because passport is now string, not array type
Simple fix & test cases cover all possible scenarios now!
This flow is …
=> fix: ensure `SetValue` "removeOne" operation preserves array types

editor.planx.uk/src/pages/FlowEditor/components/Flow/FeedbackLog/FeedbackLog.tsx, editor.planx.uk/src/pages/FlowEditor/components/Flow/FeedbackLog/feedbackFilterOptions.tsx, editor.planx.uk/src/pages/FlowEditor/components/Flow/FeedbackLog/types.ts, editor.planx.uk/src/pages/FlowEditor/components/Flow/FeedbackLog/utils.tsx, editor.planx.uk/src/ui/shared/DataTable/DataTable.tsx, editor.planx.uk/src/ui/shared/DataTable/types.ts
Sets up a `feedbackFilterOptions` file in order to filter by feedback type in the feedback log.
=> feat: Set up filter options for feedback type

e2e/tests/ui-driven/pnpm-lock.yaml
Removed both `ui-driven` & `api-driven` lockfiles and ran `pnpm i` fresh - only this one changed. 
Seeing if this might clear up our CI issue described here :crossed_fingers: https://opensystemslab.slack.com/archives/C01E3AC0C03/p1741337036758429
=> fix: regenerate E2E lock files

editor.planx.uk/src/@planx/components/PlanningConstraints/Modal.tsx
(Reported by August in Slack)
In the modal for contesting constraints the checklist rows do not sit at 100% width this is due to them being placed inside a wrapping `<Grid>` but not being assigned as being `<Grid item>`s, introducing this fixes the issue.
**After change:**
=> fix: Prevent checklists wrapping in constraint overrides

infrastructure/application/Pulumi.staging.yaml, infrastructure/application/index.ts, infrastructure/application/services/hasura.ts, infrastructure/application/types.ts, infrastructure/application/utils/helpers.ts, infrastructure/application/utils/index.ts
Postgres databases are accessed using a URL making use of the `postgres://` protocol, as per [this spec](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING-URIS) (note that [URLs are a subset of URIs](https://medium.com/tuanhdotnet/secrets-of-uris-urls-and-urns-understanding-their-differences-and-uses-b2b791af7323)).
We have one postgres server, hosted on AWS RDS. Connecting to the staging instance via pgAdmin, I can see the databases therein:
Metabase accesses the `metabase` database via a role called `metabase`, while Sharedb and Hasura access the default `postgres` database via the `dbuser` role. As such there are 2 different URLs that need to be baked into the respective images at build time.  We are currently storing these as Pulumi secrets called `db-url` …
=> [application] simplify process for passing correct DB URLs to images

editor.planx.uk/src/@planx/components/PlanningConstraints/Modal.tsx
Reported by August here: https://opensystemslab.slack.com/archives/C01E3AC0C03/p1741597807847749?thread_ts=1741255799.707409&cid=C01E3AC0C03
Currently the constraints override checklist is incorrectly wrapped in a `<label>` which is automatically associated with the first `<input>`, meaning the first input (checkbox) is actioned when clicking anywhere in the element (except other checklist items. Removing the wrapping label and unhiding the repeated `<legend>` rectifies this.
The `<textarea>` "Tell us why" was also not associated with its `<label>` (incorrectly associating with `name` rather than `id` as a ref), I've also fixed this by adding an `id` property.
**Testing:**
https://4447.planx.pizza/lambeth/constraints-test/published?analytics=false
Multiple TPO intersections at SE1 6HZ …
=> fix: Constraints override checklist structure

editor.planx.uk/src/pages/FlowEditor/components/Flow/FeedbackLog/FeedbackLog.tsx, editor.planx.uk/src/pages/FlowEditor/components/Settings/Submissions/components/EventsLog.tsx, editor.planx.uk/src/ui/shared/ErrorSummary/ErrorSummary.tsx
Quick one (nit): styles `ErrorSummary` wrapper for a bit more contrast when tables/logs are empty.
**After change:**
=> style: Empty log notification

editor.planx.uk/package.json, editor.planx.uk/pnpm-lock.yaml
Note that planx-core document templates are still on lastest major version v0.8.3 - a couple thoughts on this:
- This is for internal HTML documents only so build issue problem is low risk
- Migration from v0.8.3 to v1 alphas requires some props refactoring
- We're closer than ever before to just releasing a stable v1 ([see thread](https://opensystemslab.slack.com/archives/C01E3AC0C03/p1741705999017529))
- Let's address the planx-core upgrade in one go as part of this upcoming ticket? https://trello.com/c/hjmIHatD/3215-generate-payload-data-or-documents-from-mapandlabel-components
=> chore: upgrade `@opensystemslab/map@v1.0.0-alpha.5` 

editor.planx.uk/src/pages/FlowEditor/components/Settings/ServiceSettings/FooterLinksAndLegalDisclaimer.tsx, editor.planx.uk/src/pages/FlowEditor/components/Settings/ServiceSettings/index.tsx
- Reorders service settings page so that online/offline status is first
**Example:**
https://4456.planx.pizza/barnet/apply-for-service-declarations/service
=> refactor: Reorder settings page

editor.planx.uk/src/pages/FlowEditor/components/Flow/FeedbackLog/FeedbackLog.tsx, editor.planx.uk/src/pages/FlowEditor/components/Settings/Submissions/components/EventsLog.tsx, editor.planx.uk/src/ui/shared/DataTable/DataTable.tsx, editor.planx.uk/src/ui/shared/DataTable/utils.tsx
- Reintroduces custom filtering (multiselect) for `ARRAY` option in data table (removed here: https://github.com/theopensystemslab/planx-new/pull/4402)
- Makes "type" filter in the feedback log function correctly
Please check filters across the platform admin panel, submissions log and feedback log! This PR should fix the 'live services' filter that was broken by a previous iteration.
=> fix: Table array filtering

api.planx.uk/client/index.ts, api.planx.uk/modules/auth/controller.ts, api.planx.uk/modules/auth/docs.yaml, api.planx.uk/modules/auth/routes.ts, api.planx.uk/modules/auth/service/logout/revokeToken.ts, api.planx.uk/modules/auth/validateJWT.test.ts, docker-compose.yml, hasura.planx.uk/proxy/Caddyfile, hasura.planx.uk/proxy/Dockerfile, infrastructure/application/services/hasura.ts
- Updates Caddy to v2.9.1
- Adds check for auth, if present, redirects to REST API (see logic below)
- Adds a header to show validation status
It might be nice to add a little script / small test suite to cover this in future.
For the following commands, I get a 200 with the `x-auth-validated: true` header on the response -
```sh
curl -v -H "Authorization: Bearer ${VALID_TOKEN_HERE}" https://hasura.4445.planx.pizza
```
```sh
curl -v -b "jwt=${VALID_TOKEN_HERE}" https://hasura.4445.planx.pizza
```
```sh
curl -v "https://hasura.4445.planx.pizza?token=${VALID_TOKEN_HERE}"
```
For the following commands, I get a 401 with the `x-auth-validated: false` header on the response -
```sh
curl -v -H "Authorization: Bearer ${REVOKED_TOKEN_HERE}" https://hasura.4445.planx.pizza
```
```sh
curl -v -b …
```
=> feat: Auth proxy for Hasura

scripts/seed-database/container.sh, scripts/seed-database/write/team_integrations.sql
Removes `power_automate_webhook_url` from data sync scripts
In some specific testing cases, council may have a staging power automate URL. This has happened recently with Doncaster. If this becomes a recurring pattern we can address with with `_staging` and `_production` column as other data values are handled.
=> chore: Don't sync `team_integrations.power_automate_webhook_url`

infrastructure/application/index.ts, infrastructure/networking/index.ts
Follow up to #4473 
This now more correctly mimics the details required via the console. This should allow Hasura to connect directly to the API Fargate service without exiting the VPC and getting blocked by Cloudflare.
Changes to network layer already manually run for staging stack via Pulumi CLI.
=> fix: Setup internal DNS for Fargate (take 2)

infrastructure/application/index.ts
Fixes Pulumi error - 
```
Specify a value for either 'port' or the 'containerName' and 'containerPort' combination, but not both. Remove one and retry.
```
CI failure - https://app.pulumi.com/planx/application/staging/updates/3597
=> fix: Service registry port config

infrastructure/application/index.ts
Fixes latest error - 
```
awsx:x:ecs:FargateService$aws:ecs/service:Service (api)
error: 1 error occurred:
* updating urn:pulumi:staging::application::awsx:x:ecs:FargateService$aws:ecs/service:Service::api: 1 error occurred:
* updating ECS Service: InvalidParameterException: The values specified for serviceRegistries do not require a value for 'containerPort'. Remove the value and retry.
```
=> fix: Drop containerPort [skip pizza]

api.planx.uk/modules/auth/controller.ts, api.planx.uk/modules/auth/validateJWT.test.ts
Currently a request to `/auth/validate-jwt` is bringing down the API.
=> fix(api): Handle missing JWT

editor.planx.uk/src/pages/PlatformAdminPanel/getFlowNamesForFilter.tsx
See https://opensystemslab.slack.com/archives/C088K9ZL8EA/p1742297258994419 && this console error on production admin panel:
**Changes:**
- Councils may have 0 live services now since Silvia's "online"/"offline" message (eg see B&D); these should render an empty cell rather than error
- The `endsWith` within the `filter` here would have actually _removed_ any names with a trailing space, whereas we actually just want to ensure they're included but properly "trimmed" per the comment. We also want to sort _after_ trimming :+1: 
Admin panel loads correctly on this pizza: https://4482.planx.pizza/admin-panel 
Bigger picture question - this was a still a white page error and not more gracefully picked up by our `ErrorBoundary` component, let's keep an eye on that going forward !
=> fix: ensure admin panel correctly formats service names and accounts for 0 live services

editor.planx.uk/src/ui/editor/Filter/Filter.tsx
Loading a team/council page in Safari is failing due to the following error:
`TypeError: searchParams.entries().toArray is not a function. (In 'searchParams.entries().toArray()', 'searchParams.entries().toArray' is undefined)`
Converting to an array using `Array.from()` fixes the issue.
=> fix: Team page loading in Safari

hasura.planx.uk/metadata/tables.yaml, hasura.planx.uk/migrations/1742407557667_alter_table_public_feedback_add_column_editor_comment/down.sql, hasura.planx.uk/migrations/1742407557667_alter_table_public_feedback_add_column_editor_comment/up.sql
- Adds `feedback.editor_notes` column
- Exposes via `feedback_summary` view
- Configures permissions
- To be wired up to UI in https://github.com/theopensystemslab/planx-new/pull/4489
I'm working off the Figma here and unfortunately missed the last design call where this was discussed.
My initial instinct here would have been to have a new `feedback_editor_notes` table, with `user_id`, timestamps etc and a many-to-one relationship to `feedback`. Going off the designs it actually seems that for now a single `notes` column, without this associated metadata, is going to meet our requirements at least in the medium term. Is this a fair summary of the decisions we've made here?
=> feat: Add `feedback.editor_notes` column

editor.planx.uk/src/lib/feedback.ts, editor.planx.uk/src/pages/FlowEditor/components/FeedbackLog/FeedbackLog.stories.tsx, editor.planx.uk/src/pages/FlowEditor/components/FeedbackLog/FeedbackLog.tsx, editor.planx.uk/src/pages/FlowEditor/components/FeedbackLog/mocks/mockFeedback.ts, editor.planx.uk/src/pages/FlowEditor/components/FeedbackLog/mocks/mockFeedback.tsx, editor.planx.uk/src/pages/FlowEditor/components/FeedbackLog/queries/updateEditorNotes.ts, editor.planx.uk/src/routes/feedback.tsx, editor.planx.uk/src/ui/shared/DataTable/DataTable.tsx, editor.planx.uk/src/ui/shared/DataTable/types.ts, hasura.planx.uk/metadata/tables.yaml
- Build on @ianjon3s's UI work in https://github.com/theopensystemslab/planx-new/pull/4489
- Adds `feedback.editor_notes` column
- Updates UI to write to this column
Feedback added to B&D already - https://4495.planx.pizza/barking-and-dagenham
The "Editor notes" column can be edited, and the data will persist.
https://github.com/user-attachments/assets/21efc871-47dc-41eb-a4bd-a406401b7e1f
=> feat(editor): Persist editor notes in feedback log

editor.planx.uk/src/pages/FlowEditor/components/FeedbackLog/components/StatusChip.tsx, editor.planx.uk/src/pages/FlowEditor/components/FeedbackLog/feedbackFilterOptions.tsx, editor.planx.uk/src/pages/FlowEditor/components/FeedbackLog/mocks/mockFeedback.ts, editor.planx.uk/src/pages/FlowEditor/components/FeedbackLog/utils.tsx, editor.planx.uk/src/routes/feedback.tsx, hasura.planx.uk/migrations/1742568175451_run_sql_migration/down.sql, hasura.planx.uk/migrations/1742568175451_run_sql_migration/up.sql
- Updates values for `feedback.status`
- "read" → "actioned"
- "to_follow_up" → "in_progress"
- Please see here for full context (OSL Slack) - https://opensystemslab.slack.com/archives/C5Q59R3HB/p1742552488002169
Once these PRs have merged to production, I'll manually run the SQL to set the status of all existing feedback to "actioned".
=> chore: Update values for `feedback_status_enum`

editor.planx.uk/src/pages/FlowEditor/components/FeedbackLog/FeedbackLog.tsx, editor.planx.uk/src/pages/FlowEditor/components/Submissions/components/EventsLog.tsx, editor.planx.uk/src/ui/shared/DataTable/DataTable.stories.tsx, editor.planx.uk/src/ui/shared/DataTable/DataTable.tsx, editor.planx.uk/src/ui/shared/DataTable/components/MultipleOptionSelectFilter.tsx, editor.planx.uk/src/ui/shared/DataTable/types.ts, editor.planx.uk/src/ui/shared/DataTable/utils.tsx
Whilst working on #4492 I realised that the `singleSelect` behaviour wasn't working as expected. This is due to changes made in https://github.com/theopensystemslab/planx-new/pull/4453. This is currently using a "contains" instead of an equals match which lead to filter options with "read" being a substring of "unread".
> [!IMPORTANT]
> If there's context from the week I was away or #4453 that I'm missing (i.e. another example of broken filtering?) please let me know!
Here's my understanding of the data model, and how I've managed this in this PR - 
**Single select**
This is a native MUI datagrid column type. It's used for enums (strings) and changes filters to is/is not/is any of.
By setting a column to have a type of `singleSelect`, we get this behaviour out of the box.
**Array**
This …
=> fix: Filterable single selects in data grid

editor.planx.uk/src/pages/FlowEditor/components/Sidebar/Publish/PublishDialog.tsx
Builds on @jessicamcinchak 's publishing modal work here: https://github.com/theopensystemslab/planx-new/pull/4446
- Sets publishing modal to be full height regardless of content
- Fixes actions to bottom of modal
- Sets internal content to scroll (with appropriate padding for actions overlap)
- Positions action buttons at either side of modal (seems to work well for the next/back behaviour)
=> style: Fixed height and scroll for publishing modal

editor.planx.uk/src/pages/FlowEditor/components/FeedbackLog/FeedbackLog.tsx, editor.planx.uk/src/pages/FlowEditor/components/FeedbackLog/utils.tsx
- Addresses outstanding "TODO" comments on `FeedbackLog`
- Allows filtering by rating, node type, and help text (see code for more details on some caveats here)
- Relies on https://github.com/theopensystemslab/planx-new/pull/4496
=> feat: Filter `FeedbackLog` by rating, node type/title, and help text

api.planx.uk/modules/auth/controller.ts, api.planx.uk/modules/auth/validateJWT.test.ts, infrastructure/application/cloudflare/snippets/README.md, infrastructure/application/cloudflare/snippets/validate_jwt.js
- Documents our Cloudflare snippet setup which handles additional Hasura auth (checking for block-listed token)
- This replaces the approach originally implemented in #4445 
- Updates the JWT endpoint to also verify JWTs (required for upcoming ShareDB PR, makes more sense to check all in one place)
For more details, please see included README.md
- Handle Hasura console
- Requests made via the console will fail if you're logged out of PlanX
- Checking for origin or referer headers is insecure as these headers can be spoofed (thus bypassing the revoked token check)
- Is it an issue that we need to be logged into PlanX for this to work?
- Add back the logic for `x-auth-validated` header as a breadcrumb
The same applies here as did in #4445 (currently minus the headers). It breaks down to -
- …
=> feat: Hasura auth proxy using Cloudflare snippets

hasura.planx.uk/metadata/tables.yaml
I encountered a logical error in our permission setup for the "move flow" operation when working on the feature to restrict who can copy flow ([Trello ticket](https://trello.com/c/91QhXdFy/3156-permissions-editors-can-decide-which-flows-are-copiable-by-others-and-which-ones-are-not)).
Full details of the issue I hit on this ticket here - https://trello.com/c/91QhXdFy#comment-67e14c99dd37b0322afe8a50
This made me realise that we're checking a user's access to the _current_ team when running the "move flow" operation - not the destination team they're copying into.
It's currently possible on `main` to take the following set of actions via the API - 
- Have a user that is only teamEditor for "Team A"
- Move a copy to "Team B" (which the user does not have access to)
- Move is successful ❌ …
=> fix(permissions): Use post-update check for `flow.team_id` column

api.planx.uk/modules/auth/controller.ts, api.planx.uk/modules/auth/validateJWT.test.ts, docker-compose.yml, infrastructure/application/index.ts, sharedb.planx.uk/package.json, sharedb.planx.uk/pnpm-lock.yaml, sharedb.planx.uk/server.js
- Removes responsibility on ShareDB to verify JWT, and hands this over to the REST API
- This endpoint both validates the JWT and checks for block-listed tokens
- It also now returns the decoded JWT as ShareDB needs the user ID to write operations to Postgres
- Replaces https://github.com/theopensystemslab/planx-new/pull/4467
We could simplify things here further and rely entirely on the same CF snippet used for Hasura auth here, but that would mean that ShareDB would be unsecured locally and on Pizzas. Not really a risk, but maybe just a bad practice and it would make the gap between Pizzas and staging/prod a little too large? I think that keeping visibility of this auth step, as in this PR, seems the pragmatic approach.
=> feat(sharedb): Hand auth responsibility over to `/auth/validate-jwt` endpoint

editor.planx.uk/src/ui/editor/ListManager/ListManager.tsx
Updates styling of the list manager "insert" function:
- Keep the "add" symbol visible but simplify to a plus symbol to reduce visual noise
- Instinctively it feels like the left-side drag column should be kept free of any other interactions as it interacts in a vertical sense, so move the add icon to the right-side, so it sits with remove
Testing:
https://4512.planx.pizza/testing/long-checklist
=> style: List manager add row style update

editor.planx.uk/src/components/EditorNavMenu/EditorNavMenu.tsx, editor.planx.uk/src/components/EditorNavMenu/styles.tsx
Quick one:
- Updates editor menu icon/text alignment to accommodate multiple lines of text
- Removes redundant imports
Before (left) vs after (right):
=> style: Menu icon alignment

editor.planx.uk/src/@planx/components/FileUploadAndLabel/Editor.tsx
Removes the `Divider` element between `FileUploadAndLabel` items, in favour of whitespace. This is now updated as we have the "hover" interaction to insert new items.
There's maybe an argument that this could be managed by something like a `density` prop into the `ListManager` to make this more generic. Something to think about if we need to do this again!
| State | Before | After |
| No hover |![image](https://github.com/user-attachments/assets/d9b6e83e-9449-4aee-b040-9e1c28b5c022)|![image](https://github.com/user-attachments/assets/2b37d4f8-ffa8-42e7-bacf-2280959a8e11)|
| Hover |![image](https://github.com/user-attachments/assets/2a509dc9-5141-43e7-8ab7-a3633557ec60)|![image](https://github.com/user-attachments/assets/1ef41141-c509-43cf-9424-c8fc2f0f0fe1)|
=> fix: Remove `FileUploadAndLabel` divider

editor.planx.uk/package.json, editor.planx.uk/pnpm-lock.yaml, editor.planx.uk/src/@planx/components/Pay/Editor/Editor.test.tsx, editor.planx.uk/src/ui/editor/ListManager/ListManager.tsx
- Wraps ListManager items in a `TransitionGroup` ([docs](https://mui.com/material-ui/transitions/?srsltid=AfmBOop3o4bTsmlAoTgIOOUVIe6M1j3v_MQCXpB1eE9J301tFhhmMvOO#transitiongroup))
- Adds unique keys to each item, and a `Collapse` transition (other ideas welcome!)
https://github.com/user-attachments/assets/9197ea70-089f-4849-8d22-afea78708c84
=> feat: Transitions for `ListManager` items

editor.planx.uk/package.json, editor.planx.uk/pnpm-lock.yaml, editor.planx.uk/src/@planx/components/PlanningConstraints/List.tsx, editor.planx.uk/types.d.ts
Trying to narrow down this intermittent build issue - I believe it's actually caused by `cheerio` in planx-core.
When looking into `htmlparser2` (`pnpm why htmlparser2`) I realised we're using the library `react-html-parser` for a single use case when we already have the `ReactMarkdownOrHTML` component used elsewhere.
Removing for simplicity and to remove a variable in identifying this build issue.
=> chore: Remove react-html-parser

hasura.planx.uk/migrations/1742391756805_alter_table_public_feedback_alter_column_status/up.sql, hasura.planx.uk/migrations/1743425387530_squashed/down.sql, hasura.planx.uk/migrations/1743425387530_squashed/up.sql
Please see https://opensystemslab.slack.com/archives/C027383TRB6/p1743418344921479 (OSL Slack) for context.
Previously these migrations only worked (locally and on staging) as there were no existing `feedback` records.
This change - 
- Removes the initial "not null" constraint from a historic migration
- This is failing on production, so not yet run. On staging I'll manually drop this constraint when the PR is approved
- Populates the column, and then sets the "not null" constraint
=> fix: Handle default values for existing feedback records

editor.planx.uk/src/pages/PlatformAdminPanel/PlatformAdminPanel.tsx
Small thing I noticed whilst working on #4534
|<img width="951" alt="image" src="https://github.com/user-attachments/assets/9851e93e-30bc-4366-a436-36e6f6b7d709" />|<img width="889" alt="image" src="https://github.com/user-attachments/assets/210e3dec-ff4e-4171-9695-8bdeabec8503" />|
=> feat: Filter admin panel by team name

editor.planx.uk/src/pages/FlowEditor/lib/store/editor.ts, editor.planx.uk/src/types.ts, hasura.planx.uk/migrations/1743429247515_run_sql_migration/down.sql, hasura.planx.uk/migrations/1743429247515_run_sql_migration/up.sql
Two small fixes to the `teams_summary` view - 
- Handle new teams, without any flows
- Exclude deleted flows from the view
Also, this sets flows to "offline" when archived.
**To test (on Pizza)**
- Teams without online flows (e.g. Barking & Dagenham) are listed in admin panel
- Archived flows (e.g. Camden's “Spatial data component bundle”) is not listed in admin panel
=> fix: Handle additional edge cases in `teams_summary` view

editor.planx.uk/src/@planx/components/PropertyInformation/Public.tsx
The Property information component was missing help text rendering on public.
=> fix: add help text to property information

e2e/tests/ui-driven/src/create-flow-with-geospatial.spec.ts, e2e/tests/ui-driven/src/create-flow.spec.ts, e2e/tests/ui-driven/src/pages/Editor.ts, editor.planx.uk/src/pages/Team/components/AddFlow/BaseFormSection.tsx, editor.planx.uk/src/pages/Team/components/AddFlow/CreateFromCopyFormSection.tsx, editor.planx.uk/src/pages/Team/components/AddFlow/CreateFromTemplateFormSection.tsx, editor.planx.uk/src/pages/Team/components/AddFlow/index.tsx, editor.planx.uk/src/pages/Team/components/AddFlow/types.ts, editor.planx.uk/src/pages/Team/index.tsx
- Changes "Add a new service" from a dialog to a modal
- Modal allows flow to be created from new, copy or template
- "copy" and "template" intentionally disabled here
- Updates E2E tests 
**Upcoming PRs**
- Integrate existing template functionality from `StartFromTemplateButton`
- Enable "create from copy..."
- Single dialog style (via MUI theme?)
- https://github.com/theopensystemslab/planx-new/pull/4536
- I'll rebase here once the above is merged
=> feat: Create flow from new, copy, or template

editor.planx.uk/src/routes/index.tsx
Please see https://opensystemslab.slack.com/archives/C088K9ZL8EA/p1743678613301409 (OSL Slack) for context.
This temporary redirect is no longer required.
=> chore: Drop Canterbury FOIYNPP redirect

editor.planx.uk/src/@planx/components/Calculate/Editor.tsx
Adds a validation check to the calculate component, ensuring the component is toggled to 'automate a future question or checklist' if the formula returns a boolean value.
=> feat: add calculate component Boolean validation check

editor.planx.uk/src/pages/Team/components/AddFlow/BaseFormSection.tsx
- Changes incorrect "Service URL" label to more accurate "Editor URL"
- Fixes bug where the URL changes on submit due to `window.location` updating
=> fix: `AddFlow` modal fixes

editor.planx.uk/src/pages/FlowEditor/components/FeedbackLog/components/ExpandableHelpText.tsx, editor.planx.uk/src/theme.ts, editor.planx.uk/src/ui/shared/DataTable/DataTable.tsx
Some small tweaks to the feedback table styling:
- Align row select with content (before vs after)
- Disable row select on click. As we're now using checkboxes to select rows, and also editable cells (editor notes), it's unnecessary to be able to select a row on click
- Remove excess margins from help text (before vs after)
=> style: Tidy feedback table

api.planx.uk/modules/send/email/service.ts
Fixes https://opensystemslab.slack.com/archives/C4B0CKQ3U/p1743778821764219
Introduced in https://github.com/theopensystemslab/planx-new/pull/4540 (`s3_applications` table legitimately has `text` type column for `session_id`, so this was only wrong in one of the two places introduced)
=> fix: correct GraphQL type for `email_applications` table

api.planx.uk/modules/flows/validate/service/fileTypes.ts, api.planx.uk/modules/flows/validate/service/projectTypes.ts, api.planx.uk/modules/flows/validate/validate.test.ts
We've had two recent cases of submissions failing on unsupported `FileType` or `ProjectType` enum values. The validation checks for these are currently set to a "Warning" status rather than "Fail", which makes them very easy to ignore.
Now that passport values auto-suggest in the editor, there's less barrier to making them full failures and easier to discover/fix to use supported values.
=> fix: publish validation checks for schema values should "fail" not "warn"

editor.planx.uk/src/pages/FlowEditor/lib/store/editor.ts
=> fix: Use enum, not string, for `flow.status` value

editor.planx.uk/src/@planx/components/Pay/Public/FeeBreakdown/FeeBreakdown.tsx
Quick one: spotted in Storybook, the fee breakdown table uses the system text colour `GrayText` which does not give adequate contrast for WCAG AA. I've updated to use `palette.text.secondary` which bumps the contrast to a passing level.
`GrayText` (left) vs `text.secondary` (right):
There are several uses of text colour `GrayText` also in the editor that I'll pick up as a separate PR.
=> fix: Fee breakdown table text contrast

doc/how-to/how-to-upgrade-nodejs.md
This PR adds details on how to upgrade the Node runtime version used by our AWS Lambda Scanii application.
=> docs: Add AWS Lambda to Node upgrade docs

editor.planx.uk/src/@planx/components/Confirmation/Confirmation.stories.tsx, editor.planx.uk/src/@planx/components/Confirmation/Editor.tsx, editor.planx.uk/src/@planx/components/Confirmation/Public.test.tsx, editor.planx.uk/src/@planx/components/Confirmation/Public.tsx, editor.planx.uk/src/@planx/components/Confirmation/model.ts, editor.planx.uk/src/pages/FlowEditor/components/Sidebar/Search/mocks/allFacetFlow.ts, editor.planx.uk/src/theme.ts
Issue reported by @augustlindemer in Slack (also reported by council officers):
https://opensystemslab.slack.com/archives/C088K9ZL8EA/p1744024034664429
The background colour was being passed in to the confirmation dialog as an opacity of a solid colour using the alpha value `rgba(1, 99, 96, 0.1)` , I've updated it to be a solid colour (defined unused theme variable palette.success.light). Interestingly VSCode previews this as a dark colour based on the rgb values alone, could be that this was causing `getContrastTextColor` to do the same, albeit intermittently. Either way we should use solid colours wherever possible.
Also, the colour values (bg + text) were being passed into the confirmation dialog as `initialValues`, presumably because we had intended this component to be …
=> fix: Confirmation banner link colour

editor.planx.uk/src/pages/FlowEditor/components/Sidebar/Search/ExternalPortalList/ExternalPortals.tsx, editor.planx.uk/src/pages/FlowEditor/components/Sidebar/Search/ExternalPortalList/styles.ts, editor.planx.uk/src/pages/FlowEditor/components/Sidebar/Search/SearchHeader.tsx, editor.planx.uk/src/pages/FlowEditor/components/Sidebar/Search/SearchResultCard/index.tsx, editor.planx.uk/src/pages/FlowEditor/components/Sidebar/Search/index.tsx
- As the search tab is a form input it should have a `paper` background to be consistent with other forms in the editor
- Also disables ripple on result cards
**Before (left) vs after (right):**
=> style: Form styling for search tab

editor.planx.uk/src/@planx/components/FileUploadAndLabel/Modal.tsx, editor.planx.uk/src/@planx/components/PlanningConstraints/Modal.tsx, editor.planx.uk/src/components/ConfirmationDialog.tsx, editor.planx.uk/src/pages/FlowEditor/components/Team/components/RemoveUserModal.tsx, editor.planx.uk/src/pages/FlowEditor/components/Team/components/UserUpsertModal.tsx, editor.planx.uk/src/pages/FlowEditor/components/Team/styles.ts, editor.planx.uk/src/pages/Team/components/AddFlow/index.tsx, editor.planx.uk/src/theme.ts
- Moves repeated (and inconsistent) dialog styles to the MUI theme, and from a number of custom components
- To use this in future, we just need to import the MUI `Dialog` directly, and it will already have the PlanX theme attached
There's a few minor changes below, all pretty minor.
| Component | Before | After |
| `FileUploadAndLabel` |<img width="619" alt="image" src="https://github.com/user-attachments/assets/85979636-c105-4246-b926-7cb9e86ba3da" />|<img width="655" alt="image" src="https://github.com/user-attachments/assets/8714eb2b-76b4-4fda-b60e-3441b3f7d0f7" />|
| `PlanningConstraints` |<img width="627" alt="image" src="https://github.com/user-attachments/assets/5e0b68b7-04da-44fb-8c65-e43db3986011" />|<img width="619" alt="image" …
=> chore: Move dialog styling to MUI theme

editor.planx.uk/src/pages/FlowEditor/lib/store/editor.ts, editor.planx.uk/src/pages/Team/components/FlowCard.tsx
- Give user feedback (via a toast message) on success or failure of the "Archive" operation
- Recently raised as a suggestion via ODP Slack
In future, it would be nice to apply this pattern more broadly (e.g. to copy and move) and have a better structure in place for this than a few try/catch blocks.
=> chore: Error handling for archiving flows

editor.planx.uk/src/pages/FlowEditor/components/Sidebar/Publish/AlteredExternalPortals.tsx, editor.planx.uk/src/pages/FlowEditor/components/Sidebar/Publish/PublishDialog.tsx
Fixes styles in publishing dialog:
- Steps (before vs after)
- Focus state for portals (before vs after)
=> fix: Publish dialog styles

editor.planx.uk/src/@planx/components/SetFee/Editor.tsx
Follows on from #4312; because `SetFee` is a new component I didn't quite catch this correctly as a rebase on my original PR !
=> fix: ensure `SetFee` editor switches and inputs are disabled based on role

editor.planx.uk/src/pages/FlowEditor/lib/store/team.ts, editor.planx.uk/src/pages/Team/components/AddFlow/BaseFormSection.tsx, editor.planx.uk/src/pages/Teams/AddTeamButton.tsx, editor.planx.uk/src/pages/Teams/index.tsx, editor.planx.uk/src/ui/editor/URLPrefix.tsx
- Opens a modal when creating a team
- Allows the `isTrial` property to be toggled
- All additional team settings etc can be configured in the existing team settings interface
=> feat: Create team modal

editor.planx.uk/src/pages/FlowEditor/components/Settings/ServiceSettings/FlowStatus/index.tsx, editor.planx.uk/src/pages/FlowEditor/lib/store/settings.ts, hasura.planx.uk/metadata/tables.yaml
- Disable online/offline toggle for trial team
- Adds a basic warning / explanation
- Configures Hasura permissions so that a flow cannot be in "online" status whilst it's parent team is in "trial" mode.
=> feat: Disable online/offline toggle for trial teams

editor.planx.uk/src/pages/FlowEditor/components/Settings/GeneralSettings/TrialAccountForm.tsx, editor.planx.uk/src/pages/FlowEditor/components/Settings/GeneralSettings/index.tsx
- Adds form section (for platformAdmins only) allowing the team's "trial" status to be toggled in team settings
- Relies on `planx-core` changes and type updates in https://github.com/theopensystemslab/planx-new/pull/4577
=> feat: Toggle trial account status in team settings

editor.planx.uk/src/pages/FlowEditor/components/Settings/GeneralSettings/TrialAccountForm.tsx, editor.planx.uk/src/pages/FlowEditor/components/Settings/ServiceSettings/FlowStatus/index.tsx, editor.planx.uk/src/pages/Teams/AddTeamButton.tsx
- Fixes typos
- Standardises term to "trial account"
- Please see https://docs.google.com/document/d/1PUrPEmHg2Pp7vc_IfAQrIxMCq8lJ4sYskp77KHZAW1w/edit?tab=t.0 for reference
=> fix: Update text and typos for trial account text

api.planx.uk/package.json, api.planx.uk/pnpm-lock.yaml, e2e/tests/api-driven/package.json, e2e/tests/api-driven/pnpm-lock.yaml, e2e/tests/ui-driven/package.json, e2e/tests/ui-driven/pnpm-lock.yaml, editor.planx.uk/package.json, editor.planx.uk/pnpm-lock.yaml, editor.planx.uk/src/pages/FlowEditor/components/Settings/GeneralSettings/TrialAccountForm.tsx, editor.planx.uk/src/pages/FlowEditor/lib/store/team.ts
- Fixes cache issue with Zustand store so `teamSettings.isTrial` is correctly persisted
- Toggle all flows offline for a team when setting `team_settings.is_trial = true`
- Relies on https://github.com/theopensystemslab/planx-core/pull/712
=> fix: Trial account caching, toggling flows offline

editor.planx.uk/src/pages/Team/components/AddFlow/index.tsx, editor.planx.uk/src/pages/Team/index.tsx, editor.planx.uk/src/pages/Teams/index.tsx, editor.planx.uk/src/routes/authenticated.tsx, editor.planx.uk/src/ui/editor/InfoChip.tsx
- Adds chip to team card
- Adds chip to services page
- Fixes query types
Note: #4588 fixes some caching / data management issues which are present here (chips will persist on this Pizza when status is toggles, will be fixed when previous PR merged).
=> feat: Trial account UI

editor.planx.uk/src/lib/graphql.ts, editor.planx.uk/src/pages/FlowEditor/lib/sharedb.ts, editor.planx.uk/src/pages/FlowEditor/lib/store/editor.ts, sharedb.planx.uk/server.js
- Addresses issues raised a few times recently where ShareDB is silently failing, notably in this thread - https://opensystemslab.slack.com/archives/C01E3AC0C03/p1744706505311059(OSL Slack)
- Fixes bug with ShareDB auth checking
- Improves error messages and error handling in frontend
- Ensure WS client is only instantiated when required. This currently this happens on all public services! (see video below)
https://github.com/user-attachments/assets/1d1046e7-af15-4524-b969-5e078d4ae17e
I'm not totally convinced that this resolves the issues we're facing here - if this was the issue faced by Jonny (silent ShareDB error due to invalid token) I would have still expected Apollo to recognise this and trigger a logout.
At a minimum this PR rules some issues out and should give better visibility …
=> fix(sharedb): Improved error handling

.github/workflows/pizza-teardown-manual.yml, .github/workflows/pizza-teardown.yml, .github/workflows/pull-request.yml
Bumps `vultr-action` used in Github Actions to latest (v2.1). See PR #[3](https://github.com/theopensystemslab/vultr-action/pull/3).
=> chore: bump vultr-action

api.planx.uk/package.json, api.planx.uk/pnpm-lock.yaml, hasura.planx.uk/tests/package.json, hasura.planx.uk/tests/pnpm-lock.yaml
Resolves the following long-running dependabot issues - 
- https://github.com/theopensystemslab/planx-new/security/dependabot/195
- https://github.com/theopensystemslab/planx-new/security/dependabot/196
- https://github.com/theopensystemslab/planx-new/security/dependabot/199
- https://github.com/theopensystemslab/planx-new/security/dependabot/200
- https://github.com/theopensystemslab/planx-new/security/dependabot/202
- https://github.com/theopensystemslab/planx-new/security/dependabot/203
- https://github.com/theopensystemslab/planx-new/security/dependabot/205
- https://github.com/theopensystemslab/planx-new/security/dependabot/206
I'd been waiting for a vitest version to included an updated version of vite, but it's still at 6.2.0.
It turns out it's not an issue to just specify a higher …
=> chore(api & hasura/tests): Bump vitest, specify vite version

api.planx.uk/package.json, api.planx.uk/pnpm-lock.yaml
Fixes https://github.com/theopensystemslab/planx-new/security/dependabot/208 and https://github.com/theopensystemslab/planx-new/security/dependabot/209
=> chore: Bump `http-proxy-middleware`

.github/workflows/pizza-teardown.yml
Follow up to #4606 
The most recent action failed, as it needs to write a comment to the PR once it's associated Pizza has been torn down - https://github.com/theopensystemslab/planx-new/actions/runs/14618215456
=> fix: Allow Pizza teardown GHA to write comment to PR

editor.planx.uk/src/pages/FlowEditor/components/FeedbackLog/FeedbackLog.tsx, editor.planx.uk/src/pages/FlowEditor/components/FeedbackLog/types.ts, editor.planx.uk/src/pages/FlowEditor/components/Submissions/Submissions.tsx, editor.planx.uk/src/pages/FlowEditor/components/Submissions/components/EventsLog.tsx, editor.planx.uk/src/routes/serviceFeedback.tsx
Came up today here: https://opendigitalplanning.slack.com/archives/C01AD3YPZ24/p1745405987128419
Both subheader descriptions updated to include timeline of included data and use consistent wording for service/team context.
**After (team level):**
=> chore: update Submisison & Feedback page copy in editor

editor.planx.uk/src/@planx/components/Review/Editor.tsx, editor.planx.uk/src/@planx/components/Review/Public/Presentational.tsx, editor.planx.uk/src/@planx/components/Review/Public/Public.test.tsx, editor.planx.uk/src/@planx/components/Review/Public/index.tsx, editor.planx.uk/src/@planx/components/Review/Review.stories.tsx, editor.planx.uk/src/@planx/components/Review/model.ts, editor.planx.uk/src/@planx/components/shared/Preview/SummaryList.tsx
Adds a customisable disclaimer to the Review component. 
First commit adds a rich text input _Disclaimer_ section to the editor modal, with default content.
Second commit adds a somewhat sketchy approach using the standard library method 'find' to (inefficiently) search for the Review component by node type and retrieve its disclaimer. I can't see anything else using this approach, so presumably there are cleaner and more efficient ways of retrieving the data of the Review component.
Unfortunately any of my attempts to retrieve the disclaimer through props defaulted to the default content. I'd much appreciate suggestions!
=> feat: add customisable disclaimer to the Review component

editor.planx.uk/src/@planx/components/shared/Schema/InputFields/NumberFieldInput.tsx
This PR replaces the generic Box container in the NumberFieldInput for List and Page component schemas with InputRow styling to ensure consistency with the NumberInput component (in particular, units prop margin). 
Alternatively we could add additional styling to the Box container, not sure if this is a preferable solution @DafyddLlyr?
=> fix: align list and page number input styling with number input component

api.planx.uk/modules/send/uniform/uniform.ts
We've received a second LDC Listed Building Works type! 
Unfortunately, these are currently failing at the "attach archive" step, _after_ successfully creating a submission, because the XML mapping fails which leads to errors in the "queue" on the LPA's side. We want to fail earlier to prevent creating an initial submission at all. This is a quick solution !
=> fix: add basic application type error handling to Uniform

editor.planx.uk/src/components/Header/Header.tsx, editor.planx.uk/src/routes/views/flowEditor.tsx
Trello ticket:
https://trello.com/c/Nm29gakJ/3152-clarify-and-simplify-publishing-and-turning-a-service-online-offline
Appends an online/offline chip to the breadcrumbs of a flow when in the flow view (including settings pages):
The chip can be clicked to reach the settings page, where the status can be updated.
**Testing:**
https://4497.planx.pizza/barnet/apply-for-prior-approval
=> feat: Add online status chip to header

api.planx.uk/modules/analytics/metabase/dashboard/findDashboardTemplate.ts, hasura.planx.uk/metadata/tables.yaml
Updates `api` role permissions to include `select` on `flows.analytics_link`. (While testing #4415 on staging I realised that the last step was failing because of this.) 
The RAB template has also been changed since this was written, so the new production ID is updated.
=> fix: dashboard automation 

editor.planx.uk/src/pages/FlowEditor/components/forms/FormModal.tsx
It's not currently possible to clone an internal portal from within the Editor modal (selecting an existing internal portal).
The global `containsMadeLink()` validation function incorrectly assumes that all incoming data will be of type `object`. This is not correct - the `InternalPortal` node can run a "clone" operation instead of submitting data for a new node. See logic here responsible for this -
https://github.com/theopensystemslab/planx-new/blob/main/editor.planx.uk/src/@planx/components/InternalPortal/Editor.tsx#L58-L67
- Fix types, and narrow accordingly
- Longer term, I'm very keen to spend some time tightening up these types to avoid issues like this. If each component had a clear input and output, this could be avoided.
- Also, I think there's likely a few better ways to handle …
=> fix: Validation for internal portal

api.planx.uk/lib/notify/templates/inviteToPay/confirmation-payee.ts, api.planx.uk/lib/notify/templates/sendToEmail/submit-application.ts, api.planx.uk/modules/send/email/index.test.ts, api.planx.uk/modules/send/email/index.ts, api.planx.uk/modules/send/email/service.ts
- Fetches and formats additional data required for updated "submit" email
- Points to new template in GovNotify ([link](https://www.notifications.service.gov.uk/services/012e65af-0eb2-45d5-87bd-4248354c4c22/templates/2c61750b-3ecc-4726-9ee2-e67fd523954f))
- Once merged to prod, I'll delete old template and remove the `(copy)` suffix in the GovNotiy name
=> feat: Populate additional "submit" template fields

api.planx.uk/package.json, api.planx.uk/pnpm-lock.yaml, e2e/tests/api-driven/package.json, e2e/tests/api-driven/pnpm-lock.yaml, e2e/tests/ui-driven/package.json, e2e/tests/ui-driven/pnpm-lock.yaml, editor.planx.uk/package.json, editor.planx.uk/pnpm-lock.yaml
Latest schema release, `battlefield` added to Planning Constraints (confirm displays in modal on pizza), plus dependabot updates
BOPS already on standby for staging tests once this is merged to `main` https://opendigitalplanning.slack.com/archives/C0182MVK4AW/p1745391633604419
E2E tests were originally failing on ["code check" step of CI here](https://github.com/theopensystemslab/planx-new/actions/runs/14726642904/job/41332809032?pr=4624), which appears related to this package bump https://github.com/theopensystemslab/planx-core/pull/720. Trying to additionally upgrade `graphql` to `16.11.0` throughout planx-new as well to see if it clears up.
=> chore: bump planx-core (ODP Schema v0.7.4)

editor.planx.uk/src/@planx/components/shared/Preview/SummaryList.tsx, editor.planx.uk/src/@planx/components/shared/Schema/InputFields/ChecklistFieldInput.tsx
A nicer fix / follow-up to #4622 ! 
We already have an existing helper function `formatSchemaDisplayValue` which is used for active > inactive `List` cards
**Latest**
=> fix: format data values as text for `Page` components on `Review` page

api.planx.uk/modules/auth/controller.ts, api.planx.uk/modules/auth/routes.ts
Follow up to https://github.com/theopensystemslab/planx-new/pull/4632
This will cache responses for 1 minute, which feels like an acceptable limit whilst getting to the bottom of the issues here. Once we resolve the underlying issue, we could revert this.
=> chore: Cache validate-jwt requests for 1 minute

api.planx.uk/package.json, api.planx.uk/pnpm-lock.yaml
Addresses https://github.com/theopensystemslab/planx-new/security/dependabot/214
PNPM override can be removed once https://github.com/ladjs/superagent/pull/1832/files is merged and supertest updated.
=> chore: CVE-2025-46653

editor.planx.uk/src/components/Footer/Footer.tsx, editor.planx.uk/src/pages/FlowEditor/lib/store/editor.ts
Noticed this when checking out the a11y test flow - we don't fetch a `lastPublishedDate` for non published routes. The type has this as `string` and sets a default of `""` when `string | undefined` is more accurate.
=> fix: Hide last published data on non-published routes

editor.planx.uk/src/@planx/components/List/Editor.tsx, editor.planx.uk/src/@planx/components/List/schemas/Trees.ts
Adds the sketch plan (TPO) schema back into the list component, for the purposes of testing with DAC.
Testing:
https://4638.planx.pizza/testing/list-map-schema
=> feat: Add sketch plan schema to list component

editor.planx.uk/src/pages/FlowEditor/components/Settings/GeneralSettings/BoundaryForm.tsx, editor.planx.uk/src/pages/FlowEditor/components/Settings/shared/SettingsForm.tsx, editor.planx.uk/src/ui/editor/InputGroup.tsx
- Updates copy in the `BoundaryForm` component to explain (and show) the bounding box used within PlanX
- For Tewkesbury shows information about their SLP, disables and removes form
Please note: there's an existing issue with displaying OS vector tiles on Pizzas unrelated to the changes made here.
Originally, I went for something like this - https://github.com/theopensystemslab/planx-new/commit/b49cea73a61fcb2636832e296540bcf0996c1dbc
This fetched existing `boundary_bbox` values and merged them if within the SLP. However, this would need to be done each time - for every visitor, for every instance of the map. The boundary is effectively static and can be held within the database.
I've ran the following SQL on the Pizza, and I'd proposed to run it (manually) on staging and production.
This …
=> feat: Track Gloucester, Cheltenham & Tewkesbury SLP in database, display boundary in Team Settings

editor.planx.uk/src/@planx/components/Send/Public.tsx, hasura.planx.uk/migrations/1746110962912_add_useragent_referrer_to_submission_services_summary/down.sql, hasura.planx.uk/migrations/1746110962912_add_useragent_referrer_to_submission_services_summary/up.sql
Thanks Jess for the pointers!!
This is a new version of #4631 because I got myself into a migrations pickle and had to open a new branch. Please see earlier conversation for context. 
When I test locally, I'm still getting some unexpected `NULL`s in Hasura. Can't quite figure out where I'm going wrong!
Certain values populate correctly in `analytics_summary` (but not all, eg `flow_direction` is also `NULL`)
Same is happening in `submission_services_summary`; certain values populate but not all (eg the submission date, etc.)
- Creates a new migration to show `userAgent` properties (`os`, `browser`, `platform`) as well as `referrer` in submission_services_summary table
- In the Send component, saves `userAgent` and `referrer` and passes them to `handleSubmit`
M&E want to be able to break …
=> feat: show `userAgent` and `referrer` in `submission_services_summary` through allow list

editor.planx.uk/src/pages/FlowEditor/lib/store/editor.ts, editor.planx.uk/src/pages/Team/components/FlowCard.tsx, editor.planx.uk/src/pages/Team/helpers/sortAndFilterOptions.ts, editor.planx.uk/src/ui/editor/FlowTag/styles.ts, editor.planx.uk/src/ui/editor/FlowTag/types.ts
- Adds a "Template" chip
- Adds a "Template" filter option
- Both behind the `TEMPLATES` feature flag still
https://github.com/user-attachments/assets/5fc4a9a5-9335-4df8-946a-26001df14aaa
=> feat: Chip and filter options for template flows

editor.planx.uk/src/components/AnalyticsDisabled/AnalyticsDisabledBanner.tsx, editor.planx.uk/src/components/EditorNavMenu/styles.tsx, editor.planx.uk/src/components/Feedback/FeedbackPhaseBanner.tsx, editor.planx.uk/src/pages/FlowEditor/index.tsx, editor.planx.uk/src/ui/shared/WatermarkBackground.tsx
Fixes two issues:
The `max-height` was previously variable depending on the presence of a testing banner, it was incorrectly removed entirely as part of the watermark PR.
Before: https://editor.planx.dev/barnet/apply-for-a-lawful-development-certificate
After: https://4658.planx.pizza/barnet/apply-for-a-lawful-development-certificate
As the watermark was positioned `absolute` with a finite size, on longer screens the watermark does not cover the entire canvas. An alternative option would be to make the watermark respond to page size, however this would mean the text is inconsistently size and would cause some unwanted layout-shift behaviour when interacting with elements that change the screen size (i.e. accordions). Keeping the watermark positioned `fixed` means a consistent view across …
=> fix: Watermark position and editor overflow scroll

editor.planx.uk/src/@planx/components/shared/Preview/MoreInfo.tsx
Addresses two issues:
This was caused by adding a `z-index` css property to containers.
Ensures there is a `<h1>` present with the title: "More information"
Before: https://editor.planx.dev/testing/help-text/preview
After: https://4659.planx.pizza/testing/help-text/preview
=> fix(a11y): Close button and h1 for help text modal

api.planx.uk/package.json, api.planx.uk/pnpm-lock.yaml, api.planx.uk/tests/mocks/inviteToPayMocks.ts, e2e/tests/api-driven/package.json, e2e/tests/api-driven/pnpm-lock.yaml, e2e/tests/ui-driven/package.json, e2e/tests/ui-driven/pnpm-lock.yaml, editor.planx.uk/package.json, editor.planx.uk/pnpm-lock.yaml
Relies on https://github.com/theopensystemslab/planx-core/pull/727
See bug report https://opensystemslab.slack.com/archives/C07F7215W7P/p1746545457127259?thread_ts=1746524633.032529&cid=C07F7215W7P
**For the given passport:**
**`getFeeBreakdown` before:**
Incorrectly setting calculated = payable if calculated = 0 and payable > 0
**`getFeeBreakdown` after:**
Preserves original calculated and "Application fee" row correctly shows 0
=> fix: preserve calculated fee = 0 in breakdowns

editor.planx.uk/src/pages/Team/components/CopyDialog.tsx
Based on feedback by @augustlindemer - 
> _for any flow currently with a trailing whitespace, when the copy dialogue appends  (copy) it does so without trimming the whitespace first, so it creates a flow with two whitespaces before the (copy)._
| ![image](https://github.com/user-attachments/assets/43e80e11-e091-4e6c-a13e-5bb6a25af969) | ![image](https://github.com/user-attachments/assets/0afa2343-9531-4982-b578-b4a2054d7518) |
=> fix: Trim flow name before adding ' (copy)' suffix

api.planx.uk/helpers.ts, api.planx.uk/modules/flows/copyFlow/service.ts, api.planx.uk/modules/flows/createFlow/controller.ts, api.planx.uk/modules/flows/createFlowFromTemplate/service.ts, api.planx.uk/modules/flows/docs.yaml, editor.planx.uk/src/pages/FlowEditor/lib/store/editor.ts, editor.planx.uk/src/pages/Team/components/AddFlow/BaseFormSection.tsx, editor.planx.uk/src/pages/Team/components/AddFlow/index.tsx, editor.planx.uk/src/pages/Team/components/AddFlow/types.ts, editor.planx.uk/src/pages/Team/components/FlowCard.tsx, editor.planx.uk/src/ui/editor/FlowTag/styles.ts, editor.planx.uk/src/ui/editor/FlowTag/types.ts, hasura.planx.uk/metadata/tables.yaml
- Adds a "source template" toggle to the create flow modal (platform admins only)
- Updates API to accept this new argument, refactors `createFlow()` to take a single options argument
- Adds temporary "Source Template" tag to `FlowCard`
- This will be replaced by a styled card, but serves as a visual cue for now and sorts out the data needed for this restyle
- Please see https://github.com/theopensystemslab/planx-new/pull/4651#discussion_r2075513134
=> feat: Create source template

api.planx.uk/package.json, api.planx.uk/pnpm-lock.yaml, e2e/tests/api-driven/package.json, e2e/tests/api-driven/pnpm-lock.yaml, e2e/tests/ui-driven/package.json, e2e/tests/ui-driven/pnpm-lock.yaml, e2e/tests/ui-driven/src/invite-to-pay/mocks.ts, editor.planx.uk/package.json, editor.planx.uk/pnpm-lock.yaml, editor.planx.uk/src/@planx/components/Pay/Public/FeeBreakdown/FeeBreakdown.tsx
Relies on https://github.com/theopensystemslab/planx-core/pull/729
See this thread https://opensystemslab.slack.com/archives/C07F7215W7P/p1746524633032529
**Testing:** 
Compare journeys outlined below between https://editor.planx.uk/testing/set-fee-demo and same flow on this pizza
1. 0 intial application fee > Sports reduction > any Fast Track
- Breakdown should display "Application fee" = 0
- Reduction is displayed & labeled "Modification" with amount = 578
- Payable is correct
2. 200 initial application fee > Disabilty exemption (0 off) > any Fast Track
- Breakdown should display "Application fee" = 200
- Exemption is displayed with amount = 0
- Payable is correct
Finally, confirm no visual regressions on existing Storybook scenarios between prod and this pizza …
=> fix: fee breakdown should account for non-100% exemptions

editor.planx.uk/src/@planx/components/Calculate/model.test.ts, editor.planx.uk/src/@planx/components/Calculate/model.ts
See thread https://opensystemslab.slack.com/archives/C07F7215W7P/p1746708641958439?thread_ts=1746524633.032529&cid=C07F7215W7P
**To test:** 
- Compare same flow on this pizza to production flow https://editor.planx.uk/testing/calculator-defaults
- If you have 0 apples, you should need 0 containers
- Production flow will incorrectly output 3 containers in passport when Calculate has default value of 10 and receives a valid incoming value of 0 apples (default should only be triggered when incoming apples are undefined)
- From what I can tell only impacting passport & `handleSubmit`, not the "Try" section of the editor modal
=> fix: handle incoming value = 0 correctly in Calculate, don't fallback to default value

editor.planx.uk/src/pages/FlowEditor/lib/store/user.ts, editor.planx.uk/src/routes/authenticated.tsx, editor.planx.uk/src/routes/views/authenticated.tsx
There's a race condition between routes loading (and their associated data fetches and renders) and the `UserStore` being initialised. We need the `UserStore` to be initialised for route guards to work, and as `react-navi` sits outside it react rendering hierarchy it doesn't re-render / update when Zustand stores do.
What's happening currently - 
- User loads page
- (Concurrently) Fetch user, load data (e.g. for `/admin-panel`)
- If user is not returned yet, route guard fails
This behaviour is most commonly seen of refreshes and when direct linking to a nested route - simply as the home page does not have a route guard build into `react-navi`. The user request succeeds and is saved to the store before nested, guarded, routes are loaded.
The user store was being incorrectly initialised …
=> fix: Race condition between routes and `initUserStore()`

api.planx.uk/modules/webhooks/controller.ts, api.planx.uk/modules/webhooks/routes.ts, api.planx.uk/modules/webhooks/service/updateTemplatedFlowEdits/index.ts, api.planx.uk/modules/webhooks/service/updateTemplatedFlowEdits/schema.ts, hasura.planx.uk/metadata/tables.yaml
Stubs out a new database event trigger that listens for updates on `flows.data`. If that flow is templated from another, it's going to diff the updated `data` against the source template's `data`, filter out differences to nodes tagged "customisation", then format and save them to `templated_flow_edits` table. This code doesn't actually do the logical second part yet, it's just the skeletal event trigger setup and request validation.
I think there might be benefit in merging just the skeletal part here early to monitor performance? This event trigger will be far more frequent than our other uses so far. Then I'll come back and fill in the logic soon.
**To test:** 
- Update a flow that is not templated from another, check the Hasura events log to confirm an event was triggered. It should …
=> feat: setup event trigger to update `templated_flow_edits`

api.planx.uk/modules/gis/service/digitalLand.ts
Fixes incorrect schema value here https://api.editor.planx.dev/admin/session/08e8421b-96e2-44aa-a22f-de8090b07315/digital-planning-application?skipValidation=true
=> fix: ensure `article4.caz` variables reflect correct council name too

editor.planx.uk/src/@planx/components/Checklist/Editor/Editor.test.tsx, editor.planx.uk/src/@planx/components/Checklist/Editor/Editor.tsx, editor.planx.uk/src/@planx/components/Checklist/model.ts, editor.planx.uk/src/@planx/components/Checklist/types.ts, editor.planx.uk/src/@planx/components/Question/Editor.tsx, editor.planx.uk/src/@planx/components/Question/model.ts, editor.planx.uk/src/pages/FlowEditor/lib/__tests__/automations.blanks.test.ts, editor.planx.uk/src/pages/FlowEditor/lib/store/preview.ts
See for context https://opensystemslab.slack.com/archives/C01E3AC0C03/p1746778683171619
Allows editors an option override normal auto-answering navigation for blanks by marking a Question or Checklist as "never put to user (default to blank automation)". When this is toggled on, the editor modal will enforce that the Question or Checklist sets a top-level data field and that exactly one option data value is blank.
Logic changes do not impact any existing automation rules or unit tests, this is an additive-change only. New unit tests added to exemplify.
Testing https://4676.planx.pizza/testing/automations-test-flow
=> feat: `Questions` and `Checklists` can toggle "never put to user (default blank automation)"

editor.planx.uk/src/@planx/components/List/schemas/GLA/OpenSpace.ts, editor.planx.uk/src/@planx/components/Page/Editor.tsx, editor.planx.uk/src/@planx/components/Page/schema/Monitoring.ts, editor.planx.uk/src/@planx/components/Page/schema/Utilities.ts
Add news page schemas relevant for full planning applications and associated London Data Hub requirements.
=> feat: add new page schemas

editor.planx.uk/src/components/EditorNavMenu/EditorNavMenu.tsx
External analytics links are now viewable by users with the "analyst" role.
=> feat: Make analytics link visible to analyst role

api.planx.uk/package.json, api.planx.uk/pnpm-lock.yaml
Fixes https://github.com/theopensystemslab/planx-new/security/dependabot/219
Release notes: https://github.com/expressjs/multer/releases/tag/v2.0.0
=> chore: CVE-2025-47935

api.planx.uk/helpers.ts, api.planx.uk/modules/flows/validate/service/index.ts, api.planx.uk/modules/flows/validate/validate.test.ts
An error is thrown when an unpublished flow is first published.
The `GetHistory` query requires a `last_published_at` timestamp which does not exist on unpublished flows.
Conditionally return `null` from `getHistory()` if there's no `last_published_at` timestamp.
=> fix: Handle first publish of flows with no history

editor.planx.uk/src/@planx/components/Feedback/Editor/Editor.tsx, editor.planx.uk/src/ui/editor/MoreInformation/MoreInformation.tsx, editor.planx.uk/src/ui/editor/RichTextInput/RichTextInput.tsx
Highlighted by @augustlindemer here: https://opensystemslab.slack.com/archives/C088K9ZL8EA/p1747672628094169
When authoring content for `MoreInformation` (AKA help text), clicking twice on text toggles `H2` formatting on/off in error, making it difficult to use the editor.
**Example:**
https://editor.planx.dev/testing/content-editing/nodes/_root/nodes/iZ2Ak5BYLv/edit
The issue seems to arise from having the `RichTextInput` component wrapped in a `<label>`, without having any means of associating it with an `<input>`, as the `RichTextInput` did not include an input by default.
The other instance of `RichTextInput` wrapped in `<label>` is in the feedback component, where there is a `htmlFor=""` attribute, which was incorrectly being associated with a `name=""` attribute on the input.
Adding …
=> fix: Rich text headings bug

editor.planx.uk/src/index.tsx, editor.planx.uk/src/lib/featureFlags.ts
Feature flags aren't available on the `window`
Rather than relying on the import order, explicitly call an init function early in the app's call chain.
- Feature flags unavailable on staging, prod, or other Pizzas
- Feature flags available on this Pizza
=> fix: Ensure feature flags are always initialised

editor.planx.uk/src/@planx/components/FindProperty/Public/Public.test.tsx, editor.planx.uk/src/@planx/components/FindProperty/Public/index.tsx, editor.planx.uk/src/@planx/components/FindProperty/Public/mocks/localAuthorityMock.ts
Planning Data now publishes [wards](https://www.planning.data.gov.uk/dataset/ward) which means we can use the address point to query the ward name and add it to the passport as `property.ward`. Can merge this anytime and will capture in next schema release.
https://trello.com/c/OkSHmSQh/3295-auto-collect-ward-boundary-data
=> feat: add ward to property info query on `FindProperty`

editor.planx.uk/src/routes/authenticated.tsx, editor.planx.uk/src/routes/utils.ts, hasura.planx.uk/metadata/tables.yaml, hasura.planx.uk/migrations/1747989699392_run_sql_migration/down.sql, hasura.planx.uk/migrations/1747989699392_run_sql_migration/up.sql, scripts/seed-database/container.sh
- The query for the `teams_summary` view coalesces staging and production values, when there can be a significant time gap between these values being populated
- This leads to the production admin panel showing the incorrect value, when only staging is popualted
- More detail here (OSL Slack) - https://opensystemslab.slack.com/archives/C01E3AC0C03/p1747909379331239
- Per-env columns in the `teams_summary` view (to match the data source of `team_integrations`)
- Conditionally query different columns, based on environment
- Still map these columns to single, simpler, `AdminPanelData` type within the Editor
=> fix: Env based admin panel query

editor.planx.uk/src/@planx/components/ExternalPortal/Editor.tsx, editor.planx.uk/src/ui/shared/Autocomplete/styles.ts, editor.planx.uk/src/ui/shared/SelectMultiple.tsx
Fixes autocomplete icon across all instances of autocomplete. I'm unsure what has caused this recent styling regression, but removing all instances of `top: "unset",` on the icon element fixes the issue.
**Preview (before vs after for each):**
=> fix: Autocomplete icon alignment

api.planx.uk/modules/webhooks/controller.ts, api.planx.uk/modules/webhooks/routes.ts, api.planx.uk/modules/webhooks/service/updateTemplatedFlowsOnSourcePublish/index.ts, api.planx.uk/modules/webhooks/service/updateTemplatedFlowsOnSourcePublish/schema.ts, api.planx.uk/tsconfig.json, hasura.planx.uk/metadata/tables.yaml
Sets up a Hasura event trigger on every publish. 
The logic is:
- If the published flow is _not_ a template (`isTemplate: false`), then simply return
- If the published flow is a template, then:
- (Here) Fetch its templated flows (here)
- (TODO) Update each templated flow with the live data of the recently published source template (unflattened), reconciling custom `templated_flow_edits` for each templated flow
Similar to previous template PRs, trying to keep this iterative - so event setup here & I'll pick up logic & testing in a followup!
=> feat: setup database event to update templated flows on source publish

api.planx.uk/helpers.ts, api.planx.uk/modules/flows/validate/service/index.ts, api.planx.uk/modules/flows/validate/validate.test.ts, editor.planx.uk/src/pages/FlowEditor/components/Sidebar/Publish/CheckForChangesButton.tsx, editor.planx.uk/src/pages/FlowEditor/components/Sidebar/Publish/PublishDialog.tsx
Simple UI warning when publishing the "source template" ! As only `platformAdmins` can create source templates, we don't have to worry about anyone else seeing this yet - a very good candidate to revisit later to finalise language & styles.
=> feat: if a flow is a template, inform the publisher about any `templated_from` children that will be updated

infrastructure/application/services/hasura.ts
- Updates the env var `HASURA_GRAPHQL_CORS_DOMAIN` on Hasura (staging and prod) to allow requests from https://localplanning.services
- `.env` and `.env.example` do not need to be updates as requests will be coming from a `.pizza` domain which is already configures
- Currently, we're not planning on making requests to the PlanX REST API from localplanning.services
=> chore: Configure CORS to allow requests from localplanning.services to Hasura (staging/prod)

hasura.planx.uk/metadata/databases/default/tables/public_flows.yaml
- Grants public role access to `flows.description`, `flows.summary` and `flows.limitations`
- No warning / alert required in Editor
- Required for localplanning.services
=> chore: Grant public role access to flow description, summary, and limitations

hasura.planx.uk/migrations/default/1748604081352_metabase_access_for_feedback_summary/down.sql, hasura.planx.uk/migrations/default/1748604081352_metabase_access_for_feedback_summary/up.sql
Forgot to add `GRANT SELECT ON "public"."feedback_summary" TO metabase_read_only;` to #4720, here's a new migration to do that!
=> chore: grant select permission in `feedback_summary` to metabase

editor.planx.uk/src/pages/FlowEditor/components/Sidebar/Publish/CheckForChangesButton.tsx, editor.planx.uk/src/pages/FlowEditor/lib/store/editor.ts, editor.planx.uk/src/routes/views/flowEditor.tsx
Like other PRs, aiming to introduce functional logic here but with still very rough styles that can be iterated on !
If the source template has been published more recently: 
If your template has been published more recently:
Open questions:
- Currently, I'm just comparing publish dates between your templated flow and its' source - how do we additionally communicate, "your templated flow is up to date with the source, _but_ you have unpublished customisations"
=> feat: for templated flows, show when the source was last published if your template is due to publish

editor.planx.uk/src/pages/FlowEditor/lib/store/editor.ts
Minor tidy up - `flows_by_pk` is more performant than quering all `flows` with a `where` condition!
=> fix: `lastPublished` and `lastPublisher` queries should use `flows_by_pk`

editor.planx.uk/src/@planx/components/MapAndLabel/Public/CopyFeature.tsx, editor.planx.uk/src/@planx/components/MapAndLabel/test/public.test.tsx, editor.planx.uk/src/pages/FlowEditor/lib/store/editor.ts, editor.planx.uk/src/pages/Team/components/FlowCard.tsx, editor.planx.uk/src/pages/Team/components/ShowingServicesHeader.tsx, editor.planx.uk/src/pages/Team/helpers/sortAndFilterOptions.ts, editor.planx.uk/src/pages/Team/index.tsx, editor.planx.uk/src/ui/editor/Filter/Filter.tsx, editor.planx.uk/src/ui/editor/Filter/FilterStyles.ts, editor.planx.uk/src/ui/editor/Filter/FiltersColumn.tsx, editor.planx.uk/src/ui/editor/Filter/tests/Filter.test.tsx, editor.planx.uk/src/ui/editor/Filter/tests/helpers.ts, editor.planx.uk/src/ui/editor/SelectInput/SelectInput.tsx, editor.planx.uk/src/ui/editor/SortControl/SortControl.tsx, editor.planx.uk/src/ui/shared/SearchBox/SearchBox.tsx
- Introduces a simpler filter block with no accordion
- Simplifies styling of filter cards
- Introduces a grid/row view switch to the team page UI, which is updated in the store
- Adds a `Source Template` filter option to the template filter (run `window.featureFlags.toggle("TEMPLATES")` to see)
**Testing:**
https://4541.planx.pizza/a-new-team?sort=last-edited&sortDirection=desc
=> refactor: Simplify team page filters

localplanning.services/src/lib/lpa-api.ts
Follow up to https://github.com/theopensystemslab/planx-new/pull/4730
This will now display flow summaries, where provided, on flow cards.
This raises a few questions - 
- Only Doncaster have configured these, should we enforce that this is required to take a service onto LPS?
- If so, should we restrict the query to services (and LPAs) with this configured?
- If we're not this strict, what do we use as fallback text (currently still lorem ispum)?
None of these need immediate answers 👍
=> chore(lps): Return and display flow summaries

api.planx.uk/modules/file/file.test.ts, api.planx.uk/modules/file/middleware/useFileUpload.ts, editor.planx.uk/src/@planx/components/shared/PrivateFileUpload/Dropzone.tsx
- Adds the ability to upload SVGs via frontend and API
- More explicit test for filetypes
=> feat: Support SVG file uploads

.github/workflows/pizza-teardown-manual.yml, .github/workflows/pizza-teardown.yml, .github/workflows/pull-request.yml
as per title - replaces #4755
related PR for vultr-action: https://github.com/theopensystemslab/vultr-action/pull/5
=> chore: bump vultr-action to v2.3, pass ssh_key_ids in all cases

editor.planx.uk/src/@planx/components/Content/Editor.tsx, editor.planx.uk/src/@planx/components/Pay/Editor/Editor.tsx, editor.planx.uk/src/@planx/components/Pay/Editor/InviteToPaySection.tsx, editor.planx.uk/src/@planx/components/Section/Editor.tsx, editor.planx.uk/src/ui/editor/MoreInformation/MoreInformation.tsx, editor.planx.uk/src/ui/editor/RichTextInput/RichTextInput.tsx, editor.planx.uk/src/ui/editor/RichTextInput/types.ts, editor.planx.uk/src/ui/editor/RichTextInput/validationHelpers.ts
Reported by @augustlindemer
When authoring content that is already nested below a `<h2>` heading (specifically in the help text modal), the warning "H2 must come before H3" should not be applied.
Current rules make the distinction between `rootLevelContent` (boolean) to determine whether a `<h1>` is already present, or if it should be required in the rich text content. Moving this a `variant` with an option for `nestedContent` allows us to ignore the rule "H2 must come before H3" for content where both `<h1>` and `<h2>` is already present (so heading hierarchy rules should not apply).
**Testing:**
https://4749.planx.pizza/a-new-team/text-validation-testing
=> fix: Heading level warnings for help text (nested content)

editor.planx.uk/src/pages/Team/components/FlowCard.tsx
Per bug today! https://opensystemslab.slack.com/archives/C088K9ZL8EA/p1749564694647459
We never want a flow to be both `copied_from` and `templated_from`. Plus one minor visual change to flow card banners to read "Templated from [team]" per Silvia's suggestion in design thread - agree this is much more clear!
=> fix: disable "copy" flow menu item for source templates and templated flows

editor.planx.uk/src/pages/FlowEditor/components/Flow/components/Checklist.tsx, editor.planx.uk/src/pages/FlowEditor/components/Flow/components/Portal.tsx, editor.planx.uk/src/pages/FlowEditor/components/Flow/components/Question.tsx, editor.planx.uk/src/pages/FlowEditor/components/Flow/components/Tag.tsx, editor.planx.uk/src/pages/FlowEditor/floweditor.scss, editor.planx.uk/src/theme.ts, editor.planx.uk/src/themeOverrides.d.ts
As part of the broader templates work we've identified the need to simplify graph nodes, so that we can better signpost them as custom nodes in templates.
PR makes the following changes:
- Updates tags to display as chips rather than full width banners on nodes
- Updates help text icon to be in the top-right corner to increase visibility
- (suggested change) updates info-only colour for tags to use our info blue style, used across PlanX
**Before vs after:**
**Testing:**
https://4778.planx.pizza/testing/permitted-development-jc-restructure
=> feat: Use chips for node tags

editor.planx.uk/src/pages/FlowEditor/components/Flow/components/Checklist.tsx, editor.planx.uk/src/pages/FlowEditor/components/Flow/components/Portal.tsx, editor.planx.uk/src/pages/FlowEditor/components/Flow/components/Question.tsx, editor.planx.uk/src/pages/FlowEditor/floweditor.scss, editor.planx.uk/src/pages/FlowEditor/index.tsx
Sets up basic styling for template/custom cards in the graph ("Required" only):
=> feat: Set up styling for template cards in graph

editor.planx.uk/src/pages/FlowEditor/components/Settings/ServiceSettings/FlowStatus/index.tsx, editor.planx.uk/src/pages/Team/components/AddFlow/CreateFromTemplateFormSection.tsx
Does exactly what it says - rather than immediately show all source templates in options dropdown when creating a new service "from template", only show online source templates !
=> chore: when creating a service from template, only select from "online" options

editor.planx.uk/src/pages/FlowEditor/components/Flow/components/Portal.tsx, editor.planx.uk/src/pages/FlowEditor/floweditor.scss
Fixes content alignment of portals with tags.
**Before vs after:**
=> fix: Portal tag layout

README.md, doc/how-to/how-to-configure-docker-for-apple-silicone.md
This pull request updates the documentation to improve support for Apple Silicon Macs and enhance clarity in setup instructions. The most important changes include updating the AWS SSO credentials link in the `README.md`, adding a troubleshooting guide for Docker compatibility issues on Apple Silicon Macs, and introducing a new document with detailed solutions for these issues.
* **Updated AWS SSO credentials link in `README.md`**: The link to the AWS SSO setup guide was updated to reflect its new location under a more specific directory structure. Additionally, a note was added to the `README.md` about Docker compatibility issues for Apple Silicon Macs, with a link to the troubleshooting guide.
* **Added new document for Docker compatibility solutions**: A new file, …
=> docs: readme setup update

editor.planx.uk/src/@planx/components/shared/PrivateFileUpload/UploadedFileCard.tsx
This pull request updates the `UploadedFileCard` component to replace the use of the `Box` component with the `List` component for rendering tags. This change improves the semantic structure of the component.
* [`editor.planx.uk/src/@planx/components/shared/PrivateFileUpload/UploadedFileCard.tsx`](diffhunk://#diff-754df901dc2d20a4c2aa2d07fedbb8f9ef82f742d70ca4f692a871cec2184785R7): Added the `List` import to replace the `Box` component for rendering tags.
=> refactor: updates container to use a MUI List container to contain list items

editor.planx.uk/src/ui/shared/Input/Input.tsx
Small tidy up I noticed when working on https://github.com/theopensystemslab/planx-new/pull/4804
Previously, we were using `useRef` and `useImperativeHandle` to target the child input, but it's actually possible to do this directly via MUI's `inputRef` prop ([docs](https://mui.com/material-ui/api/input/#input-prop-inputRef)).
**To test**
- Select events (text highlighting) still work across inputs
- Focus events still work across inputs
=> chore: Use MUI `inputRef` prop

editor.planx.uk/src/pages/FlowEditor/components/Sidebar/EditHistory/TimelineItems.tsx, editor.planx.uk/src/pages/FlowEditor/components/Sidebar/Publish/AlteredNodes.tsx, editor.planx.uk/src/pages/FlowEditor/components/Sidebar/Publish/CheckForChangesButton.tsx
https://trello.com/c/sngCGirg/3353-implement-internal-feedback-and-finalise-design-make-sure-live-services-are-always-up-to-date-aka-flows-copied-from-templates-sh
**User stories:**
- As someone maintaining a templated flow, I want to know that it's being "taken care of" (receiving updates from) the source template
- As someone publishing a templated flow, I want to know which update(s) to the source template I'm reviewing that are included in my next publish (** the source template may have been published more than once since your templated flow has been published!!)
**Changes:**
- Applies the purple template color to comments that have been automatically added based on the source template update so that they're easy to distinguish from "normal" comments
**Open questions:**
- Does this …
=> design: add templates style to comments automatically created on source update

editor.planx.uk/src/pages/FlowEditor/components/Flow/components/Checklist.tsx, editor.planx.uk/src/pages/FlowEditor/components/Flow/components/Portal.tsx, editor.planx.uk/src/pages/FlowEditor/components/Flow/components/Question.tsx, editor.planx.uk/src/pages/FlowEditor/components/Sidebar/Customisations/CustomisationCard.tsx, editor.planx.uk/src/pages/FlowEditor/components/Sidebar/Customisations/index.tsx, editor.planx.uk/src/pages/FlowEditor/components/Sidebar/Publish/CheckForChangesButton.tsx, editor.planx.uk/src/pages/FlowEditor/components/Sidebar/index.tsx, editor.planx.uk/src/pages/FlowEditor/floweditor.scss, editor.planx.uk/src/pages/FlowEditor/index.tsx, editor.planx.uk/src/ui/editor/TemplatedNodeContainer.tsx
- Sets background colour for optional vs required in graph and sidebar node cards
- Ensures background of Customise panel covers 100% height
- Adjusts layout of (sidebar header)
Testing:
https://4794.planx.pizza/a-new-team/template
Feature flagged: `window.featureFlags.toggle("TEMPLATES")`
=> feat: Background colours for template cards

editor.planx.uk/src/@planx/components/Section/Public.tsx, editor.planx.uk/src/@planx/components/shared/Buttons/Tag.tsx
This pull request introduces changes to consistently identify the status tags on the ```SectionsOverview``` component and indicate to as screen reader user more predictable where they will be navigated too on button click.
I think this fills the brief on pg(50) of the brief, but I think the language could maybe be clearer if anyone has any thoughts on this?
* Added a new optional `sectionTitle` prop to the `Props` interface of the `Tag` component to allow passing a section title for better contextual information. (`editor.planx.uk/src/@planx/components/shared/Buttons/Tag.tsx`, [editor.planx.uk/src/@planx/components/shared/Buttons/Tag.tsxR56-R62](diffhunk://#diff-ebfaee41a8f2b0deb01968e43c75c4a22325da0b37e10492859253923a0fcaeeR56-R62))
* Updated the `Tag` component to conditionally display …
=> refactor: adds more descriptive accessible labeling to section progress tags

editor.planx.uk/src/pages/FlowEditor/components/Settings/ServiceSettings/FlowVisibility/FlowVisibilitySection.tsx
Follows on from #4774 
https://trello.com/c/sngCGirg/3353-implement-internal-feedback-and-finalise-design-make-sure-live-services-are-always-up-to-date-aka-flows-copied-from-templates-sh
If a flow is a source template or templated flow, replace the usual "Visibility" settings toggle with a static message:
=> feat: "Visibility" flow settings should show a static message for source templates and templated flows

editor.planx.uk/src/@planx/components/MapAndLabel/Public/Context.tsx, editor.planx.uk/src/@planx/components/MapAndLabel/Public/CopyFeature.tsx, editor.planx.uk/src/@planx/components/MapAndLabel/test/public.test.tsx
- Fixes "Copy feature" dropdown to be keyboard accessible
- Adds explicit "Copy" button to control action
- Resolves https://trello.com/c/64ZlcVF7/3312-keyboard-a-aaa-p-23-last-prio-bc-mapandlabel
Try using the `MapAndLabel` component in Storybook via the keyboard - https://storybook.4804.planx.pizza/?path=/docs/planx-components-mapandlabel--docs
https://github.com/user-attachments/assets/3511bee1-5e17-4346-842a-ced937ef9c0b
=> feat(a11y): Keyboard access for `MapAndLabel` "Copy feature" select

editor.planx.uk/src/pages/FlowEditor/components/Settings/ServiceSettings/ServiceSettings.tsx, editor.planx.uk/src/pages/FlowEditor/components/Settings/ServiceSettings/TemplatedFlowStatus/TemplatedFlowStatusSection.tsx
Basic UI in service settings, will hook the button up to actual API endpoint & logic in a followup PR
Let's get this on staging ASAP so we can get feedback on location (is service settings where you expect? should it be de-emphasised at bottom of page?) and content copy first
=> design: eject from templated flow features (UI only)

editor.planx.uk/src/@planx/components/Notice/Editor.tsx, editor.planx.uk/src/@planx/components/Pay/Editor/Editor.tsx, editor.planx.uk/src/ui/editor/TemplatedNodeConfiguration.tsx
Per feedback https://opensystemslab.slack.com/archives/C04DZ1NBUMR/p1750424102836949 & outstanding tasks here https://trello.com/c/sngCGirg/3353-implement-internal-feedback-and-finalise-design-make-sure-live-services-are-always-up-to-date-aka-flows-copied-from-templates-sh
=> fix: add missing `TemplatedNodeConfig` to Pay & Notice modals

.github/workflows/pull-request.yml, localplanning.services/.env.dev, localplanning.services/.env.pizza, localplanning.services/.env.staging, localplanning.services/astro.config.mjs, localplanning.services/src/components/applications/EmailForm.tsx, localplanning.services/src/components/applications/hooks/useResumeApplication.tsx, localplanning.services/src/pages/applications/check-your-inbox.astro, localplanning.services/src/pages/applications/index.astro
- Adds the "Your applications" page
- Makes basic form which submits to hit PlanX API (response not possible currently, see below)
Currently the PlanX `/resume-application` endpoint requires a `teamSlug`. This is used for - 
- Email personalisation
- Filtering list of applications to include in the "resume" email content
For LPS, we don't want this restriction (single team) in place. The email template should send a single magic link which takes the user back to LPS, where the full list of applications is displayed.
Yes, we could do this. However, I think new endpoints (grouped within an `/lps` route/module) are a cleaner and safer option in terms of maintainability going forward. Whilst the "resume" options within PlanX and LPS are fundamentally similar we don't necessarily want them …
=> feat(lps): Basic layout for 'Your applications'

editor.planx.uk/src/pages/FlowEditor/components/Flow/components/Checklist.tsx, editor.planx.uk/src/pages/FlowEditor/components/Flow/components/Node.tsx, editor.planx.uk/src/pages/FlowEditor/components/Flow/components/Portal.tsx, editor.planx.uk/src/pages/FlowEditor/components/Flow/components/Question.tsx, editor.planx.uk/src/pages/FlowEditor/components/Flow/index.tsx, editor.planx.uk/src/pages/FlowEditor/components/Sidebar/Customisations/CustomisationCard.tsx, editor.planx.uk/src/pages/FlowEditor/floweditor.scss, editor.planx.uk/src/pages/FlowEditor/index.tsx, editor.planx.uk/src/ui/editor/TemplatedNodeContainer.tsx
- Refactors template graph node to have only purple border (no distinction of required/optional or done)
**Testing:**
https://4823.planx.pizza/a-new-team/source-templated
- Also adds `flow-locked` background as opacity to enable TESTING watermark to be visible
=> refactor: Border only style for template graph nodes

api.planx.uk/modules/send/utils/exportZip.ts, api.planx.uk/tests/loadOrRecordNockRequests.js
Context here https://trello.com/c/X3qm89R3/3327-can-we-do-we-want-to-shorten-submission-zip-filenames
Easy first step here which is ensure zip never downloads with prefix `_api_dist_modules_send_utils_`. 
In future if this continues to come up, as already captured on Trello ticket, we may want to get more clever and also strip off `apply-for-` or introduce service acronymns (either in editor service settings or via hardcoded lookup/ODP Schema application types??) which could be used here instead in full slug.
**Testing:**
- Spin up a quick test service on this pizza using "Send to email" 
- Configure team settings "Submission email" as your own email
- Publish your test service, make sure it's online - do a test
- Confirm you can successfully download the file (and ensure filename is …
=> chore: tidy up export zip filename

editor.planx.uk/src/pages/FlowEditor/lib/analytics/utils.ts, editor.planx.uk/src/pages/FlowEditor/lib/store/settings.ts, editor.planx.uk/src/pages/FlowEditor/utils.ts, editor.planx.uk/src/routes/views/flowEditor.tsx
- Adds `isSubmissionService` to `FlowInformation` interface (`editor.planx.uk/src/pages/FlowEditor/utils.ts`)
- Updates `getSubmission()` and `generateAnalyticsLink()` in to check for `isSubmissionService = true` (`editor.planx.uk/src/pages/FlowEditor/lib/analytics/utils.ts`) 
- Runs `getFlowInformation` to pass `isSubmissionService` to `generateAnalyticsLink` (`editor.planx.uk/src/routes/views/flowEditor.tsx`)
So that we can automatically create dashboards for services that have Send components without manually keeping track of an allow-list. (RAB check comes first so we'll always have the RAB dashboard if relevant.)
Turn a non-RAB service with a Send component to 'online' in the editor (and refresh). Analytics link should be working.
=> feat: create submission analytics when `isSubmissionService = true`

editor.planx.uk/src/pages/layout/PublicLayout.tsx
- Adds "(opens in a new tab)" to OGL link in the footer
- Address "Change on Request" issue in DAC report, page 64
> “Clicking on the ‘Lambeth, Open Government Licence v3’ link will open in a new tab with no
way to back out of it. This can result in confusion especially if you already have multiple tabs
open on the window. Some type of warning placed next to it would help the user know
what is about to happen.”
> [!IMPORTANT]
> I've not addressed the additional suggestion to either remove `target="_blank" or add"(opens in a new tab)" to the logo in the header as - 
> - GDS states "a use case example [for opening in a new tab] is to stop the user losing information they’ve entered into a form" which I believe applies here ([source](https://design-system.service.gov.uk/styles/links/#opening- …
=> fix(a11y): Add "(opens in a new tab)" to OGL link

api.planx.uk/modules/flows/docs.yaml, api.planx.uk/modules/flows/publish/service.ts, api.planx.uk/modules/flows/routes.ts, api.planx.uk/modules/flows/updateTemplatedFlow/controller.ts, api.planx.uk/modules/flows/updateTemplatedFlow/updateTemplatedFlow.test.ts, api.planx.uk/modules/webhooks/docs.yaml
Some API-side cleanup for templates! 
Fills in `test.todo`, adds missing Swagger docs now that endpoints have stabilised a bit, and improves a lingering `any` type.
=> chore: fill in `test.todo` & missing Swagger docs for templates endpoints

editor.planx.uk/src/@planx/components/ExternalPortal/Editor.test.tsx, editor.planx.uk/src/@planx/components/ExternalPortal/Editor.tsx, editor.planx.uk/src/@planx/components/InternalPortal/Editor.test.tsx, editor.planx.uk/src/@planx/components/InternalPortal/Editor.tsx
Fixes source template bug reported here https://opensystemslab.slack.com/archives/C04DZ1NBUMR/p1750877038481739?thread_ts=1750424102.836949&cid=C04DZ1NBUMR:
> I also noticed an issue with the Allow edits toggle on portals: Internal portal nodes within a source template always open with the Allow edits toggle off within the Editor modal. They are irrespective of that correctly saved as toggled, but their instructions disappear and in order to toggle them off you'd have to double toggle them. External portal nodes within a source template do not retain their Allow edits toggle at all, and can't be toggled on or off.
Quick one - simply missed these `initialValues` in the big PR that introduced across all component types!
=> fix: ensure internal and external portal modals set all `initialValues`

api.planx.uk/modules/lps/controller.ts, api.planx.uk/modules/lps/docs.yaml, api.planx.uk/modules/lps/index.test.ts, api.planx.uk/modules/lps/routes.ts, api.planx.uk/modules/lps/service/getApplications.ts, api.planx.uk/modules/lps/service/login.ts, api.planx.uk/modules/lps/types.ts, hasura.planx.uk/metadata/databases/default/tables/public_lps_magic_links.yaml
- Sets up the POST `/lps/applications` endpoint on the PlanX REST API
- Test coverage added in #4856 & #4857 (split PR up as it was getting pretty big)
This endpoint is used as part of the login flow for localplanning.services - provided with a magic link, it will return the associated sessions for a user.
- Wire up the applications page in LPS to hit this endpoint when provided with a token
=> feat(api): `/lps/applications` endpoint

docker-compose.e2e.yml, e2e/tests/api-driven/src/lps/getApplications.feature, e2e/tests/api-driven/src/lps/helpers.ts, e2e/tests/api-driven/src/lps/steps.ts
Coverage for functionality added in #4852
Regression tests running here https://github.com/theopensystemslab/planx-new/actions/runs/15980425980 🚀
=> test(e2e): Coverage for the `/lps/applications` endpoint

api.planx.uk/modules/lps/index.test.ts, api.planx.uk/modules/lps/service/getApplications.test.ts, api.planx.uk/vitest.config.ts
This PR focuses on validation and error handling within the endpoint. In order to functionally test this work (as most the business logic is within the GraphQL mutation) we need to rely on E2E tests - otherwise we end up basically just testing our own mocks.
=> test(api): Coverage for the `/lps/applications` endpoint

api.planx.uk/helpers.ts, hasura.planx.uk/metadata/databases/default/tables/public_flows.yaml
Small bug I've noticed while testing on staging / demo'ing last couple days !
We were still queuing up and triggering "update" events on source publish for templated flows that were archived - meaning it then takes longer for updates to trickle through to 'active' children !
=> fix: omit archived templated flows when queuing up `templatedFlow` update events

editor.planx.uk/src/@planx/components/Feedback/Editor/Editor.tsx, editor.planx.uk/src/@planx/components/Feedback/Public/Public.tsx, editor.planx.uk/src/@planx/components/Feedback/Public/tests/Public.accessibility.test.tsx, editor.planx.uk/src/@planx/components/Feedback/components/defaultContent.tsx, editor.planx.uk/src/@planx/components/Feedback/model.ts
This PR locks all but title and description fields for the Feedback component.
This ensures consistency across content, consistent use of feedback in metrics and evaluation, and the use of the service's privacy page in the disclaimer.
More context in [original PR](https://github.com/theopensystemslab/planx-new/pull/4851).
=> fix: hardcode feedback component default content

localplanning.services/src/components/applications/LoginForm.tsx, localplanning.services/src/pages/directory.astro, localplanning.services/src/styles/global.css
- Introduces custom properties (CSS variables) to control input styling across Astro, React and GOV.UK web components
- Uses the GOV.UK postcode lookup web component style as a base, adding custom properties where needed
- Works across Astro and React components with the class `input--text`
Using custom properties allows us to reach web components through the shadow DOM, the compromise is that we can't use Tailwind classes for custom properties, however it does mean we can have a universally defined set of styles for inputs.
Still to do in follow up work: standardise label styles
**Web component:**
**Astro component:**
React component:
=> feat(lps): Universal input styles

editor.planx.uk/src/@planx/components/Checklist/Public/components/GroupedChecklist.tsx, editor.planx.uk/src/@planx/components/Checklist/Public/components/GroupedChecklistOptions.tsx
This PR addresses the following issue in the report (page 29) - 
> _All the checkboxes are grouped under one group: ‘List the changes involved in the project’.
The radio buttons are split into collapsable sub-groups. An aria-labelledby attribute has
been applied to a parent div element without a role so these subgroups are not
programmatically determined._
This now matches the example markdown provided - 
- Link checkboxes programmatically via data values
- Formik validation - ensure that if repeated data values are used across subgroups, the label text is consistent
=> fix(a11y): Apply correct aria labels to grouped checkboxes

editor.planx.uk/src/@planx/components/Review/Editor.tsx, editor.planx.uk/src/@planx/components/Review/Public/Presentational.tsx, editor.planx.uk/src/@planx/components/Review/model.ts, editor.planx.uk/src/@planx/components/Section/Editor.tsx, editor.planx.uk/src/@planx/components/Section/model.ts, editor.planx.uk/src/@planx/components/Send/Editor.tsx, editor.planx.uk/src/@planx/components/Send/model.ts, editor.planx.uk/src/@planx/components/SetFee/Editor.tsx, editor.planx.uk/src/@planx/components/SetFee/model.ts, editor.planx.uk/src/@planx/components/SetValue/Editor.tsx, editor.planx.uk/src/@planx/components/SetValue/model.ts, editor.planx.uk/src/@planx/components/TaskList/Editor.tsx, editor.planx.uk/src/@planx/components/TaskList/model.ts, editor.planx.uk/src/@planx/components/TextInput/Editor.tsx, editor.planx.uk/src/@planx/components/TextInput/model.ts, editor.planx.uk/src/ui/editor/ModalFooter.tsx
This PR adds formik-level validation of the following batch of components - 
- `Review`
- `Section`
- `Send`
- `SetFee`
- `SetValue`
- `TaskList`
- `TextInput`
The only outstanding ones now either have other open PRs, or are more complex and involve the `ListManager` (FileUpload, FileUploadAndLabel).
=> feat: Editor validation schemas (cont.)

editor.planx.uk/src/@planx/components/Feedback/Editor/Editor.tsx, editor.planx.uk/src/@planx/components/Section/Editor.tsx, editor.planx.uk/src/ui/editor/RichTextInput/RichTextInput.stories.tsx, editor.planx.uk/src/ui/editor/RichTextInput/types.ts
At last, the final step in https://trello.com/c/REGig63B/3309-non-text-content-a-p16
This should now mean that each time we reach for a `RichTextInput` we have to have a viable validation schema to cover a11y issues.
Also in this PR are a few fixes caught by making the type stricter! 🚀
=> chore: Require `errorMessage` prop for `RichTextInput`

localplanning.services/src/components/Masthead.astro, localplanning.services/src/pages/index.astro
Adds a size variant to the masthead.
**Default size:**
https://localplanning.4922.planx.pizza/about/
**Large size:**
https://localplanning.4922.planx.pizza/
=> feat(lps): Size variant for masthead

doc/how-to/how-to-setup-custom-subdomains.md, infrastructure/application/index.ts
- Updates documentation to support 4096-bit keys
- Allows Pulumi to regenerate certificates, not just update certificates, when the key changes (e.g. from 2048 to 4096)
The following error was thrown when deploying #4933 to production - 
```
ValidationException: New certificate has a key of RSA_4096 which is different from RSA_2048 in the current certificate
```
This happened because -
- Epsom and Ewell did not use our CSR which specifies as 2048-bit key
- I missed the check in AWS Staging for the key size
[AWS CloudFront now supports 4096-bit keys](https://aws.amazon.com/about-aws/whats-new/2023/12/amazon-cloudfront-4096-bit-rsa-tls-certificates/) ([docs](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/cnames-and-https-requirements.html)) which are more secure, so we …
=> fix(infra): Support 4096-bit keys for ACM [skip pizza]

editor.planx.uk/src/@planx/components/List/schemas/CIL/UnoccupiedCIL.ts
Improves UnoccupiedCIL list item legibility from 'Building' to more specific 'Temporary or unoccupied building' in the CIL section.
=> chore: improve unoccupied buildings list item legibility

editor.planx.uk/src/@planx/components/shared/Buttons/ImageButton.tsx, editor.planx.uk/src/ui/shared/Checkbox/Checkbox.tsx, editor.planx.uk/src/ui/shared/ChecklistItem/ChecklistItem.tsx
- Fixes clickable area of checkboxes so that the full bordered box is clickable
Before changes:
https://editor.planx.dev/testing/checkboxes/preview
After changes:
https://4943.planx.pizza/testing/checkboxes/preview
- Clickable area of checkboxes labels with descriptions (only the label text should be clickable), to match https://design-system.service.gov.uk/components/checkboxes/error/
- Alignment of labels for checkboxes with images (before vs after):
=> fix: Checkbox clickable area

localplanning.services/src/components/Header.astro
Quick fix flagged via the Astro audit tool.
=> chore(lps): Eager load LPS logo

editor.planx.uk/src/@planx/components/DrawBoundary/Public/index.tsx
Fixes a small regression introduced in https://github.com/theopensystemslab/planx-new/pull/4843 where the map no longer fills the width of the content container.
**Testing:**
https://4952.planx.pizza/a-new-team/interactive-map/preview
=> fix: Interactive map width

localplanning.services/src/components/Header.astro, localplanning.services/src/styles/global.css
Reorganises responsive header layout to take into account extra menu item ("Find services").
Sizes increasing from 320px:
=> refactor(lps): Refine header layout

scripts/encrypt/package.json, scripts/encrypt/pnpm-lock.yaml
I was hitting an error when running `pnpm decrypt` - likely there since we updated our node version?
Switching the runner to `tsx` resolves this.
Pretty soon we won't need a runner as node will be able to run .ts files natively from v23.6+ ([docs](https://nodejs.org/en/learn/typescript/run-natively)).
=> chore(scripts): Replace ts-node with tsx

editor.planx.uk/src/@planx/components/MapAndLabel/Public/index.tsx, editor.planx.uk/src/hooks/useFormErrorFoucs.ts
[Trello issue](trello.com/c/1KMx198N/3319-tabs-a-aa-p37-last-prio-bc-mapandlabel)
Ok took a bit of initiative on this one, so really open to feedback on approach and scope on this one. I  used the hook I made in this PR a few components outside the one outlined in the issue, and the idea would be to implement in all form components eventually. Should I go farther in this PR?
This pull request introduces a new hook, `useFormErrorFocus`, to enhance user experience by automatically focusing on the first form error after submission, including support for tabbed interfaces. The hook is integrated into multiple components to streamline error handling and improve accessibility.
* [`editor.planx.uk/src/hooks/useFormErrorFoucs.ts`](diffhunk://#diff-0a00d8bc023d5e5b6c6821723464c68fe42708291b72a4f5ac …
=> refactor: navigate to tab and focus on inputs on validataion errors

e2e/tests/api-driven/src/lps/steps.ts
Updates the email used in E2E tests for LPS login to use the GovNotify smoke test email ([docs](https://docs.notifications.service.gov.uk/rest-api.html#smoke-testing)). When I logged in to Notify just now I noticed we're triggering real email when these run.
=> fix(e2e): Use test notify email address

e2e/tests/ui-driven/src/create-flow-with-geospatial.spec.ts, editor.planx.uk/src/pages/FlowEditor/components/Flow/components/Breadcrumb.tsx, editor.planx.uk/src/pages/FlowEditor/components/Flow/components/Node.tsx, editor.planx.uk/src/pages/FlowEditor/components/Flow/components/Portal.tsx, editor.planx.uk/src/pages/FlowEditor/components/Flow/index.tsx, editor.planx.uk/src/pages/FlowEditor/floweditor.scss, editor.planx.uk/src/ui/editor/NodeCard/index.tsx
- Updates internal portals to have a "folder" style as root components
- When inside an internal portal:
- root flow name is displayed as a link, which appears before and after the portal contents
- any parent internal portals are added to the hierarchy as folder breadcrumbs
- folder styling is extended to "encompass" internal portal contents
- Also updates search for internal portals to have folder style
**Testing:**
https://4896.planx.pizza/a-new-team/testing-nesting
**Real-world deep example:**
https://4896.planx.pizza/opensystemslab/permitteddevelopment,GkLVVIasqD,4sdQOdsv6G,zmgKVgZFA0,7nb1Ns0Xyn,XUrPURgXtu,QGbTxfHGcx,lHPhZSPP8f
One small styling bug (which I think we can live with, when building a source template the folder marker appears on the top of the wrapper:
=> feat: Internal portals as folder style

editor.planx.uk/src/@planx/components/FileUploadAndLabel/Public/Modal.tsx
This pull request enhances the accessibility of the `FileTaggingModal` component in the `editor.planx.uk` project. The changes ensure better focus management and provide additional context for screen readers.
* **Focus Management**: Added a `useRef` hook to manage focus on the dialog heading when the modal opens, ensuring accessibility for keyboard and screen reader users. (`editor.planx.uk/src/@planx/components/FileUploadAndLabel/Public/Modal.tsx`, [editor.planx.uk/src/@planx/components/FileUploadAndLabel/Public/Modal.tsxR39-R45](diffhunk://#diff-2179ec7a9c915f453803c1f3746fe6e986eb85813c489e7d0856549d13806e31R39-R45))
* **Screen Reader Context**: Included a visually hidden `Typography` element with additional instructions for screen reader users, describing the purpose of the dialog and …
=> fix: annouces dialog open and give description

editor.planx.uk/src/@planx/components/Checklist/Editor/Editor.test.tsx, editor.planx.uk/src/@planx/components/Checklist/Editor/Editor.tsx, editor.planx.uk/src/@planx/components/Checklist/model.test.ts, editor.planx.uk/src/@planx/components/Checklist/model.ts, editor.planx.uk/src/@planx/components/Question/Editor.tsx, editor.planx.uk/src/@planx/components/shared/index.ts
Migrates existing validation checks from `FormikConfig["test"]` to `FormikConfig["validationSchema"]`.
This PR does not (intentionally!) change the current behaviour and is just a migration from one type of validation to another.
Please see https://github.com/theopensystemslab/planx-new/pull/4978 for further context.
=> chore: Migrate checklist tests to validation schema

editor.planx.uk/src/@planx/components/shared/PrivateFileUpload/Dropzone.tsx
Addresses a11y issue p62 `DAC_Contrast_Enhanced_01`
Trello issue: https://trello.com/c/au0wFUGz/3337-enhanced-contrast-aaa-p62
- Adds "input" style focus state to dropzone
=> fix(a11y): Dropzone focus style

editor.planx.uk/src/ui/shared/ChecklistItem/ChecklistItem.tsx
Fixes a regression where `aria-describedby` pointing at checkbox descriptions is a broken ref if the description is not present. Adds logic to qualify description before adding aria ref.
=> fix(a11y): Broken aria on checkboxes

editor.planx.uk/src/@planx/components/FileUploadAndLabel/Public/Modal.tsx, editor.planx.uk/src/@planx/components/FileUploadAndLabel/Public/SelectMultipleFileTypes.tsx, editor.planx.uk/src/@planx/components/FileUploadAndLabel/Public/index.test.tsx, editor.planx.uk/src/@planx/components/shared/PrivateFileUpload/UploadedFileCard.tsx
- Refactors Upload + label component to use checkboxes rather than an autocomplete combobox
**Demo:**
https://5043.planx.pizza/a-new-team/upload-label/preview
=> refactor(a11y): Use checkboxes for upload and label

editor.planx.uk/src/components/Feedback/FeedbackPhaseBanner.test.tsx, editor.planx.uk/src/components/Feedback/FeedbackPhaseBanner.tsx, editor.planx.uk/src/components/Feedback/index.tsx
Follow up to #5039, responding to [the following comment](https://github.com/theopensystemslab/planx-new/pull/5039#issuecomment-3144940766) - 
> Coming in with late feedback here @DafyddLlyr , looks and works superb! There's a couple of follow up tasks I've spotted:
>
> - ESC key to close the drawer, similar to help text drawer
> - Returning focus to the correct place on the page when the drawer is closed (which I believe was the original feedback)
https://github.com/user-attachments/assets/fdea3689-a282-4a3a-b75e-a6ccc81dfc05
=> fix(a11y): Improvements to feedback drawer

editor.planx.uk/src/@planx/components/FileUploadAndLabel/Public/Modal.tsx, editor.planx.uk/src/@planx/components/FileUploadAndLabel/Public/index.test.tsx, editor.planx.uk/src/@planx/components/FileUploadAndLabel/Public/index.tsx, editor.planx.uk/src/@planx/components/shared/PrivateFileUpload/PrivateFileUpload.tsx, editor.planx.uk/src/@planx/components/shared/PrivateFileUpload/UploadedFileCard.tsx, editor.planx.uk/src/pages/FlowEditor/components/Sidebar/EditHistory/AddCommentDialog.tsx, editor.planx.uk/src/pages/Team/components/AddFlow/index.tsx, editor.planx.uk/src/pages/Team/components/CopyDialog.tsx, editor.planx.uk/src/pages/Team/components/RenameDialog.tsx, editor.planx.uk/src/pages/Teams/AddTeamButton.tsx, editor.planx.uk/src/theme.ts
Address a usability issue and tides up layout and styles for files upload cards (upload and upload & label).
- Adds "delete" text to delete button (usability fix https://trello.com/c/SgOvRdxF/3347-icons-and-labels-usability-p79)
- Refactors layout to accommodate for text
- Simplifies card layout using semantic React `<Stack>`
- Sets default dialog padding in theme for `dialogContent`, `dialogTitle` and `dialogActions` to improve small screen usability and prevent overrides
**Testing:**
https://5055.planx.pizza/a-new-team/uploading/preview
=> refactor(a11y): Improve and tidy up file upload

editor.planx.uk/src/pages/Team/components/ArchiveDialog.tsx, editor.planx.uk/src/pages/Team/components/FlowCard.tsx
I'm in the process of cleaning up old services in the "Testing" team and finding it quite unhelpful how generic the existing "Archive" dialog is - so suggesting a few quick sytle updates here! 
**Changes:**
- Clearly display name of flow you're about to archive
- "Warning" button style for "Archive" action
- Update "remove it from PlanX" language as this isn't really technically accurate!
**Before:**
**After:**
=> fix: display flow name when archiving a flow

editor.planx.uk/src/@planx/components/DateInput/Public.test.tsx, editor.planx.uk/src/@planx/components/DateInput/Public.tsx
DAC (pg 71)
This PR fixes various labels being repeatedly read aloud by screen readers. It removes the visually hidden legend element as this information is repeated in the card header and also corrects the fact that sometime the element was not being correctly passes an id so the id used the correct the label to the input was undefined and was causing some unexpected behaviors.
**Testing and accessibility improvements:**
* The test for accessibility violations in `DateInput` now dynamically finds all error elements and checks that they are empty before submission, and ensures that after triggering an error, at least one error message appears with the correct `role="alert"` attribute. This makes the test more robust and less dependent on hardcoded IDs.
**Component code improvements:**
* …
=> fix: date input usability improvements

infrastructure/application/index.ts
Adds a new `idleTimeout: 120` prop to `lbMetabase` to try and rule out load balancing issues in new permissions error (see [Slack thread](https://opensystemslab.slack.com/archives/C01E3AC0C03/p1754561194131359))
=> chore: bump Metabase load balancer timeout [skip pizza]

localplanning.services/src/components/Footer.astro, localplanning.services/src/components/Header.astro, localplanning.services/src/layouts/SearchLayout.astro, localplanning.services/src/pages/directory.astro, localplanning.services/src/styles/global.css
- Removes `directory` link from header
- Adds to footer with the descriptive title `Directory of local planning authorities`
- Updates page title to the above and removes search box
- Links to directory from search page
https://localplanning.5064.planx.pizza/
=> refactor(lps): Move directory from header to be linked

editor.planx.uk/src/@planx/components/FindProperty/Public/index.tsx, editor.planx.uk/src/@planx/components/shared/Preview/Card.tsx
Temporary fix for visibility of address autocomplete list. Adds margin to the bottom of the Find property component to ensure the full list is always visible.
**Testing:**
https://5066.planx.pizza/testing/address-lookup/preview
=> fix: Address autocomplete visibility (temp)

editor.planx.uk/src/@planx/components/FileUploadAndLabel/Public/FileCard.tsx, editor.planx.uk/src/@planx/components/FileUploadAndLabel/Public/Modal.tsx, editor.planx.uk/src/@planx/components/FileUploadAndLabel/Public/index.test.tsx, editor.planx.uk/src/@planx/components/FileUploadAndLabel/Public/index.tsx
- Scrolls to a selected file when the "change" button is hit in file upload and label
- Raised as usability issue in the accessibility audit
- More useful than ever now that there's a lot more vertical space within the modal
- Should we keep the modal title in view at all times?
https://github.com/user-attachments/assets/09053238-9dc0-40c1-add1-a306a2144656
=> feat: Scroll to file card on "change" click

e2e/tests/ui-driven/src/helpers/userActions.ts, editor.planx.uk/src/@planx/components/DateInput/Public.tsx, editor.planx.uk/src/@planx/components/shared/Preview/CardHeader/CardHeader.tsx, editor.planx.uk/src/@planx/components/shared/Preview/CardHeader/types.ts
Structure now matches suggestion in audit report. No change is required for the `DateInputField` on pages as this already uses a `fieldset` and `legend`.
Trello ticket: https://trello.com/c/Zc3wCtRm/3392-a-form-groups-p17
=> fix(a11y): Associate `DateInput` header with form group label

editor.planx.uk/src/@planx/components/MapAndLabel/Public/CopyFeature.tsx, editor.planx.uk/src/ui/editor/Filter/FiltersColumn.tsx, editor.planx.uk/src/ui/editor/SelectInput/SelectInput.tsx, editor.planx.uk/src/ui/editor/SortControl/SortControl.tsx
> _The accessible name of the Copy from combobox is “sourceLabel” which doesn’t describe its purpose or align with the visible label._
Trello: https://trello.com/c/FgwFBbwM/3391-a-labels-not-programmatically-associated-2-p16
- Remove redundant label
- Correctly associate label and select
=> fix(a11y): Associate label to `SelectInput` (`DAC_Labels_not_Programmatically_Associated_02`)

e2e/tests/ui-driven/src/helpers/userActions.ts, editor.planx.uk/src/@planx/components/NumberInput/Public.test.tsx, editor.planx.uk/src/@planx/components/NumberInput/Public.tsx
This is aiming to resolve a new "A" issue flagged by the audit - `DAC_Labels_not_Programmatically_Associated_01`
> _The label provided to enable users to identify the purpose of the edit field is not fully programmatically associated with the component. Screen reader users encountering the field ‘out of context’, for example, when filtering the page by element type, will encounter the component as ‘units’. Users would have to switch navigational methods, and search through the surrounding page content in order to identify the purpose of the control._
Trello ticket: https://trello.com/c/7MidNreB/3390-a-labels-not-programmatically-associated-1-p13
I believe this was a regression introduced here - https://github.com/theopensystemslab/planx-new/pull/5020
I'm proposing that we just revert this …
=> fix(a11y):  Number input labels (`DAC_Labels_not_Programmatically_Associated_01`)

editor.planx.uk/src/components/Header/Sections/ProgressBar.tsx, editor.planx.uk/src/pages/FlowEditor/lib/store/navigation.ts, editor.planx.uk/src/pages/Preview/Questions.tsx, editor.planx.uk/src/types.ts
Adds `Progress` object to user's session data.
Required to show progress in LPS. There's no need to read this data within PlanX directly - we can always just calculate it via the store as we do currently.
=> feat: Save progress to flow data

editor.planx.uk/src/pages/FlowEditor/lib/__tests__/computePassport.test.ts, editor.planx.uk/src/pages/FlowEditor/lib/__tests__/mocks/computePassport/flowWithMultipleSetValues.ts, editor.planx.uk/src/pages/FlowEditor/lib/store/preview.ts
It was reported that a user took the following path and was presented with two different final payment amounts on their service -
- Navigate through flow
- Proceed to GovPay
- Cancel payment, return to PlanX
- On return to the pay component, the amount was incorrect ❌ 
Source (ODP Slack): https://opendigitalplanning.slack.com/archives/C07491E8W68/p1755707732186779
After a lot of debugging and head scratching it turned out to be a bug based on the order in which breadcrumbs are processed when calculating a user's passport. In this instance the following was happening - 
- User navigates through journey, reaches the Pay component
- Passport is correct, breadcrumbs are stored in the Zustand store by flow depth / order of questions seen by user
- If you log these values out using …
=> fix: On resume, sort breadcrumbs by depth

ci/caddy/Caddyfile
Attempts to fix CI/pizza builds failing (more often that not!) by extending the `propagation_delay` knob four-fold to 2 minutes (if this doesn't work, we could try extending it further). I'm not convinced this is necessarily the issue, but it will help us rule out Vultr simply taking a long time to provision the requested TXT records.
Relevant ticket: https://trello.com/c/YopMVSYl
=> fix: quadruple caddy `propagation_delay` to 120s

.github/dependabot.yml, editor.planx.uk/package.json, editor.planx.uk/pnpm-lock.yaml, sharedb.planx.uk/package.json, sharedb.planx.uk/pnpm-lock.yaml
Looking into the recently reported ShareDB errors, this seems like a good issue to rule out. 
Notably, we're currently using different versions of ShareDB. I've updated `dependabot.yaml` to ensure these get kept in sync by using [multi-ecosystem groups](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#multi-ecosystem-groups-).
=> chore: Update ShareDB to v5

editor.planx.uk/src/pages/FlowEditor/lib/sharedb.ts
Temp rollback of https://github.com/theopensystemslab/planx-new/pull/5152 as this resulted in a spike in Airbrake logging.
=> fix: Don't log ShareDB errors to Airbrake

editor.planx.uk/src/pages/FlowEditor/components/Flow/components/Hanger.tsx, editor.planx.uk/src/pages/FlowEditor/lib/store/editor.ts
When navigating directly to `:flow/someChild` back to `:flow/` routes, ShareDB is not hit, and flow data is not loaded. 
This triggers a number of errors which rely on flow data - including displaying flow data.
https://github.com/user-attachments/assets/f73f4445-c8c9-46a5-8f1e-1860b3ada206
This appears as a frequent bug on Airbrake, and may be related to the recently reported issues regarding mismatched flow slug and data (this is how I began investigating this one).
Note: This will only appear if `:flow/someChild` is directly navigated to (or refreshed on). Any routing that first goes via `:flow/` will not hit this issue.
Remove the redundant check for an existing flow ID - these predated nested pages. There will be a flow ID in the store if you first visit a child page (e.g. …
=> fix: Flow data does not load when navigating back from child page

api.planx.uk/modules/saveAndReturn/service/resumeApplication.ts, api.planx.uk/modules/saveAndReturn/service/validateSession.ts, hasura.planx.uk/metadata/databases/default/tables/public_lowcal_sessions.yaml, hasura.planx.uk/migrations/default/1756743433814_run_sql_migration/down.sql, hasura.planx.uk/migrations/default/1756743433814_run_sql_migration/up.sql
This PR adds a new `status` [computed field](https://hasura.io/docs/2.0/schema/postgres/computed-fields/) to the `lowcal_sessions` table, and then references it in a few queries. It's very possible that there are a few other examples here I've missed.
This has come up as a good idea a few times - in reference to the complex LPS query, as well as migration scripts. I'm picking this up now as it will enable me to refactor the more LPS query to match the requirements of the new designs.
Regression tests passing here - https://github.com/theopensystemslab/planx-new/actions/runs/17398793228 ✅
=> feat: Create `lowcal_session.status` computed field

editor.planx.uk/src/pages/FlowEditor/ReadMePage/ReadMePage.stories.tsx, editor.planx.uk/src/pages/FlowEditor/components/Settings/ServiceSettings/LPS/LPSListingSection.tsx, editor.planx.uk/src/pages/FlowEditor/components/Settings/ServiceSettings/ServiceSettings.tsx, editor.planx.uk/src/pages/FlowEditor/lib/store/settings.ts, editor.planx.uk/src/pages/FlowEditor/utils.ts, hasura.planx.uk/metadata/databases/default/tables/public_flows.yaml, hasura.planx.uk/migrations/default/1756979341323_alter_table_public_flows_add_column_is_indexed_on_lps/down.sql, hasura.planx.uk/migrations/default/1756979341323_alter_table_public_flows_add_column_is_indexed_on_lps/up.sql, localplanning.services/src/lib/lpa-api/query.ts
Adds to a toggle allowing Editors to control if their service will be listed on LPS, alongside basic validation.
Notably, we still have checks in place on LPS for slugs, so this isn't yet entirely configurable here. The next step would have to be a way within PlanX to categorise a service.
```ts
const NOTIFY_SERVICE_SLUGS = [
"report-a-planning-breach",
"camden-report-a-planning-breach",
];
```
=> feat: Toggle within PlanX allowing users to list services on LPS

hasura.planx.uk/metadata/query_collections.yaml, hasura.planx.uk/metadata/rest_endpoints.yaml
This PR creates a Hasura REST endpoint allowing users to delete their LPS applications, which will be called from the "Delete" button on application cards. The UI is not yet in place for this feature.
This uses the same public permissions as the current "reset" button uses within PlanX when `clearLocalFlow()` is called - https://github.com/theopensystemslab/planx-new/blob/ae460ebeeba3ca526ba23f564e48f0a492ffb54f/editor.planx.uk/src/lib/lowcalStorage.ts#L36-L54
To test - 
- Create a lowcal session record on the Pizza
- Hit `https://api.5195.planx.pizza/api/rest/lps/application/:applicationId` with the required params
Example cURL - 
```sh
curl -X DELETE 'https://hasura.5195.planx.pizza/api/rest/lps/application/<SESSION_ID>' \
-H 'x-hasura-lowcal-session-id: <SESSION_ID>' \
-H …
```
=> feat: Create Hasura REST endpoint to delete session

.github/workflows/push-main.yml, infrastructure/application/Pulumi.staging.yaml, infrastructure/application/services/lps.ts, infrastructure/application/utils/createCDN.ts
- Builds LPS (or refers to existing cache) on deploy to `main` branch
- Creates a bucket to hold static files for the site
- Uploads built site to this bucket
- Created a Cloudfront CDN
Notably, I'm not handling SSL certificates here yet - the output of this should just be a CND at abc123.cloudfront.net for staging and production.
- Deploy to `main`, test that a CDN is created
- Open PR to repeat steps for production
- Handle SSL certs so that these CDNs can live at `localplanning.editor.planx.dev` and `localplanning.services` respectively
- Env vars and CORS - I'll need to set up a value for `LPS_URL_EXT` once certificates are sorted
=> feat(iac): Create staging CDN for localplanning.services 

infrastructure/application/utils/createCDN.ts
Resolves the following issue from the latest staging deploy -
```sh
@ Updating.....
+  aws:s3:Bucket localplanning.editor.planx.dev created (3s) 
aws:cloudfront:OriginAccessIdentity originAccessIdentity **failed** error: Duplicate resource URN 'urn:pulumi:staging::application::aws:cloudfront/originAccessIdentity:OriginAccessIdentity::originAccessIdentity'; try giving it a unique name
+  aws:s3:Bucket lpsRequestLogs created (2s) 
@ Updating....
pulumi:pulumi:Stack application-staging  
Diagnostics:
aws:cloudfront:OriginAccessIdentity (originAccessIdentity):
error: Duplicate resource URN 'urn:pulumi:staging::application::aws:cloudfront/originAccessIdentity:OriginAccessIdentity::originAccessIdentity'; try giving it a unique name
```
=> fix(infra): Ensure we use a unique `OriginAccessIdentity`

infrastructure/application/services/lps.ts
Should resolve this next issue 🔨 
S3 buckets no longer recommend / allow the use of ACLs - the code used for the PlanX frontend which I copied does have this legacy set up in place.
```sh
Diagnostics:
aws:s3:BucketObject (../../localplanning.services/dist/_astro/ApplicationsAuth._JE2sRcZ.js):
error: 1 error occurred:
* Error uploading object to S3 bucket (localplanning.editor.planx.dev): AccessControlListNotSupported: The bucket does not allow ACLs
```
=> fix(infra): Replace ACL with bucket policy

scripts/seed-database/write/flows.sql
We do a `select * from flows` and missed this recently-added column ! 
Data sync scripts will fail with error "Extra data after last expected column" until merged
=> fix: add `flows.is_listed_on_lps` to nightly sync scripts

editor.planx.uk/src/pages/FlowEditor/lib/sharedb.ts
Manually reverts https://github.com/theopensystemslab/planx-new/pull/5123 after new reports of lost edits (3 hours worth). Frequent login has got to be better than silent errors & lost work until we strike right balance here ! 
See https://opensystemslab.slack.com/archives/C088K9ZL8EA/p1757515479421829
=> fix: on unhandled ShareDB errors, re-introduce toast and forced logout to prevent lost edits

infrastructure/application/utils/generateCORSAllowList.ts
Now that the staging site https://localplanning.editor.planx.dev/ is in place, we need to allow it to access to API via CORS.
This is already in place for Pizza ✅ 🍕
=> chore(lps): Configure CORS for LPS staging

localplanning.services/src/pages/[lpa].astro
- Introduces a fallback message for empty service type accordions, when searching for services.
Testing (with `.html` appended due to known build error, unrelated to this PR):
https://localplanning.5246.planx.pizza/lambeth.html
=> feat(lps): Fallback message for empty service accordions

hasura.planx.uk/migrations/default/1730730955039_application_type_as_text_in_view/up.sql, hasura.planx.uk/migrations/default/1748596202549_run_sql_migration/up.sql, hasura.planx.uk/migrations/default/1749120614777_run_sql_migration/down.sql, hasura.planx.uk/migrations/default/1749120614777_run_sql_migration/up.sql, hasura.planx.uk/migrations/default/1756972534375_create_view_templated_flow_update_requests/up.sql
When building the stack on local (including just on latest from `main`), my Hasura console was reporting inconsistent metadata, like so:
I raised this on Slack [here](https://opensystemslab.slack.com/archives/C088K9ZL8EA/p1758024700227139).
After some poking around I eventually noticed that the `up.sql` file for the relevant migration (introduced in #5175) does not explicitly specify the schema to which the view should be applied. The first commit here fixes that.
The second commit is just a minor addendum to ensure that all migrations concerning views are idempotent (i.e. any instance of `CREATE VIEW` is replaced by `CREATE OR REPLACE VIEW`), so will not fail if the view has already been instantiated. This is just good practice but could be discarded if we like. It's mostly a hangover …
=> fix `templated_flow_update_requests` migration script

.github/workflows/pull-request.yml, .github/workflows/push-main.yml, localplanning.services/.env.dev, localplanning.services/.env.pizza, localplanning.services/.env.staging, localplanning.services/astro.config.mjs
A follow up to https://github.com/theopensystemslab/planx-new/pull/5251 as this approach didn't quite work as planned.
This PR now - 
- Passes in a `--site` flag at runtime for the build, so that we don't have to work around env vars in the config file
- Parses `mode` from the runtime build command, so that we can reliably build in `"files"` or `"folder"` mode based on this
This should result in - 
- Proper sitemaps
- Correct routing in dev, pizza (docker) and staging/prod (AWS Cloudfront)
=> fix(lps): Handle site and mode env vars in Astro config

api.planx.uk/modules/lps/service/getApplications/mutation.ts
Hitting an edge case on staging where I have sessions for flows which are now deleted. This is likely the sort of edge case that generally only testers and devs should hit. Without this check the request fails as we're not able to map service name, team name etc.
=> fix: Don't return LPS applications for non-existent flows

api.planx.uk/modules/admin/session/html.test.ts, api.planx.uk/modules/admin/session/html.ts
Quick fix I noticed when working on https://github.com/theopensystemslab/planx-new/pull/5273 🧪
=> test(api): Unskip `/admin/session/:id/html` tests

api.planx.uk/package.json, api.planx.uk/pnpm-lock.yaml, e2e/tests/api-driven/package.json, e2e/tests/api-driven/pnpm-lock.yaml, e2e/tests/ui-driven/package.json, e2e/tests/ui-driven/pnpm-lock.yaml, editor.planx.uk/package.json, editor.planx.uk/pnpm-lock.yaml, editor.planx.uk/src/@planx/components/Pay/Public/FeeBreakdown/FeeBreakdown.tsx
'Relevant demolition' is a fee exemption for various application types exempting the application from any planning fee. When applicable, we want to show this exemption in the fee breakdown.
Unsure if this single line addition covers all our bases. If not, please flag additional req (tests, mocks etc.)!
=> feat: add 'Relevant demolition' to fee breakdown exemptions

infrastructure/application/services/hasura.ts
Fixes the following issue with the `HASURA_GRAPHQL_CORS_DOMAIN` variable on Pulumi -
```sh
Fatal Error:- Environment variable HASURA_GRAPHQL_CORS_DOMAIN: invalid domain: 'localplanning.editor.planx.dev'. All domains should have scheme + (optional wildcard) host + (optional port)
```
=> fix(ci): Correctly prefix CORS domain with https

editor.planx.uk/src/pages/FlowEditor/lib/analytics/utils.ts, editor.planx.uk/src/pages/FlowEditor/lib/store/settings.ts, editor.planx.uk/src/routes/views/flowEditor.tsx
Instead of linking staging / pizzas to empty dashboards on Metabase staging (which has no data), this PR disables analytics links on all non-production environments.
=> feat: only generate analytics link on production

editor.planx.uk/src/pages/FlowEditor/components/Flow/components/Portal.tsx, editor.planx.uk/src/pages/FlowEditor/floweditor.scss
- Extends clone style to folders
- Reposition to bottom to accommodate for folder tab
- Handle focus and visited states
- Increases contrast (border-width) of clone marker
**Testing:**
https://5296.planx.pizza/a-new-team/clones
=> fix: Display clone style for folders

api.planx.uk/modules/admin/session/html.ts, api.planx.uk/modules/lps/service/generateHTML.ts
A dose of healthy paranoia! As we're generating the HTML it _should_ be fine, but better safe than sorry as the underlying data is originally user-provided.
=> chore(api): Sanitise HTML before returning

api.planx.uk/modules/lps/service/getApplications/index.ts, hasura.planx.uk/metadata/databases/default/tables/public_lowcal_sessions.yaml, localplanning.services/src/components/applications/ApplicationCard.tsx, localplanning.services/src/components/applications/ApplicationViewer.tsx, localplanning.services/src/components/applications/hooks/useDeleteApplication.tsx, localplanning.services/src/components/applications/hooks/useFetchApplications.tsx, localplanning.services/src/components/applications/hooks/useHTMLDownload.tsx, localplanning.services/src/pages/applications/[lpa].astro, localplanning.services/src/pages/applications/viewer.astro, localplanning.services/src/stores/applicationId.ts
- Final part of the process laid out here - https://github.com/theopensystemslab/planx-new/pull/5273
- Creates a custom React hook to wrap the `/lps/download/token` and `/lps/download/html` endpoints
- Display this within the LPS Asto application as `application/:lpa` (branded by team)
https://github.com/user-attachments/assets/728670bb-d6c1-49e8-8e8c-4f22c4ba3388
=> feat(lps): Wire up download HTML endpoint, display data within LPS

localplanning.services/src/components/applications/ApplicationCard.tsx, localplanning.services/src/components/applications/ApplicationsList.tsx
ApplicationId persists on back navigation, which doesn't allow user to return to list of applications via the browser "back" button.
Application ID should only be set on click, and we should aggressively clear it when navigating back.
=> fix(lps): Click handler for viewer link

editor.planx.uk/src/pages/FlowEditor/lib/store/settings.ts, editor.planx.uk/src/ui/editor/SettingsSection.tsx
Ensures that `isSubmissionService` is never `undefined`. 
Do we actually need an `ErrorBoundary` as discussed [here](https://opensystemslab.slack.com/archives/C088K9ZL8EA/p1759241431170869?thread_ts=1759240207.118589&cid=C088K9ZL8EA)? I took a look at it but since `flowInformation` was being accessed before any components were being rendered, the `ReadMePage` page would have broken before getting to the `ErrorBoundary` anyway.
=> chore: make hasSendComponent check more defensive

e2e/tests/ui-driven/src/helpers/addComponent.ts, e2e/tests/ui-driven/src/pages/Editor.ts, editor.planx.uk/src/pages/FlowEditor/lib/store/editor.ts
Came up as a suggestion at roadmap!
This PR will enable tags and data values by default on the graph view.
=> feat: Enable tags and data fields by default on the graph

editor.planx.uk/src/pages/FlowEditor/components/Sidebar/Review/ReviewCard.tsx, editor.planx.uk/src/pages/FlowEditor/components/Sidebar/Review/index.tsx, editor.planx.uk/src/pages/FlowEditor/components/Sidebar/index.tsx, editor.planx.uk/src/pages/FlowEditor/lib/store/navigation.ts
This PR adds a 'To review' tab to the sidebar that lists all nodes in the current flow tagged 'To review'. It displays them together with any 'Internal notes' on the node.
The tab helps editors to more easily find and navigate to nodes in need of reviewing. Internal notes are displayed because these are currently used by editors to provide context on what is to be reviewed.
The tab does not display on flows that are _templated_.
To be revised during future development of a wider in-editor notification and user tagging system.
=> feat: add 'To review' tab to sidebar

editor.planx.uk/src/pages/FlowEditor/lib/analytics/utils.ts
A tiny fix for a tiny mistake I made in #5313 that meant production analytics links were sending people to non-existent Metabase staging dashboards..!
=> fix: use metabase prod link for analytics
